import { getCode } from "../getCode";
import { Component } from "../types";

// All mega menu components from the library
// Total: 30 components (15 from MegaMenus + 15 from MegaMenus2)

export const megaMenuComponents: Component[] = [
    // From MegaMenus (first 15)
    {
        id: "nebula",
        name: "Nebula",
        description: "Glassmorphism mega menu with noise textures and blur effects for a cosmic aesthetic.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["glassmorphism", "noise", "blur", "cosmic"],
        previewUrl: "/Navigation&Structures/MegaMenus/Nebula",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Nebula.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Nebula.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Nebula/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "brandName", type: "string", default: '"NEBULA"', description: "Brand name displayed in the navigation." },
            { name: "navItems", type: "string[]", default: '["Products", "Pricing"]', description: "Array of navigation item labels." },
            { name: "menuItems", type: "Array<{title: string, desc: string}>", default: "[]", description: "Array of menu items with title and description." },
            { name: "backgroundColor", type: "string", default: '"#171717"', description: "Background color (hex, rgb, or hsl)." },
            { name: "navBgColor", type: "string", default: '"rgba(255,255,255,0.05)"', description: "Navigation background color." },
            { name: "menuBgColor", type: "string", default: '"rgba(0,0,0,0.4)"', description: "Menu dropdown background color." },
        ],
    },
    {
        id: "cyberdeck",
        name: "Cyberdeck",
        description: "Cyberpunk-inspired mega menu with glitch effects and neon aesthetics.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["cyberpunk", "glitch", "neon", "futuristic"],
        previewUrl: "/Navigation&Structures/MegaMenus/Cyberdeck",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Cyberdeck.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Cyberdeck.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Cyberdeck/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "menuTitle", type: "string", default: '"Netrun_v2"', description: "Menu title text." },
            { name: "columns", type: "Array<{title: string, items: string[]}>", default: "[]", description: "Array of menu columns with title and items." },
            { name: "backgroundColor", type: "string", default: '"#050505"', description: "Background color (hex, rgb, or hsl)." },
            { name: "navBgColor", type: "string", default: '"#facc15"', description: "Navigation button background color." },
            { name: "menuBorderColor", type: "string", default: '"#facc15"', description: "Menu border color." },
            { name: "itemHoverColor", type: "string", default: '"#22d3ee"', description: "Item hover text color." },
        ],
    },
    {
        id: "brutalist",
        name: "Brutalist",
        description: "Neo-brutalist mega menu with bold typography and high contrast design.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["brutalist", "bold", "typography", "high-contrast"],
        previewUrl: "/Navigation&Structures/MegaMenus/Brutalist",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Brutalist.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Brutalist.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Brutalist/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "openButtonText", type: "string", default: '"Open Menu"', description: "Text for the open button." },
            { name: "categories", type: "string[]", default: '["Digital Art", "Collectibles", "Music", "Photography"]', description: "Array of category labels." },
            { name: "backgroundColor", type: "string", default: '"#E0E7FF"', description: "Background color (hex, rgb, or hsl)." },
            { name: "buttonBgColor", type: "string", default: '"#FF6B6B"', description: "Button background color." },
            { name: "menuBgColor", type: "string", default: '"#ffffff"', description: "Menu background color." },
            { name: "menuBorderColor", type: "string", default: '"#000000"', description: "Menu border color." },
        ],
    },
    {
        id: "velvet",
        name: "Velvet",
        description: "Luxurious velvet-textured mega menu with smooth animations and elegant design.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["velvet", "luxury", "smooth", "elegant"],
        previewUrl: "/Navigation&Structures/MegaMenus/Velvet",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Velvet.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Velvet.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Velvet/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "navText", type: "string", default: '"Collections"', description: "Navigation trigger text." },
            { name: "items", type: "Array<{name: string, bgColor?: string}>", default: "[]", description: "Array of menu items with name and optional background color." },
            { name: "backgroundColor", type: "string", default: '"#0a0a0a"', description: "Background color (hex, rgb, or hsl)." },
            { name: "menuBgColor", type: "string", default: '"#0a0a0a"', description: "Menu background color." },
            { name: "itemTitleColor", type: "string", default: '"#ffffff"', description: "Item title text color." },
        ],
    },
    {
        id: "sketchbook",
        name: "Sketchbook",
        description: "Hand-drawn sketchy mega menu with artistic aesthetics and organic lines.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["sketch", "hand-drawn", "artistic", "organic"],
        previewUrl: "/Navigation&Structures/MegaMenus/Sketchbook",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Sketchbook.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Sketchbook.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Sketchbook/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttonText", type: "string", default: '"Navigation"', description: "Button text." },
            { name: "items", type: "Array<{title: string}>", default: "[]", description: "Array of chapter items." },
            { name: "backgroundColor", type: "string", default: '"#fffbf0"', description: "Background color (hex, rgb, or hsl)." },
            { name: "buttonBgColor", type: "string", default: '"#ffffff"', description: "Button background color." },
            { name: "itemTextColor", type: "string", default: '"#000000"', description: "Item text color." },
        ],
    },
    {
        id: "terminal",
        name: "Terminal",
        description: "Retro terminal-style mega menu with monospace typography and command-line aesthetics.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["terminal", "retro", "monospace", "command-line"],
        previewUrl: "/Navigation&Structures/MegaMenus/Terminal",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Terminal.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Terminal.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Terminal/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttonPrefix", type: "string", default: '"$"', description: "Command prefix character." },
            { name: "buttonCommand", type: "string", default: '"./open_menu.sh"', description: "Command text." },
            { name: "links", type: "Array<{label: string}>", default: "[]", description: "Array of navigation links." },
            { name: "backgroundColor", type: "string", default: '"#1a1a1a"', description: "Background color (hex, rgb, or hsl)." },
            { name: "buttonTextColor", type: "string", default: '"#22c55e"', description: "Button text color." },
            { name: "menuBgColor", type: "string", default: '"#0d0d0d"', description: "Menu background color." },
        ],
    },
    {
        id: "magazine",
        name: "Magazine",
        description: "Editorial-style mega menu with magazine layout and content-focused design.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["editorial", "magazine", "layout", "content"],
        previewUrl: "/Navigation&Structures/MegaMenus/Magazine",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Magazine.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Magazine.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Magazine/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "brandName", type: "string", default: '"VOGUE.UI"', description: "Brand name displayed in header." },
            { name: "leftItems", type: "string[]", default: '["Fashion", "Beauty", "Culture", "Living"]', description: "Array of left column menu items." },
            { name: "imageUrl", type: "string", default: "''", description: "URL for the featured image." },
            { name: "backgroundColor", type: "string", default: '"#fdfdfd"', description: "Background color (hex, rgb, or hsl)." },
            { name: "brandColor", type: "string", default: '"#000000"', description: "Brand name text color." },
        ],
    },
    {
        id: "liquida",
        name: "Liquid",
        description: "Organic liquid-style mega menu with fluid animations and morphing shapes.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["liquid", "organic", "fluid", "morphing"],
        previewUrl: "/Navigation&Structures/MegaMenus/Liquid",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Liquid.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Liquid.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Liquid/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "items", type: "string[]", default: '["About", "Works", "Contact", "Store"]', description: "Array of menu item labels." },
            { name: "backgroundColor", type: "string", default: '"#e8f4f8"', description: "Background color (hex, rgb, or hsl)." },
            { name: "buttonBgColor", type: "string", default: '"#4facfe"', description: "Button background color." },
            { name: "menuBgColor", type: "string", default: '"#4facfe"', description: "Menu background color." },
            { name: "itemTextColor", type: "string", default: '"#ffffff"', description: "Item text color." },
        ],
    },
    {
        id: "origami",
        name: "Origami",
        description: "Paper-folded origami-style mega menu with geometric transformations.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["origami", "paper", "fold", "geometric"],
        previewUrl: "/Navigation&Structures/MegaMenus/Origami",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Origami.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Origami.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Origami/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttonText", type: "string", default: '"Unfold"', description: "Button text." },
            { name: "items", type: "Array<{title: string, delay?: number}>", default: "[]", description: "Array of menu items with title and optional delay." },
            { name: "backgroundColor", type: "string", default: '"#2C3E50"', description: "Background color (hex, rgb, or hsl)." },
            { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
            { name: "menuItemBgColor", type: "string", default: '"#ECF0F1"', description: "Menu item background color." },
        ],
    },
    {
        id: "dynamic-island",
        name: "Dynamic Island",
        description: "Fluid morphing mega menu inspired by iOS Dynamic Island with smooth transitions.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["dynamic-island", "morphing", "fluid", "ios"],
        previewUrl: "/Navigation&Structures/MegaMenus/DynamicIsland",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/DynamicIsland.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/DynamicIsland.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/DynamicIsland/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "closedText", type: "string", default: '"Navigation"', description: "Text shown when menu is closed." },
            { name: "closedWidth", type: "number", default: "180", description: "Width of closed menu in pixels." },
            { name: "openWidth", type: "number", default: "800", description: "Width of open menu in pixels." },
            { name: "items", type: "Array<{title: string, icon: ReactNode, color?: string}>", default: "[]", description: "Array of menu items." },
            { name: "islandBgColor", type: "string", default: '"#000000"', description: "Island background color." },
        ],
    },
    {
        id: "spotlight",
        name: "Spotlight",
        description: "Mouse-tracking spotlight mega menu with reveal effects and interactive design.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["spotlight", "mouse-tracking", "reveal", "interactive"],
        previewUrl: "/Navigation&Structures/MegaMenus/Spotlight",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Spotlight.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Spotlight.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Spotlight/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttonText", type: "string", default: '"Reveal"', description: "Button trigger text." },
            { name: "leftColumnItems", type: "string[]", default: '["Intelligence", "Security", "Quantum", "Cloud"]', description: "Array of left column items." },
            { name: "backgroundColor", type: "string", default: '"#050505"', description: "Background color (hex, rgb, or hsl)." },
            { name: "menuBgColor", type: "string", default: '"#171717"', description: "Menu background color." },
            { name: "spotlightColor", type: "string", default: '"rgba(255,255,255,0.15)"', description: "Spotlight effect color." },
        ],
    },
    {
        id: "bauhaus",
        name: "Bauhaus",
        description: "Bauhaus-inspired mega menu with geometric shapes and modernist design principles.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["bauhaus", "geometric", "modernist", "shapes"],
        previewUrl: "/Navigation&Structures/MegaMenus/Bauhaus",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Bauhaus.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Bauhaus.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Bauhaus/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttonText", type: "string", default: '"Bauhaus"', description: "Button text." },
            { name: "backgroundColor", type: "string", default: '"#f4f1ea"', description: "Background color (hex, rgb, or hsl)." },
            { name: "buttonBgColor", type: "string", default: '"#1a1a1a"', description: "Button background color." },
            { name: "menuBgColor", type: "string", default: '"#1a1a1a"', description: "Menu background color." },
            { name: "largeCardBgColor", type: "string", default: '"#fcb900"', description: "Large card background color." },
        ],
    },
    {
        id: "blueprint",
        name: "Blueprint",
        description: "Technical blueprint-style mega menu with architectural line drawings and grid patterns.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["blueprint", "technical", "architectural", "grid"],
        previewUrl: "/Navigation&Structures/MegaMenus/Blueprint",
        code: {
            tsx: "",
        },
        usageCode: {
            tsx: "",
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttonText", type: "string", default: '"[ SYSTEM_MENU ]"', description: "Button text." },
            { name: "columns", type: "Array<{title: string, items: string[]}>", default: "[]", description: "Array of menu columns." },
            { name: "backgroundColor", type: "string", default: '"#004a99"', description: "Background color (hex, rgb, or hsl)." },
            { name: "gridPatternColor", type: "string", default: '"#ffffff"', description: "Grid pattern color." },
            { name: "menuBgColor", type: "string", default: '"rgba(0,51,102,0.9)"', description: "Menu background color." },
        ],
    },
    {
        id: "orbit",
        name: "Orbit",
        description: "Orbital navigation mega menu with circular motion and space-themed design.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["orbit", "circular", "space", "motion"],
        previewUrl: "/Navigation&Structures/MegaMenus/Orbit",
        code: {
            tsx: "",
        },
        usageCode: {
            tsx: "",
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttonIcon", type: "ReactNode", default: "<Grid />", description: "Icon component for the button." },
            { name: "items", type: "Array<{icon: ReactNode, label: string}>", default: "[]", description: "Array of orbital items with icons and labels." },
            { name: "backgroundColor", type: "string", default: '"#0f172a"', description: "Background color (hex, rgb, or hsl)." },
            { name: "buttonBgGradientFrom", type: "string", default: '"#06b6d4"', description: "Button gradient start color." },
            { name: "itemRadius", type: "number", default: "180", description: "Orbit radius in pixels." },
        ],
    },
    {
        id: "cinema",
        name: "Cinema",
        description: "Cinematic mega menu with film strip aesthetics and dramatic transitions.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["cinema", "film", "dramatic", "transitions"],
        previewUrl: "/Navigation&Structures/MegaMenus/Cinema",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Cinema.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Cinema.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Cinema/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "brandName", type: "string", default: '"STREAM."', description: "Brand name displayed in navigation." },
            { name: "navItems", type: "string[]", default: '["Movies", "Series", "New", "List"]', description: "Array of navigation item labels." },
            { name: "movies", type: "Array<{title: string, gradientFrom?: string, gradientTo?: string}>", default: "[]", description: "Array of movie objects with title and gradients." },
            { name: "backgroundColor", type: "string", default: '"#000000"', description: "Background color (hex, rgb, or hsl)." },
            { name: "cardTitleColor", type: "string", default: '"#ffffff"', description: "Card title text color." },
        ],
    },
    {
        id: "swiss-grid",
        name: "Swiss Grid",
        description: "Swiss design-inspired mega menu with precise grid layout and typography.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["swiss", "grid", "precise", "typography"],
        previewUrl: "/Navigation&Structures/MegaMenus/SwissGrid",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/SwissGrid.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/SwissGrid.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/SwissGrid/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "brandName", type: "string", default: '"HELVETICA."', description: "Brand name displayed in header." },
            { name: "items", type: "Array<{num: string, title: string, description?: string}>", default: "[]", description: "Array of grid items with number, title, and description." },
            { name: "backgroundColor", type: "string", default: '"#f0f0f0"', description: "Background color (hex, rgb, or hsl)." },
            { name: "menuBgColor", type: "string", default: '"#f0f0f0"', description: "Menu background color." },
            { name: "itemHoverBgColor", type: "string", default: '"#000000"', description: "Item hover background color." },
        ],
    },
    {
        id: "neumorph",
        name: "Neumorph",
        description: "Neumorphic mega menu with soft shadows and tactile design elements.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["neumorph", "soft", "shadows", "tactile"],
        previewUrl: "/Navigation&Structures/MegaMenus/Neumorph",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Neumorph.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Neumorph.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Neumorph/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttons", type: "Array<{label: string, icon: ReactNode}>", default: "[]", description: "Array of navigation buttons." },
            { name: "options", type: "string[]", default: '["Option 1", "Option 2", "Option 3"]', description: "Array of menu option labels." },
            { name: "backgroundColor", type: "string", default: '"#e0e5ec"', description: "Background color (hex, rgb, or hsl)." },
            { name: "navBgColor", type: "string", default: '"#e0e5ec"', description: "Navigation background color." },
            { name: "buttonActiveColor", type: "string", default: '"#3b82f6"', description: "Active button color." },
        ],
    },
    {
        id: "accordion",
        name: "Accordion",
        description: "Accordion-style mega menu with expandable sections and smooth animations.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["accordion", "expandable", "sections", "smooth"],
        previewUrl: "/Navigation&Structures/MegaMenus/Accordion",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Accordion.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Accordion.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Accordion/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "items", type: "Array<{title: string, bg?: string, description?: string}>", default: "[]", description: "Array of accordion items with title, background, and description." },
            { name: "backgroundColor", type: "string", default: '"#171717"', description: "Background color (hex, rgb, or hsl)." },
            { name: "containerHeight", type: "string", default: '"400px"', description: "Container height." },
            { name: "defaultHoveredWidth", type: "string", default: '"55%"', description: "Width when item is hovered." },
            { name: "inactiveWidth", type: "string", default: '"25%"', description: "Width when no item is hovered." },
        ],
    },
    {
        id: "variable-type",
        name: "Variable Type",
        description: "Variable typography mega menu with dynamic font weights and fluid text.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["variable", "typography", "dynamic", "fluid"],
        previewUrl: "/Navigation&Structures/MegaMenus/VariableType",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/VariableType.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/VariableType.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/VariableType/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttonText", type: "string", default: '"Menu"', description: "Button trigger text." },
            { name: "items", type: "string[]", default: '["Studio", "Work", "Agency", "Contact"]', description: "Array of menu item labels." },
            { name: "backgroundColor", type: "string", default: '"#ffffff"', description: "Background color (hex, rgb, or hsl)." },
            { name: "itemTextColor", type: "string", default: '"#000000"', description: "Item text color." },
            { name: "itemHoverWeight", type: "number", default: "900", description: "Font weight on hover." },
        ],
    },
    {
        id: "sidekick",
        name: "Sidekick",
        description: "Vertical sidebar mega menu with compact design and efficient navigation.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["sidekick", "vertical", "sidebar", "compact"],
        previewUrl: "/Navigation&Structures/MegaMenus/Sidekick",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Sidekick.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Sidekick.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Sidekick/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "items", type: "string[]", default: '["Collections", "New Arrivals", "Accessories", "Editorial"]', description: "Array of menu item labels." },
            { name: "footerLinks", type: "string[]", default: '["Instagram", "Twitter", "LinkedIn"]', description: "Array of footer social links." },
            { name: "backgroundColor", type: "string", default: '"#f5f5f5"', description: "Background color (hex, rgb, or hsl)." },
            { name: "drawerWidth", type: "string", default: '"400px"', description: "Drawer width." },
            { name: "itemTextColor", type: "string", default: '"#a3a3a3"', description: "Item text color." },
        ],
    },
    {
        id: "biome",
        name: "Biome",
        description: "Biome-themed mega menu with organic nature-inspired design and natural aesthetics.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["biome", "organic", "nature", "natural"],
        previewUrl: "/Navigation&Structures/MegaMenus/Biome",
        code: {
            tsx: getCode("src/components/Navigation&Structures/MegaMenus/tsx/Biome.tsx"),
            jsx: getCode("src/components/Navigation&Structures/MegaMenus/jsx/Biome.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Navigation&Structures/MegaMenus/Biome/page.tsx"),
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "buttonText", type: "string", default: '"Explore Nature"', description: "Button text." },
            { name: "sidebarTitle", type: "string", default: '"The Biome"', description: "Sidebar title text." },
            { name: "items", type: "Array<{title: string, icon?: ReactNode, iconColor?: string}>", default: "[]", description: "Array of menu items." },
            { name: "backgroundColor", type: "string", default: '"#F1F7F0"', description: "Background color (hex, rgb, or hsl)." },
            { name: "buttonBgColor", type: "string", default: '"#3A5A40"', description: "Button background color." },
            { name: "menuWidth", type: "string", default: '"700px"', description: "Menu width." },
        ],
    },
];
