import { Component } from "../types";

export const bentoGridComponentsMetadata: Component[] = [
    {
        id: "layout-editorial",
        name: "Editorial Layout",
        description: "Asymmetric fashion-inspired bento grid with sharp edges and editorial styling.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "editorial", "fashion", "asymmetric"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "heroImageSrc", type: "string", default: "https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?q=80&w=2070&auto=format&fit=crop", description: "Hero image source URL." },
            { name: "heroImageAlt", type: "string", default: "Editorial", description: "Hero image alt text." },
            { name: "heroTitle", type: "string", default: "Collection 001", description: "Hero section title." },
            { name: "heroDescription", type: "string", default: "Exploring the intersection of brutalism and organic growth through digital mediums.", description: "Hero section description." },
            { name: "stats", type: "Array<{value: string, label: string}>", default: "[{value: '84.2K', label: 'Active Users'}, {value: '12.5%', label: 'Growth Rate'}, {value: '0.02s', label: 'Latency'}]", description: "Array of stat objects with value and label." },
            { name: "statsButtonText", type: "string", default: "View Report", description: "Stats section button text." },
            { name: "audioFileName", type: "string", default: "Audio_Viz.wav", description: "Audio visualization file name." },
            { name: "quote", type: "string", default: "Design is intelligence made visible.", description: "Quote text." },
            { name: "quoteColor", type: "string", default: "#000000", description: "Quote text color (hex, rgb, or hsl)." },
            { name: "bottomTitle", type: "string", default: "The Process", description: "Bottom section title." },
            { name: "bottomDescription", type: "string", default: "A systematic approach to creative problem-solving.", description: "Bottom section description." },
            { name: "bottomAvatars", type: "number[]", default: "[1, 2, 3, 4]", description: "Array of avatar seed numbers for profile images." },
            { name: "techText", type: "string", default: "React • TypeScript • Next.js", description: "Technology stack text." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "layout-swiss",
        name: "Swiss Layout",
        description: "Clean Swiss design bento grid with precise typography and minimal aesthetics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "swiss", "minimal", "typography"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutSwiss",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "headerTitle", type: "string", default: "HELVETICA", description: "Header title text." },
            { name: "headerYear", type: "string", default: "(1957)", description: "Header year text." },
            { name: "mainTitle", type: "string", default: "Objective Clarity", description: "Main section title." },
            { name: "mainDescription", type: "string", default: "The typeface was designed with a neutral disposition, having great clarity, no intrinsic meaning in its form, and could be used on a wide variety of signage.", description: "Main section description." },
            { name: "weightLabel", type: "string", default: "Weight", description: "Weight selector label." },
            { name: "weightOptions", type: "string[]", default: "['Light', 'Regular', 'Bold']", description: "Array of weight option strings." },
            { name: "styleLabel", type: "string", default: "Style", description: "Style selector label." },
            { name: "downloadText", type: "string", default: "Download", description: "Download button text." },
            { name: "bottomSquare1Text", type: "string", default: "Aa", description: "Bottom left square text." },
            { name: "bottomSquare2Text", type: "string", default: "R", description: "Bottom right square text." },
            { name: "bottomWideLabel", type: "string", default: "FIG. 04 — GRID SYSTEM", description: "Bottom wide section label." },
            { name: "backgroundColor", type: "string", default: "#f2f2f2", description: "Background color (hex, rgb, or hsl)." },
            { name: "accentColor", type: "string", default: "#ff3b30", description: "Accent color for highlights (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "layout-neo-brutal",
        name: "Neo-Brutal Layout",
        description: "Bold neo-brutalist bento grid with chunky borders and vibrant colors.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "neo-brutal", "bold", "colorful"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutNeoBrutal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "mainTitle", type: "string", default: "Make It Pop!", description: "Main title text (supports for line breaks)." },
            { name: "mainSubtitle", type: "string", default: "", description: "Main subtitle text." },
            { name: "warningText", type: "string", default: "WARNING: LOUD DESIGN", description: "Warning text displayed in header." },
            { name: "navItems", type: "string[]", default: "['Works', 'About', 'Shop', 'Contact']", description: "Array of navigation item strings." },
            { name: "feature1Title", type: "string", default: "COMMAND", description: "First feature card title." },
            { name: "feature1Description", type: "string", default: "Take Control.", description: "First feature card description." },
            { name: "feature2Title", type: "string", default: "SECURE", description: "Second feature card title." },
            { name: "feature3Percentage", type: "string", default: "99%", description: "Third feature card percentage value." },
            { name: "marqueeItems", type: "string[]", default: "['START A PROJECT', '★', 'BOOK A CALL']", description: "Array of marquee scrolling items." },
            { name: "backgroundColor", type: "string", default: "#B8C0FF", description: "Background color (hex, rgb, or hsl)." },
            { name: "headerColor", type: "string", default: "#FF90E8", description: "Header section color (hex, rgb, or hsl)." },
            { name: "sidebarColor", type: "string", default: "#FFC900", description: "Sidebar section color (hex, rgb, or hsl)." },
            { name: "feature2Color", type: "string", default: "#23A094", description: "Second feature card color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "layout-obsidian",
        name: "Obsidian Layout",
        description: "Dark mode bento grid with obsidian styling and glowing accents.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "obsidian", "dark", "glow"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutObsidian",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "mainTitle", type: "string", default: "Neural\Engine", description: "Main title text (supports \ for line breaks)." },
            { name: "mainIcon", type: "React.ReactNode", default: "", description: "Main icon component (optional)." },
            { name: "mainDescription", type: "string", default: "Processing matrix loaded.", description: "Main description text." },
            { name: "mainBars", type: "number", default: "4", description: "Number of progress bars to display." },
            { name: "securityStatus", type: "string", default: "Protected", description: "Security status text." },
            { name: "securityStatusText", type: "string", default: "Protected", description: "Security status description." },
            { name: "stackLabel", type: "string", default: "Stack", description: "Stack section label." },
            { name: "performanceValue", type: "string", default: "240hz", description: "Performance value display." },
            { name: "coreLinkTitle", type: "string", default: "Core Link", description: "Core link section title." },
            { name: "coreLinkDescription", type: "string", default: "Establishing connection...", description: "Core link section description." },
            { name: "accentColor", type: "string", default: "indigo", description: "Accent color theme (Tailwind color name or hex)." },
            { name: "gradientFrom", type: "string", default: "indigo-500", description: "Gradient start color (Tailwind color name)." },
            { name: "gradientTo", type: "string", default: "purple-600", description: "Gradient end color (Tailwind color name)." },
        ],
    },
    {
        id: "layout-fluid",
        name: "Fluid Layout",
        description: "Fluid animated bento grid with smooth transitions and organic shapes.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "fluid", "animated", "organic"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutFluid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{id: string, title: string, color: string, span: string}>", default: "[{id: '1', title: 'Photography', color: 'bg-rose-500', span: 'col-span-1 row-span-1'}, ...]", description: "Array of grid items with id, title, color (Tailwind class), and span (grid span classes)." },
            { name: "backgroundColor", type: "string", default: "bg-slate-50", description: "Background color (Tailwind class or hex)." },
            { name: "expandedDescription", type: "function", default: "(title: string) => `A deeper dive into the world of ${title.toLowerCase()}...`", description: "Function that returns expanded description text based on item title." },
            { name: "expandedButtonText", type: "string", default: "Explore Collection", description: "Text for the expanded view button." },
        ],
    },
    {
        id: "layout-sketch-brutal",
        name: "Sketch Brutal Layout",
        description: "Rough sketch-style bento grid with hand-drawn aesthetics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "sketch", "rough", "hand-drawn"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutSketchBrutal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "heroTitle", type: "string", default: "ROUGH", description: "Hero section title." },
            { name: "heroSubtitle", type: "string", default: "DRAFT", description: "Hero section subtitle." },
            { name: "heroBadge", type: "string", default: "WIP", description: "Hero section badge text." },
            { name: "sideCard1Icon", type: "React.ReactNode", default: "", description: "First side card icon component (optional)." },
            { name: "sideCard1Title", type: "string", default: "SKETCH", description: "First side card title." },
            { name: "sideCard2Icon", type: "React.ReactNode", default: "", description: "Second side card icon component (optional)." },
            { name: "sideCard2Title", type: "string", default: "BRUTAL", description: "Second side card title." },
            { name: "bottomLeftQuote", type: "string", default: "Imperfection is beauty.", description: "Bottom left section quote text." },
            { name: "bottomLeftAvatars", type: "number", default: "4", description: "Number of avatar images to display in bottom left." },
            { name: "bottomRightText", type: "string", default: "WORK IN PROGRESS", description: "Bottom right section text." },
            { name: "backgroundColor", type: "string", default: "#f5f5f0", description: "Background color (hex, rgb, or hsl)." },
            { name: "heroColor", type: "string", default: "#ff6b6b", description: "Hero section color (hex, rgb, or hsl)." },
            { name: "sideCard1Color", type: "string", default: "#4ecdc4", description: "First side card color (hex, rgb, or hsl)." },
            { name: "sideCard2Color", type: "string", default: "#ffe66d", description: "Second side card color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "layout-silk-void",
        name: "Silk Void Layout",
        description: "Minimalist bento grid with silk-like textures and void spaces.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "silk", "void", "minimal"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutSilkVoid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "mainTitle", type: "string", default: "Ethereal\Resonance", description: "Main title text (supports \ for line breaks)." },
            { name: "mainIcon", type: "React.ReactNode", default: "", description: "Main icon component (optional)." },
            { name: "frequencyLabel", type: "string", default: "Frequency", description: "Frequency label text." },
            { name: "frequencyValue", type: "string", default: "432Hz", description: "Frequency value display." },
            { name: "loadingLabel", type: "string", default: "Loading State", description: "Loading state label text." },
            { name: "element1Icon", type: "React.ReactNode", default: "", description: "First element icon component (optional)." },
            { name: "element1Label", type: "string", default: "Air", description: "First element label text." },
            { name: "element2Icon", type: "React.ReactNode", default: "", description: "Second element icon component (optional)." },
            { name: "element2Label", type: "string", default: "Flow", description: "Second element label text." },
            { name: "backgroundColor", type: "string", default: "#050505", description: "Background color (hex, rgb, or hsl)." },
            { name: "meshColor1", type: "string", default: "purple-900", description: "First mesh gradient color (Tailwind color name)." },
            { name: "meshColor2", type: "string", default: "blue-900", description: "Second mesh gradient color (Tailwind color name)." },
            { name: "accentColor1", type: "string", default: "purple-300", description: "First accent color (Tailwind color name)." },
            { name: "accentColor2", type: "string", default: "blue-300", description: "Second accent color (Tailwind color name)." },
        ],
    },
    {
        id: "layout-soft-clay",
        name: "Soft Clay Layout",
        description: "Soft clay-inspired bento grid with rounded corners and earthy tones.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "clay", "soft", "rounded"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutSoftClay",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "mainTitle", type: "string", default: "Soft Touch", description: "Main card title text." },
            { name: "mainIcon", type: "React.ReactNode", default: "", description: "Main icon component (optional)." },
            { name: "balanceLabel", type: "string", default: "Balance", description: "Balance card label text." },
            { name: "balanceValue", type: "string", default: "$12,450", description: "Balance card value display." },
            { name: "storageTitle", type: "string", default: "Storage", description: "Storage card title text." },
            { name: "storagePercentage", type: "number", default: "60", description: "Storage percentage value (0-100)." },
            { name: "storageLabel", type: "string", default: "60% Used", description: "Storage card label text." },
            { name: "backgroundColor", type: "string", default: "#e0e5ec", description: "Background color (hex, rgb, or hsl)." },
            { name: "accentColor", type: "string", default: "blue-500", description: "Accent color (Tailwind color name or hex)." },
        ],
    },
    {
        id: "layout-wabi-sabi",
        name: "Wabi Sabi Layout",
        description: "Japanese-inspired bento grid with wabi-sabi aesthetics and imperfections.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "wabi-sabi", "japanese", "imperfect"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutWabiSabi",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "imageSrc", type: "string", default: "https://images.unsplash.com/photo-1542885421-3fb3de1f9f0b?q=80&w=686&auto=format&fit=crop", description: "Main image source URL." },
            { name: "imageAlt", type: "string", default: "Stone", description: "Main image alt text." },
            { name: "imageTitle", type: "string", default: "Silence", description: "Image title overlay text." },
            { name: "quote", type: "string", default: "Nothing lasts, nothing is finished, and nothing is perfect.", description: "Quote text." },
            { name: "colorBlockIcon", type: "React.ReactNode", default: "", description: "Color block icon component (optional)." },
            { name: "detailNumber", type: "string", default: "01", description: "Detail section number." },
            { name: "detailText", type: "string", default: "Embrace the beauty of the incomplete.", description: "Detail section text." },
            { name: "bottomTitle", type: "string", default: "The Collection", description: "Bottom card title text." },
            { name: "bottomSubtitle", type: "string", default: "Spring / Summer 2025", description: "Bottom card subtitle text." },
            { name: "backgroundColor", type: "string", default: "#E6E4DC", description: "Background color (hex, rgb, or hsl)." },
            { name: "colorBlockColor", type: "string", default: "#4A5D4F", description: "Color block background color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#AFA99E", description: "Border color (hex, rgb, or hsl)." },
            { name: "textColor", type: "string", default: "#3E3D38", description: "Text color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "layout-cyber-flux",
        name: "Cyber Flux Layout",
        description: "High-tech bento grid with neon accents and holographic effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "cyber", "neon", "holographic"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutCyberFlux",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "mainTitle", type: "string", default: "Mainframe Access", description: "Main card title text." },
            { name: "statusBadges", type: "string[]", default: "['SYS_READY']", description: "Array of status badge strings." },
            { name: "version", type: "string", default: "V.9.0", description: "Version number text." },
            { name: "chartData", type: "number[]", default: "[40, 60, 30, 80, 50, 90, 20, 40, 70, 60]", description: "Array of numbers for chart visualization (0-100)." },
            { name: "voiceCommandLabel", type: "string", default: "Voice Command", description: "Voice command card label." },
            { name: "encryptionType", type: "string", default: "AES-256", description: "Encryption type display text." },
            { name: "deployTitle", type: "string", default: "Deploy Module", description: "Deploy card title." },
            { name: "deployDescription", type: "string", default: "Initiating sequence alpha-01", description: "Deploy card description." },
            { name: "buttonText", type: "string", default: "EXECUTE", description: "Deploy button text." },
            { name: "accentColor", type: "string", default: "cyan", description: "Accent color theme: 'cyan', 'purple', 'blue', 'green', or 'pink'." },
            { name: "backgroundColor", type: "string", default: "neutral-950", description: "Background color (Tailwind color name or hex)." },
        ],
    },
    {
        id: "layout-botanic",
        name: "Botanic Layout",
        description: "Organic bento grid with botanical themes and curved shapes.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "botanic", "organic", "curved"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutBotanic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "imageSrc", type: "string", default: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1527&auto=format&fit=crop", description: "Main image source URL." },
            { name: "imageAlt", type: "string", default: "Plants", description: "Main image alt text." },
            { name: "title", type: "string", default: "Monstera", description: "Main card title text." },
            { name: "description", type: "string", default: "Exploring the fractal patterns found in deep jungle flora.", description: "Main card description text." },
            { name: "label", type: "string", default: "Scientific Name", description: "Top pill label text." },
            { name: "value", type: "string", default: "Deliciosa", description: "Top pill value text." },
            { name: "bottomLeftText", type: "string", default: "Rare Species", description: "Bottom left card text (supports  for line breaks)." },
            { name: "percentage", type: "string", default: "98%", description: "Bottom right card percentage value." },
            { name: "percentageLabel", type: "string", default: "Oxygen", description: "Bottom right card label text." },
            { name: "backgroundColor", type: "string", default: "#f4f7f2", description: "Background color (hex, rgb, or hsl)." },
            { name: "primaryColor", type: "string", default: "#1a3c28", description: "Primary color for main elements (hex, rgb, or hsl)." },
            { name: "secondaryColor", type: "string", default: "#dcead8", description: "Secondary color for accents (hex, rgb, or hsl)." },
            { name: "lightColor", type: "string", default: "#e6f0e9", description: "Light color for text overlays (hex, rgb, or hsl)." },
            { name: "textColor", type: "string", default: "#3a5a40", description: "Text color (hex, rgb, or hsl)." },
        ],
    },
];

