import { Component } from "../types";

export const featureGridComponentsMetadata: Component[] = [
    {
        id: "cinematic-grid",
        name: "Cinematic Stack",
        description: "Cinematic scroll-stacked feature grid with sticky cards and smooth transitions.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "cinematic", "sticky", "scroll"],
        previewUrl: "/Grids&Layouts/FeatureGrids/CinematicGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, desc: string, icon?: React.ReactNode, img?: string}>", default: "[{title: 'Global Edge', desc: 'Latency is a choice. We chose zero.', img: '...'}, ...]", description: "Array of feature items with title, description, optional icon, and optional image." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "stickyTop", type: "string", default: "top-24", description: "Sticky positioning class (Tailwind class)." },
        ],
    },
    {
        id: "bento-grid",
        name: "Cyber Bento",
        description: "Cyberpunk-inspired bento feature grid with glitch effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "bento", "cyber", "glitch"],
        previewUrl: "/Grids&Layouts/FeatureGrids/BentoGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, desc: string, icon?: React.ReactNode, img?: string}>", default: "[{title: 'Global Edge', desc: 'Latency is a choice. We chose zero.', icon: Activity}, ...]", description: "Array of feature items with title, description, optional icon, and optional image." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color (hex, rgb, or hsl)." },
            { name: "mainCardTitle", type: "string", default: "Neural Engine", description: "Main card title text." },
            { name: "mainCardStatus", type: "string", default: "ACTIVE", description: "Main card status text." },
            { name: "mainCardSubtitle", type: "string", default: "Processing matrix loaded.", description: "Main card subtitle text." },
            { name: "analyticsValue", type: "string", default: "99.9%", description: "Analytics card value display." },
            { name: "analyticsLabel", type: "string", default: "Uptime", description: "Analytics card label text." },
            { name: "networkValue", type: "string", default: "240ms", description: "Network card value display." },
            { name: "networkLabel", type: "string", default: "Latency", description: "Network card label text." },
            { name: "latencyValue", type: "string", default: "12ms", description: "Latency value display." },
            { name: "regionsValue", type: "string", default: "42", description: "Regions count display." },
            { name: "throughputValue", type: "string", default: "2.4TB/s", description: "Throughput value display." },
            { name: "deployText", type: "string", default: "Deploy", description: "Deploy button text." },
        ],
    },
    {
        id: "elastic-grid",
        name: "Elastic Expansion",
        description: "Elastic expanding feature grid with smooth morphing animations.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "elastic", "expansion", "morph"],
        previewUrl: "/Grids&Layouts/FeatureGrids/ElasticGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, desc: string, icon?: React.ReactNode, img?: string}>", default: "[{title: 'Global Edge', desc: 'Latency is a choice. We chose zero.', img: '...'}, ...]", description: "Array of feature items with title, description, optional icon, and optional image." },
            { name: "backgroundColor", type: "string", default: "#f5f5f5", description: "Background color (hex, rgb, or hsl)." },
            { name: "buttonText", type: "string", default: "Explore Capability", description: "Button text for expanded cards." },
        ],
    },
    {
        id: "glass-prism-grid",
        name: "Glass Prism",
        description: "Glassmorphic prism feature grid with light refraction effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "glass", "prism", "refraction"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GlassPrismGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, desc: string, icon?: React.ReactNode, img?: string}>", default: "[{title: 'Global Edge', desc: 'Latency is a choice. We chose zero.', img: '...'}, ...]", description: "Array of feature items with title, description, optional icon, and optional image." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color (hex, rgb, or hsl)." },
            { name: "accentColor", type: "string", default: "cyan", description: "Accent color theme: 'cyan', 'purple', 'blue', 'green', or 'pink'." },
        ],
    },
    {
        id: "brutalist-grida",
        name: "Brutalist Archive",
        description: "Brutalist feature grid with bold typography and stark contrasts.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "brutalist", "bold", "typography"],
        previewUrl: "/Grids&Layouts/FeatureGrids/BrutalistGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, desc: string, icon?: React.ReactNode, img?: string}>", default: "[{title: 'Global Edge', desc: 'Latency is a choice. We chose zero.', img: '...'}, ...]", description: "Array of feature items with title, description, optional icon, and optional image." },
            { name: "backgroundColor", type: "string", default: "#EBEBEB", description: "Background color (hex, rgb, or hsl)." },
            { name: "hoverColor", type: "string", default: "#FF3333", description: "Hover state color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#000000", description: "Border color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "minimal-grid",
        name: "Ethereal Minimal",
        description: "Minimalist feature grid with ethereal aesthetics and subtle animations.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "minimal", "ethereal", "subtle"],
        previewUrl: "/Grids&Layouts/FeatureGrids/MinimalGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, desc: string, icon?: React.ReactNode, img?: string}>", default: "[{title: 'Global Edge', desc: 'Latency is a choice. We chose zero.', img: '...'}, ...]", description: "Array of feature items with title, description, optional icon, and optional image." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "blueprint-grid",
        name: "Tech Blueprint",
        description: "Technical blueprint-style feature grid with engineering aesthetics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "blueprint", "tech", "engineering"],
        previewUrl: "/Grids&Layouts/FeatureGrids/BlueprintGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, desc: string, icon?: React.ReactNode, img?: string}>", default: "[{title: 'Global Edge', desc: 'Latency is a choice. We chose zero.', img: '...'}, ...]", description: "Array of feature items with title, description, optional icon, and optional image." },
            { name: "backgroundColor", type: "string", default: "#0f172a", description: "Background color (hex, rgb, or hsl)." },
            { name: "gridColor", type: "string", default: "#1e293b", description: "Grid pattern color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#3b82f6", description: "Border and accent color (hex, rgb, or hsl)." },
            { name: "commandText", type: "string", default: "EXECUTE_PROTOCOL", description: "Command text displayed in scanning line." },
        ],
    },
    {
        id: "uilora-spotlight-grid",
        name: "Focus Spotlight",
        description: "Spotlight-focused feature grid with dynamic lighting effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "spotlight", "lighting", "focus"],
        previewUrl: "/Grids&Layouts/FeatureGrids/SpotlightGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, desc: string, icon?: React.ReactNode, img?: string}>", default: "[{title: 'Global Edge', desc: 'Latency is a choice. We chose zero.', img: '...'}, ...]", description: "Array of feature items with title, description, optional icon, and optional image." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "hoverGradientFrom", type: "string", default: "purple-900", description: "Hover gradient start color (Tailwind color name)." },
            { name: "hoverGradientTo", type: "string", default: "blue-900", description: "Hover gradient end color (Tailwind color name)." },
        ],
    },
    {
        id: "grid-scatter-deck",
        name: "Scatter Deck",
        description: "Scattered card deck feature grid with random positioning.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "scatter", "deck", "random"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridScatterDeck",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "cards", type: "Array<{title: string, color: string, rotate: number, z: number}>", default: "[{title: 'Motion', color: 'bg-[#ff4d4d]', rotate: -5, z: 10}, ...]", description: "Array of card objects with title, color (Tailwind class), rotation angle, and z-index." },
            { name: "backgroundColor", type: "string", default: "#e5e5e5", description: "Background color (hex, rgb, or hsl)." },
            { name: "gridSize", type: "number", default: "400", description: "Grid size in pixels for positioning." },
            { name: "dragText", type: "string", default: "Drag Me", description: "Text displayed on draggable cards." },
            { name: "backgroundText", type: "string", default: "SCATTER", description: "Background text pattern." },
        ],
    },
    {
        id: "grid-kinetic",
        name: "Kinetic Type",
        description: "Kinetic typography feature grid with animated text effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "kinetic", "typography", "animated"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridKinetic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, desc: string, icon?: React.ReactNode, img?: string}>", default: "[{title: 'Global Edge', desc: 'Latency is a choice. We chose zero.', img: '...'}, ...]", description: "Array of feature items with title, description, optional icon, and optional image." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
            { name: "repeatCount", type: "number", default: "8", description: "Number of times to repeat text in marquee." },
        ],
    },
    {
        id: "grid-liquid",
        name: "Liquid Magma",
        description: "Liquid magma feature grid with flowing animations and heat effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "liquid", "magma", "flowing"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridLiquid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "itemCount", type: "number", default: "8", description: "Number of liquid blob items to display." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "gradientFrom", type: "string", default: "#6366f1", description: "Gradient start color (hex, rgb, or hsl)." },
            { name: "gradientTo", type: "string", default: "#9333ea", description: "Gradient end color (hex, rgb, or hsl)." },
            { name: "hoverGradientFrom", type: "string", default: "#f97316", description: "Hover gradient start color (hex, rgb, or hsl)." },
            { name: "hoverGradientTo", type: "string", default: "#ec4899", description: "Hover gradient end color (hex, rgb, or hsl)." },
            { name: "itemPrefix", type: "string", default: "Fluidity", description: "Prefix text for item labels." },
        ],
    },
    {
        id: "grid-bento-vault",
        name: "Bento Vault",
        description: "Vault-style bento feature grid with secure aesthetics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "bento", "vault", "secure"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridBentoVault",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{id: number, col: string, row: string, title: string, icon: React.ComponentType}>", default: "[{id: 1, col: 'md:col-span-2', row: 'md:row-span-2', title: 'Mainframe', icon: Fingerprint}, ...]", description: "Array of grid items with id, column span, row span, title, and icon component." },
            { name: "backgroundColor", type: "string", default: "#18181b", description: "Background color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#27272a", description: "Border color (hex, rgb, or hsl)." },
            { name: "closeText", type: "string", default: "Close", description: "Close button text." },
        ],
    },
    {
        id: "grid-parallax-slice",
        name: "Parallax Slice",
        description: "Parallax sliced feature grid with depth and movement.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "parallax", "slice", "depth"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridParallaxSlice",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "columns", type: "Array<Array<{image: string, alt: string, hoverText?: string}>>", default: "[[{image: '...', alt: 'Architecture 1'}, ...], ...]", description: "2D array of column items, each containing image URL, alt text, and optional hover text." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "ARCHITECTURE", description: "Title text displayed above columns." },
            { name: "subtitle", type: "string", default: "Exploring spatial relationships", description: "Subtitle text displayed above columns." },
        ],
    },
    {
        id: "grid-cursor-lens",
        name: "Cursor Lens",
        description: "Cursor lens feature grid with magnifying glass effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "cursor", "lens", "magnify"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridCursorLens",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title: string, description: string}>", default: "[{title: 'Vision', description: 'Seeing beyond the visible spectrum.'}, ...]", description: "Array of feature items with title and description." },
            { name: "backgroundColor", type: "string", default: "#f5f5f4", description: "Background color (hex, rgb, or hsl)." },
            { name: "lensColor", type: "string", default: "#f97316", description: "Lens reveal color (hex, rgb, or hsl)." },
            { name: "gridText", type: "string", default: "Create", description: "Text to repeat in background grid." },
            { name: "gridTextCount", type: "number", default: "100", description: "Number of times to repeat grid text." },
        ],
    },
    {
        id: "grid-elastic-tape",
        name: "Elastic Tape",
        description: "Elastic tape feature grid with stretchy animations.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "elastic", "tape", "stretchy"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridElasticTape",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{image: string, title: string, subtitle: string, description: string}>", default: "[{image: '...', title: 'Section', subtitle: '1', description: 'Drag to interact. Scroll to seek.'}, ...]", description: "Array of tape items with image URL, title, subtitle, and description." },
            { name: "backgroundColor", type: "string", default: "#facc15", description: "Background color (hex, rgb, or hsl)." },
            { name: "tapeColor", type: "string", default: "#000000", description: "Tape border and text color (hex, rgb, or hsl)." },
            { name: "warningText", type: "string", default: "WARNING: HEAVY LOAD // ", description: "Warning text to repeat on tape." },
            { name: "scrollText", type: "string", default: "SCROLL TO SEEK", description: "Scroll instruction text." },
        ],
    },
];

