import { Component } from "../types";

export const galleryGridComponentsMetadata: Component[] = [
    {
        id: "gallery-parallax-columns",
        name: "Parallax Columns",
        description: "Fashion editorial gallery with parallax scrolling columns.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "parallax", "columns", "fashion"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryParallaxColumns",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...9 image URLs]", description: "Array of image URLs to display in columns." },
            { name: "backgroundColor", type: "string", default: "#f5f5f4", description: "Background color (hex, rgb, or hsl)." },
            { name: "columnCount", type: "number", default: "3", description: "Number of columns (2, 3, or 4)." },
        ],
    },
    {
        id: "gallery-shattered",
        name: "Shattered Mosaic",
        description: "Abstract broken mosaic gallery with shattered tile effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "shattered", "mosaic", "abstract"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryShattered",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{span: string, img: string}>", default: "[{span: 'col-span-2 row-span-2', img: '...'}, ...]", description: "Array of items with grid span classes and image URLs." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color (hex, rgb, or hsl)." },
            { name: "labelPrefix", type: "string", default: "Abstract", description: "Prefix text for item labels." },
        ],
    },
    {
        id: "gallery-bentoa",
        name: "Bento Focus",
        description: "Interactive bento gallery with expandable focus cards.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "bento", "focus", "expandable"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryBento",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{id: number, title: string, img: string}>", default: "[{id: 1, title: 'Architecture', img: '...'}, ...]", description: "Array of gallery items with id, title, and image URL." },
            { name: "backgroundColor", type: "string", default: "#f9fafb", description: "Background color (hex, rgb, or hsl)." },
            { name: "description", type: "string", default: "Exploring the fundamental connection between space, light, and structure. This collection dives deep into modern aesthetic principles.", description: "Description text shown when item is expanded." },
        ],
    },
    {
        id: "gallery-spotlight",
        name: "Spotlight Matrix",
        description: "Spotlight matrix gallery with dynamic lighting effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "spotlight", "matrix", "lighting"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GallerySpotlight",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...16 image URLs]", description: "Array of image URLs to display in grid." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "spotlightSize", type: "number", default: "600", description: "Size of spotlight effect in pixels." },
            { name: "imageLabelPrefix", type: "string", default: "IMG", description: "Prefix text for image labels." },
        ],
    },
    {
        id: "gallery-film-stripa",
        name: "Film Strip",
        description: "Vintage film strip gallery with horizontal scrolling.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "film", "strip", "vintage"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryFilmStrip",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...5 image URLs]", description: "Array of image URLs to display in film strips." },
            { name: "backgroundColor", type: "string", default: "#111", description: "Background color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#222", description: "Film strip border color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "gallery-fan",
        name: "Z-Stack Fan",
        description: "3D fan-stacked gallery with z-depth and perspective.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "fan", "3d", "stack"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryFan",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "cards", type: "Array<{title: string, color: string}>", default: "[{title: 'Air', color: 'bg-blue-200'}, ...]", description: "Array of card objects with title and color (Tailwind class)." },
            { name: "backgroundColor", type: "string", default: "#f5f5f5", description: "Background color (hex, rgb, or hsl)." },
            { name: "collectionPrefix", type: "string", default: "Collection", description: "Prefix text for collection labels." },
            { name: "hintText", type: "string", default: "HOVER TO EXPAND DECK", description: "Hint text displayed at bottom." },
        ],
    },
    {
        id: "gallery-velocity",
        name: "Velocity Scroll",
        description: "High-velocity scrolling gallery with momentum effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "velocity", "scroll", "momentum"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryVelocity",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...4 image URLs]", description: "Array of image URLs to display in marquee." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#000000", description: "Border color (hex, rgb, or hsl)." },
            { name: "accentColor", type: "string", default: "#facc15", description: "Accent color for marquee background (hex, rgb, or hsl)." },
            { name: "titleText", type: "string", default: "STREET", description: "Large title text displayed in center." },
            { name: "imageLabelPrefix", type: "string", default: "FIG", description: "Prefix text for image labels." },
        ],
    },
    {
        id: "gallery-velocity-warp",
        name: "Velocity Warp",
        description: "Warp-speed velocity gallery with distortion effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "velocity", "warp", "distortion"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryVelocityWarp",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...9 image URLs]", description: "Array of image URLs to display in grid." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color (hex, rgb, or hsl)." },
            { name: "backgroundText", type: "string", default: "WARP", description: "Large background text pattern." },
            { name: "labelPrefix", type: "string", default: "Figure", description: "Prefix text for image labels." },
        ],
    },
    {
        id: "gallery-flashlight",
        name: "Flashlight Reveal",
        description: "Flashlight reveal gallery with spotlight interactions.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "flashlight", "reveal", "spotlight"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryFlashlight",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...12 image URLs]", description: "Array of image URLs to display in grid." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "lensSize", type: "number", default: "300", description: "Size of flashlight lens in pixels." },
            { name: "hintText", type: "string", default: "USE CURSOR TO ILLUMINATE ARCHIVE", description: "Hint text displayed at bottom." },
        ],
    },
    {
        id: "gallery-tunnel",
        name: "Parallax Tunnel",
        description: "Parallax tunnel gallery with depth and perspective.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "tunnel", "parallax", "depth"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryTunnel",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "mainImage", type: "string", default: "https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=800&q=80", description: "Main center image URL." },
            { name: "middleImages", type: "string[]", default: "[...2 image URLs]", description: "Array of middle layer image URLs." },
            { name: "backgroundColor", type: "string", default: "#1a1a1a", description: "Background color (hex, rgb, or hsl)." },
            { name: "enterText", type: "string", default: "ENTER", description: "Text displayed on main image." },
            { name: "scrollHint", type: "string", default: "SCROLL TO DIVE", description: "Scroll instruction text." },
        ],
    },
    {
        id: "gallery-sliced",
        name: "Sliced Hover",
        description: "Sliced hover gallery with split-screen effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "sliced", "hover", "split"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GallerySliced",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{title: string, img: string}>", default: "[{title: 'NATURE', img: '...'}, ...]", description: "Array of items with title and image URL." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
            { name: "descriptionTemplate", type: "string", default: "An immersive exploration into the depths of {title} aesthetics.", description: "Description template (use {title} placeholder)." },
            { name: "buttonText", type: "string", default: "Explore Collection", description: "Button text for expanded view." },
        ],
    },
    {
        id: "gallery-perspective-wall",
        name: "Perspective Wall",
        description: "3D perspective wall gallery with depth illusions.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "perspective", "wall", "3d"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryPerspectiveWall",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...16 image URLs]", description: "Array of image URLs to display in wall." },
            { name: "backgroundColor", type: "string", default: "#f5f5f5", description: "Background color (hex, rgb, or hsl)." },
            { name: "gridCols", type: "number", default: "4", description: "Number of grid columns (2, 3, 4, 5, or 6)." },
        ],
    },
    {
        id: "gallery-pin-reveal",
        name: "Pin & Reveal",
        description: "Pin and reveal gallery with interactive pinning effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "pin", "reveal", "interactive"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryPinReveal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "cards", type: "Array<{color: string, title: string, img: string}>", default: "[{color: '#FF5733', title: 'Ignite', img: '...'}, ...]", description: "Array of card objects with color (hex), title, and image URL." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "scrollHintText", type: "string", default: "Scroll Down", description: "Scroll hint main text." },
            { name: "scrollHintSubtext", type: "string", default: "↓", description: "Scroll hint subtext/arrow." },
        ],
    },
    {
        id: "gallery-diagonal-marquee",
        name: "Diagonal Marquee",
        description: "Diagonal marquee gallery with scrolling text effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "diagonal", "marquee", "scrolling"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryDiagonalMarquee",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "row1Images", type: "string[]", default: "[...10 image URLs]", description: "Array of image URLs for first row." },
            { name: "row2Images", type: "string[]", default: "[...10 image URLs]", description: "Array of image URLs for second row." },
            { name: "row3Images", type: "string[]", default: "[...10 image URLs]", description: "Array of image URLs for third row." },
            { name: "backgroundColor", type: "string", default: "#e0e0e0", description: "Background color (hex, rgb, or hsl)." },
            { name: "badgePrefix", type: "string", default: "A", description: "Prefix text for badge labels." },
        ],
    },
    {
        id: "gallery-click-expand",
        name: "Hero Expand",
        description: "Click-to-expand hero gallery with fullscreen interactions.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "expand", "hero", "fullscreen"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryClickExpand",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{id: string, title: string, col: string, img: string}>", default: "[{id: '1', title: 'Cyber', col: 'col-span-2 row-span-2', img: '...'}, ...]", description: "Array of items with id, title, grid span classes, and image URL (empty img for empty slots)." },
            { name: "backgroundColor", type: "string", default: "#18181b", description: "Background color (hex, rgb, or hsl)." },
            { name: "emptySlotText", type: "string", default: "Empty", description: "Text displayed in empty grid slots." },
            { name: "fullScreenText", type: "string", default: "Full screen immersive view active. Click anywhere to return to the grid matrix.", description: "Text displayed in fullscreen view." },
        ],
    },
];

