import { Component } from "../types";

export const masonryGridComponentsMetadata: Component[] = [
    {
        id: "masonry-editorial",
        name: "Editorial Stagger",
        description: "Sharp monochrome editorial masonry grid with high-fashion aesthetics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "editorial", "monochrome", "fashion"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{h: string, title: string, sub: string}>", default: "[{h: 'h-64', title: 'Vogue', sub: 'Collection 01'}, ...]", description: "Array of editorial items with height class (h), title, and subtitle." },
            { name: "backgroundColor", type: "string", default: "#f4f4f0", description: "Background color (hex, rgb, or hsl)." },
            { name: "imageSeed", type: "number", default: "50", description: "Seed number for generating placeholder images." },
        ],
    },
    {
        id: "masonry-neo-brutal",
        name: "Neo-Brutalist Pop",
        description: "Chunky bold neo-brutalist masonry grid with marquee effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "neo-brutal", "bold", "marquee"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryNeoBrutal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "tiles", type: "Array<{span: string, bg: string, text: string, textCol?: string}>", default: "[{span: 'col-span-1 row-span-1', bg: '#FF6B6B', text: 'POP'}, ...]", description: "Array of tile objects with grid span, background color (hex), text, and optional text color (hex)." },
            { name: "backgroundColor", type: "string", default: "#E0E0E0", description: "Background color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "masonry-swiss",
        name: "Swiss Precision",
        description: "Swiss design masonry grid with precise typography and clean lines.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "swiss", "precision", "typography"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonrySwiss",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "backgroundColor", type: "string", default: "#E5E5E5", description: "Background color (hex, rgb, or hsl)." },
            { name: "accentColor", type: "string", default: "#FF3B30", description: "Accent color for highlights (hex, rgb, or hsl)." },
            { name: "mainTitle", type: "string", default: "HELV.", description: "Main title text." },
            { name: "subtitle", type: "string", default: "INTERNATIONAL\\nSTYLE", description: "Subtitle text (supports \\n for line breaks)." },
            { name: "year", type: "string", default: "(1957)", description: "Year text displayed in sidebar." },
            { name: "coordinates", type: "{x: string, y: string}", default: "{x: '1024', y: '0768'}", description: "Coordinate values displayed in bottom section." },
        ],
    },
    {
        id: "masonry-prism",
        name: "Prism Grid",
        description: "Prismatic masonry grid with light refraction and glass effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "prism", "glass", "refraction"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryPrism",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "shards", type: "Array<{clip: string, img: string, title?: string}>", default: "[{clip: 'polygon(0 0, 100% 0, 100% 85%, 0 100%)', img: '...'}, ...]", description: "Array of shard objects with CSS clip-path, image URL, and optional title." },
            { name: "backgroundColor", type: "string", default: "#0f172a", description: "Background color (hex, rgb, or hsl)." },
            { name: "titlePrefix", type: "string", default: "Prism", description: "Prefix text for shard titles." },
        ],
    },
    {
        id: "masonry-magma",
        name: "Magma Flow",
        description: "Liquid magma masonry grid with flowing animations and heat effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "magma", "flow", "liquid"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryMagma",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{title?: string, subtitle?: string, buttonText?: string}>", default: "", description: "Array of magma items with optional title, subtitle, and button text. If not provided, items are auto-generated." },
            { name: "itemCount", type: "number", default: "6", description: "Number of items to generate if items array is not provided." },
            { name: "backgroundColor", type: "string", default: "#110000", description: "Background color (hex, rgb, or hsl)." },
            { name: "titlePrefix", type: "string", default: "Flow State", description: "Prefix text for auto-generated item titles." },
        ],
    },
    {
        id: "uilora-brutalist-grid",
        name: "Brutalist Grid",
        description: "Brutalist masonry grid with stark contrasts and bold shapes.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "brutalist", "bold", "contrast"],
        previewUrl: "/Grids&Layouts/MasonryGrids/BrutalistGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...12 image URLs]", description: "Array of image URLs." },
            { name: "content", type: "Array<{type: 'img'|'text', src?: string, title?: string, text?: string, span?: string}>", default: "", description: "Array of content items (images or text cards). If not provided, default content is generated from images." },
            { name: "backgroundColor", type: "string", default: "#f5f5f5", description: "Background color (hex, rgb, or hsl)." },
            { name: "indexPrefix", type: "string", default: "Index", description: "Prefix text for item index labels." },
            { name: "hoverColor", type: "string", default: "#facc15", description: "Hover state color for text cards (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "clay-grid",
        name: "Clay Grid",
        description: "Soft clay masonry grid with organic shapes and earthy tones.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "clay", "organic", "soft"],
        previewUrl: "/Grids&Layouts/MasonryGrids/ClayGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...9 image URLs]", description: "Array of image URLs." },
            { name: "content", type: "Array<{type: 'img'|'text', src?: string, title?: string, text?: string, span?: string}>", default: "", description: "Array of content items (images or text cards). If not provided, default content is generated from images." },
            { name: "backgroundColor", type: "string", default: "#e0e5ec", description: "Background color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "agency-grid",
        name: "Agency Grid",
        description: "Professional agency masonry grid with corporate aesthetics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "agency", "professional", "corporate"],
        previewUrl: "/Grids&Layouts/MasonryGrids/AgencyGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...12 image URLs]", description: "Array of image URLs." },
            { name: "content", type: "Array<{type: 'img'|'text', src?: string, title?: string, text?: string, span?: string}>", default: "", description: "Array of content items (images or text cards). If not provided, default content is generated from images." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color (hex, rgb, or hsl)." },
            { name: "projectPrefix", type: "string", default: "Project", description: "Prefix text for project labels." },
        ],
    },
    {
        id: "sketch-grid",
        name: "Sketch Grid",
        description: "Hand-drawn sketch masonry grid with rough aesthetics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "sketch", "hand-drawn", "rough"],
        previewUrl: "/Grids&Layouts/MasonryGrids/SketchGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...9 image URLs]", description: "Array of image URLs." },
            { name: "content", type: "Array<{type: 'img'|'text', src?: string, title?: string, text?: string, span?: string}>", default: "", description: "Array of content items (images or text cards). If not provided, default content is generated from images." },
            { name: "backgroundColor", type: "string", default: "#f0f0f0", description: "Background color (hex, rgb, or hsl)." },
            { name: "gridColor", type: "string", default: "#ccc", description: "Grid pattern color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "pop-grid",
        name: "Pop Grid",
        description: "Pop art masonry grid with vibrant colors and bold patterns.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "pop", "vibrant", "bold"],
        previewUrl: "/Grids&Layouts/MasonryGrids/PopGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...12 image URLs]", description: "Array of image URLs." },
            { name: "content", type: "Array<{type: 'img'|'text', src?: string, title?: string, text?: string, span?: string}>", default: "", description: "Array of content items (images or text cards). If not provided, default content is generated from images." },
            { name: "backgroundColor", type: "string", default: "#FFE5E5", description: "Background color (hex, rgb, or hsl)." },
            { name: "itemPrefix", type: "string", default: "ITEM", description: "Prefix text for item labels." },
            { name: "badgeText", type: "string", default: "POP", description: "Badge text displayed on images." },
            { name: "colors", type: "string[]", default: "['#A3E635', '#60A5FA', '#F472B6']", description: "Array of background colors (hex) for alternating items." },
        ],
    },
    {
        id: "sliced-grid",
        name: "Abstract Sliced",
        description: "Abstract sliced masonry grid with split-screen effects.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "sliced", "abstract", "split"],
        previewUrl: "/Grids&Layouts/MasonryGrids/SlicedGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...12 image URLs]", description: "Array of image URLs." },
            { name: "content", type: "Array<{type: 'img'|'text', src?: string, title?: string, text?: string, span?: string}>", default: "", description: "Array of content items (images or text cards). If not provided, default content is generated from images." },
            { name: "backgroundColor", type: "string", default: "#171717", description: "Background color (hex, rgb, or hsl)." },
            { name: "overlayColor", type: "string", default: "#dc2626", description: "Overlay color for hover effects (hex, rgb, or hsl)." },
        ],
    },
];

