import { Component } from "../types";

export const accordionComponentsMetadata: Component[] = [
    {
        id: "uilora-liquid",
        name: "Liquid Stretch",
        description: "Smooth liquid motion accordion with natural spring animations.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "liquid", "motion", "spring"],
        previewUrl: "/SpecialElements/Accordions/Liquid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "AccordionItem[]", default: "[{id: '1', label: 'Module 1', content: '...'}, ...]", description: "Array of accordion items with id, label, and optional content." },
            { name: "backgroundColor", type: "string", default: "transparent", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "containerBgColor", type: "string", default: "#ffffff", description: "Background color of the container (hex, rgb, or hsl)." },
            { name: "containerShadowColor", type: "string", default: "rgba(0,0,0,0.1)", description: "Shadow color of the container (hex, rgb, or hsl)." },
            { name: "itemBgColor", type: "string", default: "#f4f4f5", description: "Background color of accordion items (hex, rgb, or hsl)." },
            { name: "itemTextColor", type: "string", default: "#18181b", description: "Text color of item labels (hex, rgb, or hsl)." },
            { name: "contentTextColor", type: "string", default: "#71717a", description: "Text color of item content (hex, rgb, or hsl)." },
            { name: "iconColor", type: "string", default: "#18181b", description: "Color of the chevron icon (hex, rgb, or hsl)." },
            { name: "defaultActive", type: "number | null", default: "0", description: "Index of the initially active item (null for none)." },
            { name: "borderRadius", type: "string", default: "1rem", description: "Border radius of the container (CSS value)." },
        ],
    },
    {
        id: "split",
        name: "Split Screen",
        description: "Split screen accordion with expanding partitions.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "split", "screen", "layout"],
        previewUrl: "/SpecialElements/Accordions/Split",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "AccordionItem[]", default: "[{id: '1', label: '01', title: '...', description: '...'}, ...]", description: "Array of accordion items with id, label, optional title, description, and content." },
            { name: "backgroundColor", type: "string", default: "transparent", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "containerBorderColor", type: "string", default: "#e4e4e7", description: "Border color of the container (hex, rgb, or hsl)." },
            { name: "activeItemBgColor", type: "string", default: "#f4f4f5", description: "Background color of the active item (hex, rgb, or hsl)." },
            { name: "inactiveItemBgColor", type: "string", default: "#ffffff", description: "Background color of inactive items (hex, rgb, or hsl)." },
            { name: "itemHoverBgColor", type: "string", default: "#fafafa", description: "Background color of items on hover (hex, rgb, or hsl)." },
            { name: "itemBorderColor", type: "string", default: "#e4e4e7", description: "Border color between items (hex, rgb, or hsl)." },
            { name: "labelColor", type: "string", default: "#18181b", description: "Color of item labels (hex, rgb, or hsl)." },
            { name: "titleColor", type: "string", default: "#18181b", description: "Color of item titles (hex, rgb, or hsl)." },
            { name: "descriptionColor", type: "string", default: "#71717a", description: "Color of item descriptions (hex, rgb, or hsl)." },
            { name: "defaultActive", type: "number | null", default: "null", description: "Index of the initially active item (null for none)." },
            { name: "height", type: "string", default: "20rem", description: "Height of the accordion container (CSS value)." },
            { name: "borderRadius", type: "string", default: "0.75rem", description: "Border radius of the container (CSS value)." },
        ],
    },
    {
        id: "audio",
        name: "Audio Reactive",
        description: "Audio-reactive accordion with waveform visualization.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "audio", "reactive", "waveform"],
        previewUrl: "/SpecialElements/Accordions/Audio",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "AccordionItem[]", default: "[{id: '1', label: 'Track 01'}, ...]", description: "Array of accordion items with id, label, and optional content." },
            { name: "backgroundColor", type: "string", default: "transparent", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "itemBgColor", type: "string", default: "#18181b", description: "Background color of accordion items (hex, rgb, or hsl)." },
            { name: "itemHoverBgColor", type: "string", default: "#27272a", description: "Background color of items on hover (hex, rgb, or hsl)." },
            { name: "itemTextColor", type: "string", default: "#ffffff", description: "Text color of item labels (hex, rgb, or hsl)." },
            { name: "activeBarColor", type: "string", default: "#4ade80", description: "Color of active waveform bars (hex, rgb, or hsl)." },
            { name: "inactiveBarColor", type: "string", default: "#52525b", description: "Color of inactive waveform bars (hex, rgb, or hsl)." },
            { name: "progressBarBgColor", type: "string", default: "#3f3f46", description: "Background color of progress bar (hex, rgb, or hsl)." },
            { name: "progressBarFillColor", type: "string", default: "#4ade80", description: "Fill color of progress bar (hex, rgb, or hsl)." },
            { name: "iconColor", type: "string", default: "#ffffff", description: "Color of play/pause icons (hex, rgb, or hsl)." },
            { name: "defaultActive", type: "number | null", default: "null", description: "Index of the initially active item (null for none)." },
        ],
    },
];

