import { Component } from "../types";

export const avatarsComponentsMetadata: Component[] = [
    {
        id: "classic-avatar",
        name: "Classic Avatar",
        description: "Comprehensive avatar collection with multiple styles including cinematic, minimal, status indicators, initials, grouped stacks, and hover effects. Showcase of 10+ avatar variations.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "avatar", "classic", "variants", "status", "grouped", "showcase"],
        previewUrl: "/SpecialElements/Avatars/ClassicAvatar",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "stacked-hover-card",
        name: "Stacked Hover Card",
        description: "Stacked avatar group with hover cards showing user information. Features glassmorphism cards that appear on hover with smooth animations and user details.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "avatar", "stacked", "hover", "card", "group", "glassmorphism"],
        previewUrl: "/SpecialElements/Avatars/StackedHoverCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "spotlight-group",
        name: "Spotlight Group",
        description: "Large group of avatars with spotlight effect on hover. Features dimming overlay, scale animations, and detailed user cards with role information.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "avatar", "spotlight", "group", "hover", "dimming", "animation"],
        previewUrl: "/SpecialElements/Avatars/SpotlightGroup",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "slide-out-stack",
        name: "Slide Out Stack",
        description: "Vertical stack of avatars with sliding name tags on hover. Features smooth slide animations and compact vertical layout with role information.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "avatar", "slide", "stack", "vertical", "hover", "animation"],
        previewUrl: "/SpecialElements/Avatars/SlideOutStack",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "horizontal-lift-stack",
        name: "Horizontal Lift Stack",
        description: "Horizontal avatar stack with lift animation and glassy info cards. Features 3D lift effect, blur on inactive items, and detailed hover cards.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "avatar", "horizontal", "lift", "3d", "glassy", "blur"],
        previewUrl: "/SpecialElements/Avatars/HorizontalLiftStack",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
];

