import { Component } from "../types";

export const breadcrumbsComponentsMetadata: Component[] = [
    {
        id: "underlined-breadcrumb",
        name: "Underlined Breadcrumb",
        description: "Breadcrumb navigation with animated underline effects on hover. Features smooth underline transitions and active state indicators with glow effects.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "breadcrumb", "navigation", "underline", "animated", "hover"],
        previewUrl: "/SpecialElements/Breadcrumbs/UnderlinedBreadcrumb",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "minimal-floating-breadcrumb",
        name: "Minimal Floating Breadcrumb",
        description: "Minimal floating breadcrumb with glassmorphism design. Features subtle hover glows, ambient blur effects, and compact uppercase typography.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "breadcrumb", "minimal", "floating", "glassmorphism", "blur"],
        previewUrl: "/SpecialElements/Breadcrumbs/MinimalFloatingBreadcrumb",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "icon-breadcrumb",
        name: "Icon Breadcrumb",
        description: "Icon-enhanced breadcrumb with icon badges for each step. Features icon containers with hover states and micro-glow effects on interaction.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "breadcrumb", "icon", "badge", "enhanced", "hover"],
        previewUrl: "/SpecialElements/Breadcrumbs/IconBreadcrumb",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "boxed-segmented-breadcrumb",
        name: "Boxed Segmented Breadcrumb",
        description: "Boxed segmented breadcrumb with individual containers for each step. Features shine effects on hover, scale animations, and clean segmented layout.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "breadcrumb", "boxed", "segmented", "shine", "animation"],
        previewUrl: "/SpecialElements/Breadcrumbs/BoxedSegmentedBreadcrumb",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
];

