import { Component } from "../types";
export const carouselComponentsMetadata: Component[] = [
    {
        id: "depth",
        name: "Depth Parallax",
        description: "Carousel with depth parallax scrolling effects.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "parallax", "depth", "scroll"],
        previewUrl: "/SpecialElements/Carousels/Depth",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "images", type: "string[]", default: "[url1, url2, ...]", description: "Array of image URLs to display in the carousel." },
            { name: "labels", type: "string[]", default: "[]", description: "Optional array of labels for each slide (overrides default 'SLIDE 0X' format)." },
            { name: "defaultIndex", type: "number", default: "0", description: "Initial active slide index." },
            { name: "backgroundColor", type: "string", default: "transparent", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "containerBgColor", type: "string", default: "#000000", description: "Background color of the carousel container (hex, rgb, or hsl)." },
            { name: "borderRadius", type: "string", default: "1rem", description: "Border radius of the container (CSS value)." },
            { name: "imageOpacity", type: "number", default: "0.6", description: "Opacity of background images (0-1)." },
            { name: "textColor", type: "string", default: "#ffffff", description: "Color of slide labels (hex, rgb, or hsl)." },
            { name: "buttonBgColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Background color of navigation buttons (hex, rgb, or hsl)." },
            { name: "buttonHoverBgColor", type: "string", default: "rgba(255,255,255,0.4)", description: "Background color of buttons on hover (hex, rgb, or hsl)." },
            { name: "buttonTextColor", type: "string", default: "#ffffff", description: "Text/icon color of buttons (hex, rgb, or hsl)." },
            { name: "buttonBorderRadius", type: "string", default: "9999px", description: "Border radius of buttons (CSS value)." },
            { name: "transitionDuration", type: "number", default: "0.8", description: "Duration of slide transitions in seconds." },
            { name: "height", type: "string", default: "16rem", description: "Height of the carousel container (CSS value)." },
            { name: "maxWidth", type: "string", default: "28rem", description: "Maximum width of the carousel container (CSS value)." },
        ],
    },
    {
        id: "coverflow",
        name: "Coverflow",
        description: "3D coverflow carousel with perspective transforms.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "coverflow", "3d", "perspective"],
        previewUrl: "/SpecialElements/Carousels/Coverflow",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "images", type: "string[]", default: "[url1, url2, url3]", description: "Array of image URLs to display in the carousel." },
            { name: "defaultActive", type: "number", default: "1", description: "Initial active slide index." },
            { name: "backgroundColor", type: "string", default: "transparent", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "imageBorderColor", type: "string", default: "#ffffff", description: "Border color of carousel images (hex, rgb, or hsl)." },
            { name: "imageBorderWidth", type: "number", default: "4", description: "Border width of carousel images in pixels." },
            { name: "imageShadowColor", type: "string", default: "rgba(0,0,0,0.5)", description: "Shadow color of carousel images (hex, rgb, or hsl)." },
            { name: "activeScale", type: "number", default: "1", description: "Scale of the active slide." },
            { name: "inactiveScale", type: "number", default: "0.8", description: "Scale of inactive slides." },
            { name: "activeOpacity", type: "number", default: "1", description: "Opacity of the active slide (0-1)." },
            { name: "inactiveOpacity", type: "number", default: "0.5", description: "Opacity of inactive slides (0-1)." },
            { name: "rotationAngle", type: "number", default: "45", description: "Rotation angle for inactive slides in degrees." },
            { name: "offsetDistance", type: "number", default: "40", description: "Horizontal offset distance between slides in pixels." },
            { name: "height", type: "string", default: "12rem", description: "Height of carousel images (CSS value)." },
            { name: "width", type: "string", default: "12rem", description: "Width of carousel images (CSS value)." },
            { name: "borderRadius", type: "string", default: "0.75rem", description: "Border radius of carousel images (CSS value)." },
        ],
    },
    {
        id: "panorama",
        name: "Panorama",
        description: "Draggable panorama carousel with smooth scrolling.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "panorama", "drag", "scroll"],
        previewUrl: "/SpecialElements/Carousels/Panorama",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "images", type: "string[]", default: "[url1, url2, ...]", description: "Array of image URLs to display in the carousel." },
            { name: "backgroundColor", type: "string", default: "transparent", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "borderRadius", type: "string", default: "1rem", description: "Border radius of the container (CSS value)." },
            { name: "imageBorderRadius", type: "string", default: "0.75rem", description: "Border radius of carousel images (CSS value)." },
            { name: "imageHeight", type: "string", default: "16rem", description: "Height of carousel images (CSS value)." },
            { name: "imageWidth", type: "string", default: "12rem", description: "Width of carousel images (CSS value)." },
            { name: "imageGap", type: "string", default: "1rem", description: "Gap between carousel images (CSS value)." },
            { name: "dragConstraints", type: "{left: number, right: number}", default: "{left: -500, right: 0}", description: "Drag constraints for horizontal scrolling." },
            { name: "cursorGrab", type: "string", default: "grab", description: "Cursor style when hovering (CSS cursor value)." },
            { name: "cursorGrabbing", type: "string", default: "grabbing", description: "Cursor style when dragging (CSS cursor value)." },
        ],
    },
    {
        id: "infinite",
        name: "Infinite Loop",
        description: "Seamless infinite scrolling carousel.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "infinite", "loop", "scroll"],
        previewUrl: "/SpecialElements/Carousels/Infinite",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "images", type: "string[]", default: "[url1, url2, ...]", description: "Array of image URLs to display in the carousel." },
            { name: "backgroundColor", type: "string", default: "transparent", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "imageBgColor", type: "string", default: "#e4e4e7", description: "Background color of image containers (hex, rgb, or hsl)." },
            { name: "imageBorderRadius", type: "string", default: "0.5rem", description: "Border radius of carousel images (CSS value)." },
            { name: "imageOpacity", type: "number", default: "0.8", description: "Opacity of carousel images (0-1)." },
            { name: "imageGap", type: "string", default: "0.5rem", description: "Gap between carousel images (CSS value)." },
            { name: "imageHeight", type: "string", default: "6rem", description: "Height of carousel images (CSS value)." },
            { name: "imageWidth", type: "string", default: "8rem", description: "Width of carousel images (CSS value)." },
            { name: "animationDuration", type: "number", default: "20", description: "Duration of the infinite scroll animation in seconds." },
            { name: "maskGradient", type: "string", default: "linear-gradient(to_right,transparent,black_20%,black_80%,transparent)", description: "CSS mask gradient for fade edges." },
            { name: "maxWidth", type: "string", default: "32rem", description: "Maximum width of the carousel container (CSS value)." },
        ],
    },
    {
        id: "story",
        name: "Vertical Story",
        description: "Vertical story-style carousel with progress indicators.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "story", "vertical", "progress"],
        previewUrl: "/SpecialElements/Carousels/Story",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "images", type: "string[]", default: "[url1, url2, ...]", description: "Array of image URLs to display in the carousel." },
            { name: "labels", type: "{title?: string, subtitle?: string}[]", default: "[]", description: "Optional array of labels with title and subtitle for each slide." },
            { name: "backgroundColor", type: "string", default: "transparent", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "containerBgColor", type: "string", default: "#000000", description: "Background color of the carousel container (hex, rgb, or hsl)." },
            { name: "borderRadius", type: "string", default: "1rem", description: "Border radius of the container (CSS value)." },
            { name: "progressBarBgColor", type: "string", default: "rgba(255,255,255,0.3)", description: "Background color of progress bars (hex, rgb, or hsl)." },
            { name: "progressBarFillColor", type: "string", default: "#ffffff", description: "Fill color of progress bars (hex, rgb, or hsl)." },
            { name: "progressBarHeight", type: "string", default: "0.25rem", description: "Height of progress bars (CSS value)." },
            { name: "progressBarGap", type: "string", default: "0.25rem", description: "Gap between progress bars (CSS value)." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Color of slide titles (hex, rgb, or hsl)." },
            { name: "subtitleColor", type: "string", default: "rgba(255,255,255,0.7)", description: "Color of slide subtitles (hex, rgb, or hsl)." },
            { name: "overlayGradientFrom", type: "string", default: "rgba(0,0,0,0.8)", description: "Start color of the overlay gradient (hex, rgb, or hsl)." },
            { name: "overlayGradientTo", type: "string", default: "transparent", description: "End color of the overlay gradient (hex, rgb, or hsl)." },
            { name: "autoPlayInterval", type: "number", default: "100", description: "Auto-play interval in milliseconds." },
            { name: "progressIncrement", type: "number", default: "2", description: "Progress increment per interval (percentage)." },
            { name: "height", type: "string", default: "24rem", description: "Height of the carousel container (CSS value)." },
            { name: "width", type: "string", default: "16rem", description: "Width of the carousel container (CSS value)." },
        ],
    }
];

