import { Component } from "../types";

export const selectorComponentsMetadata: Component[] = [
    {
        id: "segmented-selector",
        name: "Segmented Selector",
        description: "Classic premium segmented selector with animated background indicator. Features spring physics, glowing active state, and icon support with responsive labels.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "selector", "segmented", "premium", "animated", "indicator"],
        previewUrl: "/SpecialElements/Selector/SegmentedSelector",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "icon-picker",
        name: "Icon Picker",
        description: "Icon-based style picker with active dot indicators. Features hover lift animations, glow effects on active state, and compact icon-only layout.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "selector", "icon", "picker", "toolkit", "compact"],
        previewUrl: "/SpecialElements/Selector/IconPicker",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "floating-pills",
        name: "Floating Pills",
        description: "Glassy minimalist floating pills selector with morphing background. Features backdrop blur, glassmorphism design, and smooth layout transitions.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "selector", "pills", "floating", "glassy", "glassmorphism"],
        previewUrl: "/SpecialElements/Selector/FloatingPills",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "card-grid-selector",
        name: "Card Grid Selector",
        description: "Visual card grid selector with rim light effects. Features grid layout, emerald accent colors, and active rim light animations on selection.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "selector", "card", "grid", "visual", "rim-light"],
        previewUrl: "/SpecialElements/Selector/CardGridSelector",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "inline-selector",
        name: "Inline Selector",
        description: "Elegant thin inline style selector with sliding underline. Features minimal design, underline slide animations, and separator dividers.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "selector", "inline", "elegant", "underline", "minimal"],
        previewUrl: "/SpecialElements/Selector/InlineSelector",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "lucide-react"],
        props: [],
    },
    {
        id: "animated-indicator",
        name: "Animated Indicator",
        description: "Material premium animated indicator with gradient underline. Features tab-style layout, gradient indicator bar, and responsive icon labels.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "selector", "animated", "indicator", "material", "gradient"],
        previewUrl: "/SpecialElements/Selector/AnimatedIndicator",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "compact-strip",
        name: "Compact Strip",
        description: "Toolbar-style compact icon and label strip selector. Features compact layout, animated background indicator, and icon-label combinations.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "selector", "compact", "strip", "toolbar", "icon-label"],
        previewUrl: "/SpecialElements/Selector/CompactStrip",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "large-thumbnails",
        name: "Large Thumbnails",
        description: "Cinematic large preview thumbnails selector with mock content previews. Features thumbnail cards with preview content, overlay states, and check indicators.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "selector", "thumbnails", "cinematic", "preview", "visual"],
        previewUrl: "/SpecialElements/Selector/LargeThumbnails",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
];

