import { Component } from "../types";

export const tablesComponentsMetadata: Component[] = [
    {
        id: "minimal-table",
        name: "Minimal Table",
        description: "Simple minimal table with clean typography and subtle borders. Features hover states and clean data presentation without visual clutter.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "minimal", "simple", "clean", "data"],
        previewUrl: "/SpecialElements/Tables/MinimalTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "striped-rows-table",
        name: "Striped Rows Table",
        description: "Table with alternating striped rows for improved readability. Features zebra striping, hover effects, and enhanced visual hierarchy.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "striped", "rows", "zebra", "readability"],
        previewUrl: "/SpecialElements/Tables/StripedRowsTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "sortable-table",
        name: "Sortable Table",
        description: "Table with sortable columns and visual sort indicators. Features ascending/descending sort states, animated sort icons, and multi-column sorting support.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "sortable", "sorting", "columns", "interactive"],
        previewUrl: "/SpecialElements/Tables/SortableTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "selectable-table",
        name: "Selectable Table",
        description: "Table with row selection functionality and checkboxes. Features select all, individual row selection, and visual selection indicators.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "selectable", "selection", "checkboxes", "multi-select"],
        previewUrl: "/SpecialElements/Tables/SelectableTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "expandable-table",
        name: "Expandable Table",
        description: "Table with expandable rows showing additional details. Features collapsible rows, smooth expand/collapse animations, and nested content display.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "expandable", "collapsible", "details", "nested"],
        previewUrl: "/SpecialElements/Tables/ExpandableTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "sticky-header-table",
        name: "Sticky Header Table",
        description: "Table with sticky header that remains visible while scrolling. Features fixed header position, smooth scrolling, and enhanced navigation for long data sets.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "sticky", "header", "scroll", "fixed"],
        previewUrl: "/SpecialElements/Tables/StickyHeaderTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "badge-table",
        name: "Badge Table",
        description: "Table with status badges for visual data categorization. Features colored status badges, dot indicators, and enhanced visual hierarchy.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "badge", "status", "indicators", "categorization"],
        previewUrl: "/SpecialElements/Tables/BadgeTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "lucide-react"],
        props: [],
    },
    {
        id: "avatar-table",
        name: "Avatar Table",
        description: "Table with avatar cells showing user images and information. Features avatar displays, user names, emails, and enhanced user identification.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "avatar", "user", "profile", "identification"],
        previewUrl: "/SpecialElements/Tables/AvatarTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "actions-table",
        name: "Actions Table",
        description: "Table with inline action buttons for each row. Features edit, delete, and view actions with hover states and icon buttons.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "actions", "buttons", "inline", "interactive"],
        previewUrl: "/SpecialElements/Tables/ActionsTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "lucide-react"],
        props: [],
    },
    {
        id: "pagination-table",
        name: "Pagination Table",
        description: "Table with pagination footer for navigating large datasets. Features page navigation controls, page indicators, and previous/next buttons.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "pagination", "navigation", "pages", "footer"],
        previewUrl: "/SpecialElements/Tables/PaginationTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "lucide-react"],
        props: [],
    },
    {
        id: "interactive-table",
        name: "Interactive Table",
        description: "Fully interactive table with sort, select, expand, and edit capabilities. Features comprehensive toolbar, search, filters, and multi-functionality.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "interactive", "toolbar", "search", "filters", "edit"],
        previewUrl: "/SpecialElements/Tables/InteractiveTable",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "core-playground",
        name: "Core Playground",
        description: "Visual table playground with configurable styling options. Features toggle controls for striped, bordered, dense, hover, and ghost styles.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "playground", "configurable", "styling", "variations"],
        previewUrl: "/SpecialElements/Tables/CorePlayground",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "lucide-react"],
        props: [],
    },
    {
        id: "business-tables",
        name: "Business Tables",
        description: "Business-focused table patterns including pricing, schedule, and invoice tables. Features tabbed interface, comparison tables, and business data presentation.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "business", "pricing", "schedule", "invoice", "comparison"],
        previewUrl: "/SpecialElements/Tables/BusinessTables",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "lucide-react"],
        props: [],
    },
];

