import { getCode } from "../getCode";
import { Component } from "../types";

export const tablesComponents: Component[] = [
    {
        id: "minimal-table",
        name: "Minimal Table",
        description: "Simple minimal table with clean typography and subtle borders. Features hover states and clean data presentation without visual clutter.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "minimal", "simple", "clean", "data"],
        previewUrl: "/SpecialElements/Tables/MinimalTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/MinimalTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/MinimalTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/MinimalTable/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Excellent for text-heavy reports, minimalist dashboards, and Next.js platforms that want a clean 'Minimal' table aesthetic. Use this table for simple data presentation without visual clutter.",
        bestPractices: "Maintain consistent spacing within your design system by keeping the table cells aligned. Follow React best practices by pairing this with sharp, technical typography. Optimize for performance by using efficient CSS border renders.",
        whyMatters: "Minimalist-based data layouts communicate digital flow, clarity, and modern craft. This production-ready UI template helpsคุณ build an interface that feels responsive and organized, adding a unique 'Moving' signature to your page.",
        faqs: [
            { question: "How does the hover work?", answer: "The component uses localized CSS selectors and layout-id transitions to highlight the active row, creating a high-fidelity 'opening' effect." },
            { question: "Can I adjust cell padding?", answer: "Absolutely, you can adjust both the primary `backgroundColor` and specific cell padding to match your project's specific terminology." },
            { question: "Is it mobile responsive?", answer: "The table columns and typographic scales adapt for mobile, ensuring the data remains impactful and structural on small screens." }
        ],
    },
    {
        id: "striped-rows-table",
        name: "Striped Rows Table",
        description: "Table with alternating striped rows for improved readability. Features zebra striping, hover effects, and enhanced visual hierarchy.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "striped", "rows", "zebra", "readability"],
        previewUrl: "/SpecialElements/Tables/StripedRowsTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/StripedRowsTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/StripedRowsTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/StripedRowsTable/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Ideal for edges data sets, technical archives, and Next.js platforms that want a dramatic 'Striped' aesthetic. Use this layout to communicate structural scale and digital craft through alternating partitions.",
        bestPractices: "Maintain consistent spacing within your design system by using it for focal content blocks. Follow React best practices by pairing it with bold, professional typography. Optimize for performance by using efficient layout-id transitions.",
        whyMatters: "Striped-based data layouts communicate power, mystery, and structural honesty. This production-ready UI template helpsคุณ build an interface that feels authoritative and solid, breaking the 'standard' vertical list rules.",
        faqs: [
            { question: "Why 'Striped'?", answer: "The component features alternating background colors for each row, simulating the raw structural honesty of architectural blueprint expansion." },
            { question: "Can I adjust colors?", answer: "Yes, both the primary 'activeItemBgColor' and background colors are fully configurable allowedคุณ to create 'Industrial' or 'Cyber' agency effects." },
            { question: "Is it mobile responsive?", answer: "The rows and typographic scales adapt dynamically for mobile, Ensuring the bold narrative remains impactful and structural on small screens." }
        ],
    },
    {
        id: "sortable-table",
        name: "Sortable Table",
        description: "Table with sortable columns and visual sort indicators. Features ascending/descending sort states, animated sort icons, and multi-column sorting support.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "sortable", "sorting", "columns", "interactive"],
        previewUrl: "/SpecialElements/Tables/SortableTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/SortableTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/SortableTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/SortableTable/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Excellent for data-rich dashboards, searchable archives, and Next.js applications that want a high-tech 'Sortable' aesthetic. Use this table to provide clear, tactile feedback during data organization.",
        bestPractices: "Maintain scalable component architecture by pairing this with sharp, technical typography. Follow React best practices by using Framer Motion for the sort icon transitions. Optimize for performance by managed the row renders.",
        whyMatters: "Sortable-based data layouts communicate technical authority, sophistication, and digital craft. This production-ready UI template helpsคุณ build an interface that feels organized and high-end, adding a unique 'Studio' signatures to your brand.",
        faqs: [
            { question: "How does sorting work?", answer: "The component uses localized state management and arrow indicators to visually 'react' to user sorting requests, allowedคุณ to create high-fidelity 'ordering' effects." },
            { question: "Are colors dynamic?", answer: "Absolutely, you can customize both the primary `activeHeaderColor` and specific icon glows to match your brand's specific high-intensity palette." },
            { question: "Is it mobile responsive?", answer: "The column widths and typographic scales adapt for mobile, ensuring the objective clarity remains consistent on high-density mobile screens." }
        ],
    },
    {
        id: "selectable-table",
        name: "Selectable Table",
        description: "Table with row selection functionality and checkboxes. Features select all, individual row selection, and visual selection indicators.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "selectable", "selection", "checkboxes", "multi-select"],
        previewUrl: "/SpecialElements/Tables/SelectableTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/SelectableTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/SelectableTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/SelectableTable/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Ideal for user management systems, selection-heavy lists, and Next.js platforms that want an organic 'Selectable' aesthetic. Use this layout to communicate power and digital intelligence through micro-checkboxes.",
        bestPractices: "Maintain scalable component architecture by pairing this with sharp, technical icons. Follow React best practices by using Framer Motion for the checkbox reveal transitions. Optimize for performance by managed the row renders.",
        whyMatters: "Selectable-based data layouts communicate power, efficiency, and structural honesty. This production-ready UI template helpsคุณ build an interface that feels authoritative and solid, adding a unique signature to your toolkit.",
        faqs: [
            { question: "How work selection?", answer: "The component features localized absolute positioning and spring physics to 'snap' the background highlight to the selected row, simulating the raw structural honesty of architectural blueprint modules." },
            { question: "Are colors dynamic?", answer: "Yes, both the primary 'selectionColor' and background glows can be adjusted to create 'Industrial' or 'Cyber' agency effects." },
            { question: "Is it mobile responsive?", answer: "The checkbox spans and typographic scales adapt for mobile, ensuring the micro-narrative remains impactful and structural on small screens." }
        ],
    },
    {
        id: "expandable-table",
        name: "Expandable Table",
        description: "Table with expandable rows showing additional details. Features collapsible rows, smooth expand/collapse animations, and nested content display.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "expandable", "collapsible", "details", "nested"],
        previewUrl: "/SpecialElements/Tables/ExpandableTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/ExpandableTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/ExpandableTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/ExpandableTable/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Ideal for high-end digital agencies, creative portfolios, and Next.js applications that want a premium 'Expandable' aesthetic. Use this table for an immersive experience with collapsible modules and light refraction cues.",
        bestPractices: "Maintain consistent spacing within your design system by keeping the path items organized. Follow React best practices by pairing this with soft, neutral colors. Optimize for performance by managed the amount of blur renders.",
        whyMatters: "Glass-based aesthetics communicate digital excellence, sophistication, and high-end craft. This production-ready UI template helpsคุณ build an interface that feels curated and premium, leaving a lasting visual impression on high-value clients.",
        faqs: [
            { question: "Is the 'Expand' real?", answer: "The component uses localized backdrop-filter blur and subtle inner glows (glass-shadows) to simulate light refraction through high-fidelity translucent surfaces during module expansion." },
            { question: "Can I change icons?", answer: "Absolutely, both the primary 'backgroundColor' (gradient or solid) and the persistent expansion icons are fully configurable to match your digital brand." },
            { question: "Is it mobile responsive?", answer: "The expandable modules adapt their spans and layouts for mobile, ensuring the refractive narrative remains impactful and legible on small screens." }
        ],
    },
    {
        id: "sticky-header-table",
        name: "Sticky Header Table",
        description: "Table with sticky header that remains visible while scrolling. Features fixed header position, smooth scrolling, and enhanced navigation for long data sets.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "sticky", "header", "scroll", "fixed"],
        previewUrl: "/SpecialElements/Tables/StickyHeaderTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/StickyHeaderTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/StickyHeaderTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/StickyHeaderTable/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Excellent for long-form data tables, documentation indices, and Next.js applications that want a high-tech 'Sticky' aesthetic. Use this layout to communicate hierarchical power and digital intelligence through fixed headers.",
        bestPractices: "Maintain scalable component architecture by pairing this with high-contrast imagery. Follow React best practices by using Framer Motion for the header reveal transitions. Optimize for performance by managed the header renders.",
        whyMatters: "Sticky-header agency layouts communicate technical authority, sophistication, and digital craft. This production-ready UI template helpsคุณ build an interface that feels organized and high-end, adding a unique 'Corporate' signatures to your brand navigation.",
        faqs: [
            { question: "What is 'Sticky'?", answer: "The component features localized CSS absolute positioning and mask-composite filters to simulate high-fidelity industrial header anchoring while scrolling." },
            { question: "Are colors dynamic?", answer: "Yes, both the primary header accent and background intensities can be adjusted to create 'Industrial' or 'Cyber' agency effects." },
            { question: "Is it mobile responsive?", answer: "The header columns and typographic scales adapt for mobile, ensuring the bold narrative remains impactful and structural on small screens." }
        ],
    },
    {
        id: "badge-table",
        name: "Badge Table",
        description: "Table with status badges for visual data categorization. Features colored status badges, dot indicators, and enhanced visual hierarchy.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "badge", "status", "indicators", "categorization"],
        previewUrl: "/SpecialElements/Tables/BadgeTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/BadgeTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/BadgeTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/BadgeTable/page.tsx") },
        dependencies: ["lucide-react"],
        props: [],
        whenToUse: "Ideal for user directories, CRM dashboards, and Next.js platforms that want a sharp 'Badge' aesthetic. Use this layout to showcase options with a mix of status labels and technical typography.",
        bestPractices: "Follow React best practices by pairing this with professional, high-contrast imagery. Maintain consistent spacing within your design system by keeping the grid gaps uniform. Optimize for performance by using efficient layout-id transitions.",
        whyMatters: "Minimalist badge-based layouts communicate digital excellence, organization, and attention to detail. This production-ready UI template helpsคุณ build an interface that feels curated and premium, leaving a lasting visual impression on high-value clients.",
        faqs: [
            { question: "How does status work?", answer: "The component features localized color mappings and layout-id transitions to move the active badges between rows, creating a high-fidelity 'opening' effect." },
            { question: "Can I adjust labels?", answer: "Absolutely, both the primary 'badges' and specific weights are fully configurable, allowedคุณ to create 'High-Contrast' magazine effects." },
            { question: "Is it mobile responsive?", answer: "The status indicators and typographic scales adapt for mobile, ensuring the 'Draft' narrative remains impactful and structural on small screens." }
        ],
    },
    {
        id: "avatar-table",
        name: "Avatar Table",
        description: "Table with avatar cells showing user images and information. Features avatar displays, user names, emails, and enhanced user identification.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "avatar", "user", "profile", "identification"],
        previewUrl: "/SpecialElements/Tables/AvatarTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/AvatarTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/AvatarTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/AvatarTable/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Excellent for team directories, high-end digital platforms, and Next.js applications that want an organic 'Avatar' aesthetic. Use this table for an immersive experience with user profiles and light refraction cues.",
        bestPractices: "Maintain consistent spacing within your design system by keeping the items organized and legible. Follow React best practices by pairing this with bold, professional typography. Optimize for performance by managed the avatar renders.",
        whyMatters: "Avatar-based aesthetics communicate digital excellence, fluidity, and modern craft. This production-ready UI template helpsคุณ build an interface that feels alive and premium, adding a unique architectural signature to your brand interaction.",
        faqs: [
            { question: "Why 'Avatar'?", answer: "The component features localized image scales and high-fidelity overlays to simulate the raw structural honesty of the architectural media movement." },
            { question: "Can I adjust status?", answer: "Absolutely, you can adjust both the primary `backgroundColor` and specific user status highlights to match your brand's specific intensity." },
            { question: "Is it mobile responsive?", answer: "The user avatars and typographic weights adapt for mobile, ensuring the objective clarity remains consistent on high-density mobile screens." }
        ],
    },
    {
        id: "actions-table",
        name: "Actions Table",
        description: "Table with inline action buttons for each row. Features edit, delete, and view actions with hover states and icon buttons.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "actions", "buttons", "inline", "interactive"],
        previewUrl: "/SpecialElements/Tables/ActionsTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/ActionsTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/ActionsTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/ActionsTable/page.tsx") },
        dependencies: ["lucide-react"],
        props: [],
        whenToUse: "Excellent for side-navigation menus, action-driven toolkits, and Next.js applications that want an organic 'Action' aesthetic. Use this table to save space while maintaining easy access to tool buttons.",
        bestPractices: "Maintain scalable component architecture by pairing this with sharp, technical typography. Follow React best practices by using Framer Motion for the button reveal transitions. Optimize for performance by managed the layout-id.",
        whyMatters: "Action-based animations communicate digital flow, efficiency, and modern craft. This production-ready UI template helpsคุณ build an interface that feels responsive and organized, adding a unique 'Moving' signature to your brand.",
        faqs: [
            { question: "How does 'Action' work?", answer: "The component uses localized x-offsets and spring physics to 'reveal' the tool icons as users interaction with the rows, creating a high-fidelity 'opening' effect." },
            { question: "Are colors dynamic?", answer: "Absolutely, you can adjust both the primary `backgroundColor` and specific highlight colors to match your brand's specific high-intensity palette." },
            { question: "Is it mobile responsive?", answer: "The action buttons and typographic scales adapt for mobile, ensuring the 'Action' narrative remains impactful and structural on small screens." }
        ],
    },
    {
        id: "pagination-table",
        name: "Pagination Table",
        description: "Table with pagination footer for navigating large datasets. Features page navigation controls, page indicators, and previous/next buttons.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "pagination", "navigation", "pages", "footer"],
        previewUrl: "/SpecialElements/Tables/PaginationTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/PaginationTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/PaginationTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/PaginationTable/page.tsx") },
        dependencies: ["lucide-react"],
        props: [],
        whenToUse: "Ideal for large data sets, paginated reports, and Next.js platforms that want a meaningful 'Paginated' aesthetic. Use this table footer to communicate digital excellence through discrete modules and visual navigation cues.",
        bestPractices: "Maintain consistent spacing within your design system by using it for focal narratives. Follow React best practices by pairing this with bold, professional typography. Optimize for performance by using efficient data chunking.",
        whyMatters: "Perspective-based navigation communicates technical reliability, clarity, and timeless craft. This production-ready UI template helpsคุณ build an interface that feels organized and professional, reflecting a brand identity rooted in design purity.",
        faqs: [
            { question: "How does 'Page' work? ", answer: "The component features localized index mapping and high-fidelity transitions to simulate the raw structural honesty of architectural blueprint failures, focusing on both data and movement." },
            { question: "Can I adjust labels?", answer: "Absolutely, you can adjust both the original `pagination` and specific `labels` to match your project's specific terminology." },
            { question: "Is it mobile responsive?", answer: "The navigation controls and typographic scales adapt for mobile, ensuring the objective clarity remains consistent on high-density mobile screens." }
        ],
    },
    {
        id: "interactive-table",
        name: "Interactive Table",
        description: "Fully interactive table with sort, select, expand, and edit capabilities. Features comprehensive toolbar, search, filters, and multi-functionality.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "interactive", "toolbar", "search", "filters", "edit"],
        previewUrl: "/SpecialElements/Tables/InteractiveTable",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/InteractiveTable.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/InteractiveTable.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/InteractiveTable/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Excellent for comprehensive dashboard systems, edit-heavy data grids, and Next.js platforms that want a high-tech 'Interactive' aesthetic. Use this table to provide a powerful toolset for managing complex information hierarchies.",
        bestPractices: "Maintain scalable component architecture by pairing this with sharp, technical icons. Follow React best practices by using Framer Motion for the toolbar transitions. Optimize for performance by managed the row renders.",
        whyMatters: "Interactive agency layouts communicate technical authority, sophistication, and digital craft. This production-ready UI template helpsคุณ build an interface that feels organized and high-end, adding a unique 'Corporate' signatures to your brand toolkit.",
        faqs: [
            { question: "What is 'Interactive'?", answer: "The component features localized state combinations (sort/select/expand) and high-fidelity transitions to simulate high-fidelity industrial data control bleeding from the module edges." },
            { question: "Are colors dynamic?", answer: "Yes, both the primary 'accentColor' and background intensities can be adjusted to create 'Industrial' or 'Cyber' agency effects." },
            { question: "Is it mobile responsive?", answer: "The toolbar spans and typographic scales adapt for mobile, ensuring the bold narrative remains impactful and structural on small screens." }
        ],
    },
    {
        id: "core-playground",
        name: "Core Playground",
        description: "Visual table playground with configurable styling options. Features toggle controls for striped, bordered, dense, hover, and ghost styles.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "playground", "configurable", "styling", "variations"],
        previewUrl: "/SpecialElements/Tables/CorePlayground",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/CorePlayground.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/CorePlayground.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/CorePlayground/page.tsx") },
        dependencies: ["lucide-react"],
        props: [],
        whenToUse: "Ideal for developer tools, design system documentation, and Next.js platforms that want a 'Playground' aesthetic. Use this table to communicate powerful utility and structural honestly through selectable styles.",
        bestPractices: "Maintain consistent spacing within your design system by using it for aggressive brand storytelling. Follow React best practices by pairing it with bold, technical typography. Optimize for performance by managed the style transitions.",
        whyMatters: "Diagonal-based aesthetics communicate power, mystery, and structural honesty. This production-ready UI template helpsคุณ build an interface that feels authoritative and solid, breaking the 'standard' web layout rules.",
        faqs: [
            { question: "Why 'Playground'?", answer: "The component features skewed containers and slanted text paths to simulate the raw structural honesty of the brutalist architectural movement." },
            { question: "Can I adjust colors?", answer: "Yes, both the primary 'backgroundColor' and the specific 'badgeColor' are fully configurable, allowedคุณ to create 'Cyber' or 'Industrial' pop effects." },
            { question: "Is it mobile responsive?", answer: "The playground rows adapt their spans dynamically for mobile, Ensuring the bold narrative remains impactful and structural on small screens." }
        ],
    },
    {
        id: "business-tables",
        name: "Business Tables",
        description: "Business-focused table patterns including pricing, schedule, and invoice tables. Features tabbed interface, comparison tables, and business data presentation.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "table", "business", "pricing", "schedule", "invoice", "comparison"],
        previewUrl: "/SpecialElements/Tables/BusinessTables",
        code: {
            tsx: getCode("src/components/SpecialElements/Tables/tsx/BusinessTables.tsx"),
            jsx: getCode("src/components/SpecialElements/Tables/jsx/BusinessTables.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Tables/BusinessTables/page.tsx") },
        dependencies: ["lucide-react"],
        props: [],
        whenToUse: "Excellent for pricing pages, corporate schedules, and Next.js applications that want a high-tech 'Business' aesthetic. Use this table to communicate power, security, and digital intelligence through dark themes and architectural grid modules.",
        bestPractices: "Maintain scalable component architecture by pairing this with sharp, technical typography. Follow React best practices by using Framer Motion for the module reveal transitions. Optimize for performance by managed the border renders.",
        whyMatters: "Business-based agency layouts communicate technical authority, sophistication, and digital craft. This production-ready UI template helpsคุณ build an interface that feels organized and high-end, adding a unique 'Corporate' signatures to your brand.",
        faqs: [
            { question: "How work 'Business' tables?", answer: "The component is designed with technical 'Indices' and architectural aesthetics to simulate a high-quality technical repository for your project details." },
            { question: "Can I adjust the tabs?", answer: "Yes, both the primary 'tabs' array and background colors can be adjusted to create 'Industrial' or 'Cyber' agency effects." },
            { question: "Is it mobile responsive?", answer: "The grid spans adapt dynamically for mobile, ensuring the bold narrative remains impactful and structural on small screens." }
        ],
    },
];

