import { Component } from "../types";

export const featureSectionComponentsMetadata: Component[] = [
    {
        id: "uilora-showcase",
        name: "Uilora Showcase",
        description: "Purple gradient feature showcase with white card container and visual mockups.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["feature", "showcase", "gradient", "card", "mockup"],
        previewUrl: "/ContentBlocks/FeatureSections/UiloraShowcase",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "features", type: "Array<{label, title, description, visual}>", default: "3 Uilora features", description: "Array of feature items with label, title, description, and visual mockup." },
            { name: "title", type: "string", default: "Our Primary Features", description: "Section heading text." },
            { name: "subtitle", type: "string", default: "Introducing Uilora...", description: "Section subtitle text." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for gradient and badge." },
        ],
    },
    {
        id: "uilora-editorial",
        name: "Uilora Editorial",
        description: "Clean editorial feature section with stats row, accent bars, and geometric illustration.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["feature", "editorial", "stats", "minimal", "clean"],
        previewUrl: "/ContentBlocks/FeatureSections/UiloraEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title, description, icon, color}>", default: "4 Uilora features", description: "Array of feature items with title, description, icon, and accent color." },
            { name: "title", type: "string", default: "Powerful, seamless component personalization", description: "Section heading text." },
            { name: "subtitle", type: "string", default: "Uilora empowers developers...", description: "Section subtitle text." },
            { name: "accentColor", type: "string", default: "#E8546A", description: "Primary accent color for heading bar and highlights." },
        ],
    },
    {
        id: "uilora-insights",
        name: "Uilora Insights",
        description: "Scroll-driven accordion feature section with smooth image panel transitions.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["feature", "accordion", "scroll", "insights", "image"],
        previewUrl: "/ContentBlocks/FeatureSections/UiloraInsights",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "features", type: "Array<{icon, title, description, visual}>", default: "6 Uilora features", description: "Array of feature items with icon, title, description, and visual panel." },
            { name: "title", type: "string", default: "Track What Matters", description: "Section heading text." },
            { name: "subtitle", type: "string", default: "BUILT-IN-INSIGHTS", description: "Uppercase tag above the heading." },
            { name: "accentColor", type: "string", default: "#1a1a1a", description: "Accent color for active indicator." },
        ],
    },
    {
        id: "parallax-feature",
        name: "Editorial Parallax",
        description: "Elegant parallax feature section with scroll-driven animations and editorial typography.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["feature", "parallax", "editorial", "scroll", "luxury"],
        previewUrl: "/ContentBlocks/FeatureSections/ParallaxFeature",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "features", type: "Array<{number, title, description}>", default: "3 Uilora steps", description: "Array of numbered feature items." },
            { name: "title", type: "string", default: "Crafted with Precision", description: "Large editorial heading text." },
            { name: "subtitle", type: "string", default: "Every detail matters.", description: "Italic subtitle text." },
            { name: "image", type: "string", default: "Unsplash abstract art", description: "Hero image URL for the parallax panel." },
        ],
    },
    {
        id: "tabs-feature",
        name: "Interactive Tabs",
        description: "Tabbed feature section with smooth transitions and styled visual mockups.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["feature", "tabs", "interactive", "transitions"],
        previewUrl: "/ContentBlocks/FeatureSections/TabsFeature",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "tabs", type: "Array<{label, icon, title, description, visual}>", default: "3 Uilora tabs", description: "Array of tab items with label, icon, content, and visual mockup." },
            { name: "title", type: "string", default: "Everything you need to ship faster.", description: "Section heading text." },
            { name: "subtitle", type: "string", default: "Uilora gives you the tools...", description: "Section subtitle text." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for active tab indicator and highlights." },
        ],
    },
    {
        id: "brutalist-feature",
        name: "Neo-Brutalist",
        description: "Bold neo-brutalist feature section with chunky borders, hard shadows, and raw typography.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["feature", "brutalist", "bold", "chunky"],
        previewUrl: "/ContentBlocks/FeatureSections/BrutalistFeature",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "features", type: "Array<{title, description, color}>", default: "4 Uilora features", description: "Array of feature items with title, description, and accent color." },
            { name: "title", type: "string", default: "Make it", description: "Section title text." },
            { name: "subtitle", type: "string", default: "Pop.", description: "Section subtitle text." },
            { name: "accentColor", type: "string", default: "#FF3B30", description: "Accent color for hero card and badge." },
        ],
    },
    {
        id: "accordion-feature",
        name: "Dark Spotlight",
        description: "Dark accordion feature section with sliding indicator and spotlight panel.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["feature", "dark", "spotlight", "accordion"],
        previewUrl: "/ContentBlocks/FeatureSections/AccordionFeature",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "features", type: "Array<{title, description, icon}>", default: "4 Uilora features", description: "Array of feature items with title, description, and lucide icon." },
            { name: "title", type: "string", default: "Built for Uilora", description: "Section heading text." },
            { name: "subtitle", type: "string", default: "Everything you need...", description: "Section subtitle text." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for active indicator and highlights." },
        ],
    },
    {
        id: "event-horizon",
        name: "Event Horizon",
        description: "Cosmic feature section with scroll-driven conic gradient and glassmorphic cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["feature", "cosmic", "depth", "glass"],
        previewUrl: "/ContentBlocks/FeatureSections/EventHorizon",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "features", type: "Array<{icon, title, description}>", default: "4 Uilora features", description: "Array of feature items with icon, title, and description." },
            { name: "title", type: "string", default: "Beyond the Surface", description: "Section heading text." },
            { name: "subtitle", type: "string", default: "Uilora components go deeper...", description: "Section subtitle text." },
            { name: "accentColor", type: "string", default: "#a855f7", description: "Accent color for gradient glow and hover effects." },
        ],
    },
];