import { getCode } from "../getCode";
import { Component } from "../types";

export const paginationComponents: Component[] = [
    {
        id: "uilora-swipe-pagination",
        name: "Uilora Swipe",
        description: "Swipe card pagination with spring animations, gradient overlays, and dot indicators.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pagination", "swipe", "cards", "spring", "dark"],
        previewUrl: "/ContentBlocks/Pagination/UiloraSwipe",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/UiloraSwipe.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/UiloraSwipe.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/UiloraSwipe/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "pages", type: "Array<{title, description, image}>", default: "5 Uilora pages", description: "Page items with title, description, and image URL." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for active dot indicator." },
            { name: "autoPlay", type: "boolean", default: "false", description: "Enable auto-play slideshow." },
            { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
        ],
        whenToUse: "Great for hero sliders, product showcases, and portfolio galleries that need smooth card-style pagination with spring physics.",
        bestPractices: "Use high-quality landscape images. Keep titles short for clean overlay text. 4-6 pages works best for engagement.",
        whyMatters: "Spring-physics card transitions create a premium, app-like feel that elevates standard image carousels into interactive experiences.",
        faqs: [
            { question: "Does it support swipe gestures?", answer: "Yes, you can extend it with framer-motion drag gestures for touch-based swiping." },
            { question: "Can I autoplay?", answer: "The autoPlay prop enables automatic page cycling at a set interval." },
        ],
    },
    {
        id: "uilora-fade-pagination",
        name: "Uilora Fade",
        description: "Crossfade gallery pagination with thumbnail previews and editorial counter.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pagination", "fade", "gallery", "thumbnails", "editorial"],
        previewUrl: "/ContentBlocks/Pagination/UiloraFade",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/UiloraFade.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/UiloraFade.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/UiloraFade/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "pages", type: "Array<{title, image}>", default: "5 aesthetic pages", description: "Page items with title and image URL." },
            { name: "accentColor", type: "string", default: "#000000", description: "Accent color for active thumbnail border." },
            { name: "showThumbnails", type: "boolean", default: "true", description: "Show thumbnail strip below main image." },
            { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
        ],
        whenToUse: "Perfect for portfolio lookbooks, photography galleries, and editorial content where smooth crossfade transitions and thumbnail navigation enhance the viewing experience.",
        bestPractices: "Use consistent aspect ratio images for the best thumbnail strip appearance. 4-8 pages provide good navigation density.",
        whyMatters: "Crossfade transitions feel elegant and intentional compared to sliding. The thumbnail strip provides at-a-glance navigation that improves usability.",
        faqs: [
            { question: "Can I hide thumbnails?", answer: "Yes, set showThumbnails to false for a cleaner layout with only arrow navigation." },
            { question: "Does it support keyboard navigation?", answer: "You can extend it with keyboard event listeners for arrow key navigation." },
        ],
    },
    {
        id: "uilora-stack-pagination",
        name: "Uilora Stack",
        description: "3D stacked depth pagination with perspective cards and glass info bar.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pagination", "stack", "3d", "depth", "perspective", "dark"],
        previewUrl: "/ContentBlocks/Pagination/UiloraStack",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/UiloraStack.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/UiloraStack.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/UiloraStack/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "pages", type: "Array<{title, image}>", default: "5 design pages", description: "Page items with title and image URL." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for active dot." },
            { name: "visibleCards", type: "number", default: "3", description: "Number of stacked cards visible." },
            { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
        ],
        whenToUse: "Ideal for creative portfolios, product showcases, and landing pages that want a unique 3D card stack effect with depth perception.",
        bestPractices: "Use 3 visible cards for the cleanest depth effect. Square or portrait images work best for the stacked layout.",
        whyMatters: "The stacked card metaphor creates a tangible sense of browsing through a deck, making the interaction feel physical and premium.",
        faqs: [
            { question: "Can I click to advance?", answer: "Yes, clicking the front card cycles to the next page. You can also use the arrow buttons or dots." },
            { question: "Does it loop?", answer: "Yes, the stack loops infinitely — the last card wraps back to the first." },
        ],
    },
    {
        id: "classic-pagination",
        name: "Classic Pagination",
        description: "Comprehensive pagination showcase with 8 different variants including minimal, floating pill, neo-brutalist, glassmorphism, circular, scrollable, dots, and smart jump styles.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "classic", "variants", "navigation", "ui"],
        previewUrl: "/ContentBlocks/Pagination/Classic",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/Classic.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/Classic.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/Classic/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes." },
        ],
        whenToUse: "Ideal for data-rich applications, e-commerce sites, and blogs that need a reliable, versatile navigation system. Use this React component to showcase multiple pagination styles including minimal, pill, and brutalist variants in one place.",
        bestPractices: "Maintain consistent spacing within your design system by choosing the variant that best matches your overall brand aesthetic. Follow React best practices by using high-contrast colors for active page states. Optimize for performance by using efficient state management for page changes.",
        whyMatters: "Pagination is critical for user experience in long lists of content. This production-ready UI component provides 8 distinct visual signatures, givingคุณ the flexibility to build an interface that feels tailored to your specific application architecture.",
        faqs: [
            { question: "How many styles are included?", answer: "The component features 8 unique styles: Minimal, Floating Pill, Neo-Brutalist, Glassmorphism, Circular, Scrollable, Dots, and Smart Jump." },
            { question: "Is it mobile responsive?", answer: "Yes, all variants are designed to scale gracefully, with some (like the scrollable style) specifically optimized for touch-based navigation." },
            { question: "Can I customize the colors?", answer: "Absolutely, each variant uses local Tailwind classes that can be easily overridden to match your project's color palette." }
        ],
    },
    {
        id: "cinematic-slice-pagination",
        name: "Cinematic Slice Pagination",
        description: "Dramatic cinematic image pagination with 3-slice vertical animation and blur depth effects. High-end visual transitions with gradient overlays.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "cinematic", "slice", "image", "animation", "visual"],
        previewUrl: "/ContentBlocks/Pagination/CinematicSlice",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/CinematicSlice.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/CinematicSlice.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/CinematicSlice/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
        whenToUse: "Perfect for high-end photography portfolios, cinematic brand experiences, and Next.js sites that want a dramatic visual transition. Use this React component for image-based pagination with vertical slice animations and blur depth effects.",
        bestPractices: "Follow React best practices by pairing this with high-resolution, high-impact imagery. Maintain scalable component architecture by keeping the `totalPages` low for maximum impact. Optimize performance by using hardware-accelerated transforms for the slice animations.",
        whyMatters: "Vertical slice transitions add a layer of production value and cinematic polish that standard fades lack. This customizable UI component givesคุณ a hardware-accelerated version of this aesthetic, improving user engagement through visual storytelling.",
        faqs: [
            { question: "How does the slice animation work?", answer: "The image is split into three vertical sections that animate independently with slight delays, creating a 'shutter' or 'glitch' entry effect." },
            { question: "Can I adjust the slice count?", answer: "The current version is hard-coded to 3 slices for optimal balance, but the component's internal logic can be extended for more segments." },
            { question: "Does it support video?", answer: "The slice logic is optimized for images, but can be adapted for HTML5 videos to create ultra-premium motion background transitions." }
        ],
    },
    {
        id: "cube-flip-pagination",
        name: "Cube Flip Pagination",
        description: "3D cube flip animation pagination with perspective transforms. Smooth 3D rotation effects for image galleries.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "cube", "flip", "3d", "perspective", "animation"],
        previewUrl: "/ContentBlocks/Pagination/CubeFlip",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/CubeFlip.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/CubeFlip.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/CubeFlip/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
        whenToUse: "Excellent for gaming dashboards, interactive portfolios, and Next.js sites that want a tactile, 3D 'cube' feel. Use this React component for image pagination with perspective transforms and smooth 3D rotation effects.",
        bestPractices: "Maintain consistent spacing within your design system by using it as a primary gallery element. Follow React best practices by choosing images with similar aspect ratios. Optimize for performance by managed the perspective depth for different screen sizes.",
        whyMatters: "3D transforms increase the perceived value and interactivity of a digital interface. This production-ready component helpsคุณ build an interface that feels deep and tangible, turning standard navigation into a 3D experience.",
        faqs: [
            { question: "What is the rotation angle?", answer: "The component performs a full 90-degree vertical rotation between pages, creating the illusion of a continuous rotating solid." },
            { question: "Does it work in Safari?", answer: "Yes, it uses hardware-accelerated CSS 3D transforms with appropriate `backface-visibility` settings for cross-browser support." },
            { question: "Can I change the direction?", answer: "The current implementation is vertical, but the `rotateX` transforms can be swapped for `rotateY` to create a horizontal cube flip." }
        ],
    },
    {
        id: "liquid-distortion-pagination",
        name: "Liquid Distortion Pagination",
        description: "Liquid distortion wave transition effects with blur and color blend modes. Smooth morphing animations for page changes.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "liquid", "distortion", "wave", "morphing", "animation"],
        previewUrl: "/ContentBlocks/Pagination/LiquidDistortion",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/LiquidDistortion.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/LiquidDistortion.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/LiquidDistortion/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
        whenToUse: "Perfect for deep-tech brands, artistic portfolios, and Next.js experiences that want an organic, fluid feel. Use this React component for image pagination with morphing liquid waves and color blending effects.",
        bestPractices: "Maintain scalable component architecture by pairing this with vibrant, high-contrast images. Follow React best practices by using subtle wave amplitudes to ensure the text remains legible. Optimize performance by using efficient SVG filters for the distortion.",
        whyMatters: "Liquid distortion adds a sense of flow and organic life to digital screens. This production-ready component helpsคุณ build an interface that feels atmospheric and advanced, adding semantic authority to your project's digital architecture.",
        faqs: [
            { question: "How does the distortion work?", answer: "It uses a displacement map filter combined with perlin noise to warp the image texture in a fluid, wave-like pattern during transitions." },
            { question: "Can I control the wave speed?", answer: "Yes, the internal animation duration can be customized to create anything from slow, deep drifts to rapid, energetic ripples." },
            { question: "Is it mobile responsive?", answer: "Absolutely, the SVG filters scale with the canvas, ensuring a consistent liquid experience on both desktop and mobile devices." }
        ],
    },
    {
        id: "parallax-strip-pagination",
        name: "Parallax Strip Pagination",
        description: "Parallax scrolling image strip with thumbnail navigation. Smooth horizontal scrolling with depth effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "parallax", "strip", "scroll", "thumbnail", "gallery"],
        previewUrl: "/ContentBlocks/Pagination/ParallaxStrip",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/ParallaxStrip.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/ParallaxStrip.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/ParallaxStrip/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
        whenToUse: "Ideal for editorial layouts, travel blogs, and Next.js sites that want a sophisticated, scrolling 'film strip' aesthetic. Use this React component for a parallax-driven image strip with thumbnail-based navigation and depth effects.",
        bestPractices: "Maintain consistent spacing within your design system by using it as a central focus element. Follow React best practices by using horizontal layouts. Optimize performance by lazy-loading images in the hidden segments of the strip.",
        whyMatters: "Horizontal strip layouts provide a unique narrative flow that breaks away from standard vertical scrolling. This production-ready component helpsคุณ build an interface that feels expensive and cinematic, improving user exploration speeds.",
        faqs: [
            { question: "How does the parallax feel?", answer: "The images move at a different speed than the thumbnail strip, creating a sense of depth and 3D space during navigation." },
            { question: "Can I add titles to each strip?", answer: "Yes, the current structure can be easily extended to include text overlays on each image for better context and SEO." },
            { question: "Is it touch-enabled?", answer: "The component is optimized for click-based navigation, but supports standard horizontal swipe gestures on touch-enabled mobile devices." }
        ],
    },
    {
        id: "vertical-accordion-pagination",
        name: "Vertical Accordion Pagination",
        description: "Vertical accordion-style pagination with expandable panels. Smooth flex animations with grayscale to color transitions.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "vertical", "accordion", "expandable", "panels", "animation"],
        previewUrl: "/ContentBlocks/Pagination/VerticalAccordion",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/VerticalAccordion.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/VerticalAccordion.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/VerticalAccordion/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "totalPages", type: "number", default: "4", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
        whenToUse: "Excellent for enterprise dashboards, architectural showcases, and Next.js applications that want a high-contrast 'Pro' aesthetic. Use this React component for vertical accordion-style pagination with expandable panels and grayscale-to-color transitions.",
        bestPractices: "Maintain consistent spacing within your design system by using it for high-impact navigation. Follow React best practices by pairing it with bold typography. Optimize performance by using efficient flex-basis transitions instead of heavy absolute positioning.",
        whyMatters: "Vertical accordions provide a unique way to browse content categories while maintaining visual focus. This production-ready UI component helpsคุณ build an interface that feels structured and professional, adding a layer of architectural depth.",
        faqs: [
            { question: "What is the color effect?", answer: "Inactive panels are desaturated (grayscale) to draw focus to the active panel, which is revealed in its full color palette." },
            { question: "Can I use it horizontally?", answer: "The current implementation is vertical, but the `flex-col` classes can be swapped for `flex-row` to create a horizontal accordion gallery." },
            { question: "How many panels can I have?", answer: "While you can have many, it's best to limit it to 4-6 panels to ensure each one has enough height for content when expanded." }
        ],
    },
    {
        id: "staggered-masonry-pagination",
        name: "Staggered Masonry Pagination",
        description: "Staggered masonry grid layout with directional animations. Gallery-style pagination with staggered entry effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "staggered", "masonry", "grid", "gallery", "animation"],
        previewUrl: "/ContentBlocks/Pagination/StaggeredMasonry",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pagination/tsx/StaggeredMasonry.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pagination/jsx/StaggeredMasonry.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pagination/StaggeredMasonry/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
        whenToUse: "Perfect for creative galleries, fashion lookbooks, and Next.js sites that want a dynamic, 'living' layout. Use this React component for a staggered masonry grid that animates in based on the directional flow of navigation.",
        bestPractices: "Follow React best practices by selecting images with varying aspect ratios to maximize the masonry effect. Maintain scalable component architecture by using clear grid gaps. Optimize performance by managed the staggered entry delays.",
        whyMatters: "Staggered layouts break the monotony of standard grids, making the process of viewing images feel more organic and less rigid. This production-ready UI component helpsคุณ build an interface that feels fresh and interactive, improving user retention through visual variety.",
        faqs: [
            { question: "How does the staggering work?", answer: "Each grid item is assigned a slightly different delay based on its position, creating a 'waterfall' effect as they animate into view." },
            { question: "Does it support infinite scroll?", answer: "The component is designed for paging, but can be integrated with intersection observers to create an infinite masonry list." },
            { question: "Can I change the column count?", answer: "Yes, the Tailwind grid classes (`grid-cols-1`, `md:grid-cols-2`, etc.) can be adjusted to fit your specific layout requirements." }
        ],
    },
];
