import { Component } from "../types";

export const paginationComponentsMetadata: Component[] = [
    {
        id: "uilora-swipe-pagination",
        name: "Uilora Swipe",
        description: "Swipe card pagination with spring animations, gradient overlays, and dot indicators.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pagination", "swipe", "cards", "spring", "dark"],
        previewUrl: "/ContentBlocks/Pagination/UiloraSwipe",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "pages", type: "Array<{title, description, image}>", default: "5 Uilora pages", description: "Page items with title, description, and image URL." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for active dot indicator." },
            { name: "autoPlay", type: "boolean", default: "false", description: "Enable auto-play slideshow." },
            { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
        ],
    },
    {
        id: "uilora-fade-pagination",
        name: "Uilora Fade",
        description: "Crossfade gallery pagination with thumbnail previews and editorial counter.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pagination", "fade", "gallery", "thumbnails", "editorial"],
        previewUrl: "/ContentBlocks/Pagination/UiloraFade",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "pages", type: "Array<{title, image}>", default: "5 aesthetic pages", description: "Page items with title and image URL." },
            { name: "accentColor", type: "string", default: "#000000", description: "Accent color for active thumbnail border." },
            { name: "showThumbnails", type: "boolean", default: "true", description: "Show thumbnail strip below main image." },
            { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
        ],
    },
    {
        id: "uilora-stack-pagination",
        name: "Uilora Stack",
        description: "3D stacked depth pagination with perspective cards and glass info bar.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pagination", "stack", "3d", "depth", "perspective", "dark"],
        previewUrl: "/ContentBlocks/Pagination/UiloraStack",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "pages", type: "Array<{title, image}>", default: "5 design pages", description: "Page items with title and image URL." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for active dot." },
            { name: "visibleCards", type: "number", default: "3", description: "Number of stacked cards visible." },
            { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
        ],
    },
    {
        id: "classic-pagination",
        name: "Classic Pagination",
        description: "Comprehensive pagination showcase with 8 different variants including minimal, floating pill, neo-brutalist, glassmorphism, circular, scrollable, dots, and smart jump styles.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "classic", "variants", "navigation", "ui"],
        previewUrl: "/ContentBlocks/Pagination/Classic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "cinematic-slice-pagination",
        name: "Cinematic Slice Pagination",
        description: "Dramatic cinematic image pagination with 3-slice vertical animation and blur depth effects. High-end visual transitions with gradient overlays.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "cinematic", "slice", "image", "animation", "visual"],
        previewUrl: "/ContentBlocks/Pagination/CinematicSlice",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
    },
    {
        id: "cube-flip-pagination",
        name: "Cube Flip Pagination",
        description: "3D cube flip animation pagination with perspective transforms. Smooth 3D rotation effects for image galleries.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "cube", "flip", "3d", "perspective", "animation"],
        previewUrl: "/ContentBlocks/Pagination/CubeFlip",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
    },
    {
        id: "liquid-distortion-pagination",
        name: "Liquid Distortion Pagination",
        description: "Liquid distortion wave transition effects with blur and color blend modes. Smooth morphing animations for page changes.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "liquid", "distortion", "wave", "morphing", "animation"],
        previewUrl: "/ContentBlocks/Pagination/LiquidDistortion",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
    },
    {
        id: "parallax-strip-pagination",
        name: "Parallax Strip Pagination",
        description: "Parallax scrolling image strip with thumbnail navigation. Smooth horizontal scrolling with depth effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "parallax", "strip", "scroll", "thumbnail", "gallery"],
        previewUrl: "/ContentBlocks/Pagination/ParallaxStrip",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
    },
    {
        id: "vertical-accordion-pagination",
        name: "Vertical Accordion Pagination",
        description: "Vertical accordion-style pagination with expandable panels. Smooth flex animations with grayscale to color transitions.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "vertical", "accordion", "expandable", "panels", "animation"],
        previewUrl: "/ContentBlocks/Pagination/VerticalAccordion",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion"],
        props: [
            { name: "totalPages", type: "number", default: "4", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
    },
    {
        id: "staggered-masonry-pagination",
        name: "Staggered Masonry Pagination",
        description: "Staggered masonry grid layout with directional animations. Gallery-style pagination with staggered entry effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["content-blocks", "pagination", "staggered", "masonry", "grid", "gallery", "animation"],
        previewUrl: "/ContentBlocks/Pagination/StaggeredMasonry",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "totalPages", type: "number", default: "5", description: "Total number of pages to paginate through." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
    },
];

