import { Component } from "../types";

export const testimonialComponentsMetadata: Component[] = [
    {
        id: "uilora-pixel-bloom",
        name: "Uilora Pixel Bloom",
        description: "Infinite circular carousel with per-card pastel backgrounds, floating DiceBear avatars at top, quote text, and name/rating at bottom.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "carousel", "pastel", "floating-avatar", "infinite", "light"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraPixelBloom",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, seed, cardColor}>", default: "6 pastel testimonials", description: "Testimonial items with per-card pastel color." },
            { name: "title", type: "string", default: "Learner Success Stories", description: "Section heading." },
            { name: "subtitle", type: "string", default: "See how our learners achieved success...", description: "Section subtitle." },
            { name: "accentColor", type: "string", default: "#7C3AED", description: "Accent color (reserved for future use)." },
        ],
    },
    {
        id: "uilora-wenzy",
        name: "Uilora Wenzy",
        description: "Light 2-up testimonial cards with colored borders, quote title, body text, star ratings, metric numbers, and trending revenue indicator.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "metric", "cards", "light", "revenue", "rating", "2-up"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraWenzy",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "WenzyTestimonial[]", default: "6 testimonials", description: "Testimonial items with quoteTitle, quoteText, name, role, seed, metric, metricLabel, rating, borderColor, bgTint." },
            { name: "title", type: "string", default: "Trusted By Leaders", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for navigation arrow." },
        ],
    },
    {
        id: "uilora-chainex",
        name: "Uilora Chainex",
        description: "Infinite horizontal carousel with edge fade, green-tinted active card, DiceBear avatars, and progress dots.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "carousel", "infinite", "green", "horizontal", "fade"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraChainex",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, seed?}>", default: "8 testimonials", description: "Testimonial items." },
            { name: "accentColor", type: "string", default: "#22C55E", description: "Accent color for active card and dots." },
        ],
    },
    {
        id: "uilora-veluno",
        name: "Uilora Veluno",
        description: "Featured testimonial with image + metric cards below.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "featured", "metrics", "cards", "light"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraVeluno",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Object<{featured, metrics}>", default: "Uilora testimonials", description: "Featured + metric testimonials." },
            { name: "title", type: "string", default: "Trusted By Leaders", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for metrics and buttons." },
        ],
    },
    {
        id: "uilora-shipx",
        name: "Uilora ShipX",
        description: "Dark navy testimonial cards with large decorative quote marks.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "dark", "navy", "quotes", "glass"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraShipX",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, avatar}>", default: "3 Uilora testimonials", description: "Testimonial items." },
            { name: "title", type: "string", default: "Here's What People Say", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#6C63FF", description: "Accent color for quote marks." },
        ],
    },
    {
        id: "uilora-sparkly",
        name: "Uilora Sparkly",
        description: "Split layout testimonial with DiceBear avatar hero section and dark quote card.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "split", "avatar", "dark", "gradient"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraSparkly",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, seed, bgFrom?, bgTo?}>", default: "6 Uilora testimonials", description: "Testimonial items with gradient colors." },
            { name: "title", type: "string", default: "Words That Reflect Real Results", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for active arrow and quote mark." },
        ],
    },
    {
        id: "uilora-triloe",
        name: "Uilora Triloe",
        description: "Dark auto-advancing carousel with notched-corner cards, DiceBear avatars, star ratings, and DiceBear company logos.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "dark", "auto-advance", "notched", "company-logo", "infinite"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraTriloe",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, company, seed, companySeed}>", default: "6 Uilora testimonials", description: "Testimonial items with company info." },
            { name: "title", type: "string", default: "Results Backed by Clients", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for badges and indicators." },
        ],
    },
    {
        id: "testimonials-brutalist",
        name: "Neo-Brutalism",
        description: "Bold neo-brutalist testimonial section with marquee animation.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "brutalist", "marquee", "bold"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsBrutalist",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#F0F0F0", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "headerBgColor", type: "string", default: "#FF4D00", description: "Background color of the header section (hex, rgb, or hsl)." },
            { name: "headerBorderColor", type: "string", default: "#000000", description: "Border color of the header section (hex, rgb, or hsl)." },
            { name: "headerTextColor", type: "string", default: "#ffffff", description: "Text color of the header section (hex, rgb, or hsl)." },
            { name: "headerRotate", type: "number", default: "-1", description: "Rotation angle of the header in degrees." },
            { name: "headerShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of the header (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Unfiltered Feedback", description: "Main title text." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#000000", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of the cards (hex, rgb, or hsl)." },
            { name: "cardHoverShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of cards on hover (hex, rgb, or hsl)." },
            { name: "cardHoverTranslate", type: "number", default: "2", description: "Translation distance of cards on hover in pixels." },
            { name: "avatarBorderColor", type: "string", default: "#000000", description: "Border color of the avatar images (hex, rgb, or hsl)." },
            { name: "avatarBgColor", type: "string", default: "#fef08a", description: "Background color of the avatar images (hex, rgb, or hsl)." },
            { name: "starFillColor", type: "string", default: "#000000", description: "Fill color of the star icons (hex, rgb, or hsl)." },
            { name: "starTextColor", type: "string", default: "#000000", description: "Text color for star rating (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#000000", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "quoteUppercase", type: "boolean", default: "true", description: "Whether to display quotes in uppercase." },
            { name: "dividerBorderColor", type: "string", default: "#000000", description: "Border color of dividers (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorNameUppercase", type: "boolean", default: "true", description: "Whether to display author names in uppercase." },
            { name: "companyBadgeBgColor", type: "string", default: "#000000", description: "Background color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeTextColor", type: "string", default: "#ffffff", description: "Text color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeUppercase", type: "boolean", default: "true", description: "Whether to display company badges in uppercase." },
        ],
    },
    {
        id: "testimonials-dark",
        name: "Dark Spotlight",
        description: "Premium dark spotlight testimonial cards with hover effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "dark", "spotlight", "premium"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsDark",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#050505", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "badgeText", type: "string", default: "Excellence", description: "Text displayed in the badge." },
            { name: "badgeTextColor", type: "string", default: "#D4AF37", description: "Text color of the badge (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Client Success Stories", description: "Main title text." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "rgba(23, 23, 23, 0.5)", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#262626", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardHoverBorderColor", type: "string", default: "rgba(212, 175, 55, 0.5)", description: "Border color of cards on hover (hex, rgb, or hsl)." },
            { name: "spotlightColor", type: "string", default: "rgba(212, 175, 55, 0.1)", description: "Color of the spotlight effect (hex, rgb, or hsl)." },
            { name: "spotlightSize", type: "number", default: "600", description: "Size of the spotlight effect in pixels." },
            { name: "quoteIconColor", type: "string", default: "#404040", description: "Color of the quote icon (hex, rgb, or hsl)." },
            { name: "quoteTextColor", type: "string", default: "#d4d4d4", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "avatarGrayscale", type: "boolean", default: "true", description: "Whether to apply grayscale filter to avatars." },
            { name: "avatarOpacity", type: "number", default: "0.7", description: "Opacity of avatar images (0-1)." },
            { name: "authorNameColor", type: "string", default: "#ffffff", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "#D4AF37", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "dividerColor", type: "string", default: "#262626", description: "Color of dividers (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "testimonials-clay",
        name: "Clay Physics",
        description: "Organic clay physics testimonial cards with morphing shapes.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "clay", "physics", "morphing"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsClay",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#E0E5EC", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "textColor", type: "string", default: "#475569", description: "Default text color (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Loved by Humans.", description: "Main title text." },
            { name: "titleColor", type: "string", default: "#334155", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "subtitle", type: "string", default: "Our users are our biggest fans. We don't just build software; we build relationships.", description: "Subtitle text." },
            { name: "subtitleColor", type: "string", default: "#475569", description: "Color of the subtitle text (hex, rgb, or hsl)." },
            { name: "buttonBgColor", type: "string", default: "#E0E5EC", description: "Background color of buttons (hex, rgb, or hsl)." },
            { name: "buttonShadowLight", type: "string", default: "rgba(255,255,255,0.5)", description: "Light shadow color for buttons (hex, rgb, or hsl)." },
            { name: "buttonShadowDark", type: "string", default: "rgb(163,177,198)", description: "Dark shadow color for buttons (hex, rgb, or hsl)." },
            { name: "buttonTextColor", type: "string", default: "#334155", description: "Text color of buttons (hex, rgb, or hsl)." },
            { name: "buttonHoverTextColor", type: "string", default: "#3b82f6", description: "Text color of buttons on hover (hex, rgb, or hsl)." },
            { name: "buttonActiveShadowLight", type: "string", default: "rgb(163,177,198)", description: "Light shadow color for active buttons (hex, rgb, or hsl)." },
            { name: "buttonActiveShadowDark", type: "string", default: "rgba(255,255,255,0.5)", description: "Dark shadow color for active buttons (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#E0E5EC", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardShadowLight", type: "string", default: "rgba(255,255,255,0.5)", description: "Light shadow color for cards (hex, rgb, or hsl)." },
            { name: "cardShadowDark", type: "string", default: "rgb(163,177,198)", description: "Dark shadow color for cards (hex, rgb, or hsl)." },
            { name: "iconBgColor", type: "string", default: "#60a5fa", description: "Background color of icons (hex, rgb, or hsl)." },
            { name: "iconBorderColor", type: "string", default: "#E0E5EC", description: "Border color of icons (hex, rgb, or hsl)." },
            { name: "iconColor", type: "string", default: "#ffffff", description: "Color of icons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#334155", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#334155", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorCompanyColor", type: "string", default: "#64748b", description: "Color of the author company text (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "testimonials-sketch",
        name: "Sketch Note",
        description: "Hand-drawn sketch testimonial section with rough aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "sketch", "hand-drawn", "rough"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsSketch",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#fffdf5", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "gridColor", type: "string", default: "#444444", description: "Color of the grid pattern (hex, rgb, or hsl)." },
            { name: "gridOpacity", type: "number", default: "0.1", description: "Opacity of the grid pattern (0-1)." },
            { name: "title", type: "string", default: "The Verdict", description: "Main title text." },
            { name: "titleColor", type: "string", default: "#1f2937", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "titleUnderlineColor", type: "string", default: "#facc15", description: "Color of the title underline (hex, rgb, or hsl)." },
            { name: "titleUnderlineWavy", type: "boolean", default: "true", description: "Whether to use wavy underline style." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#1f2937", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,0.1)", description: "Shadow color of the cards (hex, rgb, or hsl)." },
            { name: "tapeBgColor", type: "string", default: "rgba(254, 240, 138, 0.8)", description: "Background color of tape decorations (hex, rgb, or hsl)." },
            { name: "tapeRotate", type: "number", default: "-2", description: "Rotation angle of tape decorations in degrees." },
            { name: "starColor", type: "string", default: "#eab308", description: "Color of star icons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#1f2937", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#1f2937", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorCompanyColor", type: "string", default: "#6b7280", description: "Color of the author company text (hex, rgb, or hsl)." },
            { name: "authorCompanyUppercase", type: "boolean", default: "true", description: "Whether to display company names in uppercase." },
            { name: "avatarBorderColor", type: "string", default: "#1f2937", description: "Border color of the avatar images (hex, rgb, or hsl)." },
            { name: "decorativeLineColor", type: "string", default: "#000000", description: "Color of decorative lines (hex, rgb, or hsl)." },
            { name: "decorativeLineOpacity", type: "number", default: "0.1", description: "Opacity of decorative lines (0-1)." },
        ],
    },
    {
        id: "testimonials-bento",
        name: "Bento Mosaic",
        description: "Bento mosaic testimonial grid with expandable cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "bento", "mosaic", "expandable"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsBento",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#f5f5f5", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "headerCardBgColor", type: "string", default: "#4f46e5", description: "Background color of the header card (hex, rgb, or hsl)." },
            { name: "headerCardBlurColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Blur effect color for the header card (hex, rgb, or hsl)." },
            { name: "headerTextColor", type: "string", default: "#ffffff", description: "Text color of the header (hex, rgb, or hsl)." },
            { name: "headerText", type: "string", default: "What people are saying.", description: "Header text content." },
            { name: "card1BgColor", type: "string", default: "#ffffff", description: "Background color of card 1 (hex, rgb, or hsl)." },
            { name: "card1TextColor", type: "string", default: "#525252", description: "Text color of card 1 (hex, rgb, or hsl)." },
            { name: "card2BgColor", type: "string", default: "#facc15", description: "Background color of card 2 (hex, rgb, or hsl)." },
            { name: "card2TextColor", type: "string", default: "#000000", description: "Text color of card 2 (hex, rgb, or hsl)." },
            { name: "card2QuoteColor", type: "string", default: "#000000", description: "Quote text color of card 2 (hex, rgb, or hsl)." },
            { name: "card2CompanyColor", type: "string", default: "rgba(0,0,0,0.6)", description: "Company text color of card 2 (hex, rgb, or hsl)." },
            { name: "card3BgColor", type: "string", default: "#000000", description: "Background color of card 3 (hex, rgb, or hsl)." },
            { name: "card3AvatarBorderColor", type: "string", default: "#404040", description: "Avatar border color of card 3 (hex, rgb, or hsl)." },
            { name: "card3QuoteColor", type: "string", default: "#ffffff", description: "Quote text color of card 3 (hex, rgb, or hsl)." },
            { name: "card3QuoteItalic", type: "boolean", default: "true", description: "Whether to display quotes in italic on card 3." },
            { name: "card3AuthorColor", type: "string", default: "#ffffff", description: "Author name color of card 3 (hex, rgb, or hsl)." },
            { name: "card3RoleColor", type: "string", default: "#737373", description: "Author role color of card 3 (hex, rgb, or hsl)." },
            { name: "statCardBgColor", type: "string", default: "#ffffff", description: "Background color of stat cards (hex, rgb, or hsl)." },
            { name: "statValueColor", type: "string", default: "#4f46e5", description: "Value text color of stat cards (hex, rgb, or hsl)." },
            { name: "statLabelColor", type: "string", default: "#737373", description: "Label text color of stat cards (hex, rgb, or hsl)." },
            { name: "card5BgColor", type: "string", default: "#faf5ff", description: "Background color of card 5 (hex, rgb, or hsl)." },
            { name: "card5HoverBgColor", type: "string", default: "#f3e8ff", description: "Background color of card 5 on hover (hex, rgb, or hsl)." },
            { name: "card5TextColor", type: "string", default: "#581c87", description: "Text color of card 5 (hex, rgb, or hsl)." },
            { name: "card5IconColor", type: "string", default: "#9333ea", description: "Icon color of card 5 (hex, rgb, or hsl)." },
            { name: "card5AuthorColor", type: "string", default: "#6b21a8", description: "Author name color of card 5 (hex, rgb, or hsl)." },
            { name: "card6BgColor", type: "string", default: "#ffffff", description: "Background color of card 6 (hex, rgb, or hsl)." },
            { name: "card6IconBgColor", type: "string", default: "#f5f5f5", description: "Icon background color of card 6 (hex, rgb, or hsl)." },
            { name: "card6IconColor", type: "string", default: "#eab308", description: "Icon color of card 6 (hex, rgb, or hsl)." },
            { name: "card6TextColor", type: "string", default: "#525252", description: "Text color of card 6 (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "testimonials-editorial",
        name: "Editorial Split",
        description: "Editorial split testimonial section with typography focus.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "editorial", "split", "typography"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "imageBgColor", type: "string", default: "#f5f5f5", description: "Background color of the image section (hex, rgb, or hsl)." },
            { name: "imageGrayscale", type: "boolean", default: "true", description: "Whether to apply grayscale filter to images." },
            { name: "imageContrast", type: "number", default: "125", description: "Contrast level of images (0-200)." },
            { name: "figureLabelBgColor", type: "string", default: "#ffffff", description: "Background color of figure labels (hex, rgb, or hsl)." },
            { name: "figureLabelTextColor", type: "string", default: "#000000", description: "Text color of figure labels (hex, rgb, or hsl)." },
            { name: "figureLabelPrefix", type: "string", default: "Fig.", description: "Prefix text for figure labels." },
            { name: "title", type: "string", default: "Voices", description: "Main title text." },
            { name: "titleItalic", type: "string", default: "of the Industry", description: "Italic title text." },
            { name: "titleColor", type: "string", default: "#000000", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "titleItalicColor", type: "string", default: "#000000", description: "Color of the italic title text (hex, rgb, or hsl)." },
            { name: "dividerColor", type: "string", default: "#000000", description: "Color of dividers (hex, rgb, or hsl)." },
            { name: "arrowColor", type: "string", default: "#000000", description: "Color of arrow icons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#000000", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "#737373", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "footerBgColor", type: "string", default: "#000000", description: "Background color of the footer (hex, rgb, or hsl)." },
            { name: "footerTextColor", type: "string", default: "#ffffff", description: "Text color of the footer (hex, rgb, or hsl)." },
            { name: "footerText", type: "string", default: "End of Section", description: "Footer text content." },
        ],
    },
    {
        id: "cine-parallax",
        name: "Cine-Parallax",
        description: "Cinematic parallax testimonial section with depth effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "cinematic", "parallax", "depth"],
        previewUrl: "/ContentBlocks/Testimonials/CineParallax",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image, video." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "blobColor", type: "string", default: "rgba(99, 102, 241, 0.2)", description: "Color of the blob effect (hex, rgb, or hsl)." },
            { name: "blobSize", type: "number", default: "800", description: "Size of the blob effect in pixels." },
            { name: "title", type: "string", default: "Voices of Innovation.", description: "Main title text." },
            { name: "titleGradientFrom", type: "string", default: "#ffffff", description: "Start color of the title gradient (hex, rgb, or hsl)." },
            { name: "titleGradientTo", type: "string", default: "rgba(255,255,255,0.5)", description: "End color of the title gradient (hex, rgb, or hsl)." },
            { name: "subtitle", type: "string", default: "See how leading teams are reshaping their workflows using our platform. Real stories, real impact.", description: "Subtitle text." },
            { name: "subtitleColor", type: "string", default: "#a3a3a3", description: "Color of the subtitle text (hex, rgb, or hsl)." },
            { name: "trustedPartnersCount", type: "string", default: "500+", description: "Trusted partners count text." },
            { name: "trustedPartnersLabel", type: "string", default: "Trusted Partners", description: "Trusted partners label text." },
            { name: "trustedPartnersCountColor", type: "string", default: "#ffffff", description: "Color of the trusted partners count (hex, rgb, or hsl)." },
            { name: "trustedPartnersLabelColor", type: "string", default: "#737373", description: "Color of the trusted partners label (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#171717", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardHoverBorderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Border color of cards on hover (hex, rgb, or hsl)." },
            { name: "imageOverlayFrom", type: "string", default: "rgba(0,0,0,0.9)", description: "Start color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "imageOverlayVia", type: "string", default: "rgba(0,0,0,0.2)", description: "Middle color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "imageOverlayTo", type: "string", default: "transparent", description: "End color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "playButtonBgColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Background color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonBorderColor", type: "string", default: "rgba(255,255,255,0.3)", description: "Border color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonIconColor", type: "string", default: "#ffffff", description: "Icon color of play buttons (hex, rgb, or hsl)." },
            { name: "nameColor", type: "string", default: "#ffffff", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "roleColor", type: "string", default: "#a3a3a3", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#d4d4d4", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "avatarBorderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Border color of the avatar images (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "horizontal-gallery",
        name: "Horizontal Gallery",
        description: "Horizontal scrolling testimonial gallery with smooth transitions.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "horizontal", "gallery", "scroll"],
        previewUrl: "/ContentBlocks/Testimonials/HorizontalGallery",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "textColor", type: "string", default: "#000000", description: "Default text color (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "REAL\nSTORIES", description: "Main title text (supports newlines with \\n)." },
            { name: "titleColor", type: "string", default: "#000000", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "arrowColor", type: "string", default: "#000000", description: "Color of arrow icons (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#f5f5f5", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "companyBadgeBgColor", type: "string", default: "#ffffff", description: "Background color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeTextColor", type: "string", default: "#000000", description: "Text color of company badges (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#000000", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "quoteItalic", type: "boolean", default: "true", description: "Whether to display quotes in italic." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorBorderColor", type: "string", default: "rgba(0,0,0,0.1)", description: "Border color of author sections (hex, rgb, or hsl)." },
            { name: "ctaCircleBgColor", type: "string", default: "#000000", description: "Background color of the CTA circle (hex, rgb, or hsl)." },
            { name: "ctaCircleTextColor", type: "string", default: "#ffffff", description: "Text color of the CTA circle (hex, rgb, or hsl)." },
            { name: "ctaText", type: "string", default: "Join the\nRevolution", description: "CTA text content (supports newlines with \\n)." },
        ],
    },
    {
        id: "video-bento",
        name: "Video Bento",
        description: "Video-enabled bento testimonial grid with modal playback.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "video", "bento", "modal"],
        previewUrl: "/ContentBlocks/Testimonials/VideoBento",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image, video." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Video Testimonials", description: "Main title text." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#171717", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "imageOverlayColor", type: "string", default: "rgba(0,0,0,0.4)", description: "Overlay color for images (hex, rgb, or hsl)." },
            { name: "imageHoverOverlayColor", type: "string", default: "rgba(0,0,0,0.2)", description: "Overlay color for images on hover (hex, rgb, or hsl)." },
            { name: "playButtonBgColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Background color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonBorderColor", type: "string", default: "rgba(255,255,255,0.3)", description: "Border color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonIconColor", type: "string", default: "#ffffff", description: "Icon color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonSize", type: "number", default: "32", description: "Size of play buttons in pixels." },
            { name: "authorNameColor", type: "string", default: "#ffffff", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "rgba(255,255,255,0.7)", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "gradientFromColor", type: "string", default: "rgba(0,0,0,0.8)", description: "Start color of the gradient overlay (hex, rgb, or hsl)." },
            { name: "gradientToColor", type: "string", default: "transparent", description: "End color of the gradient overlay (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "spotlight-grida",
        name: "Spotlight Grid",
        description: "Spotlight grid testimonial section with dynamic lighting.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "spotlight", "grid", "lighting"],
        previewUrl: "/ContentBlocks/Testimonials/SpotlightGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "badgeBgColor", type: "string", default: "#171717", description: "Background color of the badge (hex, rgb, or hsl)." },
            { name: "badgeBorderColor", type: "string", default: "#262626", description: "Border color of the badge (hex, rgb, or hsl)." },
            { name: "badgeTextColor", type: "string", default: "#a3a3a3", description: "Text color of the badge (hex, rgb, or hsl)." },
            { name: "badgeIconColor", type: "string", default: "#eab308", description: "Icon color of the badge (hex, rgb, or hsl)." },
            { name: "badgeText", type: "string", default: "Wall of Love", description: "Badge text content." },
            { name: "title", type: "string", default: "Trusted by the best.", description: "Main title text." },
            { name: "titleGradientFrom", type: "string", default: "#ffffff", description: "Start color of the title gradient (hex, rgb, or hsl)." },
            { name: "titleGradientTo", type: "string", default: "#737373", description: "End color of the title gradient (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "rgba(23, 23, 23, 0.5)", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#262626", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "spotlightColor", type: "string", default: "rgba(255,255,255,0.06)", description: "Color of the spotlight effect (hex, rgb, or hsl)." },
            { name: "spotlightSize", type: "number", default: "600", description: "Size of the spotlight effect in pixels." },
            { name: "avatarGrayscale", type: "boolean", default: "true", description: "Whether to apply grayscale filter to avatars." },
            { name: "avatarOpacity", type: "number", default: "0.7", description: "Opacity of avatar images (0-1)." },
            { name: "iconColor", type: "string", default: "#404040", description: "Color of icons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#d4d4d4", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#e5e5e5", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorCompanyColor", type: "string", default: "#737373", description: "Color of the author company text (hex, rgb, or hsl)." },
            { name: "dividerColor", type: "string", default: "#404040", description: "Color of dividers (hex, rgb, or hsl)." },
            { name: "dividerDotColor", type: "string", default: "#404040", description: "Color of divider dots (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "vertical-accordion",
        name: "Vertical Accordion",
        description: "Vertical accordion testimonial section with expandable cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "vertical", "accordion", "expandable"],
        previewUrl: "/ContentBlocks/Testimonials/VerticalAccordion",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image, video." },
            { name: "backgroundColor", type: "string", default: "#f5f5f5", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "textColor", type: "string", default: "#000000", description: "Default text color (hex, rgb, or hsl)." },
            { name: "imageOverlayFrom", type: "string", default: "transparent", description: "Start color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "imageOverlayVia", type: "string", default: "rgba(0,0,0,0.2)", description: "Middle color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "imageOverlayTo", type: "string", default: "rgba(0,0,0,0.9)", description: "End color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "companyBadgeBgColor", type: "string", default: "#ffffff", description: "Background color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeTextColor", type: "string", default: "#000000", description: "Text color of company badges (hex, rgb, or hsl)." },
            { name: "playButtonBgColor", type: "string", default: "#ffffff", description: "Background color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonIconColor", type: "string", default: "#000000", description: "Icon color of play buttons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#ffffff", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "quoteTruncateLength", type: "number", default: "60", description: "Maximum length of quote text before truncation." },
            { name: "authorNameColor", type: "string", default: "#ffffff", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "rgba(255,255,255,0.7)", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "authorAvatarBorderColor", type: "string", default: "#ffffff", description: "Border color of the author avatar images (hex, rgb, or hsl)." },
            { name: "inactiveLabelColor", type: "string", default: "rgba(255,255,255,0.7)", description: "Color of inactive labels (hex, rgb, or hsl)." },
            { name: "inactiveLabelRotate", type: "number", default: "-90", description: "Rotation angle of inactive labels in degrees." },
        ],
    },
    {
        id: "minimal-typographic",
        name: "Minimal Typographic",
        description: "Minimal typographic testimonial section with clean design.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "minimal", "typographic", "clean"],
        previewUrl: "/ContentBlocks/Testimonials/MinimalTypographic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#f3f4f6", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "quoteIconColor", type: "string", default: "#d1d5db", description: "Color of the quote icon (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#111827", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "#6b7280", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "dividerColor", type: "string", default: "#d1d5db", description: "Color of dividers (hex, rgb, or hsl)." },
            { name: "dotActiveColor", type: "string", default: "#000000", description: "Color of active pagination dots (hex, rgb, or hsl)." },
            { name: "dotInactiveColor", type: "string", default: "#d1d5db", description: "Color of inactive pagination dots (hex, rgb, or hsl)." },
            { name: "dotHoverColor", type: "string", default: "#9ca3af", description: "Color of pagination dots on hover (hex, rgb, or hsl)." },
            { name: "autoPlayInterval", type: "number", default: "5000", description: "Auto-play interval in milliseconds." },
        ],
    },
    {
        id: "neo-brutal-grid",
        name: "Neo-Brutal Grid",
        description: "Neo-brutalist grid testimonial section with bold aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "neo-brutal", "grid", "bold"],
        previewUrl: "/ContentBlocks/Testimonials/NeoBrutalGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image, video." },
            { name: "backgroundColor", type: "string", default: "#FFDEE9", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "backgroundGradientFrom", type: "string", default: "#FFDEE9", description: "Start color of the background gradient (hex, rgb, or hsl)." },
            { name: "backgroundGradientTo", type: "string", default: "#B5FFFC", description: "End color of the background gradient (hex, rgb, or hsl)." },
            { name: "headerBgColor", type: "string", default: "#ffffff", description: "Background color of the header section (hex, rgb, or hsl)." },
            { name: "headerBorderColor", type: "string", default: "#000000", description: "Border color of the header section (hex, rgb, or hsl)." },
            { name: "headerShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of the header (hex, rgb, or hsl)." },
            { name: "headerTextColor", type: "string", default: "#000000", description: "Text color of the header section (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "The People Have Spoken", description: "Main title text." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#000000", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of the cards (hex, rgb, or hsl)." },
            { name: "cardHoverShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of cards on hover (hex, rgb, or hsl)." },
            { name: "cardHoverTranslate", type: "number", default: "2", description: "Translation distance of cards on hover in pixels." },
            { name: "avatarBorderColor", type: "string", default: "#000000", description: "Border color of the avatar images (hex, rgb, or hsl)." },
            { name: "companyBadgeBgColor", type: "string", default: "#000000", description: "Background color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeTextColor", type: "string", default: "#ffffff", description: "Text color of company badges (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#000000", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "videoContainerBgColor", type: "string", default: "#000000", description: "Background color of video containers (hex, rgb, or hsl)." },
            { name: "videoContainerBorderColor", type: "string", default: "#000000", description: "Border color of video containers (hex, rgb, or hsl)." },
            { name: "videoContainerHoverBgColor", type: "string", default: "#facc15", description: "Background color of video containers on hover (hex, rgb, or hsl)." },
            { name: "playButtonColor", type: "string", default: "#ffffff", description: "Color of play button icons (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "#000000", description: "Color of the author role text (hex, rgb, or hsl)." },
        ],
    },
];

