import { getCode } from "../getCode";
import { Component } from "../types";

export const testimonialComponents: Component[] = [
    {
        id: "testimonials-brutalist",
        name: "Neo-Brutalism",
        description: "Bold neo-brutalist testimonial section with marquee animation.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "brutalist", "marquee", "bold"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsBrutalist",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/TestimonialsBrutalist.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/TestimonialsBrutalist.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/TestimonialsBrutalist/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#F0F0F0", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "headerBgColor", type: "string", default: "#FF4D00", description: "Background color of the header section (hex, rgb, or hsl)." },
            { name: "headerBorderColor", type: "string", default: "#000000", description: "Border color of the header section (hex, rgb, or hsl)." },
            { name: "headerTextColor", type: "string", default: "#ffffff", description: "Text color of the header section (hex, rgb, or hsl)." },
            { name: "headerRotate", type: "number", default: "-1", description: "Rotation angle of the header in degrees." },
            { name: "headerShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of the header (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Unfiltered Feedback", description: "Main title text." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#000000", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of the cards (hex, rgb, or hsl)." },
            { name: "cardHoverShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of cards on hover (hex, rgb, or hsl)." },
            { name: "cardHoverTranslate", type: "number", default: "2", description: "Translation distance of cards on hover in pixels." },
            { name: "avatarBorderColor", type: "string", default: "#000000", description: "Border color of the avatar images (hex, rgb, or hsl)." },
            { name: "avatarBgColor", type: "string", default: "#fef08a", description: "Background color of the avatar images (hex, rgb, or hsl)." },
            { name: "starFillColor", type: "string", default: "#000000", description: "Fill color of the star icons (hex, rgb, or hsl)." },
            { name: "starTextColor", type: "string", default: "#000000", description: "Text color for star rating (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#000000", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "quoteUppercase", type: "boolean", default: "true", description: "Whether to display quotes in uppercase." },
            { name: "dividerBorderColor", type: "string", default: "#000000", description: "Border color of dividers (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorNameUppercase", type: "boolean", default: "true", description: "Whether to display author names in uppercase." },
            { name: "companyBadgeBgColor", type: "string", default: "#000000", description: "Background color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeTextColor", type: "string", default: "#ffffff", description: "Text color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeUppercase", type: "boolean", default: "true", description: "Whether to display company badges in uppercase." },
        ],
        whenToUse: "Perfect for high-energy brands, street-wear e-commerce, and experimental Next.js portfolios. Use this React component for a bold, neo-brutalist testimonial section with a continuous marquee animation and chunky card shadows.",
        bestPractices: "Follow React best practices by pairing this with thick, monospaced typography and saturated primary colors. Maintain scalable component architecture by using it for high-impact social proof. Optimize for performance by using CSS-based marquee animations.",
        whyMatters: "Neo-brutalist design is a powerful visual statement of raw power and structural honesty. This production-ready UI component helpsคุณ build an interface that feels solid and unyielding, adding a unique architectural signature to your project.",
        faqs: [
            { question: "Does the marquee pause on hover?", answer: "Yes, the animation automatically pauses when a user hovers over a card, allowing them to read the testimonial at their own pace." },
            { question: "Can I adjust the rotation?", answer: "The `headerRotate` prop allows you to control the exact tilt of the 'Unfiltered Feedback' banner for a custom 'hand-placed' look." },
            { question: "Are the shadow colors customizable?", answer: "Each card's shadow color is fully customizable via the `cardShadowColor` prop, supporting both solid blacks and vibrant secondary colors." }
        ],
        imageUrl: "testimonials-brutalist.png"
    },
    {
        id: "testimonials-dark",
        name: "Dark Spotlight",
        description: "Premium dark spotlight testimonial cards with hover effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "dark", "spotlight", "premium"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsDark",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/TestimonialsDark.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/TestimonialsDark.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/TestimonialsDark/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#050505", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "badgeText", type: "string", default: "Excellence", description: "Text displayed in the badge." },
            { name: "badgeTextColor", type: "string", default: "#D4AF37", description: "Text color of the badge (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Client Success Stories", description: "Main title text." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "rgba(23, 23, 23, 0.5)", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#262626", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardHoverBorderColor", type: "string", default: "rgba(212, 175, 55, 0.5)", description: "Border color of cards on hover (hex, rgb, or hsl)." },
            { name: "spotlightColor", type: "string", default: "rgba(212, 175, 55, 0.1)", description: "Color of the spotlight effect (hex, rgb, or hsl)." },
            { name: "spotlightSize", type: "number", default: "600", description: "Size of the spotlight effect in pixels." },
            { name: "quoteIconColor", type: "string", default: "#404040", description: "Color of the quote icon (hex, rgb, or hsl)." },
            { name: "quoteTextColor", type: "string", default: "#d4d4d4", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "avatarGrayscale", type: "boolean", default: "true", description: "Whether to apply grayscale filter to avatars." },
            { name: "avatarOpacity", type: "number", default: "0.7", description: "Opacity of avatar images (0-1)." },
            { name: "authorNameColor", type: "string", default: "#ffffff", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "#D4AF37", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "dividerColor", type: "string", default: "#262626", description: "Color of dividers (hex, rgb, or hsl)." },
        ],
        whenToUse: "Ideal for enterprise service providers, high-end consulting firms, and Next.js applications that want a luxury 'Pro' aesthetic. Use this React component for a premium dark-mode testimonial section with gold accents and a dynamic spotlight effect.",
        bestPractices: "Maintain consistent spacing within your design system by using it on pure black or deep navy backgrounds. Follow React best practices by using light, airy typography. Optimize for performance by using hardware-accelerated transforms for the mouse-tracking spotlight.",
        whyMatters: "Luxury aesthetics communicate exclusivity and trust. This production-ready component provides a refined version of social proof, adding a layer of architectural depth and perceived value to your client stories.",
        faqs: [
            { question: "How does the spotlight work?", answer: "The spotlight effect follows the user's cursor across the cards, highlighting the specific testimonial they are currently reading." },
            { question: "Can I remove the grayscale filter?", answer: "Yes, the `avatarGrayscale` prop can be set to `false` if you prefer to show author photos in their original colors." },
            { question: "Is the gold color required?", answer: "While designed for gold (`#D4AF37`), the `badgeTextColor` and `authorRoleColor` props allow you to use any accent color that fits your brand." }
        ],
    },
    {
        id: "testimonials-clay",
        name: "Clay Physics",
        description: "Organic clay physics testimonial cards with morphing shapes.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "clay", "physics", "morphing"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsClay",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/TestimonialsClay.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/TestimonialsClay.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/TestimonialsClay/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#E0E5EC", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "textColor", type: "string", default: "#475569", description: "Default text color (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Loved by Humans.", description: "Main title text." },
            { name: "titleColor", type: "string", default: "#334155", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "subtitle", type: "string", default: "Our users are our biggest fans. We don't just build software; we build relationships.", description: "Subtitle text." },
            { name: "subtitleColor", type: "string", default: "#475569", description: "Color of the subtitle text (hex, rgb, or hsl)." },
            { name: "buttonBgColor", type: "string", default: "#E0E5EC", description: "Background color of buttons (hex, rgb, or hsl)." },
            { name: "buttonShadowLight", type: "string", default: "rgba(255,255,255,0.5)", description: "Light shadow color for buttons (hex, rgb, or hsl)." },
            { name: "buttonShadowDark", type: "string", default: "rgb(163,177,198)", description: "Dark shadow color for buttons (hex, rgb, or hsl)." },
            { name: "buttonTextColor", type: "string", default: "#334155", description: "Text color of buttons (hex, rgb, or hsl)." },
            { name: "buttonHoverTextColor", type: "string", default: "#3b82f6", description: "Text color of buttons on hover (hex, rgb, or hsl)." },
            { name: "buttonActiveShadowLight", type: "string", default: "rgb(163,177,198)", description: "Light shadow color for active buttons (hex, rgb, or hsl)." },
            { name: "buttonActiveShadowDark", type: "string", default: "rgba(255,255,255,0.5)", description: "Dark shadow color for active buttons (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#E0E5EC", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardShadowLight", type: "string", default: "rgba(255,255,255,0.5)", description: "Light shadow color for cards (hex, rgb, or hsl)." },
            { name: "cardShadowDark", type: "string", default: "rgb(163,177,198)", description: "Dark shadow color for cards (hex, rgb, or hsl)." },
            { name: "iconBgColor", type: "string", default: "#60a5fa", description: "Background color of icons (hex, rgb, or hsl)." },
            { name: "iconBorderColor", type: "string", default: "#E0E5EC", description: "Border color of icons (hex, rgb, or hsl)." },
            { name: "iconColor", type: "string", default: "#ffffff", description: "Color of icons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#334155", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#334155", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorCompanyColor", type: "string", default: "#64748b", description: "Color of the author company text (hex, rgb, or hsl)." },
        ],
        whenToUse: "Excellent for friendly mobile apps, design portfolios, and Next.js startups that want a tactile, 'soft' aesthetic. Use this React component for a neumorphic testimonial section with organic, morphing card shapes.",
        bestPractices: "Maintain consistent spacing within your design system by using it on light, monochromatic backgrounds. Follow React best practices by pairing it with clear, rounded typography. Optimize for performance by managed the shadow-blur radii.",
        whyMatters: "Neumorphism (Claymorphism) creates a sense of approachability and physical presence. This production-ready UI component helpsคุณ build an interface that feels tactile and friendly, improving user affinity with your brand.",
        faqs: [
            { question: "How are the morphing shapes made?", answer: "The cards use internal animation loops for their `border-radius`, creating a soft, shifting 'clay-like' appearance." },
            { question: "Is the neumorphic effect customizable?", answer: "Yes, the `cardShadowLight` and `cardShadowDark` props allow you to fine-tune the depth and 'softness' of the elevation." },
            { question: "Can I use it on dark backgrounds?", answer: "While optimized for light mode (`#E0E5EC`), the colors can be adjusted to create a similar tactile effect on dark gray backgrounds." }
        ],
    },
    {
        id: "testimonials-sketch",
        name: "Sketch Note",
        description: "Hand-drawn sketch testimonial section with rough aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "sketch", "hand-drawn", "rough"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsSketch",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/TestimonialsSketch.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/TestimonialsSketch.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/TestimonialsSketch/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#fffdf5", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "gridColor", type: "string", default: "#444444", description: "Color of the grid pattern (hex, rgb, or hsl)." },
            { name: "gridOpacity", type: "number", default: "0.1", description: "Opacity of the grid pattern (0-1)." },
            { name: "title", type: "string", default: "The Verdict", description: "Main title text." },
            { name: "titleColor", type: "string", default: "#1f2937", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "titleUnderlineColor", type: "string", default: "#facc15", description: "Color of the title underline (hex, rgb, or hsl)." },
            { name: "titleUnderlineWavy", type: "boolean", default: "true", description: "Whether to use wavy underline style." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#1f2937", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,0.1)", description: "Shadow color of the cards (hex, rgb, or hsl)." },
            { name: "tapeBgColor", type: "string", default: "rgba(254, 240, 138, 0.8)", description: "Background color of tape decorations (hex, rgb, or hsl)." },
            { name: "tapeRotate", type: "number", default: "-2", description: "Rotation angle of tape decorations in degrees." },
            { name: "starColor", type: "string", default: "#eab308", description: "Color of star icons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#1f2937", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#1f2937", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorCompanyColor", type: "string", default: "#6b7280", description: "Color of the author company text (hex, rgb, or hsl)." },
            { name: "authorCompanyUppercase", type: "boolean", default: "true", description: "Whether to display company names in uppercase." },
            { name: "avatarBorderColor", type: "string", default: "#1f2937", description: "Border color of the avatar images (hex, rgb, or hsl)." },
            { name: "decorativeLineColor", type: "string", default: "#000000", description: "Color of decorative lines (hex, rgb, or hsl)." },
            { name: "decorativeLineOpacity", type: "number", default: "0.1", description: "Opacity of decorative lines (0-1)." },
        ],
        whenToUse: "Ideal for creative labs, educational platforms, and Next.js portfolios that want a playful, hand-crafted aesthetic. Use this React component for a 'sketchbook' testimonial section with rough borders, wavy underlines, and tape decorations.",
        bestPractices: "Follow React best practices by pairing this with playful, informal typography. Maintain scalable component architecture by using it for narrative sections. Optimize for performance by using efficient SVG filters for the 'hand-drawn' lines.",
        whyMatters: "Sketch aesthetics break the digital barrier by adding a human, tactile touch to social proof. This production-ready UI component helpsคุณ build an interface that feels approachable and experimental, improving user engagement through visual novelty.",
        faqs: [
            { question: "How is the tape effect created?", answer: "It uses semi-transparent `rgba` backgrounds and slight rotations to simulate physical pieces of masking tape holding the cards." },
            { question: "Can I change the underline style?", answer: "Yes, the `titleUnderlineWavy` prop allows you to switch between a standard straight underline and a playful wavy one." },
            { question: "Is the grid real paper?", answer: "The background uses a lightweight CSS grid pattern on top of a soft cream color (`#fffdf5`) to mimic the look of an artist's sketchbook." }
        ],
    },
    {
        id: "testimonials-bento",
        name: "Bento Mosaic",
        description: "Bento mosaic testimonial grid with expandable cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "bento", "mosaic", "expandable"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsBento",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/TestimonialsBento.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/TestimonialsBento.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/TestimonialsBento/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#f5f5f5", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "headerCardBgColor", type: "string", default: "#4f46e5", description: "Background color of the header card (hex, rgb, or hsl)." },
            { name: "headerCardBlurColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Blur effect color for the header card (hex, rgb, or hsl)." },
            { name: "headerTextColor", type: "string", default: "#ffffff", description: "Text color of the header (hex, rgb, or hsl)." },
            { name: "headerText", type: "string", default: "What people are saying.", description: "Header text content." },
            { name: "card1BgColor", type: "string", default: "#ffffff", description: "Background color of card 1 (hex, rgb, or hsl)." },
            { name: "card1TextColor", type: "string", default: "#525252", description: "Text color of card 1 (hex, rgb, or hsl)." },
            { name: "card2BgColor", type: "string", default: "#facc15", description: "Background color of card 2 (hex, rgb, or hsl)." },
            { name: "card2TextColor", type: "string", default: "#000000", description: "Text color of card 2 (hex, rgb, or hsl)." },
            { name: "card2QuoteColor", type: "string", default: "#000000", description: "Quote text color of card 2 (hex, rgb, or hsl)." },
            { name: "card2CompanyColor", type: "string", default: "rgba(0,0,0,0.6)", description: "Company text color of card 2 (hex, rgb, or hsl)." },
            { name: "card3BgColor", type: "string", default: "#000000", description: "Background color of card 3 (hex, rgb, or hsl)." },
            { name: "card3AvatarBorderColor", type: "string", default: "#404040", description: "Avatar border color of card 3 (hex, rgb, or hsl)." },
            { name: "card3QuoteColor", type: "string", default: "#ffffff", description: "Quote text color of card 3 (hex, rgb, or hsl)." },
            { name: "card3QuoteItalic", type: "boolean", default: "true", description: "Whether to display quotes in italic on card 3." },
            { name: "card3AuthorColor", type: "string", default: "#ffffff", description: "Author name color of card 3 (hex, rgb, or hsl)." },
            { name: "card3RoleColor", type: "string", default: "#737373", description: "Author role color of card 3 (hex, rgb, or hsl)." },
            { name: "statCardBgColor", type: "string", default: "#ffffff", description: "Background color of stat cards (hex, rgb, or hsl)." },
            { name: "statValueColor", type: "string", default: "#4f46e5", description: "Value text color of stat cards (hex, rgb, or hsl)." },
            { name: "statLabelColor", type: "string", default: "#737373", description: "Label text color of stat cards (hex, rgb, or hsl)." },
            { name: "card5BgColor", type: "string", default: "#faf5ff", description: "Background color of card 5 (hex, rgb, or hsl)." },
            { name: "card5HoverBgColor", type: "string", default: "#f3e8ff", description: "Background color of card 5 on hover (hex, rgb, or hsl)." },
            { name: "card5TextColor", type: "string", default: "#581c87", description: "Text color of card 5 (hex, rgb, or hsl)." },
            { name: "card5IconColor", type: "string", default: "#9333ea", description: "Icon color of card 5 (hex, rgb, or hsl)." },
            { name: "card5AuthorColor", type: "string", default: "#6b21a8", description: "Author name color of card 5 (hex, rgb, or hsl)." },
            { name: "card6BgColor", type: "string", default: "#ffffff", description: "Background color of card 6 (hex, rgb, or hsl)." },
            { name: "card6IconBgColor", type: "string", default: "#f5f5f5", description: "Icon background color of card 6 (hex, rgb, or hsl)." },
            { name: "card6IconColor", type: "string", default: "#eab308", description: "Icon color of card 6 (hex, rgb, or hsl)." },
            { name: "card6TextColor", type: "string", default: "#525252", description: "Text color of card 6 (hex, rgb, or hsl)." },
        ],
        whenToUse: "Excellent for complex products, diverse user bases, and Next.js applications that want a high-density, modular information layout. Use this React component for a bento-style testimonial grid with varying card sizes, metrics, and interactive states.",
        bestPractices: "Maintain consistent spacing within your design system by aligning the grid gaps with your primary site layout. Follow React best practices by pairing it with high-contrast active highlights. Optimize for performance by using efficient grid-column spans.",
        whyMatters: "Bento grids allow you to showcase both qualitative feedback and quantitative metrics (like star ratings or active users) in a unified layout. This production-ready UI component helpsคุณ build an interface that feels structured and modern.",
        faqs: [
            { question: "How does the layout work?", answer: "It uses a multi-column CSS grid where cards 'bento' together, with some spanning multiple rows or columns to create a dynamic mosaic." },
            { question: "Can I add more testimonial cards?", answer: "The component is built with a fixed mosaic pattern for maximum visual impact, but the content of each 'tile' is fully customizable." },
            { question: "Are the statistics real?", answer: "The component features stylized stat cards that can be used to showcase aggregate data like '500+ Happy Clients' alongside individual quotes." }
        ],
    },
    {
        id: "testimonials-editorial",
        name: "Editorial Split",
        description: "Editorial split testimonial section with typography focus.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "editorial", "split", "typography"],
        previewUrl: "/ContentBlocks/Testimonials/TestimonialsEditorial",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/TestimonialsEditorial.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/TestimonialsEditorial.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/TestimonialsEditorial/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "imageBgColor", type: "string", default: "#f5f5f5", description: "Background color of the image section (hex, rgb, or hsl)." },
            { name: "imageGrayscale", type: "boolean", default: "true", description: "Whether to apply grayscale filter to images." },
            { name: "imageContrast", type: "number", default: "125", description: "Contrast level of images (0-200)." },
            { name: "figureLabelBgColor", type: "string", default: "#ffffff", description: "Background color of figure labels (hex, rgb, or hsl)." },
            { name: "figureLabelTextColor", type: "string", default: "#000000", description: "Text color of figure labels (hex, rgb, or hsl)." },
            { name: "figureLabelPrefix", type: "string", default: "Fig.", description: "Prefix text for figure labels." },
            { name: "title", type: "string", default: "Voices", description: "Main title text." },
            { name: "titleItalic", type: "string", default: "of the Industry", description: "Italic title text." },
            { name: "titleColor", type: "string", default: "#000000", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "titleItalicColor", type: "string", default: "#000000", description: "Color of the italic title text (hex, rgb, or hsl)." },
            { name: "dividerColor", type: "string", default: "#000000", description: "Color of dividers (hex, rgb, or hsl)." },
            { name: "arrowColor", type: "string", default: "#000000", description: "Color of arrow icons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#000000", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "#737373", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "footerBgColor", type: "string", default: "#000000", description: "Background color of the footer (hex, rgb, or hsl)." },
            { name: "footerTextColor", type: "string", default: "#ffffff", description: "Text color of the footer (hex, rgb, or hsl)." },
            { name: "footerText", type: "string", default: "End of Section", description: "Footer text content." },
        ],
        whenToUse: "Ideal for artistic agencies, architecture firms, and Next.js sites that want a sophisticated, editorial-split aesthetic. Use this React component for a testimonial section that halves the screen between high-impact monochromatic imagery and bold typography.",
        bestPractices: "Follow React best practices by pairing this with high-contrast Serif typography. Maintain consistent spacing within your design system by using it on pure white or light gray backgrounds. Optimize for performance by lazy-loading the side-panel images.",
        whyMatters: "Editorial layouts add a sense of authority and timelessness to user feedback. This production-ready UI component helpsคุณ build an interface that feels like a high-end publication, improving the perceived exclusivity of your product.",
        faqs: [
            { question: "Why is it monochromatic?", answer: "The editorial style focuses on the power of typography and the raw emotion in the photos, ensuring user feedback feels profound and authoritative." },
            { question: "Can I use color images?", answer: "Yes, the `imageGrayscale` prop can be set to `false` if you prefer to use full-color photography in the side panel." },
            { question: "Is the split fixed?", answer: "The component uses a responsive flex/grid layout that maintains the split on desktop while elegantly stacking the image and text on mobile." }
        ],
    },
    {
        id: "cine-parallax",
        name: "Cine-Parallax",
        description: "Cinematic parallax testimonial section with depth effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "cinematic", "parallax", "depth"],
        previewUrl: "/ContentBlocks/Testimonials/CineParallax",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/CineParallax.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/CineParallax.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/CineParallax/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image, video." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "blobColor", type: "string", default: "rgba(99, 102, 241, 0.2)", description: "Color of the blob effect (hex, rgb, or hsl)." },
            { name: "blobSize", type: "number", default: "800", description: "Size of the blob effect in pixels." },
            { name: "title", type: "string", default: "Voices of Innovation.", description: "Main title text." },
            { name: "titleGradientFrom", type: "string", default: "#ffffff", description: "Start color of the title gradient (hex, rgb, or hsl)." },
            { name: "titleGradientTo", type: "string", default: "rgba(255,255,255,0.5)", description: "End color of the title gradient (hex, rgb, or hsl)." },
            { name: "subtitle", type: "string", default: "See how leading teams are reshaping their workflows using our platform. Real stories, real impact.", description: "Subtitle text." },
            { name: "subtitleColor", type: "string", default: "#a3a3a3", description: "Color of the subtitle text (hex, rgb, or hsl)." },
            { name: "trustedPartnersCount", type: "string", default: "500+", description: "Trusted partners count text." },
            { name: "trustedPartnersLabel", type: "string", default: "Trusted Partners", description: "Trusted partners label text." },
            { name: "trustedPartnersCountColor", type: "string", default: "#ffffff", description: "Color of the trusted partners count (hex, rgb, or hsl)." },
            { name: "trustedPartnersLabelColor", type: "string", default: "#737373", description: "Color of the trusted partners label (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#171717", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardHoverBorderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Border color of cards on hover (hex, rgb, or hsl)." },
            { name: "imageOverlayFrom", type: "string", default: "rgba(0,0,0,0.9)", description: "Start color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "imageOverlayVia", type: "string", default: "rgba(0,0,0,0.2)", description: "Middle color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "imageOverlayTo", type: "string", default: "transparent", description: "End color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "playButtonBgColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Background color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonBorderColor", type: "string", default: "rgba(255,255,255,0.3)", description: "Border color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonIconColor", type: "string", default: "#ffffff", description: "Icon color of play buttons (hex, rgb, or hsl)." },
            { name: "nameColor", type: "string", default: "#ffffff", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "roleColor", type: "string", default: "#a3a3a3", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#d4d4d4", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "avatarBorderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Border color of the avatar images (hex, rgb, or hsl)." },
        ],
        whenToUse: "Perfect for deep-tech brands, cinematic portfolios, and Next.js applications that want an immersive, volumetric social proof experience. Use this React component for a premium dark-mode section with video-enabled cards and deep parallax effects.",
        bestPractices: "Maintain scalable component architecture by keeping foreground text bright and readable. Follow React best practices by pairing this with dark-themed layouts. Optimize for performance by managed the parallax intensity on touch devices.",
        whyMatters: "Cinematic parallax increases the perceived value and interactivity of a digital interface. This production-ready component helpsคุณ build an interface that feels deep and tangible, turning standard feedback into an interactive experience.",
        faqs: [
            { question: "How does the parallax work?", answer: "The cards and background blobs move at different speeds relative to the user's scroll position, creating a sense of three-dimensional depth." },
            { question: "Can I add video testimonials?", answer: "Yes, each card supports an optional video background that plays on hover for a truly cinematic and alive feel." },
            { question: "What are the partners for?", answer: "The component includes a dedicated 'Trusted Partners' counter to reinforce authority before showing individual testimonials." }
        ],
    },
    {
        id: "horizontal-gallery",
        name: "Horizontal Gallery",
        description: "Horizontal scrolling testimonial gallery with smooth transitions.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "horizontal", "gallery", "scroll"],
        previewUrl: "/ContentBlocks/Testimonials/HorizontalGallery",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/HorizontalGallery.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/HorizontalGallery.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/HorizontalGallery/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "textColor", type: "string", default: "#000000", description: "Default text color (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "REAL\nSTORIES", description: "Main title text (supports newlines with \\n)." },
            { name: "titleColor", type: "string", default: "#000000", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "arrowColor", type: "string", default: "#000000", description: "Color of arrow icons (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#f5f5f5", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "companyBadgeBgColor", type: "string", default: "#ffffff", description: "Background color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeTextColor", type: "string", default: "#000000", description: "Text color of company badges (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#000000", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "quoteItalic", type: "boolean", default: "true", description: "Whether to display quotes in italic." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorBorderColor", type: "string", default: "rgba(0,0,0,0.1)", description: "Border color of author sections (hex, rgb, or hsl)." },
            { name: "ctaCircleBgColor", type: "string", default: "#000000", description: "Background color of the CTA circle (hex, rgb, or hsl)." },
            { name: "ctaCircleTextColor", type: "string", default: "#ffffff", description: "Text color of the CTA circle (hex, rgb, or hsl)." },
            { name: "ctaText", type: "string", default: "Join the\nRevolution", description: "CTA text content (supports newlines with \\n)." },
        ],
        whenToUse: "Excellent for marketing-heavy landing pages, creative agencies, and Next.js sites that want a high-impact, lateral scrolling experience. Use this React component for a horizontal gallery that moves cards along a track as the user scrolls or drags.",
        bestPractices: "Maintain consistent spacing within your design system by using it for showcase sections that require focus on individual cards. Follow React best practices by using high-contrast arrow icons. Optimize for performance by using hardware-accelerated transforms.",
        whyMatters: "Horizontal galleries provide a curated, linear way to explore user stories. This production-ready UI component helpsคุณ build an interface that feels expansive and narrative-driven, improving user discovery of multiple testimonials.",
        faqs: [
            { question: "Is it draggable?", answer: "Yes, users can navigate the gallery either by scrolling horizontally, using the provided arrow buttons, or dragging on touch devices." },
            { question: "How many cards can I include?", answer: "The component is optimized for 3-7 high-quality cards, but it can handle more as the track expands horizontally to accommodate the array." },
            { question: "What is the CTA circle?", answer: "The gallery ends with a dedicated 'Call to Action' circle, encouraging users to join the community after reading the testimonials." }
        ],
    },
    {
        id: "video-bento",
        name: "Video Bento",
        description: "Video-enabled bento testimonial grid with modal playback.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "video", "bento", "modal"],
        previewUrl: "/ContentBlocks/Testimonials/VideoBento",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/VideoBento.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/VideoBento.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/VideoBento/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image, video." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Video Testimonials", description: "Main title text." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Color of the title text (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#171717", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "imageOverlayColor", type: "string", default: "rgba(0,0,0,0.4)", description: "Overlay color for images (hex, rgb, or hsl)." },
            { name: "imageHoverOverlayColor", type: "string", default: "rgba(0,0,0,0.2)", description: "Overlay color for images on hover (hex, rgb, or hsl)." },
            { name: "playButtonBgColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Background color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonBorderColor", type: "string", default: "rgba(255,255,255,0.3)", description: "Border color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonIconColor", type: "string", default: "#ffffff", description: "Icon color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonSize", type: "number", default: "32", description: "Size of play buttons in pixels." },
            { name: "authorNameColor", type: "string", default: "#ffffff", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "rgba(255,255,255,0.7)", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "gradientFromColor", type: "string", default: "rgba(0,0,0,0.8)", description: "Start color of the gradient overlay (hex, rgb, or hsl)." },
            { name: "gradientToColor", type: "string", default: "transparent", description: "End color of the gradient overlay (hex, rgb, or hsl)." },
        ],
        whenToUse: "Ideal for video-first brands, course creators, and Next.js platforms that want to prioritize authenticity. Use this React component for a video-enabled bento grid where testimonials can be played directly in a modal overlay.",
        bestPractices: "Follow React best practices by using high-quality thumbnail images for the video tiles. Maintain consistent spacing within your design system by aligning the grid tiles. Optimize for performance by lazy-loading the video players only when the modal is opened.",
        whyMatters: "Video testimonials are the highest form of social proof as they convey tone and emotion that text cannot. This production-ready UI component helpsคุณ build an interface that feels human and trustworthy, significantly increasing conversion potential.",
        faqs: [
            { question: "How do the videos play?", answer: "When a user clicks a tile, it opens a focused modal with an embedded video player for a distraction-free experience." },
            { question: "Can I use YouTube links?", answer: "The component is built to handle various video sources, but it's best paired with high-quality MP4s or hosted video links in the `media` property." },
            { question: "Is the bento grid responsive?", answer: "Yes, the mosaic layout automatically collapses into a single-column list on mobile to ensure the play buttons remain easily tappable." }
        ],
    },
    {
        id: "spotlight-grida",
        name: "Spotlight Grid",
        description: "Spotlight grid testimonial section with dynamic lighting.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "spotlight", "grid", "lighting"],
        previewUrl: "/ContentBlocks/Testimonials/SpotlightGrid",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/SpotlightGrid.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/SpotlightGrid.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/SpotlightGrid/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "badgeBgColor", type: "string", default: "#171717", description: "Background color of the badge (hex, rgb, or hsl)." },
            { name: "badgeBorderColor", type: "string", default: "#262626", description: "Border color of the badge (hex, rgb, or hsl)." },
            { name: "badgeTextColor", type: "string", default: "#a3a3a3", description: "Text color of the badge (hex, rgb, or hsl)." },
            { name: "badgeIconColor", type: "string", default: "#eab308", description: "Icon color of the badge (hex, rgb, or hsl)." },
            { name: "badgeText", type: "string", default: "Wall of Love", description: "Badge text content." },
            { name: "title", type: "string", default: "Trusted by the best.", description: "Main title text." },
            { name: "titleGradientFrom", type: "string", default: "#ffffff", description: "Start color of the title gradient (hex, rgb, or hsl)." },
            { name: "titleGradientTo", type: "string", default: "#737373", description: "End color of the title gradient (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "rgba(23, 23, 23, 0.5)", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#262626", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "spotlightColor", type: "string", default: "rgba(255,255,255,0.06)", description: "Color of the spotlight effect (hex, rgb, or hsl)." },
            { name: "spotlightSize", type: "number", default: "600", description: "Size of the spotlight effect in pixels." },
            { name: "avatarGrayscale", type: "boolean", default: "true", description: "Whether to apply grayscale filter to avatars." },
            { name: "avatarOpacity", type: "number", default: "0.7", description: "Opacity of avatar images (0-1)." },
            { name: "iconColor", type: "string", default: "#404040", description: "Color of icons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#d4d4d4", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#e5e5e5", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorCompanyColor", type: "string", default: "#737373", description: "Color of the author company text (hex, rgb, or hsl)." },
            { name: "dividerColor", type: "string", default: "#404040", description: "Color of dividers (hex, rgb, or hsl)." },
            { name: "dividerDotColor", type: "string", default: "#404040", description: "Color of divider dots (hex, rgb, or hsl)." },
        ],
        whenToUse: "Perfect for high-end SaaS, dark-mode dashboards, and Next.js applications that want a high-fidelity 'Wall of Love'. Use this React component for a spotlight grid where each card illuminates as the mouse moves over it.",
        bestPractices: "Maintain consistent spacing within your design system by using it on pure black or deep gray backgrounds. Follow React best practices by using light, airy typography. Optimize for performance by using hardware-accelerated transforms for the spotlight overlay.",
        whyMatters: "Dynamic lighting creates a sense of discovery and premium quality. This production-ready UI component helpsคุณ build an interface that feels alive and responsive, improving user engagement with your customer stories.",
        faqs: [
            { question: "How does the spotlight work?", answer: "The spotlight effect follows the user's cursor across the entire grid, subtly highlighting the specific card and borders near the mouse." },
            { question: "Can I change the spotlight color?", answer: "Yes, the `spotlightColor` prop allows you to change the glow from white to brand-specific colors like purple or gold." },
            { question: "Is it mobile responsive?", answer: "On mobile, the mouse-tracking spotlight is typically disabled in favor of static hover states to ensure consistent performance." }
        ],
    },
    {
        id: "vertical-accordion",
        name: "Vertical Accordion",
        description: "Vertical accordion testimonial section with expandable cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "vertical", "accordion", "expandable"],
        previewUrl: "/ContentBlocks/Testimonials/VerticalAccordion",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/VerticalAccordion.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/VerticalAccordion.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/VerticalAccordion/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image, video." },
            { name: "backgroundColor", type: "string", default: "#f5f5f5", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "textColor", type: "string", default: "#000000", description: "Default text color (hex, rgb, or hsl)." },
            { name: "imageOverlayFrom", type: "string", default: "transparent", description: "Start color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "imageOverlayVia", type: "string", default: "rgba(0,0,0,0.2)", description: "Middle color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "imageOverlayTo", type: "string", default: "rgba(0,0,0,0.9)", description: "End color of the image overlay gradient (hex, rgb, or hsl)." },
            { name: "companyBadgeBgColor", type: "string", default: "#ffffff", description: "Background color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeTextColor", type: "string", default: "#000000", description: "Text color of company badges (hex, rgb, or hsl)." },
            { name: "playButtonBgColor", type: "string", default: "#ffffff", description: "Background color of play buttons (hex, rgb, or hsl)." },
            { name: "playButtonIconColor", type: "string", default: "#000000", description: "Icon color of play buttons (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#ffffff", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "quoteTruncateLength", type: "number", default: "60", description: "Maximum length of quote text before truncation." },
            { name: "authorNameColor", type: "string", default: "#ffffff", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "rgba(255,255,255,0.7)", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "authorAvatarBorderColor", type: "string", default: "#ffffff", description: "Border color of the author avatar images (hex, rgb, or hsl)." },
            { name: "inactiveLabelColor", type: "string", default: "rgba(255,255,255,0.7)", description: "Color of inactive labels (hex, rgb, or hsl)." },
            { name: "inactiveLabelRotate", type: "number", default: "-90", description: "Rotation angle of inactive labels in degrees." },
        ],
        whenToUse: "Ideal for storytelling, long-form testimonials, and Next.js sites that want a space-efficient yet dramatic layout. Use this React component for a vertical accordion where cards expand into full-bleed sections with video backgrounds.",
        bestPractices: "Follow React best practices by using high-impact portrait orientation media for the accordion panels. Maintain consistent spacing within your design system by aligning the accordion header. Optimize for performance by lazy-loading the video backgrounds.",
        whyMatters: "Vertical accordions allow users to focus intensely on one story at a time. This production-ready UI component helpsคุณ build an interface that feels narrative-driven and expansive, making each testimonial feel like a dedicated feature.",
        faqs: [
            { question: "How do the cards expand?", answer: "Each card occupies a thin vertical sliver until hovered or clicked, at which point it smoothly expands to reveal the full content and media." },
            { question: "Can I use it for video testimonials?", answer: "Absolutely, each panel supports an optional video background that brings the client story to life when the card is expanded." },
            { question: "Is the text truncated?", answer: "The `quoteTruncateLength` prop allows you to control how much text is shown in the collapsed state to maintain the visual balance of the accordion." }
        ],
    },
    {
        id: "minimal-typographic",
        name: "Minimal Typographic",
        description: "Minimal typographic testimonial section with clean design.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "minimal", "typographic", "clean"],
        previewUrl: "/ContentBlocks/Testimonials/MinimalTypographic",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/MinimalTypographic.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/MinimalTypographic.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/MinimalTypographic/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image." },
            { name: "backgroundColor", type: "string", default: "#f3f4f6", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "quoteIconColor", type: "string", default: "#d1d5db", description: "Color of the quote icon (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#111827", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "#6b7280", description: "Color of the author role text (hex, rgb, or hsl)." },
            { name: "dividerColor", type: "string", default: "#d1d5db", description: "Color of dividers (hex, rgb, or hsl)." },
            { name: "dotActiveColor", type: "string", default: "#000000", description: "Color of active pagination dots (hex, rgb, or hsl)." },
            { name: "dotInactiveColor", type: "string", default: "#d1d5db", description: "Color of inactive pagination dots (hex, rgb, or hsl)." },
            { name: "dotHoverColor", type: "string", default: "#9ca3af", description: "Color of pagination dots on hover (hex, rgb, or hsl)." },
            { name: "autoPlayInterval", type: "number", default: "5000", description: "Auto-play interval in milliseconds." },
        ],
        whenToUse: "Perfect for minimalist blogs, editorial portfolios, and Next.js applications that want a clean, type-focused aesthetic. Use this React component for a minimal typographic testimonial section with smooth auto-playing transitions and subtle quote icons.",
        bestPractices: "Follow React best practices by pairing this with bold, high-contrast typography. Maintain consistent spacing within your design system by using it on light, neutral backgrounds. Optimize for performance by using efficient state management for the transitions.",
        whyMatters: "Clean typography focuses the user's entire attention on the words of your customers. This production-ready UI component helpsคุณ build an interface that feels sincere and authoritative, without distracting from the message.",
        faqs: [
            { question: "Does it support auto-play?", answer: "Yes, the testimonials automatically cycle based on the `autoPlayInterval` prop, which can be adjusted or disabled." },
            { question: "Can I change the quote icon?", answer: "The component features a signature large quote icon at the top, whose color can be customized to subtly match your brand's color palette." },
            { question: "Is it mobile responsive?", answer: "The typography scales gracefully across screen sizes, ensuring the testimonials remain legible and centered on mobile devices." }
        ],
    },
    {
        id: "neo-brutal-grid",
        name: "Neo-Brutal Grid",
        description: "Neo-brutalist grid testimonial section with bold aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "neo-brutal", "grid", "bold"],
        previewUrl: "/ContentBlocks/Testimonials/NeoBrutalGrid",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/NeoBrutalGrid.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/NeoBrutalGrid.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/NeoBrutalGrid/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "testimonials", type: "TestimonialItem[]", default: "[]", description: "Array of testimonial items with id, name, role, company, content/text, media, avatar/image, video." },
            { name: "backgroundColor", type: "string", default: "#FFDEE9", description: "Background color of the component (hex, rgb, or hsl)." },
            { name: "backgroundGradientFrom", type: "string", default: "#FFDEE9", description: "Start color of the background gradient (hex, rgb, or hsl)." },
            { name: "backgroundGradientTo", type: "string", default: "#B5FFFC", description: "End color of the background gradient (hex, rgb, or hsl)." },
            { name: "headerBgColor", type: "string", default: "#ffffff", description: "Background color of the header section (hex, rgb, or hsl)." },
            { name: "headerBorderColor", type: "string", default: "#000000", description: "Border color of the header section (hex, rgb, or hsl)." },
            { name: "headerShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of the header (hex, rgb, or hsl)." },
            { name: "headerTextColor", type: "string", default: "#000000", description: "Text color of the header section (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "The People Have Spoken", description: "Main title text." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Background color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardBorderColor", type: "string", default: "#000000", description: "Border color of the testimonial cards (hex, rgb, or hsl)." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of the cards (hex, rgb, or hsl)." },
            { name: "cardHoverShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color of cards on hover (hex, rgb, or hsl)." },
            { name: "cardHoverTranslate", type: "number", default: "2", description: "Translation distance of cards on hover in pixels." },
            { name: "avatarBorderColor", type: "string", default: "#000000", description: "Border color of the avatar images (hex, rgb, or hsl)." },
            { name: "companyBadgeBgColor", type: "string", default: "#000000", description: "Background color of company badges (hex, rgb, or hsl)." },
            { name: "companyBadgeTextColor", type: "string", default: "#ffffff", description: "Text color of company badges (hex, rgb, or hsl)." },
            { name: "quoteColor", type: "string", default: "#000000", description: "Color of the quote text (hex, rgb, or hsl)." },
            { name: "videoContainerBgColor", type: "string", default: "#000000", description: "Background color of video containers (hex, rgb, or hsl)." },
            { name: "videoContainerBorderColor", type: "string", default: "#000000", description: "Border color of video containers (hex, rgb, or hsl)." },
            { name: "videoContainerHoverBgColor", type: "string", default: "#facc15", description: "Background color of video containers on hover (hex, rgb, or hsl)." },
            { name: "playButtonColor", type: "string", default: "#ffffff", description: "Color of play button icons (hex, rgb, or hsl)." },
            { name: "authorNameColor", type: "string", default: "#000000", description: "Color of the author name text (hex, rgb, or hsl)." },
            { name: "authorRoleColor", type: "string", default: "#000000", description: "Color of the author role text (hex, rgb, or hsl)." },
        ],
        whenToUse: "Excellent for high-energy brands, street-wear e-commerce, and experimental Next.js portfolios. Use this React component for a bold, neo-brutalist grid where testimonials are displayed as chunky cards with high-contrast shadows and video support.",
        bestPractices: "Follow React best practices by pairing this with thick, monospaced typography and vibrant primary colors. Maintain scalable component architecture by using it for high-impact social proof. Optimize for performance by using CSS-based box-shadows.",
        whyMatters: "Neo-brutalist design is a powerful visual statement of raw power and structural honesty. This production-ready UI component helpsคุณ build an interface that feels solid and unyielding, adding a unique architectural signature to your project.",
        faqs: [
            { question: "Does it support video?", answer: "Yes, specific cards in the grid can be designated for video content, featuring high-contrast play buttons and chunky borders." },
            { question: "Can I change the card tilt?", answer: "The component is built with a stable grid layout but can be easily adapted with Framer Motion to add slight random rotations for a more 'raw' feel." },
            { question: "Are the gradients customizable?", answer: "The background supports a full-width linear gradient that can be customized via the `backgroundGradientFrom` and `backgroundGradientTo` props." }
        ],
    },
    {
        id: "uilora-triloe",
        name: "Uilora Triloe",
        description: "Dark glass testimonial cards with star ratings and company badges.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "dark", "glass", "ratings", "stars"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraTriloe",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/UiloraTriloe.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/UiloraTriloe.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/UiloraTriloe/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, company, avatar}>", default: "3 Uilora testimonials", description: "Testimonial items." },
            { name: "title", type: "string", default: "Results Backed by Clients", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color." },
        ],
        whenToUse: "Perfect for SaaS landing pages and dark-themed sites that want premium glass-effect testimonials with star ratings.",
        bestPractices: "Use 3 testimonials for the best visual balance. Include company names for credibility.",
        whyMatters: "Star ratings and company badges add social proof credibility. The dark glass aesthetic conveys premium quality.",
        faqs: [
            { question: "Can I customize the star count?", answer: "Stars are fixed at 5 for simplicity. Modify the component source to make them dynamic." },
        ],
    },
    {
        id: "uilora-sparkly",
        name: "Uilora Sparkly",
        description: "Split layout testimonial with image and glass quote overlay.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "split", "image", "glass", "overlay"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraSparkly",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/UiloraSparkly.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/UiloraSparkly.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/UiloraSparkly/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, image, avatar}>", default: "3 Uilora testimonials", description: "Testimonial items with images." },
            { name: "title", type: "string", default: "Words That Reflect Real Results", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color." },
        ],
        whenToUse: "Ideal for agency sites and portfolios where each testimonial deserves a visual context with a hero image.",
        bestPractices: "Use high-quality workspace/team images. Keep quotes concise for the glass overlay.",
        whyMatters: "Pairing testimonials with images creates emotional resonance. The glass overlay adds a premium, editorial feel.",
        faqs: [
            { question: "Can I use different images per testimonial?", answer: "Yes, each testimonial item accepts its own image URL." },
        ],
    },
    {
        id: "uilora-shipx",
        name: "Uilora ShipX",
        description: "Dark navy testimonial cards with large decorative quote marks.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "dark", "navy", "quotes", "glass"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraShipX",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/UiloraShipX.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/UiloraShipX.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/UiloraShipX/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, avatar}>", default: "3 Uilora testimonials", description: "Testimonial items." },
            { name: "title", type: "string", default: "Here's What People Say", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#6C63FF", description: "Quote mark accent color." },
        ],
        whenToUse: "Great for tech products and developer tools that want a dark, contained testimonial section with decorative typography.",
        bestPractices: "Use 3 testimonials. The large quote marks work best with shorter quotes.",
        whyMatters: "The contained dark card creates a focused reading experience. Decorative quote marks add visual rhythm.",
        faqs: [
            { question: "What does the View All button do?", answer: "It's a placeholder link. Connect it to your testimonials page or modal." },
        ],
    },
    {
        id: "uilora-veluno",
        name: "Uilora Veluno",
        description: "Featured testimonial with image + metric cards below.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "featured", "metrics", "cards", "light"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraVeluno",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/UiloraVeluno.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/UiloraVeluno.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/UiloraVeluno/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Object<{featured, metrics}>", default: "Uilora testimonials", description: "Featured + metric testimonials." },
            { name: "title", type: "string", default: "Trusted By Leaders", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for metrics." },
        ],
        whenToUse: "Perfect for B2B SaaS and enterprise sites that want to highlight a featured testimonial with supporting metric cards.",
        bestPractices: "Use real metrics (ROI, growth multiples) in the bottom cards for maximum impact.",
        whyMatters: "Combining detailed testimonials with hard metrics creates the strongest social proof — stories backed by numbers.",
        faqs: [
            { question: "Can I add more metric cards?", answer: "The bottom row supports any number of cards. 3 provides the best visual balance." },
        ],
    },
    {
        id: "uilora-chainex",
        name: "Uilora Chainex",
        description: "Infinite horizontal carousel with edge fade mask, green-tinted active card, DiceBear avatars, and circular navigation.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "carousel", "infinite", "green", "horizontal", "fade"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraChainex",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/UiloraChainex.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/UiloraChainex.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/UiloraChainex/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, seed?}>", default: "8 testimonials", description: "Testimonial items." },
            { name: "accentColor", type: "string", default: "#22C55E", description: "Accent color for active card and progress dots." },
        ],
        whenToUse: "Use when you want a clean infinite testimonial carousel with minimal UI. Great for SaaS, developer tools, and portfolio sites.",
        bestPractices: "Use 6–10 testimonials so the infinite loop feels natural without repetition.",
        whyMatters: "The edge fade and circular navigation create an elegant, frictionless experience.",
        faqs: [
            { question: "Can I change the accent color?", answer: "Yes, accentColor controls the active card tint, border, avatar ring, and progress dots." },
        ],
    },
    {
        id: "uilora-wenzy",
        name: "Uilora Wenzy",
        description: "2-up testimonial cards with per-card colored borders, quote title, body text, DiceBear avatars, half-star ratings, and metric/revenue indicators.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "metric", "cards", "light", "revenue", "rating", "2-up", "bordered"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraWenzy",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/UiloraWenzy.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/UiloraWenzy.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/UiloraWenzy/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "WenzyTestimonial[]", default: "6 testimonials", description: "Items with quoteTitle, quoteText, name, role, seed, metric, metricLabel, rating, borderColor, bgTint." },
            { name: "title", type: "string", default: "Trusted By Leaders", description: "Section heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for the next navigation arrow." },
        ],
        whenToUse: "Perfect for agencies, consultancies, and growth-focused SaaS that want to highlight measurable ROI alongside testimonials.",
        bestPractices: "Use 6 testimonials (3 pairs). Vary borderColor between cards for visual rhythm.",
        whyMatters: "Combining qualitative quotes with quantitative metrics (10x, 15x) builds immediate credibility.",
        faqs: [
            { question: "Can I customize the metric label?", answer: "Yes, each testimonial has its own metricLabel field — 'Increased Revenue', 'Pipeline Growth', etc." },
        ],
    },
    {
        id: "uilora-pixel-bloom",
        name: "Uilora Pixel Bloom",
        description: "Infinite circular carousel with pastel-colored cards, floating DiceBear avatars at the top, quote text, and name/rating at bottom.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["testimonial", "carousel", "pastel", "floating-avatar", "infinite", "light"],
        previewUrl: "/ContentBlocks/Testimonials/UiloraPixelBloom",
        code: {
            tsx: getCode("src/components/ContentBlocks/Testimonials/tsx/UiloraPixelBloom.tsx"),
            jsx: getCode("src/components/ContentBlocks/Testimonials/jsx/UiloraPixelBloom.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Testimonials/UiloraPixelBloom/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "testimonials", type: "Array<{name, role, content, seed, cardColor}>", default: "6 pastel testimonials", description: "Testimonial items with per-card pastel color." },
            { name: "title", type: "string", default: "Learner Success Stories", description: "Section heading." },
            { name: "subtitle", type: "string", default: "See how our learners achieved success...", description: "Section subtitle." },
            { name: "accentColor", type: "string", default: "#7C3AED", description: "Accent color (currently reserved for future use)." },
        ],
        whenToUse: "Great for education platforms, course marketplaces, and community-driven products with a warm, approachable feel.",
        bestPractices: "Use soft pastel cardColors that harmonize. 6 testimonials gives a full circular loop.",
        whyMatters: "Floating avatars above pastel cards create an instantly warm and personal testimonial experience.",
        faqs: [
            { question: "How do I change card colors?", answer: "Each testimonial item has a cardColor field — pass any hex color to style each card individually." },
        ],
    },
];

