import { Component } from "../types";

export const faqComponentsMetadata: Component[] = [
    {
        id: "faq-uilora-cloud",
        name: "Uilora Cloud",
        description: "Soft pastel blue FAQ with frosted glass accordion cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "cloud", "pastel", "glass", "frosted"],
        previewUrl: "/ContentBlocks/FAQ/UiloraCloud",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "7 Uilora FAQs", description: "Array of FAQ items." },
            { name: "title", type: "string", default: "All the details.", description: "Section heading." },
            { name: "subtitle", type: "string", default: "Got a question? We can answer it.", description: "Subtitle text." },
            { name: "accentColor", type: "string", default: "#1B2A4A", description: "Text and icon accent color." },
        ],
    },
    {
        id: "faq-uilora-gallery",
        name: "Uilora Gallery",
        description: "Image + FAQ split layout with clean minimal accordion.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "gallery", "image", "split", "minimal"],
        previewUrl: "/ContentBlocks/FAQ/UiloraGallery",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "5 Uilora FAQs", description: "Array of FAQ items." },
            { name: "title", type: "string", default: "Frequently asked questions", description: "Section heading." },
            { name: "image", type: "string", default: "Unsplash portrait", description: "Left panel image URL." },
            { name: "accentColor", type: "string", default: "#000000", description: "Accent color for active states." },
        ],
    },
    {
        id: "faq-uilora-grid",
        name: "Uilora Grid",
        description: "Editorial 2-column FAQ grid with serif typography and inline expansion.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "grid", "editorial", "serif", "minimal"],
        previewUrl: "/ContentBlocks/FAQ/UiloraGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "9 Uilora FAQs", description: "Array of FAQ items." },
            { name: "title", type: "string", default: "Frequently Asked Questions", description: "Section heading." },
            { name: "subtitle", type: "string", default: "", description: "Optional subtitle text." },
            { name: "accentColor", type: "string", default: "#1a1a1a", description: "Icon and accent color." },
        ],
    },
    {
        id: "faq-uilora-split",
        name: "Uilora Split",
        description: "Image-reactive FAQ with crossfading visuals that change per question.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "split", "image", "reactive", "crossfade"],
        previewUrl: "/ContentBlocks/FAQ/UiloraSplit",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q, a, image}>", default: "5 Uilora FAQs with images", description: "FAQ items with corresponding images." },
            { name: "title", type: "string", default: "Got Questions?", description: "Section heading." },
            { name: "subtitle", type: "string", default: "We've got answers.", description: "Subtitle text." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Active border and icon accent." },
        ],
    },
    {
        id: "faq-uilora-timeline",
        name: "Uilora Timeline",
        description: "Dark timeline FAQ with alternating cards and glowing nodes.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "timeline", "dark", "alternating", "glow"],
        previewUrl: "/ContentBlocks/FAQ/UiloraTimeline",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "6 Uilora FAQs", description: "Array of FAQ items." },
            { name: "title", type: "string", default: "Common Questions", description: "Section heading." },
            { name: "subtitle", type: "string", default: "FAQ", description: "Uppercase tag above heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Timeline glow and number accent color." },
        ],
    },
    {
        id: "faq-brutal",
        name: "Neo-Brutalism",
        description: "Bold neo-brutalist FAQ with chunky design and hard shadows.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "brutalist", "bold", "chunky"],
        previewUrl: "/ContentBlocks/FAQ/FAQBrutal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#FFF4E0", description: "Background color (hex, rgb, or hsl)." },
            { name: "headerBgColor", type: "string", default: "#FF4D4D", description: "Header background color." },
            { name: "headerTextColor", type: "string", default: "#ffffff", description: "Header text color." },
            { name: "headerBorderColor", type: "string", default: "#000000", description: "Header border color." },
            { name: "headerShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Header shadow color." },
            { name: "title", type: "string", default: "Common Queries", description: "Header title text." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "cardBorderColor", type: "string", default: "#000000", description: "Card border color." },
            { name: "cardTextColor", type: "string", default: "#000000", description: "Card text color." },
            { name: "activeCardBgColor", type: "string", default: "#5D9CFF", description: "Active card background color." },
            { name: "activeCardTextColor", type: "string", default: "#000000", description: "Active card text color." },
            { name: "shadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color for cards." },
            { name: "iconBorderColor", type: "string", default: "#000000", description: "Icon border color." },
        ],
    },
    {
        id: "faq-spotlight",
        name: "Dark Spotlight",
        description: "Dark spotlight FAQ with radial hover effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "dark", "spotlight", "hover"],
        previewUrl: "/ContentBlocks/FAQ/FAQSpotlight",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "badgeText", type: "string", default: "Support Center", description: "Badge text displayed above title." },
            { name: "badgeBgColor", type: "string", default: "rgba(23, 23, 23, 0.5)", description: "Badge background color." },
            { name: "badgeBorderColor", type: "string", default: "#262626", description: "Badge border color." },
            { name: "badgeTextColor", type: "string", default: "#a3a3a3", description: "Badge text color." },
            { name: "title", type: "string", default: "Frequently Asked Questions", description: "Section title text." },
            { name: "titleGradientFrom", type: "string", default: "#ffffff", description: "Title gradient start color." },
            { name: "titleGradientTo", type: "string", default: "rgba(255,255,255,0.4)", description: "Title gradient end color." },
            { name: "cardBgColor", type: "string", default: "rgba(23, 23, 23, 0.3)", description: "Card background color." },
            { name: "cardBorderColor", type: "string", default: "#262626", description: "Card border color." },
            { name: "cardTextColor", type: "string", default: "#e5e5e5", description: "Card text color." },
            { name: "hoverCardTextColor", type: "string", default: "#ffffff", description: "Card text color on hover." },
            { name: "answerTextColor", type: "string", default: "#a3a3a3", description: "Answer text color." },
            { name: "iconColor", type: "string", default: "#737373", description: "Icon color." },
            { name: "hoverIconColor", type: "string", default: "#ffffff", description: "Icon color on hover." },
            { name: "spotlightColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Spotlight effect color." },
        ],
    },
    {
        id: "faq-cyber",
        name: "Cyber Terminal",
        description: "Cyber terminal FAQ with glitch and scanline effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "cyber", "terminal", "glitch"],
        previewUrl: "/ContentBlocks/FAQ/FAQCyber",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#050505", description: "Background color (hex, rgb, or hsl)." },
            { name: "gridColor", type: "string", default: "rgba(0,255,0,0.03)", description: "Grid pattern color." },
            { name: "containerBgColor", type: "string", default: "rgba(0,0,0,0.8)", description: "Container background color." },
            { name: "containerBorderColor", type: "string", default: "rgba(0,255,0,0.5)", description: "Container border color." },
            { name: "containerShadowColor", type: "string", default: "rgba(0,255,0,0.1)", description: "Container shadow color." },
            { name: "dotColor1", type: "string", default: "#ef4444", description: "First dot color (red)." },
            { name: "dotColor2", type: "string", default: "#eab308", description: "Second dot color (yellow)." },
            { name: "dotColor3", type: "string", default: "#22c55e", description: "Third dot color (green)." },
            { name: "versionText", type: "string", default: "System_FAQ_v2.0", description: "Version text displayed in header." },
            { name: "versionTextColor", type: "string", default: "rgba(0,255,0,0.7)", description: "Version text color." },
            { name: "questionTextColor", type: "string", default: "rgba(0,255,0,0.7)", description: "Question text color." },
            { name: "activeQuestionTextColor", type: "string", default: "#4ade80", description: "Active question text color." },
            { name: "activeBgColor", type: "string", default: "rgba(0,255,0,0.1)", description: "Active item background color." },
            { name: "activeBorderColor", type: "string", default: "rgba(0,255,0,0.5)", description: "Active item border color." },
            { name: "answerTextColor", type: "string", default: "rgba(0,255,0,0.8)", description: "Answer text color." },
            { name: "answerPrefixColor", type: "string", default: "rgba(0,255,0,0.5)", description: "Answer prefix color (>)." },
            { name: "hoverBorderColor", type: "string", default: "rgba(0,255,0,0.3)", description: "Hover border color." },
        ],
    },
    {
        id: "faq-minimal",
        name: "Soft Minimal",
        description: "Clean and airy minimal FAQ design.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "minimal", "clean", "airy"],
        previewUrl: "/ContentBlocks/FAQ/FAQMinimal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#FAFAFA", description: "Background color (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Help & Support", description: "Section title text." },
            { name: "titleColor", type: "string", default: "#171717", description: "Title text color." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,0.03)", description: "Card shadow color." },
            { name: "cardHoverShadowColor", type: "string", default: "rgba(0,0,0,0.04)", description: "Card shadow color on hover." },
            { name: "iconBorderColor", type: "string", default: "#e5e5e5", description: "Icon border color." },
            { name: "activeIconBgColor", type: "string", default: "#000000", description: "Active icon background color." },
            { name: "activeIconColor", type: "string", default: "#ffffff", description: "Active icon color." },
            { name: "inactiveIconColor", type: "string", default: "#a3a3a3", description: "Inactive icon color." },
            { name: "questionTextColor", type: "string", default: "#737373", description: "Question text color." },
            { name: "activeQuestionTextColor", type: "string", default: "#000000", description: "Active question text color." },
            { name: "answerTextColor", type: "string", default: "#737373", description: "Answer text color." },
        ],
    },
    {
        id: "faq-clay",
        name: "Clay Morphic",
        description: "3D soft clay morphic FAQ with neumorphic design.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "clay", "morphic", "3d"],
        previewUrl: "/ContentBlocks/FAQ/FAQClay",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#eef0f4", description: "Background color (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Just ask.", description: "Section title text." },
            { name: "titleColor", type: "string", default: "#475569", description: "Title text color." },
            { name: "cardBgColor", type: "string", default: "#eef0f4", description: "Card background color." },
            { name: "cardTextColor", type: "string", default: "#475569", description: "Card text color." },
            { name: "cardSubtextColor", type: "string", default: "#64748b", description: "Card subtext/answer color." },
            { name: "iconColor", type: "string", default: "#94a3b8", description: "Icon color." },
            { name: "activeIconBgColor", type: "string", default: "#60a5fa", description: "Active icon background color." },
            { name: "activeIconColor", type: "string", default: "#ffffff", description: "Active icon color." },
            { name: "shadowLightColor", type: "string", default: "#ffffff", description: "Light shadow color for neumorphic effect." },
            { name: "shadowDarkColor", type: "string", default: "#d1d9e6", description: "Dark shadow color for neumorphic effect." },
        ],
    },
    {
        id: "faq-editorial",
        name: "Editorial Split",
        description: "Editorial split FAQ with sticky sidebar.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "editorial", "split", "sticky"],
        previewUrl: "/ContentBlocks/FAQ/FAQEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
            { name: "sidebarBgColor", type: "string", default: "#f5f5f5", description: "Sidebar background color." },
            { name: "sidebarTextColor", type: "string", default: "#000000", description: "Sidebar text color." },
            { name: "title", type: "string", default: "FAQ", description: "Section title text." },
            { name: "titleAccentColor", type: "string", default: "#2563eb", description: "Title accent color (dot color)." },
            { name: "subtitle", type: "string", default: "Everything you need to know about the product and billing.", description: "Section subtitle text." },
            { name: "subtitleColor", type: "string", default: "#737373", description: "Subtitle text color." },
            { name: "currentTopicLabel", type: "string", default: "Current Topic", description: "Label text for current topic indicator." },
            { name: "currentTopicLabelColor", type: "string", default: "#a3a3a3", description: "Current topic label color." },
            { name: "contentBgColor", type: "string", default: "#ffffff", description: "Content area background color." },
            { name: "contentTextColor", type: "string", default: "#000000", description: "Content text color." },
            { name: "borderColor", type: "string", default: "#e5e5e5", description: "Border color for dividers." },
            { name: "badgeBgColor", type: "string", default: "#000000", description: "Badge background color." },
            { name: "badgeTextColor", type: "string", default: "#ffffff", description: "Badge text color." },
            { name: "questionColor", type: "string", default: "#000000", description: "Question text color." },
            { name: "answerColor", type: "string", default: "#737373", description: "Answer text color." },
            { name: "ctaBgColor", type: "string", default: "#dbeafe", description: "CTA section background color." },
            { name: "ctaTextColor", type: "string", default: "#000000", description: "CTA text color." },
            { name: "ctaButtonBgColor", type: "string", default: "#000000", description: "CTA button background color." },
            { name: "ctaButtonTextColor", type: "string", default: "#ffffff", description: "CTA button text color." },
            { name: "ctaTitle", type: "string", default: "Still have questions?", description: "CTA title text." },
            { name: "ctaSubtitle", type: "string", default: "Can't find the answer you're looking for?", description: "CTA subtitle text." },
            { name: "ctaButtonText", type: "string", default: "Contact Support", description: "CTA button text." },
        ],
    },
    {
        id: "faq-sketch",
        name: "Hand-Drawn",
        description: "Hand-drawn sketchy FAQ with paper texture.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "sketch", "hand-drawn", "paper"],
        previewUrl: "/ContentBlocks/FAQ/FAQSketch",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#fffdf5", description: "Background color (hex, rgb, or hsl)." },
            { name: "patternColor", type: "string", default: "#444", description: "Grid pattern color." },
            { name: "title", type: "string", default: "Q & A", description: "Section title text." },
            { name: "titleColor", type: "string", default: "#0f172a", description: "Title text color." },
            { name: "titleUnderlineColor", type: "string", default: "#facc15", description: "Title underline color." },
            { name: "shadowBorderColor", type: "string", default: "#cbd5e1", description: "Shadow border color." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "activeCardBgColor", type: "string", default: "#fef9c3", description: "Active card background color." },
            { name: "cardBorderColor", type: "string", default: "#1e293b", description: "Card border color." },
            { name: "questionColor", type: "string", default: "#0f172a", description: "Question text color." },
            { name: "answerColor", type: "string", default: "#475569", description: "Answer text color." },
            { name: "answerBorderColor", type: "string", default: "#cbd5e1", description: "Answer border color." },
            { name: "tapeBgColor", type: "string", default: "rgba(254, 226, 226, 0.8)", description: "Tape background color." },
        ],
    },
    {
        id: "faq-luxury",
        name: "Luxury Fluid",
        description: "Luxury fluid FAQ with mesh gradient background.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "luxury", "fluid", "gradient"],
        previewUrl: "/ContentBlocks/FAQ/FAQLuxury",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "blob1FromColor", type: "string", default: "#581c87", description: "First blob gradient start color." },
            { name: "blob1ViaColor", type: "string", default: "#312e81", description: "First blob gradient middle color." },
            { name: "blob2FromColor", type: "string", default: "#1e3a8a", description: "Second blob gradient start color." },
            { name: "blob2ViaColor", type: "string", default: "#064e3b", description: "Second blob gradient middle color." },
            { name: "title", type: "string", default: "Inquiries", description: "Section title text." },
            { name: "subtitle", type: "string", default: "Curated answers for the elite.", description: "Section subtitle text." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Title text color." },
            { name: "subtitleColor", type: "string", default: "rgba(255,255,255,0.5)", description: "Subtitle text color." },
            { name: "borderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Border color." },
            { name: "questionTextColor", type: "string", default: "rgba(255,255,255,0.4)", description: "Question text color." },
            { name: "activeQuestionTextColor", type: "string", default: "#ffffff", description: "Active question text color." },
            { name: "hoverQuestionTextColor", type: "string", default: "#ffffff", description: "Question text color on hover." },
            { name: "answerTextColor", type: "string", default: "rgba(255,255,255,0.7)", description: "Answer text color." },
            { name: "iconColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Icon color." },
            { name: "hoverIconColor", type: "string", default: "#ffffff", description: "Icon color on hover." },
        ],
    },
    {
        id: "faq-gravity",
        name: "Gravity Physics",
        description: "Gravity physics FAQ with draggable bubbles.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "gravity", "physics", "draggable"],
        previewUrl: "/ContentBlocks/FAQ/FAQGravity",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{id: number, q: string, a: string}>", default: "[]", description: "Array of FAQ items with id, question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#111111", description: "Background color (hex, rgb, or hsl)." },
            { name: "backgroundText", type: "string", default: "CHAOS", description: "Background text displayed behind bubbles." },
            { name: "backgroundTextColor", type: "string", default: "#222222", description: "Background text color." },
            { name: "bubbleBgColor", type: "string", default: "rgba(255,255,255,0.05)", description: "Bubble background color." },
            { name: "bubbleBorderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Bubble border color." },
            { name: "bubbleTextColor", type: "string", default: "#ffffff", description: "Bubble text color." },
            { name: "activeBubbleBgColor", type: "string", default: "#a3e635", description: "Active bubble background color." },
            { name: "activeBubbleTextColor", type: "string", default: "#000000", description: "Active bubble text color." },
            { name: "activeBubbleShadowColor", type: "string", default: "rgba(163, 230, 53, 0.4)", description: "Active bubble shadow color." },
            { name: "hintText", type: "string", default: "DRAG_TO_INSPECT // PHYSICS_ENGINE_ACTIVE", description: "Hint text displayed at bottom." },
            { name: "hintTextColor", type: "string", default: "rgba(255,255,255,0.5)", description: "Hint text color." },
        ],
    },
    {
        id: "faq-decrypt",
        name: "Decryptor",
        description: "Matrix-style decryptor FAQ with scrambled text.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "decrypt", "matrix", "scrambled"],
        previewUrl: "/ContentBlocks/FAQ/FAQDecrypt",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{id: number, q: string, a: string}>", default: "[]", description: "Array of FAQ items with id, question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#001000", description: "Background color (hex, rgb, or hsl)." },
            { name: "backgroundImage", type: "string", default: "https://media.giphy.com/media/U3qYN8S0j3bpK/giphy.gif", description: "Background image URL for matrix effect." },
            { name: "borderColor", type: "string", default: "#00ff00", description: "Border color." },
            { name: "questionTextColor", type: "string", default: "#00ff00", description: "Question text color." },
            { name: "answerTextColor", type: "string", default: "#00dd00", description: "Answer text color." },
            { name: "activeBgColor", type: "string", default: "#003300", description: "Active item background color." },
            { name: "hoverBgColor", type: "string", default: "#001100", description: "Hover background color." },
            { name: "iconColor", type: "string", default: "#00ff00", description: "Terminal icon color." },
            { name: "scrambleChars", type: "string", default: "XYZ010101<>?//", description: "Characters used for scrambling effect." },
        ],
    },
    {
        id: "faq-elastic",
        name: "Elastic Pull",
        description: "Elastic pull FAQ with spring physics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "elastic", "pull", "spring"],
        previewUrl: "/ContentBlocks/FAQ/FAQElastic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{id: number, q: string, a: string}>", default: "[]", description: "Array of FAQ items with id, question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#171717", description: "Background color (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#262626", description: "Card background color." },
            { name: "cardTextColor", type: "string", default: "#ffffff", description: "Card text color." },
            { name: "dragHintColor", type: "string", default: "#737373", description: "Drag hint text color." },
            { name: "answerBgColor", type: "string", default: "#171717", description: "Answer background color." },
            { name: "answerTextColor", type: "string", default: "#d4d4d4", description: "Answer text color." },
            { name: "answerBorderColor", type: "string", default: "#404040", description: "Answer border color." },
            { name: "dragLeftColor", type: "string", default: "#ff0055", description: "Background color when dragging left." },
            { name: "dragRightColor", type: "string", default: "#0055ff", description: "Background color when dragging right." },
            { name: "dragCenterColor", type: "string", default: "#262626", description: "Background color when centered." },
        ],
    },
];

