import { getCode } from "../getCode";
import { Component } from "../types";

export const faqComponents: Component[] = [
    {
        id: "faq-uilora-cloud",
        name: "Uilora Cloud",
        description: "Soft pastel blue FAQ with frosted glass accordion cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "cloud", "pastel", "glass", "frosted"],
        previewUrl: "/ContentBlocks/FAQ/UiloraCloud",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/UiloraCloud.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/UiloraCloud.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/UiloraCloud/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "7 Uilora FAQs", description: "Array of FAQ items." },
            { name: "title", type: "string", default: "All the details.", description: "Section heading." },
            { name: "subtitle", type: "string", default: "Got a question? We can answer it.", description: "Subtitle text." },
            { name: "accentColor", type: "string", default: "#1B2A4A", description: "Text and icon accent color." },
        ],
        whenToUse: "Ideal for SaaS products, health apps, and friendly brand websites that want a soft, approachable FAQ section with a pastel color scheme.",
        bestPractices: "Use 5-8 FAQ items for the best visual balance. The frosted glass cards work best on the pastel background — avoid using on dark themes.",
        whyMatters: "Soft, approachable design reduces user anxiety around asking questions, increasing engagement with support content.",
        faqs: [
            { question: "Can I change the background color?", answer: "The background uses a pastel blue by default. Modify the component source to change it to any pastel shade." },
            { question: "Does it support dark mode?", answer: "This component is designed for light/pastel themes. For dark mode, consider the Uilora Timeline FAQ." },
        ],
    },
    {
        id: "faq-uilora-gallery",
        name: "Uilora Gallery",
        description: "Image + FAQ split layout with clean minimal accordion.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "gallery", "image", "split", "minimal"],
        previewUrl: "/ContentBlocks/FAQ/UiloraGallery",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/UiloraGallery.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/UiloraGallery.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/UiloraGallery/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "5 Uilora FAQs", description: "Array of FAQ items." },
            { name: "title", type: "string", default: "Frequently asked questions", description: "Section heading." },
            { name: "image", type: "string", default: "Unsplash portrait", description: "Left panel image URL." },
            { name: "accentColor", type: "string", default: "#000000", description: "Accent color for active states." },
        ],
        whenToUse: "Perfect for fashion brands, lifestyle products, and portfolio sites that want a visually striking FAQ section with a hero image alongside clean text.",
        bestPractices: "Use a high-quality vertical/portrait image for the best visual balance. Keep FAQs to 4-6 items.",
        whyMatters: "The image-text split creates visual interest and breaks monotony. It pairs support content with brand imagery for a premium feel.",
        faqs: [
            { question: "Can I use a video instead?", answer: "The image prop accepts a URL. For video, modify the component to use a video element." },
            { question: "Does the image change?", answer: "This version uses a static image. For reactive images, use the Uilora Split FAQ." },
        ],
    },
    {
        id: "faq-uilora-grid",
        name: "Uilora Grid",
        description: "Editorial 2-column FAQ grid with serif typography and inline expansion.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "grid", "editorial", "serif", "minimal"],
        previewUrl: "/ContentBlocks/FAQ/UiloraGrid",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/UiloraGrid.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/UiloraGrid.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/UiloraGrid/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "9 Uilora FAQs", description: "Array of FAQ items." },
            { name: "title", type: "string", default: "Frequently Asked Questions", description: "Section heading." },
            { name: "subtitle", type: "string", default: "", description: "Optional subtitle text." },
            { name: "accentColor", type: "string", default: "#1a1a1a", description: "Icon and accent color." },
        ],
        whenToUse: "Great for editorial websites, documentation pages, and minimalist brands that want a clean FAQ table-of-contents style layout.",
        bestPractices: "Use 6-10 items for a balanced 2-column grid. Keep question text short for the best visual rhythm.",
        whyMatters: "The grid layout makes FAQ content scannable at a glance. Users can quickly find their question without scrolling through a long accordion.",
        faqs: [
            { question: "Can I make it single-column?", answer: "Remove the md:grid-cols-2 class from the grid container to switch to a single column layout." },
            { question: "Does it support categories?", answer: "This version is flat. Group related questions together in the array for implicit categorization." },
        ],
    },
    {
        id: "faq-uilora-split",
        name: "Uilora Split",
        description: "Image-reactive FAQ with crossfading visuals that change per question.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "split", "image", "reactive", "crossfade"],
        previewUrl: "/ContentBlocks/FAQ/UiloraSplit",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/UiloraSplit.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/UiloraSplit.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/UiloraSplit/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q, a, image}>", default: "5 Uilora FAQs with images", description: "FAQ items with corresponding images." },
            { name: "title", type: "string", default: "Got Questions?", description: "Section heading." },
            { name: "subtitle", type: "string", default: "We've got answers.", description: "Subtitle text." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Active border and icon accent." },
        ],
        whenToUse: "Ideal for product pages and feature-rich platforms where each FAQ deserves its own visual context. The image-reactive pattern keeps users engaged.",
        bestPractices: "Use high-quality images that directly relate to each question. Keep to 4-6 items for smooth transitions.",
        whyMatters: "Pairing each question with a relevant image creates a richer learning experience. The crossfade transitions add polish and prevent the section from feeling static.",
        faqs: [
            { question: "How does the image transition work?", answer: "AnimatePresence with mode='wait' handles smooth crossfade transitions between images keyed on the active FAQ index." },
            { question: "Can I use videos?", answer: "The image prop accepts any URL. For video, modify the visual element from img to video." },
        ],
    },
    {
        id: "faq-uilora-timeline",
        name: "Uilora Timeline",
        description: "Dark timeline FAQ with alternating cards and glowing nodes.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "timeline", "dark", "alternating", "glow"],
        previewUrl: "/ContentBlocks/FAQ/UiloraTimeline",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/UiloraTimeline.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/UiloraTimeline.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/UiloraTimeline/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "6 Uilora FAQs", description: "Array of FAQ items." },
            { name: "title", type: "string", default: "Common Questions", description: "Section heading." },
            { name: "subtitle", type: "string", default: "FAQ", description: "Uppercase tag above heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Timeline glow and number accent color." },
        ],
        whenToUse: "Perfect for dark-themed landing pages, developer tools, and tech products that want a unique FAQ layout with visual depth and timeline progression.",
        bestPractices: "Use 4-8 items for a balanced timeline. The alternating layout works best on desktop — mobile collapses to a single column automatically.",
        whyMatters: "The timeline layout transforms a mundane FAQ into a visual journey. The alternating cards and glowing nodes add architectural interest that keeps users scrolling.",
        faqs: [
            { question: "Does it work on mobile?", answer: "Yes, the timeline collapses to a single column with the line on the left edge for mobile devices." },
            { question: "Can I change the glow color?", answer: "Yes, the accentColor prop controls the timeline node glow and number label color." },
        ],
    },
    {
        id: "faq-brutal",
        name: "Neo-Brutalism",
        description: "Bold neo-brutalist FAQ with chunky design and hard shadows.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "brutalist", "bold", "chunky"],
        previewUrl: "/ContentBlocks/FAQ/FAQBrutal",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQBrutal.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQBrutal.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQBrutal/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#FFF4E0", description: "Background color (hex, rgb, or hsl)." },
            { name: "headerBgColor", type: "string", default: "#FF4D4D", description: "Header background color." },
            { name: "headerTextColor", type: "string", default: "#ffffff", description: "Header text color." },
            { name: "headerBorderColor", type: "string", default: "#000000", description: "Header border color." },
            { name: "headerShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Header shadow color." },
            { name: "title", type: "string", default: "Common Queries", description: "Header title text." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "cardBorderColor", type: "string", default: "#000000", description: "Card border color." },
            { name: "cardTextColor", type: "string", default: "#000000", description: "Card text color." },
            { name: "activeCardBgColor", type: "string", default: "#5D9CFF", description: "Active card background color." },
            { name: "activeCardTextColor", type: "string", default: "#000000", description: "Active card text color." },
            { name: "shadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Shadow color for cards." },
            { name: "iconBorderColor", type: "string", default: "#000000", description: "Icon border color." },
        ],
        whenToUse: "Perfect for street-wear brands, experimental agency sites, and high-energy Next.js portfolios that adopt a 'neo-brutalist' aesthetic. Use this React component for a bold, high-contrast FAQ section with chunky shadows and raw geometric borders.",
        bestPractices: "Follow React best practices by pairing this with thick, monospaced typography and saturated primary colors. Maintain scalable component architecture by using it for high-impact section headers. Optimize for performance by using CSS-based box-shadows for the 'chunky' effect.",
        whyMatters: "Neo-brutalist design is a powerful visual statement of raw power and structural honesty. This production-ready UI component helpsคุณ build an interface that feels solid and unyielding, adding a unique architectural signature to your project.",
        faqs: [
            { question: "Can I adjust the shadow intensity?", answer: "Yes, the shadow color and depth can be customized via the `shadowColor` prop to match your brand's contrast level." },
            { question: "Are the colors too bright?", answer: "The default theme uses high-saturation colors, but you can swap them for more muted tones while keeping the layout's structural boldness." },
            { question: "Is it mobile responsive?", answer: "Absolutely, the layout scales perfectly, and the shadows adapt to maintain visual balance on smaller screens." }
        ],
    },
    {
        id: "faq-spotlight",
        name: "Dark Spotlight",
        description: "Dark spotlight FAQ with radial hover effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "dark", "spotlight", "hover"],
        previewUrl: "/ContentBlocks/FAQ/FAQSpotlight",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQSpotlight.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQSpotlight.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQSpotlight/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "badgeText", type: "string", default: "Support Center", description: "Badge text displayed above title." },
            { name: "badgeBgColor", type: "string", default: "rgba(23, 23, 23, 0.5)", description: "Badge background color." },
            { name: "badgeBorderColor", type: "string", default: "#262626", description: "Badge border color." },
            { name: "badgeTextColor", type: "string", default: "#a3a3a3", description: "Badge text color." },
            { name: "title", type: "string", default: "Frequently Asked Questions", description: "Section title text." },
            { name: "titleGradientFrom", type: "string", default: "#ffffff", description: "Title gradient start color." },
            { name: "titleGradientTo", type: "string", default: "rgba(255,255,255,0.4)", description: "Title gradient end color." },
            { name: "cardBgColor", type: "string", default: "rgba(23, 23, 23, 0.3)", description: "Card background color." },
            { name: "cardBorderColor", type: "string", default: "#262626", description: "Card border color." },
            { name: "cardTextColor", type: "string", default: "#e5e5e5", description: "Card text color." },
            { name: "hoverCardTextColor", type: "string", default: "#ffffff", description: "Card text color on hover." },
            { name: "answerTextColor", type: "string", default: "#a3a3a3", description: "Answer text color." },
            { name: "iconColor", type: "string", default: "#737373", description: "Icon color." },
            { name: "hoverIconColor", type: "string", default: "#ffffff", description: "Icon color on hover." },
            { name: "spotlightColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Spotlight effect color." },
        ],
        whenToUse: "Excellent for dark mode landing pages, premium developer tools, and Next.js sites that want a mysterious, high-end aesthetic. Use this React component for a subtle FAQ section with radial spotlight hover effects and glowing gradients.",
        bestPractices: "Maintain consistent spacing within your design system by using this on dark or textured backgrounds. Follow React best practices by pairing it with high-contrast text. Optimize for performance by managed the spotlight calculation for high-DPI displays.",
        whyMatters: "Spotlight effects create a sense of exclusivity and focus. This production-ready component provides a refined version of this aesthetic, adding a layer of visual excitement and perceived value to your interface.",
        faqs: [
            { question: "How does the spotlight work?", answer: "The component tracks mouse movements and applies a radial gradient mask to create a localized glow on the active card." },
            { question: "Is it too dark for readability?", answer: "It uses a sophisticated balance of low-opacity backgrounds and high-contrast text to ensure accessibility while maintaining the dark aesthetic." },
            { question: "Can I change the glow color?", answer: "Yes, the `spotlightColor` prop allows you to customize the glow to match your brand's primary or secondary colors." }
        ],
    },
    {
        id: "faq-cyber",
        name: "Cyber Terminal",
        description: "Cyber terminal FAQ with glitch and scanline effects.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "cyber", "terminal", "glitch"],
        previewUrl: "/ContentBlocks/FAQ/FAQCyber",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQCyber.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQCyber.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQCyber/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#050505", description: "Background color (hex, rgb, or hsl)." },
            { name: "gridColor", type: "string", default: "rgba(0,255,0,0.03)", description: "Grid pattern color." },
            { name: "containerBgColor", type: "string", default: "rgba(0,0,0,0.8)", description: "Container background color." },
            { name: "containerBorderColor", type: "string", default: "rgba(0,255,0,0.5)", description: "Container border color." },
            { name: "containerShadowColor", type: "string", default: "rgba(0,255,0,0.1)", description: "Container shadow color." },
            { name: "dotColor1", type: "string", default: "#ef4444", description: "First dot color (red)." },
            { name: "dotColor2", type: "string", default: "#eab308", description: "Second dot color (yellow)." },
            { name: "dotColor3", type: "string", default: "#22c55e", description: "Third dot color (green)." },
            { name: "versionText", type: "string", default: "System_FAQ_v2.0", description: "Version text displayed in header." },
            { name: "versionTextColor", type: "string", default: "rgba(0,255,0,0.7)", description: "Version text color." },
            { name: "questionTextColor", type: "string", default: "rgba(0,255,0,0.7)", description: "Question text color." },
            { name: "activeQuestionTextColor", type: "string", default: "#4ade80", description: "Active question text color." },
            { name: "activeBgColor", type: "string", default: "rgba(0,255,0,0.1)", description: "Active item background color." },
            { name: "activeBorderColor", type: "string", default: "rgba(0,255,0,0.5)", description: "Active item border color." },
            { name: "answerTextColor", type: "string", default: "rgba(0,255,0,0.8)", description: "Answer text color." },
            { name: "answerPrefixColor", type: "string", default: "rgba(0,255,0,0.5)", description: "Answer prefix color (>)." },
            { name: "hoverBorderColor", type: "string", default: "rgba(0,255,0,0.3)", description: "Hover border color." },
        ],
        whenToUse: "Ideal for terminal-style dashboards, cyberpunk landing pages, and Next.js sites that want a digital 'CRT' aesthetic. Use this React component for a scanline effect with integrated digital signal noise and a glowing terminal green color palette.",
        bestPractices: "Follow React best practices by pairing this with monospaced typography. Maintain scalable component architecture by keeping the scanline opacity low enough to ensure content readability. Optimize for performance by managing the glitch animation durations.",
        whyMatters: "Cyber terminal visuals evoke a sense of technical authority and secure infrastructure. This customizable UI component givesคุณ a hardware-accelerated version of this aesthetic, reinforcing a technical feel for your project.",
        faqs: [
            { question: "Can I change the terminal color?", answer: "Yes, you can customize the border, text, and active colors to create amber, cyan, or white CRT effects." },
            { question: "How intensive is the glitch?", answer: "The glitch is subtle by default to ensure it doesn't distract from the actual content while still providing a techy vibe." },
            { question: "Does it support custom fonts?", answer: "Yes, while it defaults to monospaced, you can pass any system or Google Font via your CSS to enhance the terminal look." }
        ],
    },
    {
        id: "faq-minimal",
        name: "Soft Minimal",
        description: "Clean and airy minimal FAQ design.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "minimal", "clean", "airy"],
        previewUrl: "/ContentBlocks/FAQ/FAQMinimal",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQMinimal.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQMinimal.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQMinimal/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#FAFAFA", description: "Background color (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Help & Support", description: "Section title text." },
            { name: "titleColor", type: "string", default: "#171717", description: "Title text color." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,0.03)", description: "Card shadow color." },
            { name: "cardHoverShadowColor", type: "string", default: "rgba(0,0,0,0.04)", description: "Card shadow color on hover." },
            { name: "iconBorderColor", type: "string", default: "#e5e5e5", description: "Icon border color." },
            { name: "activeIconBgColor", type: "string", default: "#000000", description: "Active icon background color." },
            { name: "activeIconColor", type: "string", default: "#ffffff", description: "Active icon color." },
            { name: "inactiveIconColor", type: "string", default: "#a3a3a3", description: "Inactive icon color." },
            { name: "questionTextColor", type: "string", default: "#737373", description: "Question text color." },
            { name: "activeQuestionTextColor", type: "string", default: "#000000", description: "Active question text color." },
            { name: "answerTextColor", type: "string", default: "#737373", description: "Answer text color." },
        ],
        whenToUse: "Perfect for high-end SaaS landing pages, minimal portfolios, and Next.js applications that want an airy, clean, and professional aesthetic. Use this React component for a clutter-free FAQ section with soft shadows and refined interactions.",
        bestPractices: "Maintain consistent spacing within your design system by using plenty of white space. Follow React best practices by using subtle transitions instead of aggressive animations. Optimize for performance by avoiding heavy filters or complex background layers.",
        whyMatters: "Minimalism communicate clarity and reliability. This production-ready component helpsคุณ build an interface that feels lightweight and user-focused, improving the perceived quality of your support content.",
        faqs: [
            { question: "How minimal is the design?", answer: "It removes all non-essential borders and lines, relying on soft shadows and typography to create a sense of hierarchy." },
            { question: "Can I change the active icon?", answer: "The icon uses Lucide-React and can be customized via the component's internal structure to match your brand's iconography." },
            { question: "Is it suitable for long answers?", answer: "Yes, the clean layout ensures that long-form text remains readable without overcrowding the section." }
        ],
    },
    {
        id: "faq-clay",
        name: "Clay Morphic",
        description: "3D soft clay morphic FAQ with neumorphic design.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "clay", "morphic", "3d"],
        previewUrl: "/ContentBlocks/FAQ/FAQClay",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQClay.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQClay.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQClay/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#eef0f4", description: "Background color (hex, rgb, or hsl)." },
            { name: "title", type: "string", default: "Just ask.", description: "Section title text." },
            { name: "titleColor", type: "string", default: "#475569", description: "Title text color." },
            { name: "cardBgColor", type: "string", default: "#eef0f4", description: "Card background color." },
            { name: "cardTextColor", type: "string", default: "#475569", description: "Card text color." },
            { name: "cardSubtextColor", type: "string", default: "#64748b", description: "Card subtext/answer color." },
            { name: "iconColor", type: "string", default: "#94a3b8", description: "Icon color." },
            { name: "activeIconBgColor", type: "string", default: "#60a5fa", description: "Active icon background color." },
            { name: "activeIconColor", type: "string", default: "#ffffff", description: "Active icon color." },
            { name: "shadowLightColor", type: "string", default: "#ffffff", description: "Light shadow color for neumorphic effect." },
            { name: "shadowDarkColor", type: "string", default: "#d1d9e6", description: "Dark shadow color for neumorphic effect." },
        ],
        whenToUse: "Excellent for playful brand identities, educational platforms, and Next.js applications that want a tactile, 'squishy' aesthetic. Use this React component for a 3D-feeling FAQ section with soft claymophic shadows and rounded UI elements.",
        bestPractices: "Maintain consistent spacing within your design system by pairing this with pastel colors and soft typography. Follow React best practices by using high-contrast colors for the active icon state. Optimize for performance by using efficient box-shadow combinations for the 3D effect.",
        whyMatters: "Claymorphism adds a unique tactile dimension to digital interfaces, making them feel more interactive and approachable. This production-ready component helpsคุณ build an interface that stands out through its unique 3D visual language.",
        faqs: [
            { question: "What is claymorphism?", answer: "It is a design trend that uses multiple inner and outer shadows to create a soft, 3D 'clay-like' appearance for UI elements." },
            { question: "Can I use it in dark mode?", answer: "Yes, you can customize the background and shadow colors to create 'dark clay' aesthetics while maintaining the soft 3D look." },
            { question: "Does it work on mobile?", answer: "Absolutely, the shadows and rounded corners scale perfectly across all screen sizes for a consistent tactile experience." }
        ],
    },
    {
        id: "faq-editorial",
        name: "Editorial Split",
        description: "Editorial split FAQ with sticky sidebar.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "editorial", "split", "sticky"],
        previewUrl: "/ContentBlocks/FAQ/FAQEditorial",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQEditorial.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQEditorial.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQEditorial/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
            { name: "sidebarBgColor", type: "string", default: "#f5f5f5", description: "Sidebar background color." },
            { name: "sidebarTextColor", type: "string", default: "#000000", description: "Sidebar text color." },
            { name: "title", type: "string", default: "FAQ", description: "Section title text." },
            { name: "titleAccentColor", type: "string", default: "#2563eb", description: "Title accent color (dot color)." },
            { name: "subtitle", type: "string", default: "Everything you need to know about the product and billing.", description: "Section subtitle text." },
            { name: "subtitleColor", type: "string", default: "#737373", description: "Subtitle text color." },
            { name: "currentTopicLabel", type: "string", default: "Current Topic", description: "Label text for current topic indicator." },
            { name: "currentTopicLabelColor", type: "string", default: "#a3a3a3", description: "Current topic label color." },
            { name: "contentBgColor", type: "string", default: "#ffffff", description: "Content area background color." },
            { name: "contentTextColor", type: "string", default: "#000000", description: "Content text color." },
            { name: "borderColor", type: "string", default: "#e5e5e5", description: "Border color for dividers." },
            { name: "badgeBgColor", type: "string", default: "#000000", description: "Badge background color." },
            { name: "badgeTextColor", type: "string", default: "#ffffff", description: "Badge text color." },
            { name: "questionColor", type: "string", default: "#000000", description: "Question text color." },
            { name: "answerColor", type: "string", default: "#737373", description: "Answer text color." },
            { name: "ctaBgColor", type: "string", default: "#dbeafe", description: "CTA section background color." },
            { name: "ctaTextColor", type: "string", default: "#000000", description: "CTA text color." },
            { name: "ctaButtonBgColor", type: "string", default: "#000000", description: "CTA button background color." },
            { name: "ctaButtonTextColor", type: "string", default: "#ffffff", description: "CTA button text color." },
            { name: "ctaTitle", type: "string", default: "Still have questions?", description: "CTA title text." },
            { name: "ctaSubtitle", type: "string", default: "Can't find the answer you're looking for?", description: "CTA subtitle text." },
            { name: "ctaButtonText", type: "string", default: "Contact Support", description: "CTA button text." },
        ],
        whenToUse: "Ideal for content-heavy sites, corporate landing pages, and Next.js applications that require a structured, informative layout. Use this React component for an editorial-style FAQ section with a sticky sidebar and integrated call-to-action.",
        bestPractices: "Follow React best practices by pairing this with bold, professional typography. Maintain scalable component architecture by using the sticky sidebar for secondary navigation. Optimize for performance by ensuring the sidebar only sticks on desktop views.",
        whyMatters: "Editorial layouts provide a sense of hierarchy and authority. This production-ready component helpsคุณ build an interface that feels academic and reliable, improving the efficiency of information retrieval for your users.",
        faqs: [
            { question: "Is the sidebar sticky?", answer: "Yes, the sidebar stays in view as the user scrolls through the FAQ content, ensuring the context is never lost." },
            { question: "Can I add more categories?", answer: "The layout is designed for a single primary category, but can be easily extended to support multiple sections with a tabbed sidebar." },
            { question: "Does it support long answers?", answer: "The split layout provides ample horizontal space for detailed answers and supporting information without visual clutter." }
        ],
    },
    {
        id: "faq-sketch",
        name: "Hand-Drawn",
        description: "Hand-drawn sketchy FAQ with paper texture.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "sketch", "hand-drawn", "paper"],
        previewUrl: "/ContentBlocks/FAQ/FAQSketch",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQSketch.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQSketch.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQSketch/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#fffdf5", description: "Background color (hex, rgb, or hsl)." },
            { name: "patternColor", type: "string", default: "#444", description: "Grid pattern color." },
            { name: "title", type: "string", default: "Q & A", description: "Section title text." },
            { name: "titleColor", type: "string", default: "#0f172a", description: "Title text color." },
            { name: "titleUnderlineColor", type: "string", default: "#facc15", description: "Title underline color." },
            { name: "shadowBorderColor", type: "string", default: "#cbd5e1", description: "Shadow border color." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "activeCardBgColor", type: "string", default: "#fef9c3", description: "Active card background color." },
            { name: "cardBorderColor", type: "string", default: "#1e293b", description: "Card border color." },
            { name: "questionColor", type: "string", default: "#0f172a", description: "Question text color." },
            { name: "answerColor", type: "string", default: "#475569", description: "Answer text color." },
            { name: "answerBorderColor", type: "string", default: "#cbd5e1", description: "Answer border color." },
            { name: "tapeBgColor", type: "string", default: "rgba(254, 226, 226, 0.8)", description: "Tape background color." },
        ],
        whenToUse: "Great for creative portfolios, personal workshops, and Next.js applications that want an organic, 'hand-crafted' aesthetic. Use this React component for a rough, hand-drawn FAQ section with paper textures and playful 'tape' accents.",
        bestPractices: "Maintain consistent spacing within your design system by pairing this with handwritten or organic typography. Follow React best practices by using warm, 'paper-like' background colors. Optimize for performance by using lightweight SVG paths for the hand-drawn elements.",
        whyMatters: "Hand-drawn visuals create a sense of approachability and human touch. This production-ready component helpsคุณ build an interface that feels friendly and personalized, improving user trust through aesthetic warmth.",
        faqs: [
            { question: "How real is the paper texture?", answer: "It uses a subtle grain overlay combined with a light-colored background filter to mimic the look of unbleached notebook paper." },
            { question: "Can I change the tape color?", answer: "Yes, the `tapeBgColor` prop allows you to choose from various wash-tape styles like pink, blue, or yellow." },
            { question: "Are the borders perfectly straight?", answer: "No, the borders are procedurally 'roughened' through SVG paths to maintain the authentic hand-drawn feel across all components." }
        ],
    },
    {
        id: "faq-luxury",
        name: "Luxury Fluid",
        description: "Luxury fluid FAQ with mesh gradient background.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "luxury", "fluid", "gradient"],
        previewUrl: "/ContentBlocks/FAQ/FAQLuxury",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQLuxury.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQLuxury.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQLuxury/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{q: string, a: string}>", default: "[]", description: "Array of FAQ items with question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "blob1FromColor", type: "string", default: "#581c87", description: "First blob gradient start color." },
            { name: "blob1ViaColor", type: "string", default: "#312e81", description: "First blob gradient middle color." },
            { name: "blob2FromColor", type: "string", default: "#1e3a8a", description: "Second blob gradient start color." },
            { name: "blob2ViaColor", type: "string", default: "#064e3b", description: "Second blob gradient middle color." },
            { name: "title", type: "string", default: "Inquiries", description: "Section title text." },
            { name: "subtitle", type: "string", default: "Curated answers for the elite.", description: "Section subtitle text." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Title text color." },
            { name: "subtitleColor", type: "string", default: "rgba(255,255,255,0.5)", description: "Subtitle text color." },
            { name: "borderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Border color." },
            { name: "questionTextColor", type: "string", default: "rgba(255,255,255,0.4)", description: "Question text color." },
            { name: "activeQuestionTextColor", type: "string", default: "#ffffff", description: "Active question text color." },
            { name: "hoverQuestionTextColor", type: "string", default: "#ffffff", description: "Question text color on hover." },
            { name: "answerTextColor", type: "string", default: "rgba(255,255,255,0.7)", description: "Answer text color." },
            { name: "iconColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Icon color." },
            { name: "hoverIconColor", type: "string", default: "#ffffff", description: "Icon color on hover." },
        ],
        whenToUse: "Perfect for high-end boutique brands, premium service landing pages, and Next.js sites that want a refined, luxurious aesthetic. Use this React component for an elegant FAQ section with mesh gradients and soft, fluid typography interactions.",
        bestPractices: "Maintain consistent spacing within your design system by using it as a thematic backdrop for immersive sections. Follow React best practices by pairing it with high-contrast active states. Optimize for performance by using hardware-accelerated mesh gradient animations.",
        whyMatters: "Luxury visuals communicate exclusivity and attention to detail. This production-ready component helpsคุณ build an interface that feels expensive and atmospheric, ensuring your support content aligns with your premium brand identity.",
        faqs: [
            { question: "Is the mesh gradient animated?", answer: "Yes, it uses slow-moving color blobs to create a hypnotically fluid background that doesn't distract from the text." },
            { question: "How readable is the text?", answer: "The component carefully balances opacity and color to ensure that the text remains perfectly legible against the dynamic background." },
            { question: "Can I use custom font weights?", answer: "The luxury aesthetic is best paired with high-contrast weights, which you can easily control via your project's global CSS." }
        ],
    },
    {
        id: "faq-gravity",
        name: "Gravity Physics",
        description: "Gravity physics FAQ with draggable bubbles.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "gravity", "physics", "draggable"],
        previewUrl: "/ContentBlocks/FAQ/FAQGravity",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQGravity.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQGravity.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQGravity/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{id: number, q: string, a: string}>", default: "[]", description: "Array of FAQ items with id, question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#111111", description: "Background color (hex, rgb, or hsl)." },
            { name: "backgroundText", type: "string", default: "CHAOS", description: "Background text displayed behind bubbles." },
            { name: "backgroundTextColor", type: "string", default: "#222222", description: "Background text color." },
            { name: "bubbleBgColor", type: "string", default: "rgba(255,255,255,0.05)", description: "Bubble background color." },
            { name: "bubbleBorderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Bubble border color." },
            { name: "bubbleTextColor", type: "string", default: "#ffffff", description: "Bubble text color." },
            { name: "activeBubbleBgColor", type: "string", default: "#a3e635", description: "Active bubble background color." },
            { name: "activeBubbleTextColor", type: "string", default: "#000000", description: "Active bubble text color." },
            { name: "activeBubbleShadowColor", type: "string", default: "rgba(163, 230, 53, 0.4)", description: "Active bubble shadow color." },
            { name: "hintText", type: "string", default: "DRAG_TO_INSPECT // PHYSICS_ENGINE_ACTIVE", description: "Hint text displayed at bottom." },
            { name: "hintTextColor", type: "string", default: "rgba(255,255,255,0.5)", description: "Hint text color." },
        ],
        whenToUse: "Ideal for experimental labs, creative agency landing pages, and Next.js applications that want a playful, interactive 'chaos' aesthetic. Use this React component for an FAQ section where questions are individual physics-based bubbles that users can drag and toss.",
        bestPractices: "Maintain consistent spacing within your design system by using it for high-impact narrative sections. Follow React best practices by pairing it with clear 'Hint' text. Optimize for performance by managing the number of concurrent physics bodies to ensure smooth 60fps interaction.",
        whyMatters: "Physics-based UIs create a sense of tangibility and fun. This production-ready component helpsคุณ build an interface that feels toy-like and engaging, making the process of information discovery memorable for your users.",
        faqs: [
            { question: "How realistic is the physics?", answer: "It uses a simplified 2D physics engine with gravity, collision detection, and friction to ensure bubbles feel 'heavy' and reactive." },
            { question: "What happens when I click a bubble?", answer: "The bubble expands and locks into a focused state, displaying the answer while the other bubbles react to the collision." },
            { question: "Is it too chaotic for serious sites?", answer: "The 'chaos' can be controlled by adjusting the initial velocity and gravity props, allowing for a more stable or hyper-active experience." }
        ],
    },
    {
        id: "faq-decrypt",
        name: "Decryptor",
        description: "Matrix-style decryptor FAQ with scrambled text.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "decrypt", "matrix", "scrambled"],
        previewUrl: "/ContentBlocks/FAQ/FAQDecrypt",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQDecrypt.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQDecrypt.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQDecrypt/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{id: number, q: string, a: string}>", default: "[]", description: "Array of FAQ items with id, question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#001000", description: "Background color (hex, rgb, or hsl)." },
            { name: "backgroundImage", type: "string", default: "https://media.giphy.com/media/U3qYN8S0j3bpK/giphy.gif", description: "Background image URL for matrix effect." },
            { name: "borderColor", type: "string", default: "#00ff00", description: "Border color." },
            { name: "questionTextColor", type: "string", default: "#00ff00", description: "Question text color." },
            { name: "answerTextColor", type: "string", default: "#00dd00", description: "Answer text color." },
            { name: "activeBgColor", type: "string", default: "#003300", description: "Active item background color." },
            { name: "hoverBgColor", type: "string", default: "#001100", description: "Hover background color." },
            { name: "iconColor", type: "string", default: "#00ff00", description: "Terminal icon color." },
            { name: "scrambleChars", type: "string", default: "XYZ010101<>?//", description: "Characters used for scrambling effect." },
        ],
        whenToUse: "Perfect for security-themed sites, developer portfolios, and Next.js sites that want a digital 'hacker' or Matrix aesthetic. Use this React component for a high-fidelity 'decrypting' effect where text scrambles and solves as the user hovers over it.",
        bestPractices: "Follow React best practices by using monospaced typography and high-contrast colors (e.g., matrix green on black). Maintain scalable component architecture by adjusting `scrambleChars` for different thematic intensities. Optimize for performance by managed the scramble frequency.",
        whyMatters: "Decryption visuals communicate technical depth and security. This production-ready component helpsคุณ build an interface that feels advanced and encrypted, reinforcing a technical brand identity.",
        faqs: [
            { question: "How does the scramble work?", answer: "The component replaces the original text with random characters (`scrambleChars`) and progressively 'solves' them back to the original text over a short duration." },
            { question: "Can I use it as a background?", answer: "Yes, it includes an optional background GIF or image layer (like the classic Matrix code) to reinforce the technical aesthetic." },
            { question: "Does it support custom characters?", answer: "Absolutely, you can pass any string of characters to the `scrambleChars` prop to create different types of 'encrypted' looks." }
        ],
    },
    {
        id: "faq-elastic",
        name: "Elastic Pull",
        description: "Elastic pull FAQ with spring physics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["faq", "elastic", "pull", "spring"],
        previewUrl: "/ContentBlocks/FAQ/FAQElastic",
        code: {
            tsx: getCode("src/components/ContentBlocks/FAQ/tsx/FAQElastic.tsx"),
            jsx: getCode("src/components/ContentBlocks/FAQ/jsx/FAQElastic.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/FAQ/FAQElastic/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "faqs", type: "Array<{id: number, q: string, a: string}>", default: "[]", description: "Array of FAQ items with id, question (q) and answer (a)." },
            { name: "backgroundColor", type: "string", default: "#171717", description: "Background color (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#262626", description: "Card background color." },
            { name: "cardTextColor", type: "string", default: "#ffffff", description: "Card text color." },
            { name: "dragHintColor", type: "string", default: "#737373", description: "Drag hint text color." },
            { name: "answerBgColor", type: "string", default: "#171717", description: "Answer background color." },
            { name: "answerTextColor", type: "string", default: "#d4d4d4", description: "Answer text color." },
            { name: "answerBorderColor", type: "string", default: "#404040", description: "Answer border color." },
            { name: "dragLeftColor", type: "string", default: "#ff0055", description: "Background color when dragging left." },
            { name: "dragRightColor", type: "string", default: "#0055ff", description: "Background color when dragging right." },
            { name: "dragCenterColor", type: "string", default: "#262626", description: "Background color when centered." },
        ],
        whenToUse: "Excellent for mobile-first applications, playful landing pages, and Next.js sites that want a tactile, 'stretchy' aesthetic. Use this React component for an FAQ section where answers are revealed through elastic 'pull-to-open' interactions and spring-based physics.",
        bestPractices: "Maintain consistent spacing within your design system by using it as a secondary information layer. Follow React best practices by pairing it with clear drag indicators. Optimize for performance by using Framer Motion's hardware-accelerated spring animations.",
        whyMatters: "Elastic interactions feel more natural and responsive to swipe gestures. This production-ready component helpsคุณ build an interface that feels modern and lightweight, improving the joy of small interactions (micro-interactions) in your project.",
        faqs: [
            { question: "How does the pull reveal work?", answer: "Users can drag the FAQ card horizontally; as it stretches, it changes color and reveals high-priority actions or the answer layer." },
            { question: "Is the spring physics customizable?", answer: "Yes, you can control the stiffness and damping of the pull effect to make it feel more or less 'snappy'." },
            { question: "Can I use it for left/right actions?", answer: "The component supports independent background colors for both left and right drag directions, allowing for versatile 'swipe-to-action' patterns." }
        ],
    },
];

