import { getCode } from "../getCode";
import { Component } from "../types";

export const pricingComponents: Component[] = [
    {
        id: "uilora-dynamic",
        name: "Uilora Dynamic",
        description: "Interactive tiered pricing calculator with seat slider, billing toggle, and real-time cost breakdown.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "interactive", "slider", "calculator", "tiers", "saas"],
        previewUrl: "/ContentBlocks/Pricing/UiloraDynamic",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/UiloraDynamic.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/UiloraDynamic.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/UiloraDynamic/page.tsx") },
        dependencies: ["react"],
        props: [
            { name: "accentColor", type: "string", default: '"#5227FF"', description: "Accent color for toggle, slider, badge, and breakdown highlights." },
        ],
    },
    {
        id: "uilora-cloud-slider",
        name: "Uilora Cloud Slider",
        description: "Dark navy 3-plan cloud pricing with per-card vCPU/storage/SLA sliders, add-on checkboxes, and live price calculation.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "dark", "cloud", "slider", "interactive", "saas"],
        previewUrl: "/ContentBlocks/Pricing/UiloraCloudSlider",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/UiloraCloudSlider.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/UiloraCloudSlider.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/UiloraCloudSlider/page.tsx") },
        dependencies: ["react"],
        props: [],
    },
    {
        id: "uilora-matrix",
        name: "Uilora Matrix",
        description: "Feature comparison matrix with 3 plans, monthly/yearly toggle, Pro spotlight, check/cross icons, and library badges.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "comparison", "matrix", "features", "table", "saas"],
        previewUrl: "/ContentBlocks/Pricing/UiloraMatrix",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/UiloraMatrix.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/UiloraMatrix.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/UiloraMatrix/page.tsx") },
        dependencies: ["react"],
        props: [
            { name: "accentColor", type: "string", default: '"#7C3AED"', description: "Accent color for Pro column, badges, and CTA button." },
        ],
    },
    {
        id: "uilora-spectra",
        name: "Uilora Spectra",
        description: "Full-screen overlapping dual-card service pricing with feature tag grids, starting price, and Book a call CTA.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "agency", "service", "cards", "overlap", "gradient"],
        previewUrl: "/ContentBlocks/Pricing/UiloraSpectra",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/UiloraSpectra.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/UiloraSpectra.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/UiloraSpectra/page.tsx") },
        dependencies: ["react"],
        props: [
            { name: "accentColor", type: "string", default: '"#FF2DCA"', description: "Accent color for the Book a call button." },
        ],
    },
    {
        id: "uilora-framify",
        name: "Uilora Framify",
        description: "3-column pricing layout with 2 plan cards and a stacked testimonials sidebar featuring DiceBear avatars and star ratings.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "testimonials", "social-proof", "plans", "light", "saas"],
        previewUrl: "/ContentBlocks/Pricing/UiloraFramify",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/UiloraFramify.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/UiloraFramify.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/UiloraFramify/page.tsx") },
        dependencies: ["react"],
        props: [
            { name: "accentColor", type: "string", default: '"#7C3AED"', description: "Accent color for Studio plan price, CTA button, and Popular badge." },
        ],
    },
    {
        id: "pricing-glass",
        name: "Glass Prism",
        description: "Crystal clear glass prism pricing cards with backdrop blur.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "glass", "prism", "blur"],
        previewUrl: "/ContentBlocks/Pricing/PricingGlass",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingGlass.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingGlass.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingGlass/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Crystal Clear Pricing", description: "Section title text." },
            { name: "plans", type: "Array<{name: string, monthlyPrice: number, yearlyPrice: number, features?: string[]}>", default: "[]", description: "Array of pricing plans with name, monthly and yearly prices, and optional features." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "backgroundColor", type: "string", default: "#0f172a", description: "Background color (hex, rgb, or hsl)." },
            { name: "blob1Color", type: "string", default: "#9333ea", description: "First blob color for background effect." },
            { name: "blob2Color", type: "string", default: "#06b6d4", description: "Second blob color for background effect." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Title text color." },
            { name: "toggleBgColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Toggle background color." },
            { name: "toggleBorderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Toggle border color." },
            { name: "toggleActiveColor", type: "string", default: "#ffffff", description: "Toggle active state color." },
            { name: "toggleInactiveColor", type: "string", default: "rgba(255,255,255,0.4)", description: "Toggle inactive state color." },
            { name: "cardBgColor", type: "string", default: "rgba(255,255,255,0.05)", description: "Card background color." },
            { name: "activeCardGradientFrom", type: "string", default: "rgba(168, 85, 247, 0.2)", description: "Active card gradient start color." },
            { name: "activeCardGradientTo", type: "string", default: "rgba(6, 182, 212, 0.2)", description: "Active card gradient end color." },
            { name: "cardBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Card border color." },
            { name: "planNameColor", type: "string", default: "rgba(255,255,255,0.8)", description: "Plan name text color." },
            { name: "priceColor", type: "string", default: "#ffffff", description: "Price text color." },
            { name: "priceGradientFrom", type: "string", default: "#ffffff", description: "Price gradient start color." },
            { name: "priceGradientTo", type: "string", default: "rgba(255,255,255,0.5)", description: "Price gradient end color." },
            { name: "featureTextColor", type: "string", default: "rgba(255,255,255,0.6)", description: "Feature text color." },
            { name: "featureIconBgColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Feature icon background color." },
            { name: "buttonBgFrom", type: "string", default: "rgba(255,255,255,0.1)", description: "Button gradient start color." },
            { name: "buttonBgTo", type: "string", default: "rgba(255,255,255,0.05)", description: "Button gradient end color." },
            { name: "buttonBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Button border color." },
            { name: "buttonTextColor", type: "string", default: "#ffffff", description: "Button text color." },
            { name: "buttonText", type: "string", default: "Choose Plan", description: "Button text." },
        ],
        whenToUse: "Excellent for modern SaaS platforms, AI tools, and Next.js applications that want a high-fidelity, transparent aesthetic. Use this React component for a pricing section where tiers are displayed as blurry glass cards with vibrant background glow effects.",
        bestPractices: "Maintain consistent spacing within your design system by using it on dark or textured backgrounds to maximize the glass effect. Follow React best practices by using high-contrast text for the features list. Optimize for performance by managed the blur intensity on mobile devices.",
        whyMatters: "Glassmorphism creates a sense of depth and technical sophistication that appeals to modern tech users. This production-ready UI component helpsคุณ build an interface that feels lightweight and premium, improving the perceived quality of your product tiers.",
        faqs: [
            { question: "Is the monthly/yearly toggle included?", answer: "Yes, the component features a smooth animated toggle that switches between monthly and yearly pricing plans." },
            { question: "Can I customize the background blobs?", answer: "The `blob1Color` and `blob2Color` props allow you to customize the underlying glow colors to match your brand's palette." },
            { question: "How many features can I list?", answer: "While you can list many, it's best to keep it to 5-8 key features to ensure the glass card remains balanced and legible." }
        ],
    },
    {
        id: "pricing-brutalist",
        name: "Neo-Brutalism",
        description: "Bold neo-brutalist pricing cards with chunky shadows.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "brutalist", "bold", "chunky"],
        previewUrl: "/ContentBlocks/Pricing/PricingBrutalist",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingBrutalist.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingBrutalist.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingBrutalist/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "No Hidden Fees.", description: "Section title text." },
            { name: "titleLine1", type: "string", default: "No Hidden Fees.", description: "First line of title." },
            { name: "titleLine2", type: "string", default: "Just Raw Value.", description: "Second line of title." },
            { name: "plans", type: "Array<{name: string, price: number, badge?: string}>", default: "[]", description: "Array of pricing plans with name, price, and optional badge." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "backgroundColor", type: "string", default: "#F4F4F0", description: "Background color (hex, rgb, or hsl)." },
            { name: "headerBgColor", type: "string", default: "#FF5E5B", description: "Header background color." },
            { name: "headerBorderColor", type: "string", default: "#000000", description: "Header border color." },
            { name: "headerTextColor", type: "string", default: "#000000", description: "Header text color." },
            { name: "headerShadowColor", type: "string", default: "rgba(0,0,0,1)", description: "Header shadow color." },
            { name: "cardBgColors", type: "string[]", default: "[\"#A3E635\", \"#60A5FA\", \"#F472B6\"]", description: "Array of card background colors." },
            { name: "cardBorderColor", type: "string", default: "#000000", description: "Card border color." },
            { name: "cardTextColor", type: "string", default: "#000000", description: "Card text color." },
            { name: "badgeBgColor", type: "string", default: "#000000", description: "Badge background color." },
            { name: "badgeTextColor", type: "string", default: "#ffffff", description: "Badge text color." },
            { name: "priceColor", type: "string", default: "#000000", description: "Price text color." },
            { name: "featureCheckBgColor", type: "string", default: "#000000", description: "Feature check background color." },
            { name: "featureCheckTextColor", type: "string", default: "#ffffff", description: "Feature check text color." },
            { name: "buttonBgColor", type: "string", default: "#000000", description: "Button background color." },
            { name: "buttonTextColor", type: "string", default: "#ffffff", description: "Button text color." },
            { name: "buttonHoverBgColor", type: "string", default: "#ffffff", description: "Button hover background color." },
            { name: "buttonHoverTextColor", type: "string", default: "#000000", description: "Button hover text color." },
            { name: "buttonHoverBorderColor", type: "string", default: "#000000", description: "Button hover border color." },
            { name: "shadowColor", type: "string", default: "#000000", description: "Shadow color." },
            { name: "buttonText", type: "string", default: "Get It Now", description: "Button text." },
        ],
        whenToUse: "Perfect for high-energy brands, street-wear e-commerce, and experimental Next.js portfolios. Use this React component for a bold, neo-brutalist pricing section with chunky shadows, high-saturation colors, and raw architectural hierarchy.",
        bestPractices: "Follow React best practices by pairing this with thick, monospaced typography and saturated primary colors. Maintain scalable component architecture by using it for high-impact section headers. Optimize for performance by using CSS-based box-shadows.",
        whyMatters: "Neo-brutalist design is a powerful visual statement of raw power and structural honesty. This production-ready UI component helpsคุณ build an interface that feels solid and unyielding, adding a unique architectural signature to your project.",
        faqs: [
            { question: "Can I adjust the shadow depth?", answer: "The component uses hard-coded shadow offsets to maintain the signature brutalist look, but these can be easily adjusted in the Tailwind classes." },
            { question: "Is the color palette customizable?", answer: "Yes, the `cardBgColors` prop allows you to pass an array of unique colors for each tier for maximum visual pop." },
            { question: "Are the checkmarks custom?", answer: "The component uses stylized Lucide icons wrapped in heavy-bordered circles to match the chunky aesthetic." }
        ],
    },
    {
        id: "pricing-dark-premium",
        name: "Dark Executive",
        description: "Premium dark executive pricing section with luxury aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "dark", "executive", "premium"],
        previewUrl: "/ContentBlocks/Pricing/PricingDarkPremium",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingDarkPremium.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingDarkPremium.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingDarkPremium/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "badgeText", type: "string", default: "The Gold Standard", description: "Badge text displayed above title." },
            { name: "badgeColor", type: "string", default: "#D4AF37", description: "Badge color." },
            { name: "title", type: "string", default: "Membership", description: "Section title text." },
            { name: "plans", type: "Array<{name: string, price: number, description?: string}>", default: "[]", description: "Array of pricing plans with name, price, and optional description." },
            { name: "backgroundColor", type: "string", default: "#050505", description: "Background color (hex, rgb, or hsl)." },
            { name: "containerBgColor", type: "string", default: "rgba(23, 23, 23, 0.5)", description: "Container background color." },
            { name: "containerBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Container border color." },
            { name: "cardBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Card border color." },
            { name: "planNameColor", type: "string", default: "rgba(163, 163, 163, 1)", description: "Plan name text color." },
            { name: "priceColor", type: "string", default: "#D4AF37", description: "Price text color." },
            { name: "descriptionColor", type: "string", default: "rgba(115, 115, 115, 1)", description: "Description text color." },
            { name: "buttonTextColor", type: "string", default: "#D4AF37", description: "Button text color." },
            { name: "buttonBorderColor", type: "string", default: "rgba(212, 175, 55, 0.3)", description: "Button border color." },
            { name: "buttonHoverBgColor", type: "string", default: "#D4AF37", description: "Button hover background color." },
            { name: "buttonHoverTextColor", type: "string", default: "#ffffff", description: "Button hover text color." },
            { name: "accentLineColor", type: "string", default: "#D4AF37", description: "Accent line color." },
            { name: "buttonText", type: "string", default: "Join Now", description: "Button text." },
        ],
        whenToUse: "Ideal for enterprise service providers, high-end consulting firms, and Next.js applications that want a luxury 'Pro' aesthetic. Use this React component for a premium dark-mode pricing section with gold accents and minimalist information hierarchy.",
        bestPractices: "Maintain consistent spacing within your design system by using it on pure black or deep navy backgrounds. Follow React best practices by using light, airy typography. Optimize for performance by using efficient container background colors.",
        whyMatters: "Luxury aesthetics communicate exclusivity and trust. This production-ready component provides a refined version of this aesthetic, adding a layer of architectural depth and perceived value to your pricing tiers.",
        faqs: [
            { question: "What makes it 'luxury'?", answer: "It uses a meticulous combination of deep blacks, golden accent colors (`#D4AF37`), and ultra-fine borders to create a high-end feel." },
            { question: "Can I change the gold color?", answer: "Yes, the `badgeColor`, `priceColor`, and `accentLineColor` props allow you to swap gold for silver, platinum, or any brand-specific metallic." },
            { question: "Does it support long descriptions?", answer: "The layout is optimized for short, impactful taglines to maintain its minimalist and exclusive aesthetic." }
        ],
    },
    {
        id: "pricing-soft-minimal",
        name: "Soft Cloud",
        description: "Soft minimal cloud pricing cards with gentle aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "soft", "cloud", "minimal"],
        previewUrl: "/ContentBlocks/Pricing/PricingSoftMinimal",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingSoftMinimal.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingSoftMinimal.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingSoftMinimal/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Simple plans for everyone.", description: "Section title text." },
            { name: "plans", type: "Array<{name: string, price: number, description?: string, badge?: string, iconColor?: string, iconBgColor?: string, buttonBgColor?: string, buttonTextColor?: string, buttonHoverBgColor?: string}>", default: "[]", description: "Array of pricing plans with name, price, description, badge, and optional styling props." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "backgroundColor", type: "string", default: "#F0F4F8", description: "Background color (hex, rgb, or hsl)." },
            { name: "titleColor", type: "string", default: "#1e293b", description: "Title text color." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,0.05)", description: "Card shadow color." },
            { name: "cardBorderColor", type: "string", default: "#ffffff", description: "Card border color." },
            { name: "planNameColor", type: "string", default: "#0f172a", description: "Plan name text color." },
            { name: "planDescColor", type: "string", default: "#94a3b8", description: "Plan description text color." },
            { name: "priceColor", type: "string", default: "#0f172a", description: "Price text color." },
            { name: "priceSubtextColor", type: "string", default: "#94a3b8", description: "Price subtext color." },
            { name: "featureTextColor", type: "string", default: "#0f172a", description: "Feature text color." },
            { name: "featureCheckBgColor", type: "string", default: "#f1f5f9", description: "Feature check background color." },
            { name: "featureCheckColor", type: "string", default: "#0f172a", description: "Feature check icon color." },
            { name: "badgeBgColor", type: "string", default: "#c7d2fe", description: "Badge background color." },
            { name: "badgeTextColor", type: "string", default: "#6366f1", description: "Badge text color." },
            { name: "defaultButtonBgColor", type: "string", default: "#f1f5f9", description: "Default button background color." },
            { name: "defaultButtonTextColor", type: "string", default: "#0f172a", description: "Default button text color." },
            { name: "defaultButtonHoverBgColor", type: "string", default: "#e2e8f0", description: "Default button hover background color." },
            { name: "buttonText", type: "string", default: "Get Started", description: "Button text." },
        ],
        whenToUse: "Excellent for modern mobile apps, personal portfolios, and Next.js startups that want a friendly, lightweight aesthetic. Use this React component for a soft minimal pricing section with gentle shadows and rounded corners.",
        bestPractices: "Maintain consistent spacing within your design system by using it on light, neutral backgrounds. Follow React best practices by pairing it with clear, descriptive icons. Optimize for performance by using standard CSS shadows instead of heavy filters.",
        whyMatters: "Soft minimalism improves usability by reducing visual stress and creating a welcoming atmosphere. This production-ready component helpsคุณ build an interface that feels accessible and professional, improving user conversion speeds.",
        faqs: [
            { question: "Is it friendly for SaaS?", answer: "Absolutely, its clean layout and clear hierarchy make it one of the most versatile styles for modern subscription-based products." },
            { question: "Can I adjust the card roundness?", answer: "The cards use a medium roundness (`rounded-3xl`), which can be easily customized in the internal Tailwind classes." },
            { question: "How many tiers does it support?", answer: "The grid is optimized for 3 tiers, but automatically re-stacks for 1, 2, or 4+ tiers on mobile and desktop." }
        ],
    },
    {
        id: "pricing-editorial",
        name: "Editorial Mono",
        description: "Editorial monochrome pricing section with typography focus.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "editorial", "mono", "typography"],
        previewUrl: "/ContentBlocks/Pricing/PricingEditorial",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingEditorial.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingEditorial.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingEditorial/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "PRI", description: "Section title text (first part)." },
            { name: "title2", type: "string", default: "CING", description: "Section title text (second part)." },
            { name: "subtitle", type: "string", default: "Select a tier that aligns with your ambition. Transparency is our only currency.", description: "Section subtitle text." },
            { name: "plans", type: "Array<{name: string, price: number, number?: string}>", default: "[]", description: "Array of pricing plans with name, price, and optional number." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#000000", description: "Border color." },
            { name: "sidebarBgColor", type: "string", default: "#ffffff", description: "Sidebar background color." },
            { name: "sidebarTextColor", type: "string", default: "#000000", description: "Sidebar text color." },
            { name: "planNameColor", type: "string", default: "#000000", description: "Plan name text color." },
            { name: "planNumberColor", type: "string", default: "#000000", description: "Plan number text color." },
            { name: "priceColor", type: "string", default: "#000000", description: "Price text color." },
            { name: "featureTextColor", type: "string", default: "#000000", description: "Feature text color." },
            { name: "featureIncludedColor", type: "string", default: "rgba(0,0,0,0.3)", description: "Feature included indicator color." },
            { name: "buttonBorderColor", type: "string", default: "#000000", description: "Button border color." },
            { name: "buttonTextColor", type: "string", default: "#000000", description: "Button text color." },
            { name: "buttonHoverBgColor", type: "string", default: "#000000", description: "Button hover background color." },
            { name: "buttonHoverTextColor", type: "string", default: "#ffffff", description: "Button hover text color." },
            { name: "footerText", type: "string", default: "(c) 2024 Design Systems Inc. All Rights Reserved.", description: "Footer text." },
            { name: "footerTextColor", type: "string", default: "#000000", description: "Footer text color." },
            { name: "buttonText", type: "string", default: "Subscribe", description: "Button text." },
        ],
        whenToUse: "Ideal for artistic agencies, architecture firms, and Next.js sites that want a sophisticated, monochrome aesthetic. Use this React component for an editorial-style pricing section with large typography and clean grid lines.",
        bestPractices: "Follow React best practices by pairing this with bold, high-contrast typography. Maintain consistent spacing within your design system by using it on pure white or light gray backgrounds. Optimize for performance by using efficient grid layouts.",
        whyMatters: "Editorial layouts add a sense of authority and timelessness to digital content. This production-ready UI component helpsคุณ build an interface that feels like a high-end publication, improving the perceived exclusivity of your product.",
        faqs: [
            { question: "Why is it monochrome?", answer: "The mono aesthetic focuses the user's attention on the typography and the raw information, creating a sophisticated and professional look." },
            { question: "Can I add color accents?", answer: "Yes, while designed for mono, you can easily inject brand colors via the `buttonHoverBgColor` and other styling props." },
            { question: "Is the sidebar customizable?", answer: "The `sidebarBgColor` and `sidebarTextColor` props allow you to customize the left-hand branding area for different themes." }
        ],
    },
    {
        id: "pricing-luxury",
        name: "Luxury Ethereal",
        description: "Luxury ethereal pricing section with gold accents.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "luxury", "ethereal", "gold"],
        previewUrl: "/ContentBlocks/Pricing/PricingLuxury",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingLuxury.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingLuxury.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingLuxury/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "ELEVATION", description: "Section title text." },
            { name: "plans", type: "Array<{name: string, price: number | string}>", default: "[]", description: "Array of pricing plans with name and price (can be number or string)." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "blob1FromColor", type: "string", default: "#312e81", description: "First blob gradient start color." },
            { name: "blob1ViaColor", type: "string", default: "#581c87", description: "First blob gradient middle color." },
            { name: "blob2FromColor", type: "string", default: "#9f1239", description: "Second blob gradient start color." },
            { name: "blob2ViaColor", type: "string", default: "#831843", description: "Second blob gradient middle color." },
            { name: "titleColor", type: "string", default: "rgba(255,255,255,0.8)", description: "Title text color." },
            { name: "cardBgColor", type: "string", default: "rgba(255,255,255,0.05)", description: "Card background color." },
            { name: "activeCardBgColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Active card background color." },
            { name: "cardBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Card border color." },
            { name: "planNameColor", type: "string", default: "#ffffff", description: "Plan name text color." },
            { name: "dividerColor", type: "string", default: "#ffffff", description: "Divider color." },
            { name: "priceColor", type: "string", default: "#ffffff", description: "Price text color." },
            { name: "featureTextColor", type: "string", default: "rgba(255,255,255,0.6)", description: "Feature text color." },
            { name: "featureIconColor", type: "string", default: "#ffffff", description: "Feature icon color." },
            { name: "buttonBorderColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Button border color." },
            { name: "buttonTextColor", type: "string", default: "#ffffff", description: "Button text color." },
            { name: "buttonHoverBgColor", type: "string", default: "#ffffff", description: "Button hover background color." },
            { name: "buttonHoverTextColor", type: "string", default: "#000000", description: "Button hover text color." },
            { name: "activeCardShadowColor", type: "string", default: "rgba(147, 51, 234, 0.2)", description: "Active card shadow color." },
            { name: "buttonText", type: "string", default: "SELECT", description: "Button text." },
        ],
        whenToUse: "Perfect for high-fashion, premium lifestyle brands, and Next.js applications that want an ethereal, luxurious feel. Use this React component for a luxury pricing section with gold accents, soft background glows, and elegant dividers.",
        bestPractices: "Maintain consistent spacing within your design system by using it on dark, atmospheric backgrounds. Follow React best practices by pairing it with high-quality imagery. Optimize for performance by using hardware-accelerated transforms for the background blobs.",
        whyMatters: "Luxury design is about the balance of space and detail. This production-ready component helpsคุณ build an interface that feels expansive and premium, reinforcing a high-ticket brand identity.",
        faqs: [
            { question: "How is the glow created?", answer: "It uses two large radial-gradient 'blobs' that animate slowly in the background, creating a soft, shifting light effect." },
            { question: "Can I adjust the card opacity?", answer: "The `cardBgColor` uses an alpha channel (`rgba`), allowing you to control exactly how much of the background glow shines through the cards." },
            { question: "Is it mobile responsive?", answer: "Yes, the cards stack vertically on mobile while the background blobs scale to maintain the ethereal atmosphere." }
        ],
    },
    {
        id: "pricing-sketch",
        name: "The Blueprint",
        description: "Hand-drawn blueprint pricing section with sketch aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "blueprint", "sketch", "hand-drawn"],
        previewUrl: "/ContentBlocks/Pricing/PricingSketch",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingSketch.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingSketch.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingSketch/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Rough Estimates", description: "Section title text." },
            { name: "plans", type: "Array<{name: string, price: number}>", default: "[]", description: "Array of pricing plans with name and price." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "backgroundColor", type: "string", default: "#FFFDF5", description: "Background color (hex, rgb, or hsl)." },
            { name: "patternColor", type: "string", default: "#000000", description: "Grid pattern color." },
            { name: "underlineColor", type: "string", default: "#facc15", description: "Title underline color." },
            { name: "shadowBgColor", type: "string", default: "#e2e8f0", description: "Shadow background color." },
            { name: "shadowBorderColor", type: "string", default: "#1e293b", description: "Shadow border color." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "cardBorderColor", type: "string", default: "#1e293b", description: "Card border color." },
            { name: "tapeBgColor", type: "string", default: "rgba(254, 240, 138, 0.8)", description: "Tape background color." },
            { name: "planNameColor", type: "string", default: "#0f172a", description: "Plan name text color." },
            { name: "priceColor", type: "string", default: "#0f172a", description: "Price text color." },
            { name: "priceUnderlineColor", type: "string", default: "#f87171", description: "Price underline color." },
            { name: "featureTextColor", type: "string", default: "#0f172a", description: "Feature text color." },
            { name: "featureBulletColor", type: "string", default: "#94a3b8", description: "Feature bullet color." },
            { name: "buttonBorderColor", type: "string", default: "#1e293b", description: "Button border color." },
            { name: "buttonTextColor", type: "string", default: "#0f172a", description: "Button text color." },
            { name: "buttonHoverBgColor", type: "string", default: "#1e293b", description: "Button hover background color." },
            { name: "buttonHoverTextColor", type: "string", default: "#ffffff", description: "Button hover text color." },
            { name: "buttonText", type: "string", default: "Circle It", description: "Button text." },
        ],
        whenToUse: "Excellent for creative labs, educational platforms, and Next.js portfolios that want a playful, hand-crafted aesthetic. Use this React component for a 'blueprint' pricing section with sketch-style borders and rough, hand-drawn effects.",
        bestPractices: "Follow React best practices by pairing this with playful, informal typography. Maintain scalable component architecture by using it for narrative sections. Optimize for performance by using efficient SVG patterns for the grid background.",
        whyMatters: "Sketch aesthetics break the digital barrier by adding a human, tactile touch to the interface. This production-ready UI component helpsคุณ build an interface that feels approachable and experimental, improving user engagement through visual novelty.",
        faqs: [
            { question: "Is the grid a real image?", answer: "No, the grid is a lightweight CSS/SVG pattern, ensuring it stays sharp at any resolution without adding to page weight." },
            { question: "How are the rough borders made?", answer: "The component uses custom border-radius and shadow combinations to simulate the uneven characteristic of a hand-drawn line." },
            { question: "Can I change the highlight color?", answer: "Yes, the `underlineColor` and `priceUnderlineColor` props allow you to customize the 'marker' highlights used throughout the section." }
        ],
    },
    {
        id: "pricing-terminal",
        name: "Retro Terminal",
        description: "Retro terminal pricing section with command-line aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "terminal", "retro", "command-line"],
        previewUrl: "/ContentBlocks/Pricing/PricingTerminal",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingTerminal.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingTerminal.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingTerminal/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "plans", type: "Array<{name: string, price: number}>", default: "[]", description: "Array of pricing plans with name and price." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "backgroundColor", type: "string", default: "#1a1b26", description: "Background color (hex, rgb, or hsl)." },
            { name: "terminalBgColor", type: "string", default: "#24283b", description: "Terminal background color." },
            { name: "terminalBorderColor", type: "string", default: "#414868", description: "Terminal border color." },
            { name: "terminalShadowColor", type: "string", default: "rgba(0,0,0,0.5)", description: "Terminal shadow color." },
            { name: "headerBgColor", type: "string", default: "#1f2335", description: "Header background color." },
            { name: "headerBorderColor", type: "string", default: "#414868", description: "Header border color." },
            { name: "dot1Color", type: "string", default: "#ff5f56", description: "First dot color (red)." },
            { name: "dot2Color", type: "string", default: "#ffbd2e", description: "Second dot color (yellow)." },
            { name: "dot3Color", type: "string", default: "#27c93f", description: "Third dot color (green)." },
            { name: "promptTextColor", type: "string", default: "#9aa5ce", description: "Prompt text color." },
            { name: "commandTextColor", type: "string", default: "#7aa2f7", description: "Command text color." },
            { name: "successTextColor", type: "string", default: "#73daca", description: "Success text color." },
            { name: "infoTextColor", type: "string", default: "#a9b1d6", description: "Info text color." },
            { name: "planPrefixColor", type: "string", default: "#7aa2f7", description: "Plan prefix color." },
            { name: "planNameColor", type: "string", default: "#ffffff", description: "Plan name text color." },
            { name: "planPriceColor", type: "string", default: "#9aa5ce", description: "Plan price text color." },
            { name: "planHoverBorderColor", type: "string", default: "#7aa2f7", description: "Plan hover border color." },
            { name: "detailsBgColor", type: "string", default: "#1f2335", description: "Details background color." },
            { name: "detailsBorderColor", type: "string", default: "#414868", description: "Details border color." },
            { name: "detailsTitleColor", type: "string", default: "#7aa2f7", description: "Details title text color." },
            { name: "featureCheckColor", type: "string", default: "#73daca", description: "Feature check color." },
            { name: "featureTextColor", type: "string", default: "#a9b1d6", description: "Feature text color." },
            { name: "hintBgColor", type: "string", default: "#1f2335", description: "Hint background color." },
            { name: "hintTextColor", type: "string", default: "#9aa5ce", description: "Hint text color." },
            { name: "hintKeyBgColor", type: "string", default: "#414868", description: "Hint key background color." },
            { name: "hintKeyTextColor", type: "string", default: "#ffffff", description: "Hint key text color." },
            { name: "cursorColor", type: "string", default: "#7aa2f7", description: "Cursor color." },
            { name: "promptText", type: "string", default: "$", description: "Prompt text." },
            { name: "commandText", type: "string", default: "cat pricing.txt", description: "Command text." },
            { name: "successText", type: "string", default: "✓ Loaded", description: "Success text." },
            { name: "infoText", type: "string", default: "→ Select a tier", description: "Info text." },
            { name: "detailsTitle", type: "string", default: "Features:", description: "Details title text." },
            { name: "hintText", type: "string", default: "Press", description: "Hint text." },
            { name: "hintKey", type: "string", default: "ENTER", description: "Hint key text." },
        ],
        whenToUse: "Excellent for developer-centric startups, security-themed apps, and Next.js projects that want a retro 'command-line' aesthetic. Use this React component for a terminal-style pricing section with keyboard-driven navigation and ASCII-like visuals.",
        bestPractices: "Maintain consistent spacing within your design system by using it as a secondary interactive layer. Follow React best practices by using monospaced typography and high-contrast colors (e.g., terminal green). Optimize for performance by managed the cursor blink animations.",
        whyMatters: "Terminal UIs create a sense of technical depth and nostalgia. This production-ready component helpsคุณ build an interface that feels advanced and developer-friendly, reinforcing a technical brand identity.",
        faqs: [
            { question: "Are there keyboard shortcuts?", answer: "Yes, users can navigate tiers using arrow keys and select plans with the ENTER key, simulating a real CLI experience." },
            { question: "Can I customize the colors?", answer: "The component supports full customization of prompt, command, cursor, and success colors via its extensive props list." },
            { question: "Is it mobile responsive?", answer: "On mobile, the keyboard-specific hints are hidden, and the interface becomes fully touch-interactable like a standard pricing list." }
        ],
    },
    {
        id: "pricing-slider",
        name: "Dynamic Slider",
        description: "Dynamic slider pricing section with smooth transitions.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "slider", "dynamic", "transitions"],
        previewUrl: "/ContentBlocks/Pricing/PricingSlider",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingSlider.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingSlider.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingSlider/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Scale as you grow", description: "Section title text." },
            { name: "subtitle", type: "string", default: "Pay only for what you need. No hidden fees.", description: "Section subtitle text." },
            { name: "tiers", type: "Array<{title: string, desc: string, threshold: number}>", default: "[]", description: "Array of pricing tiers with title, description, and threshold." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "minUsers", type: "number", default: "1", description: "Minimum number of users." },
            { name: "maxUsers", type: "number", default: "50", description: "Maximum number of users." },
            { name: "defaultUsers", type: "number", default: "5", description: "Default number of users." },
            { name: "pricePerUser", type: "number", default: "12", description: "Price per user." },
            { name: "backgroundColor", type: "string", default: "#f8fafc", description: "Background color (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,0.1)", description: "Card shadow color." },
            { name: "titleColor", type: "string", default: "#0f172a", description: "Title text color." },
            { name: "subtitleColor", type: "string", default: "#64748b", description: "Subtitle text color." },
            { name: "labelColor", type: "string", default: "#94a3b8", description: "Label text color." },
            { name: "userCountColor", type: "string", default: "#2563eb", description: "User count text color." },
            { name: "totalColor", type: "string", default: "#0f172a", description: "Total price text color." },
            { name: "sliderBgColor", type: "string", default: "#f1f5f9", description: "Slider background color." },
            { name: "sliderFillColor", type: "string", default: "#2563eb", description: "Slider fill color." },
            { name: "sliderHandleBgColor", type: "string", default: "#ffffff", description: "Slider handle background color." },
            { name: "sliderHandleBorderColor", type: "string", default: "#2563eb", description: "Slider handle border color." },
            { name: "sliderIconColor", type: "string", default: "#2563eb", description: "Slider icon color." },
            { name: "tierActiveBorderColor", type: "string", default: "#2563eb", description: "Active tier border color." },
            { name: "tierActiveBgColor", type: "string", default: "#eff6ff", description: "Active tier background color." },
            { name: "tierInactiveBorderColor", type: "string", default: "#f1f5f9", description: "Inactive tier border color." },
            { name: "tierTitleColor", type: "string", default: "#0f172a", description: "Tier title text color." },
            { name: "tierDescColor", type: "string", default: "#64748b", description: "Tier description text color." },
            { name: "tierFeatureTextColor", type: "string", default: "#0f172a", description: "Tier feature text color." },
            { name: "tierFeatureCheckColor", type: "string", default: "#2563eb", description: "Tier feature check color." },
            { name: "buttonBgColor", type: "string", default: "#2563eb", description: "Button background color." },
            { name: "buttonTextColor", type: "string", default: "#ffffff", description: "Button text color." },
            { name: "buttonText", type: "string", default: "Get Started", description: "Button text." },
        ],
        whenToUse: "Perfect for scaling businesses, usage-based products, and Next.js applications that want a tactile, dynamic 'cost calculator' feel. Use this React component for a slider-driven pricing section with real-time price updates and smooth tier transitions.",
        bestPractices: "Follow React best practices by using clear, high-contrast labels for the slider thresholds. Maintain scalable component architecture by keeping the math simple for the user. Optimize for performance by using efficient state management for the slider values.",
        whyMatters: "Interactive sliders improve user transparency and agency. This production-ready component helpsคุณ build an interface that feels personalized and fair, allowing users to find their perfect 'sweet spot' for pricing.",
        faqs: [
            { question: "How does the calculation work?", answer: "The total price is calculated in real-time as the product of the `pricePerUser` and the current user count from the slider." },
            { question: "Are the tiers automatic?", answer: "Yes, as the slider passes certain thresholds defined in the `tiers` prop, the corresponding category card becomes active." },
            { question: "Can I adjust the user range?", answer: "Absolutely, you can set the `minUsers` and `maxUsers` props to fit anything from a small boutique to a massive enterprise scale." }
        ],
    },
    {
        id: "pricing-swiss",
        name: "Swiss Grid",
        description: "Swiss grid pricing section with precision typography.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "swiss", "grid", "precision"],
        previewUrl: "/ContentBlocks/Pricing/PricingSwiss",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingSwiss.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingSwiss.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingSwiss/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "PRI", description: "Section title text (first part)." },
            { name: "title2", type: "string", default: "CING", description: "Section title text (second part)." },
            { name: "badgeText", type: "string", default: "International\nStyle\nSystem", description: "Badge text (can include newlines)." },
            { name: "tiers", type: "Array<{letter: string, name: string, price: number}>", default: "[]", description: "Array of pricing tiers with letter, name, and price." },
            { name: "backgroundColor", type: "string", default: "#F2F2F2", description: "Background color (hex, rgb, or hsl)." },
            { name: "containerBgColor", type: "string", default: "#ffffff", description: "Container background color." },
            { name: "containerBorderColor", type: "string", default: "#111111", description: "Container border color." },
            { name: "containerShadowColor", type: "string", default: "#111111", description: "Container shadow color." },
            { name: "titleColor", type: "string", default: "#111111", description: "Title text color." },
            { name: "badgeBgColor", type: "string", default: "#FF4400", description: "Badge background color." },
            { name: "badgeTextColor", type: "string", default: "#ffffff", description: "Badge text color." },
            { name: "tierBgColor", type: "string", default: "#ffffff", description: "Tier background color." },
            { name: "tierHoverBgColor", type: "string", default: "#FFD700", description: "Tier hover background color." },
            { name: "tierBorderColor", type: "string", default: "#111111", description: "Tier border color." },
            { name: "tierLetterColor", type: "string", default: "#111111", description: "Tier letter text color." },
            { name: "tierNameColor", type: "string", default: "#111111", description: "Tier name text color." },
            { name: "tierPriceColor", type: "string", default: "#111111", description: "Tier price text color." },
            { name: "tierPriceLabelColor", type: "string", default: "#111111", description: "Tier price label text color." },
            { name: "buttonBgColor", type: "string", default: "#000000", description: "Button background color." },
            { name: "buttonTextColor", type: "string", default: "#ffffff", description: "Button text color." },
            { name: "buttonHoverBgColor", type: "string", default: "#ffffff", description: "Button hover background color." },
            { name: "buttonHoverTextColor", type: "string", default: "#000000", description: "Button hover text color." },
            { name: "buttonBorderColor", type: "string", default: "#000000", description: "Button border color." },
            { name: "buttonText", type: "string", default: "Select", description: "Button text." },
        ],
        whenToUse: "Ideal for editorial-heavy platforms, architecture sites, and Next.js projects that want a bold, European modernist aesthetic. Use this React component for a Swiss-style pricing grid with heavy lines, bold letter-tiering, and high typographic precision.",
        bestPractices: "Maintain consistent spacing within your design system by aligning the grid gaps with your primary layout. Follow React best practices by pairing this with clean, Sans-Serif typography (like Inter or Roboto). Optimize for performance by using efficient grid transforms.",
        whyMatters: "Swiss design is the foundation of modern visual clarity. This production-ready UI component helpsคุณ build an interface that feels authoritative and structured, making complex pricing easy to digest.",
        faqs: [
            { question: "What is the 'Letter Tiering'?", answer: "Each plan is assigned a bold alphabetical letter (A, B, C) to create a clear, architectural hierarchy inspired by classic modernist posters." },
            { question: "Can I change the highlight color?", answer: "Yes, the `badgeBgColor` and `tierHoverBgColor` props allow you to inject vibrant Swiss-style color accents like International Orange or Gold." },
            { question: "Is the border width adjustable?", answer: "The component uses a signature 2px 'precision' border to maintain its architectural feel across all screen sizes." }
        ],
    },
    {
        id: "pricing-receipt",
        name: "The Receipt",
        description: "Receipt-style pricing section with paper aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "receipt", "paper", "vintage"],
        previewUrl: "/ContentBlocks/Pricing/PricingReceipt",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingReceipt.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingReceipt.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingReceipt/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "storeName", type: "string", default: "SaaS Market", description: "Store name text." },
            { name: "storeAddress", type: "string", default: "1234 Cloud Ave, Internet City", description: "Store address text." },
            { name: "items", type: "Array<{name: string, price: number}>", default: "[]", description: "Array of pricing items with name and price." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "backgroundColor", type: "string", default: "#e0e0e0", description: "Background color (hex, rgb, or hsl)." },
            { name: "receiptBgColor", type: "string", default: "#ffffff", description: "Receipt background color." },
            { name: "receiptShadowColor", type: "string", default: "rgba(0,0,0,0.25)", description: "Receipt shadow color." },
            { name: "iconColor", type: "string", default: "#404040", description: "Icon color." },
            { name: "titleColor", type: "string", default: "#171717", description: "Title text color." },
            { name: "addressColor", type: "string", default: "#171717", description: "Address text color." },
            { name: "dividerColor", type: "string", default: "#d4d4d4", description: "Divider color." },
            { name: "itemNameColor", type: "string", default: "#171717", description: "Item name text color." },
            { name: "itemPriceColor", type: "string", default: "#171717", description: "Item price text color." },
            { name: "featureTextColor", type: "string", default: "#737373", description: "Feature text color." },
            { name: "featureBorderColor", type: "string", default: "#d4d4d4", description: "Feature border color." },
            { name: "buttonBorderColor", type: "string", default: "#000000", description: "Button border color." },
            { name: "buttonTextColor", type: "string", default: "#000000", description: "Button text color." },
            { name: "totalLabelColor", type: "string", default: "#171717", description: "Total label text color." },
            { name: "totalPriceColor", type: "string", default: "#171717", description: "Total price text color." },
            { name: "footerText", type: "string", default: "THANK YOU FOR YOUR BUSINESS", description: "Footer text." },
            { name: "footerTextColor", type: "string", default: "#171717", description: "Footer text color." },
            { name: "patternColor", type: "string", default: "#000000", description: "Pattern color." },
            { name: "buttonText", type: "string", default: "Add to Cart", description: "Button text." },
        ],
        whenToUse: "Excellent for e-commerce checkouts, vintage-style boutiques, and Next.js sites that want a 'physical' paper aesthetic. Use this React component for a pricing section that looks like a printed grocery or retail receipt.",
        bestPractices: "Maintain consistent spacing within your design system by using it on neutral, textured backgrounds. Follow React best practices by using monospaced or typewriter-style fonts. Optimize for performance by using simple CSS shadows for the paper depth.",
        whyMatters: "Receipt aesthetics provide a unique, skeuomorphic connection to real-world transactions. This production-ready UI component helpsคุณ build an interface that feels tactile and transparent, adding a layer of storytelling to the purchase process.",
        faqs: [
            { question: "Is the paper edge torn?", answer: "Yes, the component uses a decorative SVG mask to create the signature 'zig-zag' torn edge at the top and bottom of the receipt." },
            { question: "Can I change the store details?", answer: "The `storeName` and `storeAddress` props allow you to fully customize the branding at the top of the receipt." },
            { question: "Does it support long item lists?", answer: "The receipt scales vertically based on the number of items in the `items` array, maintaining its paper-strip aesthetic regardless of length." }
        ],
    },
    {
        id: "pricing-aero",
        name: "Aero Glass",
        description: "Aero glass pricing section with Windows Vista aesthetics.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "aero", "glass", "vista"],
        previewUrl: "/ContentBlocks/Pricing/PricingAero",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingAero.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingAero.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingAero/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "plans", type: "Array<{name: string, price: number, description?: string}>", default: "[]", description: "Array of pricing plans with name, price, and optional description." },
            { name: "features", type: "string[]", default: "[]", description: "Array of feature strings to display." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "backgroundImage", type: "string", default: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?q=80&w=2070&auto=format&fit=crop", description: "Background image URL." },
            { name: "cardBgColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Card background color." },
            { name: "cardBorderColor", type: "string", default: "rgba(255,255,255,0.4)", description: "Card border color." },
            { name: "cardBlurColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Card blur effect color." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Title text color." },
            { name: "descriptionColor", type: "string", default: "rgba(255,255,255,0.8)", description: "Description text color." },
            { name: "priceColor", type: "string", default: "#ffffff", description: "Price text color." },
            { name: "featureTextColor", type: "string", default: "rgba(255,255,255,0.9)", description: "Feature text color." },
            { name: "buttonBgColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Button background color." },
            { name: "buttonTextColor", type: "string", default: "#ffffff", description: "Button text color." },
            { name: "buttonBorderColor", type: "string", default: "rgba(255,255,255,0.4)", description: "Button border color." },
            { name: "buttonText", type: "string", default: "Purchase", description: "Button text." },
        ],
        whenToUse: "Perfect for nostalgic tech brands, early-2000s revival sites, and Next.js projects that want the signature Windows Vista 'Aero' look. Use this React component for a glass pricing section with high-gloss reflections and soft translucency.",
        bestPractices: "Follow React best practices by pairing this with vibrant, abstract background images. Maintain scalable component architecture by using it for high-impact showcase areas. Optimize for performance by managed the blur and reflection filters.",
        whyMatters: "Aero Glass is a landmark of digital design history that evokes a specific era of optimism and depth. This production-ready component helpsคุณ build an interface that feels both nostalgic and technologically sophisticated.",
        faqs: [
            { question: "How are the reflections made?", answer: "The component uses multiple stacked linear-gradients and a 'specular' highlight overlay to simulate the glossy surface of 2007-era glass." },
            { question: "Can I use my own background?", answer: "Yes, the `backgroundImage` prop accepts any URL, which is then blurred and darkened to ensure the glass tiers remain the focal point." },
            { question: "Is it mobile responsive?", answer: "The high-gloss effects are hardware-accelerated to ensure 60fps glass transitions on both desktop and high-end mobile devices." }
        ],
    },
    {
        id: "pricing-magazine",
        name: "Magazine",
        description: "Magazine-style pricing section with editorial layout.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["pricing", "magazine", "editorial", "layout"],
        previewUrl: "/ContentBlocks/Pricing/PricingMagazine",
        code: {
            tsx: getCode("src/components/ContentBlocks/Pricing/tsx/PricingMagazine.tsx"),
            jsx: getCode("src/components/ContentBlocks/Pricing/jsx/PricingMagazine.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/ContentBlocks/Pricing/PricingMagazine/page.tsx")
        },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "issueText", type: "string", default: "Issue 024 • The Collection", description: "Issue text displayed above title." },
            { name: "title", type: "string", default: "Vogue", description: "Section title text." },
            { name: "subtitle", type: "string", default: "Subscription Tiers", description: "Section subtitle text." },
            { name: "plans", type: "Array<{name: string, price: number, description?: string, image?: string}>", default: "[]", description: "Array of pricing plans with name, price, description, and optional image URL." },
            { name: "backgroundColor", type: "string", default: "#f5f5f0", description: "Background color (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "cardShadowColor", type: "string", default: "rgba(0,0,0,0.1)", description: "Card shadow color." },
            { name: "badgeBgColor", type: "string", default: "#000000", description: "Badge background color." },
            { name: "badgeTextColor", type: "string", default: "#ffffff", description: "Badge text color." },
            { name: "titleColor", type: "string", default: "#1a1a1a", description: "Title text color." },
            { name: "dividerColor", type: "string", default: "#000000", description: "Divider color." },
            { name: "subtitleColor", type: "string", default: "#6b7280", description: "Subtitle text color." },
            { name: "planNameColor", type: "string", default: "#1a1a1a", description: "Plan name text color." },
            { name: "planDescColor", type: "string", default: "#6b7280", description: "Plan description text color." },
            { name: "priceColor", type: "string", default: "#1a1a1a", description: "Price text color." },
            { name: "buttonTextColor", type: "string", default: "#000000", description: "Button text color." },
            { name: "buttonHoverTextColor", type: "string", default: "#6b7280", description: "Button hover text color." },
            { name: "buttonBorderColor", type: "string", default: "#000000", description: "Button border color." },
            { name: "buttonHoverBorderColor", type: "string", default: "#6b7280", description: "Button hover border color." },
            { name: "footerText", type: "string", default: "Printed in Italy • 100% Recycled Paper", description: "Footer text." },
            { name: "footerTextColor", type: "string", default: "#9ca3af", description: "Footer text color." },
            { name: "buttonText", type: "string", default: "Subscribe", description: "Button text." },
        ],
        whenToUse: "Ideal for lifestyle blogs, high-end publications, and Next.js sites that want a sophisticated, editorial layout. Use this React component for a magazine-style pricing section with high-quality imagery and classic serif typography.",
        bestPractices: "Follow React best practices by pairing this with high-resolution portraits or product photography. Maintain consistent spacing within your design system by using it on off-white or paper-textured backgrounds. Optimize for performance by lazy-loading the plan images.",
        whyMatters: "Magazine layouts add a sense of luxury and curated taste to digital subscriptions. This production-ready UI component helpsคุณ build an interface that feels like a high-end coffee table book, improving the perceived quality of your content.",
        faqs: [
            { question: "Can I use vertical images?", answer: "The component is optimized for high-impact vertical or square imagery, typically used to represent different magazine issues or membership levels." },
            { question: "Is the typography Serif?", answer: "Yes, it uses a classic Serif font for the title and plans to reinforce the 'printed publication' aesthetic." },
            { question: "Does it support long summaries?", answer: "The `planDescColor` and layout are designed for brief, evocative summaries that entice the user without overcrowding the editorial space." }
        ],
    },
];

