import { Component } from "../types";

export const statsSectionComponentsMetadata: Component[] = [
    {
        id: "stats-luxury",
        name: "Luxury Gold",
        description: "Luxury gold stats section with serif typography and gradients.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["stats", "luxury", "gold", "serif"],
        previewUrl: "/ContentBlocks/StatsSections/StatsLuxury",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "badgeText", type: "string", default: "Performance Metrics", description: "Badge text displayed above title." },
            { name: "title", type: "string", default: "Our Legacy in Numbers", description: "Section title text." },
            { name: "stats", type: "Array<{value: number, suffix?: string, label: string}>", default: "[]", description: "Array of stat items." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color." },
        ],
    },
    {
        id: "stats-brutal",
        name: "Neo-Brutalism",
        description: "Premium neo-brutalist stats with chunky borders, hard shadows, and counter animations.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["stats", "brutalist", "bold", "chunky"],
        previewUrl: "/ContentBlocks/StatsSections/StatsBrutal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "stats", type: "Array<{value, label, color}>", default: "4 Uilora stats", description: "Stat items with value, label, and accent bar color." },
            { name: "title", type: "string", default: "Hard Numbers.", description: "Section heading." },
            { name: "subtitle", type: "string", default: "The metrics that matter.", description: "Section subtitle." },
            { name: "accentColor", type: "string", default: "#FF3B30", description: "Accent color for badge and hero elements." },
        ],
    },
    {
        id: "stats-circular",
        name: "Luxury Rings",
        description: "Luxury gold circular progress rings with animated fill and counter.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["stats", "circular", "rings", "luxury", "gold"],
        previewUrl: "/ContentBlocks/StatsSections/StatsCircular",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "stats", type: "Array<{value, label, percentage}>", default: "4 Uilora metrics", description: "Stats with value, label, and ring fill percentage." },
            { name: "title", type: "string", default: "Our Impact", description: "Section heading." },
            { name: "subtitle", type: "string", default: "UILORA METRICS", description: "Tag above heading." },
            { name: "accentColor", type: "string", default: "#C9A84C", description: "Gold accent color for rings and highlights." },
        ],
    },
    {
        id: "stats-editorial",
        name: "Editorial Split",
        description: "Editorial split stats section with typography focus and image.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["stats", "editorial", "split", "typography"],
        previewUrl: "/ContentBlocks/StatsSections/StatsEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "image", type: "string", default: "Unsplash architecture", description: "Background image URL." },
            { name: "title", type: "string", default: "Building the future,", description: "Title text." },
            { name: "titleItalic", type: "string", default: "one block at a time.", description: "Italic title text." },
            { name: "stats", type: "Array<{value: number, label: string}>", default: "[]", description: "Array of stat items." },
        ],
    },
    {
        id: "stats-clay",
        name: "Clay Premium",
        description: "Premium neumorphic clay stats with icon containers and hover depth.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["stats", "clay", "neumorphic", "premium"],
        previewUrl: "/ContentBlocks/StatsSections/StatsClay",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "stats", type: "Array<{value, label, icon}>", default: "4 Uilora stats", description: "Stat items with value, label, and lucide icon." },
            { name: "title", type: "string", default: "Uilora in Numbers", description: "Section heading." },
            { name: "subtitle", type: "string", default: "UILORA STATS", description: "Tag above heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Accent color for numbers and icon glow." },
        ],
    },
    {
        id: "stats-minimal",
        name: "Minimal Scale",
        description: "Premium minimal stats with massive typography and scroll-triggered counter animation.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["stats", "minimal", "scale", "typography", "editorial"],
        previewUrl: "/ContentBlocks/StatsSections/StatsMinimal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "stats", type: "Array<{value, label, suffix?}>", default: "4 Uilora stats", description: "Stat items with value, label, and optional suffix." },
            { name: "title", type: "string", default: "", description: "Optional section heading (hidden by default)." },
            { name: "subtitle", type: "string", default: "", description: "Optional subtitle." },
            { name: "accentColor", type: "string", default: "#000000", description: "Accent color for hover line and active states." },
        ],
    },
    {
        id: "stats-gravity",
        name: "Gravity Chaos",
        description: "Gravity chaos stats section with draggable physics bubbles.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["stats", "gravity", "chaos", "dynamic", "draggable"],
        previewUrl: "/ContentBlocks/StatsSections/StatsGravity",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "stats", type: "Array<{value, label, color?, size?, x?, y?}>", default: "[]", description: "Stat items with position and styling." },
            { name: "backgroundColor", type: "string", default: "#111111", description: "Background color." },
            { name: "patternColor", type: "string", default: "#222222", description: "Grid pattern color." },
            { name: "hintText", type: "string", default: "DRAG_THE_DATA // PHYSICS_ENABLED", description: "Hint text." },
        ],
    },
    {
        id: "stats-gooey",
        name: "The Gooey",
        description: "Gooey blob stats section with liquid morphing animations.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["stats", "gooey", "blob", "liquid"],
        previewUrl: "/ContentBlocks/StatsSections/StatsGooey",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "stats", type: "Array<{value: number, label: string}>", default: "[]", description: "Array of stat items." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color." },
            { name: "blobColor", type: "string", default: "#ffffff", description: "Blob color." },
            { name: "blobSize", type: "number", default: "256", description: "Blob size in pixels." },
        ],
    },
    {
        id: "stats-matrix",
        name: "Data Rain",
        description: "Matrix data rain stats with falling characters and terminal cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["stats", "matrix", "rain", "terminal"],
        previewUrl: "/ContentBlocks/StatsSections/StatsMatrix",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "stats", type: "Array<{value: number, label: string}>", default: "[]", description: "Array of stat items." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color." },
            { name: "canvasTextColor", type: "string", default: "#0F0", description: "Matrix rain text color." },
            { name: "cardBorderColor", type: "string", default: "rgba(0,255,0,0.5)", description: "Card border color." },
        ],
    },
];
