import { Component } from "../types";

export const timelineComponentsMetadata: Component[] = [
    {
        id: "timeline-luminous",
        name: "Luminous Path",
        description: "Glowing center beam timeline with scroll progress.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["timeline", "luminous", "glow", "scroll"],
        previewUrl: "/ContentBlocks/Timeline/TimelineLuminous",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{year: string, title: string, desc: string, category: string}>", default: "[]", description: "Array of timeline items with year, title, description, and category." },
            { name: "backgroundColor", type: "string", default: "#020617", description: "Background color (hex, rgb, or hsl)." },
            { name: "beamColor", type: "string", default: "#3b82f6", description: "Center beam color." },
            { name: "nodeColor", type: "string", default: "#3b82f6", description: "Timeline node color." },
            { name: "cardBgColor", type: "string", default: "rgba(15, 23, 42, 0.5)", description: "Card background color." },
            { name: "cardBorderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Card border color." },
            { name: "yearColor", type: "string", default: "#60a5fa", description: "Year text color." },
            { name: "titleColor", type: "string", default: "#ffffff", description: "Title text color." },
            { name: "textColor", type: "string", default: "#94a3b8", description: "Text color." },
        ],
    },
    {
        id: "timeline-brutal",
        name: "Neo-Brutal Scroll",
        description: "Neo-brutal scroll timeline with sticky stack cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["timeline", "brutalist", "scroll", "sticky"],
        previewUrl: "/ContentBlocks/Timeline/TimelineBrutal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{year: string, title: string, desc: string, category: string}>", default: "[]", description: "Array of timeline items with year, title, description, and category." },
            { name: "backgroundColor", type: "string", default: "#E0E7FF", description: "Background color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#000000", description: "Border color." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "textColor", type: "string", default: "#000000", description: "Text color." },
        ],
    },
    {
        id: "timeline-sketch",
        name: "Sketchbook",
        description: "Hand-drawn sketchbook timeline with paper texture.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["timeline", "sketch", "hand-drawn", "paper"],
        previewUrl: "/ContentBlocks/Timeline/TimelineSketch",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{year: string, title: string, desc: string, category: string}>", default: "[]", description: "Array of timeline items with year, title, description, and category." },
            { name: "backgroundColor", type: "string", default: "#fffdf5", description: "Background color (hex, rgb, or hsl)." },
            { name: "paperTextureColor", type: "string", default: "#444", description: "Paper texture pattern color." },
            { name: "lineColor", type: "string", default: "#333", description: "Timeline line color." },
            { name: "cardBgColor", type: "string", default: "#ffffff", description: "Card background color." },
            { name: "cardBorderColor", type: "string", default: "#1e293b", description: "Card border color." },
            { name: "titleColor", type: "string", default: "#0f172a", description: "Title text color." },
            { name: "textColor", type: "string", default: "#475569", description: "Text color." },
            { name: "yearColor", type: "string", default: "rgba(15, 23, 42, 0.1)", description: "Year text color." },
        ],
    },
    {
        id: "timeline-glass",
        name: "Glass Helix",
        description: "Glass helix timeline with rotating cards.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["timeline", "glass", "helix", "rotating"],
        previewUrl: "/ContentBlocks/Timeline/TimelineGlass",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{year: string, title: string, desc: string, category: string}>", default: "[]", description: "Array of timeline items with year, title, description, and category." },
            { name: "backgroundColor", type: "string", default: "#0f172a", description: "Background color (hex, rgb, or hsl)." },
            { name: "cardBgColor", type: "string", default: "rgba(255,255,255,0.05)", description: "Card background color." },
            { name: "borderColor", type: "string", default: "rgba(255,255,255,0.1)", description: "Border color." },
            { name: "accentColor", type: "string", default: "#a855f7", description: "Accent color for hover effects." },
        ],
    },
    {
        id: "uilora-scroll-timeline",
        name: "Uilora Scroll",
        description: "Scroll-driven image timeline with parallax and progress indicator.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["timeline", "scroll", "parallax", "image", "dark"],
        previewUrl: "/ContentBlocks/Timeline/UiloraScroll",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "events", type: "Array<{date, title, description, image}>", default: "5 Uilora milestones", description: "Timeline events with images." },
            { name: "title", type: "string", default: "The Uilora Story", description: "Section heading." },
            { name: "subtitle", type: "string", default: "OUR JOURNEY", description: "Tag above heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Progress line and dot accent color." },
        ],
    },
    {
        id: "uilora-horizontal-timeline",
        name: "Uilora Horizontal",
        description: "Horizontal draggable timeline with snap-to behavior.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["timeline", "horizontal", "drag", "interactive"],
        previewUrl: "/ContentBlocks/Timeline/UiloraHorizontal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "events", type: "Array<{date, title, description, image}>", default: "6 Uilora milestones", description: "Timeline events with thumbnails." },
            { name: "title", type: "string", default: "Our Timeline", description: "Section heading." },
            { name: "subtitle", type: "string", default: "MILESTONES", description: "Tag above heading." },
            { name: "accentColor", type: "string", default: "#5227FF", description: "Active dot and highlight color." },
        ],
    },
    {
        id: "uilora-cards-timeline",
        name: "Uilora Cards",
        description: "Stacked overlapping cards timeline with hover expand.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["timeline", "cards", "stacked", "hover", "expand"],
        previewUrl: "/ContentBlocks/Timeline/UiloraCards",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "events", type: "Array<{date, title, description, image, color}>", default: "5 Uilora milestones", description: "Timeline events with colored borders." },
            { name: "title", type: "string", default: "Our Journey So Far", description: "Section heading." },
            { name: "subtitle", type: "string", default: "Every milestone that shaped Uilora.", description: "Section subtitle." },
            { name: "accentColor", type: "string", default: "#1a1a1a", description: "Header text color." },
        ],
    },
    {
        id: "uilora-minimal-timeline",
        name: "Uilora Minimal",
        description: "Ultra-minimal editorial timeline with typography-only design.",
        category: "Content Blocks",
        installType: "cli",
        tags: ["timeline", "minimal", "editorial", "typography"],
        previewUrl: "/ContentBlocks/Timeline/UiloraMinimal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "events", type: "Array<{year, title, description}>", default: "5 Uilora milestones", description: "Timeline events with year and text." },
            { name: "title", type: "string", default: "TIMELINE", description: "Small tag label." },
            { name: "subtitle", type: "string", default: "", description: "Optional subtitle." },
            { name: "accentColor", type: "string", default: "#000000", description: "Title and hover accent color." },
        ],
    },
];

