import { Component } from "../types";

// All form components from Forms and Forms2
// Total: 27 components (15 from Forms + 12 from Forms2)

export const formComponentsMetadata: Component[] = [
  // From Forms (first 15)
  {
    id: "neo-brutal-form",
    name: "Neo Brutal Form",
    description: "Bold neo-brutalist form with high contrast and geometric design.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "brutalist", "bold", "geometric"],
    previewUrl: "/UIComponents/Forms/NeoBrutalForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Join the Cult"', description: "Form title text." },
      { name: "fields", type: "Array<{ label: string; type?: string }>", default: "[{ label: \"Username\", type: \"text\" }, { label: \"Email Address\", type: \"text\" }, { label: \"Secret Code\", type: \"password\" }]", description: "Array of form field objects with label and optional type." },
      { name: "buttonText", type: "string", default: '"Submit Data"', description: "Submit button text." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"28rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#E0E7FF"', description: "Background color (hex, rgb, or hsl)." },
      { name: "cardBgColor", type: "string", default: '"#FFDE00"', description: "Card background color." },
      { name: "borderColor", type: "string", default: '"#000000"', description: "Border color (hex, rgb, or hsl)." },
      { name: "shadowColor", type: "string", default: '"rgba(0,0,0,1)"', description: "Shadow color (rgba)." },
      { name: "titleColor", type: "string", default: '"#000000"', description: "Title text color." },
      { name: "labelColor", type: "string", default: '"#000000"', description: "Label text color." },
      { name: "inputBgColor", type: "string", default: '"#ffffff"', description: "Input background color." },
      { name: "inputBorderColor", type: "string", default: '"#000000"', description: "Input border color." },
      { name: "inputTextColor", type: "string", default: '"#000000"', description: "Input text color." },
      { name: "inputPlaceholderColor", type: "string", default: '"#9ca3af"', description: "Input placeholder color." },
      { name: "inputFocusShadowColor", type: "string", default: '"rgba(0,0,0,0.5)"', description: "Input focus shadow color (rgba)." },
      { name: "buttonBgColor", type: "string", default: '"#000000"', description: "Button background color." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "buttonBorderColor", type: "string", default: '"#000000"', description: "Button border color." },
      { name: "buttonShadowColor", type: "string", default: '"rgba(0,0,0,1)"', description: "Button shadow color (rgba)." },
      { name: "buttonHoverShadowColor", type: "string", default: '"rgba(0,0,0,0.5)"', description: "Button hover shadow color (rgba)." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "glass-form",
    name: "Glassmorphism Form",
    description: "Frosted glass form with blur effects and modern aesthetics.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "glassmorphism", "frosted", "modern"],
    previewUrl: "/UIComponents/Forms/GlassForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Secure Access"', description: "Form title text." },
      { name: "subtitle", type: "string", default: '"Enter your credentials to float."', description: "Form subtitle text." },
      { name: "icon", type: "React.ReactNode", default: "<Lock className=\"text-white w-6 h-6\" />", description: "Icon element to display." },
      { name: "fields", type: "Array<{ placeholder: string; type?: string }>", default: "[{ placeholder: \"Email\", type: \"email\" }, { placeholder: \"Password\", type: \"password\" }]", description: "Array of form field objects with placeholder and optional type." },
      { name: "buttonText", type: "string", default: '"Enter"', description: "Submit button text." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"28rem"', description: "Maximum form width." },
      { name: "backgroundGradientFrom", type: "string", default: '"#667eea"', description: "Background gradient start color." },
      { name: "backgroundGradientVia", type: "string", default: '"#764ba2"', description: "Background gradient middle color." },
      { name: "backgroundGradientTo", type: "string", default: '"#f093fb"', description: "Background gradient end color." },
      { name: "blob1Color", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "First blob color (rgba)." },
      { name: "blob2Color", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Second blob color (rgba)." },
      { name: "blob3Color", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Third blob color (rgba)." },
      { name: "blobSize", type: "string", default: '"20rem"', description: "Blob size." },
      { name: "blobBlur", type: "string", default: '"8rem"', description: "Blob blur radius." },
      { name: "cardBgColor", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Card background color (rgba)." },
      { name: "cardBorderColor", type: "string", default: '"rgba(255, 255, 255, 0.2)"', description: "Card border color (rgba)." },
      { name: "iconBgColor", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Icon background color (rgba)." },
      { name: "iconColor", type: "string", default: '"#ffffff"', description: "Icon color." },
      { name: "titleColor", type: "string", default: '"#ffffff"', description: "Title text color." },
      { name: "subtitleColor", type: "string", default: '"rgba(255, 255, 255, 0.7)"', description: "Subtitle text color (rgba)." },
      { name: "inputBgColor", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Input background color (rgba)." },
      { name: "inputBorderColor", type: "string", default: '"rgba(255, 255, 255, 0.2)"', description: "Input border color (rgba)." },
      { name: "inputFocusBgColor", type: "string", default: '"rgba(255, 255, 255, 0.15)"', description: "Input background color on focus (rgba)." },
      { name: "inputFocusBorderColor", type: "string", default: '"rgba(255, 255, 255, 0.4)"', description: "Input border color on focus (rgba)." },
      { name: "inputTextColor", type: "string", default: '"#ffffff"', description: "Input text color." },
      { name: "inputPlaceholderColor", type: "string", default: '"rgba(255, 255, 255, 0.5)"', description: "Input placeholder color (rgba)." },
      { name: "buttonGradientFrom", type: "string", default: '"#667eea"', description: "Button gradient start color." },
      { name: "buttonGradientTo", type: "string", default: '"#764ba2"', description: "Button gradient end color." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "buttonBorderColor", type: "string", default: '"rgba(255, 255, 255, 0.2)"', description: "Button border color (rgba)." },
      { name: "buttonShadowColor", type: "string", default: '"rgba(102, 126, 234, 0.4)"', description: "Button shadow color (rgba)." },
      { name: "shimmerColor", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Shimmer effect color (rgba)." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "cyberpunk-form",
    name: "Cyberpunk Form",
    description: "Cyberpunk-inspired form with neon effects and glitch aesthetics.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "cyberpunk", "neon", "glitch"],
    previewUrl: "/UIComponents/Forms/CyberpunkForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Netrunner"', description: "Form title text." },
      { name: "statusText", type: "string", default: '"SYS.ONLINE"', description: "Status text to display." },
      { name: "fields", type: "Array<{ label: string; type?: string }>", default: "[{ label: \"Identity\", type: \"text\" }, { label: \"Access_Key\", type: \"password\" }]", description: "Array of form field objects with label and optional type." },
      { name: "buttonText", type: "string", default: '"Initialize Link"', description: "Submit button text." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"32rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#050505"', description: "Background color (hex, rgb, or hsl)." },
      { name: "borderColor", type: "string", default: '"rgba(6, 182, 212, 0.3)"', description: "Border color (rgba)." },
      { name: "cornerTopColor", type: "string", default: '"#06b6d4"', description: "Top corner accent color." },
      { name: "cornerBottomColor", type: "string", default: '"#ec4899"', description: "Bottom corner accent color." },
      { name: "cardBgColor", type: "string", default: '"#0a0a0a"', description: "Card background color." },
      { name: "cardBorderColor", type: "string", default: '"rgba(255, 255, 255, 0.05)"', description: "Card border color (rgba)." },
      { name: "titleGradientFrom", type: "string", default: '"#22d3ee"', description: "Title gradient start color." },
      { name: "titleGradientTo", type: "string", default: '"#2563eb"', description: "Title gradient end color." },
      { name: "statusColor", type: "string", default: '"#06b6d4"', description: "Status text color." },
      { name: "labelColor", type: "string", default: '"#ec4899"', description: "Label text color." },
      { name: "inputBgColor", type: "string", default: '"#000000"', description: "Input background color." },
      { name: "inputBorderColor", type: "string", default: '"#1f2937"', description: "Input border color." },
      { name: "inputFocusBorderColor", type: "string", default: '"#22d3ee"', description: "Input border color on focus." },
      { name: "inputTextColor", type: "string", default: '"#06b6d4"', description: "Input text color." },
      { name: "underlineColor", type: "string", default: '"#22d3ee"', description: "Input underline color." },
      { name: "underlineShadowColor", type: "string", default: '"rgba(34, 211, 238, 0.5)"', description: "Input underline shadow color (rgba)." },
      { name: "buttonBorderColor", type: "string", default: '"#22d3ee"', description: "Button border color." },
      { name: "buttonTextColor", type: "string", default: '"#22d3ee"', description: "Button text color." },
      { name: "buttonHoverBgColor", type: "string", default: '"rgba(34, 211, 238, 0.1)"', description: "Button background color on hover (rgba)." },
      { name: "clipPath", type: "string", default: '"polygon(0 0, 100% 0, 100% 100%, 0 100%)"', description: "Clip path CSS value for corner effects." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "clay-form",
    name: "Clay Form",
    description: "Soft clay-like form with organic shapes and tactile design.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "clay", "soft", "organic"],
    previewUrl: "/UIComponents/Forms/ClayForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Soft Sign In"', description: "Form title text." },
      { name: "icon", type: "React.ReactNode", default: "<Feather size={32} />", description: "Icon element to display." },
      { name: "fields", type: "Array<{ placeholder: string; type?: string }>", default: "[{ placeholder: \"Username\", type: \"text\" }, { placeholder: \"Password\", type: \"password\" }]", description: "Array of form field objects with placeholder and optional type." },
      { name: "buttonText", type: "string", default: '"Enter"', description: "Submit button text." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"24rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#f0f4f8"', description: "Background color (hex, rgb, or hsl)." },
      { name: "cardBgColor", type: "string", default: '"#f0f4f8"', description: "Card background color." },
      { name: "cardShadow", type: "string", default: '"inset -12px -12px 20px rgba(255,255,255,1), inset 12px 12px 20px rgba(174,174,192,0.4), 12px 12px 24px rgba(174,174,192,0.2)"', description: "Card shadow CSS value." },
      { name: "iconBgColor", type: "string", default: '"#f0f4f8"', description: "Icon background color." },
      { name: "iconShadow", type: "string", default: '"inset -6px -6px 10px rgba(255,255,255,1), inset 6px 6px 10px rgba(174,174,192,0.4), 6px 6px 12px rgba(174,174,192,0.3)"', description: "Icon shadow CSS value." },
      { name: "iconColor", type: "string", default: '"#60a5fa"', description: "Icon color (hex, rgb, or hsl)." },
      { name: "titleColor", type: "string", default: '"#64748b"', description: "Title text color." },
      { name: "inputBgColor", type: "string", default: '"#f0f4f8"', description: "Input background color." },
      { name: "inputTextColor", type: "string", default: '"#475569"', description: "Input text color." },
      { name: "inputPlaceholderColor", type: "string", default: '"#94a3b8"', description: "Input placeholder color." },
      { name: "inputShadow", type: "string", default: '"inset 6px 6px 10px rgba(174,174,192,0.3), inset -6px -6px 10px rgba(255,255,255,1)"', description: "Input shadow CSS value." },
      { name: "inputFocusShadow", type: "string", default: '"inset 2px 2px 4px rgba(174,174,192,0.4), inset -2px -2px 4px rgba(255,255,255,1)"', description: "Input focus shadow CSS value." },
      { name: "buttonBgColor", type: "string", default: '"#ebf0f5"', description: "Button background color." },
      { name: "buttonTextColor", type: "string", default: '"#3b82f6"', description: "Button text color." },
      { name: "buttonShadow", type: "string", default: '"-6px -6px 14px rgba(255,255,255,1), 6px 6px 10px rgba(174,174,192,0.4)"', description: "Button shadow CSS value." },
      { name: "buttonActiveShadow", type: "string", default: '"inset 4px 4px 8px rgba(174,174,192,0.3), inset -4px -4px 8px rgba(255,255,255,1)"', description: "Button active shadow CSS value." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "lux-form",
    name: "Luxury Form",
    description: "Luxurious minimal form with elegant design and premium aesthetics.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "luxury", "minimal", "elegant"],
    previewUrl: "/UIComponents/Forms/LuxForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Atelier."', description: "Form title text." },
      { name: "subtitle", type: "string", default: '"Digital craftsmanship."', description: "Form subtitle text." },
      { name: "fields", type: "Array<{ label: string; type?: string }>", default: "[{ label: \"Full Name\", type: \"text\" }, { label: \"Email Address\", type: \"email\" }]", description: "Array of form field objects with label and optional type." },
      { name: "buttonText", type: "string", default: '"Proceed"', description: "Submit button text." },
      { name: "buttonIcon", type: "React.ReactNode", default: "<ArrowRight className=\"w-5 h-5\" />", description: "Button icon element." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"32rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#FDFBF7"', description: "Background color (hex, rgb, or hsl)." },
      { name: "titleColor", type: "string", default: '"#1a1a1a"', description: "Title text color." },
      { name: "subtitleColor", type: "string", default: '"#666666"', description: "Subtitle text color." },
      { name: "inputTextColor", type: "string", default: '"#111827"', description: "Input text color." },
      { name: "inputBorderColor", type: "string", default: '"#d1d5db"', description: "Input border color." },
      { name: "inputFocusBorderColor", type: "string", default: '"#000000"', description: "Input border color on focus." },
      { name: "labelColor", type: "string", default: '"#9ca3af"', description: "Label text color." },
      { name: "labelFocusColor", type: "string", default: '"#000000"', description: "Label text color on focus." },
      { name: "underlineColor", type: "string", default: '"#000000"', description: "Input underline color." },
      { name: "buttonColor", type: "string", default: '"#000000"', description: "Button color." },
      { name: "underlineHoverDuration", type: "number", default: "500", description: "Underline hover animation duration in milliseconds." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "floating-form",
    name: "Floating Form",
    description: "Physics-based floating form with smooth animations and interactions.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "floating", "physics", "smooth"],
    previewUrl: "/UIComponents/Forms/FloatingForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Dynamic Input"', description: "Form title text." },
      { name: "icon", type: "React.ReactNode", default: "<Sparkles className=\"text-white w-5 h-5\" />", description: "Icon element to display." },
      { name: "fields", type: "Array<{ id: string; label: string; type?: string }>", default: "[{ id: \"name\", label: \"Your Name\", type: \"text\" }, { id: \"role\", label: \"Current Role\", type: \"text\" }]", description: "Array of form field objects with id, label, and optional type." },
      { name: "buttonText", type: "string", default: '"Continue"', description: "Submit button text." },
      { name: "buttonIcon", type: "React.ReactNode", default: "<ArrowRight className=\"w-4 h-4\" />", description: "Button icon element." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"28rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#0f172a"', description: "Background color (hex, rgb, or hsl)." },
      { name: "cardBgColor", type: "string", default: '"#1e293b"', description: "Card background color." },
      { name: "cardBorderColor", type: "string", default: '"#334155"', description: "Card border color." },
      { name: "iconBgColor", type: "string", default: '"#6366f1"', description: "Icon background color." },
      { name: "iconColor", type: "string", default: '"#ffffff"', description: "Icon color." },
      { name: "titleColor", type: "string", default: '"#ffffff"', description: "Title text color." },
      { name: "fieldBgColor", type: "string", default: '"#0f172a"', description: "Field background color." },
      { name: "fieldBorderColor", type: "string", default: '"#334155"', description: "Field border color." },
      { name: "fieldActiveBorderColor", type: "string", default: '"#6366f1"', description: "Field border color when active." },
      { name: "fieldActiveShadowColor", type: "string", default: '"rgba(99, 102, 241, 0.3)"', description: "Field shadow color when active (rgba)." },
      { name: "labelColor", type: "string", default: '"#94a3b8"', description: "Label text color." },
      { name: "labelActiveColor", type: "string", default: '"#818cf8"', description: "Label text color when active." },
      { name: "inputTextColor", type: "string", default: '"#ffffff"', description: "Input text color." },
      { name: "buttonBgColor", type: "string", default: '"#4f46e5"', description: "Button background color." },
      { name: "buttonHoverBgColor", type: "string", default: '"#4338ca"', description: "Button background color on hover." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "terminal-form",
    name: "Terminal Form",
    description: "Terminal CLI-style form with monospace typography and command-line aesthetics.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "terminal", "cli", "monospace"],
    previewUrl: "/UIComponents/Forms/TerminalForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "steps", type: "Array<{ prompt: string; key: string; type?: string }>", default: "[{ prompt: \"Enter username:\", key: \"username\" }, { prompt: \"Enter password:\", key: \"password\", type: \"password\" }, { prompt: \"Confirm execution? (y/n):\", key: \"confirm\" }]", description: "Array of form step objects with prompt, key, and optional type." },
      { name: "initCommand", type: "string", default: '"./init_protocol.sh"', description: "Initial command text." },
      { name: "initMessage", type: "string", default: '"Initializing secure environment... [OK]"', description: "Initial message text." },
      { name: "successMessage", type: "string", default: '"Access Granted. Launching payload..."', description: "Success message text." },
      { name: "terminalTitle", type: "string", default: '"bash — 80x24"', description: "Terminal window title." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"42rem"', description: "Maximum form width." },
      { name: "height", type: "string", default: '"20rem"', description: "Form height." },
      { name: "backgroundColor", type: "string", default: '"#000000"', description: "Background color (hex, rgb, or hsl)." },
      { name: "borderColor", type: "string", default: '"#1f2937"', description: "Border color (hex, rgb, or hsl)." },
      { name: "headerBgColor", type: "string", default: '"#111827"', description: "Header background color." },
      { name: "headerBorderColor", type: "string", default: '"#1f2937"', description: "Header border color." },
      { name: "redDotColor", type: "string", default: '"#ef4444"', description: "Red dot color." },
      { name: "yellowDotColor", type: "string", default: '"#eab308"', description: "Yellow dot color." },
      { name: "greenDotColor", type: "string", default: '"#22c55e"', description: "Green dot color." },
      { name: "commandColor", type: "string", default: '"#60a5fa"', description: "Command text color." },
      { name: "promptColor", type: "string", default: '"#ffffff"', description: "Prompt text color." },
      { name: "inputColor", type: "string", default: '"#22c55e"', description: "Input text color." },
      { name: "successColor", type: "string", default: '"#facc15"', description: "Success message color." },
      { name: "progressBgColor", type: "string", default: '"#1f2937"', description: "Progress bar background color." },
      { name: "progressBarColor", type: "string", default: '"#22c55e"', description: "Progress bar fill color." },
      { name: "cursorBlinkDuration", type: "number", default: "0.8", description: "Cursor blink animation duration in seconds." },
      { name: "progressDuration", type: "number", default: "2", description: "Progress animation duration in seconds." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "natural-form",
    name: "Natural Language Form",
    description: "Natural language form with conversational interface and AI-like interactions.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "natural", "language", "conversational"],
    previewUrl: "/UIComponents/Forms/NaturalForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "sentence", type: "string", default: '"I want to hire a {0} for my project regarding {1}. My budget is around {2}."', description: "Sentence template with placeholders {0}, {1}, {2}, etc." },
      { name: "placeholders", type: "string[]", default: "[\"designer\", \"branding\", \"$5k\"]", description: "Array of placeholder values for the sentence template." },
      { name: "buttonText", type: "string", default: '"Let\'s Talk"', description: "Submit button text." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"48rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#fcfcfc"', description: "Background color (hex, rgb, or hsl)." },
      { name: "textColor", type: "string", default: '"#333333"', description: "Text color (hex, rgb, or hsl)." },
      { name: "inputBorderColor", type: "string", default: '"#d1d5db"', description: "Input border color." },
      { name: "inputFocusBorderColor", type: "string", default: '"#000000"', description: "Input border color on focus." },
      { name: "inputPlaceholderColor", type: "string", default: '"#d1d5db"', description: "Input placeholder color." },
      { name: "buttonBgColor", type: "string", default: '"#000000"', description: "Button background color." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "dividerColor", type: "string", default: '"#e5e7eb"', description: "Divider color (hex, rgb, or hsl)." },
      { name: "inputWidth", type: "string", default: '"12rem"', description: "Input width." },
      { name: "inputFocusWidth", type: "string", default: '"16rem"', description: "Input width on focus." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "card-wizard",
    name: "3D Card Wizard",
    description: "3D card-based multi-step form wizard with depth and perspective.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "wizard", "3d", "multi-step"],
    previewUrl: "/UIComponents/Forms/CardWizard",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "steps", type: "Array<{ title: string; icon: React.ComponentType<{ className?: string }> }>", default: "[{ title: \"Personal Details\", icon: User }, { title: \"Shipping Address\", icon: MapPin }, { title: \"Payment Method\", icon: CreditCard }]", description: "Array of step objects with title and icon component." },
      { name: "placeholders", type: "Array<{ a: string; b: string }>", default: "[{ a: \"Input A\", b: \"Input B\" }, { a: \"Input A\", b: \"Input B\" }, { a: \"Input A\", b: \"Input B\" }]", description: "Array of placeholder objects for each step." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"24rem"', description: "Maximum form width." },
      { name: "height", type: "string", default: '"24rem"', description: "Form height." },
      { name: "backgroundColor", type: "string", default: '"#f1f5f9"', description: "Background color (hex, rgb, or hsl)." },
      { name: "gridColor", type: "string", default: '"#000000"', description: "Grid color (hex, rgb, or hsl)." },
      { name: "cardBgColor", type: "string", default: '"#ffffff"', description: "Card background color." },
      { name: "cardBorderColor", type: "string", default: '"#e2e8f0"', description: "Card border color." },
      { name: "stepTextColor", type: "string", default: '"#94a3b8"', description: "Step text color." },
      { name: "iconColor", type: "string", default: '"#3b82f6"', description: "Icon color (hex, rgb, or hsl)." },
      { name: "titleColor", type: "string", default: '"#1e293b"', description: "Title text color." },
      { name: "inputBgColor", type: "string", default: '"#f8fafc"', description: "Input background color." },
      { name: "inputFocusRingColor", type: "string", default: '"#3b82f6"', description: "Input focus ring color." },
      { name: "backButtonColor", type: "string", default: '"#64748b"', description: "Back button color." },
      { name: "backButtonHoverColor", type: "string", default: '"#000000"', description: "Back button color on hover." },
      { name: "nextButtonBgColor", type: "string", default: '"#2563eb"', description: "Next button background color." },
      { name: "nextButtonTextColor", type: "string", default: '"#ffffff"', description: "Next button text color." },
      { name: "nextButtonShadowColor", type: "string", default: '"rgba(37, 99, 235, 0.5)"', description: "Next button shadow color (rgba)." },
      { name: "springStiffness", type: "number", default: "300", description: "Spring animation stiffness." },
      { name: "springDamping", type: "number", default: "30", description: "Spring animation damping." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "holographic-form",
    name: "Holographic Form",
    description: "Holographic form with prismatic effects and futuristic design.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "holographic", "prismatic", "futuristic"],
    previewUrl: "/UIComponents/Forms/HolographicForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Hololink ID"', description: "Form title text." },
      { name: "fields", type: "Array<{ label: string; type?: string }>", default: "[{ label: \"Sector\", type: \"text\" }, { label: \"Unit ID\", type: \"text\" }]", description: "Array of form field objects with label and optional type." },
      { name: "buttonText", type: "string", default: '"Materialize"', description: "Submit button text." },
      { name: "icon", type: "React.ReactNode", default: "<Ghost className=\"w-5 h-5\" />", description: "Icon element to display." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"28rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#000000"', description: "Background color (hex, rgb, or hsl)." },
      { name: "glowGradientFrom", type: "string", default: '"#db2777"', description: "Glow gradient start color." },
      { name: "glowGradientVia", type: "string", default: '"#9333ea"', description: "Glow gradient middle color." },
      { name: "glowGradientTo", type: "string", default: '"#06b6d4"', description: "Glow gradient end color." },
      { name: "cardBgColor", type: "string", default: '"rgba(0, 0, 0, 0.8)"', description: "Card background color (rgba)." },
      { name: "cardBorderColor", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Card border color (rgba)." },
      { name: "titleGradientFrom", type: "string", default: '"#f9a8d4"', description: "Title gradient start color." },
      { name: "titleGradientVia", type: "string", default: '"#c084fc"', description: "Title gradient middle color." },
      { name: "titleGradientTo", type: "string", default: '"#67e8f9"', description: "Title gradient end color." },
      { name: "labelColor", type: "string", default: '"#9ca3af"', description: "Label text color." },
      { name: "labelFocusColor", type: "string", default: '"#c084fc"', description: "Label text color on focus." },
      { name: "inputBgColor", type: "string", default: '"rgba(255, 255, 255, 0.05)"', description: "Input background color (rgba)." },
      { name: "inputBorderColor", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Input border color (rgba)." },
      { name: "inputFocusBorderColor", type: "string", default: '"rgba(192, 132, 252, 0.5)"', description: "Input border color on focus (rgba)." },
      { name: "inputFocusBgColor", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Input background color on focus (rgba)." },
      { name: "inputFocusShadowColor", type: "string", default: '"rgba(192, 132, 252, 0.3)"', description: "Input shadow color on focus (rgba)." },
      { name: "inputTextColor", type: "string", default: '"#ffffff"', description: "Input text color." },
      { name: "iconColor", type: "string", default: '"#c084fc"', description: "Icon color." },
      { name: "buttonGradientFrom", type: "string", default: '"#db2777"', description: "Button gradient start color." },
      { name: "buttonGradientTo", type: "string", default: '"#9333ea"', description: "Button gradient end color." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "spotlightSize", type: "string", default: '"600px"', description: "Spotlight effect size." },
      { name: "spotlightOpacity", type: "number", default: "0.1", description: "Spotlight effect opacity (0-1)." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "sketch-form",
    name: "Hand Sketch Form",
    description: "Hand-drawn sketchy form with artistic aesthetics and organic lines.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "sketch", "hand-drawn", "artistic"],
    previewUrl: "/UIComponents/Forms/SketchForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Sign Up!"', description: "Form title text." },
      { name: "nameLabel", type: "string", default: '"Who are you?"', description: "Name field label." },
      { name: "passwordLabel", type: "string", default: '"Secret Password"', description: "Password field label." },
      { name: "buttonText", type: "string", default: '"Let\'s Go!"', description: "Submit button text." },
      { name: "icon", type: "string", default: "undefined", description: "Icon string (deprecated, use iconEmoji)." },
      { name: "iconEmoji", type: "string", default: '"✏️"', description: "Icon emoji to display." },
      { name: "onSubmit", type: "(data: { name: string; password: string }) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"28rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#ffffff"', description: "Background color (hex, rgb, or hsl)." },
      { name: "backgroundPageColor", type: "string", default: '"#fffdf0"', description: "Page background color." },
      { name: "borderColor", type: "string", default: '"#333333"', description: "Border color (hex, rgb, or hsl)." },
      { name: "titleColor", type: "string", default: '"#333333"', description: "Title text color." },
      { name: "labelColor", type: "string", default: '"#444444"', description: "Label text color." },
      { name: "inputBorderColor", type: "string", default: '"#333333"', description: "Input border color." },
      { name: "buttonBgColor", type: "string", default: '"#FFD700"', description: "Button background color." },
      { name: "buttonTextColor", type: "string", default: '"#000000"', description: "Button text color." },
      { name: "buttonShadowColor", type: "string", default: '"#333333"', description: "Button shadow color." },
      { name: "shadowColor", type: "string", default: '"rgba(0,0,0,0.1)"', description: "General shadow color (rgba)." },
      { name: "borderRadius", type: "string", default: '"255px 15px 225px 15px / 15px 225px 15px 255px"', description: "Border radius CSS value for sketchy effect." },
      { name: "borderRadius2", type: "string", default: '"15px 225px 15px 255px / 255px 15px 225px 15px"', description: "Alternative border radius CSS value." },
      { name: "titleRotation", type: "string", default: '"-2deg"', description: "Title rotation angle." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "code-block-form",
    name: "Code Block Form",
    description: "Code editor-style form with syntax highlighting and developer aesthetics.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "code", "editor", "syntax"],
    previewUrl: "/UIComponents/Forms/CodeBlockForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "fileName", type: "string", default: '"form.tsx"', description: "File name displayed in header." },
      { name: "lineNumber", type: "string", default: '"12"', description: "Line number displayed in header." },
      { name: "columnNumber", type: "string", default: '"42"', description: "Column number displayed in header." },
      { name: "encoding", type: "string", default: '"UTF-8"', description: "File encoding displayed in header." },
      { name: "language", type: "string", default: '"TypeScript React"', description: "Language displayed in header." },
      { name: "fields", type: "Array<{ prop: string; placeholder: string; type?: string }>", default: "[{ prop: \"prop\", placeholder: \"\\\"username\\\"\", type: \"text\" }, { prop: \"secure\", placeholder: \"\\\"*****\\\"\", type: \"password\" }]", description: "Array of form field objects with prop name, placeholder, and optional type." },
      { name: "buttonText", type: "string", default: '"Compile & Submit"', description: "Submit button text." },
      { name: "buttonIcon", type: "React.ReactNode", default: "<Zap size={14} />", description: "Button icon element." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"32rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#1e1e1e"', description: "Background color (hex, rgb, or hsl)." },
      { name: "headerBgColor", type: "string", default: '"#333333"', description: "Header background color." },
      { name: "headerTextColor", type: "string", default: '"#9ca3af"', description: "Header text color." },
      { name: "fileNameColor", type: "string", default: '"#60a5fa"', description: "File name color." },
      { name: "borderColor", type: "string", default: '"#3e3e42"', description: "Border color (hex, rgb, or hsl)." },
      { name: "lineNumberColor", type: "string", default: '"#6b7280"', description: "Line number color." },
      { name: "codeTextColor", type: "string", default: '"#d1d5db"', description: "Code text color." },
      { name: "constColor", type: "string", default: '"#a78bfa"', description: "Const keyword color." },
      { name: "functionColor", type: "string", default: '"#fbbf24"', description: "Function keyword color." },
      { name: "arrowColor", type: "string", default: '"#60a5fa"', description: "Arrow color." },
      { name: "braceColor", type: "string", default: '"#ffffff"', description: "Brace color." },
      { name: "commentColor", type: "string", default: '"#6b7280"', description: "Comment color." },
      { name: "tagColor", type: "string", default: '"#34d399"', description: "Tag color." },
      { name: "propColor", type: "string", default: '"#f472b6"', description: "Property color." },
      { name: "inputColor", type: "string", default: '"#22c55e"', description: "Input text color." },
      { name: "buttonBgColor", type: "string", default: '"#2563eb"', description: "Button background color." },
      { name: "buttonHoverBgColor", type: "string", default: '"#1d4ed8"', description: "Button background color on hover." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "buttonIconColor", type: "string", default: '"#ffffff"', description: "Button icon color." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "arcade-form",
    name: "Sonic Arcade Form",
    description: "Retro arcade-style form with gaming aesthetics and pixel-perfect design.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "arcade", "retro", "gaming"],
    previewUrl: "/UIComponents/Forms/ArcadeForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Insert Coin"', description: "Form title text." },
      { name: "icon", type: "React.ReactNode", default: "<Gamepad2 className=\"w-6 h-6 animate-pulse\" />", description: "Icon element to display." },
      { name: "placeholder", type: "string", default: '"PLAYER 1"', description: "Input placeholder text." },
      { name: "loadingText", type: "string", default: '"LOADING RESOURCES..."', description: "Loading state text." },
      { name: "buttonText", type: "string", default: '"Start Game"', description: "Submit button text." },
      { name: "onSubmit", type: "(data: { player: string }) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"24rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#2c0e37"', description: "Background color (hex, rgb, or hsl)." },
      { name: "backgroundGradientFrom", type: "string", default: '"#5b1e70"', description: "Background gradient start color." },
      { name: "backgroundGradientTo", type: "string", default: '"#2c0e37"', description: "Background gradient end color." },
      { name: "gridColor", type: "string", default: '"rgba(255,0,255,0.3)"', description: "Grid color (rgba)." },
      { name: "gridSize", type: "string", default: '"40px"', description: "Grid size." },
      { name: "outerBorderColor", type: "string", default: '"#ff00ff"', description: "Outer border color." },
      { name: "outerShadowColor", type: "string", default: '"#ff00ff"', description: "Outer shadow color." },
      { name: "innerBorderColor", type: "string", default: '"#00ffff"', description: "Inner border color." },
      { name: "titleColor", type: "string", default: '"#ffffff"', description: "Title text color." },
      { name: "titleShadowColor", type: "string", default: '"#ff00ff"', description: "Title shadow color." },
      { name: "titleDropShadowColor", type: "string", default: '"#00ffff"', description: "Title drop shadow color." },
      { name: "iconColor", type: "string", default: '"#ffffff"', description: "Icon color." },
      { name: "inputBgColor", type: "string", default: '"#000000"', description: "Input background color." },
      { name: "inputBorderColor", type: "string", default: '"#ff00ff"', description: "Input border color." },
      { name: "inputTextColor", type: "string", default: '"#00ffff"', description: "Input text color." },
      { name: "inputPlaceholderColor", type: "string", default: '"rgba(0,255,255,0.5)"', description: "Input placeholder color (rgba)." },
      { name: "inputFocusShadowColor", type: "string", default: '"rgba(0,255,255,0.5)"', description: "Input focus shadow color (rgba)." },
      { name: "progressBgColor", type: "string", default: '"#000000"', description: "Progress bar background color." },
      { name: "progressBorderColor", type: "string", default: '"#ff00ff"', description: "Progress bar border color." },
      { name: "progressGradientFrom", type: "string", default: '"#ff00ff"', description: "Progress bar gradient start color." },
      { name: "progressGradientTo", type: "string", default: '"#00ffff"', description: "Progress bar gradient end color." },
      { name: "loadingTextColor", type: "string", default: '"#00ffff"', description: "Loading text color." },
      { name: "buttonBgColor", type: "string", default: '"#000000"', description: "Button background color." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "buttonBorderColor", type: "string", default: '"#ff00ff"', description: "Button border color." },
      { name: "buttonActiveBorderColor", type: "string", default: '"#00ffff"', description: "Button border color when active." },
      { name: "progressAnimationDuration", type: "number", default: "2", description: "Progress animation duration in seconds." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "split-form",
    name: "Split Visual Form",
    description: "Split-screen form with visual separation and modern layout.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "split", "visual", "layout"],
    previewUrl: "/UIComponents/Forms/SplitForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Welcome Back."', description: "Left panel title text." },
      { name: "subtitle", type: "string", default: '"Design is intelligence made visible."', description: "Left panel subtitle text." },
      { name: "formTitle", type: "string", default: '"Log in to your account"', description: "Form title text." },
      { name: "emailLabel", type: "string", default: '"Email"', description: "Email field label." },
      { name: "passwordLabel", type: "string", default: '"Password"', description: "Password field label." },
      { name: "rememberText", type: "string", default: '"Remember me"', description: "Remember me checkbox text." },
      { name: "forgotText", type: "string", default: '"Forgot?"', description: "Forgot password link text." },
      { name: "buttonText", type: "string", default: '"Sign In"', description: "Submit button text." },
      { name: "images", type: "string[]", default: "[\"https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop\", \"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1000&auto=format&fit=crop\", \"https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=1000&auto=format&fit=crop\"]", description: "Array of image URLs for the left panel." },
      { name: "imageChangeInterval", type: "number", default: "3000", description: "Image change interval in milliseconds." },
      { name: "onSubmit", type: "(data: { email: string; password: string; remember: boolean }) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"56rem"', description: "Maximum form width." },
      { name: "height", type: "string", default: '"500px"', description: "Form height." },
      { name: "backgroundColor", type: "string", default: '"#ffffff"', description: "Background color (hex, rgb, or hsl)." },
      { name: "leftPanelBgColor", type: "string", default: '"#000000"', description: "Left panel background color." },
      { name: "leftPanelTextColor", type: "string", default: '"#ffffff"', description: "Left panel text color." },
      { name: "leftPanelSubtitleColor", type: "string", default: '"#d1d5db"', description: "Left panel subtitle color." },
      { name: "imageOpacity", type: "number", default: "0.6", description: "Image opacity (0-1)." },
      { name: "imageScale", type: "number", default: "1.1", description: "Image scale factor." },
      { name: "indicatorActiveColor", type: "string", default: '"#ffffff"', description: "Active indicator color." },
      { name: "indicatorInactiveColor", type: "string", default: '"rgba(255, 255, 255, 0.5)"', description: "Inactive indicator color (rgba)." },
      { name: "formTitleColor", type: "string", default: '"#1f2937"', description: "Form title text color." },
      { name: "labelColor", type: "string", default: '"#4b5563"', description: "Label text color." },
      { name: "inputBgColor", type: "string", default: '"#f9fafb"', description: "Input background color." },
      { name: "inputFocusBgColor", type: "string", default: '"#ffffff"', description: "Input background color on focus." },
      { name: "inputFocusRingColor", type: "string", default: '"#000000"', description: "Input focus ring color." },
      { name: "buttonBgColor", type: "string", default: '"#000000"', description: "Button background color." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "liquid-form",
    name: "Liquid Fluid Form",
    description: "Liquid fluid form with morphing shapes and organic animations.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "liquid", "fluid", "morphing"],
    previewUrl: "/UIComponents/Forms/LiquidForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Flow State"', description: "Form title text." },
      { name: "emailPlaceholder", type: "string", default: '"Email"', description: "Email input placeholder." },
      { name: "passwordPlaceholder", type: "string", default: '"Password"', description: "Password input placeholder." },
      { name: "emailIcon", type: "React.ReactNode", default: "<Droplets size={20} />", description: "Email icon element." },
      { name: "passwordIcon", type: "React.ReactNode", default: "<span>***</span>", description: "Password icon element." },
      { name: "buttonIcon", type: "React.ReactNode", default: "<ArrowRight />", description: "Button icon element." },
      { name: "onSubmit", type: "(data: { email: string; password: string }) => void", default: "undefined", description: "Form submission handler function." },
      { name: "width", type: "string", default: '"400px"', description: "Form width." },
      { name: "minHeight", type: "string", default: '"500px"', description: "Minimum form height." },
      { name: "backgroundColor", type: "string", default: '"#e0f2fe"', description: "Background color (hex, rgb, or hsl)." },
      { name: "cardBgColor", type: "string", default: '"rgba(255, 255, 255, 0.5)"', description: "Card background color (rgba)." },
      { name: "cardBlur", type: "string", default: '"xl"', description: "Card blur level (Tailwind class)." },
      { name: "titleColor", type: "string", default: '"#0ea5e9"', description: "Title text color." },
      { name: "inputBgColor", type: "string", default: '"rgba(255, 255, 255, 0.6)"', description: "Input background color (rgba)." },
      { name: "inputTextColor", type: "string", default: '"#1e293b"', description: "Input text color." },
      { name: "inputPlaceholderColor", type: "string", default: '"#94a3b8"', description: "Input placeholder color." },
      { name: "inputFocusRingColor", type: "string", default: '"rgba(14, 165, 233, 0.2)"', description: "Input focus ring color (rgba)." },
      { name: "buttonBgColor", type: "string", default: '"#0ea5e9"', description: "Button background color." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "buttonShadowColor", type: "string", default: '"rgba(14, 165, 233, 0.4)"', description: "Button shadow color (rgba)." },
      { name: "blob1Color", type: "string", default: '"#38bdf8"', description: "First blob color." },
      { name: "blob2Color", type: "string", default: '"#60a5fa"', description: "Second blob color." },
      { name: "blob1Size", type: "string", default: '"20rem"', description: "First blob size." },
      { name: "blob2Size", type: "string", default: '"15rem"', description: "Second blob size." },
      { name: "borderRadius", type: "string[]", default: "[\"60% 40% 30% 70% / 60% 30% 70% 40%\", \"30% 60% 70% 40% / 50% 60% 30% 60%\", \"60% 40% 30% 70% / 60% 30% 70% 40%\"]", description: "Array of border radius values for morphing animation." },
      { name: "morphingDuration", type: "number", default: "8", description: "Morphing animation duration in seconds." },
      { name: "blob1Duration", type: "number", default: "10", description: "First blob animation duration in seconds." },
      { name: "blob2Duration", type: "number", default: "12", description: "Second blob animation duration in seconds." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  // From Forms2 (next 12)
  {
    id: "lamp-form",
    name: "The Noir Lamp",
    description: "Pull cord lamp form with dramatic lighting and noir aesthetics.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "lamp", "noir", "dramatic"],
    previewUrl: "/UIComponents/Forms/LampForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"The Investigation"', description: "Form title text." },
      { name: "fields", type: "Array<{ label: string; placeholder?: string }>", default: "[{ label: \"Suspect Name\", placeholder: \"\" }, { label: \"Last Seen Location\", placeholder: \"\" }]", description: "Array of form field objects with label and optional placeholder." },
      { name: "buttonText", type: "string", default: '"File Report"', description: "Submit button text." },
      { name: "instructionText", type: "string", default: '"PULL THE CORD"', description: "Instruction text for the lamp cord." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"28rem"', description: "Maximum form width." },
      { name: "darkBgColor", type: "string", default: '"#0a0a0a"', description: "Dark background color (when lamp is off)." },
      { name: "lightBgColor", type: "string", default: '"#f0e6d2"', description: "Light background color (when lamp is on)." },
      { name: "cordColor", type: "string", default: '"#1f2937"', description: "Lamp cord color." },
      { name: "pullColor", type: "string", default: '"#7f1d1d"', description: "Lamp pull color." },
      { name: "instructionTextColor", type: "string", default: '"rgba(255, 255, 255, 0.2)"', description: "Instruction text color (rgba)." },
      { name: "formBgColor", type: "string", default: '"#ffffff"', description: "Form background color." },
      { name: "formBorderColor", type: "string", default: '"#e5e7eb"', description: "Form border color." },
      { name: "titleColor", type: "string", default: '"#1f2937"', description: "Title text color." },
      { name: "titleBorderColor", type: "string", default: '"#1f2937"', description: "Title border color." },
      { name: "labelColor", type: "string", default: '"#6b7280"', description: "Label text color." },
      { name: "inputBgColor", type: "string", default: '"#f4f4f4"', description: "Input background color." },
      { name: "inputBorderColor", type: "string", default: '"#9ca3af"', description: "Input border color." },
      { name: "inputFocusBorderColor", type: "string", default: '"#ef4444"', description: "Input border color on focus." },
      { name: "buttonBgColor", type: "string", default: '"#1f2937"', description: "Button background color." },
      { name: "buttonHoverBgColor", type: "string", default: '"#374151"', description: "Button background color on hover." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "lightColor", type: "string", default: '"#f0e6d2"', description: "Lamp light color." },
      { name: "lightOpacity", type: "number", default: "0.9", description: "Lamp light opacity (0-1)." },
      { name: "dragThreshold", type: "number", default: "50", description: "Drag threshold in pixels to trigger lamp." },
      { name: "springStiffness", type: "number", default: "300", description: "Spring animation stiffness." },
      { name: "springDamping", type: "number", default: "30", description: "Spring animation damping." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "rocket-form",
    name: "Space Launch",
    description: "Space launch form with rocket animations and cosmic aesthetics.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "rocket", "space", "launch"],
    previewUrl: "/UIComponents/Forms/RocketForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Launch Control"', description: "Form title text." },
      { name: "missionPlaceholder", type: "string", default: '"MISSION NAME"', description: "Mission input placeholder." },
      { name: "emailPlaceholder", type: "string", default: '"COMMANDER EMAIL"', description: "Email input placeholder." },
      { name: "toggleLabels", type: "string[]", default: "[\"FUEL\", \"OXYGEN\", \"NAVI\"]", description: "Array of toggle switch labels." },
      { name: "buttonText", type: "string", default: '"Launch"', description: "Submit button text." },
      { name: "rocketEmoji", type: "string", default: '"🚀"', description: "Rocket emoji to display." },
      { name: "backgroundPattern", type: "string", default: '"https://www.transparenttextures.com/patterns/stardust.png"', description: "Background pattern image URL." },
      { name: "onSubmit", type: "(data: { mission: string; email: string; toggles: boolean[] }) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"28rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#1e293b"', description: "Background color (hex, rgb, or hsl)." },
      { name: "borderColor", type: "string", default: '"#334155"', description: "Border color (hex, rgb, or hsl)." },
      { name: "titleColor", type: "string", default: '"#ffffff"', description: "Title text color." },
      { name: "readyIndicatorColor", type: "string", default: '"#22c55e"', description: "Ready indicator color." },
      { name: "notReadyIndicatorColor", type: "string", default: '"#ef4444"', description: "Not ready indicator color." },
      { name: "inputBgColor", type: "string", default: '"#0f172a"', description: "Input background color." },
      { name: "inputBorderColor", type: "string", default: '"#475569"', description: "Input border color." },
      { name: "inputFocusBorderColor", type: "string", default: '"#22d3ee"', description: "Input border color on focus." },
      { name: "inputTextColor", type: "string", default: '"#22d3ee"', description: "Input text color." },
      { name: "toggleLabelColor", type: "string", default: '"#94a3b8"', description: "Toggle label text color." },
      { name: "toggleActiveBgColor", type: "string", default: '"#22c55e"', description: "Toggle background color when active." },
      { name: "toggleActiveBorderColor", type: "string", default: '"#16a34a"', description: "Toggle border color when active." },
      { name: "toggleInactiveBgColor", type: "string", default: '"#475569"', description: "Toggle background color when inactive." },
      { name: "toggleInactiveBorderColor", type: "string", default: '"#64748b"', description: "Toggle border color when inactive." },
      { name: "buttonReadyBgColor", type: "string", default: '"#22c55e"', description: "Button background color when ready." },
      { name: "buttonReadyTextColor", type: "string", default: '"#ffffff"', description: "Button text color when ready." },
      { name: "buttonReadyBorderColor", type: "string", default: '"#16a34a"', description: "Button border color when ready." },
      { name: "buttonNotReadyBgColor", type: "string", default: '"#475569"', description: "Button background color when not ready." },
      { name: "buttonNotReadyTextColor", type: "string", default: '"#94a3b8"', description: "Button text color when not ready." },
      { name: "buttonNotReadyBorderColor", type: "string", default: '"#64748b"', description: "Button border color when not ready." },
      { name: "launchDuration", type: "number", default: "2000", description: "Launch animation duration in milliseconds." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "flashlight-form",
    name: "Horror Flashlight",
    description: "Flashlight reveal form with horror aesthetics and spotlight effects.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "flashlight", "horror", "spotlight"],
    previewUrl: "/UIComponents/Forms/FlashlightForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Don\'t Scream."', description: "Form title text." },
      { name: "icon", type: "React.ReactNode", default: "<Ghost className=\"text-white w-8 h-8\" />", description: "Icon element to display." },
      { name: "fields", type: "Array<{ label: string; placeholder?: string }>", default: "[{ label: \"Your Fear\", placeholder: \"...\" }, { label: \"Last Words\", placeholder: \"...\" }]", description: "Array of form field objects with label and optional placeholder." },
      { name: "buttonText", type: "string", default: '"SUBMIT SOUL"', description: "Submit button text." },
      { name: "helpText", type: "string", default: '"HELP"', description: "Help text to display." },
      { name: "hiddenText", type: "string", default: '"I see you"', description: "Hidden text revealed by flashlight." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"500px"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#000000"', description: "Background color (hex, rgb, or hsl)." },
      { name: "revealedBgColor", type: "string", default: '"#0f172a"', description: "Revealed background color." },
      { name: "formBgColor", type: "string", default: '"#1e293b"', description: "Form background color." },
      { name: "formBorderColor", type: "string", default: '"#334155"', description: "Form border color." },
      { name: "titleColor", type: "string", default: '"#ffffff"', description: "Title text color." },
      { name: "labelColor", type: "string", default: '"#dc2626"', description: "Label text color." },
      { name: "inputBgColor", type: "string", default: '"#000000"', description: "Input background color." },
      { name: "inputBorderColor", type: "string", default: '"rgba(220, 38, 38, 0.5)"', description: "Input border color (rgba)." },
      { name: "inputFocusBorderColor", type: "string", default: '"#dc2626"', description: "Input border color on focus." },
      { name: "inputTextColor", type: "string", default: '"#d1d5db"', description: "Input text color." },
      { name: "buttonBgColor", type: "string", default: '"#991b1b"', description: "Button background color." },
      { name: "buttonHoverBgColor", type: "string", default: '"#b91c1c"', description: "Button background color on hover." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "helpTextColor", type: "string", default: '"#475569"', description: "Help text color." },
      { name: "hiddenTextColor", type: "string", default: '"#ffffff"', description: "Hidden text color." },
      { name: "spotlightSize", type: "string", default: '"300px"', description: "Spotlight effect size." },
      { name: "overlayColor", type: "string", default: '"rgba(0, 0, 0, 0.95)"', description: "Overlay color (rgba)." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "letter-form",
    name: "Love Letter",
    description: "Love letter form with romantic aesthetics and handwritten style.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "letter", "romantic", "handwritten"],
    previewUrl: "/UIComponents/Forms/LetterForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "greeting", type: "string", default: '"Dearest..."', description: "Letter greeting text." },
      { name: "placeholder", type: "string", default: '"Write your confession here..."', description: "Textarea placeholder text." },
      { name: "sealButtonText", type: "string", default: '"Seal Letter"', description: "Seal button text." },
      { name: "sealInitial", type: "string", default: '"W"', description: "Initial letter for the seal." },
      { name: "reopenText", type: "string", default: '"Click to reopen"', description: "Text displayed when letter is sealed." },
      { name: "onSubmit", type: "(content: string) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"32rem"', description: "Maximum form width." },
      { name: "height", type: "string", default: '"600px"', description: "Form height." },
      { name: "backgroundColor", type: "string", default: '"#3e2c2c"', description: "Background color (hex, rgb, or hsl)." },
      { name: "paperBgColor", type: "string", default: '"#fcf5e5"', description: "Paper background color." },
      { name: "paperLineColor", type: "string", default: '"#e5e5e5"', description: "Paper line color." },
      { name: "greetingColor", type: "string", default: '"#1f2937"', description: "Greeting text color." },
      { name: "textColor", type: "string", default: '"#374151"', description: "Text color." },
      { name: "sealButtonBgColor", type: "string", default: '"#991b1b"', description: "Seal button background color." },
      { name: "sealButtonHoverBgColor", type: "string", default: '"#7f1d1d"', description: "Seal button background color on hover." },
      { name: "sealButtonTextColor", type: "string", default: '"#fcf5e5"', description: "Seal button text color." },
      { name: "envelopeBgColor", type: "string", default: '"#eaddcf"', description: "Envelope background color." },
      { name: "envelopeBorderColor", type: "string", default: '"#eaddcf"', description: "Envelope border color." },
      { name: "sealBgColor", type: "string", default: '"#991b1b"', description: "Seal background color." },
      { name: "sealTextColor", type: "string", default: '"#eaddcf"', description: "Seal text color." },
      { name: "reopenTextColor", type: "string", default: '"rgba(255, 255, 255, 0.5)"', description: "Reopen text color (rgba)." },
      { name: "foldingDelay", type: "number", default: "1000", description: "Folding animation delay in milliseconds." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "vinyl-form",
    name: "Vinyl Player",
    description: "Vinyl record player form with turntable aesthetics and retro design.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "vinyl", "player", "retro"],
    previewUrl: "/UIComponents/Forms/VinylForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "placeholder", type: "string", default: '"Song Request?"', description: "Input placeholder text." },
      { name: "standbyText", type: "string", default: '"Standby"', description: "Standby status text." },
      { name: "recordingText", type: "string", default: '"Recording..."', description: "Recording status text." },
      { name: "onSubmit", type: "(value: string) => void", default: "undefined", description: "Form submission handler function." },
      { name: "width", type: "string", default: '"400px"', description: "Form width." },
      { name: "height", type: "string", default: '"400px"', description: "Form height." },
      { name: "backgroundColor", type: "string", default: '"#d35400"', description: "Background color (hex, rgb, or hsl)." },
      { name: "borderColor", type: "string", default: '"#a04000"', description: "Border color (hex, rgb, or hsl)." },
      { name: "vinylColor", type: "string", default: '"#000000"', description: "Vinyl record color." },
      { name: "centerColor", type: "string", default: '"#f1c40f"', description: "Vinyl center color." },
      { name: "centerTextColor", type: "string", default: '"#d35400"', description: "Center text color." },
      { name: "inputBorderColor", type: "string", default: '"#000000"', description: "Input border color." },
      { name: "statusIndicatorColor", type: "string", default: '"#ef4444"', description: "Status indicator color." },
      { name: "statusTextColor", type: "string", default: '"#ffffff"', description: "Status text color." },
      { name: "rotationDuration", type: "number", default: "2", description: "Vinyl rotation animation duration in seconds." },
      { name: "armInitialRotate", type: "number", default: "-30", description: "Initial arm rotation angle in degrees." },
      { name: "armActiveRotate", type: "number", default: "10", description: "Active arm rotation angle in degrees." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "passport-form",
    name: "Passport Stamp",
    description: "Passport stamp form with travel aesthetics and official design.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "passport", "stamp", "travel"],
    previewUrl: "/UIComponents/Forms/PassportForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "visaTitle", type: "string", default: '"VISA ENTRY"', description: "Visa title text." },
      { name: "visaClass", type: "string", default: '"Class A-1"', description: "Visa class text." },
      { name: "surnamePlaceholder", type: "string", default: '"SURNAME"', description: "Surname input placeholder." },
      { name: "passportPlaceholder", type: "string", default: '"PASSPORT NO."', description: "Passport number input placeholder." },
      { name: "buttonText", type: "string", default: '"SUBMIT"', description: "Submit button text." },
      { name: "stampText", type: "string", default: '"APPROVED"', description: "Stamp text." },
      { name: "instructionText", type: "string", default: '"Click anywhere to STAMP approval"', description: "Instruction text." },
      { name: "icon", type: "React.ReactNode", default: "<Plane size={48} />", description: "Icon element to display." },
      { name: "stampCursor", type: "string", default: '"https://cdn-icons-png.flaticon.com/512/5696/5696473.png"', description: "Stamp cursor image URL." },
      { name: "onSubmit", type: "(data: { surname: string; passportNo: string }) => void", default: "undefined", description: "Form submission handler function." },
      { name: "onStamp", type: "(position: { x: number; y: number }) => void", default: "undefined", description: "Stamp click handler function." },
      { name: "maxWidth", type: "string", default: '"28rem"', description: "Maximum form width." },
      { name: "minHeight", type: "string", default: '"500px"', description: "Minimum form height." },
      { name: "backgroundColor", type: "string", default: '"#2c3e50"', description: "Background color (hex, rgb, or hsl)." },
      { name: "pageBgColor", type: "string", default: '"#ecf0f1"', description: "Page background color." },
      { name: "borderColor", type: "string", default: '"#9ca3af"', description: "Border color (hex, rgb, or hsl)." },
      { name: "spineBgColor", type: "string", default: '"#34495e"', description: "Spine background color." },
      { name: "spineBorderColor", type: "string", default: '"#2c3e50"', description: "Spine border color." },
      { name: "iconColor", type: "string", default: '"#3498db"', description: "Icon color." },
      { name: "visaTitleColor", type: "string", default: '"#2c3e50"', description: "Visa title text color." },
      { name: "visaClassColor", type: "string", default: '"#7f8c8d"', description: "Visa class text color." },
      { name: "inputBorderColor", type: "string", default: '"#bdc3c7"', description: "Input border color." },
      { name: "inputPlaceholderColor", type: "string", default: '"#95a5a6"', description: "Input placeholder color." },
      { name: "buttonBgColor", type: "string", default: '"#2c3e50"', description: "Button background color." },
      { name: "buttonHoverBgColor", type: "string", default: '"#34495e"', description: "Button background color on hover." },
      { name: "buttonTextColor", type: "string", default: '"#ffffff"', description: "Button text color." },
      { name: "instructionTextColor", type: "string", default: '"#7f8c8d"', description: "Instruction text color." },
      { name: "stampBorderColor", type: "string", default: '"#e74c3c"', description: "Stamp border color." },
      { name: "stampTextColor", type: "string", default: '"#e74c3c"', description: "Stamp text color." },
      { name: "patternColor", type: "string", default: '"rgba(44, 62, 80, 0.1)"', description: "Pattern color (rgba)." },
      { name: "patternSize", type: "string", default: '"20px"', description: "Pattern size." },
      { name: "minSurnameLength", type: "number", default: "3", description: "Minimum surname length for validation." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "chat-form",
    name: "Chat Buddy",
    description: "Chat interface form with conversational UI and messaging aesthetics.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "chat", "conversational", "messaging"],
    previewUrl: "/UIComponents/Forms/ChatForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "botName", type: "string", default: '"FormBot 3000"', description: "Bot name displayed in header." },
      { name: "botStatus", type: "string", default: '"Online"', description: "Bot status text." },
      { name: "initialMessage", type: "string", default: '"Hey! What\'s your name?"', description: "Initial bot message." },
      { name: "botAvatarColor", type: "string", default: '"#4ade80"', description: "Bot avatar color." },
      { name: "inputPlaceholder", type: "string", default: '"Type here..."', description: "Input placeholder text." },
      { name: "sendIcon", type: "React.ReactNode", default: "<Send size={16} />", description: "Send button icon element." },
      { name: "onSubmit", type: "(data: Record<string, string>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"24rem"', description: "Maximum form width." },
      { name: "height", type: "string", default: '"500px"', description: "Form height." },
      { name: "backgroundColor", type: "string", default: '"#eef2ff"', description: "Background color (hex, rgb, or hsl)." },
      { name: "cardBgColor", type: "string", default: '"#ffffff"', description: "Card background color." },
      { name: "headerBgColor", type: "string", default: '"#4f46e5"', description: "Header background color." },
      { name: "headerTextColor", type: "string", default: '"#ffffff"', description: "Header text color." },
      { name: "botAvatarBgColor", type: "string", default: '"#4ade80"', description: "Bot avatar background color." },
      { name: "botAvatarBorderColor", type: "string", default: '"#ffffff"', description: "Bot avatar border color." },
      { name: "messagesBgColor", type: "string", default: '"#f9fafb"', description: "Messages area background color." },
      { name: "botMessageBgColor", type: "string", default: '"#ffffff"', description: "Bot message background color." },
      { name: "botMessageTextColor", type: "string", default: '"#1f2937"', description: "Bot message text color." },
      { name: "userMessageBgColor", type: "string", default: '"#4f46e5"', description: "User message background color." },
      { name: "userMessageTextColor", type: "string", default: '"#ffffff"', description: "User message text color." },
      { name: "inputBgColor", type: "string", default: '"#ffffff"', description: "Input background color." },
      { name: "inputFocusRingColor", type: "string", default: '"#4f46e5"', description: "Input focus ring color." },
      { name: "buttonBgColor", type: "string", default: '"#4f46e5"', description: "Button background color." },
      { name: "buttonHoverScale", type: "number", default: "1.1", description: "Button scale on hover." },
      { name: "buttonIconColor", type: "string", default: '"#ffffff"', description: "Button icon color." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
  {
    id: "slider-form",
    name: "Slider Mixer",
    description: "Slider mixer form with audio control aesthetics and interactive sliders.",
        category: "UI Components",
        installType: "cli",
        tags: ["form", "slider", "mixer", "audio"],
    previewUrl: "/UIComponents/Forms/SliderForm",
    code: {
      tsx: "",
    },
    usageCode: {
      tsx: "",
    },
    dependencies: ["next", "framer-motion"],
    props: [
      { name: "title", type: "string", default: '"Audio Input Module"', description: "Form title text." },
      { name: "labels", type: "string[]", default: "[\"Vol\", \"Bass\", \"Treb\", \"Mid\"]", description: "Array of slider labels." },
      { name: "onSubmit", type: "(values: Record<string, number>) => void", default: "undefined", description: "Form submission handler function." },
      { name: "maxWidth", type: "string", default: '"32rem"', description: "Maximum form width." },
      { name: "backgroundColor", type: "string", default: '"#2a2a2a"', description: "Background color (hex, rgb, or hsl)." },
      { name: "borderColor", type: "string", default: '"rgba(255, 255, 255, 0.1)"', description: "Border color (rgba)." },
      { name: "titleColor", type: "string", default: '"#9ca3af"', description: "Title text color." },
      { name: "indicatorColor", type: "string", default: '"#ef4444"', description: "Indicator color." },
      { name: "sliderBgColor", type: "string", default: '"#1a1a1a"', description: "Slider background color." },
      { name: "sliderTrackColor", type: "string", default: '"#333333"', description: "Slider track color." },
      { name: "sliderHandleColor", type: "string", default: '"#374151"', description: "Slider handle color." },
      { name: "sliderHandleBorderColor", type: "string", default: '"rgba(255, 255, 255, 0.2)"', description: "Slider handle border color (rgba)." },
      { name: "labelColor", type: "string", default: '"#6b7280"', description: "Label text color." },
      { name: "visualizerBgColor", type: "string", default: '"rgba(0, 0, 0, 0.5)"', description: "Visualizer background color (rgba)." },
      { name: "visualizerBarColor", type: "string", default: '"#22c55e"', description: "Visualizer bar color." },
      { name: "visualizerBarCount", type: "number", default: "20", description: "Number of visualizer bars." },
      { name: "sliderHeight", type: "string", default: '"16rem"', description: "Slider height." },
      { name: "sliderWidth", type: "string", default: '"4rem"', description: "Slider width." },
      { name: "dragConstraints", type: "{ top: number; bottom: number }", default: "{ top: 0, bottom: 180 }", description: "Drag constraints object for sliders." },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes." },
    ],
  },
];
