import { getCode } from "../getCode";
import { Component } from "../types";

export const backgroundComponents: Component[] = [
    {
        id: "interstellar-fluid-hero",
        name: "Interstellar Fluid Hero",
        description: "Interactive fluid simulation creating cosmic nebula effects with mouse interaction. Deep space aesthetic with animated gas clouds and star trails.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "interstellar", "fluid", "nebula", "space", "interactive", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/InterstellarFluidHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/InterstellarFluidHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/InterstellarFluidHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/InterstellarFluidHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [
            { name: "baseColor", type: "[number, number, number]", default: "[0.05, 0.05, 0.2]", description: "RGB array 0-1 for base color (Deep Space Blue)." },
            { name: "glowColor", type: "[number, number, number]", default: "[0.8, 0.4, 1.0]", description: "RGB array 0-1 for glow color (Nebula Violet)." },
            { name: "dissipation", type: "number", default: "0.97", description: "How fast the gas fades (0.95 - 0.99)." },
            { name: "velocityDissipation", type: "number", default: "0.98", description: "How fast movement stops." },
            { name: "interactive", type: "boolean", default: "true", description: "Enable mouse interaction." },
        ],
        whenToUse: "This production-ready React UI component is perfect for deep space-themed landing pages, sci-fi portfolios, and immersive hero sections. Use this interactive fluid simulation to create a moving, 'cosmic nebula' effect that responds to every mouse movement, giving your Next.js site a high-end, cinematic feel.",
        bestPractices: "Maintain consistent spacing within your design system by using this as a full-viewport hero background. Follow React best practices by setting a lower `dissipation` value for a more persistent cloud effect. Optimize for performance in large-scale applications by enabling mouse interaction only on desktop devices.",
        whyMatters: "Fluid simulations are a hallmark of premium modern frontend development. This customizable UI component helps you build a real-world application architecture that feels atmospheric and technically superior, improving user engagement and retention.",
        faqs: [
            { question: "Is it heavy on the GPU?", answer: "This component is built with OGL (a lightweight WebGL library) and is highly optimized for performance, though it's best to test on lower-end devices." },
            { question: "Can I change the nebula colors?", answer: "Yes, you can fully customize the `baseColor` and `glowColor` using RGB arrays (0 to 1) to match your brand's palette." },
            { question: "Does it work as a static background?", answer: "While intended to be dynamic, you can disable `interactive` to create a steady, hypnotic drift that adds texture without direct user control." }
        ],
    },
    {
        id: "interstellar-background-hero",
        name: "Interstellar Background Hero",
        description: "Warp tunnel effect simulating high-velocity travel through nebular clusters. Procedural WebGL engine with mouse-responsive space distortion.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "interstellar", "warp", "tunnel", "space", "procedural", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/InterstellarBackgroundHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/InterstellarBackgroundHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/InterstellarBackgroundHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/InterstellarBackgroundHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [
            { name: "baseColor", type: "[number, number, number]", default: "[0.1, 0.4, 0.9]", description: "RGB 0-1 for base color (Deep Electric Blue)." },
            { name: "speed", type: "number", default: "1.0", description: "Animation speed (0.0 - 5.0)." },
            { name: "density", type: "number", default: "1.2", description: "Nebula density (0.5 - 2.0)." },
            { name: "brightness", type: "number", default: "1.0", description: "Overall brightness (0.0 - 2.0)." },
            { name: "interactive", type: "boolean", default: "true", description: "Enable mouse interaction." },
        ],
        whenToUse: "Ideal for high-velocity intro sequences, portal effects, and experimental Next.js landing pages. Use this React component to create a procedural warp tunnel that mimics traveling through hyperspace, perfect for storytelling and sci-fi aesthetic applications.",
        bestPractices: "Follow React best practices by tuning the `speed` and `density` to match the energy of your content. Maintain scalable component architecture by using this as a thematic transition background. Optimize for performance by using the `brightness` prop to ensure readability of foreground text.",
        whyMatters: "Procedural WebGL backgrounds add a layer of complexity and polish that static images can't match. This reusable React component gives your project semantic authority and a premium edge in the competitive digital landscape.",
        faqs: [
            { question: "Can I adjust the tunnel speed?", answer: "Yes, the `speed` prop allows you to range from a slow, drifting nebula to a high-speed warp tunnel effect." },
            { question: "What is the 'density' prop for?", answer: "It controls how thick the gas clouds and star clusters appear within the tunnel simulation." },
            { question: "Is the space distortion interactive?", answer: "Yes, when `interactive` is true, the tunnel perspective shifts slightly in response to mouse movement for added depth." }
        ],
    },
    {
        id: "liquid-chrome-hero",
        name: "Liquid Chrome Hero",
        description: "Procedural simulation of molten chrome alloys with velocity-based distortion. Interactive liquid metal surface with specular highlights.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "liquid", "chrome", "metal", "interactive", "webgl", "procedural"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/LiquidChromeHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/LiquidChromeHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/LiquidChromeHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/LiquidChromeHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [
            { name: "baseColor", type: "[number, number, number]", default: "[0.5, 0.5, 0.5]", description: "RGB array for base chrome color (neutral silver)." },
            { name: "speed", type: "number", default: "1.0", description: "Animation speed." },
            { name: "amplitude", type: "number", default: "0.6", description: "Distortion amplitude." },
            { name: "interactive", type: "boolean", default: "true", description: "Enable mouse interaction." },
        ],
        whenToUse: "Perfect for luxury tech brands, modern agency portfolios, and product reveals that want a tactile, high-end look. Use this React component to simulate molten chrome or liquid mercury surfaces that 'melt' and distort as the user interacts with them.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring high-contrast foreground elements. Follow React best practices by using a neutral `baseColor` to keep the chrome look authentic. Optimize for performance in large-scale applications by keeping the `amplitude` subtle for a more realistic metal feel.",
        whyMatters: "Specular highlights and liquid metal simulations are trending in high-performance modern UI development. This production-ready component helps you build an interface that feels heavy, expensive, and technically advanced.",
        faqs: [
            { question: "Can I use colors other than silver?", answer: "Absolutely! By changing the `baseColor`, you can create liquid gold, molten copper, or even neon fluid metal effects." },
            { question: "How does the distortion work?", answer: "The component uses a procedural displacement map that is affected by both time (speed) and mouse velocity (interactivity)." },
            { question: "Is it mobile responsive?", answer: "Yes, the WebGL canvas scales to fill its container, ensuring a consistent liquid metal experience on all devices." }
        ],
    },
    {
        id: "ameoba-cyber-hero",
        name: "Ameoba Cyber Hero",
        description: "Soft matte fluid motion background with subtle mouse lens effects. Modern Swiss-style aesthetic with frosted grain texture.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "ameoba", "cyber", "fluid", "matte", "minimal", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/AmeobaCyberHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/AmeobaCyberHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/AmeobaCyberHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/AmeobaCyberHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Excellent for minimalist portfolios, modern lifestyle brands, and Next.js applications that prioritize a 'matte' and soft aesthetic. Use this React component for a Swiss-style background that combines frosted grain with organic fluid motion.",
        bestPractices: "Maintain scalable component architecture by keeping foreground text large and bold. Follow React best practices by pairing this background with clean typography. Optimize for performance by utilizing the built-in frosted grain texture which adds detail without heavy GPU overhead.",
        whyMatters: "Soft, organic motion is a key element of 'calm' modern frontend development. This customizable UI component provides a sophisticated way to add movement without being distracting, perfect for professional real-world application architecture.",
        faqs: [
            { question: "Can I change the 'organic' shapes?", answer: "The shapes are procedurally generated; you can adjust the underlying shader parameters to change the 'fluidity' of the amoebas." },
            { question: "Does it support different grains?", answer: "The component comes with a high-quality frosted grain texture optimized for the matte cyber aesthetic." },
            { question: "Is this suitable for content-heavy pages?", answer: "Yes, its subtle nature makes it one of the best choices for backgrounds where readability is the top priority." }
        ],
    },
    {
        id: "glass-biology-hero",
        name: "Glass Biology Hero",
        description: "Biological cell pattern with Voronoi diagrams creating radioactive glass-like textures. Interactive pressure field with toxic neon colors.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "glass", "biology", "voronoi", "neon", "toxic", "interactive", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/GlassBiologyHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/GlassBiologyHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/GlassBiologyHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/GlassBiologyHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Ideal for bio-tech landing pages, experimental labs, and Next.js sites that want a toxic, neon, or structured organic feel. Use this React component for a 'cellular' pattern based on Voronoi diagrams that reacts like radioactive glass.",
        bestPractices: "Maintain consistent spacing within your design system by using the Voronoi cells as a grid-like layout hint. Follow React best practices by keeping the neon colors high-contrast. Optimize for performance in large-scale applications by being mindful of the pressure field calculations.",
        whyMatters: "Structured organic patterns like Voronoi diagrams are powerful tools for visual storytelling in science and tech sectors. This production-ready component adds a layer of 'biological' polish and semantic authority to your project's digital architecture.",
        faqs: [
            { question: "What is a Voronoi diagram?", answer: "It's a mathematical way of dividing space into regions based on proximity to points, creating a natural, cell-like structure." },
            { question: "Can I change the neon colors?", answer: "Yes, the shader supports custom color mapping to range from toxic greens to bioluminescent blues." },
            { question: "How does the 'pressure' interaction work?", answer: "As you move the mouse, the cells 'compress' and 'glow' as if being pressed against a glass surface." }
        ],
    },
    {
        id: "brutalist-hero",
        name: "Brutalist Hero",
        description: "Neo-brutalist text pattern with safety yellow and black color scheme. Interactive shockwave distortion with chromatic aberration effects.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "brutalist", "text", "yellow", "interactive", "webgl", "distortion"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/BrutalistHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/BrutalistHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/BrutalistHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/BrutalistHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Perfect for street-wear brands, 'raw' agency sites, and neo-brutalist Next.js portfolios. Use this React component for a high-impact, distorted text pattern that screams for attention with its safety yellow and black color scheme.",
        bestPractices: "Follow React best practices by using short, punchy words for the text pattern. Maintain scalable component architecture by pairing this with other brutalist UI elements like thick borders and sharp shadows. Optimize for performance by using the chromatic aberration effect sparingly.",
        whyMatters: "Brutalism is a bold choice that signals confidence and a 'no-nonsense' attitude. This customizable UI component gives you a production-level tool for building aggressive, memorable real-world application architecture.",
        faqs: [
            { question: "Can I change the colors?", answer: "While designed for the yellow/black aesthetic, you can easily tweak the shader constants to any high-contrast pair." },
            { question: "How do I change the text?", answer: "The text pattern is generated from a texture; the component can be extended to support custom strings for a truly branded look." },
            { question: "What is chromatic aberration?", answer: "It's a visual effect that separates colors at the edges of shapes, creating a 'glitchy' or lens-distortion feel." }
        ],
    },
    {
        id: "hacker-mode-hero",
        name: "Hacker Mode Hero",
        description: "Matrix-style terminal grid with animated characters and glitch effects. Cyberpunk aesthetic with interactive text rendering.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "hacker", "terminal", "matrix", "cyberpunk", "glitch", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/HackerModeHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/HackerModeHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/HackerModeHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/HackerModeHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Excellent for developer tools, cybersecurity sites, and 'dark web' themed Next.js applications. Use this React component for a Matrix-style falling code effect that feels modern and high-tech with its interactive glitch layers.",
        bestPractices: "Maintain consistent spacing within your design system by using this as a backdrop for code blocks or terminal-style interfaces. Follow React best practices by using monospace fonts for any overlapping text. Optimize for performance in large-scale applications by managing the character drop density.",
        whyMatters: "The 'hacker terminal' is an iconic UI archetype. This reusable React component provides a hardware-accelerated version of this aesthetic, adding a layer of technical polish and 'leet' energy to your project's digital architecture.",
        faqs: [
            { question: "Can I add my own characters?", answer: "Yes, the character set used for the 'falling' effect can be fully customized to include symbols, alphabets, or even binary." },
            { question: "Does it react to the mouse?", answer: "Yes, the component includes 'glitch' triggers and character displacements that occur when the mouse passes over-head." },
            { question: "Is it readable as a background?", answer: "The falling code is designed to be subtle and atmospheric, making it much better for backgrounds than standard static Matrix clones." }
        ],
    },
    {
        id: "raw-sketch-hero",
        name: "Raw Sketch Hero",
        description: "Hand-drawn sketch aesthetic with velocity-based grain and distortion. Raw artistic texture with organic movement.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "sketch", "raw", "artistic", "grain", "organic", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/RawSketchHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/RawSketchHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/RawSketchHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/RawSketchHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Ideal for artistic portfolios, high-end branding, and Next.js sites that want a 'hand-drawn' or raw aesthetic. Use this React component for a sketch-like background with velocity-based grain and organic movement that feels human and unique.",
        bestPractices: "Maintain consistent spacing within your design system by using this as a subtle texture rather than a loud background. Follow React best practices by pairing it with simple, high-contrast UI elements. Optimize for performance by adjusting the grain density for different screen sizes.",
        whyMatters: "The quest for 'authenticity' in digital design often leads back to organic, raw textures. This customizable UI component helpsคุณ build an interface that feels less like a machine and more like a craft, adding semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Is the 'grain' interactive?", answer: "Yes, the intensity of the sketch grain shifts based on scroll and mouse velocity, creating a dynamic 'shaky' hand-drawn feel." },
            { question: "Can I change the ink color?", answer: "The shader supports color overrides, allowing you to switch from classic charcoal black to blueprint blue or sepia." },
            { question: "Does it work well with full-screen images?", answer: "It works best as a standalone texture or as an overlay to give images a 'sketched' over-layer." }
        ],
    },
    {
        id: "fluid-dynamics-hero",
        name: "Fluid Dynamics Hero",
        description: "Advanced fluid simulation with image distortion and velocity-based effects. Realistic liquid motion with interactive mouse response.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "fluid", "dynamics", "simulation", "liquid", "interactive", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/FluidDynamicsHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/FluidDynamicsHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/FluidDynamicsHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/FluidDynamicsHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Perfect for creative studios, high-performance SaaS landing pages, and Next.js applications that want to emphasize motion and fluidity. Use this React component for a realistic liquid simulation that distorts everything in its path with smooth, velocity-based math.",
        bestPractices: "Optimize for performance in large-scale applications by limiting the number of active fluid particles. Follow React best practices by setting a `drag` value that makes the interaction feel viscous and expensive. Maintain scalable component architecture by using this as a focal point for your hero section.",
        whyMatters: "High-fidelity fluid dynamics are the pinnacle of interactive modern frontend development. This production-ready component provides a robust implementation of complex physics, giving your project a layer of polish that is rarely seen in standard web apps.",
        faqs: [
            { question: "How realistic is the simulation?", answer: "It uses Navier-Stokes equations for real-time fluid dynamics, providing one of the most realistic liquid experiences possible in a browser." },
            { question: "Can I use an image background?", answer: "Yes, the fluid simulation can act as a distortion layer on top of any background image, creating 'ripples' as the mouse moves." },
            { question: "Is it mobile-friendly?", answer: "The component is optimized for WebGL, but we recommend lowering the simulation resolution on mobile for the smoothest experience." }
        ],
    },
    {
        id: "image-distortion-hero",
        name: "Image Distortion Hero",
        description: "Dynamic image distortion with noise-based warping effects. Interactive visual manipulation with procedural texture generation.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "image", "distortion", "warp", "noise", "interactive", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/ImageDistortionHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/ImageDistortionHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/ImageDistortionHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/ImageDistortionHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Excellent for tech-forward brand reveals, experimental landing pages, and Next.js sites that want a 'glitchy' or noise-based aesthetic. Use this React component for dynamic image warping that evolves procedurally and responds to user interaction.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the distorted images don't break the container boundaries. Follow React best practices by using high-resolution base images. Optimize for performance by choosing an efficient noise function (like Simplex or Perlin) for the warping logic.",
        whyMatters: "Visual distortion adds a sense of 'digital life' to an interface. This customizable UI component gives you a production-level tool for building high-energy, memorable real-world application architecture that feels intentional and technical.",
        faqs: [
            { question: "Can I control the warp intensity?", answer: "Yes, the shader constants allow you to fine-tune how much the image bends and stretches in response to the noise field." },
            { question: "What kind of noise does it use?", answer: "It primarily uses procedural noise to create 'waves' of distortion that feel more organic than standard pixel glitching." },
            { question: "Does it support hover effects?", answer: "The distortion is always active but can be amplified in the area surrounding the user's cursor." }
        ],
    },
    {
        id: "dark-gradient-hero",
        name: "Dark Gradient Hero",
        description: "Smooth dark gradient background with animated color transitions. Minimalist aesthetic with subtle motion effects.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "dark", "gradient", "minimal", "smooth", "animated", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/DarkGradientHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/DarkGradientHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/DarkGradientHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/DarkGradientHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Ideal for minimalist dashboards, luxury startup landing pages, and Next.js applications that need a smooth, animated color transition. Use this React component for a deep, high-contrast gradient that adds texture and depth without overwhelming the user.",
        bestPractices: "Follow React best practices by selecting two or three complementary dark colors. Maintain scalable component architecture by using this as a root-level background. Optimize for performance in large-scale applications by using slow, hardware-accelerated color shift animations.",
        whyMatters: "Gradients are a staple of modern frontend development, but dynamic gradients add an extra layer of sophistication. This production-ready component helpsคุณ build an interface that feels calm and premium, improving the overall aesthetic authority of your project.",
        faqs: [
            { question: "Is it just a CSS gradient?", answer: "While it looks like one, it uses a custom shader for much smoother color blending and animated 'swirls' than pure CSS allow." },
            { question: "Can I make it brighter?", answer: "Yes, the color array is fully customizable, allowing you to transition from deep blacks to vibrant neon headers if desired." },
            { question: "Does it cause color banding?", answer: "We include a subtle noise/dither layer to prevent banding, ensuring smooth transitions even on lower-quality displays." }
        ],
    },
    {
        id: "webgl-hero",
        name: "WebGL Hero",
        description: "Generic WebGL background with customizable shader effects. Flexible foundation for custom visual effects.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "webgl", "shader", "customizable", "flexible"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/WebglHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/WebglHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/WebglHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/WebglHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "The perfect 'blank canvas' for creative developers using Next.js. Use this React component as a robust shell for your custom GLSL shaders, providing a pre-configured OGL environment for building unique visual effects.",
        bestPractices: "Maintain scalable component architecture by keeping your shader logic modular. Follow React best practices by managing the WebGL context lifecycle properly. Optimize for performance by using efficient attribute and uniform updates within the render loop.",
        whyMatters: "WebGL is the future of high-impact web design. Having a reliable 'hero' shell allows you to focus on the creative visuals without worrying about the boilerplate of setting up a high-performance rendering engine.",
        faqs: [
            { question: "Can I use my own .vert and .frag shaders?", answer: "Absolutely! This component is designed to be the foundation for any custom shader code you want to implement." },
            { question: "Does it come with any presets?", answer: "It includes a default animated noise shader so you can see it working immediately after installation." },
            { question: "Is it compatible with Three.js?", answer: "This specific component uses OGL for its lightweight footprint, but the concepts are easily transferable to other WebGL libraries." }
        ],
    },
    {
        id: "rain-storm-hero",
        name: "Rain Storm Hero",
        description: "Atmospheric rain and storm simulation with particle effects. Dynamic weather visualization with realistic precipitation.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "rain", "storm", "weather", "particles", "atmospheric", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/RainStormHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/RainStormHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/RainStormHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/RainStormHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Excellent for atmospheric storytelling, music-related landing pages, and Next.js sites that want a 'moody' or weather-inspired look. Use this React component for a realistic rain and storm simulation that adds movement and texture to your background.",
        bestPractices: "Follow React best practices by pairing this with dark, immersive color palettes. Maintain consistent spacing within your design system by keeping foreground elements clear of particle clutter. Optimize for performance in large-scale applications by adjusting the droplet count for mobile devices.",
        whyMatters: "Weather effects create an immediate emotional connection with the user. This customizable UI component gives you a production-level tool for building immersive real-world application architecture that feels atmospheric and 'alive'.",
        faqs: [
            { question: "Can I adjust the rain intensity?", answer: "Yes, you can control the number of droplets and their fall speed to create everything from a light drizzle to a heavy storm." },
            { question: "Does it include lightning effects?", answer: "The shader supports screen flashes to simulate lightning, which can be synced to audio or timed randomly." },
            { question: "Is the rain interactive?", answer: "The droplets react subtly to mouse movement, creating wind-like shifts in the precipitation pattern." }
        ],
    },
    {
        id: "holographic-grid-hero",
        name: "Holographic Grid Hero",
        description: "Futuristic holographic grid pattern with 3D depth and neon glow. Sci-fi aesthetic with animated grid lines.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "holographic", "grid", "futuristic", "neon", "sci-fi", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/HolographicGridHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/HolographicGridHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/HolographicGridHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/HolographicGridHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Perfect for sci-fi brands, cybersecurity dashboards, and futuristic Next.js landing pages. Use this React component for a 3D grid with neon glows and depth effects that move as the user explores the page.",
        bestPractices: "Maintain scalable component architecture by using this as a background for data visualizations or complex charts. Follow React best practices by setting clear neon colors that match your brand. Optimize for performance by using efficient line rendering for the grid structure.",
        whyMatters: "Holographic visuals are a recurring trend in high-tech modern frontend development. This reusable React component helpsคุณ build an interface that feels like a 'heads-up display' (HUD), adding scale and semantic authority to your project.",
        faqs: [
            { question: "Is the grid 3D?", answer: "Yes, it uses a perspective matrix to create a 3D floor and ceiling effect that 'tilts' with mouse movement." },
            { question: "Can I change the grid spacing?", answer: "Yes, you can define how dense the grid lines are to achieve a more tight, technical look or a wide, expansive feel." },
            { question: "Does it support neon pulsing?", answer: "The grid lines have a built-in 'glow' factor that can be animated for a pulsing 'energy' effect." }
        ],
    },
    {
        id: "retro-grid-hero",
        name: "Retro Grid Hero",
        description: "Nostalgic retro grid pattern with vintage aesthetic. Classic 80s-inspired visual style with animated grid effects.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "retro", "grid", "vintage", "80s", "classic", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/RetroGridHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/RetroGridHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/RetroGridHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/RetroGridHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Ideal for retro gaming, 80s-inspired brands, and nostalgic Next.js portfolios. Use this React component for a classic synthwave grid that scrolls infinitely, perfect for hero sections with a 'retro-future' aesthetic.",
        bestPractices: "Maintain consistent spacing within your design system by pairing this with bold, neon typography. Follow React best practices by ensuring the 'horizon' line doesn't cut off important text. Optimize for performance by using hardware-accelerated Y-axis scrolling for the grid.",
        whyMatters: "The retro-grid is an iconic visual style that immediately communicates a specific 'vibe'. This production-ready component gives you a polished version of this classic design, helping you build memorable and high-impact real-world application architecture.",
        faqs: [
            { question: "Can I tilt the grid?", answer: "Yes, the 'pitch' and 'roll' of the grid can be customized to create different perspectives on the infinite plane." },
            { question: "How do I change the speed?", answer: "The scroll speed is fully adjustable, allowing for a slow, hypnotic drift or a fast, energetic movement." },
            { question: "Is the sun effect included?", answer: "While this component focuses on the grid, it's designed to be easily paired with our 'Retro Sun' or other specialty elements." }
        ],
    },
    {
        id: "grid-distortion-hero",
        name: "Grid Distortion Hero",
        description: "Interactive grid with dynamic distortion effects. Mouse-responsive grid warping with smooth transitions.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "grid", "distortion", "interactive", "warp", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/GridDistortionHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/GridDistortionHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/GridDistortionHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/GridDistortionHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Excellent for interactive portfolios and Next.js sites that want to emphasize user agency. Use this React component for a mouse-responsive grid that 'warps' as the user moves their cursor, creating a tactile sense of interaction.",
        bestPractices: "Maintain consistent spacing within your design system by keeping the grid lines subtle. Follow React best practices by setting a smooth transition for the warping effect. Optimize for performance in large-scale applications by using hardware-accelerated transforms.",
        whyMatters: "Interactive grid distortion is a signature of high-end modern UI design. This production-ready component helpsคุณ build an interface that feels responsive and alive, adding visual depth and semantic authority to your project.",
        faqs: [
            { question: "Can I change the grid color?", answer: "Yes, you can fully customize the grid line colors to match your brand's palette." },
            { question: "How intense is the distortion?", answer: "The distortion intensity is fully adjustable, allowing you to create everything from a subtle wave to an extreme warp." },
            { question: "Does it support touch interaction?", answer: "Yes, the warping effect is mapped to touch-move events on mobile devices for a consistent experience." }
        ],
    },
    {
        id: "dark-matter-hero",
        name: "Dark Matter Hero",
        description: "Cosmic dark matter visualization with mysterious particle effects. Deep space aesthetic with ethereal glow.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "dark", "matter", "cosmic", "space", "particles", "ethereal", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/DarkMatterHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/DarkMatterHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/DarkMatterHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/DarkMatterHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Perfect for space-themed landing pages, sci-fi portfolios, and Next.js experiences that want a mysterious, ethereal feel. Use this React component for a cosmic dark matter visualization with soft particle glows and deep depth.",
        bestPractices: "Follow React best practices by pairing this with dark, high-contrast typography. Maintain scalable component architecture by using this as a thematic backdrop for specific narrative sections. Optimize for performance by managing the particle count for mobile users.",
        whyMatters: "Cosmic visuals create a sense of scale and wonder. This customizable UI component gives you a production-level tool for building immersive real-world application architecture that feels atmospheric and advanced.",
        faqs: [
            { question: "Can I change the particle colors?", answer: "Yes, the particle system supports custom color mappings for its ethereal glow." },
            { question: "How does the 'matter' move?", answer: "The particles follow a procedural noise field that creates a slow, drifting, and mysterious motion." },
            { question: "Is it suitable for hero sections?", answer: "Absolutely, its deep perspective and soft lighting make it one of the most popular choices for high-impact hero backgrounds." }
        ],
    },
    {
        id: "terminal-hero",
        name: "Terminal Hero",
        description: "Command-line terminal aesthetic with animated text and code effects. Developer-focused background with monospace typography.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "terminal", "code", "developer", "monospace", "text", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/TerminalHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/TerminalHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/TerminalHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/TerminalHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Ideal for developer-facing tools, coding blogs, and tech-focused Next.js applications. Use this React component for a 'terminal' aesthetic with animated code snippets and monospace typography that feels authentically technical.",
        bestPractices: "Maintain consistent spacing within your design system by using this as a background for documentation or code sections. Follow React best practices by using high-contrast colors for readability. Optimize for performance in large-scale applications by limiting the number of simultaneous text animations.",
        whyMatters: "Terminal aesthetics are a powerful way to communicate technical authority. This reusable React component provides a hardware-accelerated version of this classic design, adding a layer of polish and 'developer' energy to your project.",
        faqs: [
            { question: "Can I use my own code snippets?", answer: "Yes, the component can be configured to display custom text or code arrays as its falling 'blocks'." },
            { question: "Does it support syntax highlighting?", answer: "The background is primarily atmospheric, but base colors can be adjusted to match common syntax themes like Monokai or Dracula." },
            { question: "Is it readable?", answer: "It's designed as an atmospheric background, so the 'falling' text is kept at a low opacity to ensure foreground content remains the priority." }
        ],
    },
    {
        id: "liquid-reality-hero",
        name: "Liquid Reality Hero",
        description: "Surreal liquid reality effect with morphing shapes and color transitions. Abstract visual experience with fluid motion.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "liquid", "reality", "surreal", "morphing", "abstract", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/LiquidRealityHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/LiquidRealityHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/LiquidRealityHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/LiquidRealityHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Excellent for abstract portfolios, creative branding, and Next.js storytelling. Use this React component for a surreal, 'liquid' experience that morphs shapes and colors in a hypnotic, non-linear way.",
        bestPractices: "Maintain scalable component architecture by using this as a background for artistic or conceptual content. Follow React best practices by pairing it with clean, simple foreground elements. Optimize for performance by utilizing efficient shader-based morphing transitions.",
        whyMatters: "Abstract fluid visuals are a trend in premium modern frontend development. This customizable UI component helpsคุณ build an interface that feels experimental and artistic, adding a unique visual signature to your project.",
        faqs: [
            { question: "How fast does it morph?", answer: "The morphing speed is fully adjustable, from a slow, relaxing drift to a fast, energetic transition." },
            { question: "Can I use my own shapes?", answer: "The morphing logic is built on procedural sdf (signed distance fields) which can be customized to support different geometric or organic base shapes." },
            { question: "Does it support color shifting?", answer: "Yes, the liquid colors cycle through a customizable gradient palette as they morph." }
        ],
    },
    {
        id: "brutalist-glitch-hero",
        name: "Brutalist Glitch Hero",
        description: "Brutalist design combined with digital glitch effects. Raw aesthetic with distortion and color separation artifacts.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "brutalist", "glitch", "distortion", "raw", "digital", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/BrutalistGlitchHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/BrutalistGlitchHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/BrutalistGlitchHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/BrutalistGlitchHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Ideal for street-wear brands, experimental agency sites, and neo-brutalist Next.js portfolios. Use this React component for a high-impact, distorted glitch pattern that combines raw design with digital artifacts.",
        bestPractices: "Maintain consistent spacing within your design system by pairing this with sharp borders and bold colors. Follow React best practices by using high-contrast shadows. Optimize for performance in large-scale applications by managing the glitch frequency.",
        whyMatters: "Brutalist glitches are a bold way to manage user attention. This customizable UI component gives you a production-level tool for building aggressive, memorable real-world application architecture.",
        faqs: [
            { question: "Is the glitch random?", answer: "The glitch effects are triggered procedurally, ensuring a unique yet controlled visual experience for every visitor." },
            { question: "Can I change the glitch color?", answer: "Yes, the chromatic aberration and color separation values can be tweaked to any palette." },
            { question: "Does it support hover interaction?", answer: "Yes, the glitch intensity can be mapped to mouse movements for a more interactive experience." }
        ],
    },
    {
        id: "bioluminescent-hero",
        name: "Bioluminescent Hero",
        description: "Glowing bioluminescent organisms simulation with organic movement. Underwater aesthetic with soft light emissions.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "bioluminescent", "glow", "organic", "underwater", "soft", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/BioluminescentHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/BioluminescentHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/BioluminescentHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/BioluminescentHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Excellent for underwater themes, luxury biotech brands, and Next.js sites that want a calm, organic feel. Use this React component for a bioluminescent simulation that adds soft glows and fluid movement to your background.",
        bestPractices: "Follow React best practices by pairing this with soft, rounded UI elements. Maintain scalable component architecture by using this as a thematic backdrop for specific narrative chapters. Optimize for performance by adjusting the number of glowing organisms.",
        whyMatters: "Bioluminescence creates a unique emotional atmosphere. This production-ready component helpsคุณ build an interface that feels atmospheric and 'alive', improving user retention through visual calm.",
        faqs: [
            { question: "Are the 'organisms' interactive?", answer: "Yes, they react to mouse proximity by glowing brighter or moving away, simulating natural predator-prey behavior." },
            { question: "Can I change the glow color?", answer: "Yes, you can fully customize the bioluminescent palette to include greens, blues, or even deep purples." },
            { question: "How realistic is the movement?", answer: "The component uses procedural flocks and fluid movement patterns to ensure a realistic, organic experience." }
        ],
    },
    {
        id: "smoke-hero",
        name: "Smoke Hero",
        description: "Realistic smoke and fog simulation with volumetric effects. Atmospheric background with organic particle movement.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "smoke", "fog", "volumetric", "atmospheric", "particles", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/SmokeHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/SmokeHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/SmokeHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/SmokeHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Perfect for moody portfolios, music landing pages, and Next.js experiences that want a deep, atmospheric feel. Use this React component for a realistic smoke and fog simulation that adds volumetric depth to your hero section.",
        bestPractices: "Maintain consistent spacing within your design system by keeping foreground content large and bold. Follow React best practices by using dark, immersive color schemes. Optimize for performance in large-scale applications by managing the particle lifetime and density.",
        whyMatters: "Volumetric smoke adds a sense of tangible space to 2D screens. This customizable UI component givesคุณ a production-level tool for building high-impact real-world application architecture that feels atmospheric and technically superior.",
        faqs: [
            { question: "Is the smoke interactive?", answer: "Yes, the smoke 'swirls' and reacts to mouse movement as if there's a physical wind source." },
            { question: "Can I change the smoke density?", answer: "Yes, you can range from a light morning mist to a thick, heavy fog using simple prop adjustments." },
            { question: "Does it work with background images?", answer: "Absolutely, it's designed to overlay beautifully on top of gradients or static images to add depth." }
        ],
    },
    {
        id: "molten-glass-hero",
        name: "Molten Glass Hero",
        description: "Molten glass effect with heat distortion and refraction. Liquid glass aesthetic with realistic light interactions.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "molten", "glass", "heat", "refraction", "liquid", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/MoltenGlassHero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/tsx/MoltenGlassHero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/Backgrounds/jsx/MoltenGlassHero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/Backgrounds/MoltenGlassHero/page.tsx") },
        dependencies: ["react", "ogl", "next"],
        props: [],
        whenToUse: "Ideal for high-end fashion brands, glassmorphism-themed sites, and Next.js applications that want a tactile, expensive look. Use this React component to simulate molten glass surfaces with realistic heat distortion and refraction.",
        bestPractices: "Maintain consistent spacing within your design system by using this as a high-contrast hero background. Follow React best practices by pairing it with glassmorphic cards and subtle shadows. Optimize for performance by using efficient refraction calculations.",
        whyMatters: "Glass effects are a signature of modern UI development. This production-ready component provides a hardware-accelerated version of molten glass, adding visual depth and semantic authority to your project.",
        faqs: [
            { question: "How does the refraction work?", answer: "The shader calculates the bending of light as it passes through 'varying thicknesses' of procedural glass." },
            { question: "Can I change the glass color?", answer: "Yes, you can create anything from clear crystalline surfaces to tinted, amber, or frosted glass." },
            { question: "Is the heat distortion animated?", answer: "Yes, the glass has a constant 'flow' to it, mimicking the behavior of molten materials." }
        ],
    },
];
