import { Component } from "../types";

export const backgroundComponentsMetadata: Component[] = [
    {
        id: "interstellar-fluid-hero",
        name: "Interstellar Fluid Hero",
        description: "Interactive fluid simulation creating cosmic nebula effects with mouse interaction. Deep space aesthetic with animated gas clouds and star trails.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "interstellar", "fluid", "nebula", "space", "interactive", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/InterstellarFluidHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [
            { name: "baseColor", type: "[number, number, number]", default: "[0.05, 0.05, 0.2]", description: "RGB array 0-1 for base color (Deep Space Blue)." },
            { name: "glowColor", type: "[number, number, number]", default: "[0.8, 0.4, 1.0]", description: "RGB array 0-1 for glow color (Nebula Violet)." },
            { name: "dissipation", type: "number", default: "0.97", description: "How fast the gas fades (0.95 - 0.99)." },
            { name: "velocityDissipation", type: "number", default: "0.98", description: "How fast movement stops." },
            { name: "interactive", type: "boolean", default: "true", description: "Enable mouse interaction." },
        ],
    },
    {
        id: "interstellar-background-hero",
        name: "Interstellar Background Hero",
        description: "Warp tunnel effect simulating high-velocity travel through nebular clusters. Procedural WebGL engine with mouse-responsive space distortion.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "interstellar", "warp", "tunnel", "space", "procedural", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/InterstellarBackgroundHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [
            { name: "baseColor", type: "[number, number, number]", default: "[0.1, 0.4, 0.9]", description: "RGB 0-1 for base color (Deep Electric Blue)." },
            { name: "speed", type: "number", default: "1.0", description: "Animation speed (0.0 - 5.0)." },
            { name: "density", type: "number", default: "1.2", description: "Nebula density (0.5 - 2.0)." },
            { name: "brightness", type: "number", default: "1.0", description: "Overall brightness (0.0 - 2.0)." },
            { name: "interactive", type: "boolean", default: "true", description: "Enable mouse interaction." },
        ],
    },
    {
        id: "liquid-chrome-hero",
        name: "Liquid Chrome Hero",
        description: "Procedural simulation of molten chrome alloys with velocity-based distortion. Interactive liquid metal surface with specular highlights.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "liquid", "chrome", "metal", "interactive", "webgl", "procedural"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/LiquidChromeHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [
            { name: "baseColor", type: "[number, number, number]", default: "[0.5, 0.5, 0.5]", description: "RGB array for base chrome color (neutral silver)." },
            { name: "speed", type: "number", default: "1.0", description: "Animation speed." },
            { name: "amplitude", type: "number", default: "0.6", description: "Distortion amplitude." },
            { name: "interactive", type: "boolean", default: "true", description: "Enable mouse interaction." },
        ],
    },
    {
        id: "ameoba-cyber-hero",
        name: "Ameoba Cyber Hero",
        description: "Soft matte fluid motion background with subtle mouse lens effects. Modern Swiss-style aesthetic with frosted grain texture.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "ameoba", "cyber", "fluid", "matte", "minimal", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/AmeobaCyberHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "glass-biology-hero",
        name: "Glass Biology Hero",
        description: "Biological cell pattern with Voronoi diagrams creating radioactive glass-like textures. Interactive pressure field with toxic neon colors.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "glass", "biology", "voronoi", "neon", "toxic", "interactive", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/GlassBiologyHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "brutalist-hero",
        name: "Brutalist Hero",
        description: "Neo-brutalist text pattern with safety yellow and black color scheme. Interactive shockwave distortion with chromatic aberration effects.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "brutalist", "text", "yellow", "interactive", "webgl", "distortion"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/BrutalistHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "hacker-mode-hero",
        name: "Hacker Mode Hero",
        description: "Matrix-style terminal grid with animated characters and glitch effects. Cyberpunk aesthetic with interactive text rendering.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "hacker", "terminal", "matrix", "cyberpunk", "glitch", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/HackerModeHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "raw-sketch-hero",
        name: "Raw Sketch Hero",
        description: "Hand-drawn sketch aesthetic with velocity-based grain and distortion. Raw artistic texture with organic movement.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "sketch", "raw", "artistic", "grain", "organic", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/RawSketchHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "fluid-dynamics-hero",
        name: "Fluid Dynamics Hero",
        description: "Advanced fluid simulation with image distortion and velocity-based effects. Realistic liquid motion with interactive mouse response.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "fluid", "dynamics", "simulation", "liquid", "interactive", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/FluidDynamicsHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "image-distortion-hero",
        name: "Image Distortion Hero",
        description: "Dynamic image distortion with noise-based warping effects. Interactive visual manipulation with procedural texture generation.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "image", "distortion", "warp", "noise", "interactive", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/ImageDistortionHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "dark-gradient-hero",
        name: "Dark Gradient Hero",
        description: "Smooth dark gradient background with animated color transitions. Minimalist aesthetic with subtle motion effects.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "dark", "gradient", "minimal", "smooth", "animated", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/DarkGradientHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "webgl-hero",
        name: "WebGL Hero",
        description: "Generic WebGL background with customizable shader effects. Flexible foundation for custom visual effects.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "webgl", "shader", "customizable", "flexible"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/WebglHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "rain-storm-hero",
        name: "Rain Storm Hero",
        description: "Atmospheric rain and storm simulation with particle effects. Dynamic weather visualization with realistic precipitation.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "rain", "storm", "weather", "particles", "atmospheric", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/RainStormHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "holographic-grid-hero",
        name: "Holographic Grid Hero",
        description: "Futuristic holographic grid pattern with 3D depth and neon glow. Sci-fi aesthetic with animated grid lines.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "holographic", "grid", "futuristic", "neon", "sci-fi", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/HolographicGridHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "retro-grid-hero",
        name: "Retro Grid Hero",
        description: "Nostalgic retro grid pattern with vintage aesthetic. Classic 80s-inspired visual style with animated grid effects.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "retro", "grid", "vintage", "80s", "classic", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/RetroGridHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "grid-distortion-hero",
        name: "Grid Distortion Hero",
        description: "Interactive grid with dynamic distortion effects. Mouse-responsive grid warping with smooth transitions.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "grid", "distortion", "interactive", "warp", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/GridDistortionHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "dark-matter-hero",
        name: "Dark Matter Hero",
        description: "Cosmic dark matter visualization with mysterious particle effects. Deep space aesthetic with ethereal glow.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "dark", "matter", "cosmic", "space", "particles", "ethereal", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/DarkMatterHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "terminal-hero",
        name: "Terminal Hero",
        description: "Command-line terminal aesthetic with animated text and code effects. Developer-focused background with monospace typography.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "terminal", "code", "developer", "monospace", "text", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/TerminalHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "liquid-reality-hero",
        name: "Liquid Reality Hero",
        description: "Surreal liquid reality effect with morphing shapes and color transitions. Abstract visual experience with fluid motion.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "liquid", "reality", "surreal", "morphing", "abstract", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/LiquidRealityHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "brutalist-glitch-hero",
        name: "Brutalist Glitch Hero",
        description: "Brutalist design combined with digital glitch effects. Raw aesthetic with distortion and color separation artifacts.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "brutalist", "glitch", "distortion", "raw", "digital", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/BrutalistGlitchHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "bioluminescent-hero",
        name: "Bioluminescent Hero",
        description: "Glowing bioluminescent organisms simulation with organic movement. Underwater aesthetic with soft light emissions.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "bioluminescent", "glow", "organic", "underwater", "soft", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/BioluminescentHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "smoke-hero",
        name: "Smoke Hero",
        description: "Realistic smoke and fog simulation with volumetric effects. Atmospheric background with organic particle movement.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "smoke", "fog", "volumetric", "atmospheric", "particles", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/SmokeHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
    {
        id: "molten-glass-hero",
        name: "Molten Glass Hero",
        description: "Molten glass effect with heat distortion and refraction. Liquid glass aesthetic with realistic light interactions.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["background", "visuals", "molten", "glass", "heat", "refraction", "liquid", "webgl"],
        previewUrl: "/Backgrounds&Visuals/Backgrounds/MoltenGlassHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "ogl", "next"],
        props: [],
    },
];
