import { getCode } from "../getCode";
import { Component } from "../components-data";

export const gradientPackComponents: Component[] = [
    {
        id: "liquid-gradient",
        name: "Liquid Gradient",
        description: "A premium fluid simulation with deep burgundy and magenta tones, featuring a yellowish-white shine and high-detail noise.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "liquid", "fluid", "simulation", "premium"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/LiquidGradient",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/tsx/LiquidGradient.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/jsx/LiquidGradient.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/GradientsPacks/LiquidGradient/page.tsx") },
        dependencies: ["next", "ogl"],
        props: [
            { name: "color1", type: "string", default: "#220011", description: "Base Dark (e.g., Deep Burgundy)" },
            { name: "color2", type: "string", default: "#990055", description: "Mid Tone (e.g., Vibrant Magenta)" },
            { name: "color3", type: "string", default: "#fff4d0", description: "Highlight (e.g., Yellowish White)" },
            { name: "speed", type: "number", default: "0.8", description: "Animation speed" },
            { name: "reflection", type: "number", default: "0.6", description: "How shiny the highlights are" },
        ],
        whenToUse: "Use this component for hero sections or full-page backgrounds where you want a deep, atmospheric, and highly 'liquid' feel that reacts subtly to mouse movement.",
        bestPractices: "Pair with high-contrast, bold typography. The deep color shifts work best as a backdrop for minimal content that needs to feel premium and moody.",
        whyMatters: "Standard CSS-only gradients often lack the depth and organic feel of real-world fluid dynamics. This component uses GLSL shaders to provide high-performance, complex motion that elevates the visual quality of any modern web interface.",
        faqs: [
            { question: "Can I use different colors?", answer: "Yes, you can pass any hex color to `color1`, `color2`, and `color3` to completely transform the mood from dark burgundy to any other palette." },
            { question: "Is it performance-heavy?", answer: "The component uses WebGL via the OGL library, which is extremely lightweight and efficient, ensuring smooth 60fps animations even on mobile devices." },
            { question: "Does it support mouse interaction?", answer: "Yes, it has a built-in mouse lag/follow effect that subtly distorts the liquid based on the cursor position." }
        ],
    },
    {
        id: "plasma-rise",
        name: "Plasma Rise",
        description: "An upward-rising plasma effect with deep background colors and muted red/brown tones, featuring warm white specular highlights.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "plasma", "rising", "animated", "premium"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/PlasmaRise",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/tsx/PlasmaRise.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/jsx/PlasmaRise.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/GradientsPacks/PlasmaRise/page.tsx") },
        dependencies: ["next", "ogl"],
        props: [
            { name: "color1", type: "string", default: "#050505", description: "Deep background color" },
            { name: "color2", type: "string", default: "#331111", description: "Main rising color" },
            { name: "speed", type: "number", default: "1.0", description: "Upward velocity" },
            { name: "intensity", type: "number", default: "0.5", description: "Shine/Specular amount" },
        ],
        whenToUse: "Excellent for dark-themed landings, tech blogs, or creative portfolios where a vertical flow or 'energy' effect is desired.",
        bestPractices: "Use with dark background colors to make the 'rising' plasma threads pop. It works particularly well as a subtle layer behind high-tech UI components.",
        whyMatters: "Verticality creates a narrative of growth and upward momentum. This shader-based plasma effect provides a unique alternative to traditional horizontal or radial gradients.",
        faqs: [
            { question: "How do I make the glow stronger?", answer: "Increase the `intensity` prop to sharpen the specular highlights and make the plasma threads appear brighter." },
            { question: "Can the speed be negative?", answer: "The current logic is optimized for rising motion, but you can adjust the `speed` to slow it down to a near-static drift." },
            { question: "Is there a grain effect?", answer: "Yes, a premium fine grain is built-in to prevent banding and add a cinematic texture to the background." }
        ],
    },
    {
        id: "uilora-ascii",
        name: "Uilora Dynamic ASCII",
        description: "A liquid-flow ASCII dot grid that reacts to mouse movement and features dynamic brightness.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "ascii", "dot-grid", "interactive", "liquid"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraAscii",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/tsx/UiloraAscii.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/jsx/UiloraAscii.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/GradientsPacks/UiloraAscii/page.tsx") },
        dependencies: ["next", "ogl"],
        props: [
            { name: "color1", type: "string", default: "#020310", description: "Background color" },
            { name: "color2", type: "string", default: "#7dd3fc", description: "Character color" },
            { name: "gridSize", type: "number", default: "70", description: "Number of characters across" },
            { name: "speed", type: "number", default: "1.0", description: "Animation speed" },
            { name: "flowStrength", type: "number", default: "1.0", description: "How much the dots move/offset" },
            { name: "mouseInfluence", type: "number", default: "0.5", description: "Cursor push strength" },
        ],
        whenToUse: "Perfect for developer tools, technical landing pages, or any site that wants a 'terminal' or 'matrix' vibe with a modern, liquid twist.",
        bestPractices: "Keep the `gridSize` high (70+) for a dense, high-tech look, or lower (20-40) for a more abstract, chunky retro aesthetic.",
        whyMatters: "ASCII art is a staple of early computing culture. Bringing it into the modern era with fluid simulations and WebGL interaction creates a powerful bridge between nostalgic tech and cutting-edge design.",
        faqs: [
            { question: "Can I change the character used?", answer: "This version is hardcoded to dots for performance and aesthetic consistency, but the brightness modulation creates a convincing character-like effect." },
            { question: "How do I make it more responsive to mouse?", answer: "Increase the `mouseInfluence` prop to make the grid warp more aggressively around the cursor." },
            { question: "Does it scale to full screen?", answer: "Yes, the grid density automatically adjusts based on the container size to maintain the desired `gridSize`." }
        ],
    },
    {
        id: "uilora-aurora",
        name: "Monolith Aurora",
        description: "A vertical 'curtain' aurora effect with liquid folding logic and premium specular shine, creating a mercury or silk-like appearance.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "aurora", "monolith", "silk", "mercury"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraAurora",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/tsx/UiloraAurora.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/jsx/UiloraAurora.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/GradientsPacks/UiloraAurora/page.tsx") },
        dependencies: ["next", "ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#0a0a0a", description: "Deepest background (Black/Dark Gray)" },
            { name: "waveColor", type: "string", default: "#d1d1d1", description: "The moving liquid (Silver/White)" },
            { name: "speed", type: "number", default: "0.6", description: "Flow speed" },
            { name: "intensity", type: "number", default: "0.8", description: "How bright the shine is" },
        ],
        whenToUse: "Ideal for 'Apple-style' dark mode landers where you need a sense of premium texture, silver waves, or a monochromatic 'monolith' feel.",
        bestPractices: "Use with light mode text and thin, elegant typography. The silver highlights create a sense of metallic depth that works beautifully with minimal UI.",
        whyMatters: "Standard aurora effects often look like blurry green blobs. This 'Monolith' version uses domain warping and specular mapping to create sharp 'folding' logic, making it feel more like real liquid mercury or silk than just colored gas.",
        faqs: [
            { question: "Can I make it colorful?", answer: "Yes, pass any vibrant color to `waveColor` (like Emerald or Cyan) to turn the silver waves into a traditional aurora effect." },
            { question: "What is 'folding' logic?", answer: "It refers to the way the shader warps space-time coordinate systems to simulate physical creases and folds in a surface." },
            { question: "Is it responsive?", answer: "Yes, it uses an internal aspect-ratio correction to ensure the vertical curtain look remains consistent on all screen resolutions." }
        ],
    },
    {
        id: "uilora-dither",
        name: "Uilora Dither",
        description: "A smooth fluid brightness simulation passed through an 8x8 Bayer matrix for ordered dithering, creating a sharp pixel-art look.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "dither", "pixel-art", "matrix", "retro"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraDither",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/tsx/UiloraDither.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/jsx/UiloraDither.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/GradientsPacks/UiloraDither/page.tsx") },
        dependencies: ["next", "ogl"],
        props: [
            { name: "color1", type: "string", default: "#000000", description: "Background (Dark)" },
            { name: "color2", type: "string", default: "#ffffff", description: "Foreground (Dots)" },
            { name: "speed", type: "number", default: "1.0", description: "Flow speed" },
            { name: "blockSize", type: "number", default: "2.0", description: "Pixel size (higher for chunkier)" },
            { name: "intensity", type: "number", default: "1.0", description: "Contrast of the dithering" },
        ],
        whenToUse: "Excellent for retro-themed sites, lo-fi aesthetic brands, or any project that wants a high-contrast, pixelated texture.",
        bestPractices: "Adjust the `blockSize` to match your site's overall 'resolution'. A block size of 2.0 or 4.0 creates a great 'GameBoy' or 'Macintosh' dither feel.",
        whyMatters: "Dithering is a classic technique for simulating gradients with limited colors. Using a full 8x8 Bayer matrix in a shader allows for real-time high-performance dithering that looks infinitely more 'authentic' than simple CSS patterns.",
        faqs: [
            { question: "Does it look good in color?", answer: "Absolutely. Try using deep Blue/Cyan or Green/Black for a 'Cyberpunk Matrix' or 'Terminal' aesthetic." },
            { question: "How small can the blocks be?", answer: "Set `blockSize` to 1.0 for the finest possible dithering, but usually 2.0+ is better for the dithered 'texture' to be visible." },
            { question: "Is it interactive?", answer: "Yes, the underlying fluid simulation reacts to the mouse, which in turn shifts the dither pattern dynamically." }
        ],
    },
    {
        id: "uilora-silk",
        name: "Uilora Silk",
        description: "A high-end layered flow simulation creating silk folds with a creamy satin shine and subtle grain texture.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "silk", "satin", "flow", "elegant"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraSilk",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/tsx/UiloraSilk.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/jsx/UiloraSilk.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/GradientsPacks/UiloraSilk/page.tsx") },
        dependencies: ["next", "ogl"],
        props: [
            { name: "primaryColor", type: "string", default: "#2d1b69", description: "The main 'Silk' color" },
            { name: "secondaryColor", type: "string", default: "#050212", description: "The deep valley color" },
            { name: "speed", type: "number", default: "1.0", description: "Flow speed" },
            { name: "interactive", type: "number", default: "0.5", description: "Cursor influence (0 to 1)" },
            { name: "intensity", type: "number", default: "0.4", description: "Satin shine amount (0 to 1)" },
        ],
        whenToUse: "Perfect for fashion, luxury branding, or premium agency sites where an elegant, high-viscosity flow adds a sense of quality and smoothness.",
        bestPractices: "Use with dark, rich colors. The 'viscosity' and satin highlights create a weight that looks best with slow, deliberate animations.",
        whyMatters: "Silk simulations are notoriously difficult to get right without heavy compute. This GLSL implementation uses multiple layers of noise and specular peaks to create a convincing 'satin' feel at minimal performance cost.",
        faqs: [
            { question: "Is the grain adjustable?", answer: "The grain is subtle and calibrated for a high-end feel, but you can change the intensity by modifying the shader's grain uniform if needed." },
            { question: "Does the mouse warp it?", answer: "Yes, it features a 'wake' system where the mouse creates a subtle ripple in the silk as you move across it." },
            { question: "What colors work best?", answer: "Deep Indigos, Emerald Greens, and Rich Burgundies highlight the satin specular peaks the best." }
        ],
    },
    {
        id: "uilora-carbon",
        name: "Uilora Carbon Vapor",
        description: "A cinematic smoke simulation with deep charcoal tones and sharp metallic silver highlights.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "smoke", "carbon", "cinematic", "premium"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraCarbon",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/tsx/UiloraCarbon.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/jsx/UiloraCarbon.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/GradientsPacks/UiloraCarbon/page.tsx") },
        dependencies: ["next", "ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#050505", description: "Deepest background color" },
            { name: "vaporColor", type: "string", default: "#555555", description: "The smoky highlight color" },
            { name: "speed", type: "number", default: "0.5", description: "Vapor flow speed" },
            { name: "swirl", type: "number", default: "2.0", description: "Intensity of the curls" },
            { name: "intensity", type: "number", default: "1.5", description: "The metallic glint amount" },
        ],
        whenToUse: "Perfect for high-end cinematic landings, luxury product reveals, or any dark-mode project needing a sophisticated, smoke-like atmosphere.",
        bestPractices: "Works best as a full-page background or a hero section backdrop. Keep the `intensity` low for a more subtle, natural smoke effect.",
        whyMatters: "Smoke simulations in shaders often look either too simple or too heavy. This 'Carbon' version uses high-contrast noise mapping and metallic specular highlights to create a premium, high-fidelity look that mirrors cinematic special effects.",
        faqs: [
            { question: "Is it truly atmospheric?", answer: "Yes, the smoke folds use domain warping to simulate multi-layered depth, making it feel 3D and immersive." },
            { question: "Can I use it for colorful smoke?", answer: "Absolutely. Change `vaporColor` to any vibrant hex code (like #ff0055) for a neon-smoke aesthetic." },
            { question: "How does it interact with the mouse?", answer: "It features a subtle mouse follow effect that shifts the viewport perspective rather than strictly warping the smoke." }
        ],
    },
    {
        id: "uilora-vanto",
        name: "Uilora Vanta Vapor",
        description: "An ultra-dense, high-contrast smoke effect with pure white highlights and deep void-like shadows.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "smoke", "vanta", "void", "monochrome"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraVanto",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/tsx/UiloraVanto.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/jsx/UiloraVanto.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/GradientsPacks/UiloraVanto/page.tsx") },
        dependencies: ["next", "ogl"],
        props: [
            { name: "smokeColor", type: "string", default: "#ffffff", description: "Highlight/Smoke color" },
            { name: "voidColor", type: "string", default: "#000000", description: "Background/Void color" },
            { name: "density", type: "number", default: "8.0", description: "Thickness of the smoke layers" },
            { name: "speed", type: "number", default: "0.6", description: "Rising speed" },
            { name: "opacity", type: "number", default: "1.0", description: "Overall visibility" },
        ],
        whenToUse: "Ideal for 'Apple-style' dark mode landers where you need a sense of premium texture, sharp contrasts, and a monochromatic 'void' feel.",
        bestPractices: "Stick to monochromatic palettes for the most 'Vanta' look. High `density` values create a thicker, more opaque smoke cloud.",
        whyMatters: "Vantablack refers to a material that absorbs almost all light. This shader replicates that high-contrast delta by layering extremely dark shadows against razor-sharp highlights, providing a deep, high-fidelity aesthetic.",
        faqs: [
            { question: "What represents the 'Void'?", answer: "The `voidColor` allows for deep, high-contrast areas that make the smoke layers appears significantly more dramatic." },
            { question: "Is there a mouse effect?", answer: "Yes, the mouse acts as a subtle 'current' that pushes the smoke trails dynamically as you move." },
            { question: "How many layers are simulated?", answer: "It uses a 6-octave FBM (Fractal Brownian Motion) system to create the characteristic 'thick' smoke texture." }
        ],
    },
    {
        id: "uilora-vortice",
        name: "Uilora Vortice Aero",
        description: "A high-fidelity atmospheric swirl simulation with glowing cyan streaks and deep oceanic layering.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "vortex", "atmospheric", "swirl", "cyan"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraVorticeAero",
        code: {
            tsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/tsx/UiloraVorticeAero.tsx"),
            jsx: getCode("src/components/Backgrounds&Visuals/GradientsPacks/jsx/UiloraVorticeAero.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Backgrounds&Visuals/GradientsPacks/UiloraVorticeAero/page.tsx") },
        dependencies: ["next", "ogl"],
        props: [
            { name: "primaryColor", type: "string", default: "#00d4ff", description: "The glowing streak color" },
            { name: "secondaryColor", type: "string", default: "#020617", description: "The deep background void" },
            { name: "vorticity", type: "number", default: "0.5", description: "Intensity of the swirl motion" },
            { name: "speed", type: "number", default: "0.8", description: "Fluid velocity" },
        ],
        whenToUse: "Excellent for tech dashboards, AI-themed landing pages, or high-performance SaaS sites that want to convey 'intelligence' or 'data flow'.",
        bestPractices: "Use with glowing, high-tech accents in your UI. The cyan tones work best with neon-styled components and dark, navy backgrounds.",
        whyMatters: "Vorticity simulation adds a layer of intelligence and complexity to a simple background. By using ridged noise for 'filaments', this shader creates a unique aesthetic that feels both organic and cybernetic.",
        faqs: [
            { question: "What are 'Filaments'?", answer: "These are the sharp, glowing streaks that simulate air currents or electrical pulses within the vortex." },
            { question: "Does the mouse change it?", answer: "Absolutely. The cursor acts as an anchor point that pulls the center of the vortex, allowing users to physically 'tug' on the atmosphere." },
            { question: "Is the grain adjustable?", answer: "The shader includes a built-in star-like grain that creates small 'atmospheric dust' particles for added depth." }
        ],
    },
];
