import { Component } from "../components-data";

export const noiseTextureComponentsMetadata: Component[] = [
    {
        id: "uilora-biolume-grain",
        name: "Uilora Biolume Grain",
        description: "An organic micro-grain field that breathes and wakes up with bioluminescent glows upon mouse interaction.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["noise", "grain", "biolume", "interactive", "organic", "ogl"],
        previewUrl: "/Backgrounds&Visuals/NoiseTexture/UiloraBiolumeGrain",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#020202", description: "Background depth color" },
            { name: "glowColor", type: "string", default: "#ffffff", description: "Bioluminescent grain tint" },
            { name: "breatheSpeed", type: "number", default: "0.8", description: "Natural pulse frequency" },
            { name: "sensitivity", type: "number", default: "1.0", description: "Mouse wakeup intensity" },
            { name: "grainScale", type: "number", default: "1024", description: "Frequency of micro-dots" },
        ],
    },
    {
        id: "uilora-cloud-background",
        name: "Uilora Cloud Background",
        description: "A high-fidelity domain-warped noise field that creates the appearance of swirling nebula clouds or marble veins.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["noise", "clouds", "nebula", "warping", "interactive", "ogl"],
        previewUrl: "/Backgrounds&Visuals/NoiseTexture/UiloraCloudBackground",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#000000", description: "Deep sky/background color" },
            { name: "cloudColor", type: "string", default: "#ffffff", description: "Color of the swirling veins" },
            { name: "speed", type: "number", default: "0.2", description: "Animation flow speed" },
            { name: "intensity", type: "number", default: "1.8", description: "Vein contrast and thickness" },
        ],
    },
    {
        id: "uilora-ink-grain",
        name: "Uilora Ink Grain",
        description: "A viscous liquid simulation that combines domain-warped clouds with high-precision micro-ink particles.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["noise", "ink", "grain", "fluid", "interactive", "ogl"],
        previewUrl: "/Backgrounds&Visuals/NoiseTexture/UiloraInkGrain",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#050505", description: "Liquid depth color" },
            { name: "inkColor", type: "string", default: "#ffffff", description: "Ink particle color" },
            { name: "viscosity", type: "number", default: "0.4", description: "Heaviness of the liquid flow" },
            { name: "grainDensity", type: "number", default: "0.6", description: "Particle visibility" },
            { name: "turbulence", type: "number", default: "0.5", description: "Mouse-driven stir amount" },
        ],
    },
    {
        id: "uilora-liquid-chrome",
        name: "Uilora Liquid Chrome",
        description: "A molten metal simulation using procedural height-maps to calculate real-time chrome reflections and specular peaks.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["noise", "chrome", "molten", "metal", "interactive", "ogl"],
        previewUrl: "/Backgrounds&Visuals/NoiseTexture/UiloraLiquidChrome",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#020202", description: "Deep shadow tint" },
            { name: "chromeColor", type: "string", default: "#ffffff", description: "Highlight/Metal color" },
            { name: "speed", type: "number", default: "0.5", description: "Rate of flow" },
            { name: "viscosity", type: "number", default: "0.4", description: "Liquid 'Thickness'" },
            { name: "distortion", type: "number", default: "0.8", description: "Mouse wake intensity" },
        ],
    },
    {
        id: "uilora-parchment",
        name: "Uilora Parchment",
        description: "A tactile paper synthesis system that recreates organic fibers, pulp clumps, and 3D shadow depth for an authentic physical feel.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["noise", "parchment", "paper", "tactile", "texture", "ogl"],
        previewUrl: "/Backgrounds&Visuals/NoiseTexture/UiloraParchment",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "paperColor", type: "string", default: "#f4f4f2", description: "The base pulp tint" },
            { name: "fiberColor", type: "string", default: "#000000", description: "Tint of the microscopic fibers" },
            { name: "pulpIntensity", type: "number", default: "0.5", description: "Clumpiness of the paper" },
            { name: "shadowDepth", type: "number", default: "0.02", description: "Tactile relief strength" },
        ],
    },
    {
        id: "uilora-refractive-deep",
        name: "Uilora Refractive Deep",
        description: "A layered aquatic simulation featuring surface ripples, caustics, and refracted sediment grain.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["noise", "refractive", "water", "deep", "caustics", "ogl"],
        previewUrl: "/Backgrounds&Visuals/NoiseTexture/UiloraRefractiveDeep",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#080808", description: "Bottom depth color" },
            { name: "grainColor", type: "string", default: "#ffffff", description: "Sediment particle color" },
            { name: "refractionIndex", type: "number", default: "0.4", description: "Light bending intensity" },
            { name: "waveSpeed", type: "number", default: "0.5", description: "Surface ripple speed" },
            { name: "grainScale", type: "number", default: "800", description: "Sediment density" },
        ],
    },
];

