import { Component } from "../components-data";

export const blurredBackgroundComponentsMetadata: Component[] = [
    {
        id: "dot-uilora",
        name: "Dot Uilora",
        description: "Sophisticated interactive dot mesh background with fluid warping and halftone depth effects.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["blur", "dots", "mesh", "interactive", "halftone"],
        previewUrl: "/Backgrounds&Visuals/BlurredBackgrounds/DotUilora",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["ogl"],
        props: [
            { name: "dotColor", type: "string", default: "#50d8f7", description: "The color of the dots" },
            { name: "backgroundColor", type: "string", default: "#020617", description: "Deep background color" },
            { name: "density", type: "number", default: "40.0", description: "Density of the grid (15-60)" },
            { name: "speed", type: "number", default: "0.4", description: "Speed of the movement" },
            { name: "interactive", type: "boolean", default: "true", description: "Responsive to mouse movement" },
        ],
    },
    {
        id: "uilora-digital-sorting",
        name: "Uilora Digital Sorting",
        description: "Premium pixel-sorting effect with vertical streaks, digital jitter, and subtle scanline textures.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["blur", "digital", "sorting", "glitch", "premium"],
        previewUrl: "/Backgrounds&Visuals/BlurredBackgrounds/UiloraDigitalSorting",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#050505", description: "The deep background color" },
            { name: "accentColor", type: "string", default: "#1a1a25", description: "Color of the sorted blocks" },
            { name: "blockSize", type: "number", default: "1.0", description: "Width of vertical columns (0.5-2.0)" },
            { name: "speed", type: "number", default: "0.2", description: "Speed of vertical drift" },
        ],
    },
    {
        id: "uilora-frosted-glass",
        name: "Uilora Frosted Glass",
        description: "Elegant sandblasted glass effect with organic moving blobs and premium film grain texture.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["blur", "glass", "frosted", "soft", "premium"],
        previewUrl: "/Backgrounds&Visuals/BlurredBackgrounds/UiloraFrostedGlass",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#080808", description: "Main background color" },
            { name: "accentColor", type: "string", default: "#222222", description: "Color of moving blobs" },
            { name: "speed", type: "number", default: "0.3", description: "Speed of organic movement" },
            { name: "grainAmount", type: "number", default: "0.05", description: "Intensity of frosting (0.0-0.1)" },
        ],
    },
    {
        id: "uilora-glass-melt",
        name: "Uilora Glass Melt",
        description: "Stunning liquid glass refraction with interactive domain warping and edge highlights.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["blur", "liquid", "glass", "warp", "refraction"],
        previewUrl: "/Backgrounds&Visuals/BlurredBackgrounds/UiloraGlassMelt",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["ogl"],
        props: [
            { name: "primaryColor", type: "string", default: "#050505", description: "Primary glass tint" },
            { name: "accentColor", type: "string", default: "#1a1a1a", description: "Flowing refraction color" },
            { name: "fluidity", type: "number", default: "0.5", description: "How fast the liquid moves" },
            { name: "refraction", type: "number", default: "0.4", description: "Intensity of distortion" },
        ],
    },
    {
        id: "uilora-gradient-background",
        name: "Uilora Gradient Background",
        description: "4-color organic gradient with domain warping and soft CSS-enhanced blurring for ultimate smoothness.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["blur", "gradient", "smooth", "fluid", "color"],
        previewUrl: "/Backgrounds&Visuals/BlurredBackgrounds/UiloraGradientBackground",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["ogl"],
        props: [
            { name: "colors", type: "string[]", default: "['#4f46e5', '#7c3aed', '#2563eb', '#db2777']", description: "4 Hex colors for the blend" },
            { name: "speed", type: "number", default: "0.5", description: "Animation speed" },
            { name: "intensity", type: "number", default: "0.4", description: "Distortion intensity" },
            { name: "interactive", type: "boolean", default: "true", description: "Follows mouse movement" },
        ],
    },
    {
        id: "uilora-iridescent-oil",
        name: "Uilora Iridescent Oil",
        description: "Luxurious oil-on-water effect with rainbow iridescence, domain warping, and specular highlights.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["blur", "iridescent", "oil", "color", "premium"],
        previewUrl: "/Backgrounds&Visuals/BlurredBackgrounds/UiloraIridescentOil",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#050505", description: "The underlying substrate color" },
            { name: "speed", type: "number", default: "0.5", description: "How fast the oil swirls" },
            { name: "vibrancy", type: "number", default: "0.4", description: "Intensity of rainbow effect" },
        ],
    },
    {
        id: "uilora-nebula-gossamer",
        name: "Uilora Nebula Gossamer",
        description: "Deep space nebula effect using FBM noise for volumetric smoke simulation and interactive wind.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["blur", "nebula", "smoke", "volumetric", "space"],
        previewUrl: "/Backgrounds&Visuals/BlurredBackgrounds/UiloraNebulaGossamer",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#020202", description: "Deep space color" },
            { name: "fogColor", type: "string", default: "#222530", description: "Nebula smoke color" },
            { name: "speed", type: "number", default: "0.5", description: "Movement speed" },
            { name: "density", type: "number", default: "0.7", description: "Vissibility of the smoke layers" },
        ],
    },
    {
        id: "uilora-prism-dispersion",
        name: "Uilora Prism Dispersion",
        description: "Sophisticated RGB chromatic aberration effect with spectral splitting and liquid highlights.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["blur", "prism", "dispersion", "chromatic", "light"],
        previewUrl: "/Backgrounds&Visuals/BlurredBackgrounds/UiloraPrismDispersion",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#030303", description: "Background depth color" },
            { name: "accentColor", type: "string", default: "#202025", description: "Moving highlight color" },
            { name: "dispersion", type: "number", default: "0.05", description: "Intensity of RGB splitting" },
            { name: "speed", type: "number", default: "0.4", description: "Flow speed" },
        ],
    },
    {
        id: "uilora-topographic-pulse",
        name: "Uilora Topographic Pulse",
        description: "Cinematic topographic map simulation with pulsing isolines, gravity distortion, and film grain.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["blur", "topo", "map", "pulse", "premium"],
        previewUrl: "/Backgrounds&Visuals/BlurredBackgrounds/UiloraTopographicPulse",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#050505", description: "The deep background color" },
            { name: "lineColor", type: "string", default: "#333333", description: "The color of the topographic lines" },
            { name: "speed", type: "number", default: "0.4", description: "Pulse and flow rate" },
            { name: "complexity", type: "number", default: "1.5", description: "Density of contour lines" },
        ],
    },
];
