import { Component } from "../components-data";

export const gradientPackComponentsMetadata: Component[] = [
    {
        id: "liquid-gradient",
        name: "Liquid Gradient",
        description: "A premium fluid simulation with deep burgundy and magenta tones, featuring a yellowish-white shine and high-detail noise.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "liquid", "fluid", "simulation", "premium"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/LiquidGradient",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "color1", type: "string", default: "#220011", description: "Base Dark (e.g., Deep Burgundy)" },
            { name: "color2", type: "string", default: "#990055", description: "Mid Tone (e.g., Vibrant Magenta)" },
            { name: "color3", type: "string", default: "#fff4d0", description: "Highlight (e.g., Yellowish White)" },
            { name: "speed", type: "number", default: "0.8", description: "Animation speed" },
            { name: "reflection", type: "number", default: "0.6", description: "How shiny the highlights are" },
        ],
    },
    {
        id: "plasma-rise",
        name: "Plasma Rise",
        description: "An upward-rising plasma effect with deep background colors and muted red/brown tones, featuring warm white specular highlights.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "plasma", "rising", "animated", "premium"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/PlasmaRise",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "color1", type: "string", default: "#050505", description: "Deep background color" },
            { name: "color2", type: "string", default: "#331111", description: "Main rising color" },
            { name: "speed", type: "number", default: "1.0", description: "Upward velocity" },
            { name: "intensity", type: "number", default: "0.5", description: "Shine/Specular amount" },
        ],
    },
    {
        id: "uilora-ascii",
        name: "Uilora Dynamic ASCII",
        description: "A liquid-flow ASCII dot grid that reacts to mouse movement and features dynamic brightness.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "ascii", "dot-grid", "interactive", "liquid"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraAscii",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "color1", type: "string", default: "#020310", description: "Background color" },
            { name: "color2", type: "string", default: "#7dd3fc", description: "Character color" },
            { name: "gridSize", type: "number", default: "70", description: "Number of characters across" },
            { name: "speed", type: "number", default: "1.0", description: "Animation speed" },
            { name: "flowStrength", type: "number", default: "1.0", description: "How much the dots move/offset" },
            { name: "mouseInfluence", type: "number", default: "0.5", description: "Cursor push strength" },
        ],
    },
    {
        id: "uilora-aurora",
        name: "Monolith Aurora",
        description: "A vertical 'curtain' aurora effect with liquid folding logic and premium specular shine, creating a mercury or silk-like appearance.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "aurora", "monolith", "silk", "mercury"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraAurora",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#0a0a0a", description: "Deepest background (Black/Dark Gray)" },
            { name: "waveColor", type: "string", default: "#d1d1d1", description: "The moving liquid (Silver/White)" },
            { name: "speed", type: "number", default: "0.6", description: "Flow speed" },
            { name: "intensity", type: "number", default: "0.8", description: "How bright the shine is" },
        ],
    },
    {
        id: "uilora-dither",
        name: "Uilora Dither",
        description: "A smooth fluid brightness simulation passed through an 8x8 Bayer matrix for ordered dithering, creating a sharp pixel-art look.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "dither", "pixel-art", "matrix", "retro"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraDither",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "color1", type: "string", default: "#000000", description: "Background (Dark)" },
            { name: "color2", type: "string", default: "#ffffff", description: "Foreground (Dots)" },
            { name: "speed", type: "number", default: "1.0", description: "Flow speed" },
            { name: "blockSize", type: "number", default: "2.0", description: "Pixel size (higher for chunkier)" },
            { name: "intensity", type: "number", default: "1.0", description: "Contrast of the dithering" },
        ],
    },
    {
        id: "uilora-silk",
        name: "Uilora Silk",
        description: "A high-end layered flow simulation creating silk folds with a creamy satin shine and subtle grain texture.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "silk", "satin", "flow", "elegant"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraSilk",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "primaryColor", type: "string", default: "#2d1b69", description: "The main 'Silk' color" },
            { name: "secondaryColor", type: "string", default: "#050212", description: "The deep valley color" },
            { name: "speed", type: "number", default: "1.0", description: "Flow speed" },
            { name: "interactive", type: "number", default: "0.5", description: "Cursor influence (0 to 1)" },
            { name: "intensity", type: "number", default: "0.4", description: "Satin shine amount (0 to 1)" },
        ],
    },
    {
        id: "uilora-carbon",
        name: "Uilora Carbon Vapor",
        description: "A cinematic smoke simulation with deep charcoal tones and sharp metallic silver highlights.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "smoke", "carbon", "cinematic", "premium"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraCarbon",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "baseColor", type: "string", default: "#050505", description: "Deepest background color" },
            { name: "vaporColor", type: "string", default: "#555555", description: "The smoky highlight color" },
            { name: "speed", type: "number", default: "0.5", description: "Vapor flow speed" },
            { name: "swirl", type: "number", default: "2.0", description: "Intensity of the curls" },
            { name: "intensity", type: "number", default: "1.5", description: "The metallic glint amount" },
        ],
    },
    {
        id: "uilora-vanto",
        name: "Uilora Vanta Vapor",
        description: "An ultra-dense, high-contrast smoke effect with pure white highlights and deep void-like shadows.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "smoke", "vanta", "void", "monochrome"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraVanto",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "smokeColor", type: "string", default: "#ffffff", description: "Highlight/Smoke color" },
            { name: "voidColor", type: "string", default: "#000000", description: "Background/Void color" },
            { name: "density", type: "number", default: "8.0", description: "Thickness of the smoke layers" },
            { name: "speed", type: "number", default: "0.6", description: "Rising speed" },
            { name: "opacity", type: "number", default: "1.0", description: "Overall visibility" },
        ],
    },
    {
        id: "uilora-vortice",
        name: "Uilora Vortice Aero",
        description: "A high-fidelity atmospheric swirl simulation with glowing cyan streaks and deep oceanic layering.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["gradient", "vortex", "atmospheric", "swirl", "cyan"],
        previewUrl: "/Backgrounds&Visuals/GradientsPacks/UiloraVorticeAero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "primaryColor", type: "string", default: "#00d4ff", description: "The glowing streak color" },
            { name: "secondaryColor", type: "string", default: "#020617", description: "The deep background void" },
            { name: "vorticity", type: "number", default: "0.5", description: "Intensity of the swirl motion" },
            { name: "speed", type: "number", default: "0.8", description: "Fluid velocity" },
        ],
    },
];


