import { Component } from "../components-data";

export const patternBackgroundComponentsMetadata: Component[] = [
    {
        id: "uilora-kinetic-raster",
        name: "Uilora Kinetic Raster",
        description: "A dynamic Halftone-inspired grid featuring elastic mouse interaction and fluid noise-driven movement.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["pattern", "raster", "grid", "halftone", "interactive", "ogl"],
        previewUrl: "/Backgrounds&Visuals/PatternBackgrounds/UiloraKineticRaster",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "dotColor", type: "string", default: "#222222", description: "Base color of the dots" },
            { name: "accentColor", type: "string", default: "#ffffff", description: "Color of dots near the mouse" },
            { name: "density", type: "number", default: "30", description: "Grid density (number of dots)" },
            { name: "speed", type: "number", default: "1.0", description: "Animation speed" },
        ],
    },
    {
        id: "uilora-moire-interference",
        name: "Uilora Moire Interference",
        description: "A sophisticated mathematical interference pattern with chromatic aberration and liquid mouse distortion.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["pattern", "moire", "interference", "prism", "interactive", "ogl"],
        previewUrl: "/Backgrounds&Visuals/PatternBackgrounds/UiloraMoireInterference",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "lineColor", type: "string", default: "#ffffff", description: "Color of the interference rings" },
            { name: "density", type: "number", default: "40.0", description: "Frequency of the rings" },
            { name: "strength", type: "number", default: "0.2", description: "Distortion intensity" },
            { name: "opacity", type: "number", default: "0.5", description: "Overall transparency" },
        ],
    },
    {
        id: "uilora-sdf-pattern",
        name: "Uilora SDF Pattern",
        description: "A multi-layered shape-morphing grid using Signed Distance Fields (SDF) for ultra-sharp, anti-aliased geometry.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["pattern", "sdf", "morphing", "geometry", "interactive", "ogl"],
        previewUrl: "/Backgrounds&Visuals/PatternBackgrounds/UiloraSDFPattern",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "gridSize", type: "number", default: "20", description: "Number of cells across" },
            { name: "color", type: "string", default: "#333333", description: "Base shape color" },
            { name: "accentColor", type: "string", default: "#ffffff", description: "Active shape color" },
            { name: "mouseRadius", type: "number", default: "0.25", description: "Radius of mouse influence" },
            { name: "interactionStrength", type: "number", default: "1.0", description: "Elastic warp amount" },
        ],
    },
    {
        id: "uilora-vector-grid",
        name: "Uilora Vector Grid",
        description: "A responsive grid of vector needles that react both to global noise 'wind' and local mouse magnetic pulls.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["pattern", "vector", "grid", "magnet", "interactive", "ogl"],
        previewUrl: "/Backgrounds&Visuals/PatternBackgrounds/UiloraVectorGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "ogl"],
        props: [
            { name: "gridSize", type: "number", default: "35", description: "Density of the needle grid" },
            { name: "color", type: "string", default: "#333333", description: "Idle needle color" },
            { name: "accentColor", type: "string", default: "#ffffff", description: "Magnetic needle color" },
            { name: "mouseRadius", type: "number", default: "0.25", description: "Magnet attraction radius" },
        ],
    },
    {
        id: "reactive-dots",
        name: "Reactive Dot Matrix",
        description: "Interactive canvas-based dot matrix that responds to mouse movement.",
        category: "Backgrounds & Visuals",
        installType: "cli",
        tags: ["pattern", "dots", "matrix", "interactive", "canvas"],
        previewUrl: "/Backgrounds&Visuals/PatternBackgrounds/ReactiveDots",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next"],
        props: [
            { name: "backgroundColor", type: "string", default: "#09090b", description: "Background color" },
            { name: "dotColor", type: "string", default: "#3b82f6", description: "Dot color" },
            { name: "dotBaseRadius", type: "number", default: "1.5", description: "Base radius of dots" },
            { name: "spacing", type: "number", default: "30", description: "Spacing between dots" },
            { name: "interactionDistance", type: "number", default: "200", description: "Mouse interaction distance" },
            { name: "interactionStrength", type: "number", default: "40", description: "Interaction strength" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
    },
];
