import { Component } from "../types";

export const chatUIComponentsMetadata: Component[] = [
    {
        id: "dock-chat",
        name: "Dock Chat",
        description: "Floating dock chat widget with customizable position, animated open/close transitions, and spring physics. Features morphing button icon and smooth chat panel animations.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "dock", "floating", "widget", "interactive", "animation"],
        previewUrl: "/Navigation&Structures/ChatUi/DockChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "position", type: "'bottom-right' | 'bottom-left' | 'top-right' | 'top-left'", default: "'bottom-right'", description: "Position of the dock button and chat panel." },
            { name: "buttonSize", type: "number", default: "56", description: "Size of the floating button in pixels." },
            { name: "chatWidth", type: "number", default: "320", description: "Width of the chat panel in pixels." },
            { name: "chatHeight", type: "number", default: "384", description: "Height of the chat panel in pixels." },
            { name: "title", type: "string", default: '"Support Team"', description: "Title displayed in the chat header." },
            { name: "subtitle", type: "string", default: '"How can we help you today?"', description: "Subtitle displayed in the chat header." },
            { name: "buttonColor", type: "string", default: '"#4f46e5"', description: "Color of the floating button (hex, rgb, or hsl)." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "onOpenChange", type: "(open: boolean) => void", default: "undefined", description: "Callback function called when chat opens or closes." },
        ],
    },
    {
        id: "media-chat",
        name: "Media Chat",
        description: "Chat message component for displaying images and code snippets. Features responsive image grid, code syntax highlighting, and interactive image preview with hover effects.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "media", "images", "code", "snippets", "gallery"],
        previewUrl: "/Navigation&Structures/ChatUi/MediaChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "lucide-react"],
        props: [
            { name: "images", type: "Array<{ url: string; alt?: string }>", default: "[]", description: "Array of image objects with URL and optional alt text." },
            { name: "codeSnippet", type: "{ language: string; code: string; fileName: string }", default: "undefined", description: "Code snippet object with language, code, and filename." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "onImageClick", type: "(index: number) => void", default: "undefined", description: "Callback function called when an image is clicked." },
            { name: "showCode", type: "boolean", default: "true", description: "Whether to display the code snippet." },
        ],
    },
    {
        id: "voice-message-bubble-chat",
        name: "Voice Message Bubble Chat",
        description: "Voice message bubble with animated waveform visualization, play/pause controls, and time display. Features smooth waveform animation during playback.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "voice", "audio", "waveform", "message", "bubble"],
        previewUrl: "/Navigation&Structures/ChatUi/VoiceMessageBubbleChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "isPlaying", type: "boolean", default: "undefined", description: "Whether the voice message is currently playing." },
            { name: "onPlayToggle", type: "(playing: boolean) => void", default: "undefined", description: "Callback function called when play/pause is toggled." },
            { name: "currentTime", type: "number", default: "12", description: "Current playback time in seconds." },
            { name: "duration", type: "number", default: "105", description: "Total duration of the voice message in seconds." },
            { name: "avatarUrl", type: "string", default: '"https://api.dicebear.com/7.x/avataaars/svg?seed=Jack"', description: "URL of the avatar image." },
            { name: "waveformColor", type: "string", default: '"#f97316"', description: "Color of the waveform visualization (hex, rgb, or hsl)." },
            { name: "bgColor", type: "string", default: '"white"', description: "Background color of the bubble." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
    },
    {
        id: "thread-preview-card",
        name: "Thread Preview Card",
        description: "Thread preview card with status badges, online indicators, and hover effects. Features gradient overlays and smooth animations on interaction.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "thread", "preview", "card", "status", "indicator"],
        previewUrl: "/Navigation&Structures/ChatUi/ThreadPreviewCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion"],
        props: [
            { name: "avatarUrl", type: "string", default: '"https://api.dicebear.com/7.x/bottts/svg?seed=gpt"', description: "URL of the avatar image." },
            { name: "name", type: "string", default: '"Support Bot"', description: "Name displayed in the preview card." },
            { name: "message", type: "string", default: '"Your ticket #4928 has been resolved. Click here to view details."', description: "Preview message text." },
            { name: "status", type: "'new' | 'unread' | 'read'", default: "'new'", description: "Status of the thread." },
            { name: "timestamp", type: "string", default: '"2 min ago"', description: "Timestamp text displayed in the card." },
            { name: "online", type: "boolean", default: "true", description: "Whether the user is online." },
            { name: "hoverEffect", type: "boolean", default: "true", description: "Whether to enable hover animations." },
            { name: "onClick", type: "() => void", default: "undefined", description: "Callback function called when the card is clicked." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "accentColor", type: "string", default: '"#3b82f6"', description: "Accent color for status badges and hover effects (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "avatar-pulse-message-chat",
        name: "Avatar Pulse Message Chat",
        description: "Avatar with pulsing animation and pop-in message bubble. Features dual pulse rings and animated message appearance with spring physics.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "avatar", "pulse", "message", "animation", "notification"],
        previewUrl: "/Navigation&Structures/ChatUi/AvatarPulseMessageChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion"],
        props: [
            { name: "avatarUrl", type: "string", default: '"https://api.dicebear.com/7.x/avataaars/svg?seed=Felix"', description: "URL of the avatar image." },
            { name: "message", type: "string", default: '"Hey! I\'m online now."', description: "Message text displayed in the bubble." },
            { name: "showPulse", type: "boolean", default: "true", description: "Whether to display the pulse animation." },
            { name: "pulseColor", type: "string", default: '"#ec4899"', description: "Color of the pulse rings (hex, rgb, or hsl)." },
            { name: "avatarSize", type: "number", default: "64", description: "Size of the avatar in pixels." },
            { name: "messagePosition", type: "'right' | 'left'", default: "'right'", description: "Position of the message bubble relative to avatar." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "delay", type: "number", default: "1", description: "Delay before message appears in seconds." },
        ],
    },
    {
        id: "typing-indicator-chat",
        name: "Typing Indicator Chat",
        description: "Animated typing indicators with multiple animation styles. Features bounce, pulse, and wave animations with customizable colors and alignment.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "typing", "indicator", "animation", "loading"],
        previewUrl: "/Navigation&Structures/ChatUi/TypingIndicatorChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion"],
        props: [
            { name: "type", type: "'bounce' | 'pulse' | 'wave'", default: "'bounce'", description: "Animation type for the typing indicator." },
            { name: "label", type: "string", default: "undefined", description: "Optional label text displayed with the indicator." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "align", type: "'left' | 'right' | 'center'", default: "'left'", description: "Alignment of the typing indicator." },
            { name: "color", type: "string", default: "'white'", description: "Color of the typing indicator dots/bars (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "morphing-input-chat",
        name: "Morphing Input Chat",
        description: "Morphing chat input with dynamic icon transitions. Features attachment buttons that morph into send button when text is entered, with smooth animations.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "input", "morphing", "animation", "interactive"],
        previewUrl: "/Navigation&Structures/ChatUi/MorphingInputChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "placeholder", type: "string", default: '"Ask AI anything..."', description: "Placeholder text for the input field." },
            { name: "onSend", type: "(message: string) => void", default: "undefined", description: "Callback function called when message is sent." },
            { name: "showLeftIcon", type: "boolean", default: "true", description: "Whether to display the left icon button." },
            { name: "showAttachments", type: "boolean", default: "true", description: "Whether to show attachment buttons when input is empty." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "value", type: "string", default: "undefined", description: "Controlled input value." },
            { name: "onChange", type: "(value: string) => void", default: "undefined", description: "Callback function called when input value changes." },
        ],
    },
    {
        id: "minimal-thread-chat",
        name: "Minimal Thread Chat",
        description: "Minimal thread chat message with attachments and reactions. Features file attachment previews, emoji reactions, and clean typography.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "thread", "minimal", "attachments", "reactions"],
        previewUrl: "/Navigation&Structures/ChatUi/MinimalThreadChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "lucide-react"],
        props: [
            { name: "userName", type: "string", default: '"Jane Doe"', description: "Name of the message sender." },
            { name: "userInitials", type: "string", default: '"JD"', description: "Initials displayed in the avatar." },
            { name: "timestamp", type: "string", default: '"12:42 PM"', description: "Timestamp text displayed in the message." },
            { name: "message", type: "string", default: '"Has anyone checked the latest deployment? I\'m seeing some improved latency figures on the dashboard. 🚀"', description: "Message text content." },
            { name: "attachments", type: "Array<{ name: string; size: string; type: 'pdf' | 'image' | 'doc' | 'other' }>", default: "[]", description: "Array of attachment objects with name, size, and type." },
            { name: "reactions", type: "Array<{ emoji: string; count: number }>", default: "[]", description: "Array of reaction objects with emoji and count." },
            { name: "showReactions", type: "boolean", default: "true", description: "Whether to display reactions." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
    },
    {
        id: "floating-chat",
        name: "Floating Chat",
        description: "3D floating chat list with perspective transforms and hover effects. Features card-based chat previews with 3D rotation on hover.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "floating", "3d", "perspective", "list"],
        previewUrl: "/Navigation&Structures/ChatUi/FloatingChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion"],
        props: [
            { name: "items", type: "Array<{ id: string | number; name: string; message: string; time: string; avatar?: string; color?: string; unread?: boolean }>", default: "[]", description: "Array of chat items to display." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "onItemClick", type: "(item: ChatItem) => void", default: "undefined", description: "Callback function called when a chat item is clicked." },
            { name: "maxWidth", type: "string", default: '"max-w-sm"', description: "Maximum width of the chat list container." },
        ],
    },
    {
        id: "ai-waveform-chat",
        name: "AI Waveform Chat",
        description: "AI chat bubble with animated waveform states. Features thinking, speaking, and idle states with auto-rotation and smooth state transitions.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "ai", "waveform", "states", "animation"],
        previewUrl: "/Navigation&Structures/ChatUi/AIWaveformChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "states", type: "Array<'thinking' | 'speaking' | 'idle'>", default: "['thinking', 'speaking', 'idle']", description: "Array of states to cycle through." },
            { name: "messages", type: "{ thinking: string; speaking: string; idle: string }", default: "{ thinking: '', speaking: 'I\'m generating that analysis for you now...', idle: 'Here is the summary of your meeting.' }", description: "Messages for each state." },
            { name: "autoRotate", type: "boolean", default: "true", description: "Whether to automatically rotate through states." },
            { name: "rotateInterval", type: "number", default: "3000", description: "Interval in milliseconds between state rotations." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "aiName", type: "string", default: '"AI"', description: "Name of the AI displayed in the status." },
        ],
    },
    {
        id: "soft-bubble-chat",
        name: "Soft Bubble Chat",
        description: "Soft rounded bubble chat interface with message history and typing indicators. Features smooth message animations and modern UI design.",
        category: "Navigation & Structure",
        installType: "cli",
        tags: ["navigation-structure", "chat", "bubble", "soft", "messages", "typing"],
        previewUrl: "/Navigation&Structures/ChatUi/SoftBubbleChat",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "initialMessages", type: "Array<Message>", default: "[]", description: "Initial messages to display in the chat." },
            { name: "userName", type: "string", default: '"You"', description: "Name of the current user." },
            { name: "userAvatar", type: "string", default: '"Y"', description: "Avatar initial or URL for the current user." },
            { name: "aiName", type: "string", default: '"Alice AI"', description: "Name of the AI assistant." },
            { name: "aiAvatar", type: "string", default: '"A"', description: "Avatar initial or URL for the AI." },
            { name: "showHeader", type: "boolean", default: "true", description: "Whether to display the chat header." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "onSendMessage", type: "(message: string) => Promise<void>", default: "undefined", description: "Callback function called when a message is sent." },
            { name: "placeholder", type: "string", default: '"Type a message..."', description: "Placeholder text for the input field." },
        ],
    },
];

