import { Component } from "../types";

export const accordionComponentsMetadata: Component[] = [
    {
        id: "uilora-liquid",
        name: "Liquid Stretch",
        description: "Smooth liquid motion accordion with natural spring animations.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "liquid", "motion", "spring"],
        previewUrl: "/SpecialElements/Accordions/Liquid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "AccordionItem[]", default: "[{id, label, content}, ...]", description: "Array of accordion items with id, label, and optional content." },
            { name: "containerBgColor", type: "string", default: "#ffffff", description: "Background color of the container card." },
            { name: "itemBgColor", type: "string", default: "#f4f4f5", description: "Background color of each accordion row." },
            { name: "itemTextColor", type: "string", default: "#18181b", description: "Text color of item labels." },
            { name: "contentTextColor", type: "string", default: "#71717a", description: "Text color of expanded content." },
            { name: "defaultActive", type: "number | null", default: "0", description: "Index of the initially active item." },
        ],
    },
    {
        id: "split",
        name: "Split Screen",
        description: "Split screen accordion with expanding image partitions — click a panel to reveal its content.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "split", "screen", "image", "layout"],
        previewUrl: "/SpecialElements/Accordions/Split",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "items", type: "AccordionItem[]", default: "[{id, label, title, description, image}, ...]", description: "Array of items — each panel can have a label, title, description, and background image URL." },
            { name: "height", type: "string", default: '"20rem"', description: "Height of the accordion container." },
            { name: "labelColor", type: "string", default: '"#ffffff"', description: "Color of the vertical label on collapsed panels." },
            { name: "titleColor", type: "string", default: '"#ffffff"', description: "Color of the expanded panel title." },
            { name: "descriptionColor", type: "string", default: '"#d4d4d8"', description: "Color of the expanded panel description." },
            { name: "defaultActive", type: "number | null", default: "null", description: "Index of the initially expanded panel." },
        ],
    },
    {
        id: "audio",
        name: "Audio Reactive",
        description: "Audio-reactive accordion with animated waveform bars and a progress track.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "audio", "reactive", "waveform"],
        previewUrl: "/SpecialElements/Accordions/Audio",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "AccordionItem[]", default: "[{id, label, content}, ...]", description: "Array of items — each gets a waveform and progress bar when active." },
            { name: "itemBgColor", type: "string", default: '"#18181b"', description: "Background color of inactive rows." },
            { name: "activeBarColor", type: "string", default: '"#4ade80"', description: "Color of the animated waveform bars on the active item." },
            { name: "progressBarFillColor", type: "string", default: '"#4ade80"', description: "Fill color of the progress bar." },
            { name: "defaultActive", type: "number | null", default: "null", description: "Index of the initially active item." },
        ],
    },
    {
        id: "faq-dark",
        name: "FAQ Dark",
        description: "Dark-themed card FAQ with accent-colored border glow on the active item and a 'View more' inline link.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "dark", "cards", "glow"],
        previewUrl: "/SpecialElements/Accordions/FAQDark",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#a78bfa"', description: "Accent color for the active border glow, icon, divider line, and View more link." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of FAQ items — each needs a question and an answer string." },
            { name: "title", type: "string", default: '"Frequently Asked"', description: "Section heading above the accordion." },
            { name: "eyebrow", type: "string", default: '"Uilora Support"', description: "Small mono eyebrow label above the title." },
        ],
    },
    {
        id: "faq-light",
        name: "FAQ Light",
        description: "Clean minimal light accordion with circular +/− icons, bullet-point sub-content, and a Learn more CTA per item.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "light", "minimal", "clean"],
        previewUrl: "/SpecialElements/Accordions/FAQLight",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Accent color for toggle icons, bullet dots, and the Learn more button." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of items — each needs a question, answer, and optional points string array." },
            { name: "title", type: "string", default: '"Uilora Components"', description: "Section heading." },
            { name: "subtitle", type: "string", default: '"A vertically stacked..."', description: "Supporting text below the heading." },
        ],
    },
    {
        id: "faq-bold",
        name: "FAQ Bold",
        description: "Dark bold FAQ with a giant editorial heading, full-width dividers, and inverted circular toggle icons.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "bold", "editorial", "dark", "typography"],
        previewUrl: "/SpecialElements/Accordions/FAQBold",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#ffffff"', description: "Color used to fill the toggle icon when active." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of FAQ items — each needs a question and answer." },
            { name: "heading", type: "string", default: '"FAQ"', description: "Large display heading — 2–4 chars render at maximum size." },
        ],
    },
    {
        id: "faq-editorial",
        name: "FAQ Editorial",
        description: "White editorial FAQ with a large display heading, dark card expansion, and decorative accent dots.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "editorial", "light", "cards", "premium"],
        previewUrl: "/SpecialElements/Accordions/FAQEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#f59e0b"', description: "Accent color for toggle icon fill, category eyebrow tint, and decorative dots." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of items — each needs a category, question, and answer." },
            { name: "heading", type: "string", default: '"FAQ"', description: "Large editorial heading at top-left." },
            { name: "lead", type: "string", default: '"The component library..."', description: "Supporting lead text beside the heading." },
        ],
    },
    {
        id: "faq-gallery",
        name: "FAQ Gallery",
        description: "Dark FAQ where each expanded item reveals a side-by-side image and answer panel.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "gallery", "image", "dark", "reveal"],
        previewUrl: "/SpecialElements/Accordions/FAQGallery",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#22d3ee"', description: "Accent color for tag badges, View more link, and active toggle icon." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of items — each needs a question, answer, image URL, and optional tag." },
            { name: "title", type: "string", default: '"Discover Uilora"', description: "Section heading." },
            { name: "subtitle", type: "string", default: '"Click a question..."', description: "Small subtitle below the heading." },
        ],
    },
    {
        id: "faq-timeline",
        name: "FAQ Timeline",
        description: "Stepped workflow accordion with a vertical connector line, animated numbered dots, and step tags.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "timeline", "steps", "workflow", "dark", "numbered"],
        previewUrl: "/SpecialElements/Accordions/FAQTimeline",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#818cf8"', description: "Accent color for the connector line, active dot fill, and tag badges." },
            { name: "items", type: "StepItem[]", default: "DEFAULT_ITEMS", description: "Array of steps — each needs a step string, title, description, and optional tag." },
            { name: "title", type: "string", default: '"How Uilora works"', description: "Section heading." },
            { name: "eyebrow", type: "string", default: '"Uilora Workflow"', description: "Mono eyebrow label above the heading." },
        ],
    },
];
