import { getCode } from "../getCode";
import { Component } from "../types";


export const accordionComponents: Component[] = [
    {
        id: "uilora-liquid",
        name: "Liquid Stretch",
        description: "Smooth liquid motion accordion with natural spring animations.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "liquid", "motion", "spring"],
        previewUrl: "/SpecialElements/Accordions/Liquid",
        code: {
            tsx: getCode("src/components/SpecialElements/Accordions/tsx/AccordionLiquid.tsx"),
            jsx: getCode("src/components/SpecialElements/Accordions/jsx/AccordionLiquid.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/SpecialElements/Accordions/Liquid/page.tsx")
        },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "AccordionItem[]", default: "[{id: '1', label: '...', content: '...'}, ...]", description: "Array of accordion items with id, label, and optional content." },
            { name: "containerBgColor", type: "string", default: "#ffffff", description: "Background color of the container card." },
            { name: "itemBgColor", type: "string", default: "#f4f4f5", description: "Background color of each accordion row." },
            { name: "itemTextColor", type: "string", default: "#18181b", description: "Text color of item labels." },
            { name: "contentTextColor", type: "string", default: "#71717a", description: "Text color of expanded content." },
            { name: "defaultActive", type: "number | null", default: "0", description: "Index of the initially active item (null for none)." },
        ],
        whenToUse: "Use for FAQ sections, feature lists, or any collapsible content block where a soft, organic feel fits the brand. Pairs well with white or light-gray backgrounds.",
        bestPractices: "Keep labels short and scannable — under 8 words. The spring physics feel most natural at 3–6 items. For longer lists, consider AccordionFAQBold which handles density better.",
        whyMatters: "Spring-driven height animation makes content feel like it has physical weight. The difference between a CSS transition and a spring is immediately felt — one slides, one breathes.",
        faqs: [
            { question: "How do I change the spring feel?", answer: "Adjust stiffness and damping in the AnimatePresence transition. Higher stiffness = snappier, lower damping = more bounce." },
            { question: "Can I use React nodes as content?", answer: "Yes — the content prop accepts React.ReactNode, so you can pass any JSX including buttons, links, and images." },
            { question: "Is it mobile responsive?", answer: "Yes — the max-w-md container scales down naturally. The spring animation performs at 60fps on modern mobile devices." }
        ],
    },
    {
        id: "split",
        name: "Split Screen",
        description: "Split screen accordion with expanding image partitions — click a panel to reveal its content.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "split", "screen", "image", "layout"],
        previewUrl: "/SpecialElements/Accordions/Split",
        code: {
            tsx: getCode("src/components/SpecialElements/Accordions/tsx/AccordionSplit.tsx"),
            jsx: getCode("src/components/SpecialElements/Accordions/jsx/AccordionSplit.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Accordions/Split/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "AccordionItem[]", default: "[{id, label, title, description, image}, ...]", description: "Array of items — each panel can have a label, title, description, and background image URL." },
            { name: "height", type: "string", default: '"20rem"', description: "Height of the accordion container." },
            { name: "labelColor", type: "string", default: '"#ffffff"', description: "Color of the vertical label text on each collapsed panel." },
            { name: "titleColor", type: "string", default: '"#ffffff"', description: "Color of the title shown in the expanded panel." },
            { name: "descriptionColor", type: "string", default: '"#d4d4d8"', description: "Color of the description text in the expanded panel." },
            { name: "defaultActive", type: "number | null", default: "null", description: "Index of the initially expanded panel." },
        ],
        whenToUse: "Ideal for editorial showcases, portfolio galleries, and product feature sections where visual storytelling is the priority. The horizontal split creates instant hierarchy.",
        bestPractices: "Use 3–4 panels for best visual balance. Landscape images with a clear subject work best since the panel crops to portrait on collapse. Keep labels 1–2 words.",
        whyMatters: "Horizontal expanding panels are one of the most visually impactful UI patterns — they turn a static image grid into an interactive narrative. Motion and content reveal together.",
        faqs: [
            { question: "Can I use a color instead of an image?", answer: "Yes — omit the image prop on any item and set the item's background via the backgroundImage style on the motion.div." },
            { question: "How do I adjust the expand ratio?", answer: "Change flex-[4] on the active class and flex-1 on inactive to control the ratio. flex-[3] gives a less dramatic expansion." },
            { question: "Is the layout animation smooth?", answer: "Yes — the Framer Motion layout prop animates the flex transition automatically using FLIP, so no janky reflows." }
        ],
    },
    {
        id: "audio",
        name: "Audio Reactive",
        description: "Audio-reactive accordion with animated waveform bars and a progress track — like a music player built into an FAQ.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "audio", "reactive", "waveform", "music"],
        previewUrl: "/SpecialElements/Accordions/Audio",
        code: {
            tsx: getCode("src/components/SpecialElements/Accordions/tsx/AccordionAudio.tsx"),
            jsx: getCode("src/components/SpecialElements/Accordions/jsx/AccordionAudio.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Accordions/Audio/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "AccordionItem[]", default: "[{id, label, content}, ...]", description: "Array of items — each gets a waveform visualizer and progress bar when active." },
            { name: "itemBgColor", type: "string", default: '"#18181b"', description: "Background color of inactive rows." },
            { name: "activeBarColor", type: "string", default: '"#4ade80"', description: "Color of the animated waveform bars on the active item." },
            { name: "progressBarFillColor", type: "string", default: '"#4ade80"', description: "Fill color of the progress bar shown in the expanded state." },
            { name: "defaultActive", type: "number | null", default: "null", description: "Index of the initially active item." },
        ],
        whenToUse: "Perfect for music platforms, podcast archives, or any context where the tracklist metaphor adds personality. Also works as a creative FAQ with strong brand voice.",
        bestPractices: "Use monospace or technical labels (Track 01, Module A) to reinforce the audio player aesthetic. Pair with a dark background for maximum waveform contrast.",
        whyMatters: "Repurposing the music player interaction pattern for content disclosure is rare — it creates delight through the unexpected. Users remember interfaces that surprise them.",
        faqs: [
            { question: "Is the waveform real audio data?", answer: "No — the bars animate with looping spring physics to simulate a waveform. For real audio, hook into the Web Audio API and map frequency data to the bar heights." },
            { question: "Can I use it with actual audio files?", answer: "Yes — add an HTML audio element and control playback in the onClick handler. The visual layer is decoupled from audio logic." },
            { question: "How do I change the animation speed?", answer: "Adjust the duration value in the bar's transition (currently 0.5 + bar * 0.1). Higher = slower, lower = faster frantic bars." }
        ],
    },
    {
        id: "faq-dark",
        name: "FAQ Dark",
        description: "Dark-themed card FAQ with accent-colored border glow on the active item and a 'View more' inline link.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "dark", "cards", "glow"],
        previewUrl: "/SpecialElements/Accordions/FAQDark",
        code: {
            tsx: getCode("src/components/SpecialElements/Accordions/tsx/AccordionFAQDark.tsx"),
            jsx: getCode("src/components/SpecialElements/Accordions/jsx/AccordionFAQDark.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Accordions/FAQDark/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#a78bfa"', description: "Accent color for the active border glow, icon, divider line, and View more link." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of FAQ items — each needs a question string and an answer string." },
            { name: "title", type: "string", default: '"Frequently Asked"', description: "Section heading above the accordion." },
            { name: "eyebrow", type: "string", default: '"Uilora Support"', description: "Small mono eyebrow label above the title." },
        ],
        whenToUse: "Drop this into any dark-themed product page as a support FAQ, feature explainer, or documentation section. The card layout keeps items visually separated and easy to scan.",
        bestPractices: "Use 4–6 questions for ideal density. Keep answers under 3 sentences — the 'View more' link implies there's more to read if needed. Purple or cyan work best as accent colors on dark.",
        whyMatters: "Most dark FAQ implementations use flat dividers. The subtle border glow on the active card adds visual hierarchy without heavy contrast — users instantly know which item is open.",
        faqs: [
            { question: "How does the glow work?", answer: "The active item gets a 1px border at accentColor + '35' opacity plus a box-shadow with accentColor + '08' — subtle enough to avoid visual noise, strong enough to communicate state." },
            { question: "Can I keep multiple items open?", answer: "Change the state to a Set<number> and toggle membership instead of setting a single index. AnimatePresence handles multiple simultaneous open items." },
            { question: "Can I remove the View more link?", answer: "Yes — it's a plain button inside the expanded content div. Delete or replace it with your own CTA." }
        ],
    },
    {
        id: "faq-light",
        name: "FAQ Light",
        description: "Clean minimal light accordion with circular +/− icons, bullet-point sub-content, and a Learn more CTA per item.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "light", "minimal", "clean"],
        previewUrl: "/SpecialElements/Accordions/FAQLight",
        code: {
            tsx: getCode("src/components/SpecialElements/Accordions/tsx/AccordionFAQLight.tsx"),
            jsx: getCode("src/components/SpecialElements/Accordions/jsx/AccordionFAQLight.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Accordions/FAQLight/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Accent color for the toggle icon border/fill, bullet dots, and Learn more button." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of items — each needs a question, answer, and optional points string array." },
            { name: "title", type: "string", default: '"Uilora Components"', description: "Section heading above the accordion." },
            { name: "subtitle", type: "string", default: '"A vertically stacked..."', description: "Supporting text below the heading." },
        ],
        whenToUse: "Best for documentation sites, SaaS dashboards, and any product context that calls for a clean, accessible FAQ that doesn't compete with the surrounding content.",
        bestPractices: "Use the points array to surface 2–4 key takeaways before the full answer — this improves scannability for users who skim. Keep the Learn more button to one CTA per item.",
        whyMatters: "The circular icon with a rotation transform is a small detail that reads as polish. Combined with the light background expand state, it creates a accordion that feels designed, not default.",
        faqs: [
            { question: "How do I remove the bullet points?", answer: "Omit the points array on any item. The component checks if (item.points) before rendering the bullet section." },
            { question: "Can I replace Learn more with a link?", answer: "Yes — replace the button with an anchor tag. The styling class 'text-xs font-semibold px-4 py-2 rounded-lg text-white' on the anchor will match perfectly." },
            { question: "Can I open multiple items at once?", answer: "Replace the single active index state with a Set<number>. The AnimatePresence exit animation handles concurrent open items natively." }
        ],
    },
    {
        id: "faq-bold",
        name: "FAQ Bold",
        description: "Dark bold FAQ with a giant editorial heading, full-width divider lines, and circular toggle icons that fill on active.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "bold", "editorial", "dark", "typography"],
        previewUrl: "/SpecialElements/Accordions/FAQBold",
        code: {
            tsx: getCode("src/components/SpecialElements/Accordions/tsx/AccordionFAQBold.tsx"),
            jsx: getCode("src/components/SpecialElements/Accordions/jsx/AccordionFAQBold.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Accordions/FAQBold/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#ffffff"', description: "Color used to fill the toggle icon when active — white creates the classic dark/light inversion." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of FAQ items — each needs a question and an answer string." },
            { name: "heading", type: "string", default: '"FAQ"', description: "The large display heading above the list — 2–4 characters render at maximum size." },
        ],
        whenToUse: "Deploy on agency homepages, product launch pages, and any brand context where editorial weight signals authority. The large heading makes the FAQ section feel like a statement, not an afterthought.",
        bestPractices: "Keep heading short (FAQ, Ask, Help). Use 4–6 questions — more than 7 dilutes the bold typographic impact. The hover color shift on labels adds subtle life without distraction.",
        whyMatters: "Most FAQ sections are buried in tiny type at the bottom of a page. A 6rem heading announces that questions deserve answers. Typographic scale is the cheapest form of visual authority.",
        faqs: [
            { question: "How does the heading size scale?", answer: "It uses CSS clamp(4rem, 8vw, 6rem) — grows proportionally on large screens, caps at 6rem, minimum 4rem on mobile." },
            { question: "Why does the icon invert on active?", answer: "The circle fills with accentColor (#ffffff by default) and the + color becomes #000000. On dark backgrounds this reads as a bold on/off toggle — clear and decisive." },
            { question: "Can I use this on a light background?", answer: "Yes — change the container background to white and set accentColor to your brand color. The divider lines and text colors will need updating to zinc equivalents." }
        ],
    },
    {
        id: "faq-editorial",
        name: "FAQ Editorial",
        description: "White editorial FAQ with a large display heading, expandable dark-card items, and a decorative accent dot row.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "editorial", "light", "cards", "premium"],
        previewUrl: "/SpecialElements/Accordions/FAQEditorial",
        code: {
            tsx: getCode("src/components/SpecialElements/Accordions/tsx/AccordionFAQEditorial.tsx"),
            jsx: getCode("src/components/SpecialElements/Accordions/jsx/AccordionFAQEditorial.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Accordions/FAQEditorial/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#f59e0b"', description: "Accent color for the toggle icon fill, category eyebrow tint, and decorative dots." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of items — each needs a category label, question heading, and answer string." },
            { name: "heading", type: "string", default: '"FAQ"', description: "Large editorial heading displayed at top-left of the component." },
            { name: "lead", type: "string", default: '"The component library..."', description: "Supporting lead text beside the heading." },
        ],
        whenToUse: "Ideal for brand homepages, SaaS pricing pages, and premium product sites where the FAQ needs to feel like an editorial section — not a support widget.",
        bestPractices: "Use 3–5 items. The category eyebrow (e.g. 'Inspiration', 'Usage') gives each item editorial taxonomy — use it to organize by theme, not by question type.",
        whyMatters: "The inversion on active (white card → black card) is a strong visual affordance that most accordions skip. The user never wonders which item is open — the contrast tells them instantly.",
        faqs: [
            { question: "Why does the card flip dark on expand?", answer: "The motion.div transitions background from #f4f4f5 to #09090b. Combined with the white-to-dark text transition, it creates a complete color inversion — visually unambiguous." },
            { question: "What's the category eyebrow for?", answer: "It's a 9px mono uppercase label above the question — it groups items by theme without adding visual weight. Users can skim categories before reading questions." },
            { question: "Can I add an image inside the expanded content?", answer: "Yes — replace or augment the answer paragraph with any JSX including img, video, or a component. The height animation handles any content height automatically." }
        ],
    },
    {
        id: "faq-gallery",
        name: "FAQ Gallery",
        description: "Dark FAQ where each expanded item reveals a side-by-side image and answer panel — a visual question explorer.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "faq", "gallery", "image", "dark", "reveal"],
        previewUrl: "/SpecialElements/Accordions/FAQGallery",
        code: {
            tsx: getCode("src/components/SpecialElements/Accordions/tsx/AccordionFAQGallery.tsx"),
            jsx: getCode("src/components/SpecialElements/Accordions/jsx/AccordionFAQGallery.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Accordions/FAQGallery/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#22d3ee"', description: "Accent color for tag badges, the View more link, and the active toggle icon." },
            { name: "items", type: "FAQItem[]", default: "DEFAULT_ITEMS", description: "Array of items — each needs a question, answer, image URL, and optional tag string." },
            { name: "title", type: "string", default: '"Discover Uilora"', description: "Section heading above the FAQ list." },
            { name: "subtitle", type: "string", default: '"Click a question..."', description: "Small subtitle below the heading." },
        ],
        whenToUse: "Use when the FAQ answers benefit from visual context — product features, workflow steps, portfolio work, or any content where a supporting image clarifies more than text alone.",
        bestPractices: "Choose images that reinforce the answer, not just decorate it. The image crops to 144×112px, so use images with a clear subject centered. Cyan, teal, and green accents read best on the dark background.",
        whyMatters: "Standard FAQs are text-only. Adding an image per answer turns the FAQ into a micro product tour — users explore by curiosity, not obligation. The reveal animation makes each expand feel like a discovery.",
        faqs: [
            { question: "How does the image reveal animate?", answer: "The image div uses `initial={{ opacity: 0, scale: 1.05 }}` and animates to `{ opacity: 1, scale: 1 }` with a 0.08s delay — a subtle zoom-in that feels cinematic." },
            { question: "Can I use different images per item?", answer: "Yes — each FAQItem has an image prop. Pass any URL. Unsplash works well; add w=400 to the URL for optimized sizing." },
            { question: "Can I remove the tag badge?", answer: "Yes — the tag is optional. Omit it from any item and the badge won't render. The question text fills the space automatically." }
        ],
    },
    {
        id: "faq-timeline",
        name: "FAQ Timeline",
        description: "Stepped workflow accordion with a vertical connector line, animated numbered dots, and a tag badge per step.",
        category: "Special Elements",
        installType: "cli",
        tags: ["accordion", "timeline", "steps", "workflow", "dark", "numbered"],
        previewUrl: "/SpecialElements/Accordions/FAQTimeline",
        code: {
            tsx: getCode("src/components/SpecialElements/Accordions/tsx/AccordionFAQTimeline.tsx"),
            jsx: getCode("src/components/SpecialElements/Accordions/jsx/AccordionFAQTimeline.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Accordions/FAQTimeline/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#818cf8"', description: "Accent color for the connector line gradient, active step dot, tag badges, and description background tint." },
            { name: "items", type: "StepItem[]", default: "DEFAULT_ITEMS", description: "Array of steps — each needs a step string (01–99), title, description, and optional tag." },
            { name: "title", type: "string", default: '"How Uilora works"', description: "Section heading above the timeline." },
            { name: "eyebrow", type: "string", default: '"Uilora Workflow"', description: "Mono eyebrow label above the heading." },
        ],
        whenToUse: "Use for onboarding flows, product setup guides, pricing tier comparisons, and any sequential process where step order matters. The connector line makes the sequence feel linear and intentional.",
        bestPractices: "Use exactly 4 steps for the cleanest composition — the connector line looks best at that length. Keep step labels 2–4 words. Tags work best with single-word status labels (Free, Pro, Beta).",
        whyMatters: "A timeline turns a bullet list into a journey. The animated dot fill on active communicates 'you are here' without any additional UI — the connector line does the work.",
        faqs: [
            { question: "How does the step dot animate?", answer: "It uses `motion.animate` with a background transition from #1a1a1e to accentColor and a scale from 1 to 1.15 — giving the active step a physical 'pop' that reads as selected." },
            { question: "Can I use icons instead of numbers?", answer: "Yes — replace the step span with a Lucide icon. The dot container is 30×30px centered, so any 14px icon fits perfectly." },
            { question: "Does the connector line animate?", answer: "Currently it's a static gradient div. For a filling animation, wrap it in a motion.div and animate scaleY from 0→1 using useInView or scroll progress." }
        ],
    },
];
