import { Component } from "../types";

export const avatarsComponentsMetadata: Component[] = [
    {
        id: "classic-avatar",
        name: "Classic Avatar",
        description: "Comprehensive avatar collection with multiple styles including cinematic, minimal, status indicators, initials, grouped stacks, and hover effects. Showcase of 10+ avatar variations.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "avatar", "classic", "variants", "status", "grouped", "showcase"],
        previewUrl: "/SpecialElements/Avatars/ClassicAvatar",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "profile-avatars",
        name: "Profile Avatars",
        description: "Avatar collection for user profile contexts — editable overlays, verified badges, role tags, story rings, follow suggestions, permission tiers, multi-account switchers, and connected platform icons.",
        category: "Special Elements",
        installType: "cli",
        tags: ["avatar", "profile", "verified", "editable", "story", "role", "permissions", "social", "account"],
        previewUrl: "/SpecialElements/Avatars/ProfileAvatars",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [],
    },
    {
        id: "team-avatars",
        name: "Team Avatars",
        description: "Avatar collection for team and collaboration contexts — online presence strips, facepiles, task assignment rows, multi-assignee pickers, editing indicators, viewer presence, member directory rows, and invite-pending states.",
        category: "Special Elements",
        installType: "cli",
        tags: ["avatar", "team", "collaboration", "presence", "assignment", "facepile", "directory", "online", "members"],
        previewUrl: "/SpecialElements/Avatars/TeamAvatars",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [],
    },
    {
        id: "chat-avatars",
        name: "Chat Avatars",
        description: "Avatar collection for messaging and chat contexts — message thread avatars, typing indicators, last-seen states, group chat composite icons, mention chips, read receipts, reaction groups, and thread reply bars.",
        category: "Special Elements",
        installType: "cli",
        tags: ["avatar", "chat", "messaging", "typing", "read-receipts", "reactions", "group", "mention", "thread"],
        previewUrl: "/SpecialElements/Avatars/ChatAvatars",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [],
    },
];
