import { getCode } from "../getCode";
import { Component } from "../types";

export const avatarsComponents: Component[] = [
    {
        id: "classic-avatar",
        name: "Classic Avatar",
        description: "Comprehensive avatar collection with multiple styles including cinematic, minimal, status indicators, initials, grouped stacks, and hover effects. Showcase of 10+ avatar variations.",
        category: "Special Elements",
        installType: "cli",
        tags: ["special-elements", "avatar", "classic", "variants", "status", "grouped", "showcase"],
        previewUrl: "/SpecialElements/Avatars/ClassicAvatar",
        code: {
            tsx: getCode("src/components/SpecialElements/Avatars/tsx/ClassicAvatar.tsx"),
            jsx: getCode("src/components/SpecialElements/Avatars/jsx/ClassicAvatar.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Avatars/ClassicAvatar/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — dark for dashboards/apps, light for minimal or white-background interfaces." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Custom accent color applied to gradient rings, status glow, initials gradient, and interactive popup highlights." },
            { name: "showInteractive", type: "boolean", default: "true", description: "When false, hides the Interactive States section — useful for embedding in tight spaces or simpler contexts." },
        ],
        whenToUse: "Use when you need a complete, versatile avatar system for SaaS dashboards, admin panels, or premium interfaces. Covers all common avatar patterns — image, initials, status, and grouped — in a single showcase.",
        bestPractices: "Use CinematicAvatar for hero/profile header moments. Pair StatusAvatar with real-time presence data. Use AvatarStack for contributor counts in tight spaces.",
        whyMatters: "A consistent avatar system communicates identity and presence hierarchy across your entire interface — standardizing these reduces visual noise and speeds up user recognition.",
        faqs: [
            { question: "How do I handle missing images?", answer: "Use the MonoInitials or InitialsAvatar fallback components — they generate from a name string and always render something meaningful." },
            { question: "Can I customize status colors?", answer: "Yes — the StatusAvatar accepts an 'online' | 'away' | 'busy' prop that maps to emerald, amber, and rose respectively. Extend the colors object to add custom states." },
        ],
    },
    {
        id: "profile-avatars",
        name: "Profile Avatars",
        description: "Avatar collection for user profile contexts — editable overlays, verified badges, role tags, story rings, follow suggestions, permission tiers, multi-account switchers, and connected platform icons.",
        category: "Special Elements",
        installType: "cli",
        tags: ["avatar", "profile", "verified", "editable", "story", "role", "permissions", "social", "account"],
        previewUrl: "/SpecialElements/Avatars/ProfileAvatars",
        code: {
            tsx: getCode("src/components/SpecialElements/Avatars/tsx/ProfileAvatars.tsx"),
            jsx: getCode("src/components/SpecialElements/Avatars/jsx/ProfileAvatars.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Avatars/ProfileAvatars/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — adapts all cards, text, and borders for dark or light page backgrounds." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Applied to verified rings, follow button, permission tier highlights, and story ring gradient." },
            { name: "platform", type: '"twitter" | "github" | "linkedin"', default: '"twitter"', description: "Controls which connected platform badge icon is shown in the ConnectedProfile variant." },
        ],
        whenToUse: "Use in social platforms, creator tools, SaaS settings pages, and any product with user profiles, verification tiers, or role-based identity display.",
        bestPractices: "Reserve gradient story rings for unseen/active state — use grey for seen. Keep verified badges consistent in placement (always bottom-right) to build visual muscle memory.",
        whyMatters: "Profile avatars are the face of identity in your product — how you render them communicates trust, role hierarchy, and social proof at a glance.",
        faqs: [
            { question: "How does the editable overlay work?", answer: "It's a CSS-only hover reveal — the camera icon fades in via opacity transition on the parent :hover, no JS required." },
            { question: "Can the story ring animate on load?", answer: "Yes — swap the CSS spin animation with a Framer Motion initial/animate cycle to trigger on mount instead of continuously." },
        ],
    },
    {
        id: "team-avatars",
        name: "Team Avatars",
        description: "Avatar collection for team and collaboration contexts — online presence strips, facepiles, task assignment rows, multi-assignee pickers, editing indicators, viewer presence, member directory rows, and invite-pending states.",
        category: "Special Elements",
        installType: "cli",
        tags: ["avatar", "team", "collaboration", "presence", "assignment", "facepile", "directory", "online", "members"],
        previewUrl: "/SpecialElements/Avatars/TeamAvatars",
        code: {
            tsx: getCode("src/components/SpecialElements/Avatars/tsx/TeamAvatars.tsx"),
            jsx: getCode("src/components/SpecialElements/Avatars/jsx/TeamAvatars.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Avatars/TeamAvatars/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — dark for internal tools, light for client-facing or minimal dashboards." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Team accent color applied to presence glow, editing ring, assignment hover border, and facepile count badge." },
            { name: "onlineCount", type: "number", default: "4", description: "Number of team members shown as online in the presence strip and presence grid (1–6)." },
        ],
        whenToUse: "Perfect for project management tools, internal dashboards, collaborative editors, and admin panels that need to communicate team presence, task ownership, and member status.",
        bestPractices: "Keep the facepile to 4-5 visible avatars max with an overflow count — showing too many loses the human feel. Use EditingIndicator sparingly — only for documents actively being edited.",
        whyMatters: "Team avatar patterns are the social fabric of collaborative products — they communicate who is here, who is responsible, and who to reach out to without any navigation.",
        faqs: [
            { question: "How do I wire the online presence data?", answer: "Replace the static status array with a real-time source (WebSocket, polling, or Pusher). The component renders the dot color based on the status string — just pass in live values." },
            { question: "Can I use FacepileWithCount in a table cell?", answer: "Yes — it's a self-contained flex row that shrinks to fit any container width." },
        ],
    },
    {
        id: "chat-avatars",
        name: "Chat Avatars",
        description: "Avatar collection for messaging and chat contexts — message thread avatars, typing indicators, last-seen states, group chat composite icons, mention chips, read receipts, reaction groups, and thread reply bars.",
        category: "Special Elements",
        installType: "cli",
        tags: ["avatar", "chat", "messaging", "typing", "read-receipts", "reactions", "group", "mention", "thread"],
        previewUrl: "/SpecialElements/Avatars/ChatAvatars",
        code: {
            tsx: getCode("src/components/SpecialElements/Avatars/tsx/ChatAvatars.tsx"),
            jsx: getCode("src/components/SpecialElements/Avatars/jsx/ChatAvatars.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Avatars/ChatAvatars/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — dark for chat apps, light for comment sections or social feeds on white backgrounds." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Applied to outgoing message bubble, mention chip border/text, thread reply bar, and read receipt checkmarks." },
            { name: "userName", type: "string", default: '"You"', description: "Name shown above outgoing message bubbles — replace with the current user's display name." },
        ],
        whenToUse: "Use when building chat interfaces, comment threads, activity feeds, or any messaging feature that needs rich avatar context at the message level.",
        bestPractices: "Read receipts should show max 3 avatar thumbnails + an overflow count to avoid cluttering message rows. Typing indicators should auto-disappear after a timeout to avoid stale UI.",
        whyMatters: "Chat avatars carry enormous communicative weight — they tell you who said what, who's listening, and who reacted, all without reading text.",
        faqs: [
            { question: "How do I animate the typing dots?", answer: "The component uses Framer Motion keyframes on scale and opacity with staggered delays per dot. Wrap in AnimatePresence so the bubble mounts/unmounts cleanly." },
            { question: "Can the GroupChatComposite handle non-square images?", answer: "Yes — each quadrant uses object-cover to fill its cell regardless of source image aspect ratio." },
        ],
    },
];
