import { getCode } from "../getCode";
import { Component } from "../types";

export const badgesComponents: Component[] = [
    {
        id: "classic-badges",
        name: "Classic Badges",
        description: "Comprehensive badge system with 10+ variations — glassy status, dot indicators, micro glow, pastel chips, tech tags, icon pills, blur tags, contrast labels, neon edges, and glossy gradients. Supports dark/light theme, compact mode, and custom accent color.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "classic", "status", "tags", "chips", "labels", "indicators", "dark", "light"],
        previewUrl: "/SpecialElements/Badges/ClassicBadges",
        code: {
            tsx: getCode("src/components/SpecialElements/Badges/tsx/ClassicBadges.tsx"),
            jsx: getCode("src/components/SpecialElements/Badges/jsx/ClassicBadges.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Badges/ClassicBadges/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — dark for dashboards, light for minimal interfaces." },
            { name: "compact", type: "boolean", default: "false", description: "Hides the Status Indicators section and tightens spacing for embedding in smaller areas." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Custom accent color applied to the Micro Glow badges." },
        ],
        whenToUse: "Use when you need a complete, ready-to-use badge system for SaaS dashboards, admin panels, or luxury interfaces. Supports both dark and light themes for easy integration.",
        bestPractices: "Pair dark theme with dark-background pages and light theme with white/gray pages. Use compact mode when embedding inside a settings panel or sidebar.",
        whyMatters: "A consistent badge system communicates status, roles, and metadata hierarchy across your entire interface — standardizing these prevents visual noise and speeds up user comprehension.",
        faqs: [
            { question: "How do I switch to light mode?", answer: 'Pass theme="light" — all 10 badge variants automatically adapt their colors, backgrounds, and borders.' },
            { question: "Can I customize the accent color?", answer: 'Yes — the accentColor prop controls the MicroBadge gradient and ring color. Pass any CSS color string.' },
            { question: "What does compact mode do?", answer: "It hides the Status Indicators section and reduces padding — useful when embedding inside a sidebar or modal." },
        ],
    },
    {
        id: "status-badges",
        name: "Status Badges",
        description: "System/app status badge collection — service health, notification counts, priority tags, connection states, user availability, and progress indicators. Light theme, dashboard-ready.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "status", "health", "notification", "priority", "availability", "dashboard"],
        previewUrl: "/SpecialElements/Badges/StatusBadges",
        code: {
            tsx: getCode("src/components/SpecialElements/Badges/tsx/StatusBadges.tsx"),
            jsx: getCode("src/components/SpecialElements/Badges/jsx/StatusBadges.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Badges/StatusBadges/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Perfect for SaaS dashboards, admin panels, uptime monitors, and any product interface that needs to communicate system or user state clearly.",
        bestPractices: "Use the ping animation sparingly — reserve it for truly live/active states. Priority tags work best when kept to a consistent 4-5 tier system across your product.",
        whyMatters: "Status communication is the backbone of operational interfaces. Clear, scannable indicators prevent users from needing to dig into details to understand system health.",
        faqs: [
            { question: "Are the ping animations CSS or JS?", answer: "Pure CSS via Tailwind's animate-ping — zero JS overhead, runs entirely on the GPU." },
            { question: "Can I use these in a table row?", answer: "Yes — each badge is a self-contained inline-flex element that works inside any container including table cells." },
        ],
    },
    {
        id: "ecommerce-badges",
        name: "Ecommerce Badges",
        description: "Bold product label system for shops and marketplaces — promotional tags, availability states, shipping offers, quality certifications, and pricing labels.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "ecommerce", "product", "sale", "promotion", "shop", "labels"],
        previewUrl: "/SpecialElements/Badges/EcommerceBadges",
        code: {
            tsx: getCode("src/components/SpecialElements/Badges/tsx/EcommerceBadges.tsx"),
            jsx: getCode("src/components/SpecialElements/Badges/jsx/EcommerceBadges.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Badges/EcommerceBadges/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Ideal for product cards, listing pages, cart items, and any commerce interface needing prominent product status communication.",
        bestPractices: "Limit promotional badges to 1-2 per product card to avoid visual overload. Use SALE and HOT together sparingly — they compete for attention.",
        whyMatters: "Product labels are conversion drivers. A well-placed SALE or Best Seller badge directly influences purchase decisions and time-on-page metrics.",
        faqs: [
            { question: "Are these dark-themed only?", answer: "Yes, by design — the dark theme makes the vivid colored labels pop with maximum contrast." },
            { question: "Can I add a percentage to the SALE badge?", answer: "Yes — extend the badge to accept a value prop and render it inline, e.g. SALE · 30% OFF." },
        ],
    },
    {
        id: "social-badges",
        name: "Social Badges",
        description: "Creator and social platform badge system — verification tiers, creator roles, account types, community roles, achievement badges, and live activity indicators.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "social", "verified", "creator", "profile", "community", "roles"],
        previewUrl: "/SpecialElements/Badges/SocialBadges",
        code: {
            tsx: getCode("src/components/SpecialElements/Badges/tsx/SocialBadges.tsx"),
            jsx: getCode("src/components/SpecialElements/Badges/jsx/SocialBadges.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Badges/SocialBadges/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Use in social platforms, community tools, creator marketplaces, and any product with user roles, tiers, or public profiles.",
        bestPractices: "Keep verification badges compact — they appear inline with usernames. Use gradient badges only for top-tier account types to preserve their premium signal.",
        whyMatters: "Role and verification badges communicate trust and authority instantly. They reduce the cognitive load of evaluating a user's credibility.",
        faqs: [
            { question: "How is the Verified badge different from Verified+?", answer: "Verified uses a sky-blue ring (platform verification), Verified+ uses gold (top creator status). Both use CheckCircle from lucide-react." },
            { question: "Can Live Now pulse on mount?", answer: "Yes — it uses a Framer Motion loop animation. You can control the pulse duration via the transition prop." },
        ],
    },
    {
        id: "animated-badges",
        name: "Animated Badges",
        description: "Motion-forward badge showcase — live indicators with ripple effects, shimmer loading states, hover interactions (flip, glow, shimmer swipe, magnetic pull), countdown timers, and notification animations.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "animated", "motion", "live", "loading", "hover", "framer-motion"],
        previewUrl: "/SpecialElements/Badges/AnimatedBadges",
        code: {
            tsx: getCode("src/components/SpecialElements/Badges/tsx/AnimatedBadges.tsx"),
            jsx: getCode("src/components/SpecialElements/Badges/jsx/AnimatedBadges.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Badges/AnimatedBadges/page.tsx") },
        dependencies: ["framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Use for live-streaming interfaces, real-time dashboards, notification systems, and any product that needs animated feedback in badge form.",
        bestPractices: "Use loop animations only for genuinely live/active states — constant motion in static contexts creates distraction. Hover interactions should be subtle enough to feel responsive, not jarring.",
        whyMatters: "Animation in badges adds a layer of real-time feedback that static badges cannot provide. A pulsing LIVE badge communicates immediacy that no static label can match.",
        faqs: [
            { question: "Will these impact performance?", answer: "All animations use transform and opacity only — GPU-composited properties that don't trigger layout or paint." },
            { question: "Can I disable animations globally?", answer: "Yes — wrap with Framer Motion's MotionConfig with reducedMotion='user' to respect system accessibility preferences." },
        ],
    },
];
