import { Component } from "../types";

export const badgesComponentsMetadata: Component[] = [
    {
        id: "classic-badges",
        name: "Classic Badges",
        description: "Comprehensive badge system with 10+ variations — glassy status, dot indicators, micro glow, pastel chips, tech tags, icon pills, blur tags, contrast labels, neon edges, and glossy gradients. Supports dark/light theme, compact mode, and custom accent color.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "classic", "status", "tags", "chips", "labels", "indicators", "dark", "light"],
        previewUrl: "/SpecialElements/Badges/ClassicBadges",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — dark for dashboards, light for minimal interfaces." },
            { name: "compact", type: "boolean", default: "false", description: "Hides the Status Indicators section and tightens spacing." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Custom accent color for Micro Glow badges." },
        ],
    },
    {
        id: "status-badges",
        name: "Status Badges",
        description: "System/app status badge collection — service health, notification counts, priority tags, connection states, user availability, and progress indicators. Light theme, dashboard-ready.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "status", "health", "notification", "priority", "availability", "dashboard"],
        previewUrl: "/SpecialElements/Badges/StatusBadges",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "ecommerce-badges",
        name: "Ecommerce Badges",
        description: "Bold product label system for shops and marketplaces — promotional tags, availability states, shipping offers, quality certifications, and pricing labels.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "ecommerce", "product", "sale", "promotion", "shop", "labels"],
        previewUrl: "/SpecialElements/Badges/EcommerceBadges",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "social-badges",
        name: "Social Badges",
        description: "Creator and social platform badge system — verification tiers, creator roles, account types, community roles, achievement badges, and live activity indicators.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "social", "verified", "creator", "profile", "community", "roles"],
        previewUrl: "/SpecialElements/Badges/SocialBadges",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [],
    },
    {
        id: "animated-badges",
        name: "Animated Badges",
        description: "Motion-forward badge showcase — live indicators, shimmer loading states, hover interactions (flip, glow, shimmer, magnetic), countdown timers, and notification animations.",
        category: "Special Elements",
        installType: "cli",
        tags: ["badges", "animated", "motion", "live", "loading", "hover", "framer-motion"],
        previewUrl: "/SpecialElements/Badges/AnimatedBadges",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [],
    },
];
