import { Component } from "../types";

export const breadcrumbsComponentsMetadata: Component[] = [
    {
        id: "classic-breadcrumbs",
        name: "Classic Breadcrumbs",
        description: "Foundational breadcrumb collection — slash, chevron, dot separators, pill and glassy chip styles, arrow ribbon, numbered steps, icon-prefix, back link, and floating frosted-glass breadcrumb. 10+ variants.",
        category: "Special Elements",
        installType: "cli",
        tags: ["breadcrumb", "navigation", "classic", "pill", "arrow", "separator", "floating", "minimal"],
        previewUrl: "/SpecialElements/Breadcrumbs/ClassicBreadcrumbs",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [],
    },
    {
        id: "app-breadcrumbs",
        name: "App Breadcrumbs",
        description: "Breadcrumb patterns for SaaS apps and internal tools — workspace context, team/project paths, collapsible deep nav, status-aware crumbs, inline editable page names, notification badges, and breadcrumb action bars.",
        category: "Special Elements",
        installType: "cli",
        tags: ["breadcrumb", "saas", "app", "workspace", "dashboard", "status", "editable", "navigation"],
        previewUrl: "/SpecialElements/Breadcrumbs/AppBreadcrumbs",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [],
    },
    {
        id: "ecommerce-breadcrumbs",
        name: "Ecommerce Breadcrumbs",
        description: "Breadcrumb patterns for shop and product interfaces — category paths, chip tags, item counts, image thumbnails, inline price and rating, checkout steppers, progress indicators, mobile back links, and dropdown path pickers.",
        category: "Special Elements",
        installType: "cli",
        tags: ["breadcrumb", "ecommerce", "shop", "product", "checkout", "stepper", "mobile", "category"],
        previewUrl: "/SpecialElements/Breadcrumbs/EcommerceBreadcrumbs",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [],
    },
    {
        id: "docs-breadcrumbs",
        name: "Docs Breadcrumbs",
        description: "Breadcrumb patterns for documentation sites and developer tools — monospace file paths, terminal-style prompts, versioned docs, section-aware trails, GitHub repo/PR/issue paths, searchable crumb pickers, and reading progress indicators.",
        category: "Special Elements",
        installType: "cli",
        tags: ["breadcrumb", "docs", "developer", "monospace", "terminal", "github", "versioned", "search"],
        previewUrl: "/SpecialElements/Breadcrumbs/DocsBreadcrumbs",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [],
    },
];
