import { getCode } from "../getCode";
import { Component } from "../types";

export const breadcrumbsComponents: Component[] = [
    {
        id: "classic-breadcrumbs",
        name: "Classic Breadcrumbs",
        description: "Foundational breadcrumb collection — slash, chevron, dot separators, pill and glassy chip styles, arrow ribbon, numbered steps, icon-prefix, back link, and floating frosted-glass breadcrumb. 10+ variants.",
        category: "Special Elements",
        installType: "cli",
        tags: ["breadcrumb", "navigation", "classic", "pill", "arrow", "separator", "floating", "minimal"],
        previewUrl: "/SpecialElements/Breadcrumbs/ClassicBreadcrumbs",
        code: {
            tsx: getCode("src/components/SpecialElements/Breadcrumbs/tsx/ClassicBreadcrumbs.tsx"),
            jsx: getCode("src/components/SpecialElements/Breadcrumbs/jsx/ClassicBreadcrumbs.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Breadcrumbs/ClassicBreadcrumbs/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — dark for app/dashboard backgrounds, light for white-background pages." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Applied to active crumb text, hover underlines, arrow fill, numbered circle, pill active bg." },
            { name: "separator", type: '"slash" | "chevron" | "dot"', default: '"slash"', description: "Highlights the matching separator variant with an accent ring and uses that character across all separator-style breadcrumbs." },
            { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Scales all breadcrumb text — sm=text-xs, md=text-sm, lg=text-base." },
        ],
        whenToUse: "Use when you need a versatile breadcrumb foundation — pick any variant as a starting point. SlashBreadcrumb and ChevronBreadcrumb cover 80% of use cases. FloatingBreadcrumb fits top-of-page sticky contexts.",
        bestPractices: "Keep breadcrumbs to 4 levels max before collapsing the middle. Always make parent crumbs clickable — the current page crumb should not be a link.",
        whyMatters: "Breadcrumbs are the primary wayfinding tool in deep hierarchies. A consistent, well-animated trail reduces disorientation and improves navigation confidence.",
        faqs: [
            { question: "Which separator should I use?", answer: "Chevron for apps and dashboards, slash for file-path contexts, dot for editorial/blog layouts where separators should feel lightweight." },
            { question: "How does FloatingBreadcrumb work?", answer: "It's a frosted glass pill that expands on hover via AnimatePresence — revealing the full path. Collapses back on mouse leave." },
        ],
    },
    {
        id: "app-breadcrumbs",
        name: "App Breadcrumbs",
        description: "Breadcrumb patterns for SaaS apps and internal tools — workspace context, team/project paths, collapsible deep nav, status-aware crumbs, inline editable page names, notification badges, and breadcrumb action bars.",
        category: "Special Elements",
        installType: "cli",
        tags: ["breadcrumb", "saas", "app", "workspace", "dashboard", "status", "editable", "navigation"],
        previewUrl: "/SpecialElements/Breadcrumbs/AppBreadcrumbs",
        code: {
            tsx: getCode("src/components/SpecialElements/Breadcrumbs/tsx/AppBreadcrumbs.tsx"),
            jsx: getCode("src/components/SpecialElements/Breadcrumbs/jsx/AppBreadcrumbs.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Breadcrumbs/AppBreadcrumbs/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — dark for internal tools, light for client-facing dashboards." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Applied to workspace avatar, tab underline, status dot glow, notification badge, and action button hover." },
            { name: "workspaceName", type: "string", default: '"Acme Corp"', description: "Org/workspace name shown in WorkspaceBreadcrumb and TeamspaceBreadcrumb." },
            { name: "maxDepth", type: "number", default: "2", description: "Number of crumbs visible on each side of the '···' collapse in DeepNavBreadcrumb (1–3)." },
        ],
        whenToUse: "Perfect for Notion-style tools, project management apps, admin panels, and any product with workspace/org hierarchy. DeepNavBreadcrumb handles 5+ level paths gracefully.",
        bestPractices: "Use WorkspaceBreadcrumb with real org avatars for personalization. EditableBreadcrumb works best when the last crumb is a page/doc name the user controls.",
        whyMatters: "In deep SaaS apps, users constantly need to know where they are and how to get back — a context-aware breadcrumb reduces friction and supports multi-level navigation without full page loads.",
        faqs: [
            { question: "How does EditableBreadcrumb work?", answer: "Clicking the last crumb swaps it for an inline input. Pressing Enter or blurring the field commits the new name back to display mode." },
            { question: "Can DeepNavBreadcrumb handle dynamic paths?", answer: "Yes — pass an array of crumb objects and it automatically collapses the middle items into an expandable '···' pill when the path exceeds 4 levels." },
        ],
    },
    {
        id: "ecommerce-breadcrumbs",
        name: "Ecommerce Breadcrumbs",
        description: "Breadcrumb patterns for shop and product interfaces — category paths, chip tags, item counts, image thumbnails, inline price and rating, checkout steppers, progress indicators, mobile back links, and dropdown path pickers.",
        category: "Special Elements",
        installType: "cli",
        tags: ["breadcrumb", "ecommerce", "shop", "product", "checkout", "stepper", "mobile", "category"],
        previewUrl: "/SpecialElements/Breadcrumbs/EcommerceBreadcrumbs",
        code: {
            tsx: getCode("src/components/SpecialElements/Breadcrumbs/tsx/EcommerceBreadcrumbs.tsx"),
            jsx: getCode("src/components/SpecialElements/Breadcrumbs/jsx/EcommerceBreadcrumbs.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Breadcrumbs/EcommerceBreadcrumbs/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — dark for boutique/luxury shops, light for clean minimal storefronts." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Applied to active chip fill, checkout stepper current step, progress bar fill, and step number circle." },
            { name: "currency", type: "string", default: '"$"', description: "Currency symbol shown before prices in PriceCrumb — e.g. '€', '£', '₹'." },
            { name: "checkoutStep", type: "number", default: "2", description: "Active step in CheckoutStepper, ProgressCrumb, and StepNumberCrumb (1=Cart, 2=Shipping, 3=Payment, 4=Review). Steps before this are marked done." },
        ],
        whenToUse: "Use on product pages, category listing pages, and checkout flows. MobileCrumb covers the dominant mobile pattern. CheckoutStepper and ProgressCrumb work as ordered-flow indicators.",
        bestPractices: "On product pages, keep breadcrumbs above the fold and below the header. On mobile, collapse to MobileCrumb (back link only). In checkout, always show completed steps as clickable to allow going back.",
        whyMatters: "Ecommerce breadcrumbs serve a dual role — navigation and conversion. Clear category paths reduce bounce rate, and step indicators in checkout reduce abandonment by making progress visible.",
        faqs: [
            { question: "How does CheckoutStepper mark completed steps?", answer: "Each step has a state: 'upcoming' | 'current' | 'done'. Done steps show an animated emerald check circle. Click any done step to go back." },
            { question: "Can ImageCrumb use real product images?", answer: "Yes — replace the colored placeholder squares with <img> tags pointed at your product thumbnail URLs." },
        ],
    },
    {
        id: "docs-breadcrumbs",
        name: "Docs Breadcrumbs",
        description: "Breadcrumb patterns for documentation sites and developer tools — monospace file paths, terminal-style prompts, versioned docs, section-aware trails, GitHub repo/PR/issue paths, searchable crumb pickers, and reading progress indicators.",
        category: "Special Elements",
        installType: "cli",
        tags: ["breadcrumb", "docs", "developer", "monospace", "terminal", "github", "versioned", "search"],
        previewUrl: "/SpecialElements/Breadcrumbs/DocsBreadcrumbs",
        code: {
            tsx: getCode("src/components/SpecialElements/Breadcrumbs/tsx/DocsBreadcrumbs.tsx"),
            jsx: getCode("src/components/SpecialElements/Breadcrumbs/jsx/DocsBreadcrumbs.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/SpecialElements/Breadcrumbs/DocsBreadcrumbs/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: "Color theme — dark for developer tools, light for public-facing docs sites." },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Applied to terminal prompt arrows, version badge, reading progress bar, section § symbol, and active crumb highlight." },
            { name: "repoName", type: "string", default: '"ui-library"', description: "Repository name shown in RepoCrumb and PRCrumb — replace with your actual repo name." },
            { name: "version", type: "string", default: '"v3.2"', description: "Current docs version shown in VersionedCrumb. Dropdown auto-derives previous minor and legacy versions from this string." },
        ],
        whenToUse: "Use in documentation sites, developer portals, GitHub-style platforms, and any product aimed at technical users. TerminalCrumb and MonoPathCrumb signal developer context immediately.",
        bestPractices: "Use VersionedCrumb whenever your docs have multiple versions in active use. AnnotatedCrumb works best on landing/index pages where page counts help users choose a section.",
        whyMatters: "Developer docs have the most demanding navigation requirements — users jump between deeply nested pages constantly. Familiar monospace and terminal aesthetics build instant trust with technical audiences.",
        faqs: [
            { question: "How does SearchableCrumb work?", answer: "Clicking any non-current crumb opens an inline search input. Typing filters child pages, pressing Enter navigates. Built with AnimatePresence for smooth open/close." },
            { question: "Can ReadingProgress hook into real scroll position?", answer: "Yes — replace the mount animation with a scroll event listener that maps scrollY to a 0–100% width value on the progress bar." },
        ],
    },
];
