import { Component } from "../types";

export const carouselComponentsMetadata: Component[] = [
    {
        id: "depth",
        name: "Depth Parallax",
        description: "Carousel with depth parallax scrolling effects.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "parallax", "depth", "scroll"],
        previewUrl: "/SpecialElements/Carousels/Depth",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "images", type: "string[]", default: "[url1, url2, ...]", description: "Array of image URLs to display." },
            { name: "labels", type: "string[]", default: "[]", description: "Optional labels for each slide." },
            { name: "defaultIndex", type: "number", default: "0", description: "Initial active slide index." },
            { name: "containerBgColor", type: "string", default: "#000000", description: "Background color of the container." },
            { name: "height", type: "string", default: "16rem", description: "Height of the carousel container." },
            { name: "maxWidth", type: "string", default: "28rem", description: "Maximum width of the container." },
        ],
    },
    {
        id: "infinite",
        name: "Infinite Loop",
        description: "Seamless infinite scrolling carousel with auto-play.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "infinite", "loop", "scroll", "marquee"],
        previewUrl: "/SpecialElements/Carousels/Infinite",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[url1, url2, ...]", description: "Array of image URLs to loop." },
            { name: "animationDuration", type: "number", default: "20", description: "Duration of one complete loop in seconds." },
            { name: "imageHeight", type: "string", default: "6rem", description: "Height of each image card." },
            { name: "imageWidth", type: "string", default: "8rem", description: "Width of each image card." },
            { name: "imageGap", type: "string", default: "0.5rem", description: "Gap between image cards." },
            { name: "maxWidth", type: "string", default: "32rem", description: "Maximum width of the carousel." },
        ],
    },
    {
        id: "story",
        name: "Vertical Story",
        description: "Vertical story-style carousel with auto-advancing progress indicators.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "story", "vertical", "progress", "instagram"],
        previewUrl: "/SpecialElements/Carousels/Story",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[url1, url2, ...]", description: "Array of image URLs to display." },
            { name: "labels", type: "{title?: string, subtitle?: string}[]", default: "[]", description: "Optional labels per slide." },
            { name: "autoPlayInterval", type: "number", default: "100", description: "Auto-play interval in milliseconds." },
            { name: "height", type: "string", default: "24rem", description: "Height of the carousel." },
            { name: "width", type: "string", default: "16rem", description: "Width of the carousel." },
        ],
    },
    {
        id: "focus-card",
        name: "Focus Card",
        description: "Centered 3-card carousel — active card enlarged and elevated with serif italic label and counter.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "focus", "centered", "editorial", "card"],
        previewUrl: "/SpecialElements/Carousels/FocusCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "FocusItem[]", default: "DEFAULT_ITEMS (12 items)", description: "Array of items with id, image URL, label, and category." },
            { name: "defaultActive", type: "number", default: "5", description: "Index of the initially active card." },
            { name: "bgColor", type: "string", default: "#e8e8ea", description: "Background color of the container." },
        ],
    },
    {
        id: "travel-cards",
        name: "Travel Cards",
        description: "Tall portrait card carousel with metadata overlay — title, duration, and star rating per card.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "cards", "travel", "portrait", "metadata"],
        previewUrl: "/SpecialElements/Carousels/TravelCards",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "TravelItem[]", default: "DEFAULT_ITEMS (6 items)", description: "Array of items with id, image URL, title, days, and rating." },
            { name: "defaultActive", type: "number", default: "1", description: "Index of the initially active card." },
            { name: "accentColor", type: "string", default: "#14b8a6", description: "Accent color for the active card border and dot indicator." },
        ],
    },
    {
        id: "tilt-gallery",
        name: "Tilt Gallery",
        description: "Editorial row of slightly tilted images that straighten and elevate on hover.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "gallery", "tilt", "hover", "editorial"],
        previewUrl: "/SpecialElements/Carousels/TiltGallery",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "TiltItem[]", default: "DEFAULT_ITEMS (5 items)", description: "Array of items with id, image URL, and optional caption." },
            { name: "heading", type: "string", default: "\"Find your dream\"", description: "First line of the heading." },
            { name: "headingAccent", type: "string", default: "\"aesthetic\"", description: "Bold accented second heading line." },
            { name: "accentColor", type: "string", default: "#166534", description: "Color of the bold accent heading." },
            { name: "bgColor", type: "string", default: "#f5f5f5", description: "Background color of the container." },
        ],
    },
    {
        id: "perspective-3d",
        name: "3D Perspective",
        description: "3D Y-axis rotation carousel — side cards fold back in perspective with a CTA button for the active card.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "3d", "perspective", "rotation", "product"],
        previewUrl: "/SpecialElements/Carousels/Perspective3D",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "PerspectiveItem[]", default: "DEFAULT_ITEMS (5 items)", description: "Array of items with id, image URL, title, and optional subtitle." },
            { name: "defaultActive", type: "number", default: "2", description: "Index of the initially active card." },
            { name: "heading", type: "string", default: "\"Choose Your Piece\"", description: "Main heading above the carousel." },
            { name: "ctaLabel", type: "string", default: "\"Add To Cart\"", description: "Label for the action button." },
            { name: "accentColor", type: "string", default: "#166534", description: "Color for the CTA button." },
            { name: "bgColor", type: "string", default: "#f0f0f6", description: "Background color of the container." },
        ],
    },
    {
        id: "curve-arc",
        name: "Curve Arc",
        description: "Wide 3D arc carousel — 5 cards arranged on a curved plane with depth-fading side cards and a CTA action button.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "3d", "arc", "curve", "perspective", "product"],
        previewUrl: "/SpecialElements/Carousels/CurveArc",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "CurveItem[]", default: "DEFAULT_ITEMS (7 items)", description: "Array of items with id, image URL, title, and optional subtitle." },
            { name: "defaultActive", type: "number", default: "3", description: "Index of the initially active card." },
            { name: "heading", type: "string", default: "\"Choose Your Piece\"", description: "Main heading above the carousel." },
            { name: "subheading", type: "string", default: "\"Explore our curated collection\"", description: "Subtitle below the heading." },
            { name: "ctaLabel", type: "string", default: "\"Add To Cart\"", description: "Label for the action button." },
            { name: "accentColor", type: "string", default: "#166534", description: "Color for heading and CTA button border." },
        ],
    },
    {
        id: "morph-shape",
        name: "Morph Shape",
        description: "Organic blob carousel — the center card morphs between fluid border-radius shapes on each navigation, with side cards at slight angles.",
        category: "Special Elements",
        installType: "cli",
        tags: ["carousel", "blob", "morph", "organic", "shape", "creative"],
        previewUrl: "/SpecialElements/Carousels/MorphShape",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "items", type: "MorphItem[]", default: "DEFAULT_ITEMS (5 items)", description: "Array of items with id, image URL, and label." },
            { name: "defaultActive", type: "number", default: "0", description: "Index of the initially active card." },
            { name: "eyebrow", type: "string", default: "\"Convenient Setup\"", description: "Small uppercase label above the heading." },
            { name: "heading", type: "string", default: "\"Hangtimes just got an upgrade.\"", description: "Main heading text." },
            { name: "subheading", type: "string", default: "\"Games can be hosted...\"", description: "Subtitle below the heading." },
            { name: "accentColor", type: "string", default: "#2d6a4f", description: "Color for the eyebrow label." },
            { name: "autoPlayInterval", type: "number", default: "2000", description: "Auto-advance interval in milliseconds." },
        ],
    },
];
