import { Component } from "../types";

export const tabComponentsMetadata: Component[] = [
    {
        id: "glassa",
        name: "Glass Floating",
        description: "Glassmorphism tabs with floating effect and animated background images.",
        category: "Special Elements",
        installType: "cli",
        tags: ["tabs", "glass", "floating", "glassmorphism"],
        previewUrl: "/SpecialElements/Tabs/Glass",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "tabs", type: "TabItem[]", default: "[{id: '1', label: 'Option 1'}, ...]", description: "Array of tab items with id and label." },
            { name: "backgroundImages", type: "string[]", default: "[url1, url2, url3]", description: "Background image URLs that transition on tab change." },
            { name: "defaultActive", type: "number", default: "0", description: "Index of the initially active tab." },
            { name: "containerHeight", type: "string", default: "16rem", description: "Height of the container." },
            { name: "containerMaxWidth", type: "string", default: "28rem", description: "Maximum width of the container." },
            { name: "borderRadius", type: "string", default: "1rem", description: "Border radius of the container." },
            { name: "buttonTextColor", type: "string", default: "#ffffff", description: "Text color of tab buttons." },
            { name: "activeIndicatorBgColor", type: "string", default: "rgba(255,255,255,0.3)", description: "Background of the active indicator." },
        ],
    },
    {
        id: "image",
        name: "Image Backed",
        description: "Tabs with background images that change on selection with smooth transitions.",
        category: "Special Elements",
        installType: "cli",
        tags: ["tabs", "image", "background", "animated"],
        previewUrl: "/SpecialElements/Tabs/Image",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "tabs", type: "TabItem[]", default: "[{id: '1', label: 'Scene 1', image?: url}, ...]", description: "Array of tab items with id, label, and optional per-tab image." },
            { name: "images", type: "string[]", default: "[url1, url2, ...]", description: "Fallback array of image URLs if tabs don't have images." },
            { name: "defaultActive", type: "number", default: "0", description: "Index of the initially active tab." },
            { name: "containerBgColor", type: "string", default: "#18181b", description: "Background color of the container." },
            { name: "containerHeight", type: "string", default: "10rem", description: "Height of the container." },
            { name: "containerMaxWidth", type: "string", default: "32rem", description: "Maximum width of the container." },
            { name: "imageOpacity", type: "number", default: "0.5", description: "Opacity of background images (0–1)." },
            { name: "activeButtonBgColor", type: "string", default: "#ffffff", description: "Background color of the active tab button." },
        ],
    },
    {
        id: "swipe",
        name: "Swipe (Mobile)",
        description: "Mobile-optimized swipeable tabs with spring physics and drag gestures.",
        category: "Special Elements",
        installType: "cli",
        tags: ["tabs", "swipe", "mobile", "gesture"],
        previewUrl: "/SpecialElements/Tabs/Swipe",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "tabs", type: "TabItem[]", default: "[{id: '1', label: 'View 1', content: '...'}, ...]", description: "Array of tab items with id, label, and optional content node." },
            { name: "defaultActive", type: "number", default: "0", description: "Index of the initially active tab." },
            { name: "containerBgColor", type: "string", default: "#ffffff", description: "Background color of the container." },
            { name: "containerMaxWidth", type: "string", default: "28rem", description: "Maximum width of the container." },
            { name: "activeTabTextColor", type: "string", default: "#2563eb", description: "Text color and underline color of the active tab." },
            { name: "contentHeight", type: "string", default: "10rem", description: "Height of the content area." },
            { name: "springStiffness", type: "number", default: "260", description: "Spring animation stiffness." },
            { name: "springDamping", type: "number", default: "28", description: "Spring animation damping." },
        ],
    },
    {
        id: "apple-dock",
        name: "Apple Dock",
        description: "macOS-style magnification dock with spring physics — icons scale based on cursor proximity.",
        category: "Special Elements",
        installType: "cli",
        tags: ["tabs", "dock", "apple", "spring", "magnification"],
        previewUrl: "/SpecialElements/Tabs/AppleDock",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "DockItem[]", default: "DEFAULT_ITEMS", description: "Array of dock items with id, label, emoji, bg gradient, and content node." },
            { name: "defaultActive", type: "string", default: "items[0].id", description: "ID of the initially active item." },
            { name: "accentColor", type: "string", default: "#a78bfa", description: "Color of the active dot indicator under icons." },
            { name: "dockBg", type: "string", default: "rgba(255,255,255,0.14)", description: "Background of the dock shelf pill." },
        ],
    },
    {
        id: "floating-nav",
        name: "Floating Nav",
        description: "Floating pill navigation with a neon pip indicator above the active icon.",
        category: "Special Elements",
        installType: "cli",
        tags: ["tabs", "floating", "nav", "pill", "mobile"],
        previewUrl: "/SpecialElements/Tabs/FloatingNav",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "NavItem[]", default: "DEFAULT_ITEMS", description: "Array of nav items with id, label, icon SVG, and content node." },
            { name: "defaultActive", type: "string", default: "items[0].id", description: "ID of the initially active item." },
            { name: "accentColor", type: "string", default: "#a78bfa", description: "Color used for the active pip, icon, and label." },
            { name: "pillBg", type: "string", default: "rgba(18,18,24,0.95)", description: "Background color of the floating pill." },
        ],
    },
    {
        id: "neumorphic",
        name: "Neumorphic",
        description: "Soft UI neumorphic circle buttons with inset shadow activation state.",
        category: "Special Elements",
        installType: "cli",
        tags: ["tabs", "neumorphic", "soft-ui", "light"],
        previewUrl: "/SpecialElements/Tabs/Neumorphic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "NeuItem[]", default: "DEFAULT_ITEMS", description: "Array of items with id, label, icon SVG, and content node." },
            { name: "defaultActive", type: "string", default: "items[0].id", description: "ID of the initially active item." },
            { name: "accentColor", type: "string", default: "#3b82f6", description: "Color for active icons, labels, and progress pill." },
            { name: "bgColor", type: "string", default: "#e0e5ec", description: "Base neumorphic background color." },
        ],
    },
];

