import { Component } from "../types";

export const bentoGridComponentsMetadata: Component[] = [
    {
        id: "layout-editorial",
        name: "Editorial Layout",
        description: "Asymmetric fashion-inspired bento grid with sharp edges and editorial styling, branded for Uilora.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "editorial", "fashion", "asymmetric"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Uilora Design System", description: "Hero section title displayed over the image." },
            { name: "description", type: "string", default: "Crafting beautiful, production-ready components for the modern web.", description: "Hero section subtitle/description." },
            { name: "accentColor", type: "string", default: "bg-orange-600", description: "Tailwind background class for the quote accent block (e.g. 'bg-orange-600', 'bg-indigo-500')." },
        ],
    },
    {
        id: "layout-swiss",
        name: "Swiss Layout",
        description: "Clean Swiss design bento grid with precise typography and minimal aesthetics, branded for Uilora.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "swiss", "minimal", "typography"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutSwiss",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "UILORA", description: "Large header title text (displayed in 6xl bold)." },
            { name: "description", type: "string", default: "Precision-crafted component library for modern web interfaces.", description: "Main block description text." },
            { name: "accentColor", type: "string", default: "#ff3b30", description: "Accent color hex for the floating circle and bottom dot highlight." },
        ],
    },
    {
        id: "layout-wabi-sabi",
        name: "Wabi Sabi Layout",
        description: "Japanese-inspired bento grid with wabi-sabi aesthetics, imperfections, and Uilora branding.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "wabi-sabi", "japanese", "imperfect"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutWabiSabi",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Uilora Studio", description: "Title overlaid on the main image in large serif italic." },
            { name: "quote", type: "string", default: '"Crafted with intention, refined with care."', description: "Italic serif quote displayed in the text block." },
            { name: "accentColor", type: "string", default: "#4A5D4F", description: "Background color of the small color accent block (hex)." },
        ],
    },
    {
        id: "layout-botanic",
        name: "Botanic Layout",
        description: "Organic bento grid with botanical themes, curved shapes, and Uilora branding.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "botanic", "organic", "curved"],
        previewUrl: "/Grids&Layouts/BentoGrids/LayoutBotanic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Uilora", description: "Main title displayed in serif italic over the image." },
            { name: "description", type: "string", default: "Where beautiful components grow.", description: "Subtitle text displayed below the title on the image." },
            { name: "accentColor", type: "string", default: "#1a3c28", description: "Primary dark green color used for backgrounds, text, and gradient overlays (hex)." },
        ],
    },
    {
        id: "uilora-service-grid",
        name: "Uilora Service Grid",
        description: "3×2 pastel bento with unique geometric SVG illustrations per card — mint, lavender, dark (featured), gray, light-blue, and cream variants.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "pastel", "geometric", "services", "portfolio", "minimal"],
        previewUrl: "/Grids&Layouts/BentoGrids/UiloraServiceGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Focus on developer experience", description: "Title text for the dark featured card (center-right)." },
            { name: "description", type: "string", default: "Prioritizing clean APIs and intuitive integration, ensuring developers ship beautiful UIs with Uilora.", description: "Description text for the dark featured card." },
            { name: "accentColor", type: "string", default: "#22d3ee", description: "Color of the crosshair/plus symbol on the dark featured card." },
        ],
    },
    {
        id: "uilora-light-bento",
        name: "Uilora Light Bento",
        description: "Light fintech-inspired bento grid with portfolio chart, donut pie, transaction list, code block, and integration logo grid on a soft gray background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "light", "fintech", "dashboard", "portfolio", "saas"],
        previewUrl: "/Grids&Layouts/BentoGrids/UiloraLightBento",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Customize at will", description: "Headline shown in the accent-colored CTA card (bottom-left)." },
            { name: "description", type: "string", default: "For anyone to start building their design system, no matter the size of your team.", description: "Description shown below the title in the CTA card." },
            { name: "accentColor", type: "string", default: "#bbf451", description: "Lime/neon accent hex — used for the CTA card background, portfolio badge, donut chart segment, and expected-reach icon." },
        ],
    },
    {
        id: "uilora-feature-grid",
        name: "Uilora Feature Grid",
        description: "Dark bento feature section with animated chart, component table, shield visual, and framework integration hub — inspired by fintech UI aesthetics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "dark", "features", "dashboard", "fintech", "saas"],
        previewUrl: "/Grids&Layouts/BentoGrids/UiloraFeatureGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Essential tools for your design growth", description: "Main heading. The last two words are rendered in muted white for a two-tone effect." },
            { name: "description", type: "string", default: "Unlock your design potential with Uilora's powerful suite of 700+ components designed to drive your product success.", description: "Subtitle below the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex color used for the glow in the shield/reliability card." },
        ],
    },
    {
        id: "uilora-tags-bento",
        name: "Uilora Tags Bento",
        description: "Light bento grid with colorful rotated tag cloud, interactive package manager install UI, avatar grid, SWOT quadrant, and stacked component preview cards.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["bento", "light", "tags", "install", "saas", "developer", "community"],
        previewUrl: "/Grids&Layouts/BentoGrids/UiloraTagsBento",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Get started in seconds", description: "Heading shown in the install card." },
            { name: "description", type: "string", default: "Install Uilora and add production-ready components to your project instantly.", description: "Subtext below the install card heading." },
            { name: "accentColor", type: "string", default: "#a78bfa", description: "Accent hex used for active package manager tab, CTA button, avatar badge, and stacked card hover hint." },
        ],
    },
];
