import { Component } from "../types";

export const featureGridComponentsMetadata: Component[] = [
    {
        id: "cinematic-grid",
        name: "Cinematic Stack",
        description: "Sticky scroll feature grid with full-bleed cinematic image cards, Uilora-branded feature content, and smooth whileInView animations on a black background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "cinematic", "sticky", "scroll", "dark"],
        previewUrl: "/Grids&Layouts/FeatureGrids/CinematicGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Why teams choose Uilora", description: "Section heading rendered in the top header block." },
            { name: "description", type: "string", default: "Every component is crafted to be production-ready, accessible, and beautiful out of the box.", description: "Subtitle shown below the section heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for the label badge on each sticky card and the header eyebrow." },
        ],
    },
    {
        id: "elastic-grid",
        name: "Elastic Expansion",
        description: "Hover-to-expand accordion feature grid with image backgrounds, vertical labels on inactive panels, and Uilora-branded content on a light gray background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "elastic", "expansion", "accordion", "hover"],
        previewUrl: "/Grids&Layouts/FeatureGrids/ElasticGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Everything your design system needs", description: "Section heading displayed above the accordion." },
            { name: "description", type: "string", default: "Uilora brings structure, speed, and craft to every product you ship.", description: "Subtitle shown below the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for label badges on expanded panels and the eyebrow text." },
        ],
    },
    {
        id: "minimal-grid",
        name: "Ethereal Minimal",
        description: "Editorial 2-column photo grid with desaturated-to-color hover, serif italic headings, and Uilora-branded feature items on a white background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "minimal", "editorial", "photo", "light"],
        previewUrl: "/Grids&Layouts/FeatureGrids/MinimalGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Crafted with intention", description: "Large heading displayed in the top-left of the section header." },
            { name: "description", type: "string", default: "Uilora components aren't generated — they're designed, reviewed, and refined until they feel right.", description: "Short description shown top-right opposite the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for the numbered labels above each feature item." },
        ],
    },
    {
        id: "grid-scatter-deck",
        name: "Scatter Deck",
        description: "Draggable card deck with Uilora-branded cards (Uilora, Motion, TypeScript, Design, 700+), spring physics, and a crosshair-grid background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "scatter", "deck", "drag", "interactive"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridScatterDeck",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Drag. Explore. Build.", description: "Heading displayed at the top of the scatter deck." },
            { name: "description", type: "string", default: "Uilora gives you every piece — drag them into your stack.", description: "Subtitle below the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for the eyebrow label and hover hint color." },
        ],
    },
    {
        id: "uilora-hero-feature",
        name: "Uilora Hero Feature",
        description: "Split hero feature section with gradient headline, CTA buttons, and 3 staggered feature cards — each with a pastel dot-grid background, iOS-style gradient icon, title and description.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "hero", "cards", "saas", "light", "gradient"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraHeroFeature",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Build faster: ship with an all-in-one library.", description: "Main headline. The phrase 'all-in-one' is automatically rendered in a gradient — include it in your title string to activate the effect." },
            { name: "description", type: "string", default: "Production-ready component library. Ship beautiful, accessible UIs instantly with Uilora's 700+ components.", description: "Subtitle displayed below the headline." },
            { name: "accentColor", type: "string", default: "#f472b6", description: "Hex color for the gradient on 'all-in-one', the badge icon, the stat card, and CTA button hover." },
        ],
    },
    {
        id: "uilora-feature-trio",
        name: "Uilora Feature Trio",
        description: "Centered feature section with large heading and three equal cards — each featuring a unique inline SVG illustration (shield, folder, component grid) on a light gradient background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "cards", "illustration", "saas", "light", "minimal"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraFeatureTrio",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Unlock the Full Potential of Your Component Library", description: "Section heading. The phrase 'Component Library' is highlighted in an emerald gradient." },
            { name: "description", type: "string", default: "Explore Uilora's core benefits that make UI development fast, accessible, and production-ready.", description: "Subtitle shown below the heading." },
            { name: "accentColor", type: "string", default: "#10b981", description: "Hex accent used for the gradient heading highlight, all three SVG illustrations, and card backgrounds." },
        ],
    },
    {
        id: "uilora-phone-feature",
        name: "Uilora Phone Feature",
        description: "Feature section with an iOS phone mockup (status bar, document editor, formatting options panel), 4 surrounding feature cards, floating '700' counter badge, floating checkmark badge, and a bottom fade-to-white effect.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "phone", "mockup", "ios", "saas", "light"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraPhoneFeature",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Powerful features at your fingertips", description: "Section heading. The word 'fingertips' is automatically highlighted with the accentColor as a marker effect." },
            { name: "description", type: "string", default: "Slash command gives instant access to components, templates, and tokens for a streamlined workflow.", description: "Subtitle shown below the heading." },
            { name: "accentColor", type: "string", default: "#bbf451", description: "Hex color used for the 'fingertips' highlighter mark behind the text." },
        ],
    },
    {
        id: "uilora-night-grid",
        name: "Uilora Night Grid",
        description: "Dark luxury bento grid on a near-black background. Features a hero card (col-span-2) with an animated constellation SVG and gradient border, plus 4 feature cards. Georgia serif headings with monospace accent labels.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["dark", "bento", "premium", "saas", "animated", "constellation"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraNightGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Everything your team needs to ship", description: "Section heading displayed in a large Georgia serif font." },
            { name: "description", type: "string", default: "Uilora gives developers a complete, production-ready component system…", description: "Subtitle below the heading in zinc-400." },
            { name: "accentColor", type: "string", default: "#818cf8", description: "Hex accent color used for the gradient border, icon backgrounds, monospace label, and highlighted constellation dots." },
        ],
    },
    {
        id: "uilora-asym-grid",
        name: "Uilora Asym Grid",
        description: "Clean asymmetric feature grid on a white background. One large left card with a big 700+ stat and animated mini-bento SVG illustration spans 3 rows, with 3 stacked feature cards on the right.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["light", "asymmetric", "editorial", "clean", "saas", "stats"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraAsymGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "A complete system, not just components", description: "Section heading in Georgia serif, left-aligned." },
            { name: "description", type: "string", default: "Every piece of Uilora is designed to work together…", description: "Subtitle below heading in zinc-500." },
            { name: "accentColor", type: "string", default: "#0ea5e9", description: "Hex accent used for the badge, the '+' in '700+', the MiniGrid illustration, and icon colors on right cards." },
        ],
    },
    {
        id: "uilora-glow-cards",
        name: "Uilora Glow Cards",
        description: "Ultra-dark feature section with a large gradient '700+' headline stat and a 2×2 grid of glassmorphic cards. Each card has a unique per-card colored glow blob that intensifies on hover, plus an accent gradient top-border line.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["dark", "glass", "glow", "futuristic", "hover", "premium"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraGlowCards",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Powerful features, beautiful by default", description: "Section heading in Georgia serif, below the large stat." },
            { name: "description", type: "string", default: "Every Uilora component is crafted to be drop-in ready…", description: "Subtitle in zinc-400 below the heading." },
            { name: "accentColor", type: "string", default: "#34d399", description: "Hex accent for the heading label and icon box backgrounds. Each row item has its own fixed stat color (cyan, orange, violet)." },
        ],
    },
    {
        id: "uilora-mosaic-grid",
        name: "Uilora Mosaic Grid",
        description: "Light gray feature section with 5 cards in a 3+2 mosaic layout — each card has a unique inline SVG illustration plus title and description.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["light", "mosaic", "illustrations", "bento", "5-cards", "saas"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraMosaicGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Features that make building faster", description: "Section heading, centered above the card grid." },
            { name: "description", type: "string", default: "Everything you need to build production UI…", description: "Subtitle below the heading in zinc-500." },
            { name: "accentColor", type: "string", default: "#3b82f6", description: "Hex accent threaded through all 5 illustrations — check circles, slider fill, TSX badge, tree root pill, and first ecosystem icon." },
        ],
    },
];
