import { getCode } from "../getCode";
import { Component } from "../types";

export const featureGridComponents: Component[] = [
    {
        id: "cinematic-grid",
        name: "Cinematic Stack",
        description: "Sticky scroll feature grid with full-bleed cinematic image cards, Uilora-branded feature content, and smooth whileInView animations on a black background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "cinematic", "sticky", "scroll", "dark"],
        previewUrl: "/Grids&Layouts/FeatureGrids/CinematicGrid",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/CinematicGrid.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/CinematicGrid.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/CinematicGrid/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Why teams choose Uilora", description: "Section heading rendered in the top header block." },
            { name: "description", type: "string", default: "Every component is crafted to be production-ready, accessible, and beautiful out of the box.", description: "Subtitle shown below the section heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for the label badge on each sticky card and the header eyebrow." },
        ],
        whenToUse: "Perfect for landing pages with deep narrative-driven feature sections, product launch pages, and any page that benefits from a premium, immersive scroll experience. The cinematic quality signals quality and depth.",
        bestPractices: "Use a dark or neutral page background so the black section blends cleanly. The sticky offset (top-24) assumes a fixed navbar — adjust if your navbar height differs. Keep feature headings concise for the large text to read comfortably at 7xl.",
        whyMatters: "Stacked scroll sequences guide users through complex feature sets with a sense of physical depth and narrative momentum. The cinematic aesthetic elevates perceived product quality immediately.",
        faqs: [
            { question: "How does sticky stacking work?", answer: "Each card uses CSS `sticky` positioning. As you scroll down, earlier cards remain pinned while new ones slide in from below, creating a layered stack effect." },
            { question: "Can I change the feature content?", answer: "The 4 feature items (headings, sub-descriptions, images) are hardcoded in the features array at the top of the component. Clone and edit that array to customize." },
            { question: "Is it responsive?", answer: "Yes — the text scales from text-5xl on mobile to text-7xl on desktop. The sticky offset works on all screen sizes." }
        ],
    },
    {
        id: "elastic-grid",
        name: "Elastic Expansion",
        description: "Hover-to-expand accordion feature grid with image backgrounds, vertical labels on inactive panels, and Uilora-branded content on a light gray background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "elastic", "expansion", "accordion", "hover"],
        previewUrl: "/Grids&Layouts/FeatureGrids/ElasticGrid",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/ElasticGrid.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/ElasticGrid.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/ElasticGrid/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Everything your design system needs", description: "Section heading displayed above the accordion." },
            { name: "description", type: "string", default: "Uilora brings structure, speed, and craft to every product you ship.", description: "Subtitle shown below the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for label badges on expanded panels and the eyebrow text." },
        ],
        whenToUse: "Ideal for feature comparison sections, capability showcases, and any use case where you want users to actively explore content rather than passively read a list. Works especially well on desktop-first landing pages.",
        bestPractices: "Keep panel labels short (1–2 words) so they read cleanly in the vertical rotated state. Use images with strong visual contrast since they display at 60% opacity over black.",
        whyMatters: "Accordion-style feature grids encourage active engagement — users are drawn to hover and explore, increasing time on page and feature comprehension compared to static lists.",
        faqs: [
            { question: "How do I change the feature content?", answer: "Edit the features array at the top of the component. Each item has label, heading, sub (description), and img (Unsplash URL)." },
            { question: "Can I make it click-to-expand instead of hover?", answer: "Yes — the component uses both onClick and onHoverStart. Remove onHoverStart to make it click-only." },
            { question: "Is it responsive?", answer: "On mobile the panels stack vertically (flex-col) and each shows in the expanded state by default. The horizontal expansion layout activates at md breakpoint." }
        ],
    },
    {
        id: "minimal-grid",
        name: "Ethereal Minimal",
        description: "Editorial 2-column photo grid with desaturated-to-color hover, serif italic headings, and Uilora-branded feature items on a white background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "minimal", "editorial", "photo", "light"],
        previewUrl: "/Grids&Layouts/FeatureGrids/MinimalGrid",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/MinimalGrid.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/MinimalGrid.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/MinimalGrid/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Crafted with intention", description: "Large heading displayed in the top-left of the section header." },
            { name: "description", type: "string", default: "Uilora components aren't generated — they're designed, reviewed, and refined until they feel right.", description: "Short description shown top-right opposite the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for the numbered labels above each feature item." },
        ],
        whenToUse: "Best for editorial brands, design studios, boutique agencies, and products that want to signal quality through restraint. The desaturate-to-color hover creates an elegant reveal that rewards exploration.",
        bestPractices: "This component is white-background-only — it pairs best with a white or near-white page. The serif italic typography works best with short, evocative headings (3–6 words). Avoid long feature descriptions as the light font-weight requires comfortable line length.",
        whyMatters: "Minimalism signals confidence. This layout communicates that the product doesn't need visual tricks — the work speaks for itself. The alternating vertical offset adds dynamism without breaking the calm aesthetic.",
        faqs: [
            { question: "Why does every other card have a top margin?", answer: "The md:mt-32 offset on odd-indexed cards creates the characteristic staggered editorial grid — each column scrolls into view at a slightly different pace." },
            { question: "Can I use custom images?", answer: "Yes — edit the features array and replace the img URLs. Any 4:3 aspect ratio image works well with the aspect-[4/3] container." },
            { question: "What does the ArrowUpRight icon do?", answer: "It appears on hover as a visual affordance suggesting the item is interactive. Wire it to a router.push() or <Link> for real navigation." }
        ],
    },
    {
        id: "grid-scatter-deck",
        name: "Scatter Deck",
        description: "Draggable card deck with Uilora-branded cards (Uilora, Motion, TypeScript, Design, 700+), spring physics, and a crosshair-grid background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "scatter", "deck", "drag", "interactive"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridScatterDeck",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/GridScatterDeck.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/GridScatterDeck.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/GridScatterDeck/page.tsx") },
        dependencies: ["lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Drag. Explore. Build.", description: "Heading displayed at the top of the scatter deck." },
            { name: "description", type: "string", default: "Uilora gives you every piece — drag them into your stack.", description: "Subtitle below the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for the eyebrow label and hover hint color." },
        ],
        whenToUse: "Best for hero sections that want to create delight and surprise — hackathon pages, creative portfolio landing screens, or component library showcases where interactivity itself is the message. High engagement, high memorability.",
        bestPractices: "The drag area is constrained to the container ref so cards never escape the viewport. Spring physics (bounce: 0.4) feel natural — avoid setting higher bounce values as cards become chaotic. The Asterisk icons use animate-spin-slow which requires a custom Tailwind animation.",
        whyMatters: "Draggable interfaces create a sense of physical ownership — users feel they're interacting with something real. This emotional engagement makes the Uilora brand memorable in a crowded market.",
        faqs: [
            { question: "How do I change the card labels?", answer: "Edit the cards array in the component. Each card has label (display text), color (Tailwind bg class), textColor (Tailwind text class), rotate, and z values." },
            { question: "Can I add more cards?", answer: "Yes — add objects to the cards array. They'll spring in with a delay of i * 0.1s automatically." },
            { question: "Why does animate-spin-slow not work?", answer: "You need to add a custom animation to your Tailwind config: `'spin-slow': 'spin 6s linear infinite'` under `theme.extend.animation`." }
        ],
    },
    {
        id: "uilora-hero-feature",
        name: "Uilora Hero Feature",
        description: "Split hero feature section with gradient headline, CTA buttons, and 3 staggered feature cards — each with a pastel dot-grid background, iOS-style gradient icon, title and description.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "hero", "cards", "saas", "light", "gradient"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraHeroFeature",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/UiloraHeroFeature.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/UiloraHeroFeature.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/UiloraHeroFeature/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Build faster: ship with an all-in-one library.", description: "Main headline. The phrase 'all-in-one' is automatically rendered in a gradient — include it in your title string to activate the effect." },
            { name: "description", type: "string", default: "Production-ready component library. Ship beautiful, accessible UIs instantly with Uilora's 700+ components.", description: "Subtitle displayed below the headline." },
            { name: "accentColor", type: "string", default: "#f472b6", description: "Hex color for the gradient on 'all-in-one', the badge icon, the stat card, and CTA button hover." },
        ],
        whenToUse: "Perfect for SaaS landing pages, component library homepages, and product hero sections that need to communicate value immediately. The 3-card stagger creates visual hierarchy without a complex layout.",
        bestPractices: "Include 'all-in-one' in your title string to activate the gradient effect. Pink-to-orange or purple-to-pink accent colors work best against the white card background. Keep the description under 2 lines for the cleanest layout.",
        whyMatters: "The combination of a bold gradient headline, clear CTAs, and three feature cards gives users everything they need to understand the product — immediately. The iOS-style icons add a polished, premium feel without image dependencies.",
        faqs: [
            { question: "How does the gradient on 'all-in-one' work?", answer: "The title string is split on the literal text 'all-in-one'. The middle part is wrapped in a span with background-clip: text and the accentColor gradient. Change the gradientWord const in the component to use a different highlighted word." },
            { question: "Can I change the feature cards?", answer: "The three cards (Components, Design System, Developer DX) and their dot-grid patterns are hardcoded. Clone the component and edit the card content and cardNSpots arrays to customize." },
            { question: "Why does the middle card extend above the others?", answer: "It uses marginTop: -32px and height: calc(100% + 32px) to create the staggered height effect. Adjust these values to change the offset." }
        ],
    },
    {
        id: "uilora-feature-trio",
        name: "Uilora Feature Trio",
        description: "Centered feature section with large heading and three equal cards — each featuring a unique inline SVG illustration (shield, folder, component grid) on a light gradient background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "cards", "illustration", "saas", "light", "minimal"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraFeatureTrio",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/UiloraFeatureTrio.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/UiloraFeatureTrio.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/UiloraFeatureTrio/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Unlock the Full Potential of Your Component Library", description: "Section heading. The phrase 'Component Library' is highlighted in an emerald gradient." },
            { name: "description", type: "string", default: "Explore Uilora's core benefits that make UI development fast, accessible, and production-ready.", description: "Subtitle shown below the heading." },
            { name: "accentColor", type: "string", default: "#10b981", description: "Hex accent used for the gradient heading highlight, all three SVG illustrations, and card backgrounds." },
        ],
        whenToUse: "Ideal for SaaS product feature sections, component library homepages, and marketing pages that need to communicate 3 core value propositions clearly. The inline SVG illustrations mean zero image dependencies.",
        bestPractices: "Emerald/teal accent colors look best since the illustrations use dark green as the base tone. Keep card titles under 5 words and descriptions to 2 lines for visual balance across all three cards.",
        whyMatters: "Custom inline SVG illustrations communicate quality and craftsmanship that generic icons cannot. Each illustration is thematically matched to its feature — shield for reliability, folder for ease, grid for breadth.",
        faqs: [
            { question: "How do I change the illustration colors?", answer: "Each illustration receives the accentColor prop and uses it for gradients, glows, and highlights. Change the accentColor prop to retheme all three simultaneously." },
            { question: "Can I swap out the illustrations?", answer: "Yes — the IllusComp prop on FeatureCard accepts any React component that takes an accent prop. Replace ShieldIllus, FolderIllus, or GridIllus with your own SVG component." },
            { question: "Which phrase gets the gradient highlight?", answer: "The gradientWord constant is set to 'Component Library'. Change it to highlight any phrase in your title string." }
        ],
    },
    {
        id: "uilora-phone-feature",
        name: "Uilora Phone Feature",
        description: "Feature section with an iOS phone mockup (status bar, document editor, formatting options panel), 4 surrounding feature cards, floating '700' counter badge, floating checkmark badge, and a bottom fade-to-white effect.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "phone", "mockup", "ios", "saas", "light"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraPhoneFeature",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/UiloraPhoneFeature.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/UiloraPhoneFeature.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/UiloraPhoneFeature/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Powerful features at your fingertips", description: "Section heading. The word 'fingertips' is automatically highlighted with the accentColor as a marker effect." },
            { name: "description", type: "string", default: "Slash command gives instant access to components, templates, and tokens for a streamlined workflow.", description: "Subtitle shown below the heading." },
            { name: "accentColor", type: "string", default: "#bbf451", description: "Hex color used for the 'fingertips' highlighter mark behind the text." },
        ],
        whenToUse: "Perfect for product landing pages that want to showcase a mobile-first or cross-platform experience. The phone mockup draws the eye while the surrounding cards communicate key feature benefits at a glance.",
        bestPractices: "Include 'fingertips' in your title string to activate the highlight effect. Bright lime/yellow accent colors work best for the highlighter effect as they contrast clearly against dark text. The section requires a white page background for the bottom fade to blend seamlessly.",
        whyMatters: "Phone mockups ground abstract software features in tangible reality — users immediately understand what the UI looks like. The floating badges (700 components, checkmark) build social proof and trust signals directly in the feature section.",
        faqs: [
            { question: "How does the 'fingertips' highlight work?", answer: "The title string is split on the literal word 'fingertips'. An absolutely positioned span with the accentColor background sits behind the word at 42% height from the bottom, creating a marker/highlighter effect. Change highlightWord in the component to use a different word." },
            { question: "Can I change the phone content?", answer: "Yes — the phone UI (document title, placeholder lines, formatting cells) is hardcoded inside PhoneMockup. Edit that component to customize the title, options panel content, or add real text content." },
            { question: "How does the bottom fade work?", answer: "Two gradient overlays are used: one inside the phone mockup (transparent → rgba(255,255,255,0.96)) to fade the phone content, and one at the section level (transparent → white) to blend the whole section into the page background." }
        ],
    },
    {
        id: "uilora-night-grid",
        name: "Uilora Night Grid",
        description: "Dark luxury bento grid on a near-black background. Features a hero card (col-span-2) with an animated constellation SVG and gradient border, plus 4 feature cards. Georgia serif headings with monospace accent labels.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["dark", "bento", "premium", "saas", "animated", "constellation"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraNightGrid",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/UiloraNightGrid.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/UiloraNightGrid.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/UiloraNightGrid/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Everything your team needs to ship", description: "Section heading displayed in a large Georgia serif font." },
            { name: "description", type: "string", default: "Uilora gives developers a complete, production-ready component system…", description: "Subtitle below the heading in zinc-400." },
            { name: "accentColor", type: "string", default: "#818cf8", description: "Hex accent color used for the gradient border on the hero card, icon backgrounds, monospace label, and highlighted constellation dots." },
        ],
        whenToUse: "Use for dark-themed SaaS landing pages, developer tool homepages, or any product that wants a premium 'night mode' aesthetic. Works especially well on pages that already have a dark background.",
        bestPractices: "Indigo, violet, and emerald accents look best on the near-black background. Keep card descriptions to 1-2 lines. The hero card's 700+ headline is hardcoded — edit it if your product stat differs.",
        whyMatters: "The animated constellation SVG creates genuine visual interest without images or heavy assets. The gradient border (1px gradient wrapper + inner dark card) produces a premium glow effect that's impossible with standard border styles.",
        faqs: [
            { question: "How does the gradient border on the hero card work?", answer: "A wrapper div has a linear-gradient background (accentColor at 55% → near-transparent). Inside it is the actual dark card div. Because the wrapper is p-px (1px padding) and the inner card matches the background color, only the 1px gradient strip shows as the border." },
            { question: "Can I change the constellation pattern?", answer: "Yes — edit the `dots` array (x/y coordinates) and the `edges` array (pairs of dot indices to connect with lines) inside the Constellation component. The `hi: true` property on a dot makes it larger and accent-colored." },
        ],
    },
    {
        id: "uilora-asym-grid",
        name: "Uilora Asym Grid",
        description: "Clean asymmetric feature grid on a white background. One large left card with a big 700+ stat and animated mini-bento SVG illustration spans 3 rows, with 3 stacked feature cards on the right.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["light", "asymmetric", "editorial", "clean", "saas", "stats"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraAsymGrid",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/UiloraAsymGrid.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/UiloraAsymGrid.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/UiloraAsymGrid/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "A complete system, not just components", description: "Section heading in Georgia serif, left-aligned." },
            { name: "description", type: "string", default: "Every piece of Uilora is designed to work together…", description: "Subtitle below heading in zinc-500." },
            { name: "accentColor", type: "string", default: "#0ea5e9", description: "Hex accent used for the badge, the '+' in '700+', the MiniGrid illustration, the monospace label, and icon colors on right cards." },
        ],
        whenToUse: "Ideal for light-themed SaaS pages, component library homepages, and product feature sections where you want to lead with a large stat. The asymmetric layout creates visual tension that draws the eye to the 700+ number.",
        bestPractices: "Sky blue, indigo, and emerald accents work best on white. The left card has a very subtle accent tint — brighter accents like red or orange can feel too strong. Keep right card descriptions to 2 lines for visual balance.",
        whyMatters: "The asymmetric grid (1.42fr left vs 1fr right) is visually unusual and creates a strong hierarchy. The animated MiniGrid SVG illustration communicates 'bento layout' abstractly without requiring screenshots.",
        faqs: [
            { question: "How does the row-span-3 left card work?", answer: "In CSS grid, the left card has `row-span-3` which makes it expand to fill the same vertical space as the 3 right cards + their gaps. The grid auto-places the 3 right cards into rows 1, 2, and 3 of the right column." },
            { question: "Can I change the large stat from 700+?", answer: "Yes — the '700+' number is hardcoded in the left card JSX. Find `700<span style={{ color: accentColor }}>+</span>` and replace with your own stat. The `+` separately colored by accentColor is a deliberate detail." },
        ],
    },
    {
        id: "uilora-glow-cards",
        name: "Uilora Glow Cards",
        description: "Ultra-dark feature section with a large gradient '700+' headline stat and a 2×2 grid of glassmorphic cards. Each card has a unique per-card colored glow blob that intensifies on hover, plus an accent gradient top-border line.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["dark", "glass", "glow", "futuristic", "hover", "premium"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraGlowCards",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/UiloraGlowCards.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/UiloraGlowCards.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/UiloraGlowCards/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Powerful features, beautiful by default", description: "Section heading in Georgia serif, below the large stat." },
            { name: "description", type: "string", default: "Every Uilora component is crafted to be drop-in ready…", description: "Subtitle in zinc-400 below the heading." },
            { name: "accentColor", type: "string", default: "#34d399", description: "Hex accent used for the '700+' gradient stat and for the first card's glow color. The other 3 cards use fixed glow colors (cyan, orange, violet)." },
        ],
        whenToUse: "Best for dark-themed SaaS pages, AI/developer tool homepages, and any product that wants a futuristic, high-tech feel. The glow cards communicate distinct feature categories with unique color identities.",
        bestPractices: "The dark gradient background (#07070f → #0e0e1a) requires the page to also be dark for seamless blending. Use bright accent colors (emerald, cyan, blue) — the glow effect relies on saturation. Avoid desaturated accents like gray or beige.",
        whyMatters: "Per-card unique glow colors create a visual hierarchy and memorability — each card has its own 'personality'. The gradient top-border line and glow blob work together to create a premium glass-card effect without any actual CSS backdrop-filter issues on older browsers.",
        faqs: [
            { question: "Can I change the per-card glow colors?", answer: "Yes — in the `cards` array, each card object has a `glow` property. Card 0 uses `accentColor` by default; cards 1-3 use fixed colors (#22d3ee cyan, #fb923c orange, #a78bfa violet). Update any of these to your preferred hex values." },
            { question: "How does the glass card effect work?", answer: "Each card has `background: rgba(255,255,255,0.04)`, `border: 1px solid rgba(255,255,255,0.07)`, and `backdropFilter: blur(12px)`. The glow blob is an absolutely positioned div with `filter: blur(44px)` and `overflow-hidden` on the card clips it." },
            { question: "How does the hover lift work?", answer: "Framer Motion's `whileHover={{ y: -4 }}` translates the card 4px upward with a fast `cubic-bezier(0.22, 1, 0.36, 1)` ease. Only `transform` is animated — no layout properties." },
        ],
    },
    {
        id: "uilora-mosaic-grid",
        name: "Uilora Mosaic Grid",
        description: "Light gray feature section with 5 cards in a 3+2 mosaic bento layout — each card has a unique inline SVG illustration (install notification, theme slider, dual export docs, component tree, ecosystem icons) plus title and description.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["light", "mosaic", "illustrations", "bento", "5-cards", "saas"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraMosaicGrid",
        code: {
            tsx: getCode("src/components/Grids&Layouts/FeatureGrids/tsx/UiloraMosaicGrid.tsx"),
            jsx: getCode("src/components/Grids&Layouts/FeatureGrids/jsx/UiloraMosaicGrid.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/Grids&Layouts/FeatureGrids/UiloraMosaicGrid/page.tsx") },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Features that make building faster", description: "Section heading, centered above the card grid." },
            { name: "description", type: "string", default: "Everything you need to build production UI…", description: "Subtitle below the heading in zinc-500." },
            { name: "accentColor", type: "string", default: "#3b82f6", description: "Hex accent threaded through all 5 illustrations — check circles, slider fill, TSX badge, tree root pill, and first ecosystem icon." },
        ],
        whenToUse: "Perfect for product feature pages that need to communicate multiple distinct capabilities visually without relying on screenshots or image assets. The 3+2 mosaic creates hierarchy where bottom cards feel more significant than top ones.",
        bestPractices: "Blue, indigo, and teal accents work well against zinc-50 illustration backgrounds. Keep card titles to 2-3 words. Requires at least 720px container width for illustrations to render clearly.",
        whyMatters: "Inline SVG illustrations ensure zero image dependencies and instant loading. Each illustration is designed thematically for its feature — notification for access, slider for theming, dual docs for export, tree for exploration, and app icons for ecosystem breadth.",
        faqs: [
            { question: "How does the 3+2 layout work?", answer: "The grid is `grid-cols-6`. The top 3 cards each use `col-span-2` (3×2=6), and the bottom 2 cards each use `col-span-3` (2×3=6). Both rows fill the full 6-column width, but bottom cards are 50% wider than top cards." },
            { question: "Can I change the illustration content?", answer: "Yes — each illustration is a separate component (IllusInstall, IllusTheme, IllusExport, IllusTree, IllusEcosystem). Edit the SVG paths within each. The `a` prop threads the accentColor through each illustration." },
        ],
    },
];
