import { Component } from "../types";

export const featureGridComponentsMetadata: Component[] = [
    {
        id: "cinematic-grid",
        name: "Cinematic Stack",
        description: "Sticky scroll feature grid with full-bleed cinematic image cards, Uilora-branded feature content, and smooth whileInView animations on a black background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "cinematic", "sticky", "scroll", "dark"],
        previewUrl: "/Grids&Layouts/FeatureGrids/CinematicGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Why teams choose Uilora", description: "Section heading rendered in the top header block." },
            { name: "description", type: "string", default: "Every component is crafted to be production-ready, accessible, and beautiful out of the box.", description: "Subtitle shown below the section heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for the label badge on each sticky card and the header eyebrow." },
        ],
    },
    {
        id: "elastic-grid",
        name: "Elastic Expansion",
        description: "Hover-to-expand accordion feature grid with image backgrounds, vertical labels on inactive panels, and Uilora-branded content on a light gray background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "elastic", "expansion", "accordion", "hover"],
        previewUrl: "/Grids&Layouts/FeatureGrids/ElasticGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Everything your design system needs", description: "Section heading displayed above the accordion." },
            { name: "description", type: "string", default: "Uilora brings structure, speed, and craft to every product you ship.", description: "Subtitle shown below the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for label badges on expanded panels and the eyebrow text." },
        ],
    },
    {
        id: "minimal-grid",
        name: "Ethereal Minimal",
        description: "Editorial 2-column photo grid with desaturated-to-color hover, serif italic headings, and Uilora-branded feature items on a white background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "minimal", "editorial", "photo", "light"],
        previewUrl: "/Grids&Layouts/FeatureGrids/MinimalGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Crafted with intention", description: "Large heading displayed in the top-left of the section header." },
            { name: "description", type: "string", default: "Uilora components aren't generated — they're designed, reviewed, and refined until they feel right.", description: "Short description shown top-right opposite the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for the numbered labels above each feature item." },
        ],
    },
    {
        id: "grid-scatter-deck",
        name: "Scatter Deck",
        description: "Draggable card deck with Uilora-branded cards (Uilora, Motion, TypeScript, Design, 700+), spring physics, and a crosshair-grid background.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "scatter", "deck", "drag", "interactive"],
        previewUrl: "/Grids&Layouts/FeatureGrids/GridScatterDeck",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "Drag. Explore. Build.", description: "Heading displayed at the top of the scatter deck." },
            { name: "description", type: "string", default: "Uilora gives you every piece — drag them into your stack.", description: "Subtitle below the heading." },
            { name: "accentColor", type: "string", default: "#6366f1", description: "Hex accent used for the eyebrow label and hover hint color." },
        ],
    },
    {
        id: "uilora-hero-feature",
        name: "Uilora Hero Feature",
        description: "Split hero feature section with gradient headline, CTA buttons, and 3 staggered feature cards — each with a pastel dot-grid background, iOS-style gradient icon, title and description.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["feature", "hero", "cards", "saas", "light", "gradient"],
        previewUrl: "/Grids&Layouts/FeatureGrids/UiloraHeroFeature",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "title", type: "string", default: "Build faster: ship with an all-in-one library.", description: "Main headline. The phrase 'all-in-one' is automatically rendered in a gradient — include it in your title string to activate the effect." },
            { name: "description", type: "string", default: "Production-ready component library. Ship beautiful, accessible UIs instantly with Uilora's 700+ components.", description: "Subtitle displayed below the headline." },
            { name: "accentColor", type: "string", default: "#f472b6", description: "Hex color for the gradient on 'all-in-one', the badge icon, the stat card, and CTA button hover." },
        ],
    },
];
