import { Component } from "../types";

export const galleryGridComponentsMetadata: Component[] = [
    {
        id: "gallery-parallax-columns",
        name: "Parallax Columns",
        description: "Uilora Parallax Columns — cinematic scroll-driven gallery with three independent layers.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "parallax", "columns", "fashion"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryParallaxColumns",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...9 image URLs]", description: "Array of image URLs to display in columns." },
            { name: "backgroundColor", type: "string", default: "#f5f5f4", description: "Background color (hex, rgb, or hsl)." },
            { name: "columnCount", type: "number", default: "3", description: "Number of columns (2, 3, or 4)." },
        ],
    },
    {
        id: "gallery-shattered",
        name: "Shattered Mosaic",
        description: "Uilora Shattered Mosaic — abstract broken-tile gallery with staggered hover reveals.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "shattered", "mosaic", "abstract"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryShattered",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{span: string, img: string}>", default: "[{span: 'col-span-2 row-span-2', img: '...'}, ...]", description: "Array of items with grid span classes and image URLs." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color (hex, rgb, or hsl)." },
            { name: "labelPrefix", type: "string", default: "Uilora", description: "Prefix text for item labels." },
        ],
    },
    {
        id: "gallery-bentoa",
        name: "Bento Focus",
        description: "Uilora Bento Focus — interactive bento grid with shared-element expand animations.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "bento", "focus", "expandable"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryBento",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{id: number, title: string, category: string, img: string}>", default: "[{id: 1, title: 'Uilora Solitude', category: 'Uilora Landscape', img: '...'}, ...]", description: "Array of gallery items with id, title, category label, and image URL." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color (hex, rgb, or hsl)." },
            { name: "heading", type: "string", default: "Uilora — Selected Works", description: "Section heading displayed above the gallery grid." },
            { name: "subheading", type: "string", default: "A curated collection of space, texture, and light by Uilora.", description: "Subtitle shown below the section heading." },
        ],
    },
    {
        id: "gallery-spotlight",
        name: "Spotlight Matrix",
        description: "Uilora Spotlight Matrix — cursor-lit gallery that illuminates images as you move.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "spotlight", "matrix", "lighting"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GallerySpotlight",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...16 image URLs]", description: "Array of image URLs to display in grid." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "spotlightSize", type: "number", default: "600", description: "Size of spotlight effect in pixels." },
            { name: "imageLabelPrefix", type: "string", default: "UIL", description: "Prefix text for image labels." },
        ],
    },
    {
        id: "gallery-film-stripa",
        name: "Film Strip",
        description: "Uilora Film Strip — vintage horizontal scroll gallery with sprocket-hole framing.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "film", "strip", "vintage"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryFilmStrip",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...5 image URLs]", description: "Array of image URLs to display in film strips." },
            { name: "backgroundColor", type: "string", default: "#111", description: "Background color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#222", description: "Film strip border color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "gallery-fan",
        name: "Z-Stack Fan",
        description: "Uilora Z-Stack Fan — 3D card deck that fans open on hover with spring physics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "fan", "3d", "stack"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryFan",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "cards", type: "Array<{title: string, color: string}>", default: "[{title: 'Air', color: 'bg-blue-200'}, ...]", description: "Array of card objects with title and color (Tailwind class)." },
            { name: "backgroundColor", type: "string", default: "#f5f5f5", description: "Background color (hex, rgb, or hsl)." },
            { name: "collectionPrefix", type: "string", default: "Uilora Collection", description: "Prefix text for collection labels." },
            { name: "hintText", type: "string", default: "HOVER TO EXPAND DECK", description: "Hint text displayed at bottom." },
        ],
    },
    {
        id: "gallery-velocity",
        name: "Velocity Scroll",
        description: "Uilora Velocity Scroll — high-octane marquee gallery driven by scroll momentum.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "velocity", "scroll", "momentum"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryVelocity",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...4 image URLs]", description: "Array of image URLs to display in marquee." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
            { name: "borderColor", type: "string", default: "#000000", description: "Border color (hex, rgb, or hsl)." },
            { name: "accentColor", type: "string", default: "#facc15", description: "Accent color for marquee background (hex, rgb, or hsl)." },
            { name: "titleText", type: "string", default: "UILORA", description: "Large title text displayed in center." },
            { name: "imageLabelPrefix", type: "string", default: "UIL", description: "Prefix text for image labels." },
        ],
    },
    {
        id: "gallery-velocity-warp",
        name: "Velocity Warp",
        description: "Uilora Velocity Warp — warp-speed grid with skew and distortion on scroll.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "velocity", "warp", "distortion"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryVelocityWarp",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...9 image URLs]", description: "Array of image URLs to display in grid." },
            { name: "backgroundColor", type: "string", default: "#0a0a0a", description: "Background color (hex, rgb, or hsl)." },
            { name: "backgroundText", type: "string", default: "WARP", description: "Large background text pattern." },
            { name: "labelPrefix", type: "string", default: "Uilora", description: "Prefix text for image labels." },
        ],
    },
    {
        id: "gallery-flashlight",
        name: "Flashlight Reveal",
        description: "Uilora Flashlight Reveal — cursor-torch that illuminates hidden images in the dark.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "flashlight", "reveal", "spotlight"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryFlashlight",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...12 image URLs]", description: "Array of image URLs to display in grid." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "lensSize", type: "number", default: "300", description: "Size of flashlight lens in pixels." },
            { name: "hintText", type: "string", default: "MOVE CURSOR TO ILLUMINATE THE UILORA ARCHIVE", description: "Hint text displayed at bottom." },
        ],
    },
    {
        id: "gallery-sliced",
        name: "Sliced Hover",
        description: "Uilora Sliced Hover — full-height sliced panels that expand and reveal on hover.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "sliced", "hover", "split"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GallerySliced",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{title: string, img: string}>", default: "[{title: 'NATURE', img: '...'}, ...]", description: "Array of items with title and image URL." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Background color (hex, rgb, or hsl)." },
            { name: "descriptionTemplate", type: "string", default: "A Uilora editorial — an immersive dive into the world of {title}.", description: "Description template (use {title} placeholder)." },
            { name: "buttonText", type: "string", default: "Explore Collection", description: "Button text for expanded view." },
        ],
    },
    {
        id: "gallery-pin-reveal",
        name: "Pin & Reveal",
        description: "Uilora Pin & Reveal — sticky scroll sequence that stacks and pins full-screen cards.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "pin", "reveal", "interactive"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryPinReveal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "cards", type: "Array<{color: string, title: string, img: string}>", default: "[{color: '#FF5733', title: 'Uilora Ignite', img: '...'}, ...]", description: "Array of card objects with color (hex), title, and image URL." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Background color (hex, rgb, or hsl)." },
            { name: "scrollHintText", type: "string", default: "Scroll Down", description: "Scroll hint main text." },
            { name: "scrollHintSubtext", type: "string", default: "↓", description: "Scroll hint subtext/arrow." },
        ],
    },
    {
        id: "gallery-diagonal-marquee",
        name: "Diagonal Marquee",
        description: "Uilora Diagonal Marquee — three offset diagonal image ribbons scrolling at different speeds.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "diagonal", "marquee", "scrolling"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryDiagonalMarquee",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "row1Images", type: "string[]", default: "[...10 image URLs]", description: "Array of image URLs for first row." },
            { name: "row2Images", type: "string[]", default: "[...10 image URLs]", description: "Array of image URLs for second row." },
            { name: "row3Images", type: "string[]", default: "[...10 image URLs]", description: "Array of image URLs for third row." },
            { name: "backgroundColor", type: "string", default: "#e0e0e0", description: "Background color (hex, rgb, or hsl)." },
            { name: "badgePrefix", type: "string", default: "A", description: "Prefix text for badge labels." },
        ],
    },
    {
        id: "gallery-click-expand",
        name: "Hero Expand",
        description: "Click-to-expand hero gallery with fullscreen interactions.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "expand", "hero", "fullscreen"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryClickExpand",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{id: string, title: string, col: string, img: string}>", default: "[{id: '1', title: 'Cyber', col: 'col-span-2 row-span-2', img: '...'}, ...]", description: "Array of items with id, title, grid span classes, and image URL." },
            { name: "backgroundColor", type: "string", default: "#18181b", description: "Background color (hex, rgb, or hsl)." },
            { name: "emptySlotText", type: "string", default: "Empty", description: "Text displayed in empty grid slots." },
            { name: "fullScreenText", type: "string", default: "Full screen immersive view active. Click anywhere to return to the grid matrix.", description: "Text displayed in fullscreen view." },
        ],
    },
    {
        id: "gallery-depth-stack",
        name: "Depth Stack",
        description: "Cinema zoom fly-through — each image blooms from tiny to full-screen as you scroll.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "scroll", "zoom", "cinematic", "depth"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryDepthStack",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...6 image URLs]", description: "Array of images. Each zooms from far away to full-screen and flies past." },
            { name: "backgroundColor", type: "string", default: "#060606", description: "Background color (hex, rgb, or hsl)." },
            { name: "label", type: "string", default: "Archive", description: "Monospace label shown top-left as a HUD overlay." },
        ],
    },
    {
        id: "gallery-ribbon-scroll",
        name: "Ribbon Scroll",
        description: "Three diagonal editorial bands drifting in alternating directions on scroll.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "ribbon", "diagonal", "marquee", "editorial"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryRibbonScroll",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "band1", type: "string[]", default: "[...6 image URLs]", description: "Images for the top angled band." },
            { name: "band2", type: "string[]", default: "[...6 image URLs]", description: "Images for the middle (reverse) band — taller portrait cards." },
            { name: "band3", type: "string[]", default: "[...6 image URLs]", description: "Images for the bottom angled band." },
            { name: "backgroundColor", type: "string", default: "#080808", description: "Background color (hex, rgb, or hsl)." },
            { name: "angle", type: "number", default: "12", description: "Diagonal tilt angle in degrees for the outer bands." },
        ],
    },
    {
        id: "gallery-reveal-wipe",
        name: "Reveal Wipe",
        description: "Full-viewport images that wipe in with distinct clip-path animations as you scroll.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "clip-path", "reveal", "wipe", "scroll"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryRevealWipe",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{img: string, title: string, label: string}>", default: "[{img: '...', title: 'Serenity', label: 'Chapter I'}, ...]", description: "Array of sections with image, heading title, and chapter label." },
            { name: "backgroundColor", type: "string", default: "#080808", description: "Background color (hex, rgb, or hsl)." },
        ],
    },
    {
        id: "gallery-drift-grid",
        name: "Drift Grid",
        description: "12 scattered photos that physically float and drift as your cursor moves.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["gallery", "cursor", "drift", "interactive", "spring"],
        previewUrl: "/Grids&Layouts/GalleryGrids/GalleryDriftGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...12 image URLs]", description: "Array of 12 images displayed as a tilted, floating photo grid." },
            { name: "backgroundColor", type: "string", default: "#f0ece4", description: "Background color (hex, rgb, or hsl)." },
            { name: "label", type: "string", default: "Collected", description: "Giant watermark label rendered as a ghost outline behind the grid." },
        ],
    },
];

