import { Component } from "../types";

export const masonryGridComponentsMetadata: Component[] = [
    {
        id: "masonry-editorial",
        name: "Uilora Editorial Stagger",
        description: "Sharp monochrome editorial masonry grid with high-fashion aesthetics.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "editorial", "monochrome", "fashion"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "items", type: "Array<{h: string, title: string, sub: string}>", default: "[{h: 'h-64', title: 'Vogue', sub: 'Collection 01'}, ...]", description: "Array of editorial items with height class (h), title, and subtitle." },
            { name: "backgroundColor", type: "string", default: "#f4f4f0", description: "Background color (hex, rgb, or hsl)." },
            { name: "imageSeed", type: "number", default: "50", description: "Seed number for generating placeholder images." },
        ],
    },
    {
        id: "masonry-chunky",
        name: "Uilora Chunky Dark",
        description: "Uilora Chunky — bold dark masonry grid with electric-green accents and chunky rounded tiles.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "dark", "bold", "neon", "premium"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryChunky",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 9 Unsplash URLs */]", description: "Array of 9 image URLs for the masonry tiles." },
            { name: "backgroundColor", type: "string", default: '"#0c0c14"', description: "Deep dark background color." },
            { name: "accentColor", type: "string", default: '"#3dffa0"', description: "Electric accent color for tags and highlights." },
            { name: "heading", type: "string", default: '"Uilora Premium"', description: "Main heading displayed at the top." },
            { name: "subheading", type: "string", default: '"Curated visual experiences for premium interfaces."', description: "Tagline shown in the accent card." },
        ],
    },
    {
        id: "masonry-noir",
        name: "Uilora Noir Gold",
        description: "Uilora Noir — cinematic black masonry grid with gold accents and editorial corner markers.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "dark", "gold", "luxury", "editorial"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryNoir",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 8 Unsplash URLs */]", description: "Array of 8 image URLs for the gold-tinted masonry tiles." },
            { name: "backgroundColor", type: "string", default: '"#080808"', description: "Near-black background for maximum contrast." },
            { name: "accentColor", type: "string", default: '"#c9a96e"', description: "Gold accent color for labels, borders, and highlight cards." },
            { name: "label", type: "string", default: '"Uilora Noir"', description: "Editorial heading displayed in the header section." },
        ],
    },
    {
        id: "masonry-brute",
        name: "Uilora Brute Grid",
        description: "Uilora Brute — raw brutalist masonry grid with thick black borders, yellow accents, and Arial Black typography.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "brutalist", "bold", "editorial", "typography"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryBrute",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 6 Unsplash URLs */]", description: "Array of 6 image URLs placed throughout the brutalist grid." },
            { name: "backgroundColor", type: "string", default: '"#f0ede6"', description: "Off-white background that contrasts with thick black borders." },
            { name: "accentColor", type: "string", default: '"#f0e500"', description: "Electric yellow accent for highlight tiles and badges." },
            { name: "heading", type: "string", default: '"UILORA"', description: "Large display heading in the header row." },
        ],
    },
    {
        id: "masonry-pop",
        name: "Uilora Pop Color",
        description: "Uilora Pop — vibrant multi-color masonry grid with bold color tiles and image cards in a playful layout.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "colorful", "pop", "playful", "bold"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryPop",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 6 Unsplash URLs */]", description: "Array of 6 image URLs for the image tiles." },
            { name: "backgroundColor", type: "string", default: '"#f8f5f0"', description: "Warm off-white base for the grid background." },
            { name: "heading", type: "string", default: '"Uilora Pop"', description: "Large display heading shown above the grid." },
        ],
    },
    {
        id: "masonry-dusk",
        name: "Uilora Dusk Archive",
        description: "Uilora Dusk — warm cinematic masonry grid with amber overlays, Georgia serif typography, and a golden-hour editorial mood.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "warm", "cinematic", "editorial", "amber"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryDusk",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 9 Unsplash URLs */]", description: "Array of 9 warm-toned image URLs for the dusk tile grid." },
            { name: "backgroundColor", type: "string", default: '"#0f0908"', description: "Deep warm-black background evoking nightfall." },
            { name: "accentColor", type: "string", default: '"#d4915a"', description: "Amber/rust accent for labels, numbers, and highlight cards." },
            { name: "heading", type: "string", default: '"Uilora Dusk"', description: "Large editorial heading in the hero section." },
            { name: "tagline", type: "string", default: '"The golden hour collection."', description: "Italic tagline below the heading." },
        ],
    },
    {
        id: "masonry-orbit",
        name: "Uilora Orbit",
        description: "Uilora Orbit — space/tech dark masonry grid with electric blue accents, scan-line overlays, HUD corner brackets, and animated system status.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "dark", "tech", "hud", "space", "futuristic"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryOrbit",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 5 Unsplash URLs */]", description: "Array of 5 image URLs for the orbit tiles." },
            { name: "backgroundColor", type: "string", default: '"#000000"', description: "Pure black background for maximum contrast." },
            { name: "accentColor", type: "string", default: '"#00A1FF"', description: "Electric blue accent for HUD brackets, labels, and data cards." },
            { name: "heading", type: "string", default: '"UILORA ORBIT"', description: "Main heading in the header section." },
            { name: "subheading", type: "string", default: '"Visual intelligence from above."', description: "Tagline displayed below the heading." },
        ],
    },
    {
        id: "masonry-board",
        name: "Uilora Board",
        description: "Uilora Board — dark moodboard/curator masonry grid with sage green accents, color swatch tiles, quote cards, and a 2×2 mini image grid.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "dark", "moodboard", "curator", "sage", "editorial"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryBoard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 7 Unsplash URLs */]", description: "Array of 7 image URLs for the board tiles." },
            { name: "backgroundColor", type: "string", default: '"#262626"', description: "Dark charcoal background." },
            { name: "accentColor", type: "string", default: '"#7a9e8e"', description: "Sage green accent for avatar gradients and quote attributions." },
            { name: "boardTitle", type: "string", default: '"Uilora Curation"', description: "Board heading in the header section." },
            { name: "subtitle", type: "string", default: '"Public Board"', description: "Small label above the board title." },
        ],
    },
    {
        id: "masonry-soyi",
        name: "Uilora Soyi",
        description: "Uilora Soyi — bold serif editorial masonry grid with a vibrant orange outer frame, massive italic heading, and tight 3-column image grid.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "editorial", "serif", "bold", "orange", "magazine"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonrySoyi",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 5 Unsplash URLs */]", description: "Array of 5 image URLs for the 3-column editorial grid." },
            { name: "outerColor", type: "string", default: '"#e8720c"', description: "Outer frame / border background color." },
            { name: "backgroundColor", type: "string", default: '"#111111"', description: "Inner container background color." },
            { name: "heading", type: "string", default: '"Uilora"', description: "Massive italic serif heading centered above the grid." },
        ],
    },
    {
        id: "masonry-feed",
        name: "Uilora Feed",
        description: "Uilora Feed — social/Pinterest-style masonry grid with white card posts, Georgia serif typography, heart/view engagement counts, and staggered columns.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "social", "feed", "pinterest", "cards", "light"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryFeed",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 6 Unsplash URLs */]", description: "Array of 6 image URLs for the image-bearing feed cards." },
            { name: "backgroundColor", type: "string", default: '"#f0eee8"', description: "Warm off-white background for the feed." },
            { name: "heading", type: "string", default: '"Uilora Feed"', description: "Centered heading above the feed columns." },
            { name: "subheading", type: "string", default: '"Curated visual discoveries."', description: "Subtitle below the heading." },
        ],
    },
    {
        id: "masonry-studio",
        name: "Uilora Studio",
        description: "Uilora Studio — minimal photo gallery masonry grid with a 'studio.' wordmark, category filter pills, 4-column layout, and spring hover animations.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "gallery", "minimal", "studio", "photographer", "light"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryStudio",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 10 Unsplash URLs */]", description: "Array of 10 image URLs for the 4-column studio grid." },
            { name: "backgroundColor", type: "string", default: '"#f6f6f4"', description: "Off-white background for the studio." },
            { name: "wordmark", type: "string", default: '"studio."', description: "Brand wordmark in the top navigation." },
            { name: "heading", type: "string", default: '"Uilora Studio"', description: "Internal heading reference." },
        ],
    },
    {
        id: "masonry-collection",
        name: "Uilora Collection",
        description: "Uilora Collection — editorial e-commerce bento masonry grid with vertical text tile, product cards, 'SHOP NOW >' CTAs, and a 5-column layout.",
        category: "Grids & Layouts",
        installType: "cli",
        tags: ["masonry", "ecommerce", "editorial", "bento", "collection", "cream"],
        previewUrl: "/Grids&Layouts/MasonryGrids/MasonryCollection",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[/* 6 Unsplash URLs */]", description: "Array of 6 image URLs for the collection product tiles." },
            { name: "backgroundColor", type: "string", default: '"#faf7f0"', description: "Warm cream background for the collection page." },
            { name: "accentColor", type: "string", default: '"#e8720c"', description: "Accent color for 'SHOP NOW >' links, vertical text, and the Fall Gear circle button." },
            { name: "heading", type: "string", default: '"Uilora Collection"', description: "Internal heading reference." },
        ],
    },
];

