import { Component } from "../components-data";

export const transform3DComponentsMetadata: Component[] = [
    {
        id: "holo-tilt",
        name: "Holographic Tilt Card",
        description: "Interactive 3D card with holographic tilt effect and depth layers.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["3d", "transform", "tilt", "holographic", "card"],
        previewUrl: "/Animations&Motion/3DTransforms/HoloTilt",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [
            { name: "imageUrl", type: "string", default: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop", description: "Image URL for the card" },
            { name: "title", type: "string", default: "NEBULA X", description: "Title text displayed on the card" },
            { name: "description", type: "string", default: "Interactive holographic projection interface with localized depth mapping.", description: "Description text displayed on the card" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "cardWidth", type: "string", default: "w-80", description: "Width of the card" },
            { name: "cardHeight", type: "string", default: "h-[450px]", description: "Height of the card" },
            { name: "perspective", type: "string", default: "perspective-[1000px]", description: "CSS perspective value for 3D effect" },
            { name: "rotateXRange", type: "[number, number]", default: "[15, -15]", description: "Range of X-axis rotation in degrees" },
            { name: "rotateYRange", type: "[number, number]", default: "[-15, 15]", description: "Range of Y-axis rotation in degrees" },
            { name: "translateZImage", type: "number", default: "50", description: "Z-axis translation for the image layer" },
            { name: "translateZText", type: "number", default: "80", description: "Z-axis translation for the text layer" },
            { name: "translateZIcon", type: "number", default: "20", description: "Z-axis translation for the icon layer" },
            { name: "iconSize", type: "number", default: "24", description: "Size of the icon" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
    },
    {
        id: "parallax-stack",
        name: "Parallax Stack",
        description: "Floating card stack with 3D parallax effect on hover.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["3d", "transform", "parallax", "stack", "cards"],
        previewUrl: "/Animations&Motion/3DTransforms/ParallaxStack",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs for the stack" },
            { name: "layerCount", type: "number", default: "3", description: "Number of layers in the stack" },
            { name: "backgroundColor", type: "string", default: "bg-neutral-900", description: "Background color of the component" },
            { name: "cardWidth", type: "string", default: "w-72", description: "Width of each card" },
            { name: "cardHeight", type: "string", default: "h-96", description: "Height of each card" },
            { name: "perspective", type: "string", default: "perspective-[2000px]", description: "CSS perspective value for 3D effect" },
            { name: "springStiffness", type: "number", default: "200", description: "Spring animation stiffness" },
            { name: "springDamping", type: "number", default: "20", description: "Spring animation damping" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for creative portfolios, SaaS landing pages, and enterprise-ready UIs that need to display stacked content like blog posts or testimonials. Use this React component when building hero sections that require a sense of depth and physical presence.",
        bestPractices: "Optimize for performance in large-scale applications by limiting the `layerCount` to avoid rendering too many overlapping images. Maintain consistent spacing within your design system by using the `cardWidth` and `cardHeight` props. Follow React best practices by using the `springStiffness` and `springDamping` to create a natural, weighted feel for the cards.",
        whyMatters: "In modern frontend development, layering is a powerful tool for visual storytelling. This reusable React component provides a sophisticated way to manage overlapping elements in 3D space, which is essential for building scalable design systems that stand out.",
        faqs: [
            { question: "How many layers should I use?", answer: "While the component is flexible, using 3 to 5 layers usually provides the best parallax depth without cluttering the UI." },
            { question: "Can I use text instead of images?", answer: "Yes, you can easily adapt the layers to hold any React content, including text, icons, or custom components." },
            { question: "Is the spring animation adjustable?", answer: "Yes, you have full control over the spring physics to make the stack feel either light and bouncy or heavy and stable." }
        ],
    },
    {
        id: "iso-blocks",
        name: "Isometric Blocks",
        description: "Isometric city blocks with 3D hover elevation effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["3d", "transform", "isometric", "blocks", "city"],
        previewUrl: "/Animations&Motion/3DTransforms/IsoBlocks",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "gridSize", type: "number", default: "9", description: "Number of blocks in the grid (n x n)" },
            { name: "containerSize", type: "string", default: "w-[500px] h-[500px]", description: "Size of the container" },
            { name: "backgroundColor", type: "string", default: "bg-[#0a0a0a]", description: "Background color of the component" },
            { name: "rotateX", type: "number", default: "60", description: "X-axis rotation in degrees" },
            { name: "rotateZ", type: "number", default: "-45", description: "Z-axis rotation in degrees" },
            { name: "gap", type: "string", default: "gap-4", description: "Gap between blocks" },
            { name: "hoverZ", type: "number", default: "80", description: "Z-axis translation on hover" },
            { name: "defaultColor", type: "string", default: "#262626", description: "Default color of blocks" },
            { name: "hoverColor", type: "string", default: "#6366f1", description: "Color of blocks on hover" },
            { name: "topColor", type: "string", default: "#404040", description: "Color of the top face" },
            { name: "topHoverColor", type: "string", default: "#818cf8", description: "Color of the top face on hover" },
            { name: "sideColor", type: "string", default: "#171717", description: "Color of the side faces" },
            { name: "sideHoverColor", type: "string", default: "#4f46e5", description: "Color of the side faces on hover" },
            { name: "blockSize", type: "string", default: "w-32 h-32", description: "Size of each block" },
            { name: "springStiffness", type: "number", default: "300", description: "Spring animation stiffness" },
            { name: "springDamping", type: "number", default: "20", description: "Spring animation damping" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This customizable UI component is great for technical blogs, data visualization, or architectural firm websites. Best suited for mobile app interfaces built with React (web) or Next.js sites that want to showcase a grid-based interface with an isometric 3D perspective.",
        bestPractices: "Optimize for performance by being mindful of the `gridSize`; a 3x3 or 4x4 grid is usually sufficient for a strong visual impact. Follow React best practices by ensuring the `rotateX` and `rotateZ` angles are set to standard isometric values (around 60 and -45) for the most natural look. Maintain scalable component architecture by using the `blockSize` prop for responsive layouts.",
        whyMatters: "Isometric design is a hallmark of premium modern frontend development. This animated UI component allows developers to build complex voxel-like grids that respond to user interaction, adding a layer of depth to your real-world application architecture.",
        faqs: [
            { question: "What is the best grid size for performance?", answer: "A 3x3 grid (9 blocks total) is the default and provides an excellent balance of visual detail and performance across all devices." },
            { question: "Can I change the colors for individual blocks?", answer: "The current implementation uses global hover and top face colors, but it can be extended to support per-block color mapping." },
            { question: "Is this component accessible?", answer: "Yes, you can add ARIA labels to the individual block containers to ensure accessibility compliance for screen readers." }
        ],
    },
    {
        id: "fold-brochure",
        name: "Folding Brochure",
        description: "3D folding brochure with backface visibility and page flip animation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["3d", "transform", "fold", "brochure", "flip"],
        previewUrl: "/Animations&Motion/3DTransforms/FoldBrochure",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "imageUrl", type: "string", default: "https://images.unsplash.com/photo-1633596683562-4a47eb4983c5?q=80&w=2664&auto=format&fit=crop", description: "Image URL for the brochure" },
            { name: "coverTitle", type: "string", default: "CLICK", description: "Title text on the cover" },
            { name: "coverSubtitle", type: "string", default: "To Reveal The Dimensions", description: "Subtitle text on the cover" },
            { name: "insideTitle", type: "string", default: "Architectural", description: "Title text on the inside" },
            { name: "insideDescription", type: "string", default: "Constructing interfaces with depth allows for greater information density without clutter.", description: "Description text on the inside" },
            { name: "statusText", type: "string", default: "System Status: Active", description: "Status text displayed" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "perspective", type: "string", default: "perspective-[1500px]", description: "CSS perspective value for 3D effect" },
            { name: "brochureWidth", type: "string", default: "w-[600px]", description: "Width of the brochure" },
            { name: "brochureHeight", type: "string", default: "h-[400px]", description: "Height of the brochure" },
            { name: "panelWidth", type: "string", default: "w-[300px]", description: "Width of each panel" },
            { name: "animationDuration", type: "number", default: "0.8", description: "Animation duration in seconds" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for Next.js applications that require a novel way to present information, such as interactive brochures or 'about us' pages. This production-ready component is perfect for startup landing pages where you want a physical, tactile feel for your content reveal.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the brochure's panels don't overlap with other UI elements when open. Follow React best practices by using high-resolution images for the cover to maintain a premium feel. Optimize for performance in large-scale applications by keeping the opening/closing animation concise.",
        whyMatters: "Real-world application architecture often benefits from mimicking real-world objects. This reusable React component provides a sophisticated folding brochure effect that adds semantic authority to your project, proving that digital interfaces can have physical character.",
        faqs: [
            { question: "How many panels are supported?", answer: "This component is designed as a classic bi-fold brochure with two interactive panels for a focused reveal experience." },
            { question: "Can I put interactive elements inside?", answer: "Absolutely! The inside panels can contain buttons, links, or any other interactive React components." },
            { question: "Does it support hover-to-open?", answer: "The default is click-to-open for more intentional interaction, but it can be easily modified to respond to hover states." }
        ],
    },
    {
        id: "interactive-cube",
        name: "Interactive Cube",
        description: "Full 3D cube with mouse-controlled rotation and floating core.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["3d", "transform", "cube", "interactive", "rotate"],
        previewUrl: "/Animations&Motion/3DTransforms/InteractiveCube",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "perspective", type: "string", default: "perspective-[800px]", description: "CSS perspective value for 3D effect" },
            { name: "cubeSize", type: "string", default: "w-48 h-48", description: "Size of the cube" },
            { name: "rotateXRange", type: "[number, number]", default: "[30, -30]", description: "Range of X-axis rotation in degrees" },
            { name: "rotateYRange", type: "[number, number]", default: "[-30, 30]", description: "Range of Y-axis rotation in degrees" },
            { name: "springStiffness", type: "number", default: "150", description: "Spring animation stiffness" },
            { name: "springDamping", type: "number", default: "20", description: "Spring animation damping" },
            { name: "coreSize", type: "string", default: "w-24 h-24", description: "Size of the floating core" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This customizable UI component is ideal for creative agencies, gaming platforms, or tech-focused SaaS landing pages. Use this React component when building hero sections that need a central, interactive focal point that users can 'play' with.",
        bestPractices: "Optimize for performance by ensuring the `cubeSize` is appropriate for the viewport. Follow React best practices by utilizing the `springStiffness` and `springDamping` props to create a realistic sense of inertia. Maintain scalable component architecture by keeping the 'core' content simple but visually distinct.",
        whyMatters: "Physics-based 3D interactions are at the core of modern frontend development trends. This production-ready component helps you implement a full 3D interactive cube using pure React logic, which is a great way to showcase technical prowess in your real-world application architecture.",
        faqs: [
            { question: "Is the rotation range limited?", answer: "Yes, you can set the `rotateXRange` and `rotateYRange` to prevent the cube from rotating too far and breaking the perspective." },
            { question: "Can I change the core's animation?", answer: "The core has a separate floating rotation duration, which can be customized to create a steady, hypnotic motion independent of user input." },
            { question: "Does it work with dark mode?", answer: "Yes, the component relies on CSS classes and props that can be easily themed for any lighting preference." }
        ],
    },
    {
        id: "cylinder-carousel",
        name: "Cylindrical Carousel",
        description: "Draggable 3D cylindrical carousel with perspective rotation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["3d", "transform", "carousel", "cylinder", "drag"],
        previewUrl: "/Animations&Motion/3DTransforms/CylinderCarousel",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs for the carousel" },
            { name: "cardCount", type: "number", default: "8", description: "Number of cards in the carousel" },
            { name: "backgroundColor", type: "string", default: "bg-[#111]", description: "Background color of the component" },
            { name: "perspective", type: "string", default: "perspective-[1000px]", description: "CSS perspective value for 3D effect" },
            { name: "containerSize", type: "string", default: "w-40 h-60", description: "Size of each card container" },
            { name: "radius", type: "number", default: "280", description: "Radius of the cylindrical carousel" },
            { name: "springStiffness", type: "number", default: "50", description: "Spring animation stiffness" },
            { name: "springDamping", type: "number", default: "20", description: "Spring animation damping" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for luxury brands and fashion-forward modern web applications that need a circular gallery. This production-ready React UI component is ideal for showcasing product lines or team members in a continuous, 3D cylindrical space.",
        bestPractices: "Maintain consistent spacing within your design system by calculating the `radius` based on the number of cards. Follow React best practices by using the `dragMultiplier` to ensure the interaction feels responsive but not jittery. Optimize for performance in large-scale applications by lazy-loading the images within the carousel.",
        whyMatters: "Cylindrical UI structures are a sophisticated way to manage horizontal content in modern UI development. This reusable React component provides a hardware-accelerated 3D carousel that enhances your real-world application architecture with a unique, draggable interaction.",
        faqs: [
            { question: "How many cards are recommended?", answer: "A card count of 8 to 12 usually provides the smoothest looking curve for the cylindrical effect." },
            { question: "Can I use it as a vertical cylinder?", answer: "The current implementation is horizontal, but the axis of rotation can be adapted for vertical scrolling with minor adjustments." },
            { question: "Is the dragging circular?", answer: "Yes, the dragging physics are mapped back to the cylinder's rotation, allowing for infinite circular navigation." }
        ],
    },
    {
        id: "voxel-grid",
        name: "Isometric Voxel Grid",
        description: "Reactive terrain grid with 3D elevation on hover.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["3d", "transform", "voxel", "grid", "terrain"],
        previewUrl: "/Animations&Motion/3DTransforms/VoxelGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "gridCols", type: "number", default: "5", description: "Number of columns in the grid" },
            { name: "gridRows", type: "number", default: "5", description: "Number of rows in the grid" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "perspective", type: "string", default: "perspective-1000", description: "CSS perspective value for 3D effect" },
            { name: "blockSize", type: "string", default: "w-16 h-16", description: "Size of each block" },
            { name: "defaultColor", type: "string", default: "#1f2937", description: "Default color of blocks" },
            { name: "hoverColor", type: "string", default: "#3b82f6", description: "Color of blocks on hover" },
            { name: "hoverBorderColor", type: "string", default: "#60a5fa", description: "Border color of blocks on hover" },
            { name: "sideColor", type: "string", default: "#18181b", description: "Color of the side faces" },
            { name: "sideHoverColor", type: "string", default: "#1d4ed8", description: "Color of the side faces on hover" },
            { name: "sideHoverColor2", type: "string", default: "#1e40af", description: "Secondary color of the side faces on hover" },
            { name: "hoverTranslateZ", type: "number", default: "40", description: "Z-axis translation on hover" },
            { name: "rotateX", type: "number", default: "60", description: "X-axis rotation in degrees" },
            { name: "rotateZ", type: "number", default: "-45", description: "Z-axis rotation in degrees" },
            { name: "springStiffness", type: "number", default: "300", description: "Spring animation stiffness" },
            { name: "springDamping", type: "number", default: "20", description: "Spring animation damping" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This customizable UI component is excellent for data visualization tools and modern web applications that want to visualize density or terrain. Use this React component when building interactive maps or background patterns that respond to the user's cursor.",
        bestPractices: "Optimize for performance in large-scale applications by keeping the `gridCols` and `gridRows` at a combined total under 50. Follow React best practices by ensuring high contrast between the `defaultColor` and `hoverColor`. Maintain scalable component architecture by using responsive `blockSize` classes.",
        whyMatters: "Voxel-based design patterns are becoming increasingly popular in tech-heavy modern frontend development. This animated UI component allows you to build a reactive 3D terrain grid that adds semantic authority and depth to your real-world application architecture.",
        faqs: [
            { question: "Does it support custom height mapping?", answer: "The current version uses mouse proximity for elevation, but it can be easily extended to use a data-driven height map." },
            { question: "Can I use a gradient for the blocks?", answer: "Yes, you can use the `sideHoverColor` and `sideHoverColor2` props to create a beautiful vertical gradient effect on hover." },
            { question: "Is the elevation spring-animated?", answer: "Yes, it uses Framer Motion's spring physics to ensure the rise and fall of each block feels natural and weighted." }
        ],
    },
    {
        id: "tunnel-vision",
        name: "Tunnel Vision",
        description: "Infinite tunnel effect with scaling rings moving through 3D space.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["3d", "transform", "tunnel", "rings", "infinite"],
        previewUrl: "/Animations&Motion/3DTransforms/TunnelVision",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "ringCount", type: "number", default: "5", description: "Number of rings in the tunnel" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "perspective", type: "string", default: "perspective-500", description: "CSS perspective value for 3D effect" },
            { name: "ringSize", type: "number", default: "300", description: "Base size of the rings" },
            { name: "ringBorderColor", type: "string", default: "border-zinc-500/30", description: "Border color of the rings" },
            { name: "text", type: "string", default: "WARP", description: "Text displayed in the center" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-4xl", description: "Size of the text" },
            { name: "initialZ", type: "number", default: "-1000", description: "Initial Z position of rings" },
            { name: "finalZ", type: "number", default: "500", description: "Final Z position of rings" },
            { name: "animationDuration", type: "number", default: "4", description: "Animation duration in seconds" },
            { name: "delayMultiplier", type: "number", default: "0.8", description: "Delay multiplier between rings" },
            { name: "scaleRange", type: "[number, number]", default: "[0.5, 1.5]", description: "Scale range for rings" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for artistic portfolios, experimental startup landing pages, and cinematic web experiences. This production-ready React UI component is perfect for intro sequences where you want to draw the user 'into' your site's world.",
        bestPractices: "To follow React best practices, ensure the `animationDuration` is slow enough to avoid motion sickness while still maintaining rhythm. Maintain consistent spacing within your design system by using the `perspective` prop to match other 3D components on your site. Optimize for performance by using a reasonable `ringCount` (e.g., 5-8).",
        whyMatters: "Infinite motion is a powerful tool for building immersive modern UI development experiences. This reusable React component gives developers a way to implement the 'dolly zoom' effect in a 2D space, adding incredible depth to your real-world application architecture.",
        faqs: [
            { question: "Can I put a video in the center?", answer: "Yes, the center of the tunnel is a standard React container where you can place text, videos, or even other components." },
            { question: "How do I control the depth?", answer: "The `initialZ` and `finalZ` props define the start and end of each ring's journey through 3D space." },
            { question: "Does the text pulse automatically?", answer: "Yes, there is a built-in `textPulseDuration` prop to keep the center element alive and engaging." }
        ],
    },
];

