import { getCode } from "../getCode";
import { Component } from "../components-data";

export const parallaxBackgroundComponents: Component[] = [
    {
        id: "z-axis-tunnel",
        name: "Z-Axis Tunnel",
        description: "Infinity scroll effect where you scroll into the screen with 3D layers.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "3d", "tunnel", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/ZAxisTunnel",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/tsx/ZAxisTunnel.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/jsx/ZAxisTunnel.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxBackgrounds/ZAxisTunnel/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "layerCount", type: "number", default: "5", description: "Number of layers" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "perspective", type: "string", default: "perspective-[100px]", description: "CSS perspective value" },
            { name: "containerHeight", type: "string", default: "h-[400vh]", description: "Height of the container" },
            { name: "text", type: "string", default: "WARP", description: "Text displayed" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-9xl", description: "Size of the text" },
            { name: "zStartOffset", type: "number", default: "-100", description: "Starting Z offset" },
            { name: "zEnd", type: "number", default: "100", description: "Ending Z position" },
            { name: "zStep", type: "number", default: "50", description: "Z step between layers" },
            { name: "rotationMultiplier", type: "number", default: "45", description: "Rotation multiplier" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for immersive storytelling, sci-fi themed landing pages, and cinematic Next.js portfolios. Use this React component to create a high-impact 'warp' effect where the user feels like they are traveling through infinite layers of content.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the `zStep` creates a clear sense of depth. Follow React best practices by providing high-quality images that work well with 3D scaling and rotation. Optimize for performance by limiting the `layerCount` to ensure smooth canvas or DOM rendering.",
        whyMatters: "Z-axis motion and tunnel zooms are a staple of premium modern UI development. This production-ready component provides a robust implementation of complex 3D perspective, adding a layer of polish and semantic authority to your real-world application architecture.",
        faqs: [
            { question: "How many images can I add?", answer: "The component is optimized for 3-7 layers. You can add more, but be mindful of browser memory usage for high-resolution images." },
            { question: "Can I adjust the rotation speed?", answer: "Yes, the `rotationMultiplier` prop allows you to make the tunnel spiral gently or spin rapidly as the user scrolls." },
            { question: "Is it responsive?", answer: "Yes, the perspective and scaling are relative to the viewport, ensuring a consistent 'warp' experience on all devices." }
        ],
    },
    {
        id: "broken-shard-gallery",
        name: "Broken Shard Gallery",
        description: "Images explode outward from center into a chaotic gallery layout.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "explosion", "gallery", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/BrokenShardGallery",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/tsx/BrokenShardGallery.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/jsx/BrokenShardGallery.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxBackgrounds/BrokenShardGallery/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "positions", type: "Array<{x: number, y: number, r: number}>", default: "[]", description: "Array of position configurations" },
            { name: "backgroundColor", type: "string", default: "bg-neutral-900", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "cardWidth", type: "string", default: "w-64", description: "Width of each card" },
            { name: "cardHeight", type: "string", default: "h-80", description: "Height of each card" },
            { name: "text", type: "string", default: "Disintegrate", description: "Text displayed" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-6xl", description: "Size of the text" },
            { name: "textFadeRange", type: "[number, number]", default: "[0, 0.2]", description: "Text fade progress range" },
            { name: "textScaleRange", type: "[number, number]", default: "[1, 3]", description: "Text scale range" },
            { name: "scaleRange", type: "[number, number, number]", default: "[1, 0.8, 1.2]", description: "Card scale range" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for high-energy product reveals, 'breaking news' sections, and experimental Next.js landing pages. Use this React component when you want to create a chaotic yet organized explosion of imagery that settles as the user scrolls.",
        bestPractices: "Follow React best practices by setting a `textFadeRange` that allows the central message to be read clearly. Maintain scalable component architecture by using a balanced `images` array that populates the layout without overlapping too much. Optimize for performance by using optimized image formats.",
        whyMatters: "Explosions and shard layouts add a dynamic, energetic quality to web galleries. This customizable UI component gives you a production-level implementation of complex fragment-based motion, adding semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Can I customize the shard positions?", answer: "Yes, the `positions` prop allows you to define exactly where each image starts and ends its 'shattering' journey." },
            { question: "How many images works best?", answer: "The component is designed for 6-12 shards for a truly 'broken' look, but it can work with fewer for a cleaner layout." },
            { question: "Is the explosion speed adjustable?", answer: "The motion is mapped to scroll progress, so the 'explosion' happens as fast or as slow as the user scrolls." }
        ],
    },
    {
        id: "skew-scroller",
        name: "Skew Scroller",
        description: "Velocity-based skew effect that deforms the layout based on scroll speed.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "skew", "velocity", "grid"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/SkewScroller",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/tsx/SkewScroller.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/jsx/SkewScroller.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxBackgrounds/SkewScroller/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "itemCount", type: "number", default: "24", description: "Number of items in the grid" },
            { name: "backgroundColor", type: "string", default: "bg-[#e1e1e1]", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[400vh]", description: "Height of the container" },
            { name: "noiseUrl", type: "string", default: "https://grainy-gradients.vercel.app/noise.svg", description: "URL of noise texture" },
            { name: "noiseOpacity", type: "number", default: "0.2", description: "Opacity of noise overlay" },
            { name: "rotation", type: "number", default: "-15", description: "Rotation angle in degrees" },
            { name: "scale", type: "number", default: "1.5", description: "Scale factor" },
            { name: "scrollRange", type: "[number, number]", default: "[0, 2000]", description: "Scroll range" },
            { name: "xRange", type: "[number, number]", default: "[0, -500]", description: "X position range" },
            { name: "yRange", type: "[number, number]", default: "[0, -1000]", description: "Y position range" },
            { name: "gridCols", type: "number", default: "4", description: "Number of grid columns" },
            { name: "aspectRatio", type: "string", default: "aspect-[3/4]", description: "Aspect ratio of items" },
            { name: "text", type: "string", default: "KINETIC\\nGRID", description: "Text displayed (use \\n for newlines)" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for high-fashion sites, modern editorial layouts, and high-performance Next.js landing pages. Use this React component for a kinetic grid that skews and deforms based on the intensity of the user's scrolling action.",
        bestPractices: "Maintain consistent spacing within your design system by using a clear `gridCols` configuration. Follow React best practices by providing a `noiseUrl` that adds texture without overpowering the content. Optimize for performance in large-scale applications by using hardware-accelerated skew transforms.",
        whyMatters: "Velocity-based skewing is a hallmark of high-end 'award-winning' modern UI design. This production-ready component helps you build an interface that feels fast and responsive, adding a layer of polish to your project's digital architecture.",
        faqs: [
            { question: "How intense is the skew effect?", answer: "The skew intensity is dynamic and mapped to scroll velocity, so it only deforms when the user is actively scrolling." },
            { question: "Does it work with standard images?", answer: "Yes, it works with any image URL and automatically fits them into the skewed grid structure." },
            { question: "Is the noise texture mandatory?", answer: "The noise adds a premium analogue feel, but can be removed by setting `noiseOpacity` to 0 for a cleaner digital look." }
        ],
    },
    {
        id: "pinwheel",
        name: "Pinwheel",
        description: "Circular rotating gallery with radial image arrangement.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "circular", "rotate", "gallery"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/Pinwheel",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/tsx/Pinwheel.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/jsx/Pinwheel.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxBackgrounds/Pinwheel/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "bladeCount", type: "number", default: "8", description: "Number of blades in the pinwheel" },
            { name: "backgroundColor", type: "string", default: "bg-slate-950", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "wheelSize", type: "string", default: "w-[150vh] h-[150vh]", description: "Size of the pinwheel" },
            { name: "bladeWidth", type: "string", default: "w-80", description: "Width of each blade" },
            { name: "bladeHeight", type: "string", default: "h-[50vh]", description: "Height of each blade" },
            { name: "bladeBgColor", type: "string", default: "bg-red-500/20", description: "Background color of blades" },
            { name: "centerSize", type: "string", default: "w-64 h-64", description: "Size of the center circle" },
            { name: "centerBgColor", type: "string", default: "bg-slate-950", description: "Background color of center" },
            { name: "centerBorderColor", type: "string", default: "border-white/20", description: "Border color of center" },
            { name: "centerText", type: "string", default: "ROTATE_Y", description: "Text in the center" },
            { name: "centerTextColor", type: "string", default: "text-white", description: "Color of center text" },
            { name: "centerTextSize", type: "string", default: "text-xl", description: "Size of center text" },
            { name: "rotationRange", type: "[number, number]", default: "[0, 360]", description: "Rotation range in degrees" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for creative studios, product showcases, and Next.js applications that want to emphasize a central hub. Use this React component to create a radial gallery that rotates like a pinwheel as the user scrolls down.",
        bestPractices: "Follow React best practices by using the `centerText` for high-impact branding. Maintain scalable component architecture by keeping the `bladeCount` reasonable (e.g., 6-12) for visual clarity. Optimize for performance by using efficient radial transforms for the images.",
        whyMatters: "Radial and circular galleries provide a unique alternative to standard linear grids. This reusable React component gives developers a robust way to implement complex polar-coordinate motion, adding semantic authority and visual movement to your real-world application architecture.",
        faqs: [
            { question: "Can I change the rotation direction?", answer: "Yes, by swapping the `rotationRange` values (e.g., from [360, 0]), you can make the pinwheel spin clockwise or counter-clockwise." },
            { question: "What size images should I use?", answer: "The `bladeWidth` and `bladeHeight` props let you adapt the blade size to any image aspect ratio." },
            { question: "Is the center circle interactive?", answer: "The center hub is designed for branding, but can be easily extended with hover effects or custom React children." }
        ],
    },
    {
        id: "masked-typography",
        name: "Masked Typography",
        description: "Giant text that clips background images and scales as you scroll through.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "typography", "mask", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/MaskedTypography",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/tsx/MaskedTypography.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/jsx/MaskedTypography.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxBackgrounds/MaskedTypography/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "backgroundColor", type: "string", default: "bg-white", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "gridCols", type: "number", default: "3", description: "Number of grid columns" },
            { name: "gridRows", type: "number", default: "3", description: "Number of grid rows" },
            { name: "text", type: "string", default: "VISION", description: "Text displayed" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-[20vw]", description: "Size of the text" },
            { name: "overlayColor", type: "string", default: "bg-blue-900/40", description: "Color of overlay" },
            { name: "overlayOpacity", type: "number", default: "0.4", description: "Opacity of overlay" },
            { name: "scaleRange", type: "[number, number]", default: "[1, 50]", description: "Scale range" },
            { name: "scaleProgressRange", type: "[number, number]", default: "[0, 0.8]", description: "Scale progress range" },
            { name: "opacityRange", type: "[number, number]", default: "[1, 0]", description: "Opacity range" },
            { name: "opacityProgressRange", type: "[number, number]", default: "[0.7, 0.8]", description: "Opacity progress range" },
            { name: "bgYRange", type: "[number, number]", default: "[0, 200]", description: "Background Y position range" },
            { name: "transitionText", type: "string", default: "Transition Complete", description: "Transition text displayed" },
            { name: "transitionTextColor", type: "string", default: "text-white", description: "Color of transition text" },
            { name: "transitionTextSize", type: "string", default: "text-2xl", description: "Size of transition text" },
            { name: "transitionOpacityRange", type: "[number, number]", default: "[0.75, 0.9]", description: "Transition opacity range" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for bold brand statements, visual storytelling, and Next.js landing pages that want to make an impact. Use this React component for 'giant' typography that acts as a window to your background imagery.",
        bestPractices: "Maintain consistent spacing within your design system by using high-contrast bold fonts. Follow React best practices by setting the `scaleRange` to allow the user to easily scroll 'through' the letters. Optimize for performance by using the `scaleProgressRange` to time the zoom effect perfectly.",
        whyMatters: "Masked typography is a powerful tool for visual hierarchy. This production-ready component provides a robust implementation of complex CSS masks and transforms, adding scale and semantic interest to your real-world application architecture.",
        faqs: [
            { question: "Can I change the font style?", answer: "Yes, the component inherits your global styles, but it is best paired with thick, sans-serif fonts for the best masking effect." },
            { question: "How fast should it scale?", answer: "The `scaleRange` determines the zoom intensity. A range of [1, 50] creates a fast, cinematic entry into the content." },
            { question: "Does it support video backgrounds?", answer: "While designed for images, the clipping logic can be easily applied to absolute-positioned video elements." }
        ],
    },
    {
        id: "parallax-slits",
        name: "Parallax Slits",
        description: "Vertical columns that move in alternating directions creating a shredder effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "columns", "vertical", "fragmentation"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/ParallaxSlits",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/tsx/ParallaxSlits.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/jsx/ParallaxSlits.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxBackgrounds/ParallaxSlits/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "columns", type: "number", default: "12", description: "Number of columns" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[250vh]", description: "Height of the container" },
            { name: "scrollDistance", type: "number", default: "400", description: "Scroll distance for parallax" },
            { name: "borderColor", type: "string", default: "border-black/50", description: "Border color between columns" },
            { name: "section1Bg", type: "string", default: "bg-zinc-800", description: "Background color of first section" },
            { name: "section2Bg", type: "string", default: "bg-zinc-900", description: "Background color of second section" },
            { name: "section2BorderColor", type: "string", default: "border-red-500", description: "Border color of second section" },
            { name: "imageOpacity", type: "number", default: "0.6", description: "Opacity of images" },
            { name: "text", type: "string", default: "Fragmentation", description: "Text displayed" },
            { name: "textColor", type: "string", default: "text-4xl", description: "Color class of the text" },
            { name: "textSize", type: "string", default: "text-4xl", description: "Size of the text" },
            { name: "textBgColor", type: "string", default: "bg-white", description: "Background color of text container" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for editorial portfolios, modern agency sites, and experimental Next.js landing pages. Use this React component to create a 'shredder' effect where vertical slices of an image move in alternating directions.",
        bestPractices: "Follow React best practices by provide high-resolution images that won't look blurry when shredded into columns. Maintain scalable component architecture by using a reasonable `columns` count (e.g., 8-16). Optimize for performance in large-scale applications by using CSS-based parallax math.",
        whyMatters: "Vertical fragmentation adds a sense of rhythm and digital texture to an interface. This customizable UI component gives you a production-level tool for building high-energy, fragmented layouts that add polish to your real-world application architecture.",
        faqs: [
            { question: "How many columns works best?", answer: "Between 10 and 16 columns usually creates the most striking 'shredder' effect without being too busy." },
            { question: "Can I move the columns horizontally?", answer: "No, this specific component is designed for coordinated vertical parallax, creating a unique 'slot machine' movement." },
            { question: "Is the background color visible?", answer: "Yes, the `backgroundColor` peaks through between the shredded columns, adding depth and contrast." }
        ],
    },
    {
        id: "horizontal-drag",
        name: "Horizontal Drag",
        description: "Vertical scroll drives a massive horizontal film strip with parallax cards.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "horizontal", "scroll", "film-strip"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/HorizontalDrag",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/tsx/HorizontalDrag.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/jsx/HorizontalDrag.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxBackgrounds/HorizontalDrag/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "itemCount", type: "number", default: "10", description: "Number of items in the strip" },
            { name: "backgroundColor", type: "string", default: "bg-[#1a1a1a]", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[500vh]", description: "Height of the container" },
            { name: "gap", type: "string", default: "gap-20", description: "Gap between items" },
            { name: "padding", type: "string", default: "px-20", description: "Horizontal padding" },
            { name: "itemWidth", type: "string", default: "w-[60vw]", description: "Width of each item" },
            { name: "itemHeight", type: "string", default: "h-[70vh]", description: "Height of each item" },
            { name: "imageScale", type: "number", default: "1.2", description: "Scale of images" },
            { name: "imageXRange", type: "[number, number]", default: "[-50, 50]", description: "Image X position range" },
            { name: "xRange", type: "[string, string]", default: "[\"0%\", \"-80%\"]", description: "Container X position range" },
            { name: "numberColor", type: "string", default: "text-transparent", description: "Color of number labels" },
            { name: "numberSize", type: "string", default: "text-6xl", description: "Size of number labels" },
            { name: "numberStrokeWidth", type: "string", default: "2px", description: "Stroke width of numbers" },
            { name: "numberStrokeColor", type: "string", default: "rgba(255,255,255,0.2)", description: "Stroke color of numbers" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for product galleries, photography portfolios, and modern Next.js commerce sites. Use this React component for a massive, cinematic 'film strip' that slides horizontally across the screen as the user scrolls vertically.",
        bestPractices: "Maintain consistent spacing within your design system by using a clear `gap` between items. Follow React best practices by ensures the `itemWidth` doesn't cut off important image details on mobile. Optimize for performance by using efficient X-axis transforms for the strip movement.",
        whyMatters: "Horizontal flow within a vertical scroll provides a refreshing break for the user. This reusable React component gives developers a robust way to implement complex viewport-driven horizontal motion, adding a layer of sophistication to your real-world application architecture.",
        faqs: [
            { question: "How long can the film strip be?", answer: "The `itemCount` determines the strip length. It can handle dozens of items, provided they are properly lazy-loaded." },
            { question: "Can I hide the numbers?", answer: "Yes, the `numberColor` can be set to 'transparent' to remove the labels for a cleaner, image-focused look." },
            { question: "Does it support drag interactions?", answer: "The movement is mapped to scroll, but it can be easily updated with Framer Motion drag props for touch-based exploration." }
        ],
    },
    {
        id: "kaleidoscope-grid",
        name: "Kaleidoscope Grid",
        description: "Four quadrants moving in different directions creating a kaleidoscope effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "quadrants", "multi-directional", "grid"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/KaleidoscopeGrid",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/tsx/KaleidoscopeGrid.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxBackgrounds/jsx/KaleidoscopeGrid.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxBackgrounds/KaleidoscopeGrid/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs (minimum 4)" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "gridGap", type: "string", default: "gap-4", description: "Gap between grid items" },
            { name: "gridPadding", type: "string", default: "p-4", description: "Padding of the grid" },
            { name: "borderRadius", type: "string", default: "rounded-3xl", description: "Border radius of grid items" },
            { name: "borderWidth", type: "string", default: "border-2", description: "Border width of grid items" },
            { name: "borderColor", type: "string", default: "border-white/10", description: "Border color of grid items" },
            { name: "imageScale", type: "string", default: "w-[150%] h-[150%]", description: "Scale of images" },
            { name: "imageTransform", type: "string", default: "translate(-20%, -20%)", description: "Transform of images" },
            { name: "imageOpacity", type: "number", default: "0.8", description: "Opacity of images" },
            { name: "parallaxDistance", type: "number", default: "300", description: "Parallax movement distance" },
            { name: "cornerLabels", type: "string[]", default: "[\"NORTH-WEST\", \"\", \"\", \"SOUTH-EAST\"]", description: "Labels for corners" },
            { name: "cornerLabelColor", type: "string", default: "text-white", description: "Color of corner labels" },
            { name: "cornerLabelSize", type: "string", default: "text-4xl", description: "Size of corner labels" },
            { name: "centerCircleSize", type: "string", default: "w-20 h-20", description: "Size of center circle" },
            { name: "centerCircleColor", type: "string", default: "bg-white", description: "Color of center circle" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for high-end digital agencies, creative studios, and Next.js applications that want to emphasize multi-faceted visions. Use this React component for an interactive grid that moves in four different directions simultaneously.",
        bestPractices: "Follow React best practices by using at least four distinct images for the quadrants. Maintain scalable component architecture by using high-contrast `cornerLabels` to anchor the design. Optimize for performance in large-scale applications by using clean quadrant-based transforms.",
        whyMatters: "Symmetrical, multi-directional motion is visually arresting and feels highly engineered. This production-ready component provide a robust implementation of complex coordinated movement, adding a layer of 'kaleidoscopic' polish to your real-world application architecture.",
        faqs: [
            { question: "Can I use more than four images?", answer: "The component is optimized for four quadrants, but you can layer multiple Kaleidoscope Grids to create more complex patterns." },
            { question: "What do the corner labels do?", answer: "They provide a way to add navigational cues or thematic titles to each quadrant's direction of movement." },
            { question: "Can I change the gap size?", answer: "Yes, the `gridGap` prop allows you to make the quadrants touch seamlessly or have a wide, distinct border." }
        ],
    },
];

