import { Component } from "../types";

export const cardComponentsMetadata: Component[] = [
    {
        id: "card-cinematic",
        name: "Cinematic Movie Card",
        description: "A premium, motion-heavy card inspired by modern streaming platforms. Features expanding headers, cinematic fades, and high-impact typography for movie or portfolio showcases.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "cinematic", "movie", "animation", "hover effect", "premium"],
        previewUrl: "/UIComponents/Cards/CardCinematic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "lucide-react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "'Cinema'", description: "Main title of the card." },
            { name: "director", type: "string", default: "'Dir. Nolan'", description: "Secondary info text for the top/bottom bars." },
            { name: "image", type: "string", default: "Unsplash URL", description: "Background image source." },
            { name: "barColor", type: "string", default: "'#000000'", description: "Color of the cinematic bars." },
        ],
    },
    {
        id: "card-dynamic",
        name: "Dynamic Action Card",
        description: "An interactive, expandable card that transitions between 'processing' and 'complete' states. Perfect for file uploads, status updates, or interactive dashboards.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "dynamic", "status", "interactive", "animation", "framer-motion"],
        previewUrl: "/UIComponents/Cards/CardDynamic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "framer-motion"],
        props: [
            { name: "processingText", type: "string", default: "'Processing...'", description: "Text shown when the card is collapsed." },
            { name: "title", type: "string", default: "'Transfer Complete'", description: "Heading for the expanded state." },
            { name: "collapsedWidth", type: "string", default: "'16rem'", description: "Width when only showing its initial state." },
            { name: "backgroundColor", type: "string", default: "'#000000'", description: "Main card background color." },
        ],
    },
    {
        id: "card-floating-badge",
        name: "Floating Badge Product Card",
        description: "A minimalist product display card featuring a 3D-effect floating image and an animated notification badge. Designed for e-commerce and featured item grids.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "product", "badge", "e-commerce", "minimal", "3d effect"],
        previewUrl: "/UIComponents/Cards/CardFloatingBadge",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "framer-motion"],
        props: [
            { name: "title", type: "string", default: "'Nike Air Max'", description: "Product name header." },
            { name: "price", type: "string", default: "'$129.00'", description: "Pricing subtext." },
            { name: "badgeText", type: "string", default: "'NEW'", description: "Text for the floating badge tag." },
            { name: "image", type: "string", default: "Unsplash URL", description: "Source for the product silhouette." },
        ],
    },
    {
        id: "uilora-glass-pricing-card",
        name: "Glassmorphic Pricing Card",
        description: "A futuristic pricing tier component with high-octane glassmorphism, glowing borders, and animated gradients. Built for premium SaaS landing pages.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "pricing", "glassmorphism", "glow", "saas", "premium"],
        previewUrl: "/UIComponents/Cards/UiloraGlassPricingCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "lucide-react", "next"],
        props: [
            { name: "plan", type: "string", default: "'Premium Plus'", description: "Plan name." },
            { name: "price", type: "string", default: "'$29.99'", description: "Numeric price." },
            { name: "features", type: "string[]", default: "['Unlimited...', ...]", description: "List of plan offerings." },
            { name: "cta", type: "string", default: "'Get Started Now'", description: "Main button call to action." },
        ],
    },
    {
        id: "uilora-input-card",
        name: "AI Prompt Input Card",
        description: "A specialized interaction card for AI-driven applications. Features a clean dark aesthetic, glass glow accents, and utility action buttons for file attachments and web searches.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "input", "AI", "prompt", "dark mode", "utility"],
        previewUrl: "/UIComponents/Cards/UiloraInputCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "lucide-react"],
        props: [
            { name: "title", type: "string", default: "'Imagine Something... ✨'", description: "Header text for the input box." },
            { name: "placeholder", type: "string", default: "'Describe your vision...'", description: "Grayed out hint text." },
        ],
    },
    {
        id: "uilora-keyboard-card",
        name: "Mechanical Keyboard Showcase",
        description: "A stunning, full-detail mechanical keyboard component with a signature Indigo/Blue glow theme. Uses styled-components for complex lighting and keycap depth.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "keyboard", "skeuomorphic", "blue theme", "interactive", "indigo"],
        previewUrl: "/UIComponents/Cards/UiloraKeyboardCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "styled-components"],
        props: [],
    },
    {
        id: "uilora-modern-blog-card",
        name: "Modern Narrative Blog Card",
        description: "A vertical card designed for high-end editorial content. Features a top-to-bottom gradient, bold condensed typography, and a hidden 'Arrow' action button revealed on hover.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "blog", "editorial", "modern", "image", "overlay"],
        previewUrl: "/UIComponents/Cards/UiloraModernBlogCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react"],
        props: [
            { name: "tag", type: "string", default: "'WHAT TO WATCH'", description: "Small category text at the top." },
            { name: "title", type: "string", default: "'Stream the Acme event'", description: "Main headline." },
            { name: "image", type: "string", default: "Unsplash URL", description: "Background cover image." },
        ],
    },
    {
        id: "uilora-music-card",
        name: "Spotify-Style Glass Player",
        description: "A sleek music/album card with frosted glass textures and sky-blue accents. Includes track counts, subtitles, and a hover-active album art scale effect.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "music", "player", "spotify", "glass", "minimal"],
        previewUrl: "/UIComponents/Cards/UiloraMusicCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react"],
        props: [
            { name: "title", type: "string", default: "'Frontend Radio'", description: "Station or album name." },
            { name: "subtitle", type: "string", default: "'DAILY MIX'", description: "Secondary tag line." },
            { name: "tracks", type: "string", default: "'12 Tracks'", description: "Content description." },
        ],
    },
    {
        id: "uilora-overlay-card",
        name: "Utility Glass Overlay Card",
        description: "A minimalist square card with a persistent 'Notify me' glass footer. Ideal for coming-soon items, gated content, or quick-action product displays.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "overlay", "glassmorphism", "minimal", "utility"],
        previewUrl: "/UIComponents/Cards/UiloraOverlayCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react"],
        props: [
            { name: "footerText", type: "string", default: "'Available soon.'", description: "Text inside the glass pill." },
            { name: "buttonText", type: "string", default: "'Notify me'", description: "Action button label." },
        ],
    },
    {
        id: "uilora-profile-card",
        name: "Designer Portfolio Card",
        description: "A professional profile card with a deep gradient overlay and a signature floating 'Plus' button. Optimized for team pages and visual designer showcases.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "profile", "team", "portfolio", "designer", "modern"],
        previewUrl: "/UIComponents/Cards/UiloraProfileCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "lucide-react"],
        props: [
            { name: "name", type: "string", default: "'Sarah Johnson'", description: "Person's name." },
            { name: "role", type: "string", default: "'Visual Designer'", description: "Job title or role." },
        ],
    },
    {
        id: "uilora-success-card",
        name: "Cyan Glow Checklist Card",
        description: "An encouraging achievement or feature list card. Features a soft corner glow, cyan checkmarks, and a powerful gradient button.",
        category: "UI Components",
        installType: "cli",
        tags: ["card", "success", "checklist", "features", "cyan", "glow"],
        previewUrl: "/UIComponents/Cards/UiloraSuccessCard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["react", "lucide-react"],
        props: [
            { name: "title", type: "string", default: "'Keys to Success'", description: "Main card header." },
            { name: "items", type: "string[]", default: "['Set...', ...]", description: "Checklist items array." },
            { name: "buttonText", type: "string", default: "'Get Your Success'", description: "Main activation button text." },
        ],
    },
];

