import { getCode } from "../getCode";
import { Component } from "../types";

export const authComponents: Component[] = [
    {
        id: "secure-reset",
        name: "Secure Reset",
        description: "Secure password reset form with real-time strength meter, password visibility toggle, and validation. Features animated strength indicators and confirmation field.",
        category: "Core Landing Pages",
        tags: ["core-landing-pages", "auth", "password", "reset", "security", "strength-meter", "validation"],
        previewUrl: "/CoreLandingPages/Auth/SecureReset",
        code: {
            tsx: getCode("src/components/CoreLandingPages/Auth/tsx/SecureReset.tsx"),
            jsx: getCode("src/components/CoreLandingPages/Auth/jsx/SecureReset.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/CoreLandingPages/Auth/SecureReset/page.tsx") },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "title", type: "string", default: '"Set New Password"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Ensure it\'s at least 8 chars long."', description: "Subtitle text displayed below the title." },
            { name: "onSubmit", type: "(data: { password: string; confirmPassword: string }) => Promise<void>", default: "undefined", description: "Callback function called when form is submitted with password data." },
            { name: "onStrengthChange", type: "(strength: number) => void", default: "undefined", description: "Callback function called when password strength changes (0-4 scale)." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "minLength", type: "number", default: "8", description: "Minimum password length requirement." },
            { name: "showStrengthMeter", type: "boolean", default: "true", description: "Whether to display the password strength meter." },
        ],
        whenToUse: "Ideal for high-security SaaS platforms, fintech applications, and Next.js sites that require a robust password recovery flow. Use this React component for a secure reset experience with real-time feedback and clear validation rules.",
        bestPractices: "Follow React best practices by managed the strength logic on the client for immediate feedback. Maintain scalable component architecture by keeping validation rules consistent with your backend. Optimize for performance by using efficient regex checks.",
        whyMatters: "A secure reset flow reduces support overhead and builds user trust. This production-ready UI component helpsคุณ build an interface that feels safe and professional, ensuring users can recover their accounts without friction or technical confusion.",
        faqs: [
            { question: "How is strength calculated?", answer: "The component uses a built-in entropy algorithm that checks for length, character variety (symbols, numbers), and common patterns." },
            { question: "Can I customize validation?", answer: "Yes, the `minLength` prop controls length, and you can extend the `onSubmit` logic to include complex requirements like 'no sequential numbers'." },
            { question: "Does it support dark mode?", answer: "The component is designed as a neutral, high-contrast module that adapts to your primary application theme's background and text colors." }
        ],
    },
    {
        id: "magic-link",
        name: "Magic Link",
        description: "Passwordless authentication with magic link email. Features 3D card flip animation on success, gradient shimmer effects, and animated success overlay.",
        category: "Core Landing Pages",
        tags: ["core-landing-pages", "auth", "magic-link", "passwordless", "email", "3d", "animation"],
        previewUrl: "/CoreLandingPages/Auth/MagicLink",
        code: {
            tsx: getCode("src/components/CoreLandingPages/Auth/tsx/MagicLink.tsx"),
            jsx: getCode("src/components/CoreLandingPages/Auth/jsx/MagicLink.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/CoreLandingPages/Auth/MagicLink/page.tsx") },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "title", type: "string", default: '"Magic Link"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Passwordless login."', description: "Subtitle text displayed below the title." },
            { name: "onSendLink", type: "(email: string) => Promise<void>", default: "undefined", description: "Callback function called when magic link is sent." },
            { name: "companyName", type: "string", default: '"Acme Inc."', description: "Company name displayed in the logo area." },
            { name: "showCompanyLogo", type: "boolean", default: "true", description: "Whether to display the company logo." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "successTitle", type: "string", default: '"Check your email"', description: "Title text displayed in the success overlay." },
            { name: "successMessage", type: "string", default: '"Click the link in the email we just sent you."', description: "Message text displayed in the success overlay." },
        ],
        whenToUse: "Excellent for modern startups, mobile-first apps, and Next.js platforms that want a passwordless 'Magic Link' aesthetic. Use this React component for a friction-free login experience with smooth 3D transitions and ambient gradients.",
        bestPractices: "Maintain consistent spacing within your design system by using it for primary login hubs. Follow React best practices by managed the email delivery state. Optimize for performance by using efficient Framer Motion layout animations.",
        whyMatters: "Magic links eliminate password fatigue and improve conversion. This production-ready UI component helpsคุณ build an interface that feels magical and effortless, leaving a lasting positive impression on your users.",
        faqs: [
            { question: "What is the 3D flip?", answer: "Upon successful email submission, the card smoothly flips 180 degrees using Framer Motion 3D transforms to reveal the success message." },
            { question: "Can I add social logins?", answer: "While designed for email, the card layout is flexible enough to include 'Sign in with Google/GitHub' buttons below the main input." },
            { question: "Is it mobile responsive?", answer: "The magic link card maintains its 3D aspect ratio and legibility on mobile, providing a high-end feel even on smaller screens." }
        ],
    },
    {
        id: "glass-forgot",
        name: "Glass Forgot",
        description: "Glassmorphism-style forgot password form with animated background blobs, gradient borders, and smooth state transitions. Features success state with checkmark animation.",
        category: "Core Landing Pages",
        tags: ["core-landing-pages", "auth", "forgot-password", "glassmorphism", "blur", "gradient"],
        previewUrl: "/CoreLandingPages/Auth/GlassForgot",
        code: {
            tsx: getCode("src/components/CoreLandingPages/Auth/tsx/GlassForgot.tsx"),
            jsx: getCode("src/components/CoreLandingPages/Auth/jsx/GlassForgot.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/CoreLandingPages/Auth/GlassForgot/page.tsx") },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "title", type: "string", default: '"Reset Password"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Enter your email to receive a reset link."', description: "Subtitle text displayed below the title." },
            { name: "onSendLink", type: "(email: string) => Promise<void>", default: "undefined", description: "Callback function called when reset link is sent." },
            { name: "onBack", type: "() => void", default: "undefined", description: "Callback function called when back button is clicked." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "successMessage", type: "string", default: '"We\'ve sent a password reset link to your email address."', description: "Success message displayed after link is sent." },
        ],
        whenToUse: "Ideal for creative agencies, design tools, and Next.js sites that want a modern 'Glassmorphism' aesthetic. Use this React component for a forgot-password flow with blurred background blobs and soft, crystalline borders.",
        bestPractices: "Maintain consistent spacing within your design system by using it on vibrant or photo-based backgrounds for maximum 'Glass' impact. Follow React best practices by pairing it with clear typography. Optimize for performance by managed the backdrop-blur intensity.",
        whyMatters: "Glassmorphism creates a sense of depth and digital premium. This production-ready UI component helpsคุณ build an interface that feels lightweight and high-end, turning a standard recovery form into a visual highlight.",
        faqs: [
            { question: "How is the glass effect made?", answer: "The component uses `backdrop-filter: blur()` and semi-transparent white/gray backgrounds to simulate physical frosted glass." },
            { question: "Are the background blobs animated?", answer: "Yes, the component features slow-moving ambient blobs that drift behind the glass container to reinforce the sense of depth." },
            { question: "Is it readable on light backgrounds?", answer: "The 'Glass' effect works best on medium-to-dark colors; for pure white backgrounds, adjust the `className` to increase the border opacity." }
        ],
    },
    {
        id: "otp-code",
        name: "OTP Code",
        description: "One-time password verification with auto-focus, keyboard navigation, and resend cooldown timer. Features animated input fields with glow effects and focus states.",
        category: "Core Landing Pages",
        tags: ["core-landing-pages", "auth", "otp", "verification", "code", "2fa", "security"],
        previewUrl: "/CoreLandingPages/Auth/OTPCode",
        code: {
            tsx: getCode("src/components/CoreLandingPages/Auth/tsx/OTPCode.tsx"),
            jsx: getCode("src/components/CoreLandingPages/Auth/jsx/OTPCode.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/CoreLandingPages/Auth/OTPCode/page.tsx") },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "title", type: "string", default: '"Verify Identity"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Enter the 4-digit code sent to your device."', description: "Subtitle text displayed below the title." },
            { name: "length", type: "number", default: "4", description: "Number of OTP code digits." },
            { name: "onComplete", type: "(code: string) => void", default: "undefined", description: "Callback function called when OTP code is complete." },
            { name: "onResend", type: "() => void", default: "undefined", description: "Callback function called when resend button is clicked." },
            { name: "resendCooldown", type: "number", default: "30", description: "Cooldown time in seconds before resend is allowed." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "autoFocus", type: "boolean", default: "true", description: "Whether to automatically focus the first input field." },
        ],
        whenToUse: "Perfect for security tools, banking apps, and Next.js platforms that require 2FA or device verification. Use this React component for an OTP (One-Time Password) experience with auto-focus inputs and technical glow effects.",
        bestPractices: "Follow React best practices by managed the keyboard focus flow across inputs. Maintain scalable component architecture by keeping the code length configurable. Optimize for performance by managed the resend timer efficiently.",
        whyMatters: "Smooth OTP flows reduce user drop-off during sensitive verification steps. This production-ready UI component helpsคุณ build an interface that feels precise and secure, improving the overall reliability of your authentication process.",
        faqs: [
            { question: "Does it auto-focus?", answer: "Yes, the component automatically focuses the first digit field on mount and moves the cursor forward as the user types or pastes the code." },
            { question: "Can I use 6 digits?", answer: "The `length` prop defaults to 4 but can be set to 6 or any other number to match your platform's security requirements." },
            { question: "What is the resend cooldown?", answer: "The `resendCooldown` prop (default 30s) prevents spam by disabling the resend button until the countdown reaches zero." }
        ],
    },
    {
        id: "split-signup",
        name: "Split Signup",
        description: "Split-screen signup form with animated left panel showcase and gradient backgrounds. Features rotating border animations and hover effects on the showcase card.",
        category: "Core Landing Pages",
        tags: ["core-landing-pages", "auth", "signup", "split", "showcase", "gradient", "animation"],
        previewUrl: "/CoreLandingPages/Auth/SplitSignup",
        code: {
            tsx: getCode("src/components/CoreLandingPages/Auth/tsx/SplitSignup.tsx"),
            jsx: getCode("src/components/CoreLandingPages/Auth/jsx/SplitSignup.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/CoreLandingPages/Auth/SplitSignup/page.tsx") },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "theme", type: "'dark' | 'light'", default: "undefined", description: "Color theme for the component." },
            { name: "accentColor", type: "string", default: "undefined", description: "Custom accent color for the component." },
            { name: "title", type: "string", default: '"Create Account"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Start your 14-day free trial."', description: "Subtitle text displayed below the title." },
            { name: "showLogo", type: "boolean", default: "undefined", description: "Whether to display the logo." },
            { name: "onSubmit", type: "(data: any) => Promise<void>", default: "undefined", description: "Callback function called when form is submitted." },
            { name: "onSuccess", type: "() => void", default: "undefined", description: "Callback function called on successful submission." },
            { name: "onError", type: "(err: string) => void", default: "undefined", description: "Callback function called on submission error." },
            { name: "loading", type: "boolean", default: "undefined", description: "Whether the form is in a loading state." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "showLeftPanel", type: "boolean", default: "true", description: "Whether to display the left showcase panel." },
        ],
        whenToUse: "Excellent for marketing-heavy landing pages, enterprise SaaS, and Next.js sites that want a high-impact 'Split Screen' aesthetic. Use this React component for a signup experience with a dedicated marketing showcase panel and clean form layout.",
        bestPractices: "Maintain consistent spacing within your design system by using high-resolution assets in the left panel. Follow React best practices by managed the multi-field form state. Optimize for performance by lazy-loading the showcase imagery.",
        whyMatters: "Split-screen layouts combine utility with brand storytelling. This production-ready UI component helpsคุณ build an interface that feels energetic and professional, summarizing your value proposition alongside the registration form.",
        faqs: [
            { question: "Can I hide the left panel?", answer: "Yes, the `showLeftPanel` prop allows you to toggle the showcase off for a focused, single-column signup experience on specific routes." },
            { question: "Does it support social login?", answer: "The form layout is optimized for traditional email/password but can easily be extended with branded provider buttons." },
            { question: "How does the rotating border work?", answer: "The showcase container features a slow-moving gradient border that uses CSS Conic Gradients and Framer Motion for a subtle 'Glow' effect." }
        ],
    },
    {
        id: "cinematic-login",
        name: "Cinematic Login",
        description: "Cinematic login form with ambient background gradients, animated glow effects, and social authentication options. Features smooth loading states and hover animations.",
        category: "Core Landing Pages",
        tags: ["core-landing-pages", "auth", "login", "cinematic", "ambient", "social", "gradient"],
        previewUrl: "/CoreLandingPages/Auth/CinematicLogin",
        code: {
            tsx: getCode("src/components/CoreLandingPages/Auth/tsx/CinematicLogin.tsx"),
            jsx: getCode("src/components/CoreLandingPages/Auth/jsx/CinematicLogin.jsx"),
        },
        usageCode: { tsx: getCode("src/app/(routes)/CoreLandingPages/Auth/CinematicLogin/page.tsx") },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "theme", type: "'dark' | 'light'", default: "undefined", description: "Color theme for the component." },
            { name: "accentColor", type: "string", default: "undefined", description: "Custom accent color for the component." },
            { name: "title", type: "string", default: '"Welcome Back"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Enter your credentials to access the nexus."', description: "Subtitle text displayed below the title." },
            { name: "showLogo", type: "boolean", default: "undefined", description: "Whether to display the logo." },
            { name: "onSubmit", type: "(data: any) => Promise<void>", default: "undefined", description: "Callback function called when form is submitted." },
            { name: "onSuccess", type: "() => void", default: "undefined", description: "Callback function called on successful submission." },
            { name: "onError", type: "(err: string) => void", default: "undefined", description: "Callback function called on submission error." },
            { name: "loading", type: "boolean", default: "undefined", description: "Whether the form is in a loading state." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
        whenToUse: "Ideal for high-end digital products, entertainment platforms, and Next.js applications that want an immersive 'Cinematic' aesthetic. Use this React component for a login experience with ambient glow effects, soft gradients, and polished social buttons.",
        bestPractices: "Follow React best practices by pairing this with dark-themed hero sections. Maintain scalable component architecture by keeping branding consistent. Optimize for performance by managed the background gradient pulses.",
        whyMatters: "Cinematic aesthetics create a sense of scale and digital atmosphere. This production-ready UI component helpsคุณ build an interface that feels high-fidelity and atmospheric, improving the perceived quality of your premium brand.",
        faqs: [
            { question: "What are 'Ambient Glows'?", answer: "The component features localized, soft glowing points behind the login box that pulse slowly, simulating environmental light for a deep 3D feel." },
            { question: "Can I use solid colors?", answer: "Yes, by setting the `accentColor` and using the `light` theme, you can transform the cinematic look into a clean, modern corporate aesthetic." },
            { question: "Is it mobile friendly?", answer: "The cinematic glows and ambient gradients are optimized to remain visually impactful without sacrificing performance on mobile GPUs." }
        ],
    },
];

