// Client-safe metadata export (no code, just metadata)
// This can be imported in client components
import { Component } from "../types";

export const heroSectionComponentsMetadata: Component[] = [
    {
        id: "cartoonish",
        name: "Cartoonish",
        description: "Playful cartoon-style hero section with fun animations and vibrant colors.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["cartoonish", "playful", "fun", "vibrant"],
        previewUrl: "/CoreLandingPages/HeroSections/Cartoonish",
        code: { tsx: "" },
        dependencies: ["lucide-react", "gsap"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#ff006e",
                description: "Primary playful color for main elements.",
            },
            {
                name: "secondaryColor",
                type: "string",
                default: "#8338ec",
                description: "Secondary vibrant color for accents.",
            },
            {
                name: "bounceIntensity",
                type: "number",
                default: "1",
                description: "Intensity of bounce animations (0.5-2).",
            },
            {
                name: "enableAnimations",
                type: "boolean",
                default: "true",
                description: "Enable fun cartoon animations.",
            },
        ],
    },
    {
        id: "draggable",
        name: "Draggable",
        description: "Interactive hero section with draggable elements and smooth physics-based interactions.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["draggable", "interactive", "physics", "smooth"],
        previewUrl: "/CoreLandingPages/HeroSections/Draggable",
        code: { tsx: "" },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#3b82f6",
                description: "Primary color for draggable elements.",
            },
            {
                name: "dragStiffness",
                type: "number",
                default: "300",
                description: "Stiffness of drag physics (100-500).",
            },
            {
                name: "dragDamping",
                type: "number",
                default: "30",
                description: "Damping of drag physics (10-50).",
            },
            {
                name: "enableConstraints",
                type: "boolean",
                default: "true",
                description: "Enable drag constraints and boundaries.",
            },
        ],
    },
    {
        id: "glass-operating-system",
        name: "Glass Operating System",
        description: "Glassmorphism hero section with frosted glass effects and modern OS-inspired design.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["glass", "glassmorphism", "frosted", "modern"],
        previewUrl: "/CoreLandingPages/HeroSections/GlassOperatingSystem",
        code: { tsx: "" },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            {
                name: "glassBlur",
                type: "string",
                default: "20px",
                description: "Blur intensity for glass effect.",
            },
            {
                name: "glassOpacity",
                type: "number",
                default: "0.3",
                description: "Opacity of glass elements (0-1).",
            },
            {
                name: "backgroundColor",
                type: "string",
                default: "#0a0a0a",
                description: "Background color behind glass.",
            },
            {
                name: "borderColor",
                type: "string",
                default: "rgba(255,255,255,0.1)",
                description: "Border color for glass elements.",
            },
        ],
    },
    {
        id: "holographic-core",
        name: "Holographic Core",
        description: "Futuristic holographic hero section with sci-fi aesthetics and glowing effects.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["holographic", "futuristic", "sci-fi", "glow"],
        previewUrl: "/CoreLandingPages/HeroSections/HolographicCore",
        code: { tsx: "" },
        dependencies: ["framer-motion", "lucide-react", "@react-three/fiber", "@react-three/drei"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#4f46e5",
                description: "Primary holographic color (indigo).",
            },
            {
                name: "glowIntensity",
                type: "number",
                default: "1",
                description: "Intensity of glow effects (0-2).",
            },
            {
                name: "distortAmount",
                type: "number",
                default: "0.4",
                description: "Distortion amount for holographic effect (0-1).",
            },
            {
                name: "rotationSpeed",
                type: "number",
                default: "1",
                description: "Speed of 3D rotation (0.5-2).",
            },
        ],
    },
    {
        id: "industrial-sentience",
        name: "Industrial Sentience",
        description: "Industrial-themed hero section with mechanical aesthetics and sentient design elements.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["industrial", "mechanical", "sentient", "dark"],
        previewUrl: "/CoreLandingPages/HeroSections/IndustrialSentience",
        code: { tsx: "" },
        dependencies: ["framer-motion", "lucide-react"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#ef4444",
                description: "Primary industrial color (red/orange).",
            },
            {
                name: "backgroundColor",
                type: "string",
                default: "#0a0a0a",
                description: "Dark industrial background color.",
            },
            {
                name: "enableMechanical",
                type: "boolean",
                default: "true",
                description: "Enable mechanical animation effects.",
            },
            {
                name: "animationSpeed",
                type: "number",
                default: "1",
                description: "Speed of industrial animations.",
            },
        ],
    },
    {
        id: "living-porcelain",
        name: "Living Porcelain",
        description: "Elegant hero section with porcelain-like textures and organic, living animations.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["porcelain", "elegant", "organic", "texture"],
        previewUrl: "/CoreLandingPages/HeroSections/LivingPorcelain",
        code: { tsx: "" },
        dependencies: ["framer-motion", "lucide-react", "@react-three/fiber", "@react-three/drei"],
        props: [
            {
                name: "porcelainColor",
                type: "string",
                default: "#fefefe",
                description: "Porcelain white/cream color.",
            },
            {
                name: "textureIntensity",
                type: "number",
                default: "1",
                description: "Intensity of porcelain texture (0-2).",
            },
            {
                name: "organicSpeed",
                type: "number",
                default: "1",
                description: "Speed of organic living animations.",
            },
            {
                name: "enableBreathing",
                type: "boolean",
                default: "true",
                description: "Enable breathing/living animation effect.",
            },
        ],
    },
    {
        id: "marble",
        name: "Marble",
        description: "Luxurious marble-textured hero section with sophisticated design and premium feel.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["marble", "luxury", "sophisticated", "premium"],
        previewUrl: "/CoreLandingPages/HeroSections/Marble",
        code: { tsx: "" },
        dependencies: ["framer-motion", "lucide-react", "gsap", "@react-three/fiber", "@react-three/drei"],
        props: [
            {
                name: "marbleColor1",
                type: "string",
                default: "#f5f5f5",
                description: "Primary marble color (light).",
            },
            {
                name: "marbleColor2",
                type: "string",
                default: "#d4d4d4",
                description: "Secondary marble color (veins).",
            },
            {
                name: "textureIntensity",
                type: "number",
                default: "1",
                description: "Intensity of marble texture (0-2).",
            },
            {
                name: "enableShimmer",
                type: "boolean",
                default: "true",
                description: "Enable luxury shimmer effects.",
            },
        ],
    },
    {
        id: "retro-80s",
        name: "Retro 80s",
        description: "Nostalgic 80s-inspired hero section with retro colors, neon effects, and vintage aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["retro", "80s", "neon", "vintage"],
        previewUrl: "/CoreLandingPages/HeroSections/Retro80s",
        code: { tsx: "" },
        dependencies: ["lucide-react", "gsap"],
        props: [
            {
                name: "neonColor1",
                type: "string",
                default: "#ff00ff",
                description: "First neon color (magenta).",
            },
            {
                name: "neonColor2",
                type: "string",
                default: "#00ffff",
                description: "Second neon color (cyan).",
            },
            {
                name: "glowIntensity",
                type: "number",
                default: "1",
                description: "Intensity of neon glow effects (0-2).",
            },
            {
                name: "enableScanlines",
                type: "boolean",
                default: "true",
                description: "Enable retro CRT scanline effects.",
            },
        ],
    },
    {
        id: "sketchy2",
        name: "Sketchy 2",
        description: "Hand-drawn sketchy hero section with organic lines and creative, artistic aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["sketchy", "hand-drawn", "organic", "artistic"],
        previewUrl: "/CoreLandingPages/HeroSections/Sketchy2",
        code: { tsx: "" },
        dependencies: ["lucide-react", "@react-three/fiber", "@react-three/drei", "three", "gsap"],
        props: [
            {
                name: "sketchColor",
                type: "string",
                default: "#1a1a1a",
                description: "Color for sketch lines.",
            },
            {
                name: "paperColor",
                type: "string",
                default: "#ffffff",
                description: "Background paper color.",
            },
            {
                name: "roughness",
                type: "number",
                default: "1",
                description: "Roughness of sketch lines (0.5-2).",
            },
            {
                name: "enableHandDrawn",
                type: "boolean",
                default: "true",
                description: "Enable hand-drawn sketch effects.",
            },
        ],
    },
    {
        id: "swiss-portfolio",
        name: "Swiss Portfolio",
        description: "Swiss design-inspired hero section with clean typography and minimalist aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["swiss", "portfolio", "typography", "minimal"],
        previewUrl: "/CoreLandingPages/HeroSections/SwissPortfolio",
        code: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#000000",
                description: "Primary text color (black).",
            },
            {
                name: "backgroundColor",
                type: "string",
                default: "#ffffff",
                description: "Clean white background.",
            },
            {
                name: "accentColor",
                type: "string",
                default: "#ef4444",
                description: "Minimal accent color for highlights.",
            },
            {
                name: "fontWeight",
                type: "string",
                default: "400",
                description: "Typography weight (300-700).",
            },
            {
                name: "spacing",
                type: "string",
                default: "minimal",
                description: "Spacing style: 'minimal', 'moderate', or 'generous'.",
            },
        ],
    },
];

