import { Component } from "../types";

export const lightboxComponentsMetadata: Component[] = [
    {
        id: "lightbox-hero",
        name: "Cinematic Hero",
        description: "Seamless layout transition lightbox with cinematic hero view.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "cinematic", "hero", "transition"],
        previewUrl: "/Media/LightBoxes/LightboxHero",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?q=80&w=2000&auto=format&fit=crop", description: "Main image source URL." },
            { name: "backgroundColor", type: "string", default: "#09090b", description: "Page background color." },
        ],
        whenToUse: "Excellent for high-end fashion campaigns and portfolios that want a meaningful 'Cinematic' aesthetic.",
        bestPractices: "Use high-resolution wide images. Dark backgrounds make the layout-morph transition most dramatic.",
        whyMatters: "Cinematic aesthetics communicate technical reliability and timeless craft. This Uilora template builds an interface that feels organized and professional.",
        faqs: [
            { question: "How does the expansion work?", answer: "Uses Framer Motion layout-id to seamlessly morph the thumbnail into the full-screen cinematic view." },
            { question: "Can I use my own image?", answer: "Yes — pass any image URL via the `image` prop." },
            { question: "Is it mobile responsive?", answer: "The lightbox uses 95vw × 90vh, scaling fluidly to any screen size." }
        ],
    },
    {
        id: "lightbox-glass",
        name: "Glassmorphism",
        description: "Blur and floating UI glassmorphism lightbox.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "glass", "blur", "floating"],
        previewUrl: "/Media/LightBoxes/LightboxGlass",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2700&auto=format&fit=crop", description: "Main image source URL." },
            { name: "backgroundColor", type: "string", default: "linear-gradient(to bottom right, #312e81, #581c87)", description: "Background color or gradient." },
        ],
        whenToUse: "Excellent for high-end digital agencies and portfolios that want a premium 'Glassmorphism' aesthetic.",
        bestPractices: "Use gradient backgrounds for maximum glass effect. Bold, colorful images work best.",
        whyMatters: "Glass-based aesthetics communicate digital excellence and sophistication. This Uilora template builds a curated and premium interface.",
        faqs: [
            { question: "Is the blur real?", answer: "Yes — uses CSS backdrop-filter blur combined with a purple radial glow for depth." },
            { question: "What's in the info bar?", answer: "A floating glass panel with title, subtitle, and like/download actions." },
            { question: "Is it mobile responsive?", answer: "The modal scales to max-w-5xl and the glass bar adapts its width fluidly." }
        ],
    },
    {
        id: "lightbox-reel",
        name: "Film Reel",
        description: "Film strip reel lightbox with gallery navigation.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "film", "reel", "gallery"],
        previewUrl: "/Media/LightBoxes/LightboxReel",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...10 Unsplash URLs]", description: "Array of image source URLs for the reel." },
            { name: "backgroundColor", type: "string", default: "#0c0a09", description: "Dark background color." },
        ],
        whenToUse: "Ideal for creative studios and portfolios that want an organic 'Film Reel' aesthetic.",
        bestPractices: "Provide at least 6 images. Use consistent aspect-ratio images for the cleanest thumbnail strip.",
        whyMatters: "Film reel animations create authenticity. This Uilora template adds a cinematic signature to your brand.",
        faqs: [
            { question: "How does navigation work?", answer: "Magazine-cover trigger shows 3 images. Inside, click reel thumbnails or use arrow keys." },
            { question: "Are there sprocket holes?", answer: "Yes — an SVG-rendered left-edge strip simulates film sprocket holes." },
            { question: "Is it mobile responsive?", answer: "The reel bar scrolls horizontally with touch support." }
        ],
    },
    {
        id: "lightbox-editorial",
        name: "Editorial Split",
        description: "Editorial split lightbox with image and article layout.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "editorial", "split", "article"],
        previewUrl: "/Media/LightBoxes/LightboxEditorial",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?q=80&w=2000&auto=format&fit=crop", description: "Editorial image source URL." },
            { name: "backgroundColor", type: "string", default: "#eaeaea", description: "Page background color." },
        ],
        whenToUse: "Ideal for editorial magazines and creative agencies. Use when the lightbox should double as a full editorial spread.",
        bestPractices: "Use high-contrast photography. The image transitions from grayscale to color on hover.",
        whyMatters: "Editorial layouts communicate digital excellence and attention to detail. This Uilora template builds a curated, premium interface.",
        faqs: [
            { question: "What's in the article panel?", answer: "Category label, serif title, three editorial paragraphs, and a photographer credit." },
            { question: "Can I customize the content?", answer: "The text is Uilora-branded defaults. Extend with additional props for custom content." },
            { question: "Is it mobile responsive?", answer: "Stacks vertically on mobile — image top, article below." }
        ],
    },
    {
        id: "lightbox-story",
        name: "Story Mode",
        description: "Multi-story vertical immersive lightbox with progress bars, tap navigation, and auto-advance.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "story", "vertical", "immersive", "social"],
        previewUrl: "/Media/LightBoxes/LightboxStory",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "stories", type: "Array<{image: string, username: string, timeAgo: string, caption: string}>", default: "[{username: 'uilora.studio', ...}]", description: "Array of story objects with image, username, timeAgo, and caption." },
            { name: "backgroundColor", type: "string", default: "linear-gradient(to top right, #ec4899, #f97316)", description: "Background gradient for the avatar row." },
        ],
        whenToUse: "Perfect for social-media-style brand presentations. Supports 1–N stories with tap zones, arrows, and auto-advance.",
        bestPractices: "Keep 3–6 stories. Use portrait-oriented images (9:16). Stories auto-advance every 5 seconds.",
        whyMatters: "Story-mode interfaces communicate immediacy and social authenticity. This Uilora template captures premium social storytelling.",
        faqs: [
            { question: "How does navigation work?", answer: "Tap left/right thirds to navigate, or use chevron arrows. Auto-advances after 5s." },
            { question: "What's the progress bar?", answer: "Each story has a 3px progress bar. Completed = full, current = live, future = empty." },
            { question: "Is it mobile responsive?", answer: "Uses min(100vw, 390px) × 9:16 — standard mobile story dimensions." }
        ],
    },
    {
        id: "lightbox-perspective",
        name: "3D Perspective",
        description: "3D tilt perspective drag card lightbox.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "3d", "perspective", "tilt"],
        previewUrl: "/Media/LightBoxes/LightboxPerspective",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?q=80&w=2000&auto=format&fit=crop", description: "Main image source URL." },
            { name: "backgroundColor", type: "string", default: "#cbd5e1", description: "Page background color." },
        ],
        whenToUse: "Excellent for high-end portfolios that want a physical, tactile 3D experience. Drag-to-tilt makes it memorable.",
        bestPractices: "Use portrait or square images for the best card proportions. High-contrast imagery maximizes the tilt effect.",
        whyMatters: "Perspective interactions communicate technical sophistication. This Uilora template creates a physical feeling in a digital interface.",
        faqs: [
            { question: "How does the tilt work?", answer: "Drag the card — useMotionValue maps x/y to rotateX/rotateY with perspective-1000px." },
            { question: "Does it snap back?", answer: "Yes — releasing drag snaps back to 0 via spring physics." },
            { question: "Is it mobile responsive?", answer: "Scales to max-w-[90vw] on mobile. Touch drag works the same as mouse." }
        ],
    },
    {
        id: "lightbox-grid",
        name: "Collection Grid",
        description: "Collection grid lightbox with circle expansion and full click-to-open image viewer.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "grid", "collection", "expansion"],
        previewUrl: "/Media/LightBoxes/LightboxGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[...10 Unsplash URLs]", description: "Array of image source URLs for the collection grid." },
            { name: "backgroundColor", type: "string", default: "#ffffff", description: "Page background color." },
        ],
        whenToUse: "Excellent for Uilora brand showcases and editorial archives. Circle-reveal opens the dark grid, clicking any image opens a full-screen viewer.",
        bestPractices: "Use portrait images (3:4) for cleanest grid cards. Provide 6–12 images for best density.",
        whyMatters: "The two-layer experience (grid reveal → image viewer) creates a premium interaction that keeps users engaged.",
        faqs: [
            { question: "How does clicking an image work?", answer: "Opens a full-screen viewer with spring animation, image counter, and left/right navigation." },
            { question: "Keyboard navigation?", answer: "ArrowLeft/Right navigate; Escape closes the viewer or the grid." },
            { question: "Is the grid responsive?", answer: "Adapts from 1 → 2 → 3 columns on sm/md/lg breakpoints." }
        ],
    },
    {
        id: "lightbox-minimal",
        name: "Minimal Focus",
        description: "Minimal polaroid-style spotlight focus lightbox.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "minimal", "spotlight", "focus"],
        previewUrl: "/Media/LightBoxes/LightboxMinimal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2700&auto=format&fit=crop", description: "Main image source URL." },
            { name: "backgroundColor", type: "string", default: "#F3F4F6", description: "Page background color." },
        ],
        whenToUse: "Ideal for analog photography portfolios and minimalist showcases with a tactile polaroid feel.",
        bestPractices: "Use warm-toned photography. The rotation and grayscale transitions are intentional — keep them.",
        whyMatters: "Minimal spotlight animations create digital authenticity. This Uilora template adds a handcrafted signature to your interface.",
        faqs: [
            { question: "What's the polaroid effect?", answer: "Trigger card has -1.5deg rotation, shadow, and italic label. Hover straightens over 500ms." },
            { question: "What's in the lightbox?", answer: "A warm framed modal with the image, Uilora Studio label, and info/download icons." },
            { question: "Is it mobile responsive?", answer: "Scales to max-w-3xl with max-h-[80vh]." }
        ],
    },
    {
        id: "lightbox-portal",
        name: "Uilora Portal",
        description: "Cosmic portal lightbox with concentric ring reveal, glassmorphism panel, and pulsing ambient rings.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "portal", "cosmic", "glass", "dark"],
        previewUrl: "/Media/LightBoxes/LightboxPortal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?q=80&w=2013&auto=format&fit=crop", description: "Main image source URL." },
            { name: "backgroundColor", type: "string", default: "#0a0014", description: "Deep cosmic background color." },
            { name: "accentColor", type: "string", default: "#00ffff", description: "Accent color for rings, glow, and glassmorphism panel." },
        ],
        whenToUse: "Perfect for futuristic brand showcases. The circular orb trigger and concentric ring entrance make the open event cinematic.",
        bestPractices: "Use dark backgrounds for the ring glow to read correctly. accentColor should match your brand signature.",
        whyMatters: "Portal-style entrances communicate exclusivity and technological mastery. This Uilora template makes every image reveal feel like an event.",
        faqs: [
            { question: "What triggers the portal?", answer: "A circular orb with radial glow and pulse ring animation. 'OPEN' text inside." },
            { question: "What are the concentric rings?", answer: "Three rings scale from 0 with staggered spring delays, creating a ripple effect." },
            { question: "Is it mobile responsive?", answer: "Image scales to viewport; info panel stacks below on narrow screens." }
        ],
    },
    {
        id: "lightbox-magazine",
        name: "Uilora Magazine",
        description: "Double-page spread editorial lightbox with spring slide-up, Georgia serif typography, and article layout.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "magazine", "editorial", "spring", "article"],
        previewUrl: "/Media/LightBoxes/LightboxMagazine",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=2006&auto=format&fit=crop", description: "Main image source URL for the left editorial panel." },
            { name: "backgroundColor", type: "string", default: "#f5f0e8", description: "Warm cream background color." },
        ],
        whenToUse: "Ideal for editorial publications and luxury brand storytelling with a full magazine spread.",
        bestPractices: "Use strong composition photography. Warm cream background pairs best with earthy, natural photography.",
        whyMatters: "Magazine-style presentation signals editorial authority. This Uilora template elevates imagery into a full narrative experience.",
        faqs: [
            { question: "What's in the right panel?", answer: "Uilora Issue No. 12, gold rule, serif title, three editorial paragraphs, photographer credit." },
            { question: "How does the entrance work?", answer: "Spring slide-up from y:60 with stiffness:340 — feels like turning a page." },
            { question: "Is it mobile responsive?", answer: "Stacks vertically on mobile: image top, article below." }
        ],
    },
    {
        id: "lightbox-auction",
        name: "Uilora Auction",
        description: "Gallery auction house lightbox with radial spotlight, gold accents, lot details, and PLACE BID CTA.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "auction", "gallery", "gold", "luxury"],
        previewUrl: "/Media/LightBoxes/LightboxAuction",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?q=80&w=1958&auto=format&fit=crop", description: "Artwork image source URL." },
            { name: "backgroundColor", type: "string", default: "#111111", description: "Deep gallery background color." },
        ],
        whenToUse: "Designed for digital auction houses and luxury art platforms. Single work with maximum gravitas.",
        bestPractices: "Use high-resolution artwork. Keep backgroundColor near #111111 for the spotlight effect.",
        whyMatters: "Auction-house aesthetics signal rarity and prestige. This Uilora template transforms any image into a collectible artifact.",
        faqs: [
            { question: "What's the trigger?", answer: "A dark lot-preview card with image, 'LOT 042' in gold, title, estimate, and 'PLACE BID →'." },
            { question: "What are the corner brackets?", answer: "Four gold L-shaped markers at image corners, referencing fine-art gallery presentation." },
            { question: "Is it mobile responsive?", answer: "Two-column layout stacks vertically on mobile." }
        ],
    },
    {
        id: "lightbox-cinescope",
        name: "Uilora Cinescope",
        description: "Cinematic 2.39:1 lightbox with letterbox bars, scan-line grain, HUD scrubber, and film metadata.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "cinematic", "letterbox", "film", "dark", "hud"],
        previewUrl: "/Media/LightBoxes/LightboxCinescope",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?q=80&w=2187&auto=format&fit=crop", description: "Main image (landscape works best for 2.39:1 ratio)." },
            { name: "backgroundColor", type: "string", default: "#000000", description: "Pure black background for maximum cinematic effect." },
        ],
        whenToUse: "Perfect for film production companies and cinematic brand campaigns.",
        bestPractices: "Use wide-format landscape images. Keep backgroundColor at #000000 for the letterbox illusion.",
        whyMatters: "Cinematic framing communicates quality and production value. This Uilora template makes every image feel like a film still.",
        faqs: [
            { question: "What's the trigger?", answer: "A 2.39:1 letterbox card with a hover '▶ PLAY' reveal — looks like a Blu-ray cover." },
            { question: "What's the scrubber?", answer: "A decorative 2px playhead animating 0%→60% over 8 seconds, simulating a film timeline." },
            { question: "Is it mobile responsive?", answer: "2.39:1 container scales proportionally to viewport width." }
        ],
    },
    {
        id: "lightbox-polaroid",
        name: "Uilora Polaroid",
        description: "Polaroid development lightbox with white-to-transparent reveal animation, warm tint, and tilted card.",
        category: "Media",
        installType: "cli",
        tags: ["lightbox", "polaroid", "film", "analog", "warm", "development"],
        previewUrl: "/Media/LightBoxes/LightboxPolaroid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=2006&auto=format&fit=crop", description: "Main image source URL." },
            { name: "backgroundColor", type: "string", default: "#f0ede6", description: "Warm off-white background." },
            { name: "caption", type: "string", default: "Uilora — Summer Archive, 2024", description: "Caption text below the polaroid image." },
        ],
        whenToUse: "Ideal for analog photography brands and nostalgic Uilora campaigns. The development animation makes the reveal itself the experience.",
        bestPractices: "Use warm-toned photography. Keep captions under 40 characters. The tape strip and -2deg rotation are intentional.",
        whyMatters: "Analog aesthetics trigger nostalgia and emotional connection. The dual-stage development animation makes users pause and engage.",
        faqs: [
            { question: "How does development work?", answer: "White overlay fades 1→0 over 1.2s (delay 0.4s), then warm amber tint also fades — two-stage polaroid development." },
            { question: "Does it replay?", answer: "Yes — AnimatePresence remounts overlays fresh on every open." },
            { question: "Is it mobile responsive?", answer: "Polaroid card uses w-80 and scales down on narrow screens." }
        ],
    },
];
