// Client-safe metadata export (no code, just metadata)
import { Component } from "../types";

// All agency portfolio components from the library
// Total: 21 components

export const agencyPortfolioComponentsMetadata: Component[] = [
    {
        id: "arcadeos",
        name: "Arcade OS",
        description: "Retro arcade-inspired portfolio with gaming aesthetics and pixel-perfect design.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["arcade", "retro", "gaming", "pixel"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/ARCADEOS",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion", "recharts"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#f43f5e",
                description: "Primary accent color for buttons and highlights (hex, rgb, or hsl).",
            },
            {
                name: "secondaryColor",
                type: "string",
                default: "#433c57",
                description: "Secondary color for borders and backgrounds.",
            },
            {
                name: "accentColor",
                type: "string",
                default: "#facc15",
                description: "Accent color for highlights and special elements.",
            },
            {
                name: "companyName",
                type: "string",
                default: "ARCADE.OS",
                description: "Your company or portfolio name displayed in the header.",
            },
            {
                name: "score",
                type: "string",
                default: "$84,230",
                description: "Revenue or score value displayed in the header.",
            },
            {
                name: "coins",
                type: "number",
                default: "420",
                description: "Coins or cash value displayed in the header.",
            },
            {
                name: "enableCRTEffect",
                type: "boolean",
                default: "true",
                description: "Enable CRT scanline effect for retro aesthetic.",
            },
            {
                name: "animationSpeed",
                type: "number",
                default: "1",
                description: "Animation speed multiplier (higher = faster).",
            },
        ],
    },
    {
        id: "aurora-command",
        name: "Aurora Command",
        description: "Futuristic portfolio with aurora effects and command center aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["aurora", "futuristic", "command", "glow"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/AuroraCommand",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#00f0ff",
                description: "Primary neon color for aurora effects and highlights.",
            },
            {
                name: "secondaryColor",
                type: "string",
                default: "#ff0055",
                description: "Secondary neon color for contrast and depth.",
            },
            {
                name: "glowIntensity",
                type: "number",
                default: "1",
                description: "Intensity of glow effects (0-2).",
            },
            {
                name: "animationSpeed",
                type: "number",
                default: "1",
                description: "Speed of aurora animations (0.5-2).",
            },
            {
                name: "darkMode",
                type: "boolean",
                default: "true",
                description: "Enable dark mode background.",
            },
        ],
    },
    {
        id: "black-box",
        name: "Black Box",
        description: "Minimalist dark portfolio with mysterious black box design elements.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["black", "minimal", "dark", "mysterious"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/BlackBox",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "accentColor",
                type: "string",
                default: "#ffffff",
                description: "Accent color for highlights and borders (typically white or light color).",
            },
            {
                name: "glowColor",
                type: "string",
                default: "#3b82f6",
                description: "Glow effect color for interactive elements.",
            },
            {
                name: "enableGlow",
                type: "boolean",
                default: "true",
                description: "Enable glow effects on hover and focus.",
            },
            {
                name: "borderWidth",
                type: "string",
                default: "2px",
                description: "Border width for black box elements.",
            },
        ],
    },
    {
        id: "claymorphism",
        name: "Claymorphism",
        description: "Soft clay-like portfolio with organic shapes and tactile design.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["clay", "soft", "organic", "tactile"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/Claymorphism",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion", "recharts"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#6c5ce7",
                description: "Primary brand color for buttons and accents.",
            },
            {
                name: "backgroundColor",
                type: "string",
                default: "#e0e5ec",
                description: "Background color (light mode neumorphic base).",
            },
            {
                name: "shadowIntensity",
                type: "number",
                default: "1",
                description: "Intensity of clay shadow effects (0.5-2).",
            },
            {
                name: "borderRadius",
                type: "string",
                default: "32px",
                description: "Border radius for clay cards.",
            },
            {
                name: "enableAnimations",
                type: "boolean",
                default: "true",
                description: "Enable smooth animations and transitions.",
            },
        ],
    },
    {
        id: "commerce-hud",
        name: "Commerce HUD",
        description: "E-commerce focused portfolio with HUD (Heads-Up Display) interface elements.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["commerce", "hud", "interface", "ecommerce"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/COMMERCE_HUD",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#00ff88",
                description: "Primary HUD color for data displays and highlights.",
            },
            {
                name: "backgroundColor",
                type: "string",
                default: "#0a0a0a",
                description: "Background color for the HUD interface.",
            },
            {
                name: "enableGrid",
                type: "boolean",
                default: "true",
                description: "Enable background grid pattern.",
            },
            {
                name: "animationSpeed",
                type: "number",
                default: "1",
                description: "Speed of HUD animations and transitions.",
            },
        ],
    },
    {
        id: "executive",
        name: "Executive",
        description: "Professional executive portfolio with sophisticated design and corporate aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["executive", "professional", "corporate", "sophisticated"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/EXECUTIVE",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#1a1a1a",
                description: "Primary brand color for headers and accents.",
            },
            {
                name: "accentColor",
                type: "string",
                default: "#d4af37",
                description: "Accent color for highlights and CTAs (gold/sophisticated tone).",
            },
            {
                name: "fontFamily",
                type: "string",
                default: "serif",
                description: "Font family (serif, sans-serif, or custom).",
            },
            {
                name: "enableAnimations",
                type: "boolean",
                default: "true",
                description: "Enable smooth scroll and fade animations.",
            },
        ],
    },
    {
        id: "luminous-horizon",
        name: "Luminous Horizon",
        description: "Ethereal portfolio with luminous effects and horizon-inspired design.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["luminous", "horizon", "ethereal", "glow"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/LuminousHorizon",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "gradientStart",
                type: "string",
                default: "#ff6b6b",
                description: "Start color of the horizon gradient.",
            },
            {
                name: "gradientEnd",
                type: "string",
                default: "#4ecdc4",
                description: "End color of the horizon gradient.",
            },
            {
                name: "glowIntensity",
                type: "number",
                default: "1",
                description: "Intensity of luminous glow effects (0-2).",
            },
            {
                name: "animationSpeed",
                type: "number",
                default: "1",
                description: "Speed of horizon animations.",
            },
        ],
    },
    {
        id: "maison-digital",
        name: "Maison Digital",
        description: "Elegant digital house portfolio with refined design and luxury aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["maison", "digital", "elegant", "luxury"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/MAISONDIGITAL",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#1a1a1a",
                description: "Primary elegant color (typically dark/black).",
            },
            {
                name: "accentColor",
                type: "string",
                default: "#c9a961",
                description: "Luxury accent color (gold/champagne tone).",
            },
            {
                name: "spacing",
                type: "string",
                default: "generous",
                description: "Spacing style: 'generous', 'compact', or 'minimal'.",
            },
            {
                name: "enableParallax",
                type: "boolean",
                default: "true",
                description: "Enable parallax scrolling effects.",
            },
        ],
    },
    {
        id: "neo-brutalism",
        name: "Neo Brutalism",
        description: "Bold neo-brutalist portfolio with high contrast and geometric shapes.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["neo-brutalism", "bold", "geometric", "high-contrast"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/NeoBrutalism",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#000000",
                description: "Primary bold color (typically black).",
            },
            {
                name: "accentColor",
                type: "string",
                default: "#ffff00",
                description: "High contrast accent color (typically bright yellow).",
            },
            {
                name: "shadowOffset",
                type: "string",
                default: "8px",
                description: "Offset for brutalist shadow effects.",
            },
            {
                name: "borderWidth",
                type: "string",
                default: "4px",
                description: "Border width for geometric elements.",
            },
        ],
    },
    {
        id: "obsidian-nebulas",
        name: "Obsidian & Nebulas",
        description: "Dark cosmic portfolio with obsidian textures and nebula effects.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["obsidian", "nebula", "cosmic", "dark"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/Obsidian&Nebulas",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "nebulaColor1",
                type: "string",
                default: "#8b5cf6",
                description: "First nebula color (purple).",
            },
            {
                name: "nebulaColor2",
                type: "string",
                default: "#ec4899",
                description: "Second nebula color (pink).",
            },
            {
                name: "nebulaColor3",
                type: "string",
                default: "#06b6d4",
                description: "Third nebula color (cyan).",
            },
            {
                name: "particleDensity",
                type: "number",
                default: "1",
                description: "Density of cosmic particles (0.5-2).",
            },
            {
                name: "animationSpeed",
                type: "number",
                default: "1",
                description: "Speed of nebula animations.",
            },
        ],
    },
    {
        id: "operatoros",
        name: "Operator OS",
        description: "Technical operator-themed portfolio with OS-inspired interface design.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["operator", "os", "technical", "interface"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/OPERATOROS",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "terminalColor",
                type: "string",
                default: "#00ff00",
                description: "Terminal text color (typically green).",
            },
            {
                name: "backgroundColor",
                type: "string",
                default: "#0a0a0a",
                description: "Terminal background color.",
            },
            {
                name: "enableTypingEffect",
                type: "boolean",
                default: "true",
                description: "Enable typing animation effects.",
            },
            {
                name: "fontFamily",
                type: "string",
                default: "monospace",
                description: "Font family (monospace for terminal feel).",
            },
        ],
    },
    {
        id: "orbital-command",
        name: "Orbital Command",
        description: "Space-themed portfolio with orbital mechanics and command center design.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["orbital", "space", "command", "mechanics"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/OrbitalCommand",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#00d4ff",
                description: "Primary space blue for UI elements.",
            },
            {
                name: "accentColor",
                type: "string",
                default: "#ff006e",
                description: "Accent color for highlights and alerts.",
            },
            {
                name: "orbitSpeed",
                type: "number",
                default: "1",
                description: "Speed of orbital animations (0.5-2).",
            },
            {
                name: "enable3D",
                type: "boolean",
                default: "true",
                description: "Enable 3D orbital effects.",
            },
        ],
    },
    {
        id: "prismos",
        name: "Prism OS",
        description: "Prismatic portfolio with light refraction effects and colorful design.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["prism", "light", "refraction", "colorful"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/PRISMOS",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "prismColor1",
                type: "string",
                default: "#ff0080",
                description: "First prism color (magenta).",
            },
            {
                name: "prismColor2",
                type: "string",
                default: "#00ff80",
                description: "Second prism color (green).",
            },
            {
                name: "prismColor3",
                type: "string",
                default: "#0080ff",
                description: "Third prism color (blue).",
            },
            {
                name: "refractionIntensity",
                type: "number",
                default: "1",
                description: "Intensity of light refraction effects (0-2).",
            },
            {
                name: "animationSpeed",
                type: "number",
                default: "1",
                description: "Speed of prism animations.",
            },
        ],
    },
    {
        id: "quantumanalytics",
        name: "Quantum Analytics",
        description: "Data-driven portfolio with quantum-inspired design and analytics aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["quantum", "analytics", "data", "scientific"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/QUANTUMANALYTICS",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#00f5ff",
                description: "Primary quantum blue for data visualizations.",
            },
            {
                name: "accentColor",
                type: "string",
                default: "#ff00ff",
                description: "Accent color for highlights and metrics.",
            },
            {
                name: "enableParticles",
                type: "boolean",
                default: "true",
                description: "Enable quantum particle effects.",
            },
            {
                name: "dataAnimationSpeed",
                type: "number",
                default: "1",
                description: "Speed of data visualization animations.",
            },
        ],
    },
    {
        id: "socialpulse",
        name: "Social Pulse",
        description: "Social media focused portfolio with pulse animations and network aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["social", "pulse", "network", "media"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/SOCIALPULSE",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#1da1f2",
                description: "Primary social media color (Twitter blue).",
            },
            {
                name: "pulseColor",
                type: "string",
                default: "#ff006e",
                description: "Color for pulse animations.",
            },
            {
                name: "pulseSpeed",
                type: "number",
                default: "1",
                description: "Speed of pulse animations (0.5-2).",
            },
            {
                name: "enableNetwork",
                type: "boolean",
                default: "true",
                description: "Enable network connection visualizations.",
            },
        ],
    },
    {
        id: "task-management",
        name: "Task Management",
        description: "Productivity-focused portfolio with task management interface elements.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["task", "management", "productivity", "interface"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/TaskManagement",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#3b82f6",
                description: "Primary color for task cards and buttons.",
            },
            {
                name: "completedColor",
                type: "string",
                default: "#10b981",
                description: "Color for completed tasks.",
            },
            {
                name: "pendingColor",
                type: "string",
                default: "#f59e0b",
                description: "Color for pending tasks.",
            },
            {
                name: "enableDragDrop",
                type: "boolean",
                default: "true",
                description: "Enable drag and drop functionality.",
            },
        ],
    },
    {
        id: "the-atelier",
        name: "The Atelier",
        description: "Artistic atelier portfolio with creative workspace aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["atelier", "artistic", "creative", "workspace"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/TheAtelier",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#8b4513",
                description: "Primary artistic color (brown/earth tone).",
            },
            {
                name: "accentColor",
                type: "string",
                default: "#ff6b6b",
                description: "Accent color for creative highlights.",
            },
            {
                name: "textureIntensity",
                type: "number",
                default: "1",
                description: "Intensity of artistic textures (0-2).",
            },
            {
                name: "enableSketch",
                type: "boolean",
                default: "true",
                description: "Enable sketch/hand-drawn effects.",
            },
        ],
    },
    {
        id: "the-mainframe",
        name: "The Mainframe",
        description: "Mainframe-inspired portfolio with retro computing aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["mainframe", "retro", "computing", "vintage"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/THEMAINFRAME",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "terminalColor",
                type: "string",
                default: "#00ff00",
                description: "Terminal green color for text.",
            },
            {
                name: "backgroundColor",
                type: "string",
                default: "#000000",
                description: "Mainframe background color (black).",
            },
            {
                name: "enableScanlines",
                type: "boolean",
                default: "true",
                description: "Enable CRT scanline effects.",
            },
            {
                name: "fontFamily",
                type: "string",
                default: "monospace",
                description: "Monospace font for retro computing feel.",
            },
        ],
    },
    {
        id: "the-oracle",
        name: "The Oracle",
        description: "Mystical oracle-themed portfolio with prophetic design elements.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["oracle", "mystical", "prophetic", "ancient"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/THEORACLE",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#6b46c1",
                description: "Mystical purple color for oracle elements.",
            },
            {
                name: "accentColor",
                type: "string",
                default: "#fbbf24",
                description: "Golden accent color for mystical highlights.",
            },
            {
                name: "enableMysticalEffects",
                type: "boolean",
                default: "true",
                description: "Enable mystical glow and particle effects.",
            },
            {
                name: "animationSpeed",
                type: "number",
                default: "1",
                description: "Speed of mystical animations.",
            },
        ],
    },
    {
        id: "the-sketchbook",
        name: "The Sketchbook",
        description: "Hand-drawn sketchbook portfolio with artistic and creative aesthetics.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["sketchbook", "hand-drawn", "artistic", "creative"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/THESKETCHBOOK",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "sketchColor",
                type: "string",
                default: "#2d3436",
                description: "Color for sketch lines and drawings.",
            },
            {
                name: "paperColor",
                type: "string",
                default: "#fefefe",
                description: "Background paper color (off-white/cream).",
            },
            {
                name: "sketchRoughness",
                type: "number",
                default: "1",
                description: "Roughness of sketch lines (0.5-2).",
            },
            {
                name: "enableHandDrawn",
                type: "boolean",
                default: "true",
                description: "Enable hand-drawn sketch effects.",
            },
        ],
    },
    {
        id: "xoxo",
        name: "XOXO",
        description: "Playful portfolio with XOXO design elements and fun interactions.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["xoxo", "playful", "fun", "interactive"],
        previewUrl: "/CoreLandingPages/AgencyPortfolio/XOXO",
        code: {
            tsx: "",
            jsx: "",
        },
        dependencies: ["next", "framer-motion"],
        props: [
            {
                name: "primaryColor",
                type: "string",
                default: "#ff006e",
                description: "Playful pink color for XOXO elements.",
            },
            {
                name: "secondaryColor",
                type: "string",
                default: "#8338ec",
                description: "Secondary playful color for variety.",
            },
            {
                name: "interactionIntensity",
                type: "number",
                default: "1",
                description: "Intensity of playful interactions (0.5-2).",
            },
            {
                name: "enableAnimations",
                type: "boolean",
                default: "true",
                description: "Enable fun animations and transitions.",
            },
        ],
    },
];

