import { Component } from "../types";

export const authComponentsMetadata: Component[] = [
    {
        id: "secure-reset",
        name: "Secure Reset",
        description: "Secure password reset form with real-time strength meter, password visibility toggle, and validation. Features animated strength indicators and confirmation field.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["core-landing-pages", "auth", "password", "reset", "security", "strength-meter", "validation"],
        previewUrl: "/CoreLandingPages/Auth/SecureReset",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "title", type: "string", default: '"Set New Password"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Ensure it\'s at least 8 chars long."', description: "Subtitle text displayed below the title." },
            { name: "onSubmit", type: "(data: { password: string; confirmPassword: string }) => Promise<void>", default: "undefined", description: "Callback function called when form is submitted with password data." },
            { name: "onStrengthChange", type: "(strength: number) => void", default: "undefined", description: "Callback function called when password strength changes (0-4 scale)." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "minLength", type: "number", default: "8", description: "Minimum password length requirement." },
            { name: "showStrengthMeter", type: "boolean", default: "true", description: "Whether to display the password strength meter." },
        ],
    },
    {
        id: "magic-link",
        name: "Magic Link",
        description: "Passwordless authentication with magic link email. Features 3D card flip animation on success, gradient shimmer effects, and animated success overlay.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["core-landing-pages", "auth", "magic-link", "passwordless", "email", "3d", "animation"],
        previewUrl: "/CoreLandingPages/Auth/MagicLink",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "title", type: "string", default: '"Magic Link"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Passwordless login."', description: "Subtitle text displayed below the title." },
            { name: "onSendLink", type: "(email: string) => Promise<void>", default: "undefined", description: "Callback function called when magic link is sent." },
            { name: "companyName", type: "string", default: '"Acme Inc."', description: "Company name displayed in the logo area." },
            { name: "showCompanyLogo", type: "boolean", default: "true", description: "Whether to display the company logo." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "successTitle", type: "string", default: '"Check your email"', description: "Title text displayed in the success overlay." },
            { name: "successMessage", type: "string", default: '"Click the link in the email we just sent you."', description: "Message text displayed in the success overlay." },
        ],
    },
    {
        id: "glass-forgot",
        name: "Glass Forgot",
        description: "Glassmorphism-style forgot password form with animated background blobs, gradient borders, and smooth state transitions. Features success state with checkmark animation.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["core-landing-pages", "auth", "forgot-password", "glassmorphism", "blur", "gradient"],
        previewUrl: "/CoreLandingPages/Auth/GlassForgot",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "title", type: "string", default: '"Reset Password"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Enter your email to receive a reset link."', description: "Subtitle text displayed below the title." },
            { name: "onSendLink", type: "(email: string) => Promise<void>", default: "undefined", description: "Callback function called when reset link is sent." },
            { name: "onBack", type: "() => void", default: "undefined", description: "Callback function called when back button is clicked." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "successMessage", type: "string", default: '"We\'ve sent a password reset link to your email address."', description: "Success message displayed after link is sent." },
        ],
    },
    {
        id: "otp-code",
        name: "OTP Code",
        description: "One-time password verification with auto-focus, keyboard navigation, and resend cooldown timer. Features animated input fields with glow effects and focus states.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["core-landing-pages", "auth", "otp", "verification", "code", "2fa", "security"],
        previewUrl: "/CoreLandingPages/Auth/OTPCode",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "title", type: "string", default: '"Verify Identity"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Enter the 4-digit code sent to your device."', description: "Subtitle text displayed below the title." },
            { name: "length", type: "number", default: "4", description: "Number of OTP code digits." },
            { name: "onComplete", type: "(code: string) => void", default: "undefined", description: "Callback function called when OTP code is complete." },
            { name: "onResend", type: "() => void", default: "undefined", description: "Callback function called when resend button is clicked." },
            { name: "resendCooldown", type: "number", default: "30", description: "Cooldown time in seconds before resend is allowed." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "autoFocus", type: "boolean", default: "true", description: "Whether to automatically focus the first input field." },
        ],
    },
    {
        id: "split-signup",
        name: "Split Signup",
        description: "Split-screen signup form with animated left panel showcase and gradient backgrounds. Features rotating border animations and hover effects on the showcase card.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["core-landing-pages", "auth", "signup", "split", "showcase", "gradient", "animation"],
        previewUrl: "/CoreLandingPages/Auth/SplitSignup",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "theme", type: "'dark' | 'light'", default: "undefined", description: "Color theme for the component." },
            { name: "accentColor", type: "string", default: "undefined", description: "Custom accent color for the component." },
            { name: "title", type: "string", default: '"Create Account"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Start your 14-day free trial."', description: "Subtitle text displayed below the title." },
            { name: "showLogo", type: "boolean", default: "undefined", description: "Whether to display the logo." },
            { name: "onSubmit", type: "(data: any) => Promise<void>", default: "undefined", description: "Callback function called when form is submitted." },
            { name: "onSuccess", type: "() => void", default: "undefined", description: "Callback function called on successful submission." },
            { name: "onError", type: "(err: string) => void", default: "undefined", description: "Callback function called on submission error." },
            { name: "loading", type: "boolean", default: "undefined", description: "Whether the form is in a loading state." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
            { name: "showLeftPanel", type: "boolean", default: "true", description: "Whether to display the left showcase panel." },
        ],
    },
    {
        id: "cinematic-login",
        name: "Cinematic Login",
        description: "Cinematic login form with ambient background gradients, animated glow effects, and social authentication options. Features smooth loading states and hover animations.",
        category: "Core Landing Pages",
        installType: "cli",
        tags: ["core-landing-pages", "auth", "login", "cinematic", "ambient", "social", "gradient"],
        previewUrl: "/CoreLandingPages/Auth/CinematicLogin",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion", "lucide-react"],
        props: [
            { name: "theme", type: "'dark' | 'light'", default: "undefined", description: "Color theme for the component." },
            { name: "accentColor", type: "string", default: "undefined", description: "Custom accent color for the component." },
            { name: "title", type: "string", default: '"Welcome Back"', description: "Title text displayed at the top of the form." },
            { name: "subtitle", type: "string", default: '"Enter your credentials to access the nexus."', description: "Subtitle text displayed below the title." },
            { name: "showLogo", type: "boolean", default: "undefined", description: "Whether to display the logo." },
            { name: "onSubmit", type: "(data: any) => Promise<void>", default: "undefined", description: "Callback function called when form is submitted." },
            { name: "onSuccess", type: "() => void", default: "undefined", description: "Callback function called on successful submission." },
            { name: "onError", type: "(err: string) => void", default: "undefined", description: "Callback function called on submission error." },
            { name: "loading", type: "boolean", default: "undefined", description: "Whether the form is in a loading state." },
            { name: "className", type: "string", default: "undefined", description: "Additional CSS classes for custom styling." },
        ],
    },
];

