import { Component } from "../components-data";

export const parallaxBackgroundComponentsMetadata: Component[] = [
    {
        id: "z-axis-tunnel",
        name: "Z-Axis Tunnel",
        description: "Infinity scroll effect where you scroll into the screen with 3D layers.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "3d", "tunnel", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/ZAxisTunnel",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "layerCount", type: "number", default: "5", description: "Number of layers" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "perspective", type: "string", default: "perspective-[100px]", description: "CSS perspective value" },
            { name: "containerHeight", type: "string", default: "h-[400vh]", description: "Height of the container" },
            { name: "text", type: "string", default: "WARP", description: "Text displayed" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-9xl", description: "Size of the text" },
            { name: "zStartOffset", type: "number", default: "-100", description: "Starting Z offset" },
            { name: "zEnd", type: "number", default: "100", description: "Ending Z position" },
            { name: "zStep", type: "number", default: "50", description: "Z step between layers" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for immersive landing pages, cinematic storytelling, and experimental modern web applications. Use this React component when you want to create a 'wormhole' effect that draws the user into a completely different visual reality as they scroll down.",
        bestPractices: "Follow React best practices by using high-resolution image assets for the layers to prevent blurring at deep Z-levels. Maintain scalable component architecture by adjusting the `zStep` to match the content density. Optimize for performance by limiting the number of heavy interactive elements within the deep tunnel layers.",
        whyMatters: "Z-axis parallax is a powerful tool for building depth in 2D environments. This production-ready component helpsคุณ implement a sophisticated 'into the screen' scroll effect that adds incredible semantic authority and visual polish to your real-world application architecture.",
        faqs: [
            { question: "How many layers are recommended?", answer: "A layer count of 5 to 7 usually provides a great sense of depth without overwhelming the browser's rendering engine." },
            { question: "Can I use different images for each layer?", answer: "Yes, you can pass an array of unique image URLs to the `images` prop to create a more varied and complex tunnel environment." },
            { question: "Is the text always centered?", answer: "The default styling centers the text in the focal point, but it can be repositioned using the `perspective` and `className` props." }
        ],
    },
    {
        id: "broken-shard-gallery",
        name: "Broken Shard Gallery",
        description: "Images explode outward from center into a chaotic gallery layout.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "explosion", "gallery", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/BrokenShardGallery",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "positions", type: "Array<{x: number, y: number, r: number}>", default: "[]", description: "Array of position configurations" },
            { name: "backgroundColor", type: "string", default: "bg-neutral-900", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "cardWidth", type: "string", default: "w-64", description: "Width of each card" },
            { name: "cardHeight", type: "string", default: "h-80", description: "Height of each card" },
            { name: "text", type: "string", default: "Disintegrate", description: "Text displayed" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-6xl", description: "Size of the text" },
            { name: "textFadeRange", type: "[number, number]", default: "[0, 0.2]", description: "Text fade progress range" },
            { name: "textScaleRange", type: "[number, number]", default: "[1, 3]", description: "Text scale range" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for fashion editorials, creative agencies, and modern web applications that want a 'chaotic yet organized' layout. Use this React component to create a high-impact gallery that explodes or implodes based on the user's scroll progress.",
        bestPractices: "Maintain consistent spacing within your design system by carefully defining the `positions` prop to avoid overlapping text. Follow React best practices by using high-quality images that can withstand scaling. Optimize for performance in large-scale applications by keeping the shard count under 15.",
        whyMatters: "Explosive layouts break the grid in a way that feels intentional and premium. This customizable UI component gives you a robust way to implement complex scatter physics, helpingคุณ build a real-world application architecture that feels dynamic and avant-garde.",
        faqs: [
            { question: "Can the shards move in any direction?", answer: "Yes, the `positions` prop allows you to define X, Y, and rotation offsets for each image, giving you total control over the direction of the explosion." },
            { question: "Does it support lazy loading?", answer: "Absolutely. The component is designed to work seamlessly with standard Next.js Image components or custom lazy loaders for the shards." },
            { question: "Is the text readable on all screens?", answer: "The text scaling is tied to scroll progress, ensuring it remains legible even during the transition between the gallery states." }
        ],
    },
    {
        id: "skew-scroller",
        name: "Skew Scroller",
        description: "Velocity-based skew effect that deforms the layout based on scroll speed.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "skew", "velocity", "grid"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/SkewScroller",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "itemCount", type: "number", default: "24", description: "Number of items in the grid" },
            { name: "backgroundColor", type: "string", default: "bg-[#e1e1e1]", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[400vh]", description: "Height of the container" },
            { name: "noiseUrl", type: "string", default: "https://grainy-gradients.vercel.app/noise.svg", description: "URL of noise texture" },
            { name: "noiseOpacity", type: "number", default: "0.2", description: "Opacity of noise overlay" },
            { name: "rotation", type: "number", default: "-15", description: "Rotation angle in degrees" },
            { name: "scale", type: "number", default: "1.5", description: "Scale factor" },
            { name: "scrollRange", type: "[number, number]", default: "[0, 2000]", description: "Scroll range" },
            { name: "xRange", type: "[number, number]", default: "[0, -500]", description: "X position range" },
            { name: "yRange", type: "[number, number]", default: "[0, -1000]", description: "Y position range" },
            { name: "gridCols", type: "number", default: "4", description: "Number of grid columns" },
            { name: "aspectRatio", type: "string", default: "aspect-[3/4]", description: "Aspect ratio of items" },
            { name: "text", type: "string", default: "KINETIC\\nGRID", description: "Text displayed (use \\n for newlines)" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for tech-heavy SaaS landing pages, gaming hubs, and modern web applications with a high-energy brand identity. Use this React component when you want the layout itself to feel 'heavy' or 'elastic' as the user scrolls rapidly through the content.",
        bestPractices: "Optimize for performance by ensuring the `gridCols` and `itemCount` are balanced for the target device's viewport. Follow React best practices by providing a noise texture that is small in file size. Maintain scalable component architecture by using responsive `aspectRatio` classes to handle different screen sizes.",
        whyMatters: "Velocity-based interactions are a hallmark of high-performance modern UI design. This production-ready component helpsคุณ implement physics-based skewing that makes the scrolling experience feel more visceral and expensive.",
        faqs: [
            { question: "Does the skew affect readability?", answer: "The skew is tied to scroll velocity, so it only deforms significantly when the user is moving quickly. It returns to neutral when the scrolling stops, ensuring readability." },
            { question: "Can I change the skew direction?", answer: "The current implementation skews based on vertical scroll speed, but the axis and intensity are fully customizable via props." },
            { question: "Is it compatible with all browsers?", answer: "Yes, it uses hardware-accelerated CSS transforms via Framer Motion, which are supported by all modern browsers." }
        ],
    },
    {
        id: "pinwheel",
        name: "Pinwheel",
        description: "Circular rotating gallery with radial image arrangement.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "circular", "rotate", "gallery"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/Pinwheel",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "bladeCount", type: "number", default: "8", description: "Number of blades in the pinwheel" },
            { name: "backgroundColor", type: "string", default: "bg-slate-950", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "wheelSize", type: "string", default: "w-[150vh] h-[150vh]", description: "Size of the pinwheel" },
            { name: "bladeWidth", type: "string", default: "w-80", description: "Width of each blade" },
            { name: "bladeHeight", type: "string", default: "h-[50vh]", description: "Height of each blade" },
            { name: "bladeBgColor", type: "string", default: "bg-red-500/20", description: "Background color of blades" },
            { name: "centerSize", type: "string", default: "w-64 h-64", description: "Size of the center circle" },
            { name: "centerBgColor", type: "string", default: "bg-slate-950", description: "Background color of center" },
            { name: "centerBorderColor", type: "string", default: "border-white/20", description: "Border color of center" },
            { name: "centerText", type: "string", default: "ROTATE_Y", description: "Text in the center" },
            { name: "centerTextColor", type: "string", default: "text-white", description: "Color of center text" },
            { name: "centerTextSize", type: "string", default: "text-xl", description: "Size of center text" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for feature showcases, circular brand narratives, and creative portfolios. Use this React component when you want to present images in a rotating, sunburst-style layout that provides a unique alternative to standard linear galleries.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the `wheelSize` doesn't overflow the parent container on smaller screens. Follow React best practices by utilizing the `bladeCount` prop to create a balanced visual rhythm. Optimize for performance by using simple gradients or solid colors for the `bladeBgColor`.",
        whyMatters: "Radial UI patterns are a sophisticated way to manage content density. This reusable React component provides a hardware-accelerated rotating gallery that enhances your real-world application architecture with an engaging, pinwheel-style interaction.",
        faqs: [
            { question: "Does the wheel rotate automatically?", answer: "The rotation is tied to the scroll position by default, but an auto-rotate feature can be easily implemented using a simple interval state." },
            { question: "Can I click on the individual blades?", answer: "Yes, each blade is a standard React container that can host links, buttons, or other interactive elements." },
            { question: "Is it mobile responsive?", answer: "Yes, the `wheelSize` and `bladeWidth` can be passed as responsive units to ensure the pinwheel fits comfortably on any screen." }
        ],
    },
    {
        id: "masked-typography",
        name: "Masked Typography",
        description: "Giant text that clips background images and scales as you scroll through.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "typography", "mask", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/MaskedTypography",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "backgroundColor", type: "string", default: "bg-white", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "gridCols", type: "number", default: "3", description: "Number of grid columns" },
            { name: "gridRows", type: "number", default: "3", description: "Number of grid rows" },
            { name: "text", type: "string", default: "VISION", description: "Text displayed" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-[20vw]", description: "Size of the text" },
            { name: "overlayColor", type: "string", default: "bg-blue-900/40", description: "Color of overlay" },
            { name: "overlayOpacity", type: "number", default: "0.4", description: "Opacity of overlay" },
            { name: "scaleRange", type: "[number, number]", default: "[1, 50]", description: "Scale range" },
            { name: "scaleProgressRange", type: "[number, number]", default: "[0, 0.8]", description: "Scale progress range" },
            { name: "opacityRange", type: "[number, number]", default: "[1, 0]", description: "Opacity range" },
            { name: "opacityProgressRange", type: "[number, number]", default: "[0.7, 0.8]", description: "Opacity progress range" },
            { name: "bgYRange", type: "[number, number]", default: "[0, 200]", description: "Background Y position range" },
            { name: "transitionText", type: "string", default: "Transition Complete", description: "Transition text displayed" },
            { name: "transitionTextColor", type: "string", default: "text-white", description: "Color of transition text" },
            { name: "transitionTextSize", type: "string", default: "text-2xl", description: "Size of transition text" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for high-end fashion brands, cinematic landing pages, and modern web applications that want to emphasize a single core concept or 'vision'. Use this React component when you want to reveal a complex background grid through the lens of a massive, scaling typographic element.",
        bestPractices: "Follow React best practices by providing high-contrast overlay colors to ensure the text remains the focal point throughout the zoom. Maintain scalable component architecture by adjusting the `scaleRange` to match the viewport dimensions. Optimize for performance by keeping the background grid resolution reasonable as it scales.",
        whyMatters: "Masked typography is a sophisticated technique that blends message and visual content perfectly. This production-ready component helpsคุณ implement a high-impact zoom-through reveal that adds incredible semantic authority and visual depth to your real-world application architecture.",
        faqs: [
            { question: "How does the 'zoom through' work?", answer: "The component scales the text mask as you scroll, eventually becoming so large that the user scrolls 'through' a letter to reveal the content underneath." },
            { question: "Can I use any font?", answer: "Yes, but bold, heavy-weight fonts work best as they provide more 'window' area for the background images to shine through." },
            { question: "Is the background grid customizable?", answer: "Absolutely. You can define the `gridCols` and `gridRows` to create anything from a single large image to a complex mosaic of background layers." }
        ],
    },
    {
        id: "parallax-slits",
        name: "Parallax Slits",
        description: "Vertical columns that move in alternating directions creating a shredder effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "columns", "vertical", "fragmentation"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/ParallaxSlits",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "columns", type: "number", default: "12", description: "Number of columns" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[250vh]", description: "Height of the container" },
            { name: "scrollDistance", type: "number", default: "400", description: "Scroll distance for parallax" },
            { name: "borderColor", type: "string", default: "border-black/50", description: "Border color between columns" },
            { name: "section1Bg", type: "string", default: "bg-zinc-800", description: "Background color of first section" },
            { name: "section2Bg", type: "string", default: "bg-zinc-900", description: "Background color of second section" },
            { name: "section2BorderColor", type: "string", default: "border-red-500", description: "Border color of second section" },
            { name: "imageOpacity", type: "number", default: "0.6", description: "Opacity of images" },
            { name: "text", type: "string", default: "Fragmentation", description: "Text displayed" },
            { name: "textColor", type: "string", default: "text-4xl", description: "Color class of the text" },
            { name: "textSize", type: "string", default: "text-4xl", description: "Size of the text" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for tech-focused portfolios, digital product launches, and Next.js applications that want a sharp, fragmented aesthetic. Use this React component to create a 'shredder' effect where your images are sliced into vertical columns that move independently.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the `columns` count is appropriate for the layout width. Follow React best practices by using high-contrast borders between the slits to emphasize the fragmentation. Optimize for performance by keeping the `imageOpacity` high enough to avoid complex sub-pixel blending.",
        whyMatters: "Slit-scan and fragmentation effects add a layer of technical precision to digital interfaces. This customizable UI component gives you a robust way to implement complex column-based parallax, helpingคุณ build a real-world application architecture that feels sharp and futuristic.",
        faqs: [
            { question: "Do the columns move in different directions?", answer: "Yes, the component automatically alternates the parallax direction for each column, creating a beautiful 'shredder' or 'sliding' motion as you scroll." },
            { question: "Can I put text over the slits?", answer: "The component includes a central text container that remains pinned while the background slits move, providing a clear focal point." },
            { question: "How many columns should I use?", answer: "A count of 8 to 16 columns usually provides the most balanced look for the fragmentation effect." }
        ],
    },
    {
        id: "horizontal-drag",
        name: "Horizontal Drag",
        description: "Vertical scroll drives a massive horizontal film strip with parallax cards.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "horizontal", "scroll", "film-strip"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/HorizontalDrag",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "itemCount", type: "number", default: "10", description: "Number of items in the strip" },
            { name: "backgroundColor", type: "string", default: "bg-[#1a1a1a]", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[500vh]", description: "Height of the container" },
            { name: "gap", type: "string", default: "gap-20", description: "Gap between items" },
            { name: "padding", type: "string", default: "px-20", description: "Horizontal padding" },
            { name: "itemWidth", type: "string", default: "w-[60vw]", description: "Width of each item" },
            { name: "itemHeight", type: "string", default: "h-[70vh]", description: "Height of each item" },
            { name: "imageScale", type: "number", default: "1.2", description: "Scale of images" },
            { name: "imageXRange", type: "[number, number]", default: "[-50, 50]", description: "Image X position range" },
            { name: "xRange", type: "[string, string]", default: "[\"0%\", \"-80%\"]", description: "Container X position range" },
            { name: "numberColor", type: "string", default: "text-transparent", description: "Color of number labels" },
            { name: "numberSize", type: "string", default: "text-6xl", description: "Size of number labels" },
            { name: "numberStrokeWidth", type: "string", default: "2px", description: "Stroke width of numbers" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for product galleries, team showcases, and modern web applications that want to combine vertical scrolling with large-scale horizontal movement. This production-ready React UI component is perfect for creating a 'film strip' feel that unveils content sideways as you scroll down.",
        bestPractices: "Optimize for performance in large-scale applications by lazy-loading the images within the horizontal strip. To follow React best practices, use the `gap` prop to ensure the parallax cards have enough breathing room. Maintain scalable component architecture by using responsive `itemWidth` and `itemHeight` values.",
        whyMatters: "Horizontal scroll within a vertical page is a powerful UX pattern for breaking the linear flow. This reusable React component provides a hardware-accelerated film-strip interaction that adds visual variety and depth to your real-world application architecture.",
        faqs: [
            { question: "Is the horizontal movement smooth?", answer: "Yes, it uses Framer Motion's `useScroll` and `useTransform` to map the vertical scroll progress to horizontal translation with sub-pixel precision." },
            { question: "Can I add numbers to the items?", answer: "The component has built-in support for large background numbers that track with each parallax card, which is great for numbered lists or steps." },
            { question: "Does it work with different card sizes?", answer: "The cards are uniform within the strip for a clean 'film' aesthetic, but the width and height can be easily customized via props." }
        ],
    },
    {
        id: "kaleidoscope-grid",
        name: "Kaleidoscope Grid",
        description: "Four quadrants moving in different directions creating a kaleidoscope effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "quadrants", "multi-directional", "grid"],
        previewUrl: "/Animations&Motion/ParallaxBackgrounds/KaleidoscopeGrid",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs (minimum 4)" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "gridGap", type: "string", default: "gap-4", description: "Gap between grid items" },
            { name: "gridPadding", type: "string", default: "p-4", description: "Padding of the grid" },
            { name: "borderRadius", type: "string", default: "rounded-3xl", description: "Border radius of grid items" },
            { name: "borderWidth", type: "string", default: "border-2", description: "Border width of grid items" },
            { name: "borderColor", type: "string", default: "border-white/10", description: "Border color of grid items" },
            { name: "imageScale", type: "string", default: "w-[150%] h-[150%]", description: "Scale of images" },
            { name: "imageTransform", type: "string", default: "translate(-20%, -20%)", description: "Transform of images" },
            { name: "imageOpacity", type: "number", default: "0.8", description: "Opacity of images" },
            { name: "parallaxDistance", type: "number", default: "300", description: "Parallax movement distance" },
            { name: "cornerLabels", type: "string[]", default: "[\"NORTH-WEST\", \"\", \"\", \"SOUTH-EAST\"]", description: "Labels for corners" },
            { name: "cornerLabelColor", type: "string", default: "text-white", description: "Color of corner labels" },
            { name: "cornerLabelSize", type: "string", default: "text-4xl", description: "Size of corner labels" },
            { name: "centerCircleSize", type: "string", default: "w-20 h-20", description: "Size of center circle" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for artistic portfolios, experimental startup landing pages, and cinematic web experiences that want a multi-dimensional feel. Use this React component to create a kaleidoscope effect where different quadrants of the screen move in opposing directions as you scroll.",
        bestPractices: "Maintain consistent spacing within your design system by using symmetrical `gridGap` and `gridPadding` values. Follow React best practices by using 4 distinct, high-quality images to maximize the kaleidoscope effect. Optimize for performance by keeping the `parallaxDistance` within a reasonable range (200-500px).",
        whyMatters: "Multi-directional parallax is the pinnacle of immersive scroll interactions. This animated UI component helpsคุณ build an interface that feels expansive and alive, adding a layer of semantic authority and visual surprise to your real-world application architecture.",
        faqs: [
            { question: "How does the kaleidoscope effect work?", answer: "The screen is divided into four quadrants, each moving in a different direction (diagonal, vertical, horizontal) relative to the scroll progress." },
            { question: "Can I label the corners?", answer: "Yes, the component supports custom `cornerLabels` which are useful for navigation or adding descriptive text to each quadrant." },
            { question: "Does it require exactly 4 images?", answer: "The effect is best with 4 images, but it can work with more; extra images will be distributed among the quadrants." }
        ],
    },
];

