import { getCode } from "../getCode";
import { Component } from "../components-data";

export const parallaxScrollComponents: Component[] = [
    {
        id: "broken-shard-gallery",
        name: "Broken Shard Gallery",
        description: "Images explode outward from center into a chaotic gallery layout as you scroll.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "explosion", "gallery", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxScroll/BrokenShardGallery",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxScroll/tsx/BrokenShardGallery.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxScroll/jsx/BrokenShardGallery.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxScroll/BrokenShardGallery/page.tsx"),
        },
        dependencies: ["framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs for the exploding shards" },
            { name: "text", type: "string", default: '"Disintegrate"', description: "Hero text displayed before the shatter animation begins" },
            { name: "backgroundColor", type: "string", default: '"bg-neutral-900"', description: "Tailwind background color class for the scroll container" },
        ],
        whenToUse: "Perfect for high-energy product reveals, editorial intros, and landing pages where you want a dramatic entrance that rewards the user for scrolling.",
        bestPractices: "Works best with 5–8 portrait images. Keep the hero text short (1–2 words) — it zooms and fades as you scroll so brevity reads better. Dark backgrounds let the image shards pop.",
        whyMatters: "A scroll-driven shard explosion turns a static gallery into an event. It immediately communicates craft and energy — the kind of motion that makes users stop and share a screenshot.",
        faqs: [
            { question: "Can I customize the shard positions?", answer: "Yes — pass a `positions` prop as an array of `{x, y, r}` objects to define exactly where each card flies on scroll." },
            { question: "How many images works best?", answer: "5–8 images gives the densest shard field. Fewer (3–4) creates a more spacious, intentional layout." },
            { question: "Is the explosion speed adjustable?", answer: "The motion maps to scroll progress, so the speed is entirely user-controlled. Adjust `containerHeight` (default h-[300vh]) to make the sequence longer or snappier." },
        ],
    },
    {
        id: "velocity-smear",
        name: "Velocity Smear",
        description: "Gallery that skews and stretches in real-time based on scroll velocity — the faster you scroll, the more the images smear.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "velocity", "skew", "gallery", "framer-motion"],
        previewUrl: "/Animations&Motion/ParallaxScroll/VelocitySmear",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxScroll/tsx/VelocitySmear.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxScroll/jsx/VelocitySmear.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxScroll/VelocitySmear/page.tsx"),
        },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#f59e0b"', description: "Accent color for label badges and section header" },
            { name: "items", type: "Array<{ image: string; label: string }>", default: "DEFAULT_ITEMS", description: "Gallery items — each needs an image URL and a label string" },
            { name: "intensity", type: "number", default: "22", description: "Maximum skew angle in degrees at peak scroll velocity" },
        ],
        whenToUse: "Perfect for photography portfolios, fashion editorials, and any gallery that should feel kinetic and alive. The velocity response makes scrolling feel physical.",
        bestPractices: "Keep intensity between 15–28 degrees. Higher values are dramatic but can feel nauseating on desktop. Works best with portrait-ratio images in a 2–3 column grid.",
        whyMatters: "Velocity-driven transforms are rare in production UI — most devs only reach for scroll position. Using `useVelocity` signals deep motion craft and creates a sensation no static gallery can match.",
        faqs: [
            { question: "How is velocity measured?", answer: "Framer Motion's `useVelocity` tracks pixels-per-second of `scrollY`. Fast flick = high velocity = maximum skew." },
            { question: "Will it snap back when I stop scrolling?", answer: "Yes — the `useSpring` wrapper (stiffness: 280, damping: 45) returns everything to 0 with a quick, snappy spring." },
            { question: "Can I add more images?", answer: "Yes — pass any number of items. The grid auto-wraps into the configured columns." },
        ],
    },
    {
        id: "curtain-split",
        name: "Curtain Split",
        description: "Two image panels split apart like stage curtains on scroll, revealing editorial text content hidden beneath.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "curtain", "reveal", "scroll", "split"],
        previewUrl: "/Animations&Motion/ParallaxScroll/CurtainSplit",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxScroll/tsx/CurtainSplit.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxScroll/jsx/CurtainSplit.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxScroll/CurtainSplit/page.tsx"),
        },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#e879f9"', description: "Accent color for the seam line, eyebrow text, and divider lines" },
            { name: "leftImage", type: "string", default: '"unsplash URL"', description: "Image URL for the left curtain panel" },
            { name: "rightImage", type: "string", default: '"unsplash URL"', description: "Image URL for the right curtain panel" },
        ],
        whenToUse: "Ideal for hero sections, dramatic product reveals, and brand intro sequences. The curtain metaphor immediately creates anticipation before the content is visible.",
        bestPractices: "Use high-contrast images against a dark background for maximum drama. The reveal content works best as short, bold typography — not paragraphs.",
        whyMatters: "The curtain reveal is one of cinema's most powerful tools. Bringing it to web scroll creates a theatrical moment that makes users feel like they're witnessing a premiere.",
        faqs: [
            { question: "Can I customize the reveal content?", answer: "Yes — edit the inner JSX inside the 'Revealed content' section. The motion is on the curtain wrapper, not the content." },
            { question: "Can both panels show the same image?", answer: "Yes — pass the same URL to both leftImage and rightImage for a symmetric split-screen effect." },
            { question: "How do I adjust the split timing?", answer: "Change the second value in `[0, 0.75]` on leftX/rightX transforms — lower = faster split." },
        ],
    },
    {
        id: "image-ribbons",
        name: "Image Ribbons",
        description: "Three horizontal image strips drifting in alternating directions as you scroll — rows counter-move to create depth and motion.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "ribbons", "gallery", "horizontal", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxScroll/ImageRibbons",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxScroll/tsx/ImageRibbons.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxScroll/jsx/ImageRibbons.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxScroll/ImageRibbons/page.tsx"),
        },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#10b981"', description: "Accent color for the eyebrow label and section header line" },
            { name: "rows", type: "string[][]", default: "DEFAULT_ROWS", description: "Array of 3 image URL arrays — one per ribbon row" },
        ],
        whenToUse: "Ideal for portfolio showcases, editorial headers, and agency-style galleries. The counter-drifting rows communicate motion even before the user scrolls.",
        bestPractices: "Provide 8+ images per row so there's no gap during drift. Rows 1 and 3 drift left, row 2 drifts right. Works best with consistently-colored images (dark-filtered or monochromatic).",
        whyMatters: "Opposing directional scroll on adjacent rows creates the illusion of depth without a single line of 3D CSS. It's a composition trick borrowed from cinema — and it works.",
        faqs: [
            { question: "Why do rows move in opposite directions?", answer: "Rows 0 and 2 translate left as you scroll down, row 1 translates right. The opposition creates a visual tension that reads as depth." },
            { question: "Can I have more or fewer rows?", answer: "The component renders rows.slice(0, 3), so you always get exactly 3 rows. Each row's images come from the corresponding sub-array." },
            { question: "How much do the ribbons move?", answer: "Each row drifts 320px across the full scroll range of the container. Adjust the useTransform range to change the speed." },
        ],
    },
    {
        id: "scroll-zoom",
        name: "Scroll Zoom",
        description: "A hero image that starts framed and small, then zooms to fill the entire viewport as you scroll — cinematic reveal in pure CSS and scroll.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "zoom", "hero", "cinematic", "reveal", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxScroll/ScrollZoom",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxScroll/tsx/ScrollZoom.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxScroll/jsx/ScrollZoom.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxScroll/ScrollZoom/page.tsx"),
        },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#f97316"', description: "Accent color for the eyebrow label and bottom divider line" },
            { name: "image", type: "string", default: '"unsplash URL"', description: "Full-bleed hero image URL — shown at 55% scale initially, expands to fill the viewport" },
            { name: "headline", type: "string", default: '"Every pixel, intentional."', description: "Headline text that overlays the image and fades as the zoom progresses" },
        ],
        whenToUse: "Perfect for brand hero sections, film or photography portfolios, and any product intro that deserves a cinematic entrance. The zoom makes the first scroll feel like a theatre curtain rising.",
        bestPractices: "Use a single high-resolution landscape image. Keep the headline short (4–6 words) — it fades by 35% scroll progress, so brevity reads better. Pair with a dark-tinted image for text legibility.",
        whyMatters: "Apple, Arc, and Linear all use scroll-driven zoom for hero reveals — it's the highest-impact single motion you can add to a landing page. Most devs reach for fade-ins; zoom communicates ambition.",
        faqs: [
            { question: "How does the zoom work?", answer: "The image container is scaled from 0.55 to 1.0 via `useTransform(scrollYProgress, [0, 0.7], [0.55, 1])`. The outer sticky div clips it." },
            { question: "Can I adjust the zoom start/end size?", answer: "Change the output range of the `scale` transform. 0.4→1 is very dramatic, 0.7→1 is subtle." },
            { question: "What appears after the zoom completes?", answer: "A small Uilora byline fades in at the bottom after 70% scroll progress, marking the reveal complete." },
        ],
    },
    {
        id: "scroll-morph",
        name: "Scroll Morph",
        description: "Display typography that morphs letter-spacing from wide-spaced to compressed as you scroll — an editorial typographic journey in one word.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["parallax", "typography", "morph", "letter-spacing", "editorial", "scroll"],
        previewUrl: "/Animations&Motion/ParallaxScroll/ScrollMorph",
        code: {
            tsx: getCode("src/components/Animations&Motion/ParallaxScroll/tsx/ScrollMorph.tsx"),
            jsx: getCode("src/components/Animations&Motion/ParallaxScroll/jsx/ScrollMorph.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ParallaxScroll/ScrollMorph/page.tsx"),
        },
        dependencies: ["framer-motion"],
        props: [
            { name: "accentColor", type: "string", default: '"#a855f7"', description: "Accent color for the eyebrow label, divider line, and tag pills" },
            { name: "word", type: "string", default: '"UILORA"', description: "The display word to morph — works best with 4–8 uppercase characters" },
            { name: "subtext", type: "string", default: '"The component library for premium interfaces"', description: "Supporting text that fades in once the letters converge" },
        ],
        whenToUse: "Use as a brand statement hero, section divider, or loading screen. One word at enormous scale scrolling through three typographic states creates a memorable brand moment.",
        bestPractices: "Short words (4–7 chars) work best — they fill the viewport cleanly. Use all-caps for maximum impact. The subtext should be one short sentence that lands the brand promise.",
        whyMatters: "Letter-spacing morphed by scroll progress is rarely seen in production — it requires understanding both CSS and MotionValues deeply. When done right, it makes the brand feel like it has physical weight.",
        faqs: [
            { question: "Can I use a multi-word phrase?", answer: "Yes — but use a short phrase (2–3 words max). Longer text will overflow on mobile." },
            { question: "How do the three phases work?", answer: "Phase 1 (0→0.32): letters expand to 0.7em spacing. Phase 2 (0.32→0.66): converge to natural. Phase 3 (0.66→1): compress slightly to -0.04em." },
            { question: "Can I add a background image?", answer: "Yes — add an absolutely-positioned img or video inside the sticky container, behind z-index 10." },
        ],
    },
];
