import { getCode } from "../getCode";
import { Component } from "../components-data";

export const scrollRevealComponents: Component[] = [
    {
        id: "liquid-displacement",
        name: "Liquid Displacement",
        description: "SVG turbulence filter creates liquid morphing effect on scroll.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "liquid", "svg", "displacement"],
        previewUrl: "/Animations&Motion/ScrollReveals/LiquidDisplacement",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/LiquidDisplacement.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/LiquidDisplacement.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/LiquidDisplacement/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1634152962476-4b8a00e1915c?q=80&w=1000&auto=format&fit=crop", description: "Image URL" },
            { name: "backgroundColor", type: "string", default: "bg-neutral-950", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[150vh]", description: "Height of the container" },
            { name: "imageWidth", type: "string", default: "w-[800px]", description: "Width of the image" },
            { name: "imageHeight", type: "string", default: "h-[500px]", description: "Height of the image" },
            { name: "text", type: "string", default: "LIQUEFY", description: "Text displayed over the image" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "filterId", type: "string", default: "liquidFilter", description: "ID of the SVG filter" },
            { name: "frequencyRange", type: "[number, number]", default: "[0.05, 0]", description: "Frequency range for turbulence" },
            { name: "scaleRange", type: "[number, number]", default: "[500, 0]", description: "Scale range for displacement" },
            { name: "opacityRange", type: "[number, number]", default: "[0, 1]", description: "Opacity range" },
            { name: "opacityProgressRange", type: "[number, number]", default: "[0, 0.5]", description: "Opacity progress range" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start end\", \"center center\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This production-ready React UI component is ideal for landing page hero sections, luxury brands, and artistic portfolios. Use this React component when building high-impact reveals for images that require a fluid, liquid-like interaction with user scrolling.",
        bestPractices: "Maintain scalable component architecture by keeping the `containerHeight` large enough (e.g., 150vh) to allow for a smooth transition. Follow React best practices by using high-contrast text colors over the image. Optimize for performance in large-scale applications by being mindful of the SVG filter's complexity on low-end devices.",
        whyMatters: "Displacement effects are a signature of premium modern frontend development. This animated UI component helps you build immersive real-world application architecture that feels alive and responsive to every pixel of the user's scroll.",
        faqs: [
            { question: "Can I use multiple images?", answer: "The current implementation is optimized for a single high-impact image reveal, but it can be adapted for a sequence of images with minor code changes." },
            { question: "Is the liquid effect adjustable?", answer: "Yes, you can define the 'turbulence' via the `frequencyRange` and `scaleRange` props to make the effect subtle or extreme." },
            { question: "Does it work with SSR?", answer: "Yes, it is designed for Next.js and handles server-side rendering while ensuring smooth client-side animation." }
        ],
    },
    {
        id: "magnifying-portal",
        name: "Magnifying Portal",
        description: "Circular mask expands to reveal content with zoom effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "portal", "mask", "zoom"],
        previewUrl: "/Animations&Motion/ScrollReveals/MagnifyingPortal",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/MagnifyingPortal.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/MagnifyingPortal.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/MagnifyingPortal/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?q=80&w=1000&auto=format&fit=crop", description: "Image URL" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[200vh]", description: "Height of the container" },
            { name: "backgroundText", type: "string", default: "FOCUS", description: "Background text displayed" },
            { name: "backgroundTextColor", type: "string", default: "text-neutral-800", description: "Color of background text" },
            { name: "backgroundTextSize", type: "string", default: "text-[15vw]", description: "Size of background text" },
            { name: "imageWidth", type: "string", default: "w-[80vw]", description: "Width of the image" },
            { name: "imageHeight", type: "string", default: "h-[80vh]", description: "Height of the image" },
            { name: "maskSizeRange", type: "[string, string]", default: "[\"0%\", \"200%\"]", description: "Mask size range" },
            { name: "imageScaleRange", type: "[number, number]", default: "[2, 1]", description: "Image scale range" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start end\", \"end end\"]", description: "Scroll offset configuration" },
            { name: "cardTitle", type: "string", default: "The Vista", description: "Title text on the card" },
            { name: "cardDescription", type: "string", default: "Optical scaling creates simulated depth.", description: "Description text on the card" },
            { name: "cardBgColor", type: "string", default: "bg-white", description: "Background color of the card" },
            { name: "cardTextColor", type: "string", default: "text-black", description: "Text color of the card" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for SaaS landing pages and creative brand portfolios that want to emphasize a 'focal point.' This customizable UI component is great for zooming into specific details of a product or a landscape image as the user scrolls down the page.",
        bestPractices: "Optimize for performance in large-scale applications by lazy-loading the high-resolution image used in the portal. Maintain consistent spacing within your design system by adjusting the `imageWidth` and `imageHeight` to fit your layout. Follow React best practices by pairing the zoom effect with meaningful `cardTitle` content.",
        whyMatters: "Masking and portal effects are at the forefront of modern UI design. This reusable React component provides a sophisticated way to manage focus and attention, adding semantic authority and visual depth to your real-world application architecture.",
        faqs: [
            { question: "Can the portal be a different shape?", answer: "The current implementation uses a circular mask, but you can easily modify the CSS clip-path to support squares, stars, or custom SVG paths." },
            { question: "How much can the image zoom?", answer: "The `imageScaleRange` prop lets you define the start and end zoom levels, typically ranging from 2x down to 1x for a natural feel." },
            { question: "Does it support hover interaction as well?", answer: "This component is primarily scroll-driven for cinematic effect, but hover-based displacement can be added for extra interactivity." }
        ],
    },
    {
        id: "card-deck-fan",
        name: "Card Deck Fan",
        description: "Physics-based card stack that fans out and stacks on scroll.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "cards", "fan", "physics"],
        previewUrl: "/Animations&Motion/ScrollReveals/CardDeckFan",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/CardDeckFan.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/CardDeckFan.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/CardDeckFan/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "cardCount", type: "number", default: "5", description: "Number of cards" },
            { name: "backgroundColor", type: "string", default: "bg-slate-900", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[150vh]", description: "Height of the container" },
            { name: "perspective", type: "string", default: "perspective-[1000px]", description: "CSS perspective value" },
            { name: "cardWidth", type: "string", default: "w-64", description: "Width of each card" },
            { name: "cardHeight", type: "string", default: "h-96", description: "Height of each card" },
            { name: "cardBgColor", type: "string", default: "bg-white", description: "Background color of cards" },
            { name: "cardBorderColor", type: "string", default: "border-white/20", description: "Border color of cards" },
            { name: "cardPadding", type: "string", default: "p-2", description: "Padding of cards" },
            { name: "imageOpacity", type: "number", default: "0.8", description: "Opacity of images" },
            { name: "labelColor", type: "string", default: "text-white", description: "Color of card labels" },
            { name: "labelSize", type: "string", default: "text-xs", description: "Size of card labels" },
            { name: "hintText", type: "string", default: "SCROLL TO STACK", description: "Hint text displayed" },
            { name: "hintColor", type: "string", default: "text-white", description: "Color of hint text" },
            { name: "hintSize", type: "string", default: "text-sm", description: "Size of hint text" },
            { name: "fanAngle", type: "number", default: "15", description: "Fan angle in degrees" },
            { name: "fanXOffset", type: "number", default: "100", description: "X offset for fan effect" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start end\", \"center center\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for creative portfolios, e-commerce product stacks, and enterprise-ready UIs that need a playful yet organized way to display cards. Use this React component when building 'Our Team' sections or testimonial carousels that require a physical, tactile feel.",
        bestPractices: "Maintain scalable component architecture by using the `fanAngle` prop to ensure cards don't overlap too much or too little. Follow React best practices by providing unique keys for each card in the stack. Optimize for performance by using a reasonable `cardCount` (e.g., 5-8).",
        whyMatters: "Physics-based motion is a hallmark of modern frontend development. This production-ready component helps you build an interface that users instinctively want to interact with, adding a layer of polish to your real-world application architecture.",
        faqs: [
            { question: "Can I drag the cards manually?", answer: "The primary interaction is scroll-based for a consistent narrative, but it can be combined with drag gestures for a more hands-on experience." },
            { question: "How do I add more cards?", answer: "Simply pass a longer array of image URLs and update the `cardCount` prop to match." },
            { question: "Is the stacking animation smooth on mobile?", answer: "Yes, it uses Framer Motion's hardware-accelerated transforms to ensure 60fps performance on most mobile devices." }
        ],
    },
    {
        id: "gallery-walk",
        name: "Gallery Walk",
        description: "Curved path animation with cards following a smooth trajectory.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "gallery", "curved", "path"],
        previewUrl: "/Animations&Motion/ScrollReveals/GalleryWalk",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/GalleryWalk.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/GalleryWalk.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/GalleryWalk/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "backgroundColor", type: "string", default: "bg-neutral-100", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[200vh]", description: "Height of the container" },
            { name: "title", type: "string", default: "CURVATURE", description: "Title text displayed" },
            { name: "titleColor", type: "string", default: "text-neutral-300", description: "Color of the title" },
            { name: "titleSize", type: "string", default: "text-4xl", description: "Size of the title" },
            { name: "cardWidth", type: "string", default: "w-[400px]", description: "Width of each card" },
            { name: "cardHeight", type: "string", default: "h-[500px]", description: "Height of each card" },
            { name: "gap", type: "string", default: "gap-10", description: "Gap between cards" },
            { name: "paddingLeft", type: "string", default: "pl-[50vw]", description: "Left padding" },
            { name: "xRange", type: "[string, string]", default: "[\"20%\", \"-100%\"]", description: "X position range" },
            { name: "yRange", type: "[number, number, number]", default: "[100, -100, 100]", description: "Y position range" },
            { name: "rotateRange", type: "[number, number]", default: "[10, -10]", description: "Rotation range in degrees" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start end\", \"end start\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for high-end photography sites, event galleries, and modern web applications that want to showcase images with a sense of rhythm and flow. This React component is ideal for making vertical scrolling feel horizontal and cinematic.",
        bestPractices: "Maintain consistent spacing within your design system by adjusting the `gap` and `paddingLeft` props. Follow React best practices by ensuring the `yRange` isn't so extreme that it causes cards to leave the viewport too early. Optimize for performance in large-scale applications by lazy-loading the images in the carousel.",
        whyMatters: "Curved paths and non-linear motion are difficult to get right. This production-ready component provides a robust implementation of a 'gallery walk' that adds incredible visual interest and premium feel to your real-world application architecture.",
        faqs: [
            { question: "Can I customize the curve shape?", answer: "Yes, by adjusting the `yRange` array, you can define the vertical arc that the cards follow as they move across the screen." },
            { question: "Does it support text-only cards?", answer: "Absolutely! While designed for images, the card containers can hold any React elements including text, icons, or custom components." },
            { question: "Is the rotation mandatory?", answer: "No, you can set the `rotateRange` to [0, 0] if you prefer a perfectly horizontal, non-tilting gallery walk." }
        ],
    },
    {
        id: "fracture-assembler",
        name: "Fracture Assembler",
        description: "Grid fragments assemble from random 3D positions into a complete image.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "fracture", "3d", "grid"],
        previewUrl: "/Animations&Motion/ScrollReveals/FractureAssembler",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/FractureAssembler.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/FractureAssembler.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/FractureAssembler/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?q=80&w=1000&auto=format&fit=crop", description: "Image URL" },
            { name: "rows", type: "number", default: "5", description: "Number of rows in the grid" },
            { name: "cols", type: "number", default: "5", description: "Number of columns in the grid" },
            { name: "backgroundColor", type: "string", default: "bg-neutral-900", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[200vh]", description: "Height of the container" },
            { name: "gridWidth", type: "string", default: "w-[800px]", description: "Width of the grid" },
            { name: "gridHeight", type: "string", default: "h-[600px]", description: "Height of the grid" },
            { name: "perspective", type: "string", default: "perspective-[1000px]", description: "CSS perspective value" },
            { name: "gap", type: "string", default: "gap-0.5", description: "Gap between grid cells" },
            { name: "offsetRange", type: "number", default: "1500", description: "Range of random offset" },
            { name: "zOffsetRange", type: "number", default: "1000", description: "Range of Z offset" },
            { name: "scrollProgressRange", type: "[number, number]", default: "[0, 0.8]", description: "Scroll progress range" },
            { name: "opacityRange", type: "[number, number]", default: "[0, 1]", description: "Opacity range" },
            { name: "opacityProgressRange", type: "[number, number]", default: "[0, 0.5]", description: "Opacity progress range" },
            { name: "text", type: "string", default: "ASSEMBLE", description: "Text displayed" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-7xl", description: "Size of the text" },
            { name: "textProgressRange", type: "[number, number]", default: "[0.7, 1]", description: "Text progress range" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start end\", \"end end\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for tech brands, data dashboards, and Next.js applications that want to emphasize construction or data assembly. This customizable UI component is perfect for intro sections where you want to reveal a 'big picture' piece by piece.",
        bestPractices: "Optimize for performance in large-scale applications by keeping the `rows` and `cols` at a reasonable level (e.g., 5x5 or 6x6). Follow React best practices by using the `offsetRange` to create enough chaos before the assembly. Maintain scalable component architecture by using responsive grid width and height props.",
        whyMatters: "3D grid assembly is a powerful visual metaphor for modern frontend development. This animated UI component allows you to transition from abstract chaos to a sharp, meaningful image, adding semantic authority to your project's storytelling.",
        faqs: [
            { question: "Can the pieces rotate as they assemble?", answer: "Yes, the component includes 3D rotation logic that can be enabled to make the fragments spin into place for extra energy." },
            { question: "What image aspect ratio works best?", answer: "The component is flexible, but it works best with high-resolution images that match the `gridWidth` and `gridHeight` aspect ratio." },
            { question: "How fast do the pieces assemble?", answer: "The assembly speed is tied to the scroll position, giving the user full control over the 'magical' construction moment." }
        ],
    },
    {
        id: "x-ray-scanner",
        name: "X-Ray Scanner",
        description: "Horizontal scan line reveals content from grayscale to full color.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "xray", "scanner", "mask"],
        previewUrl: "/Animations&Motion/ScrollReveals/XRayScanner",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/XRayScanner.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/XRayScanner.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/XRayScanner/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1000&auto=format&fit=crop", description: "Image URL" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "imageWidth", type: "string", default: "w-[80vw]", description: "Width of the image" },
            { name: "imageHeight", type: "string", default: "h-[80vh]", description: "Height of the image" },
            { name: "gridCols", type: "number", default: "12", description: "Number of grid columns" },
            { name: "gridRows", type: "number", default: "12", description: "Number of grid rows" },
            { name: "gridColor", type: "string", default: "border-green-500/30", description: "Color of grid lines" },
            { name: "gridOpacity", type: "number", default: "0.3", description: "Opacity of grid lines" },
            { name: "scanLineColor", type: "string", default: "bg-red-500", description: "Color of the scan line" },
            { name: "scanLineShadow", type: "string", default: "shadow-[0_0_50px_4px_rgba(255,0,0,0.8)]", description: "Shadow of the scan line" },
            { name: "scanText", type: "string", default: "SCANNING STRUCTURE...", description: "Scanning text displayed" },
            { name: "scanTextColor", type: "string", default: "text-green-500", description: "Color of scanning text" },
            { name: "scanTextSize", type: "string", default: "text-xl", description: "Size of scanning text" },
            { name: "renderedText", type: "string", default: "RENDERED", description: "Rendered text displayed" },
            { name: "renderedTextColor", type: "string", default: "text-white", description: "Color of rendered text" },
            { name: "renderedTextSize", type: "string", default: "text-6xl", description: "Size of rendered text" },
            { name: "scanXRange", type: "[string, string]", default: "[\"0%\", \"100%\"]", description: "Scan X position range" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start start\", \"end end\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for security-themed sites, technical products, and modern web applications that want to showcase internal structures or 'behind the scenes' content. This React component is perfect for a storytelling reveal that transitions from abstract grid lines to realistic imagery.",
        bestPractices: "Maintain scalable component architecture by keeping the `scanLineColor` consistent with your site's alert or focus colors. Follow React best practices by ensuring the `scanText` is descriptive and engaging. Optimize for performance in large-scale applications by using hardware-accelerated shadows for the scan line.",
        whyMatters: "Visualizing a 'scanning' process adds a layer of interactivity and narrative depth. This reusable React component gives you a production-level tool for building immersive, tech-forward real-world application architecture that captivates users.",
        faqs: [
            { question: "Can I use it for vertical scanning?", answer: "The current implementation is horizontal, but it can be easily rotated for a top-to-bottom scan effect." },
            { question: "How do I change the grid density?", answer: "The `gridCols` and `gridRows` props allow you to define exactly how many grid lines appear over the image." },
            { question: "Is the grayscale reveal automatic?", answer: "Yes, the component handles the transition from a grayscale grid-view to a full-color image based on the scan line's progress." }
        ],
    },
    {
        id: "vortex-tunnel",
        name: "Vortex Tunnel",
        description: "Scaling circle creates a tunnel effect revealing content at the center.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "vortex", "tunnel", "scale"],
        previewUrl: "/Animations&Motion/ScrollReveals/VortexTunnel",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/VortexTunnel.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/VortexTunnel.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/VortexTunnel/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1535382607908-17277b0c3608?q=80&w=1000&auto=format&fit=crop", description: "Image URL" },
            { name: "backgroundColor", type: "string", default: "bg-neutral-900", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "backgroundText", type: "string", default: "THE VOID", description: "Background text displayed" },
            { name: "backgroundTextColor", type: "string", default: "text-neutral-800", description: "Color of background text" },
            { name: "backgroundTextSize", type: "string", default: "text-[10vw]", description: "Size of background text" },
            { name: "portalSize", type: "string", default: "w-[10vw] h-[10vw]", description: "Size of the portal" },
            { name: "portalColor", type: "string", default: "bg-blue-500", description: "Color of the portal" },
            { name: "portalShadow", type: "string", default: "shadow-[0_0_100px_rgba(0,255,255,0.5)]", description: "Shadow of the portal" },
            { name: "innerImageWidth", type: "string", default: "w-[100vw]", description: "Width of inner image" },
            { name: "innerImageHeight", type: "string", default: "h-[100vh]", description: "Height of inner image" },
            { name: "innerImageOpacity", type: "number", default: "0.5", description: "Opacity of inner image" },
            { name: "innerText", type: "string", default: "REALITY", description: "Inner text displayed" },
            { name: "innerSubtext", type: "string", default: "Breached", description: "Inner subtext displayed" },
            { name: "innerTextColor", type: "string", default: "text-black", description: "Color of inner text" },
            { name: "innerTextSize", type: "string", default: "text-9xl", description: "Size of inner text" },
            { name: "innerSubtextSize", type: "string", default: "text-2xl", description: "Size of inner subtext" },
            { name: "scaleRange", type: "[number, number]", default: "[0, 20]", description: "Scale range" },
            { name: "rotateRange", type: "[number, number]", default: "[0, 180]", description: "Rotation range in degrees" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start start\", \"end end\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for experimental brands, cinematic storytelling, and experimental modern web applications. Use this React component when you want to create a 'wormhole' effect that draws the user into a completely different visual reality as they scroll down.",
        bestPractices: "Optimize for performance by ensuring the `innerImage` is not too heavy for multiple renders. Follow React best practices by setting a reasonable `scaleRange` to avoid extreme pixelation. Maintain scalable component architecture by using the `portalColor` to emphasize the breach point.",
        whyMatters: "Tunnel and vortex effects are powerful tools for immersive UI design. This reusable React component gives you a production-ready way to implement complex scaling and rotation transitions, helping you build a unique real-world application architecture.",
        faqs: [
            { question: "Can I use video instead of an image?", answer: "Yes, the portal is a container that can hold any React element, including high-quality looped videos for an even more dynamic effect." },
            { question: "Is the rotation speed adjustable?", answer: "The rotation is mapped to scroll progress, so the speed is determined by how fast the user scrolls and the `rotateRange` prop." },
            { question: "How large does the portal get?", answer: "By default, the portal scales up to 20x its original size, effectively 'swallowing' the screen to reveal the inner content." }
        ],
    },
    {
        id: "chromatic-slip",
        name: "Chromatic Slip",
        description: "RGB color separation effect with skew animation on scroll.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "chromatic", "rgb", "glitch"],
        previewUrl: "/Animations&Motion/ScrollReveals/ChromaticSlip",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/ChromaticSlip.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/ChromaticSlip.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/ChromaticSlip/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1000&auto=format&fit=crop", description: "Image URL" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[120vh]", description: "Height of the container" },
            { name: "containerWidth", type: "string", default: "w-[80vw]", description: "Width of the container" },
            { name: "containerHeight2", type: "string", default: "h-[60vh]", description: "Height of the inner container" },
            { name: "redColor", type: "string", default: "bg-red-600", description: "Color of red layer" },
            { name: "greenColor", type: "string", default: "bg-green-600", description: "Color of green layer" },
            { name: "blueColor", type: "string", default: "bg-blue-600", description: "Color of blue layer" },
            { name: "text", type: "string", default: "IMPACT", description: "Text displayed" },
            { name: "textColor1", type: "string", default: "text-red-200", description: "Color of text on red layer" },
            { name: "textColor2", type: "string", default: "text-green-200", description: "Color of text on green layer" },
            { name: "textColor3", type: "string", default: "text-blue-200", description: "Color of text on blue layer" },
            { name: "textSize", type: "string", default: "text-9xl", description: "Size of the text" },
            { name: "xRedRange", type: "[number, number]", default: "[-200, 0]", description: "X range for red layer" },
            { name: "xBlueRange", type: "[number, number]", default: "[200, 0]", description: "X range for blue layer" },
            { name: "skewRange", type: "[number, number]", default: "[45, 0]", description: "Skew range in degrees" },
            { name: "opacityRange", type: "[number, number]", default: "[0, 1]", description: "Opacity range" },
            { name: "opacityProgressRange", type: "[number, number]", default: "[0, 0.8]", description: "Opacity progress range" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start end\", \"center center\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for tech brands, digital art portfolios, and Next.js applications that want to emphasize a high-energy, digital aesthetic. Use this React component when building 'impact' sections where you want to reveal content through an RGB color separation effect.",
        bestPractices: "Follow React best practices by ensuring the `skewRange` is not so extreme that it breaks the layout or makes text unreadable. Maintain scalable component architecture by using the separate color layering props to stay within your brand guidelines. Optimize for performance by triggering the slip effect only once as the user reaches the trigger point.",
        whyMatters: "Chromatic aberration is a hallmark of modern frontend development style. This production-ready component helpsคุณ build an interface that feels like it's part of a high-tech data stream, adding semantic authority and visual premium to your real-world application architecture.",
        faqs: [
            { question: "Can I customize the color separation channels?", answer: "Yes, you have full control over the `redColor`, `greenColor`, and `blueColor` props to create custom color profiles like CMYK or mono-tonal shifts." },
            { question: "Does it work with any font?", answer: "Yes, the chromatic slip is applied to the container, so any typography you place inside will benefit from the RGB separation effect." },
            { question: "Is it responsive?", answer: "Absolutely! The container width and height are fully customizable and support responsive Tailwind classes." }
        ],
    },
    {
        id: "perspective-carousel",
        name: "Perspective Carousel",
        description: "3D ring carousel that rotates on scroll revealing images in 3D space.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "carousel", "3d", "perspective"],
        previewUrl: "/Animations&Motion/ScrollReveals/PerspectiveCarousel",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/PerspectiveCarousel.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/PerspectiveCarousel.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/PerspectiveCarousel/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "images", type: "string[]", default: "[]", description: "Array of image URLs" },
            { name: "cardCount", type: "number", default: "5", description: "Number of cards in the carousel" },
            { name: "backgroundColor", type: "string", default: "bg-[#050505]", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[400vh]", description: "Height of the container" },
            { name: "perspective", type: "string", default: "perspective-[1000px]", description: "CSS perspective value" },
            { name: "cardWidth", type: "string", default: "w-[600px]", description: "Width of each card" },
            { name: "cardHeight", type: "string", default: "h-[400px]", description: "Height of each card" },
            { name: "cardBgColor", type: "string", default: "bg-white/5", description: "Background color of cards" },
            { name: "cardBorderColor", type: "string", default: "border-white/10", description: "Border color of cards" },
            { name: "cardPadding", type: "string", default: "p-4", description: "Padding of cards" },
            { name: "imageOpacity", type: "number", default: "0.8", description: "Opacity of images" },
            { name: "labelColor", type: "string", default: "text-white/20", description: "Color of card labels" },
            { name: "labelSize", type: "string", default: "text-6xl", description: "Size of card labels" },
            { name: "translateZ", type: "number", default: "600", description: "Z-axis translation distance" },
            { name: "rotateYRange", type: "[number, number]", default: "[0, 360]", description: "Y rotation range in degrees" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start start\", \"end end\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for luxury showcases, product lookbooks, and Next.js applications that require a premium 3D gallery experience. Use this React component when building a carousel that needs to feel like a revolving 3D ring of content.",
        bestPractices: "Maintain consistent spacing within your design system by adjusting the `translateZ` distance to prevent cards from feeling too claustrophobic. Follow React best practices by using the `cardCount` prop to balance visual detail with memory usage. Optimize for performance in large-scale applications by lazy-loading images that are not within the current view angle.",
        whyMatters: "3D ring carousels are a staple of premium modern UI development. This production-ready component provide a robust implementation of complex 3D math and scroll mapping, helping you build a real-world application architecture that is truly world-class.",
        faqs: [
            { question: "Does it support auto-rotation?", answer: "The primary experience is scroll-driven for precise user control, but an auto-rotation toggle can be easily integrated using a separate interval hook." },
            { question: "Can I put videos in the cards?", answer: "Yes, the card containers are fully standard React elements and can hold any interactive content, including videos and buttons." },
            { question: "Is the rotation circular?", answer: "Yes, the `rotateYRange` typically goes from 0 to 360 degrees, creating a perfect loop as you scroll through the entire list of cards." }
        ],
    },
    {
        id: "inception-fold",
        name: "Inception Fold",
        description: "Corner reveal effect that peels back like a page fold.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "fold", "corner", "peel"],
        previewUrl: "/Animations&Motion/ScrollReveals/InceptionFold",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/InceptionFold.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/InceptionFold.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/InceptionFold/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?q=80&w=1000&auto=format&fit=crop", description: "Image URL" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-900", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[300vh]", description: "Height of the container" },
            { name: "backgroundColor2", type: "string", default: "bg-yellow-400", description: "Secondary background color" },
            { name: "backgroundText", type: "string", default: "SECRET", description: "Background text displayed" },
            { name: "backgroundTextColor", type: "string", default: "text-black", description: "Color of background text" },
            { name: "backgroundTextSize", type: "string", default: "text-[15vw]", description: "Size of background text" },
            { name: "backgroundTextRotation", type: "number", default: "45", description: "Rotation of background text in degrees" },
            { name: "backgroundTextOpacity", type: "number", default: "0.2", description: "Opacity of background text" },
            { name: "imageWidth", type: "string", default: "w-[400px]", description: "Width of the image" },
            { name: "imageHeight", type: "string", default: "h-[500px]", description: "Height of the image" },
            { name: "imageRotation", type: "number", default: "12", description: "Rotation of image in degrees" },
            { name: "imageBorderColor", type: "string", default: "border-white", description: "Border color of image" },
            { name: "imageBorderWidth", type: "string", default: "border-8", description: "Border width of image" },
            { name: "foldBgColor", type: "string", default: "bg-white", description: "Background color of fold" },
            { name: "foldTitle", type: "string", default: "PEEL", description: "Title text on fold" },
            { name: "foldTitleColor", type: "string", default: "text-black", description: "Color of fold title" },
            { name: "foldTitleSize", type: "string", default: "text-8xl", description: "Size of fold title" },
            { name: "foldDescription", type: "string", default: "Scroll to tear reality", description: "Description text on fold" },
            { name: "foldDescriptionColor", type: "string", default: "text-gray-500", description: "Color of fold description" },
            { name: "foldDescriptionSize", type: "string", default: "text-2xl", description: "Size of fold description" },
            { name: "foldPadding", type: "string", default: "p-20", description: "Padding of fold content" },
            { name: "rotateRange", type: "[number, number]", default: "[0, -90]", description: "Rotation range in degrees" },
            { name: "xRange", type: "[number, number]", default: "[0, -500]", description: "X position range" },
            { name: "yRange", type: "[number, number]", default: "[0, 500]", description: "Y position range" },
            { name: "borderRadiusRange", type: "[string, string]", default: "[\"0%\", \"50%\"]", description: "Border radius range" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start start\", \"end end\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for creative portfolios, 'Easter egg' reveals, and Next.js applications that want to emphasize discovery. Use this React component when you want to create a tactile 'peel back' effect that reveals hidden content in the corner of the screen.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the hidden text doesn't overflow when the fold is open. Follow React best practices by using high-contrast colors for the `foldBgColor` to make the peel effect obvious. Optimize for performance by keeping the `containerHeight` sufficient for a slow, satisfying peel.",
        whyMatters: "Corner peels and page folds add a layer of physical interaction to digital interfaces. This reusable React component provide a robust implementation of complex 2D transitions that add semantic authority and surprise to your real-world application architecture.",
        faqs: [
            { question: "Can I peel from a different corner?", answer: "The current implementation is optimized for a top-right peel, but the rotation and X/Y ranges can be mirrored for any corner of the screen." },
            { question: "What should I put under the fold?", answer: "The hidden layer is perfect for 'secret' links, social media icons, or high-impact keywords that define your brand." },
            { question: "Is it responsive?", answer: "Yes, the component uses viewport-based text sizes and flexible container heights to ensure the peel effect works on all screen sizes." }
        ],
    },
    {
        id: "pixel-sort",
        name: "Pixel Sort",
        description: "Vertical bar stretch effect that reconstructs the image on scroll.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "pixel", "sort", "stretch"],
        previewUrl: "/Animations&Motion/ScrollReveals/PixelSort",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/PixelSort.tsx"),
            jsx: getCode("src/components/Animations&Motion/ScrollReveals/jsx/PixelSort.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/PixelSort/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "image", type: "string", default: "https://images.unsplash.com/photo-1634152962476-4b8a00e1915c?q=80&w=1000&auto=format&fit=crop", description: "Image URL" },
            { name: "backgroundColor", type: "string", default: "bg-black", description: "Background color of the component" },
            { name: "containerHeight", type: "string", default: "h-[120vh]", description: "Height of the container" },
            { name: "imageWidth", type: "string", default: "w-[80vw]", description: "Width of the image" },
            { name: "imageHeight", type: "string", default: "h-[60vh]", description: "Height of the image" },
            { name: "scaleYRange", type: "[number, number]", default: "[50, 1]", description: "Y scale range" },
            { name: "scaleXRange", type: "[number, number]", default: "[0.1, 1]", description: "X scale range" },
            { name: "filterStart", type: "string", default: "blur(10px) contrast(200%)", description: "Initial filter value" },
            { name: "filterEnd", type: "string", default: "blur(0px) contrast(100%)", description: "Final filter value" },
            { name: "gradientFrom", type: "string", default: "from-black", description: "Gradient start color class" },
            { name: "gradientTo", type: "string", default: "to-transparent", description: "Gradient end color class" },
            { name: "gradientOpacity", type: "number", default: "0.5", description: "Opacity of gradient overlay" },
            { name: "statusText", type: "string", default: "RECONSTRUCTING_DATA_STREAM...", description: "Status text displayed" },
            { name: "statusTextColor", type: "string", default: "text-white", description: "Color of status text" },
            { name: "statusTextSize", type: "string", default: "text-sm", description: "Size of status text" },
            { name: "scrollOffset", type: "[string, string]", default: "[\"start end\", \"center center\"]", description: "Scroll offset configuration" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for glitch-themed sites, technical products, and modern web applications that want to emphasize a digital 'reconstruction' feel. Use this React component when building intro sequences where an image appears to be stream-loaded and processed in real-time.",
        bestPractices: "Optimize for performance by adjusting the `scaleYRange` to avoid excessive stretching on low-end GPUs. Follow React best practices by using high-contrast colors for the `statusText`. Maintain scalable component architecture by keeping the `filterStart` blur level consistent with other glitch effects on your site.",
        whyMatters: "Pixel sorting and data-bending are major trends in tech-forward modern frontend development. This customizable UI component gives you a production-level implementation of complex CSS and motion mapping, helping you build a real-world application architecture that feels cutting-edge.",
        faqs: [
            { question: "Can I use it for horizontal sorting?", answer: "The current implementation is focused on vertical bar stretching, but the scale axis can be swapped for horizontal motion with minor adjustments." },
            { question: "Does it work with transparent PNGs?", answer: "Yes, but for the best 'pixel sort' effect, it is recommended to use high-contrast images with well-defined color regions." },
            { question: "Is the reconstruction speed adjustable?", answer: "The speed is tied to the user's scroll position, allowing for a perfectly synchronized 'data reveal' as they move down the page." }
        ],
    },
    {
        id: "bento-shutter",
        name: "Bento Shutter",
        description: "Grid-based bento pieces fly away to reveal content underneath with staggered movement.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "bento", "grid", "shutter"],
        previewUrl: "/Animations&Motion/ScrollReveals/BentoShutter",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/BentoShutter.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/BentoShutter/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [],
        whenToUse: "Ideal for modern SaaS landing pages, feature showcases, and bento-grid based portfolios. Use this React component when you want to reveal a 'core truth' or a high-impact call-to-action buried beneath a sophisticated grid layout.",
        bestPractices: "Maintain scalable component architecture by keeping the bento grid items logically related to the revealed content. Follow React best practices by ensuring staggered animations don't take too long to complete. Optimize for performance by using simple shapes for the grid pieces.",
        whyMatters: "Bento grids are a major design trend in modern frontend development. This animated UI component adds a 'shutter' mechanic to the grid, transforming a static layout into a dynamic storytelling tool that enhances your real-world application architecture.",
        faqs: [
            { question: "Can I customize the fly-away direction?", answer: "Yes, the stagger and direction of each piece can be controlled to make them fly outwards, inwards, or in a random scatter pattern." },
            { question: "Does it work with existing bento layouts?", answer: "Absolutely! The shutter logic can be applied as an overlay to any standard CSS grid or flex-based bento system." },
            { question: "Is it mobile-friendly?", answer: "Yes, the component is responsive and the grid automatically adjusts to smaller screens while maintaining the shutter effect." }
        ],
    },
    {
        id: "cinematic-scroll",
        name: "Cinematic Scroll",
        description: "Layered panels scale down as new content slides in, creating a cinematic storytelling experience.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "cinematic", "layered", "storytelling"],
        previewUrl: "/Animations&Motion/ScrollReveals/CinematicScroll",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/CinematicScroll.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/CinematicScroll/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [],
        whenToUse: "Perfect for brand stories, product 'manifestos', and artistic portfolios that require a high-end cinematic feel. Use this React component when you want each scroll section to feel like a camera zoom or a panel transition in a premium movie trailer.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring each story layer has sufficient breathing room for text. Follow React best practices by using high-resolution images for the background panels. Optimize for performance in large-scale applications by lazy-loading panels that are further down the scroll path.",
        whyMatters: "Cinematic scroll transitions are a hallmark of award-winning modern UI development. This production-ready component helps you build an interface that feels like a narrative journey rather than a simple web page, adding incredible visual authority to your real-world application architecture.",
        faqs: [
            { question: "How many panels are recommended?", answer: "Between 3 and 5 panels usually provide the best narrative flow without overwhelming the user with too much scroll depth." },
            { question: "Can I add interactive buttons to the panels?", answer: "Yes, each panel is a fully interactive container that can hold buttons, forms, or custom components." },
            { question: "Is the scaling range adjustable?", answer: "Yes, you can define how much each panel 'shrinks' as it transitions out to create a subtle or dramatic cinematic effect." }
        ],
    },
    {
        id: "focal-shift-reveal",
        name: "Focal Shift Reveal",
        description: "Depth-based reveals where content moves from blurred background to sharp focus during scroll.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "focal", "blur", "depth"],
        previewUrl: "/Animations&Motion/ScrollReveals/FocalShiftReveal",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/FocalShiftReveal.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/FocalShiftReveal/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [],
        whenToUse: "Ideal for product detail pages, photographer portfolios, and modern web applications that want to emphasize depth of field. Use this React component to reveal 'hidden' text or secondary image details by shifting the focus from the foreground to the background.",
        bestPractices: "Optimize for performance by ensuring the blur intensity doesn't exceed 20px, as very high blur values can be heavy on mobile GPUs. Follow React best practices by using high-contrast typography for the focused content. Maintain scalable component architecture by choosing a standard set of blur values for your design system.",
        whyMatters: "Focal shifts provide a physical, camera-like interaction that is rare in modern frontend development. This reusable React component gives you a production-level tool for building immersive 3D-like experiences on a 2D screen, adding visual depth and premium feel to your real-world application architecture.",
        faqs: [
            { question: "Can I use it with text instead of images?", answer: "Absolutely! The focal shift works beautifully for bringing specific paragraphs or headlines into sharp focus while blurring others." },
            { question: "How fast should the focus shift?", answer: "The shift is mapped to scroll progress, so the 'speed' is controlled by the user's scroll velocity and the height of the transition container." },
            { question: "Does it support multiple layers of focus?", answer: "Yes, the component can be extended to support 'mid-ground' focus layers for a more complex lens-like experience." }
        ],
    },
    {
        id: "horizontal-scroll-text-reveal",
        name: "Horizontal Scroll Text Reveal",
        description: "Two rows of images split vertically to reveal core text content with horizontal parallax.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "horizontal", "parallax", "text"],
        previewUrl: "/Animations&Motion/ScrollReveals/HorizontalScrollTextReveal",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/HorizontalScrollTextReveal.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/HorizontalScrollTextReveal/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [],
        whenToUse: "Perfect for fashion magazines, high-end landing pages, and cinematic brand intros in Next.js. Use this React component to reveal a center-stage message by sliding two horizontal image galleries in opposite directions.",
        bestPractices: "Maintain scalable component architecture by using images that have a similar color palette to ensure the central text remains legible. Follow React best practices by setting the horizontal shift amount based on the viewport width. Optimize for performance by using efficient transforms for the image rows.",
        whyMatters: "Horizontal parallax combined with vertical reveals is a staple of 'award-winning' modern UI development. This production-ready component provides a robust framework for complex multi-axis motion, adding semantic authority and visual excitement to your real-world application architecture.",
        faqs: [
            { question: "Can the image rows move at different speeds?", answer: "Yes, the parallax multiplier can be customized for each row to create a more complex sense of depth." },
            { question: "What should the aspect ratio of the images be?", answer: "Portait or square images work best for creating a dense, textured background grid that splits apart." },
            { question: "Is it responsive?", answer: "Yes, the horizontal shift and central text scale appropriately to ensure a high-impact experience on mobile devices." }
        ],
    },
    {
        id: "infinite-tunnel",
        name: "Infinite Tunnel",
        description: "Zoom through a series of story layers that fly past the camera creating a tunnel effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "tunnel", "zoom", "story"],
        previewUrl: "/Animations&Motion/ScrollReveals/InfiniteTunnel",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/InfiniteTunnel.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/InfiniteTunnel/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [],
        whenToUse: "Excellent for immersive brand introductions, 'history' timelines, and Next.js storytelling experiences. Use this React component when you want to create a sense of moving forward through layers of content, perfect for 'into the future' narratives.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring each layer has a distinct visual theme. Follow React best practices by using the `z-index` properly to manage layer stacking. Optimize for performance by limiting the number of heavy interactive elements within the deep layers.",
        whyMatters: "Tunnel zooms are a high-impact technique in modern frontend development. This customizable UI component givesคุณ a production-level implementation of infinite-feeling motion, helping you build a real-world application architecture that truly stands out.",
        faqs: [
            { question: "How many layers can I add?", answer: "The component is designed for 3 to 7 layers to ensure a smooth transition without excessive browser memory usage." },
            { question: "Can I use different shapes for the tunnel?", answer: "Yes, while the 'zoom' is logarithmic, you can vary the content of each layer to create organic or geometric tunnel shapes." },
            { question: "Is the zoom speed customizable?", answer: "The zoom is mapped to the user's scroll depth, allowing for a fully natural exploration of the content layers." }
        ],
    },
    {
        id: "lens-portal",
        name: "Lens Portal",
        description: "A moving circular aperture reveals hidden layers of a narrative world under a dark mask.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "lens", "aperture", "mask"],
        previewUrl: "/Animations&Motion/ScrollReveals/LensPortal",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/LensPortal.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/LensPortal/page.tsx")
        },
        dependencies: ["next", "framer-motion", "lucide-react"],
        props: [],
        whenToUse: "Perfect for tech-focused landing pages, 'under the hood' sections, and modern web applications that want to emphasize precision and discovery. Use this React component to reveal a 'blueprint' or a secondary image as the user scrolls an aperture lens across the screen.",
        bestPractices: "Optimize for performance in large-scale applications by keeping the masked layer simple. Follow React best practices by using high-contrast colors for the lens border. Maintain scalable component architecture by allowing the lens size to be responsive to different screen resolutions.",
        whyMatters: "Precision masking and interactive 'viewports' are a hallmark of high-end modern UI design. This production-ready component helps you build an interface that feels like a tool or a high-tech instrument, adding semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Can the lens move automatically?", answer: "The lens move is primarily scroll-driven for narrative impact, but it can be easily adapted to follow the mouse cursor on hover." },
            { question: "What should I reveal under the lens?", answer: "Highly detailed content like circuit boards, code snippets, or high-fidelity product internals works best for this effect." },
            { question: "Is it compatible with mobile?", answer: "Yes, the lens movement is mapped to vertical scroll progress, ensuring the reveal effect is clear on vertical screens." }
        ],
    },
    {
        id: "morphinga",
        name: "Morphing",
        description: "Full-screen hero image shrinks into a card while new content slides in from the side.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "morphing", "hero", "card"],
        previewUrl: "/Animations&Motion/ScrollReveals/Morphing",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/Morphing.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/Morphing/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [],
        whenToUse: "Ideal for product detail pages and Next.js portfolios that want to transition from a 'hero' state to a 'content' state seamlessly. Use this React component to morph a full-screen image into a small sidebar or card as more information appears.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the morphed card has a clear relationship with the original image. Follow React best practices by using shared layout animations. Optimize for performance by ensuring the final card state isn't too complex.",
        whyMatters: "Morphing transitions are essential for fluid, app-like modern UI development. This reusable React component provides a production-ready implementation of complex layout shifts, helping you build a real-world application architecture that feels cohesive and polished.",
        faqs: [
            { question: "Can I morph multiple elements?", answer: "The component is optimized for a single high-impact morph, but the same logic can be applied to a group of elements using Framer Motion's layout prop." },
            { question: "How much can the image shrink?", answer: "The final size is fully customizable, allowing you to morph into a small fingernail icon or a medium-sized content card." },
            { question: "Does it support reverse morphing?", answer: "Yes, as the user scrolls back up, the card will perfectly morph back into the full-screen hero image." }
        ],
    },
    {
        id: "ortho-rotational",
        name: "Ortho Rotational",
        description: "3D rotational transitions where panels pivot around a center point on the X-axis.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "ortho", "rotation", "3d"],
        previewUrl: "/Animations&Motion/ScrollReveals/OrthoRotational",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/OrthoRotational.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/OrthoRotational/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [],
        whenToUse: "Perfect for innovative landing pages, creative portfolios, and modern web applications that want to break away from flat 2D scrolling. Use this React component when you want each section to pivot into view like panels on a rotating 3D sign.",
        bestPractices: "Maintain scalable component architecture by keeping the rotation angle around 90 degrees for a clean 'flip' feel. Follow React best practices by ensuring the perspective is high enough to avoid extreme distortion. Optimize for performance in large-scale applications by using hardware-accelerated CSS transforms.",
        whyMatters: "Ortho rotational transitions add a tactile, dimensional quality to web navigation. This production-ready component helpsคุณ build an interface that feels robust and structural, adding semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Can I rotate on the Y-axis instead?", answer: "Yes, the rotation axis can be changed from X (vertical flip) to Y (horizontal swing) with a single prop adjustment." },
            { question: "Is it compatible with text content?", answer: "Absolutely! The 3D rotation works with any content, including text, buttons, and complex React components." },
            { question: "Does it support touch scrolling?", answer: "Yes, it is fully optimized for touch devices, with rotation progress mapped to standard touch-scroll events." }
        ],
    },
    {
        id: "perspective-fold-reveal",
        name: "Perspective Fold Reveal",
        description: "Two halves of a UI component meet and flatten from a 3D perspective fold.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "fold", "perspective", "3d"],
        previewUrl: "/Animations&Motion/ScrollReveals/PerspectiveFoldReveal",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/PerspectiveFoldReveal.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/PerspectiveFoldReveal/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [],
        whenToUse: "Ideal for dashboard widgets, 'opening' sequences, and modern web applications that want to emphasize construction. Use this React component when you want a card or a section to 'unfold' and flatten out as it enters the viewport.",
        bestPractices: "Optimize for performance by ensuring the folding halves don't have extremely complex children. Follow React best practices by using high-contrast shadows to emphasize the 3D fold. Maintain scalable component architecture by choosing a standard folding axis for your design system.",
        whyMatters: "Folding reveals are a great way to manage space and add energetic transitions. This customizable UI component gives you a production-level implementation of a 3D fold, adding visual depth and semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Can it unfold vertically?", answer: "Yes, the fold can be set to horizontal (book-like) or vertical (brochure-like) depending on your design needs." },
            { question: "How 'deep' is the fold?", answer: "The perspective prop controls the intensity of the 3D effect, allowing for everything from a subtle bend to a deep 90-degree fold." },
            { question: "Does it work with SSR?", answer: "Yes, like all our components, it is optimized for Next.js and handles server-side rendering without hydration issues." }
        ],
    },
    {
        id: "vertical-scroll-text-reveal",
        name: "Vertical Scroll Text Reveal",
        description: "A dense grid of images moves vertically at different speeds to reveal a central text layer.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["scroll", "reveal", "vertical", "parallax", "text"],
        previewUrl: "/Animations&Motion/ScrollReveals/VerticalScrollTextReveal",
        code: {
            tsx: getCode("src/components/Animations&Motion/ScrollReveals/tsx/VerticalScrollTextReveal.tsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/ScrollReveals/VerticalScrollTextReveal/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [],
        whenToUse: "Excellent for hero sections, landing page intros, and cinematic web experiences in Next.js. Use this React component when you want to reveal a 'manifesto' or a central headline by moving a wall of images out of the way vertically.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the image grid has a balanced density. Follow React best practices by pairing the movement with clear, bold typography. Optimize for performance in large-scale applications by using optimized image formats (WebP/AVIF) for the grid.",
        whyMatters: "Vertical parallax with a central focal point is a powerful storytelling technique in modern frontend development. This production-ready component provides a robust framework for multi-speed reveals, adding visual polish and premium feel to your real-world application architecture.",
        faqs: [
            { question: "How do I change the image grid density?", answer: "You can adjust the number of columns and rows in the image grid to make the 'wall' feel more or less dense." },
            { question: "Can I use different speeds for each column?", answer: "Yes, the parallax multiplier can be uniquely set for each column or row to create a more dynamic, 'curtained' reveal effect." },
            { question: "Is it mobile-responsive?", answer: "Absolutely! The image grid and central text adapt to different screen sizes to maintain the reveal's impact on all devices." }
        ],
    },
];

