import { Component } from "../types";

export const skeletonsLoaderComponentsMetadata: Component[] = [
    {
        id: "classic-skeleton",
        name: "Classic Skeleton",
        description: "Comprehensive skeleton loading components collection with shimmer animations. Includes blocks, text, avatars, cards, list items, buttons, inputs, and loading overlays. High-performance shimmer effects with framer-motion.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["animations-motion", "skeleton", "loader", "loading", "shimmer", "placeholder", "ui"],
        previewUrl: "/Animations&Motion/SkeletonsLoader/Classic",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "react", "framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: 'Switches the entire color palette. "dark" uses neutral-950 backgrounds; "light" uses neutral-50 backgrounds.' },
            { name: "shimmer", type: "boolean", default: "true", description: "Toggles the shimmer animation globally across all skeleton pieces in the demo." },
        ],
        whenToUse: "Essential for modern web applications and SaaS dashboards to improve perceived performance. Use this React component during data fetching states to prevent layout shifts and keep the user engaged while content is loading.",
        bestPractices: "Follow React best practices by matching the skeleton's shape and size exactly to the final content structure. Maintain scalable component architecture by creating reusable skeleton wrappers for your complex components.",
        whyMatters: "Skeleton loaders are a key part of premium frontend development, providing a smoother transition from loading to ready states. This customizable UI component helps build robust real-world application architecture that feels fast and reliable.",
        faqs: [
            { question: "Does it support custom colors?", answer: "Yes, use the theme prop for dark/light presets. For deeper customization, fork the component and update the token objects at the top of the file." },
            { question: "Is it accessible?", answer: "The component is purely visual — add 'aria-busy' and 'aria-live' attributes to the parent container for screen reader support." },
            { question: "How many skeleton types are included?", answer: "8 types: blocks, text lines, avatars, cards, list items, buttons, inputs, and a loading overlay wrapper." }
        ],
    },
    {
        id: "uilora-dashboard-skeleton",
        name: "Uilora Dashboard",
        description: "Full SaaS dashboard skeleton with sidebar navigation, topbar, KPI stat cards, chart placeholder, and a data table — all shimmering in sync.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["animations-motion", "skeleton", "loader", "dashboard", "saas", "shimmer"],
        previewUrl: "/Animations&Motion/SkeletonsLoader/UiloraDashboard",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: 'Color palette. "dark" uses deep navy tones; "light" uses neutral gray-white.' },
            { name: "accentColor", type: "string", default: '"#6366f1"', description: "Brand accent color applied as a subtle hairline ring on the content area." },
            { name: "sidebarCollapsed", type: "boolean", default: "false", description: "Collapses the sidebar from 220px to 48px icon-only with a smooth transition." },
            { name: "statCards", type: "number", default: "4", description: "Number of KPI stat cards to render (clamped 2–5)." },
        ],
        whenToUse: "Ideal for SaaS admin panels, analytics dashboards, and CRM tools. Drop it in as the loading state for your entire app shell — sidebar, topbar, metrics, chart, and table all load together.",
        bestPractices: "Match statCards to your actual KPI count so the skeleton layout mirrors the real UI perfectly.",
        whyMatters: "A full-layout skeleton prevents jarring reflows as content loads. When the sidebar, header, and body areas appear instantly as skeletons, the app feels fast even before a single API call resolves.",
        faqs: [
            { question: "How do I add more table rows?", answer: "Fork the component and increase the array length in the table section — each row is a single reusable component call." },
            { question: "Can I animate each section separately?", answer: "Yes. Each major section has its own stagger delay. Adjust the delay multiplier at the top of the component." },
            { question: "Does sidebarCollapsed affect content layout?", answer: "Yes — when collapsed, the main content area expands to fill the freed sidebar space via CSS transition." }
        ],
    },
    {
        id: "uilora-feed-skeleton",
        name: "Uilora Feed",
        description: "Social / news feed skeleton with a stories row and staggered post cards — avatar, content lines, optional image, and action pill rows.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["animations-motion", "skeleton", "loader", "feed", "social", "shimmer"],
        previewUrl: "/Animations&Motion/SkeletonsLoader/UiloraFeed",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: 'Color palette. "dark" uses near-black cards; "light" uses white cards on a gray page.' },
            { name: "accentColor", type: "string", default: '"#10b981"', description: "Brand accent applied as a subtle ring on story avatars." },
            { name: "postCount", type: "number", default: "4", description: "Number of post skeleton cards to render (clamped 2–6)." },
            { name: "showStories", type: "boolean", default: "true", description: "Shows or hides the horizontal stories/highlights row at the top of the feed." },
        ],
        whenToUse: "Perfect for social platforms, news aggregators, content feeds, and community products. The alternating image/no-image pattern mirrors real feed variance.",
        bestPractices: "Set postCount to match the number of posts visible above the fold. Disable showStories for feeds without a highlights mechanic.",
        whyMatters: "Staggered entrance animations on each post create a natural cascade that communicates progressive loading, reducing user anxiety during long fetches.",
        faqs: [
            { question: "Which posts show an image bone?", answer: "Posts at even indices (0, 2, 4...) include an image bone. Odd-index posts skip it." },
            { question: "How do I adjust the story count?", answer: "Fork the component and change the Array.from length in the StoriesRow component." },
            { question: "Can I use this for a comment thread?", answer: "Yes — disable showStories and set postCount to match your comment depth." }
        ],
    },
    {
        id: "uilora-kanban-skeleton",
        name: "Uilora Kanban",
        description: "Project-management Kanban skeleton with multi-column layout, varied card heights, tag pills, avatar stacks, and a dashed add-card button.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["animations-motion", "skeleton", "loader", "kanban", "project", "shimmer"],
        previewUrl: "/Animations&Motion/SkeletonsLoader/UiloraKanban",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: 'Color palette. "dark" uses deep navy columns; "light" uses off-white panels.' },
            { name: "accentColor", type: "string", default: '"#f59e0b"', description: "Brand accent tinting the shimmer gradient and board title." },
            { name: "columns", type: "number", default: "4", description: "Number of Kanban columns to render (clamped 2–5)." },
            { name: "cardsPerColumn", type: "number", default: "3", description: "Cards per column (clamped 2–5). Cards cycle through 4 visual variants for natural height variation." },
        ],
        whenToUse: "Use as the loading state for Linear-style boards, Jira sprint views, CRM pipeline screens, and any drag-and-drop task manager.",
        bestPractices: "Match columns to your actual board count. Leave cardsPerColumn at 3 for the best visual balance.",
        whyMatters: "A skeleton that mirrors organic card-height variance tells users that real varied content is coming — not a uniform placeholder grid.",
        faqs: [
            { question: "How do the card variants work?", answer: "Cards cycle through 4 patterns: full, minimal, compact, tagged. This produces organic height variation across every column." },
            { question: "Can I add a board header?", answer: "Yes — a board header with title and action buttons is already rendered above the column grid." },
            { question: "Does it support horizontal scrolling?", answer: "Yes — the column container uses overflow-x-auto, so extra columns trigger native horizontal scroll." }
        ],
    },
    {
        id: "uilora-email-skeleton",
        name: "Uilora Email",
        description: "3-pane email client skeleton — sidebar folders, inbox list with active-item state, and a full email preview with header, body, attachments, and reply box.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["animations-motion", "skeleton", "loader", "email", "inbox", "shimmer"],
        previewUrl: "/Animations&Motion/SkeletonsLoader/UiloraEmail",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["framer-motion"],
        props: [
            { name: "theme", type: '"dark" | "light"', default: '"dark"', description: 'Color palette. "dark" uses deep navy panes; "light" uses white panels.' },
            { name: "accentColor", type: "string", default: '"#0ea5e9"', description: "Brand accent applied to the compose button and subtle shimmer tint." },
            { name: "emailCount", type: "number", default: "6", description: "Number of inbox list items to render (clamped 3–10)." },
            { name: "previewOpen", type: "boolean", default: "true", description: "Shows or hides the right email preview pane." },
        ],
        whenToUse: "Use for email clients, support inboxes, notification centers, and any 3-pane messaging layout.",
        bestPractices: "Set previewOpen=false on mobile breakpoints. Match emailCount to items visible at typical viewport heights.",
        whyMatters: "Email clients are among the most complex UIs to skeleton correctly. A 3-pane layout with folder badges, active states, and a realistic preview pane communicates the app's information architecture before any data loads.",
        faqs: [
            { question: "How does the active email state work?", answer: "The first list item uses the active-item background color token to simulate the selected state." },
            { question: "Can I remove the preview pane?", answer: "Yes — set previewOpen=false. Only the sidebar and inbox list render, ideal for mobile views." },
            { question: "Are folder badges always visible?", answer: "Badges appear on alternating folder items. Fork the component and adjust the badge condition in the sidebar folder map." }
        ],
    },
];
