import { getCode } from "../getCode";
import { Component } from "../components-data";

export const textAnimationComponents: Component[] = [
    {
        id: "magnetic-hover",
        name: "Magnetic Hover",
        description: "Variable font weight responds to mouse proximity creating magnetic effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "magnetic", "hover", "interactive"],
        previewUrl: "/Animations&Motion/TextAnimations/MagneticHover",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/MagneticHover.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/MagneticHover.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/MagneticHover/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "MAGNETIC", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "maxWeight", type: "number", default: "900", description: "Maximum font weight" },
            { name: "minWeight", type: "number", default: "100", description: "Minimum font weight" },
            { name: "maxWidth", type: "number", default: "1.5", description: "Maximum scale width" },
            { name: "minWidth", type: "number", default: "1", description: "Minimum scale width" },
            { name: "activeColor", type: "string", default: "#ffffff", description: "Color when active" },
            { name: "inactiveColor", type: "string", default: "#52525b", description: "Color when inactive" },
            { name: "distanceRange", type: "[number, number]", default: "[0, 300]", description: "Distance range for transformation" },
            { name: "colorRange", type: "[number, number]", default: "[0, 200]", description: "Color range for transformation" },
            { name: "gap", type: "string", default: "gap-2", description: "Gap between characters" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This production-ready React UI component is ideal for landing page headlines, luxury brands, and high-impact web applications. Use this React component when you want a headline that feels tactile and responsive to the user's attention.",
        bestPractices: "Optimize for legibility by ensuring the `maxWeight` doesn't make the characters overlap too much. Follow React best practices by setting a reasonable `distanceRange` for a subtle, professional feel. Maintain scalable component architecture by using responsive text sizes for different screen widths.",
        whyMatters: "Variable fonts are at the forefront of modern UI typography. This animated UI component helps 你 build an interface that feels alive and premium, adding a layer of semantic authority and visual depth to your real-world application architecture.",
        faqs: [
            { question: "Does this require a special font?", answer: "Yes, it works best with variable fonts that support weight axes, but it can also be used with standard fonts by mapping weight to scale." },
            { question: "Can I use it for long paragraphs?", answer: "It is primarily designed for high-impact headlines (H1/H2) to ensure the magnetic effect remains performant and readable." },
            { question: "Is it mobile-friendly?", answer: "Yes, it supports touch move events, providing a similar magnetic experience on mobile devices and tablets." }
        ],
    },
    {
        id: "spotlight-reveal",
        name: "Spotlight Reveal",
        description: "Flashlight effect reveals text as you move your mouse over it.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "spotlight", "mask", "interactive"],
        previewUrl: "/Animations&Motion/TextAnimations/SpotlightReveal",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/SpotlightReveal.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/SpotlightReveal.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/SpotlightReveal/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "DARKNESS", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "dimTextColor", type: "string", default: "text-zinc-900", description: "Color of dimmed text" },
            { name: "brightTextColor", type: "string", default: "text-zinc-100", description: "Color of bright text" },
            { name: "textSize", type: "string", default: "text-8xl md:text-9xl", description: "Size of the text" },
            { name: "spotlightSize", type: "number", default: "200", description: "Size of the spotlight circle" },
            { name: "cursorSize", type: "string", default: "w-6 h-6", description: "Size of the cursor indicator" },
            { name: "cursorBorderColor", type: "string", default: "border-white", description: "Border color of the cursor" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for 'dark mode' landing pages, security-themed sites, and creative portfolios. Use this React component to create a sense of mystery and discovery, revealing your message as the user 'searches' the dark area with their mouse.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the hidden text has enough contrast when 'lit' by the spotlight. Follow React best practices by keeping the `spotlightSize` large enough for easy readability. Optimize for performance in large-scale applications by using hardware-accelerated masks.",
        whyMatters: "Interactive masking is a powerful way to engage users and encourage exploration. This production-ready component provides a robust implementation of complex CSS masks, adding a layer of polish and narrative interest to your real-world application architecture.",
        faqs: [
            { question: "Can I use multiple spotlights?", answer: "The current implementation is optimized for a single high-impact spotlight, but it can be adapted for multiple focus points with custom CSS." },
            { question: "How do I change the spotlight color?", answer: "The 'light' is created by the `brightTextColor`, but you can also add a color gradient overlay to the `spotlightSize` mask itself." },
            { question: "Does it work with images?", answer: "Yes, while designed for text, this masking logic can be easily applied to images to create a 'flashlight' reveal effect." }
        ],
    },
    {
        id: "vertical-loop",
        name: "Vertical Loop",
        description: "Seamless vertical carousel of words with smooth looping animation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "loop", "carousel", "vertical"],
        previewUrl: "/Animations&Motion/TextAnimations/VerticalLoop",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/VerticalLoop.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/VerticalLoop.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/VerticalLoop/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "words", type: "string[]", default: "[\"DREAM\", \"BUILD\", \"CREATE\", \"SHIP\", \"REPEAT\"]", description: "Array of words to loop" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textSize", type: "string", default: "text-7xl md:text-9xl", description: "Size of the text" },
            { name: "gradientFrom", type: "string", default: "from-purple-400", description: "Gradient start color class" },
            { name: "gradientTo", type: "string", default: "to-pink-600", description: "Gradient end color class" },
            { name: "animationDuration", type: "number", default: "4", description: "Animation duration in seconds" },
            { name: "containerHeight", type: "string", default: "h-[1.2em]", description: "Height of the container" },
            { name: "gap", type: "string", default: "pb-4", description: "Gap between words" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for hero sections, elevator pitches, and feature summaries in Next.js landing pages. Use this React component to cycle through key value propositions in a compact, energetic way.",
        bestPractices: "Follow React best practices by providing a list of words that are similar in length to avoid sudden layout shifts. Maintain scalable component architecture by using the `animationDuration` to match the reading speed of your target audience. Optimize for performance by reusing the word containers for the loop.",
        whyMatters: "Vertical loops are a hallmark of modern productivity SaaS homepages. This reusable React component gives developers a clean way to implement infinite carousels, adding a sense of momentum and authority to your project's messaging.",
        faqs: [
            { question: "Can I stop the animation on hover?", answer: "Yes, you can easily add a `whileHover` prop from Framer Motion to pause the loop when the user wants to read a specific word." },
            { question: "How many words can I include?", answer: "The component is optimized for 3-7 words. Too many words can make the loop feel too long or fast." },
            { question: "Does it support custom fonts?", answer: "Absolutely! The loop inherits all your global typography styles and supports any font-family or weight." }
        ],
    },
    {
        id: "accordion-text",
        name: "Accordion Text",
        description: "Characters expand vertically on hover with rotation and scale effects.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "accordion", "hover", "expand"],
        previewUrl: "/Animations&Motion/TextAnimations/AccordionText",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/AccordionText.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/AccordionText.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/AccordionText/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "EXPANSION", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-zinc-300", description: "Color of the text" },
            { name: "hoverColor", type: "string", default: "#fff", description: "Color on hover" },
            { name: "textSize", type: "string", default: "text-8xl md:text-9xl", description: "Size of the text" },
            { name: "containerHeight", type: "string", default: "h-[120px]", description: "Height of the container" },
            { name: "scaleY", type: "number", default: "1.2", description: "Vertical scale on hover" },
            { name: "margin", type: "string", default: "0 10px", description: "Margin on hover" },
            { name: "rotation", type: "number", default: "5", description: "Rotation angle in degrees" },
            { name: "springStiffness", type: "number", default: "300", description: "Spring animation stiffness" },
            { name: "springDamping", type: "number", default: "15", description: "Spring animation damping" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for creative studios, tech portfolios, and high-energy SaaS landing pages. This customizable UI component is great for adding a playful, elastic interaction to your main navigation or section titles.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the `containerHeight` accounts for the character expansion. Follow React best practices by using high-contrast colors for the `hoverColor`. Optimize for performance in large-scale applications by keeping the `springStiffness` at a natural level.",
        whyMatters: "Elastic and accordion-like animations add a sense of personality to an interface. This animated UI component helps you build a more memorable brand experience by adding subtle micro-interactions to your real-world application architecture.",
        faqs: [
            { question: "Can the characters expand downwards?", answer: "The current implementation scales from the center, but the `transform-origin` can be adjusted to scale from the top or bottom." },
            { question: "How do I change the rotation intensity?", answer: "The `rotation` prop allows you to define how much each character tilts when fanning out for the accordion effect." },
            { question: "Is it responsive?", answer: "Yes, it uses flexible character spacing and supports responsive Tailwind text size classes." }
        ],
    },
    {
        id: "flag-wave",
        name: "Flag Wave",
        description: "Characters animate in wave motion creating a flag-like undulation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "wave", "flag", "undulation"],
        previewUrl: "/Animations&Motion/TextAnimations/FlagWave",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/FlagWave.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/FlagWave.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/FlagWave/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "UNDULATION", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-blue-400", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "waveAmplitude", type: "number", default: "20", description: "Amplitude of the wave motion" },
            { name: "animationDuration", type: "number", default: "1.5", description: "Animation duration in seconds" },
            { name: "delayMultiplier", type: "number", default: "0.1", description: "Delay multiplier per character" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for maritime-themed sites, travel blogs, and Next.js applications that want to emphasize flow and movement. Use this React component for titles that need an organic, rhythmic animation as if blowing in the wind.",
        bestPractices: "Follow React best practices by setting the `waveAmplitude` to a subtle value (e.g., 10-20px) to maintain readability. Maintain scalable component architecture by using the `delayMultiplier` to create a smooth, continuous wave effect across the entire word. Optimize for performance by using simple CSS transforms for the character movement.",
        whyMatters: "Fluid motion and wave physics are difficult to implement manually. This production-ready component provides a robust framework for complex temporal offsets, adding visual interest and semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Can I use it for multiple lines of text?", answer: "Yes, but for the best effect, it's recommended to apply it per-line to maintain the individual character wave offsets." },
            { question: "Is the wave speed adjustable?", answer: "The `animationDuration` prop allows you to control exactly how fast the undulation is, from a slow breeze to a fast flutter." },
            { question: "Does it work with special characters?", answer: "Absolutely! The wave effect treats every character independently, including spaces and symbols." }
        ],
    },
    {
        id: "glitch-layers",
        name: "Glitch Layers",
        description: "RGB chromatic aberration layers create glitch effect on hover.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "glitch", "rgb", "chromatic"],
        previewUrl: "/Animations&Motion/TextAnimations/GlitchLayers",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/GlitchLayers.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/GlitchLayers.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/GlitchLayers/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "GLITCH", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "baseTextColor", type: "string", default: "text-white", description: "Base color of the text" },
            { name: "layer1Color", type: "string", default: "text-red-500", description: "Color of the first glitch layer" },
            { name: "layer2Color", type: "string", default: "text-cyan-500", description: "Color of the second glitch layer" },
            { name: "textSize", type: "string", default: "text-9xl", description: "Size of the text" },
            { name: "glitchAmplitude", type: "number", default: "5", description: "Amplitude of glitch movement" },
            { name: "animationDuration", type: "number", default: "0.2", description: "Animation duration in seconds" },
            { name: "repeatDelay1", type: "number", default: "0.1", description: "Repeat delay for first layer" },
            { name: "repeatDelay2", type: "number", default: "0.2", description: "Repeat delay for second layer" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for tech brands, digital art platforms, and high-energy Next.js portfolios. Use this React component when you want a headline that feels 'glitched' or high-tech, perfect for cyber-security or data-driven themes.",
        bestPractices: "Maintain consistent spacing within your design system by keeping the `glitchAmplitude` low (under 10px) to prevent characters from jumping too far. Follow React best practices by triggering the glitch effect only on hover to save GPU resources. Optimize for performance by using simple color layering without heavy filters.",
        whyMatters: "Chromatic aberration and glitch effects are iconic to modern frontend development. This customizable UI component gives you a production-level tool for building high-energy, interactive headers that add semantic authority to your real-world application architecture.",
        faqs: [
            { question: "How many layers does it use?", answer: "The component uses three layers (Base, Red, and Cyan) to create a realistic RGB chromatic aberration effect." },
            { question: "Can I use it on small body text?", answer: "It is best suited for large headlines, as the glitch movement can make small font sizes difficult to read." },
            { question: "Is the glitch pattern random?", answer: "Yes, the displacement values are randomized within the `glitchAmplitude` range during each animation frame." }
        ],
    },
    {
        id: "masked-reveal",
        name: "Masked Reveal",
        description: "Staggered word reveal with 3D rotation and gradient fade.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "mask", "stagger", "3d"],
        previewUrl: "/Animations&Motion/TextAnimations/MaskedReveal",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/MaskedReveal.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/MaskedReveal.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/MaskedReveal/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Orchestrated Chaos", description: "Text to display" },
            { name: "wordGap", type: "string", default: "gap-4", description: "Gap between words" },
            { name: "fontSize", type: "string", default: "text-6xl md:text-8xl", description: "Font size of the text" },
            { name: "fontWeight", type: "string", default: "font-bold", description: "Font weight of the text" },
            { name: "tracking", type: "string", default: "tracking-tighter", description: "Letter spacing" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "gradientFrom", type: "string", default: "from-zinc-100", description: "Gradient start color class" },
            { name: "gradientTo", type: "string", default: "to-zinc-500", description: "Gradient end color class" },
            { name: "staggerChildrenDelay", type: "number", default: "0.12", description: "Delay between children" },
            { name: "childDelayMultiplier", type: "number", default: "0.04", description: "Delay multiplier per child" },
            { name: "springDamping", type: "number", default: "12", description: "Spring animation damping" },
            { name: "springStiffness", type: "number", default: "100", description: "Spring animation stiffness" },
            { name: "initialY", type: "number", default: "50", description: "Initial Y position" },
            { name: "initialRotateX", type: "number", default: "-20", description: "Initial X rotation in degrees" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for elegant brand introductions, minimalist landing pages, and cinematic web experiences. Use this React component to reveal text with a sophisticated 'curtain' effect that combines 3D rotation and gradient fading.",
        bestPractices: "Optimize for legibility by ensures the `initialRotateX` isn't too extreme. Follow React best practices by using a standard `staggerChildrenDelay` (e.g., 0.1s) for a natural reveal rhythm. Maintain scalable component architecture by using responsive font sizes that work across mobile and desktop.",
        whyMatters: "Orchestrated reveals are a staple of premium modern UI development. This production-ready component provides a robust implementation of complex staggered motion, adding a layer of polish and semantic interest to your real-world application architecture.",
        faqs: [
            { question: "Can I reveal character by character?", answer: "The current implementation is word-based for best narrative flow, but the logic can be easily updated to target individual characters." },
            { question: "Does it support custom fonts?", answer: "Yes, it fully supports all global typography styles and works beautifully with high-contrast serif or sans-serif fonts." },
            { question: "Is the 3D rotation mandatory?", answer: "No, you can set the `initialRotateX` to 0 for a simple, elegant vertical slide reveal." }
        ],
    },
    {
        id: "perspective-hover",
        name: "Perspective Hover",
        description: "3D perspective tilt effect on hover with depth layers.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "perspective", "3d", "hover"],
        previewUrl: "/Animations&Motion/TextAnimations/PerspectiveHover",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/PerspectiveHover.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/PerspectiveHover.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/PerspectiveHover/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Depth", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "perspectiveValue", type: "string", default: "perspective-1000", description: "CSS perspective value" },
            { name: "initialRotateX", type: "number", default: "17.5", description: "Initial X rotation in degrees" },
            { name: "initialRotateY", type: "number", default: "17.5", description: "Initial Y rotation in degrees" },
            { name: "depthTranslateZ1", type: "number", default: "75", description: "Z translation for first depth layer" },
            { name: "depthTranslateZ2", type: "number", default: "150", description: "Z translation for second depth layer" },
            { name: "depthTextColor", type: "string", default: "text-zinc-800", description: "Color of depth text" },
            { name: "frontGradientFrom", type: "string", default: "from-indigo-300", description: "Front gradient start color" },
            { name: "frontGradientVia", type: "string", default: "via-white", description: "Front gradient middle color" },
            { name: "frontGradientTo", type: "string", default: "to-indigo-300", description: "Front gradient end color" },
            { name: "fontSize", type: "string", default: "text-7xl md:text-9xl", description: "Font size of the text" },
            { name: "fontWeight", type: "string", default: "font-black", description: "Font weight of the text" },
            { name: "tracking", type: "string", default: "tracking-tight", description: "Letter spacing" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for artistic portfolios, luxury brands, and interactive web applications that want to emphasize depth. Use this React component to create a 3D 'look around' effect where different layers of text tilt at different speeds based on mouse movement.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the `depthTranslateZ` layers don't overlap too much. Follow React best practices by keeping the `perspectiveValue` high enough (e.g., 1000px) to avoid extreme pixel distortion. Optimize for performance by using CSS-based 3D transforms.",
        whyMatters: "Parallax depth adds a level of sophistication and interactivity that static text lacks. This reusable React component gives developers a robust way to implement complex 3D tilt math, helping you build a real-world application architecture that feels deep and immersive.",
        faqs: [
            { question: "How many depth layers can I add?", answer: "The component is optimized for 2-3 layers for the best performance. Too many layers can become heavy on the browser's 3D engine." },
            { question: "Does it follow the mouse or scroll?", answer: "This specific component is mouse-based for a reactive, 'holographic' feel on hover." },
            { question: "Can I use different colors for the depth layers?", answer: "Yes, the `depthTextColor` prop allows you to create shadows, neon glows, or ghosted text effects behind the main layer." }
        ],
    },
    {
        id: "velocity-scroll",
        name: "Velocity Scroll",
        description: "Infinite scrolling text that responds to scroll velocity.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "velocity", "scroll", "infinite"],
        previewUrl: "/Animations&Motion/TextAnimations/VelocityScroll",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/VelocityScroll.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/VelocityScroll.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/VelocityScroll/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text1", type: "string", default: "Kinetic Motion", description: "First text to scroll" },
            { name: "text2", type: "string", default: "Scroll Velocity", description: "Second text to scroll" },
            { name: "baseVelocity1", type: "number", default: "-3", description: "Base velocity for first text" },
            { name: "baseVelocity2", type: "number", default: "3", description: "Base velocity for second text" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "spacing", type: "string", default: "space-y-8", description: "Spacing between text elements" },
            { name: "fontSize", type: "string", default: "text-8xl md:text-9xl", description: "Font size of the text" },
            { name: "fontWeight", type: "string", default: "font-black", description: "Font weight of the text" },
            { name: "tracking", type: "string", default: "tracking-tighter", description: "Letter spacing" },
            { name: "textColor", type: "string", default: "text-zinc-300", description: "Color of the text" },
            { name: "marginRight", type: "string", default: "mr-12", description: "Right margin between text instances" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for news tickers, event announcements, and dynamic headers in Next.js applications. Use this React component when you want an infinite scrolling message that speeds up or slows down based on the user's scroll velocity.",
        bestPractices: "Maintain scalable component architecture by keeping the `baseVelocity` at a comfortable reading speed. Follow React best practices by ensures the infinite loop doesn't have too many repeated elements. Optimize for performance by using efficient transforms and avoiding layout thrashing.",
        whyMatters: "Velocity-based interaction makes a site feel responsive to user behavior. This production-ready component provides a high-performance implementation of infinite marquee motion, adding energy and semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Can I scroll the text horizontally?", answer: "Yes, the current implementation is horizontal, and the direction can be reversed by changing the sign of the `baseVelocity`." },
            { question: "How does it handle different screen sizes?", answer: "The component uses a percentage-based wrap, ensuring the infinite loop looks seamless on everything from mobile to ultrawide monitors." },
            { question: "Can I use multiple lines?", answer: "Absolutely! You can stack multiple instances with different velocities to create a complex 'kinetic typography' stack." }
        ],
    },
    {
        id: "stroke-fill",
        name: "Stroke Fill",
        description: "SVG text animates from stroke to fill with smooth transition.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "svg", "stroke", "fill"],
        previewUrl: "/Animations&Motion/TextAnimations/StrokeFill",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/StrokeFill.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/StrokeFill.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/StrokeFill/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Elegance", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "strokeWidth", type: "number", default: "1.5", description: "Width of the stroke" },
            { name: "strokeColor", type: "string", default: "stroke-zinc-100", description: "Color of the stroke" },
            { name: "fillColor", type: "string", default: "#ffffff", description: "Color of the fill" },
            { name: "fontFamily", type: "string", default: "font-[900]", description: "Font family class" },
            { name: "fontSize", type: "string", default: "text-8xl", description: "Font size of the text" },
            { name: "fontWeight", type: "string", default: "uppercase", description: "Font weight of the text" },
            { name: "tracking", type: "string", default: "tracking-widest", description: "Letter spacing" },
            { name: "animationDuration", type: "number", default: "3", description: "Animation duration in seconds" },
            { name: "fillDelay", type: "number", default: "2", description: "Delay before fill animation" },
            { name: "fillDuration", type: "number", default: "1", description: "Duration of fill animation" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for luxury brand logos, cinematic intros, and Next.js Landing Pages. Use this React component for a high-impact reveal where text starts as a delicate outline and fills into a solid, bold shape.",
        bestPractices: "Follow React best practices by setting the `fillDelay` to match your viewport entry. Maintain consistent spacing within your design system by using high-contrast colors for the `strokeColor`. Optimize for performance by keeping the SVG path complexity manageable.",
        whyMatters: "SVG stroke animations are a classic mark of quality in modern frontend development. This customizable UI component provides a robust framework for timed reveals, adding visual polish and semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Does it work with any font?", answer: "Yes, it works with any web font or local font. The component automatically generates the SVG paths based on the rendered text." },
            { question: "Is the stroke thickness adjustable?", answer: "The `strokeWidth` prop allows you to make the initial outline as delicate or as heavy as your design requires." },
            { question: "Can I trigger the fill on hover?", answer: "The current implementation is time-based for cinematic effect, but a hover-triggered fill can be easily implemented with a state change." }
        ],
    },
    {
        id: "cipher-text",
        name: "Cipher Text",
        description: "Characters scramble and decode to reveal the final message.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "cipher", "decode", "scramble"],
        previewUrl: "/Animations&Motion/TextAnimations/CipherText",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/CipherText.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/CipherText.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/CipherText/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "targetText", type: "string", default: "ENCRYPTED_DATA", description: "Target text to reveal" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-green-400", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-7xl md:text-9xl", description: "Size of the text" },
            { name: "cyclesPerLetter", type: "number", default: "2", description: "Number of cycles per letter" },
            { name: "shuffleTime", type: "number", default: "50", description: "Time between shuffles in milliseconds" },
            { name: "chars", type: "string", default: "!@#$%^&*():{};|,.<>/?", description: "Characters to use for scrambling" },
            { name: "autoScramble", type: "boolean", default: "true", description: "Whether to auto-scramble on mount" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for security dashboards, developer portfolios, and tech-themed Next.js landing pages. Use this React component when you want to build a 'hacker' or 'encryption' aesthetic, decoding a message as it enters the view.",
        bestPractices: "Maintain consistent spacing within your design system by choosing a `targetText` that fits your layout. Follow React best practices by avoiding too many `cyclesPerLetter` for longer strings to maintain readability. Optimize for performance by using a lightweight character set for scrambling.",
        whyMatters: "Cipher reveals add a layer of interactivity and narrative flair. This production-ready component gives you a robust implementation of text scrambling physics, adding a high-tech feel and semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Can I use custom characters for scrambling?", answer: "Yes, the `chars` prop lets you define exactly which symbols (e.g., binary, matrix code, or emoji) are used during the shuffle." },
            { question: "How long does the reveal take?", answer: "The duration is determined by `cyclesPerLetter` and `shuffleTime`. Shorter shuffles feel 'glitchy', while longer ones feel like complex decryption." },
            { question: "Does it support auto-reveal on scroll?", answer: "Yes, it is designed to trigger automatically when mounted, which can be combined with an Intersection Observer for scroll-timed reveals." }
        ],
    },
    {
        id: "liquid-motion",
        name: "Liquid Motion",
        description: "Gooey filter creates liquid blob animation around text.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "liquid", "gooey", "filter"],
        previewUrl: "/Animations&Motion/TextAnimations/LiquidMotion",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/LiquidMotion.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/LiquidMotion.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/LiquidMotion/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "FLUIDITY", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "blob1Color", type: "string", default: "bg-indigo-500", description: "Color of the first blob" },
            { name: "blob1Size", type: "string", default: "w-32 h-32", description: "Size of the first blob" },
            { name: "blob2Color", type: "string", default: "bg-purple-500", description: "Color of the second blob" },
            { name: "blob2Size", type: "string", default: "w-24 h-24", description: "Size of the second blob" },
            { name: "blob1Duration", type: "number", default: "5", description: "Animation duration for first blob" },
            { name: "blob2Duration", type: "number", default: "7", description: "Animation duration for second blob" },
            { name: "blurAmount", type: "number", default: "10", description: "Blur amount for the gooey filter" },
            { name: "filterId", type: "string", default: "goo", description: "ID of the SVG filter" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for artistic web experiences, high-end portfolios, and Next.js applications that want a fluid, organic feel. Use this React component to create text that appears to be trapped in or interacting with a liquid 'lava lamp' background.",
        bestPractices: "Optimize for performance in large-scale applications by keeping the `blurAmount` at a reasonable level (e.g., 10-15px). Follow React best practices by using high-contrast colors for the `textColor` against the moving blobs. Maintain scalable component architecture by scoping the SVG gooey filter correctly to avoid affecting other elements.",
        whyMatters: "Gooey filters and organic blob motion are at the cutting edge of modern UI design. This reusable React component provides a sophisticated implementation of complex SVG filters, adding visual depth and semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Can I change the blob colors?", answer: "Absolutely! The `blob1Color` and `blob2Color` props allow you to match the liquid motion to your brand's palette." },
            { question: "Is the movement random?", answer: "The blobs follow a defined path with varying durations, creating an organic, non-repeating feel." },
            { question: "Does it work on Safari?", answer: "Yes, this implementation uses standards-compliant SVG filters that are widely supported across all modern browsers." }
        ],
    },
    {
        id: "elastic-hovers",
        name: "Elastic Hovers",
        description: "Physics-based vertical stretch on character hover with spring animation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "elastic", "physics", "hover"],
        previewUrl: "/Animations&Motion/TextAnimations/ElasticHovers",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/ElasticHovers.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/ElasticHovers.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/ElasticHovers/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Elastic Physics", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "fontWeight", type: "string", default: "font-thin", description: "Font weight of the text" },
            { name: "defaultColor", type: "string", default: "#e4e4e7", description: "Default color of the text" },
            { name: "hoverColor", type: "string", default: "#fff", description: "Color on hover" },
            { name: "defaultScale", type: "number", default: "1", description: "Default vertical scale" },
            { name: "hoverScale", type: "number", default: "1.5", description: "Vertical scale on hover" },
            { name: "springStiffness", type: "number", default: "200", description: "Spring animation stiffness" },
            { name: "springDamping", type: "number", default: "10", description: "Spring animation damping" },
            { name: "springMass", type: "number", default: "0.5", description: "Spring animation mass" },
            { name: "hoverShadow", type: "string", default: "0 0 20px rgba(255,255,255,0.5)", description: "Text shadow on hover" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Excellent for playful brand identities, toy/game websites, and modern Next.js landing pages. Use this React component for headers that need a tactile, 'squishy' feel as the user moves their cursor over individual characters.",
        bestPractices: "Follow React best practices by pairing the elastic stretch with a subtle color shift. Maintain scalable component architecture by using the `springStiffness` and `springDamping` to create a natural, bouncy physics. Optimize for performance by using clean transforms for the character scaling.",
        whyMatters: "Elastic physics add a delightful sense of responsiveness and physical presence to digital text. This customizable UI component gives you a production-ready implementation of complex spring-based motion, adding semantic authority and personality to your real-world application architecture.",
        faqs: [
            { question: "Can I adjust the 'bounciness'?", answer: "Yes, the `springStiffness` and `springDamping` props allow you to fine-tune the physics, from a stiff snap to a loose, jelly-like wobble." },
            { question: "Is the vertical stretch too extreme for reading?", answer: "The `hoverScale` prop lets you control exactly how much each character stretches, allowing you to keep it subtle for professional designs." },
            { question: "Does it work with multi-line text?", answer: "While optimized for single lines, it can be used for multiple lines by wrapping each word or line in an Elastic Hovers instance." }
        ],
    },
    {
        id: "slot-machine",
        name: "Slot Machine",
        description: "Split-flap display effect with characters flipping into place.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "slot", "flip", "machine"],
        previewUrl: "/Animations&Motion/TextAnimations/SlotMachine",
        code: {
            tsx: getCode("src/components/Animations&Motion/TextAnimations/tsx/SlotMachine.tsx"),
            jsx: getCode("src/components/Animations&Motion/TextAnimations/jsx/SlotMachine.jsx"),
        },
        usageCode: {
            tsx: getCode("src/app/(routes)/Animations&Motion/TextAnimations/SlotMachine/page.tsx")
        },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "JACKPOT", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-amber-300", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-8xl md:text-9xl", description: "Size of the text" },
            { name: "delayMultiplier", type: "number", default: "0.1", description: "Delay multiplier per character" },
            { name: "duration", type: "number", default: "0.8", description: "Animation duration in seconds" },
            { name: "ease", type: "number[]", default: "[0.16, 1, 0.3, 1]", description: "Easing function values" },
            { name: "oldCharColor", type: "string", default: "text-zinc-700", description: "Color of the old character" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for financial dashboards, high-stakes landing pages, and cinematic brand intros. Use this React component to reveal text with a split-flap 'slot machine' effect, perfect for revealing scores, prices, or key announcements.",
        bestPractices: "Maintain consistent spacing within your design system by ensures the text doesn't move during the flip. Follow React best practices by using the `delayMultiplier` to stagger the character reveals for a realistic mechanical feel. Optimize for performance by using simple 3D rotations for the flaps.",
        whyMatters: "Split-flap and slot machine animations carry a sense of mechanical precision and excitement. This production-ready component provides a robust framework for complex character cycling, adding a layer of polish and semantic authority to your real-world application architecture.",
        faqs: [
            { question: "Can I change the character set for the flip?", answer: "The current implementation uses a realistic 'old character' transition, but the logic can be adapted to cycle through a custom sequence of letters." },
            { question: "Is the flip sound included?", answer: "This is a visual component, but it's designed to be easily paired with an `onAnimationStart` trigger for custom mechanical sound effects." },
            { question: "How fast is the flip?", answer: "The `duration` prop lets you control the flip speed, from a rapid 'jackpot' shuffle to a slow, deliberate split-flap update." }
        ],
    },
];

