import { getCode } from "../getCode";
import { Component } from "../components-data";

export const textAnimationComponentsMetadata: Component[] = [
    {
        id: "magnetic-hover",
        name: "Magnetic Hover",
        description: "Variable font weight responds to mouse proximity creating magnetic effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "magnetic", "hover", "interactive"],
        previewUrl: "/Animations&Motion/TextAnimations/MagneticHover",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "MAGNETIC", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "maxWeight", type: "number", default: "900", description: "Maximum font weight" },
            { name: "minWeight", type: "number", default: "100", description: "Minimum font weight" },
            { name: "maxWidth", type: "number", default: "1.5", description: "Maximum scale width" },
            { name: "minWidth", type: "number", default: "1", description: "Minimum scale width" },
            { name: "activeColor", type: "string", default: "#ffffff", description: "Color when active" },
            { name: "inactiveColor", type: "string", default: "#52525b", description: "Color when inactive" },
            { name: "distanceRange", type: "[number, number]", default: "[0, 300]", description: "Distance range for transformation" },
            { name: "colorRange", type: "[number, number]", default: "[0, 200]", description: "Color range for transformation" },
            { name: "gap", type: "string", default: "gap-2", description: "Gap between characters" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This production-ready React UI component is ideal for SaaS dashboards, startup landing pages, and modern web applications where interactive typography is a priority. Use this React component when building high-end brand experiences that require subtle yet engaging motion effects for headings or hero sections.",
        bestPractices: "Follow React best practices by pairing this component with variable fonts that support weight axes. Maintain scalable component architecture by utilizing the responsive `textSize` prop. Optimize for performance in large-scale applications by using the `distanceRange` prop to limit heavy calculations on smaller screens. Ensure accessibility compliance by providing descriptive aria-labels for the dynamic text.",
        whyMatters: "In modern frontend development, micro-interactions are what separate premium products from basic clones. This animated UI component provides a bridge between static content and immersive user experiences, essential for scalable design systems and production-level applications that aim for high user retention.",
        faqs: [
            { question: "Is this component optimized for Next.js SSR?", answer: "Yes, it is fully compatible with Next.js and supports server-side rendering while ensuring smooth client-side hydration for animations." },
            { question: "Can I use any font with this component?", answer: "While it works with any font, it is best suited for variable fonts that support a range of weights to achieve the smooth 'magnetic' transition effect." },
            { question: "Does this component support dark mode?", answer: "Yes, you can easily customize the `activeColor` and `inactiveColor` props to match your application's dark and light themes." }
        ],
    },
    {
        id: "spotlight-reveal",
        name: "Spotlight Reveal",
        description: "Flashlight effect reveals text as you move your mouse over it.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "spotlight", "mask", "interactive"],
        previewUrl: "/Animations&Motion/TextAnimations/SpotlightReveal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "DARKNESS", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "dimTextColor", type: "string", default: "text-zinc-900", description: "Color of dimmed text" },
            { name: "brightTextColor", type: "string", default: "text-zinc-100", description: "Color of bright text" },
            { name: "textSize", type: "string", default: "text-8xl md:text-9xl", description: "Size of the text" },
            { name: "spotlightSize", type: "number", default: "200", description: "Size of the spotlight circle" },
            { name: "cursorSize", type: "string", default: "w-6 h-6", description: "Size of the cursor indicator" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for Next.js applications that require a sense of mystery or progressive disclosure. This production-ready component is perfect for enterprise-ready UIs, creative portfolios, or SaaS landing pages where you want to guide the user's focus using a flashlight-style interaction.",
        bestPractices: "Optimizing for performance in large-scale applications is key; ensure the `spotlightSize` is tailored to the content length. Maintain consistent spacing within your design system by using the `className` prop for layout adjustments. Follow React best practices by memoizing the text content if it updates frequently to avoid unnecessary re-renders during mouse movement.",
        whyMatters: "Modern UI development often requires unique ways to present information. This reusable React component offers a sophisticated masking technique that adds semantic authority to your project, proving that your real-world application architecture can handle complex visual effects with ease.",
        faqs: [
            { question: "Does this component work on mobile touch devices?", answer: "Yes, the component is designed to respond to both mouse move and touch move events, ensuring a consistent experience across responsive layouts." },
            { question: "Can I change the shape of the spotlight?", answer: "The current implementation focuses on a circular spotlight for a classic flashlight effect, but the 'spotlightSize' can be adjusted to change its scale." },
            { question: "Is this accessible for screen readers?", answer: "Absolutely. The underlying text is always present in the DOM, ensuring that accessibility compliance and ARIA support are maintained for SEO and assistive technologies." }
        ],
    },
    {
        id: "vertical-loop",
        name: "Vertical Loop",
        description: "Seamless vertical carousel of words with smooth looping animation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "loop", "carousel", "vertical"],
        previewUrl: "/Animations&Motion/TextAnimations/VerticalLoop",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "words", type: "string[]", default: "[\"DREAM\", \"BUILD\", \"CREATE\", \"SHIP\", \"REPEAT\"]", description: "Array of words to loop" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textSize", type: "string", default: "text-7xl md:text-9xl", description: "Size of the text" },
            { name: "gradientFrom", type: "string", default: "from-purple-400", description: "Gradient start color class" },
            { name: "gradientTo", type: "string", default: "to-pink-600", description: "Gradient end color class" },
            { name: "animationDuration", type: "number", default: "4", description: "Animation duration in seconds" },
            { name: "containerHeight", type: "string", default: "h-[1.2em]", description: "Height of the container" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Use this React component when building hero sections, testimonial blocks, or feature lists that need to showcase multiple rotating keywords. Perfect for SaaS dashboard UIs and startup landing pages that want to highlight variety and benefits in a compact, vertical space.",
        bestPractices: "Maintain scalable component architecture by passing an array of strings that are concise. To follow React best practices, ensure `animationDuration` is set to a readable speed (typically 3-5 seconds). Optimize for performance by limiting the number of words in the loop to under 10 for the smoothest framerate on lower-end devices.",
        whyMatters: "Dynamic content is the heart of modern frontend development. This customizable UI component allows developers to pack multiple messages into a single line, maximizing SEO real estate and keeping the user's attention focused on key value propositions within a production-level application.",
        faqs: [
            { question: "Is the loop truly infinite?", answer: "Yes, the component uses Framer Motion's transition settings to create a seamless, non-stop vertical carousel that restarts after the last word." },
            { question: "Can I use custom gradients for the text?", answer: "Yes, you can customize the colors using the `gradientFrom` and `gradientTo` props to align with your brand's color palette." },
            { question: "Does it support different font weights?", answer: "Yes, you can pass any Tailwind font-weight class via the `className` or `textSize` props to match your design system." }
        ],
    },
    {
        id: "accordion-text",
        name: "Accordion Text",
        description: "Characters expand vertically on hover with rotation and scale effects.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "accordion", "hover", "expand"],
        previewUrl: "/Animations&Motion/TextAnimations/AccordionText",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "EXPANSION", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-zinc-300", description: "Color of the text" },
            { name: "hoverColor", type: "string", default: "#fff", description: "Color on hover" },
            { name: "textSize", type: "string", default: "text-8xl md:text-9xl", description: "Size of the text" },
            { name: "containerHeight", type: "string", default: "h-[120px]", description: "Height of the container" },
            { name: "scaleY", type: "number", default: "1.2", description: "Vertical scale on hover" },
            { name: "margin", type: "string", default: "0 10px", description: "Margin on hover" },
            { name: "rotation", type: "number", default: "5", description: "Rotation angle in degrees" },
            { name: "springStiffness", type: "number", default: "300", description: "Spring animation stiffness" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This animated UI component is ideal for playful SaaS landing pages, gaming interfaces, or creative portfolios. Best suited for mobile app interfaces built with React Native (web-compatible) or Next.js sites where you want to add a tactile, bouncy feel to your text elements on hover.",
        bestPractices: "Ensure accessibility compliance (ARIA support) by not relying solely on the hover state for meaning. Follow React best practices by tuning the `springStiffness` and `springDamping` to match your site's overall animation curve. Maintain consistent spacing within your design system by accounting for the extra height the accordion effect might consume.",
        whyMatters: "Building scalable design systems requires components that feel alive. This reusable React component demonstrates how custom physics-based animations can elevate the user experience, making your real-world application architecture feel more premium and well-crafted.",
        faqs: [
            { question: "Can I adjust the hover rotation?", answer: "Yes, the `rotation` prop allows you to set the specific angle each character tilts when hovered." },
            { question: "Is the spring animation customizable?", answer: "Absolutely. You have full control over stiffness and damping to make the effect either very bouncy or more subtle." },
            { question: "Does it work with multi-line text?", answer: "This component is optimized for single-line headings or labels to maintain the accordion effect's visual integrity." }
        ],
    },
    {
        id: "flag-wave",
        name: "Flag Wave",
        description: "Characters animate in wave motion creating a flag-like undulation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "wave", "flag", "undulation"],
        previewUrl: "/Animations&Motion/TextAnimations/FlagWave",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "UNDULATION", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-blue-400", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "waveAmplitude", type: "number", default: "20", description: "Amplitude of the wave motion" },
            { name: "animationDuration", type: "number", default: "1.5", description: "Animation duration in seconds" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This customizable UI component is great for nautical themes, creative agencies, or any project that wants to convey a sense of flow and rhythm. Use this React component when building intro sections or dividers in modern web applications that benefit from constant, subtle motion.",
        bestPractices: "Optimize for performance in large-scale applications by being mindful of the number of characters, as each one is animated independently. Maintain scalable component architecture by using the `delayMultiplier` to create a natural wave progression. Follow React best practices by ensuring the `waveAmplitude` doesn't cause text to overlap with other UI elements on small screens.",
        whyMatters: "In the world of real-world application architecture, motion design is a powerful communicative tool. This production-ready component helps developers implement complex wave physics without writing low-level code, fitting perfectly into modern frontend development workflows.",
        faqs: [
            { question: "Can I change the speed of the wave?", answer: "Yes, the `animationDuration` prop controls how fast the wave cycles through the text." },
            { question: "Is the wave effect responsive?", answer: "Yes, the component uses relative units and responsive classes to ensure it looks great on all screen sizes." },
            { question: "Can I disable the animation if needed?", answer: "You can set the `waveAmplitude` to 0 or use a conditional prop to stop the motion based on user preferences (e.g., prefers-reduced-motion)." }
        ],
    },
    {
        id: "glitch-layers",
        name: "Glitch Layers",
        description: "RGB chromatic aberration layers create glitch effect on hover.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "glitch", "rgb", "chromatic"],
        previewUrl: "/Animations&Motion/TextAnimations/GlitchLayers",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "GLITCH", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "baseTextColor", type: "string", default: "text-white", description: "Base color of the text" },
            { name: "layer1Color", type: "string", default: "text-red-500", description: "Color of the first glitch layer" },
            { name: "layer2Color", type: "string", default: "text-cyan-500", description: "Color of the second glitch layer" },
            { name: "textSize", type: "string", default: "text-9xl", description: "Size of the text" },
            { name: "glitchAmplitude", type: "number", default: "5", description: "Amplitude of glitch movement" },
            { name: "animationDuration", type: "number", default: "0.2", description: "Animation duration in seconds" },
            { name: "repeatDelay1", type: "number", default: "0.1", description: "Repeat delay for first layer" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This production-ready React UI component is ideal for gaming sites, tech brands, and modern web applications with a 'brutalist' or 'cyberpunk' aesthetic. Use this React component when building interactive headers or landing page titles that need an edgy, high-energy feel.",
        bestPractices: "Follow React best practices by ensuring the glitch intensity doesn't overwhelm the content's legibility. Maintain scalable component architecture by using the `layer1Color` and `layer2Color` props to stay within your design system's color palette. Optimize for performance by triggering the animation only on hover to reduce continuous GPU load.",
        whyMatters: "In modern frontend development, creative styling like chromatic aberration can define a site's personality. This animated UI component offers a complex visual effect that is easy to implement into production-level applications without sacrificing code quality or real-world application architecture.",
        faqs: [
            { question: "Is the glitch effect performance-heavy?", answer: "The effect uses CSS transforms and Framer Motion's hardware-accelerated animations, making it very performant for modern browsers." },
            { question: "Can I customize the glitch colors?", answer: "Yes, you can define the colors for both glitch layers to match your brand's RGB or CMYK styling." },
            { question: "Does it work with any font size?", answer: "Yes, the component is fully responsive and supports any Tailwind font-size class via the `textSize` prop." }
        ],
    },
    {
        id: "masked-reveal",
        name: "Masked Reveal",
        description: "Staggered word reveal with 3D rotation and gradient fade.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "mask", "stagger", "3d"],
        previewUrl: "/Animations&Motion/TextAnimations/MaskedReveal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Orchestrated Chaos", description: "Text to display" },
            { name: "wordGap", type: "string", default: "gap-4", description: "Gap between words" },
            { name: "fontSize", type: "string", default: "text-6xl md:text-8xl", description: "Font size of the text" },
            { name: "fontWeight", type: "string", default: "font-bold", description: "Font weight of the text" },
            { name: "tracking", type: "string", default: "tracking-tighter", description: "Letter spacing" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "gradientFrom", type: "string", default: "from-zinc-100", description: "Gradient start color class" },
            { name: "gradientTo", type: "string", default: "to-zinc-500", description: "Gradient end color class" },
            { name: "staggerChildrenDelay", type: "number", default: "0.12", description: "Delay between children" },
            { name: "childDelayMultiplier", type: "number", default: "0.04", description: "Delay multiplier per child" },
            { name: "springDamping", type: "number", default: "12", description: "Spring animation damping" },
            { name: "springStiffness", type: "number", default: "100", description: "Spring animation stiffness" },
            { name: "initialY", type: "number", default: "50", description: "Initial Y position" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for enterprise-ready UI and SaaS dashboard UIs that require a sophisticated, orchestrated entrance for text content. Use this React component when building hero sections or section introductions where you want to impress the user with high-end, staggered entrance animations.",
        bestPractices: "Maintain scalable component architecture by using the `staggerChildrenDelay` to create a smooth, logical reading flow. To follow React best practices, ensure the `initialY` and `initialRotateX` values are subtle enough to remain professional. Optimize for performance in large-scale applications by only triggering the reveal when the component enters the viewport.",
        whyMatters: "A well-executed reveal animation signals quality in modern UI development. This reusable React component provides a production-level implementation of complex 3D text transitions, helping developers build more immersive real-world application architecture with ease.",
        faqs: [
            { question: "Can I stagger by character instead of by word?", answer: "The current implementation staggers by word for better legibility, but it can be easily adapted for character-level control by splitting the text differently." },
            { question: "Is this component screen reader friendly?", answer: "Yes, it uses semantic HTML structure, ensuring that the full text remains accessible to assistive technologies while being visually transformed." },
            { question: "Does it support gradient text?", answer: "Yes, the component includes `gradientFrom` and `gradientTo` props specifically for creating beautiful gradient reveal effects." }
        ],
    },
    {
        id: "perspective-hover",
        name: "Perspective Hover",
        description: "3D perspective tilt effect on hover with depth layers.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "perspective", "3d", "hover"],
        previewUrl: "/Animations&Motion/TextAnimations/PerspectiveHover",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Depth", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "perspectiveValue", type: "string", default: "perspective-1000", description: "CSS perspective value" },
            { name: "initialRotateX", type: "number", default: "17.5", description: "Initial X rotation in degrees" },
            { name: "initialRotateY", type: "number", default: "17.5", description: "Initial Y rotation in degrees" },
            { name: "depthTranslateZ1", type: "number", default: "75", description: "Z translation for first depth layer" },
            { name: "depthTranslateZ2", type: "number", default: "150", description: "Z translation for second depth layer" },
            { name: "depthTextColor", type: "string", default: "text-zinc-800", description: "Color of depth text" },
            { name: "frontGradientFrom", type: "string", default: "from-indigo-300", description: "Front gradient start color" },
            { name: "frontGradientVia", type: "string", default: "via-white", description: "Front gradient middle color" },
            { name: "frontGradientTo", type: "string", default: "to-indigo-300", description: "Front gradient end color" },
            { name: "fontSize", type: "string", default: "text-7xl md:text-9xl", description: "Font size of the text" },
            { name: "fontWeight", type: "string", default: "font-black", description: "Font weight of the text" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Perfect for startup landing pages and creative portfolios that want to emphasize depth and dimensionality. This customizable UI component is great for large display text or 'feature' headings where a 3D perspective shift adds a modern, interactive layer to the design system.",
        bestPractices: "Ensure accessibility compliance by keeping the base text readable even when tilted. Maintain consistent spacing within your design system by using the `perspective-1000` class or higher to avoid extreme distortion. Follow React best practices by pairing this with high-contrast colors for the 'depth' layers to enhance the 3D effect.",
        whyMatters: "3D interactions are becoming standard in premium modern frontend development. This animated UI component allows you to add depth to your real-world application architecture using pure CSS and React logic, avoiding the overhead of heavy 3D libraries while still delivering a 'wow' factor.",
        faqs: [
            { question: "How many layers of depth are supported?", answer: "The component supports two distinct depth layers behind the front text for a realistic 3D stack effect." },
            { question: "Can I control the tilt intensity?", answer: "Yes, the `initialRotateX` and `initialRotateY` props let you define the default 'resting' tilt of the component." },
            { question: "Is this component responsive?", answer: "Yes, you can pass different font sizes via the `fontSize` prop for mobile and desktop layout optimization." }
        ],
    },
    {
        id: "velocity-scroll",
        name: "Velocity Scroll",
        description: "Infinite scrolling text that responds to scroll velocity.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "velocity", "scroll", "infinite"],
        previewUrl: "/Animations&Motion/TextAnimations/VelocityScroll",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text1", type: "string", default: "Kinetic Motion", description: "First text to scroll" },
            { name: "text2", type: "string", default: "Scroll Velocity", description: "Second text to scroll" },
            { name: "baseVelocity1", type: "number", default: "-3", description: "Base velocity for first text" },
            { name: "baseVelocity2", type: "number", default: "3", description: "Base velocity for second text" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "spacing", type: "string", default: "space-y-8", description: "Spacing between text elements" },
            { name: "fontSize", type: "string", default: "text-8xl md:text-9xl", description: "Font size of the text" },
            { name: "fontWeight", type: "string", default: "font-black", description: "Font weight of the text" },
            { name: "tracking", type: "string", default: "tracking-tighter", description: "Letter spacing" },
            { name: "textColor", type: "string", default: "text-zinc-300", description: "Color of the text" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for Next.js applications with long scrolling pages, such as blog archives, event listings, or creative brand portfolios. This React component is perfect for making static text feel dynamic and responsive to user behavior in real-time.",
        bestPractices: "Optimize for performance in large-scale applications by using Framer Motion's `useScroll` and `useVelocity` hooks correctly. Maintain scalable component architecture by choosing a reasonable `baseVelocity` that isn't distracting. Follow React best practices by ensuring the infinity loop is efficient and doesn't leak memory on long-lived sessions.",
        whyMatters: "Scroll-based motion is a staple of high-end modern UI development. This production-ready component helps developers build 'kinetic' interfaces that feel alive, adding a layer of polish to your real-world application architecture that users instinctively appreciate.",
        faqs: [
            { question: "Does it support two directions at once?", answer: "Yes, the component is designed with two separate tracks that can move at different base velocities and directions for a layered effect." },
            { question: "Can I put links inside the scrolling text?", answer: "While possible, it is recommended to use this for decorative or non-essential text to ensure a good user experience while the text is in motion." },
            { question: "Is the velocity calculation accurate?", answer: "Yes, the component tracks the actual scroll speed of the user and maps it to the animation's playback rate for a natural feel." }
        ],
    },
    {
        id: "stroke-fill",
        name: "Stroke Fill",
        description: "SVG text animates from stroke to fill with smooth transition.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "svg", "stroke", "fill"],
        previewUrl: "/Animations&Motion/TextAnimations/StrokeFill",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Elegance", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "strokeWidth", type: "number", default: "1.5", description: "Width of the stroke" },
            { name: "strokeColor", type: "string", default: "stroke-zinc-100", description: "Color of the stroke" },
            { name: "fillColor", type: "string", default: "#ffffff", description: "Color of the fill" },
            { name: "fontFamily", type: "string", default: "font-[900]", description: "Font family class" },
            { name: "fontSize", type: "string", default: "text-8xl", description: "Font size of the text" },
            { name: "fontWeight", type: "string", default: "uppercase", description: "Font weight of the text" },
            { name: "tracking", type: "string", default: "tracking-widest", description: "Letter spacing" },
            { name: "animationDuration", type: "number", default: "3", description: "Animation duration in seconds" },
            { name: "fillDelay", type: "number", default: "2", description: "Delay before fill animation" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This production-ready React UI component is excellent for luxury brands, fashion sites, and high-end portfolios. Use this React component when building introduction sequences where you want to emphasize elegant typography and smooth transitions from line-art to solid shapes.",
        bestPractices: "Follow React best practices by using high-quality SVG paths for your text to ensure sharp rendering at any scale. Maintain scalable component architecture by using the `stokeColor` and `fillColor` props to align with your design system. Optimize for performance by triggering the fill animation only after the stroke animation is nearly complete.",
        whyMatters: "Typography refined by animation is a hallmark of modern frontend development. This reusable React component gives developers an easy way to implement complex SVG path animations, enhancing the semantic authority and visual premium of your production-level applications.",
        faqs: [
            { question: "Can I use any font with this component?", answer: "The component dynamically generates SVG paths, so it works best with fonts that have clear, well-defined outlines." },
            { question: "How do I control the timing of the transition?", answer: "You can use the `animationDuration`, `fillDelay`, and `fillDuration` props to fine-tune the exact sequence of the reveal." },
            { question: "Does it support multi-line text?", answer: "This component is best suited for single-word headings or logos to maintain the clarity of the stroke animation." }
        ],
    },
    {
        id: "cipher-text",
        name: "Cipher Text",
        description: "Characters scramble and decode to reveal the final message.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "cipher", "decode", "scramble"],
        previewUrl: "/Animations&Motion/TextAnimations/CipherText",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "targetText", type: "string", default: "ENCRYPTED_DATA", description: "Target text to reveal" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-green-400", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-7xl md:text-9xl", description: "Size of the text" },
            { name: "cyclesPerLetter", type: "number", default: "2", description: "Number of cycles per letter" },
            { name: "shuffleTime", type: "number", default: "50", description: "Time between shuffles in milliseconds" },
            { name: "chars", type: "string", default: "!@#$%^&*():{};|,.<>/?", description: "Characters to use for scrambling" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This customizable UI component is ideal for security dashboards, developer portfolios, and tech-focused SaaS landing pages. Use this React component when building 'loading' states or data visualization titles that require a hacker-style decoding aesthetic.",
        bestPractices: "Maintain scalable component architecture by keeping the `targetText` concise for the best visual impact. Follow React best practices by setting the `shuffleTime` to a value that balances speed with legibility. Optimize for performance by using the `autoScramble` prop thoughtfully to avoid unnecessary background processes.",
        whyMatters: "Decoding animations are a staple of modern frontend development in the tech sector. This reusable React component allows developers to add a layer of complexity to their real-world application architecture, making static data feel like a part of a live, secure system.",
        faqs: [
            { question: "Can I use any character set for scrambling?", answer: "Yes, you can define a custom string of characters via the `chars` prop to match your project's theme (e.g., binary, hex, or symbols)." },
            { question: "How fast can it decode?", answer: "The speed is controlled by the `shuffleTime` and `cyclesPerLetter` props, allowing for near-instant reveals or long-duration teases." },
            { question: "Is it responsive?", answer: "Yes, the component is designed to work across all screen sizes with full responsive text support." }
        ],
    },
    {
        id: "liquid-motion",
        name: "Liquid Motion",
        description: "Gooey filter creates liquid blob animation around text.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "liquid", "gooey", "filter"],
        previewUrl: "/Animations&Motion/TextAnimations/LiquidMotion",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "FLUIDITY", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-white", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "blob1Color", type: "string", default: "bg-indigo-500", description: "Color of the first blob" },
            { name: "blob1Size", type: "string", default: "w-32 h-32", description: "Size of the first blob" },
            { name: "blob2Color", type: "string", default: "bg-purple-500", description: "Color of the second blob" },
            { name: "blob2Size", type: "string", default: "w-24 h-24", description: "Size of the second blob" },
            { name: "blob1Duration", type: "number", default: "5", description: "Animation duration for first blob" },
            { name: "blob2Duration", type: "number", default: "7", description: "Animation duration for second blob" },
            { name: "blurAmount", type: "number", default: "10", description: "Blur amount for the gooey filter" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Ideal for creative agencies, modern web applications, and landing pages that want a fluid, organic feel. This production-ready React UI component is perfect for hero sections where you want to emphasize flexibility and modern UI design through a gooey, liquid-like interaction.",
        bestPractices: "Follow React best practices by ensuring the `blurAmount` is high enough to create the gooey effect but not so high that the text becomes unreadable. Maintain scalable component architecture by using the `blob1Color` and `blob2Color` props to represent your brand palette. Optimize for performance by being careful with SVG filters on mobile devices.",
        whyMatters: "Liquid and organic shapes are a major trend in modern frontend development. This customizable UI component helps developers achieve a high-end visual effect that usually requires complex shaders, fitting easily into any real-world application architecture.",
        faqs: [
            { question: "Does this require any external dependencies?", answer: "No, it uses standard SVG filters and Framer Motion, making it easy to drop into most modern React projects." },
            { question: "Can I add more blobs?", answer: "The current implementation uses two animated blobs, which provides a rich effect without overwhelming the DOM or GPU." },
            { question: "How does the gooey filter work?", answer: "It uses a combination of Gaussian blur and color matrix multiplication to 'melt' the edges of the blobs and text together." }
        ],
    },
    {
        id: "elastic-hovers",
        name: "Elastic Hovers",
        description: "Physics-based vertical stretch on character hover with spring animation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "elastic", "physics", "hover"],
        previewUrl: "/Animations&Motion/TextAnimations/ElasticHovers",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Elastic Physics", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textSize", type: "string", default: "text-8xl", description: "Size of the text" },
            { name: "fontWeight", type: "string", default: "font-thin", description: "Font weight of the text" },
            { name: "defaultColor", type: "string", default: "#e4e4e7", description: "Default color of the text" },
            { name: "hoverColor", type: "string", default: "#fff", description: "Color on hover" },
            { name: "defaultScale", type: "number", default: "1", description: "Default vertical scale" },
            { name: "hoverScale", type: "number", default: "1.5", description: "Vertical scale on hover" },
            { name: "springStiffness", type: "number", default: "200", description: "Spring animation stiffness" },
            { name: "springDamping", type: "number", default: "10", description: "Spring animation damping" },
            { name: "springMass", type: "number", default: "0.5", description: "Spring animation mass" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "This animated UI component is ideal for modern web applications that prioritize micro-interactions. Best suited for SaaS dashboard UIs and startup landing pages where a 'soft' and 'responsive' feel is part of the brand voice. Perfect for navigation links or large interactive headlines.",
        bestPractices: "Maintain consistent spacing within your design system by ensuring the `hoverScale` doesn't cause layout shifts in neighboring elements. Follow React best practices by using the `springMass` prop to fine-tune the 'weight' of the animation. Optimize for performance by limiting the use of `hoverShadow` if rendering many characters at once.",
        whyMatters: "Physics-based motion is a cornerstone of real-world application architecture. This reusable React component demonstrates how subtle vertical stretching can make interfaces feel more tactile and responsive to user input, a key goal in modern frontend development.",
        faqs: [
            { question: "Can I change the direction of the stretch?", answer: "The component is currently focused on vertical elastic physics, which is a popular and effective choice for text interaction." },
            { question: "Is the spring animation smooth?", answer: "Yes, it uses Framer Motion's physical spring solver for a natural and jitter-free animation experience." },
            { question: "Does it work with dark mode?", answer: "Yes, you can easily toggle the `defaultColor` and `hoverColor` props to match your theme." }
        ],
    },
    {
        id: "slot-machine",
        name: "Slot Machine",
        description: "Split-flap display effect with characters flipping into place.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "slot", "flip", "machine"],
        previewUrl: "/Animations&Motion/TextAnimations/SlotMachine",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "JACKPOT", description: "Text to display" },
            { name: "backgroundColor", type: "string", default: "bg-zinc-950", description: "Background color of the component" },
            { name: "textColor", type: "string", default: "text-amber-300", description: "Color of the text" },
            { name: "textSize", type: "string", default: "text-8xl md:text-9xl", description: "Size of the text" },
            { name: "delayMultiplier", type: "number", default: "0.1", description: "Delay multiplier per character" },
            { name: "duration", type: "number", default: "0.8", description: "Animation duration in seconds" },
            { name: "ease", type: "number[]", default: "[0.16, 1, 0.3, 1]", description: "Easing function values" },
            { name: "className", type: "string", default: "", description: "Additional CSS classes" },
        ],
        whenToUse: "Use this React component when building dashboards, countdowns, or gaming interfaces that need a sense of anticipation and mechanical motion. Perfect for enterprise-ready UI and SaaS landing pages where numerical or text-based reveals need a premium 'split-flap' or slot machine feel.",
        bestPractices: "Optimize for performance in large-scale applications by being mindful of the `duration` prop; too short may look like a glitch, while too long might delay the core message. Maintain scalable component architecture by using the `oldCharColor` to provide a clear contrast during the transition. Follow React best practices by ensuring the easing function matches your site's physical motion style.",
        whyMatters: "Mechanical-inspired UI elements add a distinct character to modern frontend development. This production-ready component provides a robust implementation of the split-flap effect, essential for developers building complex real-world application architecture with a focus on details.",
        faqs: [
            { question: "Can I use this for a number counter?", answer: "Yes, it works perfectly for both text and numbers, making it a great choice for statistics or price displays." },
            { question: "Is the flipping animation customizable?", answer: "Yes, you can adjust the `ease` and `duration` props to make the 'flap' feel heavier or more snappy." },
            { question: "How does it handle different string lengths?", answer: "The component animates each character independently, so it gracefully handles any text you pass to it." }
        ],
    },
];

