import { getCode } from "../getCode";
import { Component } from "../components-data";

export const textAnimationComponentsMetadata: Component[] = [
    {
        id: "magnetic-hover",
        name: "Magnetic Hover",
        description: "Variable font weight responds to mouse proximity creating magnetic effect.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "magnetic", "hover", "interactive"],
        previewUrl: "/Animations&Motion/TextAnimations/MagneticHover",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "MAGNETIC", description: "Text to display" },
            { name: "color", type: "string", default: "#ffffff", description: "Active character color when near cursor" },
        ],
        whenToUse: "This production-ready React UI component is ideal for SaaS dashboards, startup landing pages, and modern web applications where interactive typography is a priority. Use this React component when building high-end brand experiences that require subtle yet engaging motion effects for headings or hero sections.",
        bestPractices: "Follow React best practices by pairing this component with variable fonts that support weight axes. Maintain scalable component architecture by utilizing short, uppercase words. Optimize for performance by using hardware-accelerated transforms on individual characters.",
        whyMatters: "In modern frontend development, micro-interactions are what separate premium products from basic clones. This animated UI component provides a bridge between static content and immersive user experiences.",
        faqs: [
            { question: "Is this component optimized for Next.js SSR?", answer: "Yes, it is fully compatible with Next.js and supports server-side rendering while ensuring smooth client-side hydration for animations." },
            { question: "Can I use any font with this component?", answer: "While it works with any font, it is best suited for variable fonts that support a range of weights." },
            { question: "Does this component support dark mode?", answer: "Yes, you can customize the color prop to match your application's dark and light themes." }
        ],
    },
    {
        id: "vertical-loop",
        name: "Vertical Loop",
        description: "Seamless vertical carousel of words with smooth looping animation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "loop", "carousel", "vertical"],
        previewUrl: "/Animations&Motion/TextAnimations/VerticalLoop",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "words", type: "string[]", default: "[\"DREAM\", \"BUILD\", \"CREATE\", \"SHIP\", \"REPEAT\"]", description: "Array of words to loop through" },
            { name: "duration", type: "number", default: "4", description: "Duration in seconds for each word" },
        ],
        whenToUse: "Use this React component when building hero sections, testimonial blocks, or feature lists that need to showcase multiple rotating keywords. Perfect for SaaS homepages that want to highlight multiple value propositions in a compact space.",
        bestPractices: "Maintain scalable component architecture by passing concise, similar-length words. Limit the array to 3-7 words for the smoothest looping experience.",
        whyMatters: "Dynamic content is the heart of modern frontend development. This customizable UI component allows developers to pack multiple messages into a single line, keeping the user's attention focused on key value propositions.",
        faqs: [
            { question: "Is the loop truly infinite?", answer: "Yes, the component uses Framer Motion's transition settings to create a seamless, non-stop vertical carousel." },
            { question: "Does it support different font weights?", answer: "Yes, you can pass any Tailwind font-weight class via the className prop to match your design system." },
            { question: "How many words can I include?", answer: "Optimized for 3-7 words. Too many words can make the loop feel too slow." }
        ],
    },
    {
        id: "flag-wave",
        name: "Flag Wave",
        description: "Characters animate in wave motion creating a flag-like undulation.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "wave", "flag", "undulation"],
        previewUrl: "/Animations&Motion/TextAnimations/FlagWave",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "UNDULATION", description: "Text to display" },
            { name: "color", type: "string", default: "#60a5fa", description: "Color of the text" },
        ],
        whenToUse: "Great for titles that need an organic, rhythmic animation. Works well for lifestyle, travel, or creative sites where visual flow is important.",
        bestPractices: "Use uppercase short words for the strongest visual impact. Keep the text concise to prevent line wrapping during animation.",
        whyMatters: "Fluid wave motion adds visual rhythm that draws the eye naturally across your headline, creating organic energy without heavy GPU cost.",
        faqs: [
            { question: "Does it work with special characters?", answer: "Yes, every character including spaces and symbols is animated independently." },
            { question: "Is the wave speed adjustable?", answer: "The wave timing is consistent but works well across all font sizes." },
            { question: "Can I use it for multiple lines?", answer: "It is recommended per-line to maintain the individual character wave offsets." }
        ],
    },
    {
        id: "masked-reveal",
        name: "Masked Reveal",
        description: "Staggered word reveal with 3D rotation and gradient fade.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "mask", "stagger", "3d"],
        previewUrl: "/Animations&Motion/TextAnimations/MaskedReveal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Orchestrated Chaos", description: "Text to reveal" },
            { name: "stagger", type: "number", default: "0.12", description: "Delay in seconds between each word" },
        ],
        whenToUse: "Perfect for elegant brand introductions, minimalist landing pages, and cinematic web experiences where you want text to appear with intentional, orchestrated motion.",
        bestPractices: "Use with multi-word phrases for maximum stagger impact. Works best with large, bold font sizes. Keep phrases concise for visual elegance.",
        whyMatters: "Orchestrated reveals are a staple of premium UI design, adding a layer of polish that distinguishes a brand experience from a basic page.",
        faqs: [
            { question: "Can I reveal character by character?", answer: "Currently word-based for best narrative flow, but the logic can be adapted for individual characters." },
            { question: "Is the 3D rotation mandatory?", answer: "No, setting initialRotateX to 0 gives a simple vertical slide reveal." },
            { question: "Does it support custom fonts?", answer: "Yes, it fully supports all global typography styles." }
        ],
    },
    {
        id: "perspective-hover",
        name: "Perspective Hover",
        description: "3D perspective tilt effect on hover with depth layers.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "perspective", "3d", "hover"],
        previewUrl: "/Animations&Motion/TextAnimations/PerspectiveHover",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Depth", description: "Text to display" },
            { name: "maxRotation", type: "number", default: "17.5", description: "Maximum rotation angle in degrees for the tilt effect" },
        ],
        whenToUse: "Ideal for artistic portfolios, luxury brands, and interactive apps that want to emphasize depth and dimension in their hero section.",
        bestPractices: "Keep maxRotation under 25° to avoid extreme distortion. Works best as a single, short, bold word with high-contrast colors.",
        whyMatters: "Parallax depth adds sophistication and interactivity that static text simply cannot match, creating a holographic feel.",
        faqs: [
            { question: "Does it follow the mouse or scroll?", answer: "Mouse-based for a reactive, holographic feel on hover." },
            { question: "How many depth layers can I add?", answer: "Optimized for 2-3 layers for the best performance and visual effect." },
            { question: "Can I use different colors for the depth layers?", answer: "Yes, the depth color can be customized to create shadows or neon glow effects." }
        ],
    },
    {
        id: "velocity-scroll",
        name: "Velocity Scroll",
        description: "Infinite scrolling text that responds to scroll velocity.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "velocity", "scroll", "infinite"],
        previewUrl: "/Animations&Motion/TextAnimations/VelocityScroll",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "texts", type: "[string, string]", default: "[\"Kinetic Motion\", \"Scroll Velocity\"]", description: "Two text strings for the top and bottom marquee rows" },
            { name: "baseVelocity", type: "number", default: "3", description: "Base scroll speed" },
        ],
        whenToUse: "Perfect for news tickers, event announcements, and dynamic hero sections that respond to user scroll behavior in a kinetic way.",
        bestPractices: "Keep baseVelocity between 2-5 for comfortable reading speed. Use uppercase bold text for maximum visual impact.",
        whyMatters: "Velocity-based interaction makes the site feel physically responsive to user behavior, adding energy and forward momentum to the experience.",
        faqs: [
            { question: "Can I reverse the scroll direction?", answer: "Yes, using a negative baseVelocity reverses the direction." },
            { question: "How does it handle different screen sizes?", answer: "Uses percentage-based wrapping for seamless loops across all screen widths." },
            { question: "Can I use multiple lines?", answer: "Yes, stack multiple instances with different velocities for a complex kinetic typography effect." }
        ],
    },
    {
        id: "stroke-fill",
        name: "Stroke Fill",
        description: "SVG text animates from stroke to fill with smooth transition.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "svg", "stroke", "fill"],
        previewUrl: "/Animations&Motion/TextAnimations/StrokeFill",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "text", type: "string", default: "Elegance", description: "Text to animate" },
            { name: "duration", type: "number", default: "3", description: "Total animation duration in seconds" },
        ],
        whenToUse: "Excellent for luxury brand logos, cinematic intros, and high-impact reveals where text starts as a delicate outline and fills into solid form.",
        bestPractices: "Use short single-word or two-word phrases. Larger font sizes make the stroke animation more legible and impressive.",
        whyMatters: "SVG stroke animations are a classic mark of quality UI — they create anticipation and add narrative structure to your content reveal.",
        faqs: [
            { question: "Does it work with any font?", answer: "Yes, any web font works as the SVG paths are generated from the rendered text." },
            { question: "Is the stroke thickness adjustable?", answer: "The strokeWidth is set to 1.5 for a delicate outline. You can adjust it in the component source." },
            { question: "Can I trigger the fill on hover?", answer: "The current implementation is time-based; hover triggering requires a small state change." }
        ],
    },
    {
        id: "shimmer-text",
        name: "Shimmer Text",
        description: "A bright glint sweeps continuously across bold text like light reflecting off metal.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "shimmer", "glint", "gradient"],
        previewUrl: "/Animations&Motion/TextAnimations/ShimmerText",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next"],
        props: [
            { name: "text", type: "string", default: "LUMINOUS", description: "Text to display" },
            { name: "color", type: "string", default: "#e879f9", description: "Base color of the text — the shimmer glint sweeps across this" },
        ],
        whenToUse: "Perfect for luxury brands, loading states, feature callouts, and any headline that needs to feel alive without being distracting or demanding attention.",
        bestPractices: "Use uppercase single bold words for the sharpest glint effect. Any hex color works — the shimmer glint is always white regardless of base color.",
        whyMatters: "A perpetual shimmer communicates premium quality with zero user interaction, adding life to hero sections at no cognitive cost.",
        faqs: [
            { question: "Does this need Framer Motion?", answer: "No — it uses a pure CSS background-position animation, keeping the bundle size minimal." },
            { question: "Can I change the sweep speed?", answer: "Yes, change the animation duration value in the component source (3.5s default)." },
            { question: "Does it work in Safari?", answer: "Yes, both -webkit-background-clip and background-clip are applied for full cross-browser support." }
        ],
    },
    {
        id: "scramble-reveal",
        name: "Scramble Reveal",
        description: "Characters cycle through random symbols before resolving to the final text on viewport entry.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "scramble", "decode", "reveal"],
        previewUrl: "/Animations&Motion/TextAnimations/ScrambleReveal",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next"],
        props: [
            { name: "text", type: "string", default: "UILORA", description: "Final text to reveal after scrambling" },
            { name: "duration", type: "number", default: "1.8", description: "Seconds to complete the full decode from left to right" },
        ],
        whenToUse: "Ideal for tech dashboards, developer tools, security-themed sites, and any headline where you want a moment of intrigue before the message lands.",
        bestPractices: "Use short uppercase words (4-8 chars) for maximum readability during the scramble. Monospace font is applied automatically for stable character widths.",
        whyMatters: "The scramble-to-reveal creates anticipation and reward — chaos resolving into order makes the final word feel earned and memorable.",
        faqs: [
            { question: "Does it replay on scroll?", answer: "No — it fires once via IntersectionObserver when 30% of the element enters the viewport." },
            { question: "Does it need any animation library?", answer: "No — pure React with requestAnimationFrame. Zero additional dependencies." },
            { question: "Can I use lowercase text?", answer: "Yes, though the scramble character set is uppercase — mixed case text shows contrast during the decode phase." }
        ],
    },
    {
        id: "pressure-test",
        name: "Pressure Test",
        description: "Variable font axes shift in real-time based on mouse proximity to each character.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "variable-font", "interactive", "proximity"],
        previewUrl: "/Animations&Motion/TextAnimations/PressureTest",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next"],
        props: [
            { name: "text", type: "string", default: "UILORA", description: "Text to display — each character responds independently to cursor proximity" },
            { name: "className", type: "string", default: "text-white", description: "Tailwind class for text color" },
        ],
        whenToUse: "Perfect for hero sections and interactive brand moments where you want text that feels physically responsive to the user's cursor position.",
        bestPractices: "Use a variable font (Compressa VF loads automatically). Works best with short, uppercase words. Set className to control text color.",
        whyMatters: "Variable font interactivity is a frontier technique that makes typography feel tactile and alive — impossible to achieve with static text or standard animations.",
        faqs: [
            { question: "Does it require a specific font?", answer: "It loads the Compressa VF variable font automatically. You can swap it for any variable font supporting wght, wdth, and ital axes." },
            { question: "Is it mobile-friendly?", answer: "Yes, it supports touchmove events so the proximity effect also works on touch devices." },
            { question: "How is the font loaded?", answer: "An @font-face rule is injected via a style tag at render time, so no additional CSS setup is required." }
        ],
    },
    {
        id: "type-writer",
        name: "TypeWriter",
        description: "Classic typewriter effect cycles through words with a blinking cursor.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "typewriter", "cursor", "cycle"],
        previewUrl: "/Animations&Motion/TextAnimations/TypeWriter",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next"],
        props: [
            { name: "words", type: "string[]", default: "[\"Design.\", \"Build.\", \"Ship.\", \"Scale.\"]", description: "Array of words to cycle through" },
            { name: "typingSpeed", type: "number", default: "80", description: "Milliseconds per character when typing" },
        ],
        whenToUse: "A versatile staple for hero sections, CTAs, and any context where you want to cycle through multiple values or actions dynamically without cluttering the layout.",
        bestPractices: "Keep words short (1-2 words) for the smoothest effect. Use words that share a grammatical structure so they read as a cohesive sentence.",
        whyMatters: "Typewriter effects communicate dynamism and list multiple value propositions in a single headline, maximizing layout efficiency.",
        faqs: [
            { question: "Can I control the delete speed?", answer: "Deleting runs at half the typing speed automatically for a natural feel. This is not configurable via props but can be changed in source." },
            { question: "How long does it pause between words?", answer: "1800ms pause after each word is fully typed before deleting begins." },
            { question: "Does it require any animation library?", answer: "No — it uses only React state and setInterval, keeping the bundle size minimal." }
        ],
    },
    {
        id: "text-morph",
        name: "Text Morph",
        description: "Words blur and cross-fade into each other with smooth AnimatePresence transitions.",
        category: "Animations & Motion",
        installType: "cli",
        tags: ["text", "animation", "morph", "blur", "crossfade"],
        previewUrl: "/Animations&Motion/TextAnimations/TextMorph",
        code: { tsx: "" },
        usageCode: { tsx: "" },
        dependencies: ["next", "framer-motion"],
        props: [
            { name: "words", type: "string[]", default: "[\"Innovative\", \"Scalable\", \"Production-Ready\", \"Beautiful\"]", description: "Array of words to morph between" },
            { name: "duration", type: "number", default: "2.5", description: "Seconds each word is displayed before morphing" },
        ],
        whenToUse: "Great for hero adjective cycling, feature description carousels, and any place a smooth, cinematic word transition adds premium feel to the UI.",
        bestPractices: "Use single adjectives or short phrases of similar character length. Pair with a static prefix/suffix so the changing word creates a full, meaningful sentence.",
        whyMatters: "Blur morphing creates an organic transition that feels designed rather than mechanical — elevating a simple word cycle to a genuinely premium experience.",
        faqs: [
            { question: "How is this different from TypeWriter?", answer: "TextMorph uses blur cross-fades instead of character-by-character typing — more cinematic and less mechanical." },
            { question: "Can I use it for phrases?", answer: "Yes, multi-word phrases work well — keep them short enough to fit on one line for the cleanest appearance." },
            { question: "Does it loop forever?", answer: "Yes, it loops infinitely through the words array using a setInterval that increments the index on modulo." }
        ],
    },
];
